### ISSUE TITLE
Predict_Proba method returns a float32 array, breaking scikit-learn compatibility

### ISSUE THREAD

**Issue by jstammers** [dmlc/xgboost#10004]
I've encountered an issue when trying to use an XGBoost model with the `CalibratedClassifierCV` class from scikit-learn.

From what I can see, this is ultimately due to the fact that `XGBClassifier.predict_proba` method returns an array of `np.float32`, even if my input array contains float64 values.

My issue relates to the fact that the optimiser used by `CalibratedClassifierCV` requires 64-bit floats to work. My input array has float64 values and scikit-learn classifiers that implement `predict_proba` return arrays of float64, so I would expect the same behaviour here. 

The versions I am currently using are:

- xgboost: 2.0.3
- scikit-learn: 1.4.0

And here is an example that reproduces my error
```python
import xgboost as xgb
from sklearn.calibration import CalibratedClassifierCV
from sklearn.naive_bayes import GaussianNB
import pandas as pd
import numpy as np

df = pd.DataFrame(
    {"x": np.random.random(size=100), "y": np.random.choice([0, 1], size=100)}
)

model = xgb.XGBClassifier()

sk_model = GaussianNB()

sk_calibrator = CalibratedClassifierCV(sk_model)

sk_calibrator.fit(df[["x"]], df["y"]) # runs successfully

calibrator = CalibratedClassifierCV(model)

calibrator.fit(df[["x"]], df["y"])
```

with the following traceback

```
Traceback (most recent call last):
  File "~\incorrect_classifier.py", line 21, in <module>
    calibrator.fit(df[["x"]], df["y"])
  File "~\AppData\Local\pypoetry\Cache\virtualenvs\env-vqbIi1FM-py3.10\lib\site-packages\sklearn\base.py", line 1351, in wrapper
    return fit_method(estimator, *args, **kwargs)
  File "~\AppData\Local\pypoetry\Cache\virtualenvs\env-vqbIi1FM-py3.10\lib\site-packages\sklearn\calibration.py", line 403, in fit
    self.calibrated_classifiers_ = parallel(
  File "~\AppData\Local\pypoetry\Cache\virtualenvs\env-vqbIi1FM-py3.10\lib\site-packages\sklearn\utils\parallel.py", line 67, in __call__
    return super().__call__(iterable_with_config)
  File "~\AppData\Local\pypoetry\Cache\virtualenvs\env-vqbIi1FM-py3.10\lib\site-packages\joblib\parallel.py", line 1863, in __call__
    return output if self.return_generator else list(output)
  File "~\AppData\Local\pypoetry\Cache\virtualenvs\env-vqbIi1FM-py3.10\lib\site-packages\joblib\parallel.py", line 1792, in _get_sequential_output
    res = func(*args, **kwargs)
  File "~\AppData\Local\pypoetry\Cache\virtualenvs\env-vqbIi1FM-py3.10\lib\site-packages\sklearn\utils\parallel.py", line 129, in __call__
    return self.function(*args, **kwargs)
  File "~\AppData\Local\pypoetry\Cache\virtualenvs\env-vqbIi1FM-py3.10\lib\site-packages\sklearn\calibration.py", line 616, in _fit_classifier_calibrator_pair
    calibrated_classifier = _fit_calibrator(
  File "~\AppData\Local\pypoetry\Cache\virtualenvs\env-vqbIi1FM-py3.10\lib\site-packages\sklearn\calibration.py", line 663, in _fit_calibrator
    calibrator.fit(this_pred, Y[:, class_idx], sample_weight)
  File "~\AppData\Local\pypoetry\Cache\virtualenvs\env-vqbIi1FM-py3.10\lib\site-packages\sklearn\calibration.py", line 888, in fit
    self.a_, self.b_ = _sigmoid_calibration(X, y, sample_weight)
  File "~\AppData\Local\pypoetry\Cache\virtualenvs\env-vqbIi1FM-py3.10\lib\site-packages\sklearn\calibration.py", line 835, in _sigmoid_calibration
    opt_result = minimize(
  File "~\AppData\Local\pypoetry\Cache\virtualenvs\env-vqbIi1FM-py3.10\lib\site-packages\scipy\optimize\_minimize.py", line 710, in minimize
    res = _minimize_lbfgsb(fun, x0, args, jac, bounds,
  File "~\AppData\Local\pypoetry\Cache\virtualenvs\env-vqbIi1FM-py3.10\lib\site-packages\scipy\optimize\_lbfgsb_py.py", line 307, in _minimize_lbfgsb
    sf = _prepare_scalar_function(fun, x0, jac=jac, args=args, epsilon=eps,
  File "~\AppData\Local\pypoetry\Cache\virtualenvs\env-vqbIi1FM-py3.10\lib\site-packages\scipy\optimize\_optimize.py", line 383, in _prepare_scalar_function
    sf = ScalarFunction(fun, x0, args, grad, hess,
  File "~\AppData\Local\pypoetry\Cache\virtualenvs\env-vqbIi1FM-py3.10\lib\site-packages\scipy\optimize\_differentiable_functions.py", line 158, in __init__
    self._update_fun()
  File "~\AppData\Local\pypoetry\Cache\virtualenvs\env-vqbIi1FM-py3.10\lib\site-packages\scipy\optimize\_differentiable_functions.py", line 251, in _update_fun
    self._update_fun_impl()
  File "~\AppData\Local\pypoetry\Cache\virtualenvs\env-vqbIi1FM-py3.10\lib\site-packages\scipy\optimize\_differentiable_functions.py", line 155, in update_fun
    self.f = fun_wrapped(self.x)
  File "~\AppData\Local\pypoetry\Cache\virtualenvs\env-vqbIi1FM-py3.10\lib\site-packages\scipy\optimize\_differentiable_functions.py", line 137, in fun_wrapped
    fx = fun(np.copy(x), *args)
  File "~\AppData\Local\pypoetry\Cache\virtualenvs\env-vqbIi1FM-py3.10\lib\site-packages\scipy\optimize\_optimize.py", line 77, in __call__
    self._compute_if_needed(x, *args)
  File "~\AppData\Local\pypoetry\Cache\virtualenvs\env-vqbIi1FM-py3.10\lib\site-packages\scipy\optimize\_optimize.py", line 71, in _compute_if_needed
    fg = self.fun(x, *args)
  File "~\AppData\Local\pypoetry\Cache\virtualenvs\env-vqbIi1FM-py3.10\lib\site-packages\sklearn\calibration.py", line 824, in loss_grad
    l, g = bin_loss.loss_gradient(
  File "~\AppData\Local\pypoetry\Cache\virtualenvs\env-vqbIi1FM-py3.10\lib\site-packages\sklearn\_loss\loss.py", line 254, in loss_gradient
    self.closs.loss_gradient(
  File "sklearn\\_loss\\_loss.pyx", line 1784, in sklearn._loss._loss.CyHalfBinomialLoss.loss_gradient  
ValueError: Buffer dtype mismatch, expected 'const double' but got 'float'
```

**Comment by trivialfis** [comment]
Interesting, seems like sklearn update broke its compatibility with f32

**Comment by trivialfis** [comment]
I will open an issue on sklearn tomorrow, and see if we can add a conversion to f64 there.

**Comment by trivialfis** [comment]
Fixed in sklearn.
