### ISSUE TITLE
[jvm-packages]Tests hang while running mvn package on Mac OSX

### ISSUE THREAD

**Issue by enragedginger** [dmlc/xgboost#1019]
When I run `mvn package`, my build hangs while running the Spark tests.

The output of that part of the build looks something like this:
```
Discovery starting.
Discovery completed in 173 milliseconds.
Run starting. Expected test count is: 4
XGBoostSuite:
Using Spark's default log4j profile: org/apache/spark/log4j-defaults.properties
16/03/20 16:53:34 INFO SparkContext: Running Spark version 1.6.1
16/03/20 16:53:34 WARN NativeCodeLoader: Unable to load native-hadoop library for your platform... using builtin-java classes where applicable
16/03/20 16:53:34 INFO SecurityManager: Changing view acls to: hopper
16/03/20 16:53:34 INFO SecurityManager: Changing modify acls to: hopper
16/03/20 16:53:34 INFO SecurityManager: SecurityManager: authentication disabled; ui acls disabled; users with view permissions: Set(hopper); users with modify permissions: Set(hopper)
16/03/20 16:53:35 INFO Utils: Successfully started service 'sparkDriver' on port 49321.
16/03/20 16:53:35 INFO Slf4jLogger: Slf4jLogger started
16/03/20 16:53:35 INFO Remoting: Starting remoting
16/03/20 16:53:36 INFO Remoting: Remoting started; listening on addresses :[akka.tcp://sparkDriverActorSystem@192.168.0.101:49322]
16/03/20 16:53:36 INFO Utils: Successfully started service 'sparkDriverActorSystem' on port 49322.
16/03/20 16:53:36 INFO SparkEnv: Registering MapOutputTracker
16/03/20 16:53:36 INFO SparkEnv: Registering BlockManagerMaster
16/03/20 16:53:36 INFO DiskBlockManager: Created local directory at /private/var/folders/wv/q0dd6znx585dpr1l45yylv940000gn/T/blockmgr-cebae22b-f253-48b8-a14a-3ffe0aa873ce
16/03/20 16:53:36 INFO MemoryStore: MemoryStore started with capacity 2.4 GB
16/03/20 16:53:36 INFO SparkEnv: Registering OutputCommitCoordinator
16/03/20 16:53:36 INFO Utils: Successfully started service 'SparkUI' on port 4040.
16/03/20 16:53:36 INFO SparkUI: Started SparkUI at http://192.168.0.101:4040
16/03/20 16:53:36 INFO Executor: Starting executor ID driver on host localhost
16/03/20 16:53:36 INFO Utils: Successfully started service 'org.apache.spark.network.netty.NettyBlockTransferService' on port 49323.
16/03/20 16:53:36 INFO NettyBlockTransferService: Server created on 49323
16/03/20 16:53:36 INFO BlockManagerMaster: Trying to register BlockManager
16/03/20 16:53:36 INFO BlockManagerMasterEndpoint: Registering block manager localhost:49323 with 2.4 GB RAM, BlockManagerId(driver, localhost, 49323)
16/03/20 16:53:36 INFO BlockManagerMaster: Registered BlockManager
16/03/20 16:53:37 INFO XGBoostSpark: repartitioning training set to 2 partitions
16/03/20 16:53:37 INFO SparkContext: Starting job: count at XGBoostSuite.scala:131
16/03/20 16:53:37 INFO DAGScheduler: Got job 0 (count at XGBoostSuite.scala:131) with 2 output partitions
16/03/20 16:53:37 INFO DAGScheduler: Final stage: ResultStage 0 (count at XGBoostSuite.scala:131)
16/03/20 16:53:37 INFO DAGScheduler: Parents of final stage: List()
16/03/20 16:53:37 INFO DAGScheduler: Missing parents: List()
16/03/20 16:53:37 INFO DAGScheduler: Submitting ResultStage 0 (MapPartitionsRDD[2] at mapPartitions at XGBoost.scala:57), which has no missing parents
16/03/20 16:53:37 INFO MemoryStore: Block broadcast_0 stored as values in memory (estimated size 2.8 KB, free 2.8 KB)
16/03/20 16:53:37 INFO MemoryStore: Block broadcast_0_piece0 stored as bytes in memory (estimated size 1761.0 B, free 4.5 KB)
16/03/20 16:53:37 INFO BlockManagerInfo: Added broadcast_0_piece0 in memory on localhost:49323 (size: 1761.0 B, free: 2.4 GB)
16/03/20 16:53:37 INFO SparkContext: Created broadcast 0 from broadcast at DAGScheduler.scala:1006
16/03/20 16:53:37 INFO DAGScheduler: Submitting 2 missing tasks from ResultStage 0 (MapPartitionsRDD[2] at mapPartitions at XGBoost.scala:57)
16/03/20 16:53:37 INFO TaskSchedulerImpl: Adding task set 0.0 with 2 tasks
16/03/20 16:53:37 WARN TaskSetManager: Stage 0 contains a task of very large size (3379 KB). The maximum recommended task size is 100 KB.
16/03/20 16:53:37 INFO TaskSetManager: Starting task 0.0 in stage 0.0 (TID 0, localhost, partition 0,PROCESS_LOCAL, 3460471 bytes)
16/03/20 16:53:38 INFO TaskSetManager: Starting task 1.0 in stage 0.0 (TID 1, localhost, partition 1,PROCESS_LOCAL, 3461533 bytes)
16/03/20 16:53:38 INFO Executor: Running task 1.0 in stage 0.0 (TID 1)
16/03/20 16:53:38 INFO Executor: Running task 0.0 in stage 0.0 (TID 0)
16/03/20 16:53:38 INFO CacheManager: Partition rdd_2_0 not found, computing it
16/03/20 16:53:38 INFO CacheManager: Partition rdd_2_1 not found, computing it
[16:53:38] src/tree/updater_prune.cc:74: tree pruning end, 1 roots, 4 extra nodes, 0 pruned nodes, max_depth=2
[0]	train-error:0.011974
[16:53:38] src/tree/updater_prune.cc:74: tree pruning end, 1 roots, 4 extra nodes, 0 pruned nodes, max_depth=2
[0]	train-error:0.044840
[16:53:38] src/tree/updater_prune.cc:74: tree pruning end, 1 roots, 4 extra nodes, 0 pruned nodes, max_depth=2
[1]	train-error:0.006141
[16:53:38] src/tree/updater_prune.cc:74: tree pruning end, 1 roots, 4 extra nodes, 0 pruned nodes, max_depth=2
[1]	train-error:0.000307
[16:53:38] src/tree/updater_prune.cc:74: tree pruning end, 1 roots, 4 extra nodes, 0 pruned nodes, max_depth=2
[2]	train-error:0.002456
[16:53:38] src/tree/updater_prune.cc:74: tree pruning end, 1 roots, 4 extra nodes, 0 pruned nodes, max_depth=2
[2]	train-error:0.000307
[16:53:38] src/tree/updater_prune.cc:74: tree pruning end, 1 roots, 6 extra nodes, 0 pruned nodes, max_depth=2
[3]	train-error:0.000000
[16:53:38] src/tree/updater_prune.cc:74: tree pruning end, 1 roots, 4 extra nodes, 0 pruned nodes, max_depth=2
[3]	train-error:0.000307
[16:53:38] src/tree/updater_prune.cc:74: tree pruning end, 1 roots, 4 extra nodes, 0 pruned nodes, max_depth=2
[16:53:38] src/tree/updater_prune.cc:74: tree pruning end, 1 roots, 6 extra nodes, 0 pruned nodes, max_depth=2
16/03/20 16:53:38 INFO MemoryStore: Block rdd_2_1 stored as values in memory (estimated size 64.0 B, free 4.6 KB)
16/03/20 16:53:38 INFO BlockManagerInfo: Added rdd_2_1 in memory on localhost:49323 (size: 64.0 B, free: 2.4 GB)
16/03/20 16:53:38 INFO MemoryStore: Block rdd_2_0 stored as values in memory (estimated size 64.0 B, free 4.6 KB)
16/03/20 16:53:38 INFO BlockManagerInfo: Added rdd_2_0 in memory on localhost:49323 (size: 64.0 B, free: 2.4 GB)
16/03/20 16:53:38 INFO Executor: Finished task 1.0 in stage 0.0 (TID 1). 1567 bytes result sent to driver
16/03/20 16:53:38 INFO Executor: Finished task 0.0 in stage 0.0 (TID 0). 1567 bytes result sent to driver
16/03/20 16:53:38 INFO TaskSetManager: Finished task 1.0 in stage 0.0 (TID 1) in 291 ms on localhost (1/2)
16/03/20 16:53:38 INFO TaskSetManager: Finished task 0.0 in stage 0.0 (TID 0) in 372 ms on localhost (2/2)
16/03/20 16:53:38 INFO TaskSchedulerImpl: Removed TaskSet 0.0, whose tasks have all completed, from pool 
16/03/20 16:53:38 INFO DAGScheduler: ResultStage 0 (count at XGBoostSuite.scala:131) finished in 0.385 s
16/03/20 16:53:38 INFO DAGScheduler: Job 0 finished: count at XGBoostSuite.scala:131, took 0.693864 s
16/03/20 16:53:38 INFO SparkContext: Starting job: collect at XGBoostSuite.scala:133
16/03/20 16:53:38 INFO DAGScheduler: Got job 1 (collect at XGBoostSuite.scala:133) with 2 output partitions
16/03/20 16:53:38 INFO DAGScheduler: Final stage: ResultStage 1 (collect at XGBoostSuite.scala:133)
16/03/20 16:53:38 INFO DAGScheduler: Parents of final stage: List()
16/03/20 16:53:38 INFO DAGScheduler: Missing parents: List()
16/03/20 16:53:38 INFO DAGScheduler: Submitting ResultStage 1 (MapPartitionsRDD[2] at mapPartitions at XGBoost.scala:57), which has no missing parents
16/03/20 16:53:38 INFO MemoryStore: Block broadcast_1 stored as values in memory (estimated size 2.9 KB, free 7.5 KB)
16/03/20 16:53:38 INFO MemoryStore: Block broadcast_1_piece0 stored as bytes in memory (estimated size 1791.0 B, free 9.3 KB)
16/03/20 16:53:38 INFO BlockManagerInfo: Added broadcast_1_piece0 in memory on localhost:49323 (size: 1791.0 B, free: 2.4 GB)
16/03/20 16:53:38 INFO SparkContext: Created broadcast 1 from broadcast at DAGScheduler.scala:1006
16/03/20 16:53:38 INFO DAGScheduler: Submitting 2 missing tasks from ResultStage 1 (MapPartitionsRDD[2] at mapPartitions at XGBoost.scala:57)
16/03/20 16:53:38 INFO TaskSchedulerImpl: Adding task set 1.0 with 2 tasks
16/03/20 16:53:38 INFO BlockManagerInfo: Removed broadcast_0_piece0 on localhost:49323 in memory (size: 1761.0 B, free: 2.4 GB)
16/03/20 16:53:38 INFO ContextCleaner: Cleaned accumulator 1
16/03/20 16:53:38 WARN TaskSetManager: Stage 1 contains a task of very large size (3379 KB). The maximum recommended task size is 100 KB.
16/03/20 16:53:38 INFO TaskSetManager: Starting task 0.0 in stage 1.0 (TID 2, localhost, partition 0,PROCESS_LOCAL, 3460471 bytes)
16/03/20 16:53:38 INFO TaskSetManager: Starting task 1.0 in stage 1.0 (TID 3, localhost, partition 1,PROCESS_LOCAL, 3461533 bytes)
16/03/20 16:53:38 INFO Executor: Running task 0.0 in stage 1.0 (TID 2)
16/03/20 16:53:38 INFO Executor: Running task 1.0 in stage 1.0 (TID 3)
16/03/20 16:53:38 INFO BlockManager: Found block rdd_2_1 locally
16/03/20 16:53:38 INFO BlockManager: Found block rdd_2_0 locally
16/03/20 16:53:38 INFO Executor: Finished task 0.0 in stage 1.0 (TID 2). 4310 bytes result sent to driver
16/03/20 16:53:38 INFO Executor: Finished task 1.0 in stage 1.0 (TID 3). 4310 bytes result sent to driver
16/03/20 16:53:38 INFO TaskSetManager: Finished task 0.0 in stage 1.0 (TID 2) in 87 ms on localhost (1/2)
16/03/20 16:53:38 INFO TaskSetManager: Finished task 1.0 in stage 1.0 (TID 3) in 54 ms on localhost (2/2)
16/03/20 16:53:38 INFO TaskSchedulerImpl: Removed TaskSet 1.0, whose tasks have all completed, from pool 
16/03/20 16:53:38 INFO DAGScheduler: ResultStage 1 (collect at XGBoostSuite.scala:133) finished in 0.087 s
16/03/20 16:53:38 INFO DAGScheduler: Job 1 finished: collect at XGBoostSuite.scala:133, took 0.116566 s
- build RDD containing boosters with the specified worker number
16/03/20 16:53:38 INFO SparkUI: Stopped Spark web UI at http://192.168.0.101:4040
16/03/20 16:53:38 INFO MapOutputTrackerMasterEndpoint: MapOutputTrackerMasterEndpoint stopped!
16/03/20 16:53:38 INFO MemoryStore: MemoryStore cleared
16/03/20 16:53:38 INFO BlockManager: BlockManager stopped
16/03/20 16:53:38 INFO BlockManagerMaster: BlockManagerMaster stopped
16/03/20 16:53:38 INFO OutputCommitCoordinator$OutputCommitCoordinatorEndpoint: OutputCommitCoordinator stopped!
16/03/20 16:53:38 INFO SparkContext: Successfully stopped SparkContext
16/03/20 16:53:38 INFO SparkContext: Running Spark version 1.6.1
16/03/20 16:53:38 INFO RemoteActorRefProvider$RemotingTerminator: Shutting down remote daemon.
16/03/20 16:53:38 INFO RemoteActorRefProvider$RemotingTerminator: Remote daemon shut down; proceeding with flushing remote transports.
16/03/20 16:53:38 INFO SecurityManager: Changing view acls to: hopper
16/03/20 16:53:38 INFO SecurityManager: Changing modify acls to: hopper
16/03/20 16:53:38 INFO SecurityManager: SecurityManager: authentication disabled; ui acls disabled; users with view permissions: Set(hopper); users with modify permissions: Set(hopper)
16/03/20 16:53:38 INFO Utils: Successfully started service 'sparkDriver' on port 49324.
16/03/20 16:53:38 INFO RemoteActorRefProvider$RemotingTerminator: Remoting shut down.
16/03/20 16:53:38 INFO Slf4jLogger: Slf4jLogger started
16/03/20 16:53:38 INFO Remoting: Starting remoting
16/03/20 16:53:38 INFO Remoting: Remoting started; listening on addresses :[akka.tcp://sparkDriverActorSystem@localhost:49325]
16/03/20 16:53:38 INFO Utils: Successfully started service 'sparkDriverActorSystem' on port 49325.
16/03/20 16:53:38 INFO SparkEnv: Registering MapOutputTracker
16/03/20 16:53:38 INFO SparkEnv: Registering BlockManagerMaster
16/03/20 16:53:38 INFO DiskBlockManager: Created local directory at /private/var/folders/wv/q0dd6znx585dpr1l45yylv940000gn/T/blockmgr-cdbe3727-d27e-47d4-8f1d-f7ee0f837cc8
16/03/20 16:53:38 INFO MemoryStore: MemoryStore started with capacity 2.4 GB
16/03/20 16:53:38 INFO SparkEnv: Registering OutputCommitCoordinator
16/03/20 16:53:38 INFO Utils: Successfully started service 'SparkUI' on port 4040.
16/03/20 16:53:38 INFO SparkUI: Started SparkUI at http://localhost:4040
16/03/20 16:53:38 INFO Executor: Starting executor ID driver on host localhost
16/03/20 16:53:38 INFO Utils: Successfully started service 'org.apache.spark.network.netty.NettyBlockTransferService' on port 49326.
16/03/20 16:53:38 INFO NettyBlockTransferService: Server created on 49326
16/03/20 16:53:38 INFO BlockManagerMaster: Trying to register BlockManager
16/03/20 16:53:38 INFO BlockManagerMasterEndpoint: Registering block manager localhost:49326 with 2.4 GB RAM, BlockManagerId(driver, localhost, 49326)
16/03/20 16:53:38 INFO BlockManagerMaster: Registered BlockManager
Tracker started, with env={DMLC_NUM_SERVER=0, DMLC_TRACKER_URI=192.168.0.101, DMLC_TRACKER_PORT=9091, DMLC_NUM_WORKER=4}
16/03/20 16:53:39 INFO RabitTracker$TrackerProcessLogger: 2016-03-20 16:53:39,729 INFO start listen on 192.168.0.101:9091
16/03/20 16:53:39 INFO SparkContext: Starting job: foreachPartition at XGBoost.scala:104
16/03/20 16:53:39 INFO DAGScheduler: Got job 0 (foreachPartition at XGBoost.scala:104) with 4 output partitions
16/03/20 16:53:39 INFO DAGScheduler: Final stage: ResultStage 0 (foreachPartition at XGBoost.scala:104)
16/03/20 16:53:39 INFO DAGScheduler: Parents of final stage: List()
16/03/20 16:53:39 INFO DAGScheduler: Missing parents: List()
16/03/20 16:53:39 INFO DAGScheduler: Submitting ResultStage 0 (MapPartitionsRDD[1] at mapPartitions at XGBoost.scala:57), which has no missing parents
16/03/20 16:53:39 INFO MemoryStore: Block broadcast_0 stored as values in memory (estimated size 4.4 KB, free 4.4 KB)
16/03/20 16:53:39 INFO MemoryStore: Block broadcast_0_piece0 stored as bytes in memory (estimated size 2.2 KB, free 6.7 KB)
16/03/20 16:53:39 INFO BlockManagerInfo: Added broadcast_0_piece0 in memory on localhost:49326 (size: 2.2 KB, free: 2.4 GB)
16/03/20 16:53:39 INFO SparkContext: Created broadcast 0 from broadcast at DAGScheduler.scala:1006
16/03/20 16:53:39 INFO DAGScheduler: Submitting 4 missing tasks from ResultStage 0 (MapPartitionsRDD[1] at mapPartitions at XGBoost.scala:57)
16/03/20 16:53:39 INFO TaskSchedulerImpl: Adding task set 0.0 with 4 tasks
16/03/20 16:53:39 WARN TaskSetManager: Stage 0 contains a task of very large size (1690 KB). The maximum recommended task size is 100 KB.
16/03/20 16:53:39 INFO TaskSetManager: Starting task 0.0 in stage 0.0 (TID 0, localhost, partition 0,PROCESS_LOCAL, 1731242 bytes)
16/03/20 16:53:39 INFO TaskSetManager: Starting task 1.0 in stage 0.0 (TID 1, localhost, partition 1,PROCESS_LOCAL, 1731242 bytes)
16/03/20 16:53:39 INFO TaskSetManager: Starting task 2.0 in stage 0.0 (TID 2, localhost, partition 2,PROCESS_LOCAL, 1731242 bytes)
16/03/20 16:53:39 INFO TaskSetManager: Starting task 3.0 in stage 0.0 (TID 3, localhost, partition 3,PROCESS_LOCAL, 1732304 bytes)
16/03/20 16:53:39 INFO Executor: Running task 0.0 in stage 0.0 (TID 0)
16/03/20 16:53:39 INFO Executor: Running task 1.0 in stage 0.0 (TID 1)
16/03/20 16:53:39 INFO Executor: Running task 2.0 in stage 0.0 (TID 2)
16/03/20 16:53:39 INFO Executor: Running task 3.0 in stage 0.0 (TID 3)
16/03/20 16:53:39 INFO CacheManager: Partition rdd_1_1 not found, computing it
16/03/20 16:53:39 INFO CacheManager: Partition rdd_1_3 not found, computing it
16/03/20 16:53:39 INFO CacheManager: Partition rdd_1_0 not found, computing it
16/03/20 16:53:39 INFO CacheManager: Partition rdd_1_2 not found, computing it
[4]	train-error:0.000307
[4]	train-error:0.002456
[16:53:39] src/tree/updater_prune.cc:74: tree pruni[ng1 6e:n5d3,: 391]  rosortcs/,t re4e/ uepxdtartae rn_opdreusn,e .c0c :pr7u4ne:d  ntordeees ,p rmuanxi_ndge petnhd=, 21
[0]	train-error:0.020885
 roots, 2 extra nodes, 0 pruned nodes, max_depth=1
[0]	train-error:0.000000
[16:53:39] src/tree/updater_prune.c[c1:6:7543::3 9t]r ees rpcr/utnrieneg/ uepndda,t er1_p rruonoet.sc,c :27 4ex:t rat rneoed epsr,u ni0ng  pernudn,e d 1no dreoso,t sm,a x_4de petxht=ra1 n
odes, 0 pruned nodes, max_depth=2
[1]	train-error:0.000000
[1]	train-error:0.004914
[16:53:39] src/tre[[e/11u66p::d55a33t::e33r99_p]]r  unsserr.ccc//cttrr:eeee7//4uupp:dd aattteerrre__epp rrpuurnnueen..iccnccg ::en77d44, ::  1tt rrreeoeeo  tppsrr,uu nnii4nngg  eenndd,,  11  rroooottss,,   42ex  teerxxatt rrnaao  dnneoosdd,ee ss,,0   00pr  uppnrreuudnnee ddn  onndooeddsee,ss ,,m  ammxaa_xxd__eddpeetpphtt=hh==221


[0]	train-error:0.000614
[2]	train-error:0.000000
[2]	train-error:0.004914
[16:53:39] src/tree/updater_prune.cc:74: tree pruning end, 1 roots, 2 extra nodes, 0 pruned nodes, max_depth=1
[0]	train-error:0.000614
[16:53:39] src/tree/updater_prune.cc:74: tree pruning end, 1 roots, 2 extra nodes, 0 pruned nodes, max_depth=1
[16:53:39] src/tree/updater_prune.cc:74: tree pruning end, 1 roots, 4 extra nodes, 0 pruned nodes, max_depth=2
[3]	train-error:0.000000
[3]	train-error:0.004914
[16:53:39] src/tree/updater_prune.cc:74: tree pruning end, 1 roots, 4 extra nodes, 0 prun[e[[d1 116n66:o::5d553e33:s::3,339 99m]a]] x  _sdssrerrcpcc/t//thttr=rreeee2ee///u
[1]	train-error:0.000614
uupppdddaaattteeerrr___ppprrruuunnneee...cccccc:::774: tree pruning end, 1 roots, 2 extra nodes, 0 pruned nodes, max_depth=1
4: tree pruning end, 1 roots, 4 extra nodes, 0 pruned nodes, max_depth=2
[4]	train-error:0.000000
[4]	train-error:0.004914
74: tree pruning end, 1 roots, 2 extra nodes, 0 pruned nodes, max_depth=1
16/03/20 16:53:39 INFO MemoryStore: Block rdd_1_3 stored as values in memory (estimated size 64.0 B, free 6.7 KB)
16/03/20 16:53:39 INFO BlockManagerInfo: Added rdd_1_3 in memory on localhost:49326 (size: 64.0 B, free: 2.4 GB)
16/03/20 16:53:39 INFO MemoryStore: Block rdd_1_2 stored as values in memory (estimated size 64.0 B, free 6.8 KB)
16/03/20 16:53:39 INFO BlockManagerInfo: Added rdd_1_2 in memory on localhost:49326 (size: 64.0 B, free: 2.4 GB)
[1]	train-error:0.000614
[16:53:39] src/tree/updater_prune.cc:74: tree pruning end, 1 roots, 4 extra nodes, 0 pruned nodes, max_depth=2
16/03/20 16:53:39 INFO Executor: Finished task 3.0 in stage 0.0 (TID 3). 1529 bytes result sent to driver
16/03/20 16:53:39 INFO Executor: Finished task 2.0 in stage 0.0 (TID 2). 1529 bytes result sent to driver
16/03/20 16:53:39 INFO TaskSetManager: Finished task 3.0 in stage 0.0 (TID 3) in 138 ms on localhost (1/4)
16/03/20 16:53:39 INFO TaskSetManager: Finished task 2.0 in stage 0.0 (TID 2) in 161 ms on localhost (2/4)
[2]	train-error:0.000614
[16:53:39] src/tree/updater_prune.cc:74: tree pruning end, 1 roots, 2 extra nodes, 0 pruned nodes, max_depth=1
[2]	train-error:0.000614
[16:53:39] src/tree/updater_prune.cc:74: tree pruning end, 1 roots, 4 extra nodes, 0 pruned nodes, max_depth=2
[3]	train-error:0.000614
[16:53:39] src/tree/updater_prune.cc:74: tree pruning end, 1 roots, 4 extra nodes, 0 pruned nodes, max_depth=2
[3]	train-error:0.000614
[16:53:39] src/tree/updater_prune.cc:74: tree pruning end, 1 roots, 4 extra nodes, 0 pruned nodes, max_depth=2
16/03/20 16:53:39 INFO MemoryStore: Block rdd_1_1 stored as values in memory (estimated size 64.0 B, free 6.9 KB)
16/03/20 16:53:39 INFO BlockManagerInfo: Added rdd_1_1 in memory on localhost:49326 (size: 64.0 B, free: 2.4 GB)
16/03/20 16:53:39 INFO Executor: Finished task 1.0 in stage 0.0 (TID 1). 1529 bytes result sent to driver
[4]	train-error:0.000614
[16:53:39] src/tree/updater_prune.cc:74: tree pruning end, 1 roots, 4 extra nodes, 0 pruned nodes, max_depth=2
16/03/20 16:53:39 INFO TaskSetManager: Finished task 1.0 in stage 0.0 (TID 1) in 183 ms on localhost (3/4)
16/03/20 16:53:39 INFO MemoryStore: Block rdd_1_0 stored as values in memory (estimated size 64.0 B, free 6.9 KB)
16/03/20 16:53:39 INFO BlockManagerInfo: Added rdd_1_0 in memory on localhost:49326 (size: 64.0 B, free: 2.4 GB)
16/03/20 16:53:39 INFO Executor: Finished task 0.0 in stage 0.0 (TID 0). 1529 bytes result sent to driver
16/03/20 16:53:39 INFO TaskSetManager: Finished task 0.0 in stage 0.0 (TID 0) in 196 ms on localhost (4/4)
16/03/20 16:53:39 INFO TaskSchedulerImpl: Removed TaskSet 0.0, whose tasks have all completed, from pool 
16/03/20 16:53:39 INFO DAGScheduler: ResultStage 0 (foreachPartition at XGBoost.scala:104) finished in 0.197 s
16/03/20 16:53:39 INFO DAGScheduler: Job 0 finished: foreachPartition at XGBoost.scala:104, took 0.205349 s
```

I was able to get around this for now by building and skipping tests with the following command: `mvn package -Dmaven.test.skip=true -DskipTests`

**Comment by CodingCat** [comment]
seems that your rabit tracker didn't get start signal from workers ...

can you run 

```
python dmlc-core/tracker/dmlc_tracker/tracker.py 
```

?

**Comment by CodingCat** [comment]
any update on this?

**Comment by enragedginger** [comment]
Hi @CodingCat, I started up the tracker as you mentioned before, but I'm still running into issues with failing tests.

```
ScalaBoosterImplSuite:
[18:52:22] 6513x127 matrix with 143286 entries loaded from ../../demo/data/agaricus.txt.train
[18:52:22] 1611x127 matrix with 35442 entries loaded from ../../demo/data/agaricus.txt.test
*** RUN ABORTED ***
  java.lang.NoSuchMethodError: scala.Predef$.ArrowAssoc(Ljava/lang/Object;)Ljava/lang/Object;
  at ml.dmlc.xgboost4j.scala.ScalaBoosterImplSuite.ml$dmlc$xgboost4j$scala$ScalaBoosterImplSuite$$trainBooster(ScalaBoosterImplSuite.scala:72)
  at ml.dmlc.xgboost4j.scala.ScalaBoosterImplSuite$$anonfun$1.apply$mcV$sp(ScalaBoosterImplSuite.scala:84)
  at ml.dmlc.xgboost4j.scala.ScalaBoosterImplSuite$$anonfun$1.apply(ScalaBoosterImplSuite.scala:80)
  at ml.dmlc.xgboost4j.scala.ScalaBoosterImplSuite$$anonfun$1.apply(ScalaBoosterImplSuite.scala:80)
  at org.scalatest.Transformer$$anonfun$apply$1.apply$mcV$sp(Transformer.scala:22)
  at org.scalatest.OutcomeOf$class.outcomeOf(OutcomeOf.scala:85)
  at org.scalatest.OutcomeOf$.outcomeOf(OutcomeOf.scala:104)
  at org.scalatest.Transformer.apply(Transformer.scala:22)
  at org.scalatest.Transformer.apply(Transformer.scala:20)
  at org.scalatest.FunSuiteLike$$anon$1.apply(FunSuiteLike.scala:166)
```

Feel free to look into this, but I've since moved on to other libraries.

Thank you.

**Comment by CodingCat** [comment]
it seems that your building process messed up so as to make the ...you'd delete everything and rebuild it

**Comment by jacquesqiao** [comment]
I have the same problems, and when i run 
python dmlc-core/tracker/dmlc_tracker/tracker.py  --num-workers 1
I get:
 INFO start listen on 192.168.1.104:9091
DMLC_TRACKER_ENV_START
DMLC_TRACKER_URI=192.168.1.104
DMLC_NUM_SERVER=0
DMLC_TRACKER_PORT=9091
DMLC_NUM_WORKER=1
DMLC_TRACKER_ENV_END

**Comment by CodingCat** [comment]
@jacquesqiao would you post your log trace here, I would like to check which case you are trapped at...

**Comment by xinyuwuhenZZ** [comment]
@CodingCat: I got the same issue, and I tried your solution and got: Address already in use. 
when I test XGBoostSuite, test 0 passed well, but test 1 stucked......

Thks.

**Comment by CodingCat** [comment]
@xinyuwuhenZZ , address already in use, which means that your local port 9091 has been occupied by other programs, and you can resolve it by changing the port number or kill the program which currently takes the port

BTW, if you have issues to report, you'd create a new issue instead of following the (old and) closed one, otherwise, I may miss your report when I scan the issue list
