### ISSUE TITLE
Python 3.12 `xgboost.core.XGBoostError: Invalid Parameter format for nthread expect int but value='-1'` when `DMatrix` used with `import googlecloudprofiler`.

### ISSUE THREAD

**Issue by hwlodarczyk-rtbh** [dmlc/xgboost#10224]
Hi

I have a very peculiar error which happened when I've updated versions of Python and libs in project I'm working on.

Minimal example to reproduce the case is this:
```python
# file.py
import googlecloudprofiler
from xgboost import DMatrix

DMatrix([[]])
print("works")
```

```python
# requirements.txt
xgboost==2.0.3
google-cloud-profiler==4.1.0
#
numpy==1.26.4
scipy==1.13.0
google-api-python-client==2.125.0
google-auth==2.29.0
google-auth-httplib2==0.2.0
protobuf==4.25.3
requests==2.31.0
#
cachetools==5.3.3
certifi==2024.2.2
charset-normalizer==3.3.2
google-api-core==2.18.0
httplib2==0.22.0
idna==3.6
pyasn1==0.6.0
pyasn1_modules==0.4.0
pyparsing==3.1.2
rsa==4.9
uritemplate==4.1.1
urllib3==2.2.1
```

`Python 3.12.2`

Install with
```pip
pip install -r requirements.txt --no-deps
```
Run with
```bash
python file.py
```

Results in
```python
Traceback (most recent call last):
  File "/project/path/file.py", line 4, in <module>
    DMatrix([[]])
  File "/venv/path/lib/python3.12/site-packages/xgboost/core.py", line 730, in inner_f
    return func(**kwargs)
           ^^^^^^^^^^^^^^
  File "/venv/path/lib/python3.12/site-packages/xgboost/core.py", line 857, in __init__
    handle, feature_names, feature_types = dispatch_data_backend(
                                           ^^^^^^^^^^^^^^^^^^^^^^
  File "/venv/path/lib/python3.12/site-packages/xgboost/data.py", line 1081, in dispatch_data_backend
    return _from_list(data, missing, threads, feature_names, feature_types)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/venv/path/lib/python3.12/site-packages/xgboost/data.py", line 1011, in _from_list
    return _from_numpy_array(array, missing, n_threads, feature_names, feature_types)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/venv/path/lib/python3.12/site-packages/xgboost/data.py", line 207, in _from_numpy_array
    _check_call(
  File "/venv/path/lib/python3.12/site-packages/xgboost/core.py", line 282, in _check_call
    raise XGBoostError(py_str(_LIB.XGBGetLastError()))
xgboost.core.XGBoostError: Invalid Parameter format for nthread expect int but value='-1'
```

To "solve" the problem remove `import googlecloudprofiler` from `file.py`. I really have no idea why just importing the lib causes this problem; it would make more sense after `googlecloudprofiler.start` is called.

I'm also going to check and post if downgrading any of main requirements, which are `xgboost` and `google-cloud-profiler`, will fix this issue. Not today though; tired.

**Comment by trivialfis** [comment]
It's probably Python 3.12 with google profiler. I looked into it a little bit, loading the `_profiler.cpython-312-x86_64-linux-gnu.so` inside google profiler extension causes the error. For me, it's actually a segfault during the construction of DMatrix due to an invalid write inside C++ standard function:
```
    #0 0x7e270a2bb8f4 in std::codecvt<wchar_t, char, __mbstate_t>::do_unshift(__mbstate_t&, char*, char*, char*&) const (/lib/x86_64-linux-gnu/libstdc++.so.6+0xbb8f4)
```

My guess is that it's compiled with an incompatible compiler, which can be resolved by a source installation. I don't think I can go deeper than this at the moment.

**Comment by hcho3** [comment]
It would be interesting to see if the error persists after installing the identical set of packages in a Conda environment. (Conda packages use the same C++ compiler)

**Comment by trivialfis** [comment]
the profiler is not on forge yet. Otherwise I would like to do a quick test.

**Comment by trivialfis** [comment]
> I couldn't downgrade to google-cloud-profiler==4.0.0 because it failed to build for Python 3.12.

I suggest opening an issue for google cloud profiler to fix this first. ;-)

**Comment by trivialfis** [comment]
Protobuf and grpc will be removed from the wheel in the next release.
