### ISSUE TITLE
Federated Learning Tests do not run

### ISSUE THREAD

**Issue by crockeea** [dmlc/xgboost#10394]
I tried to run federated learning tests following the directions in https://github.com/dmlc/xgboost/blob/master/plugin/federated/README.md. I fixed several obvious problems in #10389, but tests still fail with an unhelpful error:

```
[21:45:11] Insecure federated server listening on 0.0.0.0:9091, world size 2
Traceback (most recent call last):
  File "/home/ubuntu/xgboost/tests/test_distributed/test_federated/test_federated.py", line 84, in <module>
    run_federated(with_ssl=False, with_gpu=False)
  File "/home/ubuntu/xgboost/tests/test_distributed/test_federated/test_federated.py", line 69, in run_federated
    raise Exception("Error starting Federated Learning server")
Exception: Error starting Federated Learning server
```

**Comment by trivialfis** [comment]
Fixed in the master branch, will backport
