### ISSUE TITLE
Spark 1.4.1 java.lang.NoSuchMethodError: org.apache.spark.TaskContext$.getPartitionId()I

### ISSUE THREAD

**Issue by edi-bice** [dmlc/xgboost#1053]
I'm running Spark 1.4.1 shell as follows

spark-shell --master yarn-client --jars xgboost-latest/jvm-packages/xgboost4j-spark/target/xgboost4j-spark-0.5-jar-with-dependencies.jar

... and 

sc.getConf.registerKryoClasses(Array(classOf[Booster]))
val model = XGBoost.train(training, paramMap, 10, nWorkers = 9)

fails with following stacktrace:

16/03/25 20:23:10 WARN TaskSetManager: Lost task 0.0 in stage 2.0 (TID 471, lvsdevfrsa06.gspt.net): java.lang.NoSuchMethodError: org.apache.spark.TaskContext$.getPartitionId()I
        at ml.dmlc.xgboost4j.scala.spark.XGBoost$$anonfun$buildDistributedBoosters$1.apply(XGBoost.scala:59)
        at ml.dmlc.xgboost4j.scala.spark.XGBoost$$anonfun$buildDistributedBoosters$1.apply(XGBoost.scala:58)
        at org.apache.spark.rdd.RDD$$anonfun$mapPartitions$1$$anonfun$apply$17.apply(RDD.scala:686)
        at org.apache.spark.rdd.RDD$$anonfun$mapPartitions$1$$anonfun$apply$17.apply(RDD.scala:686)
        at org.apache.spark.rdd.MapPartitionsRDD.compute(MapPartitionsRDD.scala:35)
        at org.apache.spark.rdd.RDD.computeOrReadCheckpoint(RDD.scala:277)
        at org.apache.spark.CacheManager.getOrCompute(CacheManager.scala:69)
        at org.apache.spark.rdd.RDD.iterator(RDD.scala:242)
        at org.apache.spark.scheduler.ResultTask.runTask(ResultTask.scala:63)
        at org.apache.spark.scheduler.Task.run(Task.scala:70)
        at org.apache.spark.executor.Executor$TaskRunner.run(Executor.scala:213)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
        at java.lang.Thread.run(Thread.java:745)

**Comment by CodingCat** [comment]
xgboost4j is developed with Spark 1.6.x, so it will not support running with older spark versions....

in your case, because `getPartitionId()` does not exist in Spark 1.4.x but is called by XGBoost4J, it will not run.....

**Comment by edi-bice** [comment]
I don't remember seeing anywhere that Spark >= 1.6.x was a requirement. Came across another unrelated issue which mentioned getPartitionId missing from Spark 1.4.x so I sort of knew but wanted to find out if it could be fixed. Will close this issue if you prefer but at the very least it will help warn others until documentation reflects the requirement.

**Comment by CodingCat** [comment]
I'm sorry for the inconvenience 

this will not be fixed considering the dev overhead, which is kind of unnecessary since 1.4.x has been outdated for a long time....

**Comment by edi-bice** [comment]
No need to apologize, it's free software and I appreciate all you have put into it! Thanks! Okay, that makes sense but I sort of disagree with the "outdated for a long time". I just upgraded my Hortonworks cluster to the one (2.3.2) before latest release (2.4) and it has Spark 1.4.1. The latest has Spark 1.6.x but it also has Kafka 0.9 which Samza does not support. So it's my problem, not yours, but it's good to know the constraints that exist out there.
