### ISSUE TITLE
XGBoost failing with Rabit error on AWS EMR Serverless

### ISSUE THREAD

**Issue by lsli8888** [dmlc/xgboost#10647]
Environment

AWS EMR Serverless 7.0.0
PySpark 3.5.0
XGBoost 2.0.3

I’m using XBoost for regression, specifically the SparkXGBRegressor. I’m able to use it without issues on my local machine. However, I get the following Rabit-related error when executing it on AWS EMR Serverless. Any ideas? Is it related to [this](https://discuss.xgboost.ai/t/rabittracker-init-error-when-training-a-sparkxgbclassifier-on-emr/3302)?:

```
    2024-05-28 21:54:33.922 [INFO] XGBoost-PySpark: Running xgboost-2.0.3 on 1 workers with
    booster params: {‘objective’: ‘reg:squarederror’, ‘device’: ‘cpu’, ‘learning_rate’: 0.03, ‘max_depth’: 5, ‘random_state’: 0, ‘subsample’: 1.0, ‘eval_metric’: ‘rmse’, ‘nthread’: 8}
    train_call_kwargs_params: {‘early_stopping_rounds’: 50, ‘verbose_eval’: True, ‘num_boost_round’: 10}
    dmatrix_kwargs: {‘nthread’: 8, ‘missing’: 0.0}
    Traceback (most recent call last):
    File “/tmp/spark-86c93d08-da51-4c1d-9834-689be49aad15/train_model.py”, line 436, in
    main()
    File “/home/hadoop/environment/lib64/python3.9/site-packages/my_project/utils/logger_utils.py”, line 38, in wrapper
    return func(*args, **kwargs)
    File “/home/hadoop/environment/lib64/python3.9/site-packages/click/core.py”, line 1157, in call
    return self.main(*args, **kwargs)
    File “/home/hadoop/environment/lib64/python3.9/site-packages/click/core.py”, line 1078, in main
    rv = self.invoke(ctx)
    File “/home/hadoop/environment/lib64/python3.9/site-packages/click/core.py”, line 1434, in invoke
    return ctx.invoke(self.callback, **ctx.params)
    File “/home/hadoop/environment/lib64/python3.9/site-packages/click/core.py”, line 783, in invoke
    return __callback(*args, **kwargs)
    File “/tmp/spark-86c93d08-da51-4c1d-9834-689be49aad15/train_model.py”, line 326, in main
    train_model(
    File “/home/hadoop/environment/lib64/python3.9/site-packages/my_project/utils/logger_utils.py”, line 55, in timed
    result: Callable = method(*args, **kw)
    File “/home/hadoop/environment/lib64/python3.9/site-packages/my_project/utils/logger_utils.py”, line 38, in wrapper
    return func(*args, **kwargs)
    File “/tmp/spark-86c93d08-da51-4c1d-9834-689be49aad15/train_model.py”, line 410, in train_model
    model_training_strategy.train_model(
    File “/home/hadoop/environment/lib64/python3.9/site-packages/my_project/pyspark_utils/model_processor/xgboost_pipeline_model_training_strategy.py”, line 38, in train_model
    return model_training_pipeline.fit(my_project_dataframe)
    File “/usr/lib/spark/python/lib/pyspark.zip/pyspark/ml/base.py”, line 205, in fit
    File “/usr/lib/spark/python/lib/pyspark.zip/pyspark/ml/pipeline.py”, line 134, in _fit
    File “/usr/lib/spark/python/lib/pyspark.zip/pyspark/ml/base.py”, line 205, in fit
    File “/home/hadoop/environment/lib64/python3.9/site-packages/xgboost/spark/core.py”, line 1136, in _fit
    (config, booster) = _run_job()
    File “/home/hadoop/environment/lib64/python3.9/site-packages/xgboost/spark/core.py”, line 1122, in _run_job
    ret = rdd_with_resource.collect()[0]
    File “/usr/lib/spark/python/lib/pyspark.zip/pyspark/rdd.py”, line 1833, in collect
    File “/usr/lib/spark/python/lib/py4j-0.10.9.7-src.zip/py4j/java_gateway.py”, line 1322, in call
    File “/usr/lib/spark/python/lib/pyspark.zip/pyspark/errors/exceptions/captured.py”, line 179, in deco
    File “/usr/lib/spark/python/lib/py4j-0.10.9.7-src.zip/py4j/protocol.py”, line 326, in get_return_value
    py4j.protocol.Py4JJavaError: An error occurred while calling z:org.apache.spark.api.python.PythonRDD.collectAndServe.
    : org.apache.spark.SparkException: Job aborted due to stage failure: Could not recover from a failed barrier ResultStage. Most recent failure reason: Stage failed because barrier task ResultTask(314, 0) finished unsuccessfully.
    org.apache.spark.api.python.PythonException: Traceback (most recent call last):
    File “/home/hadoop/environment/lib64/python3.9/site-packages/xgboost/spark/core.py”, line 1067, in _train_booster
    _rabit_args = _get_rabit_args(context, num_workers)
    File “/home/hadoop/environment/lib64/python3.9/site-packages/xgboost/spark/utils.py”, line 77, in _get_rabit_args
    env = _start_tracker(context, n_workers)
    File “/home/hadoop/environment/lib64/python3.9/site-packages/xgboost/spark/utils.py”, line 66, in _start_tracker
    rabit_context = RabitTracker(host_ip=host, n_workers=n_workers)
    File “/home/hadoop/environment/lib64/python3.9/site-packages/xgboost/tracker.py”, line 208, in init
    sock.bind((host_ip, port))
    OSError: [Errno 99] Cannot assign requested address

at org.apache.spark.api.python.BasePythonRunner$ReaderIterator.handlePythonException(PythonRunner.scala:572)
at org.apache.spark.sql.execution.python.PythonArrowOutput$$anon$1.read(PythonArrowOutput.scala:118)
at org.apache.spark.api.python.BasePythonRunner$ReaderIterator.hasNext(PythonRunner.scala:525)
at org.apache.spark.InterruptibleIterator.hasNext(InterruptibleIterator.scala:37)
at scala.collection.Iterator$$anon$11.hasNext(Iterator.scala:491)
at scala.collection.Iterator$$anon$10.hasNext(Iterator.scala:460)
at scala.collection.Iterator$$anon$10.hasNext(Iterator.scala:460)
at org.apache.spark.ContextAwareIterator.hasNext(ContextAwareIterator.scala:39)
at org.apache.spark.api.python.SerDeUtil$AutoBatchedPickler.hasNext(SerDeUtil.scala:86)
at scala.collection.Iterator.foreach(Iterator.scala:943)
at scala.collection.Iterator.foreach$(Iterator.scala:943)
at org.apache.spark.api.python.SerDeUtil$AutoBatchedPickler.foreach(SerDeUtil.scala:80)
at org.apache.spark.api.python.PythonRDD$.writeIteratorToStream(PythonRDD.scala:322)
at org.apache.spark.api.python.PythonRunner$$anon$2.writeIteratorToStream(PythonRunner.scala:751)
at org.apache.spark.api.python.BasePythonRunner$WriterThread.$anonfun$run$1(PythonRunner.scala:451)
at org.apache.spark.util.Utils$.logUncaughtExceptions(Utils.scala:1962)
at org.apache.spark.api.python.BasePythonRunner$WriterThread.run(PythonRunner.scala:282)

at org.apache.spark.scheduler.DAGScheduler.failJobAndIndependentStages(DAGScheduler.scala:3067)
at org.apache.spark.scheduler.DAGScheduler.$anonfun$abortStage$2(DAGScheduler.scala:3003)
at org.apache.spark.scheduler.DAGScheduler.$anonfun$abortStage$2$adapted(DAGScheduler.scala:3002)
at scala.collection.mutable.ResizableArray.foreach(ResizableArray.scala:62)
at scala.collection.mutable.ResizableArray.foreach$(ResizableArray.scala:55)
at scala.collection.mutable.ArrayBuffer.foreach(ArrayBuffer.scala:49)
at org.apache.spark.scheduler.DAGScheduler.abortStage(DAGScheduler.scala:3002)
at org.apache.spark.scheduler.DAGScheduler.handleTaskCompletion(DAGScheduler.scala:2326)
at org.apache.spark.scheduler.DAGSchedulerEventProcessLoop.doOnReceive(DAGScheduler.scala:3265)
at org.apache.spark.scheduler.DAGSchedulerEventProcessLoop.onReceive(DAGScheduler.scala:3205)
at org.apache.spark.scheduler.DAGSchedulerEventProcessLoop.onReceive(DAGScheduler.scala:3194)
at org.apache.spark.util.EventLoop$$anon$1.run(EventLoop.scala:49)
at org.apache.spark.scheduler.DAGScheduler.runJob(DAGScheduler.scala:1041)
at org.apache.spark.SparkContext.runJob(SparkContext.scala:2406)
at org.apache.spark.SparkContext.runJob(SparkContext.scala:2427)
at org.apache.spark.SparkContext.runJob(SparkContext.scala:2446)
at org.apache.spark.SparkContext.runJob(SparkContext.scala:2471)
at org.apache.spark.rdd.RDD.$anonfun$collect$1(RDD.scala:1046)
at org.apache.spark.rdd.RDDOperationScope$.withScope(RDDOperationScope.scala:151)
at org.apache.spark.rdd.RDDOperationScope$.withScope(RDDOperationScope.scala:112)
at org.apache.spark.rdd.RDD.withScope(RDD.scala:407)
at org.apache.spark.rdd.RDD.collect(RDD.scala:1045)
at org.apache.spark.api.python.PythonRDD$.collectAndServe(PythonRDD.scala:195)
at org.apache.spark.api.python.PythonRDD.collectAndServe(PythonRDD.scala)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.base/java.lang.reflect.Method.invoke(Method.java:568)
at py4j.reflection.MethodInvoker.invoke(MethodInvoker.java:244)
at py4j.reflection.ReflectionEngine.invoke(ReflectionEngine.java:374)
at py4j.Gateway.invoke(Gateway.java:282)
at py4j.commands.AbstractCommand.invokeMethod(AbstractCommand.java:132)
at py4j.commands.CallCommand.execute(CallCommand.java:79)
at py4j.ClientServerConnection.waitForCommands(ClientServerConnection.java:182)
at py4j.ClientServerConnection.run(ClientServerConnection.java:106)
at java.base/java.lang.Thread.run(Thread.java:840)

2024-05-28 21:54:39.439 [INFO] py4j.clientserver: Closing down clientserver connection
```

**Comment by trivialfis** [comment]
We obtain the host address from a spark barrier context https://github.com/dmlc/xgboost/blob/778751a1bbc9a6ed539b54a36676351f1d185e63/python-package/xgboost/spark/utils.py#L57 not sure why the address cannot be assigned.

**Comment by wbo4958** [comment]
Hi @lsli8888, Could you be able try 2.1.0 which has the new rabit implementation.

**Comment by wbo4958** [comment]
No idea if the port the Rabit tried to bind got not insufficient permissions.

**Comment by sgonullu** [comment]
Hey folks,

Just wanted to share a quick fix I found for a similar issue. I noticed RabitTracker was using spark.driver.host to bind to. By default, this is set to the local hostname, but in my case, it was pointing to a different IP.

The solution: I changed spark.driver.host to my local IP address, and it worked!

Quick thought: Wouldn't it make more sense for RabitTracker to use spark.driver.bindAddress instead? Just throwing it out there.

Hope this helps someone!

**Comment by lawrence-sy-li** [comment]
Hi @sgonullu - thanks for the info!  What Python code did you use to get the local IP address?  Something like this?

`socket.gethostbyname(socket.gethostname())`

**Comment by wbo4958** [comment]
Hi @sgonullu, Currently, RabitTracker is launched on the executor side, and we get the IP address from TaskContext info which is  from spark. Looks like xgboost pyspark didn't use `spark.driver.bindAddress` or `spark.driver.host`

**Comment by wbo4958** [comment]
Hi @lsli8888, @trivialfis, I once had a PR to launch the RabitTracker on the driver side https://github.com/dmlc/xgboost/pull/10281, I don't know if it can help on this case.

**Comment by sgonullu** [comment]
> Hi @sgonullu - thanks for the info! What Python code did you use to get the local IP address? Something like this?
> 
> `socket.gethostbyname(socket.gethostname())`

I apologize for the confusion earlier. To clarify, I was troubleshooting the issue and submitted a test Spark job with `--master local[*]`, which resulted in the same bind error. However, when I changed the `spark.driver.host` setting, it worked with `--master local[*]`. I assumed that the tracker would always start on the driver.

After @wbo4958 mentioned that the tracker starts on the executor, I reviewed the code to understand how the IP address is determined. I tested with the following code snippet:

```python
def get_addr_list(iterator):
    context = BarrierTaskContext.get()
    infos = context.getTaskInfos()

    addr_list = [info.address for info in context.getTaskInfos()]
    yield addr_list

executors_addr = rdd.barrier().mapPartitions(get_addr_list).collect()

print(executor_addr)
```

Interestingly, when using `--master local[*]`, the IP address returned was the `spark.driver.host` value. However, when using `--master yarn`, the IP address returned was not the expected worker IP address, but rather a network address (e.g. 10.42.0.0, I am not on EMR) that corresponds to my client's network. Note that my client is running in a container and is not on the same network as the executors.

I'm unsure whether this is due to a Spark configuration issue or something else. Any further guidance would be appreciated.

**Comment by wbo4958** [comment]
@lsli8888, From the logs, the executor exits with unexpected error when spark tried to "create" executor.

`24/08/23 02:16:48 WARN ExecutorContainerStoreImpl: Executor(s) 66,70,67,71,68,72,69,65 exited unexpectedly with exit code 1.
`

You should check the reason here.

And to check such kind of issue, I would suggest you

1, to see if only 1 executor can work?
2, reduce the xgboost dataset to see if xgboost can work on only 1 executor with a few lines of dataset.

**Comment by wbo4958** [comment]
Hi @sgonullu, Can xgboost work on the scenario of `--master yarn`? The BarrierTaskContext of each spark tasks should hold the IP address of each task, which is assigned by spark driver. So the IP should be accessible from driver.

**Comment by wbo4958** [comment]
@lsli8888,

1, `A sampling rate of 0.0001` is the xgboost parameter? if so, then the spark tasks still need to read all the data and do the sampling in xgboost. I suppose there's OOM according to your configuration. I would suggest you 

``` python
train_df = train_df.head(10)
```

2. `socket.gethostbyname(socket.gethostname())`

 Why you did this?

 
 Can you make the sample code working without changing any XGBoost code?


``` python
    >>> from xgboost.spark import SparkXGBClassifier
    >>> from pyspark.ml.linalg import Vectors
    >>> df_train = spark.createDataFrame([
    ...     (Vectors.dense(1.0, 2.0, 3.0), 0, False, 1.0),
    ...     (Vectors.sparse(3, {1: 1.0, 2: 5.5}), 1, False, 2.0),
    ...     (Vectors.dense(4.0, 5.0, 6.0), 0, True, 1.0),
    ...     (Vectors.sparse(3, {1: 6.0, 2: 7.5}), 1, True, 2.0),
    ... ], ["features", "label", "isVal", "weight"])
    >>> df_test = spark.createDataFrame([
    ...     (Vectors.dense(1.0, 2.0, 3.0), ),
    ... ], ["features"])
    >>> xgb_classifier = SparkXGBClassifier(max_depth=5, missing=0.0,
    ...     validation_indicator_col='isVal', weight_col='weight',
    ...     early_stopping_rounds=1, eval_metric='logloss')
    >>> xgb_clf_model = xgb_classifier.fit(df_train)
    >>> xgb_clf_model.transform(df_test).show()
```

**Comment by wbo4958** [comment]
@lsli8888, I see, so the spark GBTRegressor can work? 

But from the log, it seems something wrong with spark cluster where the executor couldn't connect to the driver. If so, the `spark GBTRegressor` also shouldn't work.

**Comment by wbo4958** [comment]
@lsli8888, I see,

The issue is back to the original one, `Cannot assign requested address`.

Hmm, I would suggest you to apply  https://github.com/dmlc/xgboost/pull/10281 to xgboost. this PR which launches the RabitTracker on the driver side instead of executor side, that may help.

and try below code after applying

``` python
df_train = spark.createDataFrame(
    [
        (Vectors.dense(1.0, 2.0, 3.0), 0, False, 1.0),
        (Vectors.sparse(3, {1: 1.0, 2: 5.5}), 1, False, 2.0),
        (Vectors.dense(4.0, 5.0, 6.0), 0, True, 1.0),
        (Vectors.sparse(3, {1: 6.0, 2: 7.5}), 1, True, 2.0),
    ]
    * 100,
    ["features", "label", "isVal", "weight"],
)

callbacks = EvaluationMonitor()
xgb_regressor = SparkXGBRegressor(
    num_workers=5,
    callbacks=[callbacks],
    tracker_on_driver=True,
    validation_indicator_col="isVal",
)
xgb_reg_model = xgb_regressor.fit(df_train)
```

**Comment by wbo4958** [comment]
@lsli8888, I just updated https://github.com/dmlc/xgboost/pull/10281 to the latest. You don't need to compile XGBoost, instead, you can just copy the changed python files from https://github.com/dmlc/xgboost/pull/10281 to replace the installed xgboost python files.

**Comment by wbo4958** [comment]
Hi @lsli8888

``` console
24/08/28 08:18:25 INFO DAGScheduler: Marking ResultStage 2 (fit at /tmp/spark-5efa145b-ef07-496a-8825-3d2e2f37acb7/train_model.py:430) as failed due to a barrier task failed.
24/08/28 08:18:25 INFO TaskSchedulerImpl: Killing all running tasks in stage 2: Task ResultTask(2, 0) from barrier stage ResultStage 2 (fit at /tmp/spark-5efa145b-ef07-496a-8825-3d2e2f37acb7/train_model.py:430) failed.
24/08/28 08:18:25 INFO DAGScheduler: ResultStage 2 (fit at /tmp/spark-5efa145b-ef07-496a-8825-3d2e2f37acb7/train_model.py:430) failed in 25.776 s due to Stage failed because barrier task ResultTask(2, 0) finished unsuccessfully.
org.apache.spark.api.python.PythonException: Traceback (most recent call last):
  File "/home/hadoop/environment/lib64/python3.9/site-packages/xgboost/spark/core.py", line 1054, in _train_booster
    _rabit_args = _get_rabit_args(context, num_workers)
  File "/home/hadoop/environment/lib64/python3.9/site-packages/xgboost/spark/utils.py", line 69, in _get_rabit_args
    env = _start_tracker(context, n_workers)
  File "/home/hadoop/environment/lib64/python3.9/site-packages/xgboost/spark/utils.py", line 58, in _start_tracker
    tracker = RabitTracker(n_workers=n_workers, host_ip=host, sortby="task")
  File "/home/hadoop/environment/lib64/python3.9/site-packages/xgboost/tracker.py", line 73, in __init__
    _check_call(_LIB.XGTrackerCreate(args, ctypes.byref(handle)))
  File "/home/hadoop/environment/lib64/python3.9/site-packages/xgboost/core.py", line 284, in _check_call
    raise XGBoostError(py_str(_LIB.XGBGetLastError()))
xgboost.core.XGBoostError: [08:18:25] /workspace/src/collective/result.cc:78: 
- [socket.h:89|08:18:25]: Failed to bind socket. system error:Cannot assign requested address
```

Looks like the Rabit Tracker was started on the Executor instead of Driver side according to the `  File "/home/hadoop/environment/lib64/python3.9/site-packages/xgboost/spark/core.py", line 1054, in _train_booster
`

The correct code starting RabitTracker should be at https://github.com/dmlc/xgboost/pull/10281/files#diff-8900fd245992de81e0a7b8cb7fcd18c37bae4473e8672e9b11fd7010cac358cfR1027-R1035

Could you please double check if you have really successfuly replaced core.py/estimator.py/utils.py under `xgboost/pyspark`

**Comment by wbo4958** [comment]
Hi @trivialfis, I don't know where it is wrong, could you help take a loot at it?

**Comment by trivialfis** [comment]
> socket.gaierror: [Errno -2] Name or service not known

This error is raised from the Python socket module to signal an invalid address. We will have to spin up a EMR cluster to debug it's network configuration. Maybe it's firewall, maybe there are some quirks on EMR, I don't know. Safe to assume that sparking is returning an address that can not be used by normal TCP socket.

I have seen some errors caused by invalid DNS configuration on another platform, Networking can be tricky.
