### ISSUE TITLE
xgboost.core.XGBoostError array_interface.cu:44: Check failed: err == cudaGetLastError() 

### ISSUE THREAD

**Issue by pmorje** [dmlc/xgboost#10679]
This is my simple code 
```
from sklearn.datasets import load_iris
from sklearn.model_selection import train_test_split
import xgboost as xgb

data = load_iris()
X_train, X_test, y_train, y_test = train_test_split(data['data'], data['target'], test_size=.2)
print(X_train.shape, X_test.shape,y_train.shape,y_test.shape,)
dtrain = xgb.DMatrix(X_train, y_train) 
```
This is the output and errors 
```
(120, 4) (30, 4) (120,) (30,)
Traceback (most recent call last):
  File "...\xg_cuda_error.py", line 8, in <module>
    dtrain = xgb.DMatrix(X_train, y_train)
  File "...\Anaconda3\lib\site-packages\xgboost\core.py", line 726, in inner_f
    return func(**kwargs)
  File "...\Anaconda3\lib\site-packages\xgboost\core.py", line 890, in __init__
    self.set_info(
  File "...\Anaconda3\lib\site-packages\xgboost\core.py", line 726, in inner_f
    return func(**kwargs)
  File "...\Anaconda3\lib\site-packages\xgboost\core.py", line 954, in set_info
    self.set_label(label)
  File "...\Anaconda3\lib\site-packages\xgboost\core.py", line 1092, in set_label
    dispatch_meta_backend(self, label, "label", "float")
  File "...\Anaconda3\lib\site-packages\xgboost\data.py", line 1354, in dispatch_meta_backend
    _meta_from_numpy(data, name, dtype, handle)
  File "...\Anaconda3\lib\site-packages\xgboost\data.py", line 1295, in _meta_from_numpy
    _check_call(_LIB.XGDMatrixSetInfoFromInterface(handle, c_str(field), interface_str))
  File "...\Anaconda3\lib\site-packages\xgboost\core.py", line 284, in _check_call
    raise XGBoostError(py_str(_LIB.XGBGetLastError()))
xgboost.core.XGBoostError: [14:06:26] C:\buildkite-agent\builds\buildkite-windows-cpu-autoscaling-group-i-0015a694724fa8361-1\xgboost\xgboost-ci-windows\src\data\array_interface.cu:44: Check failed: err == cudaGetLastError() (0 vs. 4
6) :
```
The versions are
```
numpy                         2.0.1
xgboost                       2.1.1
```

and nvidia-smi shows
```
+---------------------------------------------------------------------------------------+
| NVIDIA-SMI 537.70                 Driver Version: 537.70       CUDA Version: 12.2     |
|-----------------------------------------+----------------------+----------------------+
| GPU  Name                     TCC/WDDM  | Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp   Perf          Pwr:Usage/Cap |         Memory-Usage | GPU-Util  Compute M. |
|                                         |                      |               MIG M. |
|=========================================+======================+======================|
|   0  GRID A100-20C                TCC   | 00000000:02:00.0 Off |                    0 |
| N/A   N/A    P0              N/A /  N/A |      1MiB / 20480MiB |      0%      Default |
|                                         |                      |             Disabled |
+-----------------------------------------+----------------------+----------------------+

+---------------------------------------------------------------------------------------+
| Processes:                                                                            |
|  GPU   GI   CI        PID   Type   Process name                            GPU Memory |
|        ID   ID                                                             Usage      |
|=======================================================================================|
|  No running processes found                                                           |
+---------------------------------------------------------------------------------------+
```
on my other machine with a different NVIDIA card, different NVIDIA driver version and different CUDA version (shown below), 
same xgboost code works just fine. 
```
NVIDIA Driver Version: 546.59       CUDA Version: 12.3     NVIDIA RTX A2000 8GB 
```
So is the NVIDIA version or CUDA version or xgboost an issue ? 
Thanks for your help.

**Comment by trivialfis** [comment]
Hi, the error code `4` corresponds to `cudaErrorInitializationError`, according to CUDA's document:
```
The API call failed because the CUDA driver and runtime could not be initialized.
```
I can't be sure what's the cause yet. Maybe try to update the CUDA version to >= 12.4?

**Comment by pmorje** [comment]
thanks for your quick response, 
error code actually is 46, not 4 
```
Check failed: err == cudaGetLastError() (0 vs. 46) :
```

**Comment by trivialfis** [comment]
Err, missed the next line. But still seems to be a CUDA issue:
```
    /**
     * This indicates that all CUDA devices are busy or unavailable at the current
     * time. Devices are often busy/unavailable due to use of
     * ::cudaComputeModeProhibited, ::cudaComputeModeExclusiveProcess, or when long
     * running CUDA kernels have filled up the GPU and are blocking new work
     * from starting. They can also be unavailable due to memory constraints
     * on a device that already has active CUDA work being performed.
     */
    cudaErrorDevicesUnavailable           =     46,
```

**Comment by pmorje** [comment]
Thanks. I will see what can be done about that.

**Comment by trivialfis** [comment]
Feel free to reopen if there are further information.
