### ISSUE TITLE
Test fails with Dask 2024.11.0+

### ISSUE THREAD

**Issue by hcho3** [dmlc/xgboost#10994]
https://github.com/dmlc/xgboost/actions/runs/11753771153/job/32747003155

```
E                       distributed.client.FutureCancelledError: ('_argmax-06657a445bd2e0d811c6ff48d5860817', 24) cancelled for reason: unknown.

../../mambaforge/envs/linux_cpu_test/lib/python3.10/site-packages/distributed/client.py:2427: FutureCancelledError
-------------------------------------------------- Captured log setup --------------------------------------------------
INFO     distributed.http.proxy:proxy.py:85 To route to workers diagnostics web server please install jupyter-server-proxy: python -m pip install jupyter-server-proxy
INFO     distributed.scheduler:scheduler.py:1755 State start
INFO     distributed.scheduler:scheduler.py:4225   Scheduler at:     tcp://127.0.0.1:45365
INFO     distributed.scheduler:scheduler.py:4240   dashboard at:  http://127.0.0.1:35259/status
INFO     distributed.scheduler:scheduler.py:8115 Registering Worker plugin shuffle
INFO     distributed.nanny:nanny.py:368         Start Nanny at: 'tcp://127.0.0.1:44537'
INFO     distributed.nanny:nanny.py:368         Start Nanny at: 'tcp://127.0.0.1:32881'
INFO     distributed.scheduler:scheduler.py:4579 Register worker <WorkerState 'tcp://127.0.0.1:41799', name: 0, status: init, memory: 0, processing: 0>
INFO     distributed.scheduler:scheduler.py:6171 Starting worker compute stream, tcp://127.0.0.1:41799
INFO     distributed.core:core.py:883 Starting established connection to tcp://127.0.0.1:51116
INFO     distributed.scheduler:scheduler.py:4579 Register worker <WorkerState 'tcp://127.0.0.1:42755', name: 1, status: init, memory: 0, processing: 0>
INFO     distributed.scheduler:scheduler.py:6171 Starting worker compute stream, tcp://127.0.0.1:42755
INFO     distributed.core:core.py:883 Starting established connection to tcp://127.0.0.1:51122
INFO     distributed.scheduler:scheduler.py:5925 Receive client connection: Client-1b5e6d99-a113-11ef-bd45-00c0cab020ae
INFO     distributed.core:core.py:883 Starting established connection to tcp://127.0.0.1:51132
-------------------------------------------------- Captured log call ---------------------------------------------------
INFO     distributed.worker:worker.py:3171 Run out-of-band function '_start_tracker'
INFO     distributed.scheduler:scheduler.py:5925 Receive client connection: Client-worker-1c041fdc-a113-11ef-bd59-00c0cab020ae
INFO     distributed.core:core.py:883 Starting established connection to tcp://127.0.0.1:51160
INFO     distributed.scheduler:scheduler.py:5925 Receive client connection: Client-worker-1c049a95-a113-11ef-bd5c-00c0cab020ae
INFO     distributed.core:core.py:883 Starting established connection to tcp://127.0.0.1:51200
ERROR    distributed.scheduler:scheduler.py:4956 No keys provided
ERROR    distributed.scheduler:scheduler.py:4956 No keys provided
ERROR    distributed.scheduler:scheduler.py:4956 No keys provided
INFO     distributed.scheduler:scheduler.py:4637 User asked for computation on lost data, ('_argmax-06657a445bd2e0d811c6ff48d5860817', 24)
ERROR    distributed.scheduler:scheduler.py:2091 Error transitioning 'Booster-86632f99bd6a485787c42e9e625f998e' from 'waiting' to 'processing'
Traceback (most recent call last):
  File "/home/phcho/mambaforge/envs/linux_cpu_test/lib/python3.10/site-packages/distributed/scheduler.py", line 2010, in _transition
    recommendations, client_msgs, worker_msgs = func(
  File "/home/phcho/mambaforge/envs/linux_cpu_test/lib/python3.10/site-packages/distributed/scheduler.py", line 2461, in _transition_waiting_processing
    return self._add_to_processing(ts, ws, stimulus_id=stimulus_id)
  File "/home/phcho/mambaforge/envs/linux_cpu_test/lib/python3.10/site-packages/distributed/scheduler.py", line 3407, in _add_to_processing
    return {}, {}, {ws.address: [self._task_to_msg(ts)]}
  File "/home/phcho/mambaforge/envs/linux_cpu_test/lib/python3.10/site-packages/distributed/scheduler.py", line 3579, in _task_to_msg
    assert ts.priority, ts
AssertionError: <TaskState 'Booster-86632f99bd6a485787c42e9e625f998e' processing>
ERROR    distributed.scheduler:scheduler.py:4956 <TaskState 'Booster-86632f99bd6a485787c42e9e625f998e' processing>
ERROR    distributed.protocol.pickle:pickle.py:79 Failed to serialize <TaskState 'Booster-86632f99bd6a485787c42e9e625f998e' processing>.
Traceback (most recent call last):
  File "/home/phcho/mambaforge/envs/linux_cpu_test/lib/python3.10/site-packages/distributed/scheduler.py", line 4911, in update_graph
    metrics = self._create_taskstate_from_graph(
  File "/home/phcho/mambaforge/envs/linux_cpu_test/lib/python3.10/site-packages/distributed/scheduler.py", line 4788, in _create_taskstate_from_graph
    self.transitions(recommendations, stimulus_id)
  File "/home/phcho/mambaforge/envs/linux_cpu_test/lib/python3.10/site-packages/distributed/scheduler.py", line 8227, in transitions
    self._transitions(recommendations, client_msgs, worker_msgs, stimulus_id)
  File "/home/phcho/mambaforge/envs/linux_cpu_test/lib/python3.10/site-packages/distributed/scheduler.py", line 2127, in _transitions
    new_recs, new_cmsgs, new_wmsgs = self._transition(key, finish, stimulus_id)
  File "/home/phcho/mambaforge/envs/linux_cpu_test/lib/python3.10/site-packages/distributed/scheduler.py", line 2010, in _transition
    recommendations, client_msgs, worker_msgs = func(
  File "/home/phcho/mambaforge/envs/linux_cpu_test/lib/python3.10/site-packages/distributed/scheduler.py", line 2461, in _transition_waiting_processing
    return self._add_to_processing(ts, ws, stimulus_id=stimulus_id)
  File "/home/phcho/mambaforge/envs/linux_cpu_test/lib/python3.10/site-packages/distributed/scheduler.py", line 3407, in _add_to_processing
    return {}, {}, {ws.address: [self._task_to_msg(ts)]}
  File "/home/phcho/mambaforge/envs/linux_cpu_test/lib/python3.10/site-packages/distributed/scheduler.py", line 3579, in _task_to_msg
    assert ts.priority, ts
AssertionError: <TaskState 'Booster-86632f99bd6a485787c42e9e625f998e' processing>

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/phcho/mambaforge/envs/linux_cpu_test/lib/python3.10/site-packages/distributed/protocol/pickle.py", line 60, in dumps
    result = pickle.dumps(x, **dump_kwargs)
AttributeError: Can't pickle local object '_inplace_predict_async.<locals>.mapped_predict'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/phcho/mambaforge/envs/linux_cpu_test/lib/python3.10/site-packages/distributed/protocol/pickle.py", line 65, in dumps
    pickler.dump(x)
AttributeError: Can't pickle local object '_inplace_predict_async.<locals>.mapped_predict'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/phcho/mambaforge/envs/linux_cpu_test/lib/python3.10/site-packages/distributed/protocol/pickle.py", line 77, in dumps
    result = cloudpickle.dumps(x, **dump_kwargs)
  File "/home/phcho/mambaforge/envs/linux_cpu_test/lib/python3.10/site-packages/cloudpickle/cloudpickle.py", line 1529, in dumps
    cp.dump(obj)
  File "/home/phcho/mambaforge/envs/linux_cpu_test/lib/python3.10/site-packages/cloudpickle/cloudpickle.py", line 1295, in dump
    return super().dump(obj)
TypeError: cannot pickle 'weakref.ReferenceType' object
```

**Comment by trivialfis** [comment]
Looking at the error, I can't be sure how to create an example for dask to debug  it.

**Comment by hcho3** [comment]
Were you able to reproduce the failure in the XGBoost pytest?

**Comment by trivialfis** [comment]
Yes, on my local machine with the latest dask/distributed, running only the classification tests.

```
$ pytest -s -v ./tests/test_distributed/test_gpu_with_dask/ -k test_dask_classifier
```

**Comment by trivialfis** [comment]
Dask is getting flakier with the new dask-expr and the new shuffle engine, might take some time to debug these.

**Comment by TomAugspurger** [comment]
This patch less us progress a bit further in the tests, by avoiding the issue in https://github.com/dask/distributed/issues/8998 (we don't want to disable optimization, so this is just for debugging).

```
diff --git a/python-package/xgboost/dask/__init__.py b/python-package/xgboost/dask/__init__.py
index 635bedc7d..f107d5a1e 100644
--- a/python-package/xgboost/dask/__init__.py
+++ b/python-package/xgboost/dask/__init__.py
@@ -397,7 +397,7 @@ class DaskDMatrix:
 
             """
             d = client.persist(d)
-            delayed_obj = d.to_delayed()
+            delayed_obj = d.to_delayed(optimize_graph=False)  # debugging.
             if isinstance(delayed_obj, numpy.ndarray):
                 # da.Array returns an array to delayed objects
                 check_columns(delayed_obj)
```

I believe that finishes training, and errors during `predict`:

```
__________________________________________________________________________________________________________________________________ test_dask_classifier[boosting] __________________________________________________________________________________________________________________________________
tests/test_distributed/test_with_dask/test_with_dask.py:738: in test_dask_classifier
    run_dask_classifier(X, y, w, model, None, "cpu", client, 10)
tests/test_distributed/test_with_dask/test_with_dask.py:723: in run_dask_classifier
    prediction_df = classifier.predict(X_d).compute()
/raid/toaugspurger/envs/xgboost/lib/python3.12/site-packages/dask/base.py:374: in compute
    (result,) = compute(self, traverse=False, **kwargs)
/raid/toaugspurger/envs/xgboost/lib/python3.12/site-packages/dask/base.py:662: in compute
    results = schedule(dsk, keys, **kwargs)
/raid/toaugspurger/envs/xgboost/lib/python3.12/site-packages/distributed/client.py:2426: in _gather
    raise exception.with_traceback(traceback)
E   distributed.client.FutureCancelledError: ('_argmax-066227e92a16f05ab1583bdbd8d7a30e', 3) cancelled for reason: unknown.
```

The scheduler logs reveal a couple of errors

```
INFO     distributed.worker:worker.py:3171 Run out-of-band function '_start_tracker'
INFO     distributed.scheduler:scheduler.py:5927 Receive client connection: Client-worker-0d01b752-e22d-11ef-9366-d8c49764f61b
INFO     distributed.core:core.py:883 Starting established connection to tcp://127.0.0.1:39370
INFO     distributed.scheduler:scheduler.py:5927 Receive client connection: Client-worker-0d0390fb-e22d-11ef-9368-d8c49764f61b
INFO     distributed.core:core.py:883 Starting established connection to tcp://127.0.0.1:39396
INFO     distributed.scheduler:scheduler.py:4637 User asked for computation on lost data, ('_argmax-066227e92a16f05ab1583bdbd8d7a30e', 3)
ERROR    distributed.scheduler:scheduler.py:2088 Error transitioning 'Booster-d7dc156c43ba4c319134fa81633b34f2' from 'waiting' to 'processing'
Traceback (most recent call last):
  File "/raid/toaugspurger/envs/xgboost/lib/python3.12/site-packages/distributed/scheduler.py", line 2007, in _transition
    recommendations, client_msgs, worker_msgs = func(
                                                ^^^^^
  File "/raid/toaugspurger/envs/xgboost/lib/python3.12/site-packages/distributed/scheduler.py", line 2458, in _transition_waiting_processing
    return self._add_to_processing(ts, ws, stimulus_id=stimulus_id)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/raid/toaugspurger/envs/xgboost/lib/python3.12/site-packages/distributed/scheduler.py", line 3407, in _add_to_processing
    return {}, {}, {ws.address: [self._task_to_msg(ts)]}
                                 ^^^^^^^^^^^^^^^^^^^^^
  File "/raid/toaugspurger/envs/xgboost/lib/python3.12/site-packages/distributed/scheduler.py", line 3579, in _task_to_msg
    assert ts.priority, ts
           ^^^^^^^^^^^
AssertionError: <TaskState 'Booster-d7dc156c43ba4c319134fa81633b34f2' processing>
ERROR    distributed.scheduler:scheduler.py:4956 <TaskState 'Booster-d7dc156c43ba4c319134fa81633b34f2' processing>
ERROR    distributed.protocol.pickle:pickle.py:79 Failed to serialize <TaskState 'Booster-d7dc156c43ba4c319134fa81633b34f2' processing>.
Traceback (most recent call last):
  File "/raid/toaugspurger/envs/xgboost/lib/python3.12/site-packages/distributed/scheduler.py", line 4911, in update_graph
    metrics = self._create_taskstate_from_graph(
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/raid/toaugspurger/envs/xgboost/lib/python3.12/site-packages/distributed/scheduler.py", line 4788, in _create_taskstate_from_graph
    self.transitions(recommendations, stimulus_id)
  File "/raid/toaugspurger/envs/xgboost/lib/python3.12/site-packages/distributed/scheduler.py", line 8231, in transitions
    self._transitions(recommendations, client_msgs, worker_msgs, stimulus_id)
  File "/raid/toaugspurger/envs/xgboost/lib/python3.12/site-packages/distributed/scheduler.py", line 2124, in _transitions
    new_recs, new_cmsgs, new_wmsgs = self._transition(key, finish, stimulus_id)
                                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/raid/toaugspurger/envs/xgboost/lib/python3.12/site-packages/distributed/scheduler.py", line 2007, in _transition
    recommendations, client_msgs, worker_msgs = func(
                                                ^^^^^
  File "/raid/toaugspurger/envs/xgboost/lib/python3.12/site-packages/distributed/scheduler.py", line 2458, in _transition_waiting_processing
    return self._add_to_processing(ts, ws, stimulus_id=stimulus_id)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/raid/toaugspurger/envs/xgboost/lib/python3.12/site-packages/distributed/scheduler.py", line 3407, in _add_to_processing
    return {}, {}, {ws.address: [self._task_to_msg(ts)]}
                                 ^^^^^^^^^^^^^^^^^^^^^
  File "/raid/toaugspurger/envs/xgboost/lib/python3.12/site-packages/distributed/scheduler.py", line 3579, in _task_to_msg
    assert ts.priority, ts
           ^^^^^^^^^^^
AssertionError: <TaskState 'Booster-d7dc156c43ba4c319134fa81633b34f2' processing>

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/raid/toaugspurger/envs/xgboost/lib/python3.12/site-packages/distributed/protocol/pickle.py", line 60, in dumps
    result = pickle.dumps(x, **dump_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: Can't get local object '_inplace_predict_async.<locals>.mapped_predict'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/raid/toaugspurger/envs/xgboost/lib/python3.12/site-packages/distributed/protocol/pickle.py", line 65, in dumps
    pickler.dump(x)
AttributeError: Can't get local object '_inplace_predict_async.<locals>.mapped_predict'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/raid/toaugspurger/envs/xgboost/lib/python3.12/site-packages/distributed/protocol/pickle.py", line 77, in dumps
    result = cloudpickle.dumps(x, **dump_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/raid/toaugspurger/envs/xgboost/lib/python3.12/site-packages/cloudpickle/cloudpickle.py", line 1537, in dumps
    cp.dump(obj)
  File "/raid/toaugspurger/envs/xgboost/lib/python3.12/site-packages/cloudpickle/cloudpickle.py", line 1303, in dump
    return super().dump(obj)
           ^^^^^^^^^^^^^^^^^
TypeError: cannot pickle 'weakref.ReferenceType' object
```

The log message

```
INFO     distributed.scheduler:scheduler.py:4637 User asked for computation on lost data, ('_argmax-066227e92a16f05ab1583bdbd8d7a30e', 3)
```

Is probably relevant. Seems like Dask lost track of some data unexpectedly. After that, we have some issue on this `Booster` task not having a `priority` set, which causes the `AssertionError`.

The final

```
ERROR    distributed.protocol.pickle:pickle.py:79 Failed to serialize <TaskState 'Booster-d7dc156c43ba4c319134fa81633b34f2' processing>.
```

*might* be irrelevant. That could just be an issue with Dask attempting to recreate the error. I'm not sure yet.

**Comment by hcho3** [comment]
@TomAugspurger Is this with Dask 2024.11.2 or 2024.12.1 ?

**Comment by TomAugspurger** [comment]
I've been testing multiple versions of dask, and my error messages match yours.

Right now, my suspicion is that there are multiple issues to work through

1. https://github.com/dask/distributed/issues/8998, which is preventing us from mixing Futures (persisted arrays) and Delayed objects. This is the error we're hitting with dask>=2024.12.1, because of a change to optimize the task graph in dask==2024.12.1.
2. `distributed.client.FutureCancelledError`, coming from something I don't understand yet. We hit this with Dask 2024.11.2 (so it's been around for a little while), or with dask>=2024.12.1 when changing `to_delalayed` to set `optimize_graph=False`

```diff
diff --git a/python-package/xgboost/dask/__init__.py b/python-package/xgboost/dask/__init__.py
index 635bedc7d..20da9fcc4 100644
--- a/python-package/xgboost/dask/__init__.py
+++ b/python-package/xgboost/dask/__init__.py
@@ -397,7 +397,7 @@ class DaskDMatrix:
 
             """
             d = client.persist(d)
-            delayed_obj = d.to_delayed()
+            delayed_obj = d.to_delayed(optimize_graph=False)
             if isinstance(delayed_obj, numpy.ndarray):
                 # da.Array returns an array to delayed objects
                 check_columns(delayed_obj)
```

**Comment by TomAugspurger** [comment]
One other relevant point: this only fails when passing in a Dask DataFrame into `classifier.predict` (after including that `optimize_graph=False)` change. Things work fine with a Dask Array.

Things also work fine with a simpler `predict`.

```python
# The key components
import dask.distributed
import xgboost.dask
import dask.array as da
import xgboost
import numpy as np

X = da.random.random(size=(100, 2))
y = da.random.choice(range(2), size=(100,))
X_d = X.to_dask_dataframe()

cluster = dask.distributed.LocalCluster()
client = dask.distributed.Client(cluster)

classifier = xgboost.dask.DaskXGBClassifier(eval_metric="merror")
classifier.fit(X, y)
prediction = classifier.predict_proba(X).compute()  # OK!
print("array OK!")


def mapped_predict(partition, *, booster: xgboost.Booster) -> np.ndarray:
    m = xgboost.DMatrix(partition)
    predt = booster.predict(m)
    return predt

# works fine
booster = classifier.get_booster()
X_d.map_partitions(mapped_predict, booster=booster).compute()[:1]

booster_f = client.scatter(booster, hash=False, broadcast=True)
meta = np.empty((0, classifier.n_classes_))
X_d.map_partitions(mapped_predict, booster=booster_f, meta=meta).compute()[:1]
```

It's only when using `classifier.predict` with a dask dataframe that we get the error:

```
prediction_df = classifier.predict_proba(X_d).compute()
```

**Comment by trivialfis** [comment]
May I ask what's the current status? Is there anything we can do to help?

**Comment by TomAugspurger** [comment]
I haven't had a chance to get back to this, sorry. I'll give it another look hopefully today or tomorrow.

That said, while https://github.com/dask/distributed/issues/8998 is a regression in Dask, I suspect it's enough of an edge case (delayed wrapping a delayed wrapping a Future) that we might want / need to simplify things here in `xgboost.dask` to avoid the issue.

**Comment by trivialfis** [comment]
> we might want / need to simplify things here in xgboost.dask to avoid the issue.

Any suggestion is welcome!

**Comment by trivialfis** [comment]
This PR https://github.com/dmlc/xgboost/pull/11291 disables the `optimize_graph` to prevent errors with the latest dask.

**Comment by TomAugspurger** [comment]
Thanks.

I started looking at a way to avoid the `Delayed` wrapping `Futures`, which was one of the problems we were hitting. I think the main thing to be careful about is ensuring the different chunks / partitions of the data are all colocated on the same workerks (so the i-th chunk of `X` and `y` don't have to move again). That should be doable, as long as we're careful about how we call `persist`.

I've pushed that prototype up to https://github.com/dmlc/xgboost/compare/master...TomAugspurger:xgboost:dask-futures, but it's not finished / tested.

**Comment by trivialfis** [comment]
@TomAugspurger Could you please elaberate on "Delayed warping Futures"?

I agree that the code for retrieving chunks is difficult to understand. Given a Dask array, XGBoost does:
- call `to_delayed`, then dask array becomes a numpy array, with `Delayed` as number element (hence, dtype == object)
- Call `client.compute(delayed)` to get futures (hence starting computation on workers). So, maybe it's futures wrapping delayed?

**Comment by trivialfis** [comment]
After #11291, there are three errors from my local run with Dask `2024.11.2` and `2024.12.1`:
```
FAILED tests/test_distributed/test_with_dask/test_with_dask.py::test_dask_classifier[boosting] - distributed.clnt.FutureCancelledError: ('_argmax-fc2dd3f2fc6b0462097a8d2d0b1a8261', 4) cancelled for reaso...
FAILED tests/test_distributed/test_with_dask/test_with_dask.py::test_dask_classifier[rf] - distributed.client.FureCancelledError: ('_argmax-10a471ea0021e7dc864fee018efc0d6f', 32) cancelled for reas...
FAILED tests/test_distributed/test_with_dask/test_with_dask.py::test_worker_left - assert False
```

**Comment by TomAugspurger** [comment]
I believe that `tests/test_distributed/test_with_dask/test_with_dask.py::test_worker_left` is passing on dask `main`.

`tests/test_distributed/test_with_dask/test_with_dask.py::test_dask_classifier` is still failing, likely from https://github.com/dask/distributed/issues/8998.

**Comment by trivialfis** [comment]
Thank you for the update, Tom!

> I believe that tests/test_distributed/test_with_dask/test_with_dask.py::test_worker_left is passing on dask main as of https://github.com/dask/dask/commit/8639b6e7edbb75f92218e35a8b4292a0b2485b0c.

This one is flaky. It's an XGBoost issue. We need to either cleanly shutdown the cluster or wait for a timeout. As a result, it's difficult to have a deterministic test. I will work on that.

> tests/test_distributed/test_with_dask/test_with_dask.py::test_dask_classifier is still failing

This error happens inside a `map_partition/chunk` call, unsure if it's related to `client.submit`. (it should be irrelevant to the `to_delay` issue we fixed before.)

**Comment by trivialfis** [comment]
Please distinguish the `RFClassifier` and `Classifier`. The former is a variant of random forest, while the latter is a boosting model.

**Comment by TomAugspurger** [comment]
My apologies! I mixed those up while simplifying the example. I've updated the test here to fix that, and show that the issue is only present when the Dask Array is chunked:

```python
import dask.array as da
import distributed
import xgboost.sklearn
import xgboost.dask
import sklearn.datasets
import pytest
import numpy as np


@pytest.mark.parametrize("chunks", [20, 100])
def test(chunks: int):
    X, y = sklearn.datasets.make_classification(
        n_samples=100,
        n_features=10,
        n_classes=10,
        n_informative=10,
        n_redundant=0,
        n_repeated=0,
        random_state=1994,
    )

    dX = da.from_array(X, chunks=(chunks, 10))
    dy = da.from_array(y, chunks=(chunks,))

    client = distributed.Client(n_workers=2)

    a = xgboost.sklearn.XGBRFClassifier(
        n_estimators=2,
        eval_metric="merror",
        tree_method=None,
    )
    b = xgboost.dask.DaskXGBRFClassifier(
        n_estimators=2,
        eval_metric="merror",
        tree_method=None,
    )
    a.fit(X, y)
    b.fit(dX, dy)

    result = a.predict(X)
    expected = b.predict(dX).compute()

    np.testing.assert_allclose(result, expected)
```

That might be expected: something about how the distributed version is trained means we might not get the exact same predicted classes as if we train it on all the data on a single partition?

**Comment by trivialfis** [comment]
> show that the issue is only present when the Dask Array is chunked

Looks good. There are streaming algorithms that depend on how the stream is created. Also, floating-point error can introduce issues.

**Comment by hakan-77** [comment]
Hi all, do we have a timeline for this fix?  

On Dask repo we have a similar issue (I think) and the claim is that it is an XGBoost problem and it is now resolved. https://github.com/dask/dask/issues/11809

**Comment by trivialfis** [comment]
Closing as we have been using the latest dask on the master branch. 3.1 should be fine as well.
