### ISSUE TITLE
[jvm-packages] the latest snapshot packages are broken

### ISSUE THREAD

**Issue by wbo4958** [dmlc/xgboost#11015]
Ran into the below issue when running the latest jvm packages from https://s3-us-west-2.amazonaws.com/xgboost-maven-repo/snapshot/ml/dmlc/xgboost4j-spark-gpu_2.12/2.2.0-SNAPSHOT/xgboost4j-spark-gpu_2.12-2.2.0-20241122.084702-226.jar but https://s3-us-west-2.amazonaws.com/xgboost-maven-repo/snapshot/ml/dmlc/xgboost4j-spark-gpu_2.12/2.2.0-SNAPSHOT/xgboost4j-spark-gpu_2.12-2.2.0-20241122.081755-225.jar is ok.

``` bash
24/11/25 15:09:27 INFO BlockManagerInfo: Added broadcast_5_piece0 in memory on 10.19.129.248:34365 (size: 36.6 KiB, free: 11.8 GiB)
24/11/25 15:09:27 WARN TaskSetManager: Lost task 0.0 in stage 3.0 (TID 3) (10.19.129.248 executor 0): ml.dmlc.xgboost4j.java.XGBoostError: parallel_for failed: cudaErrorNoKernelImageForDevice: no kernel image is available for execution on the device
	at ml.dmlc.xgboost4j.java.XGBoostJNI.checkCall(XGBoostJNI.java:48)
	at ml.dmlc.xgboost4j.java.QuantileDMatrix.<init>(QuantileDMatrix.java:69)
	at ml.dmlc.xgboost4j.java.QuantileDMatrix.<init>(QuantileDMatrix.java:38)
	at ml.dmlc.xgboost4j.scala.QuantileDMatrix.<init>(QuantileDMatrix.scala:36)
	at ml.dmlc.xgboost4j.scala.spark.GpuXGBoostPlugin.$anonfun$buildRddWatches$7(GpuXGBoostPlugin.scala:144)
	at scala.Option.getOrElse(Option.scala:189)
	at ml.dmlc.xgboost4j.scala.spark.GpuXGBoostPlugin.ml$dmlc$xgboost4j$scala$spark$GpuXGBoostPlugin$$buildQuantileDMatrix$1(GpuXGBoostPlugin.scala:144)
	at ml.dmlc.xgboost4j.scala.spark.GpuXGBoostPlugin$$anon$2.next(GpuXGBoostPlugin.scala:167)
	at ml.dmlc.xgboost4j.scala.spark.GpuXGBoostPlugin$$anon$2.next(GpuXGBoostPlugin.scala:164)
	at ml.dmlc.xgboost4j.scala.spark.XGBoost$.$anonfun$train$2(XGBoost.scala:252)
	at org.apache.spark.rdd.RDDBarrier.$anonfun$mapPartitions$2(RDDBarrier.scala:51)
	at org.apache.spark.rdd.RDDBarrier.$anonfun$mapPartitions$2$adapted(RDDBarrier.scala:51)

```

**Comment by hcho3** [comment]
Fixed now: https://github.com/dmlc/xgboost/actions/runs/12005755767/job/33463130639?pr=11001 (CI is now building CUDA archs 50, 60, 70, 80, and 90)
