### ISSUE TITLE
Can models trained using xgboost4j-spark be saved and loaded in python xgboost?

### ISSUE THREAD

**Issue by lminer** [dmlc/xgboost#1115]
If I train a model using `xgboost4j-spark` and dump it using the `saveModelAsHadoopFile` method. Would I be able to subsequently load it using the python package for `xgboost`?

**Comment by lminer** [comment]
The answer is, yes: https://xgboost.readthedocs.org/en/latest/tutorial/aws_yarn.html#analyze-the-model

**Comment by taoz1** [comment]
@lminer I tried it but it does not work. Do you have any idea how to get around this error?

`>>> bst=xgb.Booster(model_file="model.bin")
[19:13:14] dmlc-core/include/dmlc/./logging.h:235: [19:13:14] src/gbm/gbm.cc:17: Unknown gbm type
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/tzhu3/anaconda2/lib/python2.7/site-packages/xgboost/core.py", line 653, in __init__
    self.load_model(model_file)
  File "/home/tzhu3/anaconda2/lib/python2.7/site-packages/xgboost/core.py", line 996, in load_model
    _check_call(_LIB.XGBoosterLoadModel(self.handle, c_str(fname)))
  File "/home/tzhu3/anaconda2/lib/python2.7/site-packages/xgboost/core.py", line 127, in _check_call
    raise XGBoostError(_LIB.XGBGetLastError())
xgboost.core.XGBoostError: [19:13:14] src/gbm/gbm.cc:17: Unknown gbm type`

**Comment by lminer** [comment]
Never actually tried it myself. Just figured it was possible due to that page.

**Comment by cnglen** [comment]
The same error: unknow gbm type

**Comment by laughing** [comment]
I get the same error message

**Comment by ssimeonov** [comment]
I have the same problem, which is why I created the above issue with steps to reproduce the problem.

**Comment by haiy** [comment]
+1

**Comment by haiy** [comment]
Could anyone  give some examples?
