### ISSUE TITLE
Invalid literal for float()

### ISSUE THREAD

**Issue by ptrblck** [dmlc/xgboost#1154]
Hi all,

I am new to xgboost and wanted to try out some examples.
I installed xgboost with: `pip install xgboost`  
and I am using anaconda (with Python 2.7).
`xgb.__version__` shows version '0.4'.

It seems to me as if xgb is using a wrong format to represent floats.

This minimal example crashes in the last line:

```
import numpy as np
import xgboost as xgb


dtrain = xgb.DMatrix('./data/agaricus.txt.train')
dtest = xgb.DMatrix('./data/agaricus.txt.test')

param = {'max_depth':2, 'eta':1, 'silent':1, 'objective':'binary:logistic'}

watchlist = [(dtest,'eval'), (dtrain,'train')]
num_round = 10
bst = xgb.train(param, dtrain, num_round, watchlist)


preds = bst.predict(dtest)

bst_cv = xgb.cv(param, dtrain, num_round, nfold=10, metrics={'error'}, seed = 0)
```

Console output for bst = xgb.train(...):

```
bst = xgb.train(param, dtrain, num_round, watchlist)
[0]     eval-error:0,042831     train-error:0,046522
[1]     eval-error:0,021726     train-error:0,022263
[2]     eval-error:0,006207     train-error:0,007063
[3]     eval-error:0,018001     train-error:0,015200
[4]     eval-error:0,006207     train-error:0,007063
[5]     eval-error:0,000000     train-error:0,001228
[6]     eval-error:0,000000     train-error:0,001228
[7]     eval-error:0,000000     train-error:0,001228
[8]     eval-error:0,000000     train-error:0,001228
[9]     eval-error:0,000000     train-error:0,000000
```

Error message after last line:

```
bst_cv = xgb.cv(param, dtrain, num_round, nfold=10, metrics={'error'}, seed = 0)
Traceback (most recent call last):

  File "<ipython-input-15-6a48be9d67be>", line 1, in <module>
    bst_cv = xgb.cv(param, dtrain, num_round, nfold=10, metrics={'error'}, seed = 0)

  File "/home/./anaconda/lib/python2.7/site-packages/xgboost/training.py", line 421, in cv
    as_pandas=as_pandas)

  File "/home/./anaconda/lib/python2.7/site-packages/xgboost/training.py", line 303, in aggcv
    cvmap[k].append(float(v))

ValueError: invalid literal for float(): 0,046595
```

As you can see, a float is given with 0,046595 instead of 0.046595.

Do you have any idea what went wrong?

Best regards,
ptrblck

**Comment by khotilov** [comment]
Something is messed up with your localization settings. Check the output of `locale` from the shell that you've used to build xgboost, and compare that to python's:
```
import locale
locale.getdefaultlocale()
locale.localeconv()
```
Also try installing from github, not pypi.

**Comment by AbdealiJK** [comment]
Yup, it seems like the python API is using a different locale and the C API is using a different locale. Which is confusing your numbering system.
