### ISSUE TITLE
[jvm-packages]Check failed: ModelInitialized() Always call InitModel or LoadModel before update

### ISSUE THREAD

**Issue by futurecam** [dmlc/xgboost#1203]
Hi,
I deploy the 
xgboost4j-spark-0.5.jar and xgboost4j-0.5.jar (with out dependency)
to my own repositories,
and make a new project for training depend on the xgboost4j-spark-0.5.jar and xgboost4j-0.5.jar 
and i get :

ERROR executor.Executor: Exception in task 1.0 in stage 5.0 (TID 13)
ml.dmlc.xgboost4j.java.XGBoostError: [21:23:06] src/learner.cc:283: Check failed: ModelInitialized() Always call InitModel or LoadModel before update
        at ml.dmlc.xgboost4j.java.JNIErrorHandle.checkCall(JNIErrorHandle.java:48)
        at ml.dmlc.xgboost4j.java.Booster.update(Booster.java:133)
        at ml.dmlc.xgboost4j.java.XGBoost.train(XGBoost.java:117)
        at ml.dmlc.xgboost4j.scala.XGBoost$.train(XGBoost.scala:51)
        at ml.dmlc.xgboost4j.scala.spark.XGBoost$$anonfun$buildDistributedBoosters$1.apply(XGBoost.scala:63)
        at ml.dmlc.xgboost4j.scala.spark.XGBoost$$anonfun$buildDistributedBoosters$1.apply(XGBoost.scala:59)
        at org.apache.spark.rdd.RDD$$anonfun$mapPartitions$1$$anonfun$apply$20.apply(RDD.scala:710)
        at org.apache.spark.rdd.RDD$$anonfun$mapPartitions$1$$anonfun$apply$20.apply(RDD.scala:710)
        at org.apache.spark.rdd.MapPartitionsRDD.compute(MapPartitionsRDD.scala:38)
        at org.apache.spark.rdd.RDD.computeOrReadCheckpoint(RDD.scala:306)
        at org.apache.spark.CacheManager.getOrCompute(CacheManager.scala:69)
        at org.apache.spark.rdd.RDD.iterator(RDD.scala:268)
        at org.apache.spark.scheduler.ResultTask.runTask(ResultTask.scala:66)
        at org.apache.spark.scheduler.Task.run(Task.scala:89)
        at org.apache.spark.executor.Executor$TaskRunner.run(Executor.scala:213)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615)
        at java.lang.Thread.run(Thread.java:745)

by the way, the jvm-packages project  supply here is working OK.
Thank you!

**Comment by CodingCat** [comment]
would you post your code? or is it the complete log trace in your side?

**Comment by futurecam** [comment]
object xgboost_train {
  def main(args: Array[String]): Unit = {
    if (args.length != 4) {
      println(
        "usage: program num_of_rounds num_workers  conf_path  model_path")
      sys.exit(1)
    }
    val sparkConf = new SparkConf().setAppName("XGBoost-spark-search")
      .set("spark.serializer", "org.apache.spark.serializer.JavaSerializer")
      .set("spark.driver.maxResultSize", "2g")
      .set("spark.yarn.preserve.staging.files", "true")

    val sc = new SparkContext(sparkConf)
    val outputModelPath = args(3)
    // number of iterations
    val numRound = args(0).toInt
    import DataUtils._
    val trainRDD = processFeature(sc, args(2)).repartition(args(1).toInt)
    // training parameters
    val paramMap = List(
      "max_depth" -> 10,
      "eta" -> 0.1f,
      "silent" -> 1,
      "subsample" -> 0.5f,
      "colsample_bytree" -> 0.7f,
      "max_delta_step" -> 5,
      "min_child_weight" -> 16,
      "eval_metric" -> "auc",
      "objective" -> "binary:logistic").toMap
    val eval = new CustomEvalAuc
    val xgboostModel = XGBoost.train(trainRDD, paramMap, numRound, nWorkers = args(1).toInt, eval = eval)
    // save model to HDFS path
    xgboostModel.saveModelAsHadoopFile(outputModelPath)
  }
}

my code is very similar as DistTrainWithSpark and processFeature return a  RDD[LabeledPoint]


the complete log trace in executor is :
[21:23:06] dmlc-core/include/dmlc/logging.h:245: [21:23:06] src/learner.cc:283: Check failed: ModelInitialized() Always call InitModel or LoadModel before update
16/05/16 21:23:06 ERROR executor.Executor: Exception in task 1.0 in stage 5.0 (TID 13)
ml.dmlc.xgboost4j.java.XGBoostError: [21:23:06] src/learner.cc:283: Check failed: ModelInitialized() Always call InitModel or LoadModel before update
        at ml.dmlc.xgboost4j.java.JNIErrorHandle.checkCall(JNIErrorHandle.java:48)
        at ml.dmlc.xgboost4j.java.Booster.update(Booster.java:133)
        at ml.dmlc.xgboost4j.java.XGBoost.train(XGBoost.java:117)
        at ml.dmlc.xgboost4j.scala.XGBoost$.train(XGBoost.scala:51)
        at ml.dmlc.xgboost4j.scala.spark.XGBoost$$anonfun$buildDistributedBoosters$1.apply(XGBoost.scala:63)
        at ml.dmlc.xgboost4j.scala.spark.XGBoost$$anonfun$buildDistributedBoosters$1.apply(XGBoost.scala:59)
        at org.apache.spark.rdd.RDD$$anonfun$mapPartitions$1$$anonfun$apply$20.apply(RDD.scala:710)
        at org.apache.spark.rdd.RDD$$anonfun$mapPartitions$1$$anonfun$apply$20.apply(RDD.scala:710)
        at org.apache.spark.rdd.MapPartitionsRDD.compute(MapPartitionsRDD.scala:38)
        at org.apache.spark.rdd.RDD.computeOrReadCheckpoint(RDD.scala:306)
        at org.apache.spark.CacheManager.getOrCompute(CacheManager.scala:69)
        at org.apache.spark.rdd.RDD.iterator(RDD.scala:268)
        at org.apache.spark.scheduler.ResultTask.runTask(ResultTask.scala:66)
        at org.apache.spark.scheduler.Task.run(Task.scala:89)
        at org.apache.spark.executor.Executor$TaskRunner.run(Executor.scala:213)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615)
        at java.lang.Thread.run(Thread.java:745)

**Comment by CodingCat** [comment]
is there any other stack trace in your side? I cannot see any reason causing this problem from the current one....

**Comment by CodingCat** [comment]
I tried to reproduce the bug locally, there is no luck.....

**Comment by futurecam** [comment]
@CodingCat , I realize that I build a libxgboost.so from our C++ code(tag0.47), and this libxgboost.so was dlopen in processFeature(list above) function, but it was closed before function return
Was this the reason?Why it happen?

I have tried saveAsTextFile at last of  processFeature 
and replace 
val trainRDD = processFeature(sc, args(2)).repartition(args(1).toInt)
with 
val trainRDD = MLUtils.loadLibSVMFile(sc,args(2))
It works fine!

**Comment by CodingCat** [comment]
I have no idea about what is contained in processFeature.....
