### ISSUE TITLE
[jvm-packages] Application gets blocked on xgboost.train

### ISSUE THREAD

**Issue by tanwanirahul** [dmlc/xgboost#1287]
Hi Developers,

I am running XGBoost4J on mac. When I run a simple demo application, it executes fine until we hit xgboost.train.

From the Spark's perspective, train job finishes just fine. However, the main thread is waiting from the rabbit tracker and does not get any notify in return.

I am attaching thread dump here for the analysis. Let me know if you would need more information for the same.

[xgboost_thread_dump.txt](https://github.com/dmlc/xgboost/files/322837/xgboost_thread_dump.txt)

**Comment by CodingCat** [comment]
would you post the log trace printed on your screen, which would be more helpful for trouble shooting?

**Comment by tanwanirahul** [comment]
@CodingCat Sure. Please find the file attached showing the output. Let me know if you would need more information to dig. thanks!

[output.txt](https://github.com/dmlc/xgboost/files/327718/output.txt)

**Comment by CodingCat** [comment]
it seems that your rabit tracker didn't get started correctly, and it cannot communicate with the distributed workers so that it blocks the thread to wait for the termination signals from the lost workers

would you run `python dmlc-core/tracker/dmlc_tracker/tracker.py` and post the output?

**Comment by tanwanirahul** [comment]
@CodingCat thanks. 

Here is the output - 

python dmlc-core/tracker/dmlc_tracker/tracker.py --num-workers 4
2016-06-24 13:20:33,821 INFO start listen on 192.168.1.236:9091
DMLC_TRACKER_ENV_START
DMLC_TRACKER_URI=192.168.1.236
DMLC_NUM_SERVER=0
DMLC_TRACKER_PORT=9091
DMLC_NUM_WORKER=4
DMLC_TRACKER_ENV_END

**Comment by CodingCat** [comment]
sorry for the late response, I was in traveling....

ok, the problem is on the inter-threads communication within your mac, the worker threads cannot contact with rabit threads via the designated IP and port address

I suggest that you try the distributed xgboost through dmlc-submit, e.g. 

'dmlc-core/tracker/dmlc-submit --cluster mpi --num-workers 2 xgboost demo/binary_classification/mushroom.conf data=demo/data/agaricus.txt.train eval=demo/data/agaricus.txt.test '

and debug your network configuration issue causing the disconnection 


The last case I met is due to the inconsistency between `localhost` and actual IP address

**Comment by zhangweijiqn** [comment]
hi,
I met the same problem on ubuntu. When I running the demo example of spark, tasks were blocked...

2016-09-21 11:37:42(Logging.scala:54)[dispatcher-event-loop-2] INFO :Starting task 3.0 in stage 2.0 (TID 7, localhost, partition 3, ANY, 5392 bytes)
2016-09-21 11:37:42(Logging.scala:54)[Executor task launch worker-1] INFO :Running task 0.0 in stage 2.0 (TID 4)
2016-09-21 11:37:42(Logging.scala:54)[Executor task launch worker-0] INFO :Running task 1.0 in stage 2.0 (TID 5)
2016-09-21 11:37:42(Logging.scala:54)[Executor task launch worker-2] INFO :Running task 2.0 in stage 2.0 (TID 6)
2016-09-21 11:37:42(Logging.scala:54)[dispatcher-event-loop-1] INFO :Removed broadcast_1_piece0 on 10.12.163.52:53316 in memory (size: 2.2 KB, free: 873.7 MB)
2016-09-21 11:37:42(Logging.scala:54)[Executor task launch worker-3] INFO :Running task 3.0 in stage 2.0 (TID 7)

And when I check the spark log, and saw the stage blocking on mapPartitions at XGBoost.scala: 85 .
Then I run the same application with yarn-client mode, problems happened:

Job aborted due to stage failure: Task 1 in stage 2.0 failed 4 times, most recent failure: Lost task 1.3 in stage 2.0 (TID 14, BDS-TEST-001): java.lang.NoClassDefFoundError: Could not initialize class ml.dmlc.xgboost4j.java.Rabit +details
Job aborted due to stage failure: Task 1 in stage 2.0 failed 4 times, most recent failure: Lost task 1.3 in stage 2.0 (TID 14, BDS-TEST-001): java.lang.NoClassDefFoundError: Could not initialize class ml.dmlc.xgboost4j.java.Rabit
	at ml.dmlc.xgboost4j.scala.spark.XGBoost$$anonfun$buildDistributedBoosters$1.apply(XGBoost.scala:88)
	at ml.dmlc.xgboost4j.scala.spark.XGBoost$$anonfun$buildDistributedBoosters$1.apply(XGBoost.scala:86)
	at org.apache.spark.rdd.RDD$$anonfun$mapPartitions$1$$anonfun$apply$23.apply(RDD.scala:766)
	at org.apache.spark.rdd.RDD$$anonfun$mapPartitions$1$$anonfun$apply$23.apply(RDD.scala:766)
	at org.apache.spark.rdd.MapPartitionsRDD.compute(MapPartitionsRDD.scala:38)
	at org.apache.spark.rdd.RDD.computeOrReadCheckpoint(RDD.scala:319)
	at org.apache.spark.rdd.RDD$$anonfun$8.apply(RDD.scala:332)
	at org.apache.spark.rdd.RDD$$anonfun$8.apply(RDD.scala:330)
	at org.apache.spark.storage.BlockManager$$anonfun$doPutIterator$1.apply(BlockManager.scala:919)
	at org.apache.spark.storage.BlockManager$$anonfun$doPutIterator$1.apply(BlockManager.scala:910)
	at org.apache.spark.storage.BlockManager.doPut(BlockManager.scala:866)
	at org.apache.spark.storage.BlockManager.doPutIterator(BlockManager.scala:910)
	at org.apache.spark.storage.BlockManager.getOrElseUpdate(BlockManager.scala:668)
	at org.apache.spark.rdd.RDD.getOrCompute(RDD.scala:330)
	at org.apache.spark.rdd.RDD.iterator(RDD.scala:281)
	at org.apache.spark.scheduler.ResultTask.runTask(ResultTask.scala:70)
	at org.apache.spark.scheduler.Task.run(Task.scala:85)
	at org.apache.spark.executor.Executor$TaskRunner.run(Executor.scala:274)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)

**Comment by zhangweijiqn** [comment]
The reason is found that parameter nWorks' value is more than the executor's number.
