### ISSUE TITLE
flink: Job execution failed

### ISSUE THREAD

**Issue by gbraes** [dmlc/xgboost#1290]
Hi,  
  I am trying to run almost the same example provided in XGboost for flink:

> import ml.dmlc.xgboost4j.scala.flink.XGBoost
> import org.apache.flink.api.scala.{ExecutionEnvironment, _}
> import org.apache.flink.ml.MLUtils
> 
> object DistTrainWithFlink {
>   def main(args: Array[String]) {
>     val env: ExecutionEnvironment = ExecutionEnvironment.getExecutionEnvironment
>     // read trainining data
>     val trainData =
>       MLUtils.readLibSVM(env, "/root/agaricus.txt.train")
>     val testData = MLUtils.readLibSVM(env, "/root/agaricus.txt.test")
>     // define parameters
>     val paramMap = List(
>       "eta" -> 0.1,
>       "max_depth" -> 2,
>       "objective" -> "binary:logistic").toMap
>     // number of iterations
>     val round = 2
>     // train the model
>     val model = XGBoost.train(trainData, paramMap, round)
>     //val predTest = model.predict(testData.map{x => x.vector})
>     //model.saveModelAsHadoopFile("file:///path/to/xgboost.model")
>   }
> } 

After packaging with mvn and running with : 

   ./bin/flink run -p 1 myfile-1.0-SNAPSHOT.jar

 The client says there is an error:

>  The slot in which the task was executed has been released. Probably loss of TaskManager 47411f8fd0988e7b2d6571e15b814968 @ namenode - 4 slots - URL: akka.tcp://flink@10.0.10.2:55342/user/taskmanager

I get this log in the flink/log/flink-root-taskmanager-2-namenode.log
(the last RUNNING task seems to fail ...MapPartition in XGBoost.scala:90)

`2016-06-21 21:37:50,396 WARN  org.apache.hadoop.util.NativeCodeLoader                       - Unable to load native-hadoop library for your platform... using builtin-java classes where applicable
2016-06-21 21:37:50,496 INFO  org.apache.flink.runtime.taskmanager.TaskManager              - --------------------------------------------------------------------------------
2016-06-21 21:37:50,497 INFO  org.apache.flink.runtime.taskmanager.TaskManager              -  Starting TaskManager (Version: 1.0.3, Rev:f3a6b5f, Date:06.05.2016 @ 12:58:02 UTC)
2016-06-21 21:37:50,497 INFO  org.apache.flink.runtime.taskmanager.TaskManager              -  Current user: root
2016-06-21 21:37:50,497 INFO  org.apache.flink.runtime.taskmanager.TaskManager              -  JVM: Java HotSpot(TM) 64-Bit Server VM - Oracle Corporation - 1.7/24.51-b03
2016-06-21 21:37:50,497 INFO  org.apache.flink.runtime.taskmanager.TaskManager              -  Maximum heap size: 494 MiBytes
2016-06-21 21:37:50,497 INFO  org.apache.flink.runtime.taskmanager.TaskManager              -  JAVA_HOME: (not set)
2016-06-21 21:37:50,499 INFO  org.apache.flink.runtime.taskmanager.TaskManager              -  Hadoop version: 2.7.2
2016-06-21 21:37:50,499 INFO  org.apache.flink.runtime.taskmanager.TaskManager              -  JVM Options:
2016-06-21 21:37:50,499 INFO  org.apache.flink.runtime.taskmanager.TaskManager              -     -XX:+UseConcMarkSweepGC
2016-06-21 21:37:50,499 INFO  org.apache.flink.runtime.taskmanager.TaskManager              -     -XX:+CMSClassUnloadingEnabled
2016-06-21 21:37:50,499 INFO  org.apache.flink.runtime.taskmanager.TaskManager              -     -Xms512M
2016-06-21 21:37:50,499 INFO  org.apache.flink.runtime.taskmanager.TaskManager              -     -Xmx512M
2016-06-21 21:37:50,499 INFO  org.apache.flink.runtime.taskmanager.TaskManager              -     -XX:MaxDirectMemorySize=8388607T
2016-06-21 21:37:50,499 INFO  org.apache.flink.runtime.taskmanager.TaskManager              -     -XX:MaxPermSize=256m
2016-06-21 21:37:50,499 INFO  org.apache.flink.runtime.taskmanager.TaskManager              -     -Dlog.file=/root/flink/log/flink-root-taskmanager-2-namenode.log
2016-06-21 21:37:50,499 INFO  org.apache.flink.runtime.taskmanager.TaskManager              -     -Dlog4j.configuration=file:/root/flink/conf/log4j.properties
2016-06-21 21:37:50,499 INFO  org.apache.flink.runtime.taskmanager.TaskManager              -     -Dlogback.configurationFile=file:/root/flink/conf/logback.xml
2016-06-21 21:37:50,499 INFO  org.apache.flink.runtime.taskmanager.TaskManager              -  Program Arguments:
2016-06-21 21:37:50,499 INFO  org.apache.flink.runtime.taskmanager.TaskManager              -     --configDir
2016-06-21 21:37:50,499 INFO  org.apache.flink.runtime.taskmanager.TaskManager              -     /root/flink/conf
2016-06-21 21:37:50,499 INFO  org.apache.flink.runtime.taskmanager.TaskManager              -  Classpath: /root/flink/lib/flink-dist_2.11-1.0.3.jar:/root/flink/lib/flink-python_2.11-1.0.3.jar:/root/flink/lib/log4j-1.2.17.jar:/root/flink/lib/slf4j-log4j12-1.7.7.jar:::
2016-06-21 21:37:50,499 INFO  org.apache.flink.runtime.taskmanager.TaskManager              - --------------------------------------------------------------------------------
2016-06-21 21:37:50,500 INFO  org.apache.flink.runtime.taskmanager.TaskManager              - Registered UNIX signal handlers for [TERM, HUP, INT]
2016-06-21 21:37:50,502 INFO  org.apache.flink.runtime.taskmanager.TaskManager              - Maximum number of open file descriptors is 1048576
2016-06-21 21:37:50,519 INFO  org.apache.flink.runtime.taskmanager.TaskManager              - Loading configuration from /root/flink/conf
2016-06-21 21:37:50,562 INFO  org.apache.flink.runtime.taskmanager.TaskManager              - Security is not enabled. Starting non-authenticated TaskManager.
2016-06-21 21:37:50,576 INFO  org.apache.flink.runtime.util.LeaderRetrievalUtils            - Trying to select the network interface and address to use by connecting to the leading JobManager.
2016-06-21 21:37:50,577 INFO  org.apache.flink.runtime.util.LeaderRetrievalUtils            - TaskManager will try to connect for 10000 milliseconds before falling back to heuristics
2016-06-21 21:37:50,579 INFO  org.apache.flink.runtime.net.ConnectionUtils                  - Retrieved new target address /10.0.10.2:6123.
2016-06-21 21:37:50,582 INFO  org.apache.flink.runtime.taskmanager.TaskManager              - TaskManager will use hostname/address 'namenode' (10.0.10.2) for communication.
2016-06-21 21:37:50,583 INFO  org.apache.flink.runtime.taskmanager.TaskManager              - Starting TaskManager
2016-06-21 21:37:50,583 INFO  org.apache.flink.runtime.taskmanager.TaskManager              - Starting TaskManager actor system at 10.0.10.2:0
2016-06-21 21:37:50,839 INFO  akka.event.slf4j.Slf4jLogger                                  - Slf4jLogger started
2016-06-21 21:37:50,866 INFO  Remoting                                                      - Starting remoting
2016-06-21 21:37:50,958 INFO  Remoting                                                      - Remoting started; listening on addresses :[akka.tcp://flink@10.0.10.2:54112]
2016-06-21 21:37:50,961 INFO  org.apache.flink.runtime.taskmanager.TaskManager              - Starting TaskManager actor
2016-06-21 21:37:50,965 INFO  org.apache.flink.runtime.io.network.netty.NettyConfig         - NettyConfig [server address: namenode/10.0.10.2, server port: 37627, memory segment size (bytes): 32768, transport type: NIO, number of server threads: 4 (manual), number of client threads: 4 (manual), server connect backlog: 0 (use Netty's default), client connect timeout (sec): 120, send/receive buffer size (bytes): 0 (use Netty's default)]
2016-06-21 21:37:50,967 INFO  org.apache.flink.runtime.taskmanager.TaskManager              - Messages between TaskManager and JobManager have a max timeout of 10000 milliseconds
2016-06-21 21:37:50,969 INFO  org.apache.flink.runtime.taskmanager.TaskManager              - Temporary file directory '/tmp': total 80 GB, usable 4 GB (5.00% usable)
2016-06-21 21:37:51,010 INFO  org.apache.flink.runtime.io.network.buffer.NetworkBufferPool  - Allocated 64 MB for network buffer pool (number of memory segments: 2048, bytes per segment: 32768).
2016-06-21 21:37:51,054 INFO  org.apache.flink.runtime.taskmanager.TaskManager              - Limiting managed memory to 0.7 of the currently free heap space (293 MB), memory will be allocated lazily.
2016-06-21 21:37:51,061 INFO  org.apache.flink.runtime.io.disk.iomanager.IOManager          - I/O manager uses directory /tmp/flink-io-f704dddb-3a47-4ce7-91bd-36eb352f3da4 for spill files.
2016-06-21 21:37:51,066 INFO  org.apache.flink.runtime.filecache.FileCache                  - User file cache uses directory /tmp/flink-dist-cache-85a16f4f-0bcf-4460-9dfb-fb28b76c4abc
2016-06-21 21:37:51,182 INFO  org.apache.flink.runtime.taskmanager.TaskManager              - Starting TaskManager actor at akka://flink/user/taskmanager#438721231.
2016-06-21 21:37:51,183 INFO  org.apache.flink.runtime.taskmanager.TaskManager              - TaskManager data connection information: namenode (dataPort=37627)
2016-06-21 21:37:51,183 INFO  org.apache.flink.runtime.taskmanager.TaskManager              - TaskManager has 4 task slot(s).
2016-06-21 21:37:51,184 INFO  org.apache.flink.runtime.taskmanager.TaskManager              - Memory usage stats: [HEAP: 90/494/494 MB, NON HEAP: 25/36/304 MB (used/committed/max)]
2016-06-21 21:37:51,186 INFO  org.apache.flink.runtime.taskmanager.TaskManager              - Trying to register at JobManager akka.tcp://flink@10.0.10.2:6123/user/jobmanager (attempt 1, timeout: 500 milliseconds)
2016-06-21 21:37:51,269 INFO  org.apache.flink.runtime.taskmanager.TaskManager              - Successful registration at JobManager (akka.tcp://flink@10.0.10.2:6123/user/jobmanager), starting network stack and library cache.
2016-06-21 21:37:51,364 INFO  org.apache.flink.runtime.io.network.netty.NettyClient         - Successful initialization (took 21 ms).
2016-06-21 21:37:51,384 INFO  org.apache.flink.runtime.io.network.netty.NettyServer         - Successful initialization (took 20 ms). Listening on SocketAddress /10.0.10.2:37627.
2016-06-21 21:37:51,385 INFO  org.apache.flink.runtime.taskmanager.TaskManager              - Determined BLOB server address to be /10.0.10.2:45916. Starting BLOB cache.
2016-06-21 21:37:51,386 INFO  org.apache.flink.runtime.blob.BlobCache                       - Created BLOB cache storage directory /tmp/blobStore-60b3a4e2-3224-4547-bec5-3d6c20faa9d4
2016-06-21 21:38:01,726 INFO  org.apache.flink.runtime.taskmanager.TaskManager              - Received task CHAIN DataSource (at org.apache.flink.ml.MLUtils$.readLibSVM(MLUtils.scala:56) (org.apache.flink.api.java.io.TextInputFormat)) -> FlatMap (FlatMap at org.apache.flink.ml.MLUtils$.readLibSVM(MLUtils.scala:56)) (1/1)
2016-06-21 21:38:01,726 INFO  org.apache.flink.runtime.taskmanager.Task                     - Loading JAR files for task CHAIN DataSource (at org.apache.flink.ml.MLUtils$.readLibSVM(MLUtils.scala:56) (org.apache.flink.api.java.io.TextInputFormat)) -> FlatMap (FlatMap at org.apache.flink.ml.MLUtils$.readLibSVM(MLUtils.scala:56)) (1/1)
2016-06-21 21:38:01,727 INFO  org.apache.flink.runtime.blob.BlobCache                       - Downloading 0783e1290f5fc6e7471caa835db050d65b4ee77b from /10.0.10.2:45916
2016-06-21 21:38:01,988 INFO  org.apache.flink.runtime.taskmanager.Task                     - Registering task at network: CHAIN DataSource (at org.apache.flink.ml.MLUtils$.readLibSVM(MLUtils.scala:56) (org.apache.flink.api.java.io.TextInputFormat)) -> FlatMap (FlatMap at org.apache.flink.ml.MLUtils$.readLibSVM(MLUtils.scala:56)) (1/1) [DEPLOYING]
2016-06-21 21:38:01,990 INFO  org.apache.flink.runtime.taskmanager.Task                     - CHAIN DataSource (at org.apache.flink.ml.MLUtils$.readLibSVM(MLUtils.scala:56) (org.apache.flink.api.java.io.TextInputFormat)) -> FlatMap (FlatMap at org.apache.flink.ml.MLUtils$.readLibSVM(MLUtils.scala:56)) (1/1) switched to RUNNING
2016-06-21 21:38:02,389 INFO  org.apache.flink.runtime.taskmanager.Task                     - CHAIN DataSource (at org.apache.flink.ml.MLUtils$.readLibSVM(MLUtils.scala:56) (org.apache.flink.api.java.io.TextInputFormat)) -> FlatMap (FlatMap at org.apache.flink.ml.MLUtils$.readLibSVM(MLUtils.scala:56)) (1/1) switched to FINISHED
2016-06-21 21:38:02,389 INFO  org.apache.flink.runtime.taskmanager.Task                     - Freeing task resources for CHAIN DataSource (at org.apache.flink.ml.MLUtils$.readLibSVM(MLUtils.scala:56) (org.apache.flink.api.java.io.TextInputFormat)) -> FlatMap (FlatMap at org.apache.flink.ml.MLUtils$.readLibSVM(MLUtils.scala:56)) (1/1)
2016-06-21 21:38:02,390 INFO  org.apache.flink.runtime.taskmanager.TaskManager              - Un-registering task and sending final execution state FINISHED to JobManager for task CHAIN DataSource (at org.apache.flink.ml.MLUtils$.readLibSVM(MLUtils.scala:56) (org.apache.flink.api.java.io.TextInputFormat)) -> FlatMap (FlatMap at org.apache.flink.ml.MLUtils$.readLibSVM(MLUtils.scala:56)) (42bd9838c8c8854a59d551c60058cb84)
2016-06-21 21:38:02,440 INFO  org.apache.flink.runtime.taskmanager.TaskManager              - Received task Map (Map at org.apache.flink.ml.MLUtils$.readLibSVM(MLUtils.scala:89)) (1/1)
2016-06-21 21:38:02,441 INFO  org.apache.flink.runtime.taskmanager.Task                     - Loading JAR files for task Map (Map at org.apache.flink.ml.MLUtils$.readLibSVM(MLUtils.scala:89)) (1/1)
2016-06-21 21:38:02,441 INFO  org.apache.flink.runtime.taskmanager.TaskManager              - Received task CHAIN Map (Map at org.apache.flink.ml.MLUtils$.readLibSVM(MLUtils.scala:84)) -> Reduce (Reduce at org.apache.flink.ml.MLUtils$.readLibSVM(MLUtils.scala:87)) (1/1)
2016-06-21 21:38:02,441 INFO  org.apache.flink.runtime.taskmanager.Task                     - Loading JAR files for task CHAIN Map (Map at org.apache.flink.ml.MLUtils$.readLibSVM(MLUtils.scala:84)) -> Reduce (Reduce at org.apache.flink.ml.MLUtils$.readLibSVM(MLUtils.scala:87)) (1/1)
2016-06-21 21:38:02,442 INFO  org.apache.flink.runtime.taskmanager.Task                     - Registering task at network: Map (Map at org.apache.flink.ml.MLUtils$.readLibSVM(MLUtils.scala:89)) (1/1) [DEPLOYING]
2016-06-21 21:38:02,442 INFO  org.apache.flink.runtime.taskmanager.Task                     - Registering task at network: CHAIN Map (Map at org.apache.flink.ml.MLUtils$.readLibSVM(MLUtils.scala:84)) -> Reduce (Reduce at org.apache.flink.ml.MLUtils$.readLibSVM(MLUtils.scala:87)) (1/1) [DEPLOYING]
2016-06-21 21:38:02,442 INFO  org.apache.flink.runtime.taskmanager.Task                     - Map (Map at org.apache.flink.ml.MLUtils$.readLibSVM(MLUtils.scala:89)) (1/1) switched to RUNNING
2016-06-21 21:38:02,442 INFO  org.apache.flink.runtime.taskmanager.Task                     - CHAIN Map (Map at org.apache.flink.ml.MLUtils$.readLibSVM(MLUtils.scala:84)) -> Reduce (Reduce at org.apache.flink.ml.MLUtils$.readLibSVM(MLUtils.scala:87)) (1/1) switched to RUNNING
2016-06-21 21:38:02,590 INFO  org.apache.flink.runtime.taskmanager.Task                     - CHAIN Map (Map at org.apache.flink.ml.MLUtils$.readLibSVM(MLUtils.scala:84)) -> Reduce (Reduce at org.apache.flink.ml.MLUtils$.readLibSVM(MLUtils.scala:87)) (1/1) switched to FINISHED
2016-06-21 21:38:02,591 INFO  org.apache.flink.runtime.taskmanager.Task                     - Freeing task resources for CHAIN Map (Map at org.apache.flink.ml.MLUtils$.readLibSVM(MLUtils.scala:84)) -> Reduce (Reduce at org.apache.flink.ml.MLUtils$.readLibSVM(MLUtils.scala:87)) (1/1)
2016-06-21 21:38:02,591 INFO  org.apache.flink.runtime.taskmanager.TaskManager              - Un-registering task and sending final execution state FINISHED to JobManager for task CHAIN Map (Map at org.apache.flink.ml.MLUtils$.readLibSVM(MLUtils.scala:84)) -> Reduce (Reduce at org.apache.flink.ml.MLUtils$.readLibSVM(MLUtils.scala:87)) (cced7111b758d66060f133cfae1892b3)
2016-06-21 21:38:02,711 INFO  org.apache.flink.runtime.taskmanager.TaskManager              - Received task CHAIN MapPartition (MapPartition at ml.dmlc.xgboost4j.scala.flink.XGBoost$.train(XGBoost.scala:90)) -> Reduce (Reduce at ml.dmlc.xgboost4j.scala.flink.XGBoost$.train(XGBoost.scala:91)) (1/1)
2016-06-21 21:38:02,712 INFO  org.apache.flink.runtime.taskmanager.Task                     - Loading JAR files for task CHAIN MapPartition (MapPartition at ml.dmlc.xgboost4j.scala.flink.XGBoost$.train(XGBoost.scala:90)) -> Reduce (Reduce at ml.dmlc.xgboost4j.scala.flink.XGBoost$.train(XGBoost.scala:91)) (1/1)
2016-06-21 21:38:02,712 INFO  org.apache.flink.runtime.taskmanager.Task                     - Registering task at network: CHAIN MapPartition (MapPartition at ml.dmlc.xgboost4j.scala.flink.XGBoost$.train(XGBoost.scala:90)) -> Reduce (Reduce at ml.dmlc.xgboost4j.scala.flink.XGBoost$.train(XGBoost.scala:91)) (1/1) [DEPLOYING]
2016-06-21 21:38:02,712 INFO  org.apache.flink.runtime.taskmanager.Task                     - _CHAIN MapPartition (MapPartition at ml.dmlc.xgboost4j.scala.flink.XGBoost$.train(XGBoost.scala:90)) -> Reduce (Reduce at ml.dmlc.xgboost4j.scala.flink.XGBoost$.train(XGBoost.scala:91)) (1/1) switched to RUNNING_
2016-06-21 21:38:02,723 INFO  ml.dmlc.xgboost4j.scala.flink.XGBoost$MapFunction             - start with env{DMLC_TRACKER_URI=10.0.10.2, DMLC_NUM_WORKER=1, DMLC_TASK_ID=0, DMLC_TRACKER_PORT=9107, DMLC_NUM_SERVER=0}
2016-06-21 21:38:02,844 INFO  org.apache.flink.runtime.taskmanager.Task                     - Map (Map at org.apache.flink.ml.MLUtils$.readLibSVM(MLUtils.scala:89)) (1/1) switched to FINISHED
2016-06-21 21:38:02,844 INFO  org.apache.flink.runtime.taskmanager.Task                     - Freeing task resources for Map (Map at org.apache.flink.ml.MLUtils$.readLibSVM(MLUtils.scala:89)) (1/1)
2016-06-21 21:38:02,844 INFO  org.apache.flink.runtime.taskmanager.TaskManager              - Un-registering task and sending final execution state FINISHED to JobManager for task Map (Map at org.apache.flink.ml.MLUtils$.readLibSVM(MLUtils.scala:89)) (bcf4662410a187024eb9bafb1fdd6834)
`

Any idea about what's the problem?

Thanks.
G.

**Comment by pommedeterresautee** [comment]
Bug related to an old version, closing.
