### ISSUE TITLE
[jvm-packages]mvn package failed with test error. Only one SparkContext may be running in this JVM

### ISSUE THREAD

**Issue by Earthson** [dmlc/xgboost#1361]
Is it a good idea to make a singleton SparkContext?

```
  org.apache.spark.SparkException: Only one SparkContext may be running in this JVM (see SPARK-2243). To ignore this error, set spark.driver.allowMultipleContexts = true. The currently running SparkContext was created at:
org.apache.spark.SparkContext.<init>(SparkContext.scala:82)
ml.dmlc.xgboost4j.scala.spark.XGBoostSuite$$anonfun$6.apply$mcV$sp(XGBoostSuite.scala:183)
ml.dmlc.xgboost4j.scala.spark.XGBoostSuite$$anonfun$6.apply(XGBoostSuite.scala:176)
ml.dmlc.xgboost4j.scala.spark.XGBoostSuite$$anonfun$6.apply(XGBoostSuite.scala:176)
org.scalatest.Transformer$$anonfun$apply$1.apply$mcV$sp(Transformer.scala:22)
org.scalatest.OutcomeOf$class.outcomeOf(OutcomeOf.scala:85)
org.scalatest.OutcomeOf$.outcomeOf(OutcomeOf.scala:104)
org.scalatest.Transformer.apply(Transformer.scala:22)
org.scalatest.Transformer.apply(Transformer.scala:20)
org.scalatest.FunSuiteLike$$anon$1.apply(FunSuiteLike.scala:166)
org.scalatest.Suite$class.withFixture(Suite.scala:1122)
org.scalatest.FunSuite.withFixture(FunSuite.scala:1555)
org.scalatest.FunSuiteLike$class.invokeWithFixture$1(FunSuiteLike.scala:163)
org.scalatest.FunSuiteLike$$anonfun$runTest$1.apply(FunSuiteLike.scala:175)
org.scalatest.FunSuiteLike$$anonfun$runTest$1.apply(FunSuiteLike.scala:175)
org.scalatest.SuperEngine.runTestImpl(Engine.scala:306)
org.scalatest.FunSuiteLike$class.runTest(FunSuiteLike.scala:175)
ml.dmlc.xgboost4j.scala.spark.XGBoostSuite.org$scalatest$BeforeAndAfter$$super$runTest(XGBoostSuite.scala:36)
org.scalatest.BeforeAndAfter$class.runTest(BeforeAndAfter.scala:200)
ml.dmlc.xgboost4j.scala.spark.XGBoostSuite.runTest(XGBoostSuite.scala:36)
```

**Comment by CodingCat** [comment]
it is constraint from Spark, only one SparkContext can run in a JVM instance

and in test cases, we have some cases that we have to use different configurations than the normal ones...so we need to close the previous one and start a new SparkContext, 

in most of cases, if you see this error, that means, your previous test cases have failed

**Comment by dusj** [comment]
I got the same error. there is some log may bofore JVM error.

-

NFO RabitTracker$TrackerProcessLogger: Exception AttributeError: "'RabitTracker' object has no attribute 'sock'" in <bound method RabitTracker.__del__ of <__main__.RabitTracker object at 0x103ca7d90>> ignored
16/07/15 19:43:42 INFO RabitTracker$TrackerProcessLogger: Tracker Process ends with exit code 1
16/07/15 19:43:42 INFO RabitTracker: Tracker Process ends with exit code 1
16/07/15 19:43:42 INFO XGBoostSpark: Rabit returns with exit code 1
16/07/15 19:43:42 INFO SparkContext: Starting job: foreachPartition at XGBoost.scala:125
Exception in thread "Thread-51" java.lang.InterruptedException
	at java.lang.Object.wait(Native Method)
	at java.lang.Object.wait(Object.java:502)
	at org.apache.spark.scheduler.JobWaiter.awaitResult(JobWaiter.scala:73)
	at org.apache.spark.scheduler.DAGScheduler.runJob(DAGScheduler.scala:612)
	at org.apache.spark.SparkContext.runJob(SparkContext.scala:1832)
	at org.apache.spark.SparkContext.runJob(SparkContext.scala:1845)
	at org.apache.spark.SparkContext.runJob(SparkContext.scala:1858)
	at org.apache.spark.SparkContext.runJob(SparkContext.scala:1929)
	at org.apache.spark.rdd.RDD$$anonfun$foreachPartition$1.apply(RDD.scala:920)
	at org.apache.spark.rdd.RDD$$anonfun$foreachPartition$1.apply(RDD.scala:918)
	at org.apache.spark.rdd.RDDOperationScope$.withScope(RDDOperationScope.scala:150)
	at org.apache.spark.rdd.RDDOperationScope$.withScope(RDDOperationScope.scala:111)
	at org.apache.spark.rdd.RDD.withScope(RDD.scala:316)
	at org.apache.spark.rdd.RDD.foreachPartition(RDD.scala:918)
	at ml.dmlc.xgboost4j.scala.spark.XGBoost$$anon$2.run(XGBoost.scala:125)
16/07/15 19:43:42 INFO DAGScheduler: Got job 0 (foreachPartition at XGBoost.scala:125) with 8 output partitions
16/07/15 19:43:42 INFO DAGScheduler: Final stage: ResultStage 0 (foreachPartition at XGBoost.scala:125)
16/07/15 19:43:42 INFO DAGScheduler: Parents of final stage: List()
16/07/15 19:43:42 INFO DAGScheduler: Missing parents: List()
16/07/15 19:43:42 INFO DAGScheduler: Submitting ResultStage 0 (MapPartitionsRDD[1] at mapPartitions at XGBoost.scala:60), which has no missing parents
- save and load model *** FAILED ***
  ml.dmlc.xgboost4j.java.XGBoostError: XGBoostModel training failed
  at ml.dmlc.xgboost4j.scala.spark.XGBoost$.train(XGBoost.scala:142)
  at ml.dmlc.xgboost4j.scala.spark.XGBoostSuite$$anonfun$4.apply$mcV$sp(XGBoostSuite.scala:152)
  at ml.dmlc.xgboost4j.scala.spark.XGBoostSuite$$anonfun$4.apply(XGBoostSuite.scala:142)
  at ml.dmlc.xgboost4j.scala.spark.XGBoostSuite$$anonfun$4.apply(XGBoostSuite.scala:142)
  at org.scalatest.Transformer$$anonfun$apply$1.apply$mcV$sp(Transformer.scala:22)
  at org.scalatest.OutcomeOf$class.outcomeOf(OutcomeOf.scala:85)
  at org.scalatest.OutcomeOf$.outcomeOf(OutcomeOf.scala:104)
  at org.scalatest.Transformer.apply(Transformer.scala:22)
  at org.scalatest.Transformer.apply(Transformer.scala:20)
  at org.scalatest.FunSuiteLike$$anon$1.apply(FunSuiteLike.scala:166)
  ...
....
INFO RabitTracker$TrackerProcessLogger: Exception AttributeError: "'RabitTracker' object has no attribute 'sock'" in <bound method RabitTracker.__del__ of <__main__.RabitTracker object at 0x10123ad90>> ignored
16/07/15 19:43:43 INFO RabitTracker$TrackerProcessLogger: Tracker Process ends with exit code 1
16/07/15 19:43:43 INFO RabitTracker: Tracker Process ends with exit code 1
16/07/15 19:43:43 INFO XGBoostSpark: Rabit returns with exit code 1
- kryoSerializer test *** FAILED ***
  ml.dmlc.xgboost4j.java.XGBoostError: XGBoostModel training failed
  at ml.dmlc.xgboost4j.scala.spark.XGBoost$.train(XGBoost.scala:142)
  at ml.dmlc.xgboost4j.scala.spark.XGBoostSuite$$anonfun$6.apply$mcV$sp(XGBoostSuite.scala:190)
  at ml.dmlc.xgboost4j.scala.spark.XGBoostSuite$$anonfun$6.apply(XGBoostSuite.scala:176)
  at ml.dmlc.xgboost4j.scala.spark.XGBoostSuite$$anonfun$6.apply(XGBoostSuite.scala:176)
  at org.scalatest.Transformer$$anonfun$apply$1.apply$mcV$sp(Transformer.scala:22)
  at org.scalatest.OutcomeOf$class.outcomeOf(OutcomeOf.scala:85)
  at org.scalatest.OutcomeOf$.outcomeOf(OutcomeOf.scala:104)
  at org.scalatest.Transformer.apply(Transformer.scala:22)
  at org.scalatest.Transformer.apply(Transformer.scala:20)
  at org.scalatest.FunSuiteLike$$anon$1.apply(FunSuiteLike.scala:166)
  ...
-----
ERROR Inbox: Ignoring error
java.lang.NullPointerException
	at org.apache.spark.storage.BlockManagerMasterEndpoint.org$apache$spark$storage$BlockManagerMasterEndpoint$$updateBlockInfo(BlockManagerMasterEndpoint.scala:332)
	at org.apache.spark.storage.BlockManagerMasterEndpoint$$anonfun$receiveAndReply$1.applyOrElse(BlockManagerMasterEndpoint.scala:64)
	at org.apache.spark.rpc.netty.Inbox$$anonfun$process$1.apply$mcV$sp(Inbox.scala:104)
	at org.apache.spark.rpc.netty.Inbox.safelyCall(Inbox.scala:204)
	at org.apache.spark.rpc.netty.Inbox.process(Inbox.scala:100)
	at org.apache.spark.rpc.netty.Dispatcher$MessageLoop.run(Dispatcher.scala:215)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
16/07/15 19:43:43 WARN NettyRpcEndpointRef: Error sending message [message = UpdateBlockInfo(null,broadcast_0_piece0,StorageLevel(false, true, false, false, 1),2262,0,0)] in 1 attempts
java.lang.NullPointerException
	at org.apache.spark.storage.BlockManagerMasterEndpoint.org$apache$spark$storage$BlockManagerMasterEndpoint$$updateBlockInfo(BlockManagerMasterEndpoint.scala:332)
	at org.apache.spark.storage.BlockManagerMasterEndpoint$$anonfun$receiveAndReply$1.applyOrElse(BlockManagerMasterEndpoint.scala:64)
	at org.apache.spark.rpc.netty.Inbox$$anonfun$process$1.apply$mcV$sp(Inbox.scala:104)
	at org.apache.spark.rpc.netty.Inbox.safelyCall(Inbox.scala:204)
	at org.apache.spark.rpc.netty.Inbox.process(Inbox.scala:100)
	at org.apache.spark.rpc.netty.Dispatcher$MessageLoop.run(Dispatcher.scala:215)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)**

**Comment by CodingCat** [comment]
your rabit tracker cannot be started successfully,
