### ISSUE TITLE
[xgboost4j-spark] XGBoostModel training failed

### ISSUE THREAD

**Issue by Earthson** [dmlc/xgboost#1362]
Here is the test code. There is no tracker info, how to print more log info?

```scala
class XGBoostTest extends SparkFlatSpec {
  "xgboost" should "pass" in {
    val trainRDD = MLUtils.loadLibSVMFile(sc, "test_data/a9a/a9a").map(p => LabeledPoint((p.label + 1)/2 toInt, p.features))
    val testRDD = MLUtils.loadLibSVMFile(sc, "test_data/a9a/a9a.t").map(p => LabeledPoint((p.label + 1)/2 toInt, p.features)).map(_.features)
    trainRDD.map(_.label).distinct().collect().foreach(println)
    val paramMap = List(
      "eta" -> 0.1f,
      "max_depth" -> 2,
      "objective" -> "binary:logistic",
//      "objective" -> "multi:softprob",
      "silent" -> 0
    ).toMap
    val xgboostModel = XGBoost.train(trainRDD, paramMap, 10, nWorkers = 2,
      useExternalMemory = false)
    xgboostModel.predict(testRDD).take(10).foreach(println)
  }

}
```

```
10:13:16,959 |-INFO in ch.qos.logback.core.joran.action.AppenderRefAction - Attaching appender named [SOCKET] to Logger[com.mininglamp.whale]
10:13:16,959 |-INFO in ch.qos.logback.classic.joran.action.ConfigurationAction - End of configuration.
10:13:16,961 |-INFO in ch.qos.logback.classic.joran.JoranConfigurator@729d991e - Registering current configuration as safe fallback point

0.0
1.0
Tracker started, with env={}

Exception in thread "Thread-19" java.lang.InterruptedException
	at java.lang.Object.wait(Native Method)
	at java.lang.Object.wait(Object.java:502)
	at org.apache.spark.scheduler.JobWaiter.awaitResult(JobWaiter.scala:73)
	at org.apache.spark.scheduler.DAGScheduler.runJob(DAGScheduler.scala:612)
	at org.apache.spark.SparkContext.runJob(SparkContext.scala:1832)
	at org.apache.spark.SparkContext.runJob(SparkContext.scala:1845)
	at org.apache.spark.SparkContext.runJob(SparkContext.scala:1858)
	at org.apache.spark.SparkContext.runJob(SparkContext.scala:1929)
	at org.apache.spark.rdd.RDD$$anonfun$foreachPartition$1.apply(RDD.scala:920)
	at org.apache.spark.rdd.RDD$$anonfun$foreachPartition$1.apply(RDD.scala:918)
	at org.apache.spark.rdd.RDDOperationScope$.withScope(RDDOperationScope.scala:150)
	at org.apache.spark.rdd.RDDOperationScope$.withScope(RDDOperationScope.scala:111)
	at org.apache.spark.rdd.RDD.withScope(RDD.scala:316)
	at org.apache.spark.rdd.RDD.foreachPartition(RDD.scala:918)
	at ml.dmlc.xgboost4j.scala.spark.XGBoost$$anon$2.run(XGBoost.scala:125)

XGBoostModel training failed
ml.dmlc.xgboost4j.java.XGBoostError: XGBoostModel training failed
	at ml.dmlc.xgboost4j.scala.spark.XGBoost$.train(XGBoost.scala:142)
	at com.mininglamp.whale.algo.mlamp.XGBoostTest$$anonfun$1.apply$mcV$sp(XGBoostTest.scala:23)
	at com.mininglamp.whale.algo.mlamp.XGBoostTest$$anonfun$1.apply(XGBoostTest.scala:12)
	at com.mininglamp.whale.algo.mlamp.XGBoostTest$$anonfun$1.apply(XGBoostTest.scala:12)
	at org.scalatest.Transformer$$anonfun$apply$1.apply$mcV$sp(Transformer.scala:22)
	at org.scalatest.OutcomeOf$class.outcomeOf(OutcomeOf.scala:85)
	at org.scalatest.OutcomeOf$.outcomeOf(OutcomeOf.scala:104)
	at org.scalatest.Transformer.apply(Transformer.scala:22)
	at org.scalatest.Transformer.apply(Transformer.scala:20)
	at org.scalatest.FlatSpecLike$$anon$1.apply(FlatSpecLike.scala:1647)
	at org.scalatest.Suite$class.withFixture(Suite.scala:1122)
	at org.scalatest.FlatSpec.withFixture(FlatSpec.scala:1683)
	at org.scalatest.FlatSpecLike$class.invokeWithFixture$1(FlatSpecLike.scala:1644)
	at org.scalatest.FlatSpecLike$$anonfun$runTest$1.apply(FlatSpecLike.scala:1656)
	at org.scalatest.FlatSpecLike$$anonfun$runTest$1.apply(FlatSpecLike.scala:1656)
	at org.scalatest.SuperEngine.runTestImpl(Engine.scala:306)
	at org.scalatest.FlatSpecLike$class.runTest(FlatSpecLike.scala:1656)
	at org.scalatest.FlatSpec.runTest(FlatSpec.scala:1683)
	at org.scalatest.FlatSpecLike$$anonfun$runTests$1.apply(FlatSpecLike.scala:1714)
	at org.scalatest.FlatSpecLike$$anonfun$runTests$1.apply(FlatSpecLike.scala:1714)
	at org.scalatest.SuperEngine$$anonfun$traverseSubNodes$1$1.apply(Engine.scala:413)
	at org.scalatest.SuperEngine$$anonfun$traverseSubNodes$1$1.apply(Engine.scala:401)
	at scala.collection.immutable.List.foreach(List.scala:318)
	at org.scalatest.SuperEngine.traverseSubNodes$1(Engine.scala:401)
	at org.scalatest.SuperEngine.org$scalatest$SuperEngine$$runTestsInBranch(Engine.scala:390)
	at org.scalatest.SuperEngine$$anonfun$traverseSubNodes$1$1.apply(Engine.scala:427)
	at org.scalatest.SuperEngine$$anonfun$traverseSubNodes$1$1.apply(Engine.scala:401)
	at scala.collection.immutable.List.foreach(List.scala:318)
	at org.scalatest.SuperEngine.traverseSubNodes$1(Engine.scala:401)
```

**Comment by Earthson** [comment]
Here is the error log:

```
WhaleWeb: 2016-07-15 14:18:27,382 WARNING gethostbyname(socket.getfqdn()) failed... trying on hostname() 
WhaleWeb: Traceback (most recent call last): 
WhaleWeb:   File "/var/folders/0d/3mztrjr17md3g_gxqxkyj0680000gn/T/tracker6385215584284864342.py", line 475, in <module> 
WhaleWeb:     main() 
WhaleWeb:   File "/var/folders/0d/3mztrjr17md3g_gxqxkyj0680000gn/T/tracker6385215584284864342.py", line 470, in main 
WhaleWeb:     start_rabit_tracker(args) 
WhaleWeb:   File "/var/folders/0d/3mztrjr17md3g_gxqxkyj0680000gn/T/tracker6385215584284864342.py", line 432, in start_rabit_tracker 
WhaleWeb:     rabit = RabitTracker(hostIP=get_host_ip(args.host_ip), nslave=args.num_workers) 
WhaleWeb:   File "/var/folders/0d/3mztrjr17md3g_gxqxkyj0680000gn/T/tracker6385215584284864342.py", line 396, in get_host_ip 
WhaleWeb:     s.connect(('10.255.255.255', 0)) 
WhaleWeb: OSError: [Errno 49] Can't assign requested address 
WhaleWeb: Tracker Process ends with exit code 1 
WhaleWeb: Tracker Process ends with exit code 1 
WhaleWeb: Rabit returns with exit code 1 
```

**Comment by Earthson** [comment]
I found it does not accept port 0 on my OS X.

**Comment by Earthson** [comment]
Another error found: 

```
Tracker started, with env={DMLC_NUM_SERVER=0, DMLC_TRACKER_URI=10.100.21.247, DMLC_TRACKER_PORT=9091, DMLC_NUM_WORKER=2}
WhaleWeb: 2016-07-15 14:50:25,817 WARNING gethostbyname(socket.getfqdn()) failed... trying on hostname() 
WhaleWeb: 2016-07-15 14:50:25,819 INFO start listen on 10.100.21.247:9091 
WhaleWeb: Starting job: foreachPartition at XGBoost.scala:125 
WhaleWeb: Size of output statuses for shuffle 0 is 152 bytes 
WhaleWeb: Got job 3 (foreachPartition at XGBoost.scala:125) with 2 output partitions 
WhaleWeb: Final stage: ResultStage 6 (foreachPartition at XGBoost.scala:125) 
WhaleWeb: Parents of final stage: List(ShuffleMapStage 5) 
WhaleWeb: Missing parents: List() 
WhaleWeb: Submitting ResultStage 6 (MapPartitionsRDD[25] at mapPartitions at XGBoost.scala:60), which has no missing parents 
WhaleWeb: Block broadcast_7 stored as values in memory (estimated size 7.6 KB, free 11.8 MB) 
WhaleWeb: Block broadcast_7_piece0 stored as bytes in memory (estimated size 3.5 KB, free 11.8 MB) 
WhaleWeb: Added broadcast_7_piece0 in memory on localhost:53708 (size: 3.5 KB, free: 5.1 GB) 
WhaleWeb: Created broadcast 7 from broadcast at DAGScheduler.scala:1006 
WhaleWeb: Submitting 2 missing tasks from ResultStage 6 (MapPartitionsRDD[25] at mapPartitions at XGBoost.scala:60) 
WhaleWeb: Adding task set 6.0 with 2 tasks 
WhaleWeb: Starting task 0.0 in stage 6.0 (TID 10, localhost, partition 0,NODE_LOCAL, 2163 bytes) 
WhaleWeb: Starting task 1.0 in stage 6.0 (TID 11, localhost, partition 1,NODE_LOCAL, 2163 bytes) 
WhaleWeb: Running task 1.0 in stage 6.0 (TID 11) 
WhaleWeb: Running task 0.0 in stage 6.0 (TID 10) 
WhaleWeb: Partition rdd_25_0 not found, computing it 
WhaleWeb: Partition rdd_25_1 not found, computing it 
AssertError:ReConnectLink failure 2
```

**Comment by Earthson** [comment]
@CodingCat

**Comment by Earthson** [comment]
@CodingCat 

```
AssertError:ReConnectLink failure 2
Socket RecvAll Error:Connection reset by peer
WhaleWeb: Exception in thread Thread-1: 
WhaleWeb: Traceback (most recent call last): 
WhaleWeb:   File "/Users/earthson/env/opt/anaconda/lib/python3.5/threading.py", line 914, in _bootstrap_inner 
WhaleWeb:     self.run() 
WhaleWeb:   File "/Users/earthson/env/opt/anaconda/lib/python3.5/threading.py", line 862, in run 
WhaleWeb:     self._target(*self._args, **self._kwargs) 
WhaleWeb:   File "/var/folders/0d/3mztrjr17md3g_gxqxkyj0680000gn/T/tracker3233851401813438455.py", line 324, in run 
WhaleWeb:     self.accept_slaves(nslave) 
WhaleWeb:   File "/var/folders/0d/3mztrjr17md3g_gxqxkyj0680000gn/T/tracker3233851401813438455.py", line 268, in accept_slaves 
WhaleWeb:     s = SlaveEntry(fd, s_addr) 
WhaleWeb:   File "/var/folders/0d/3mztrjr17md3g_gxqxkyj0680000gn/T/tracker3233851401813438455.py", line 63, in __init__ 
WhaleWeb:     magic = slave.recvint() 
WhaleWeb:   File "/var/folders/0d/3mztrjr17md3g_gxqxkyj0680000gn/T/tracker3233851401813438455.py", line 39, in recvint 
WhaleWeb:     return struct.unpack('@i', self.recvall(4))[0] 
WhaleWeb:   File "/var/folders/0d/3mztrjr17md3g_gxqxkyj0680000gn/T/tracker3233851401813438455.py", line 37, in recvall 
WhaleWeb:     return ''.join(res) 
WhaleWeb: TypeError: sequence item 0: expected str instance, bytes found 
WhaleWeb:  

Process finished with exit code 255
```

**Comment by Earthson** [comment]
I'm using Python 3.5

**Comment by Earthson** [comment]
with `b''.join(res)` I got 

```
AssertError:ReConnectLink failure 4
```

**Comment by Earthson** [comment]
@CodingCat How could I get Python stacktrace? It always returned with AssertError: ReConnectLink.

**Comment by CodingCat** [comment]
it seems that the connection between the rabit worker and tracker is broken....would you check the Spark executor logs and see if there is any hint on what happened?

**Comment by Earthson** [comment]
Finally all test passed, I'll submit a PR for Python 3 compability

**Comment by CodingCat** [comment]
sure thanks
