### ISSUE TITLE
[jvm-packages] An error :UnsatisfiedLinkError when run in spark

### ISSUE THREAD

**Issue by dusj** [dmlc/xgboost#1364]
I worked in a mac, and the cluster is centos. when i make a jar upload cluster to run, i got this erro.  
-------------------------------------------------
WARN TaskSetManager: Lost task 2.0 in stage 4.0 (TID 4016, rz-data-hdp-dn2034.rz.sankuai.com): java.lang.UnsatisfiedLinkError: ml.dmlc.xgboost4j.java.XGBoostJNI.RabitInit([Ljava/lang/String;)I
	at ml.dmlc.xgboost4j.java.XGBoostJNI.RabitInit(Native Method)
	at ml.dmlc.xgboost4j.java.Rabit.init(Rabit.java:42)
	at ml.dmlc.xgboost4j.scala.spark.XGBoost$$anonfun$buildDistributedBoosters$1.apply(XGBoost.scala:63)
	at ml.dmlc.xgboost4j.scala.spark.XGBoost$$anonfun$buildDistributedBoosters$1.apply(XGBoost.scala:61)
	at org.apache.spark.rdd.RDD$$anonfun$mapPartitions$1$$anonfun$apply$17.apply(RDD.scala:706)
	at org.apache.spark.rdd.RDD$$anonfun$mapPartitions$1$$anonfun$apply$17.apply(RDD.scala:706)
	at org.apache.spark.rdd.MapPartitionsRDD.compute(MapPartitionsRDD.scala:38)
	at org.apache.spark.rdd.RDD.computeOrReadCheckpoint(RDD.scala:297)
	at org.apache.spark.CacheManager.getOrCompute(CacheManager.scala:69)
	at org.apache.spark.rdd.RDD.iterator(RDD.scala:262)
	at org.apache.spark.scheduler.ResultTask.runTask(ResultTask.scala:66)
	at org.apache.spark.scheduler.Task.run(Task.scala:88)
	at org.apache.spark.executor.Executor$TaskRunner.run(Executor.scala:214)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615)
	at java.lang.Thread.run(Thread.java:745)

16/07/15 20:17:47 INFO TaskSetManager: Lost task 9.0 in stage 4.0 (TID 4023) on executor rz-data-hdp-dn3748.rz.sankuai.com: java.lang.UnsatisfiedLinkError (ml.dmlc.xgboost4j.java.XGBoostJNI.RabitInit([Ljava/lang/String;)I) [duplicate 1]
16/07/15 20:17:47 INFO TaskSetManager: Starting task 9.1 in stage 4.0 (TID 4044, rz-data-hdp-dn0385.rz.sankuai.com, PROCESS_LOCAL, 2243 bytes)

**Comment by CodingCat** [comment]
you have to rebuild the library in centos, as in linux, jvm will find *.so as the extension of the native lib files, but in MacOS it is dylib

**Comment by dusj** [comment]
i solve this peoblem by edit file "create_jni.sh".  let ${dl} to be so

**Comment by saksim** [comment]
> you have to rebuild the library in centos, as in linux, jvm will find *.so as the extension of the native lib files, but in MacOS it is dylib

Hello~This is a newcomer in xgboost-spark. Thanks for this issue because I got this error tortures me for a moment. Actually, What I want to confirm is the manner whether I can use the JAR package with dependency in the other same version platform but with different gcc/python environment【e.g. i compile in CENTOS 6.5 with gcc-5/gcc-7 and get the JAR package with dependency,ca i use the JAR in a spark cluster with gcc-4 or other different environment】 when I  have packaged all program by following the official guide compile & using maven package the jvm-package?

Thanks for your help~
Best Wishes.
