### ISSUE TITLE
hdfsBuilderConnect

### ISSUE THREAD

**Issue by shengshen** [dmlc/xgboost#1374]
Any body encounter this issue. as  following:
hdfsBuilderConnect(forceNewInstance=0, nn=, port=0, kerbTicketCachePath=(NULL), userName=(NULL)) error:
java.lang.IllegalArgumentException: Expected authority at index 7: hdfs://
    at java.net.URI.create(URI.java:859)
Caused by: java.net.URISyntaxException: Expected authority at index 7: hdfs://
    at java.net.URI$Parser.fail(URI.java:2827)
    at java.net.URI$Parser.failExpecting(URI.java:2833)
    at java.net.URI$Parser.parseHierarchical(URI.java:3081)
    at java.net.URI$Parser.parse(URI.java:3032)
    at java.net.URI.<init>(URI.java:595)
    at java.net.URI.create(URI.java:857)
[18:05:49] include/dmlc/logging.h:241: [18:05:49] src/io/hdfs_filesys.cc:95: Failed to load HDFS-configuration:
terminate called after throwing an instance of 'dmlc::Error'
  what():  [18:05:49] src/io/hdfs_filesys.cc:95: Failed to load HDFS-configuration:

**Comment by shengshen** [comment]
I get the solution. The core of the issue is the path. When i set the full path like this :hdfs://$3/data/agaricus.txt.train. it runs ok. The $3 parameter can be my hostname or ip:port.
