### ISSUE TITLE
[xgboost4j-spark] Check failed: label_error >= 0 && label_error < nclass SoftmaxMultiClassObj: label must be in [0, num_class), num_class=2 but found 17 in label.

### ISSUE THREAD

**Issue by Earthson** [dmlc/xgboost#1379]
```scala
// labels: 0.0,1.0
tracker.debug(s"labels: ${trainRDD.map(_.label).distinct().collect().mkString(",")}")
val model: XGBoostModel = XGBoost.train(trainRDD, paramMap, numRoundC, nWorkers = numExec, useExternalMemory = true)
```

```
Caused by: ml.dmlc.xgboost4j.java.XGBoostError: [18:46:40] src/objective/multiclass_obj.cc:75: Check failed: label_error >= 0 && label_error < nclass SoftmaxMultiClassObj: label must be in [0, num_class), num_class=2 but found 17 in label.
	at ml.dmlc.xgboost4j.java.JNIErrorHandle.checkCall(JNIErrorHandle.java:48)
	at ml.dmlc.xgboost4j.java.Booster.update(Booster.java:133)
	at ml.dmlc.xgboost4j.java.XGBoost.train(XGBoost.java:117)
	at ml.dmlc.xgboost4j.scala.XGBoost$.train(XGBoost.scala:51)
	at ml.dmlc.xgboost4j.scala.spark.XGBoost$$anonfun$buildDistributedBoosters$1.apply(XGBoost.scala:74)
	at ml.dmlc.xgboost4j.scala.spark.XGBoost$$anonfun$buildDistributedBoosters$1.apply(XGBoost.scala:61)
	at org.apache.spark.rdd.RDD$$anonfun$mapPartitions$1$$anonfun$apply$20.apply(RDD.scala:710)
	at org.apache.spark.rdd.RDD$$anonfun$mapPartitions$1$$anonfun$apply$20.apply(RDD.scala:710)
	at org.apache.spark.rdd.MapPartitionsRDD.compute(MapPartitionsRDD.scala:38)
	at org.apache.spark.rdd.RDD.computeOrReadCheckpoint(RDD.scala:306)
	at org.apache.spark.CacheManager.getOrCompute(CacheManager.scala:69)
	at org.apache.spark.rdd.RDD.iterator(RDD.scala:268)
	at org.apache.spark.scheduler.ResultTask.runTask(ResultTask.scala:66)
	at org.apache.spark.scheduler.Task.run(Task.scala:89)
	at org.apache.spark.executor.Executor$TaskRunner.run(Executor.scala:227)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
```

**Comment by Earthson** [comment]
@CodingCat

**Comment by Earthson** [comment]
I can't reproduce this bug today, really strange~

**Comment by sghanukota** [comment]
i am getting the same error, need help to resolve
