### ISSUE TITLE
[jvm-packages] Hanging up during "mvn package" test,  And an Error ClassNotFound in spark-cluster

### ISSUE THREAD

**Issue by dusj** [dmlc/xgboost#1382]
## I have deal with xgboost-spark for two weeks. but still can't running it in spark. There's two problem.  First problem is "mvn package" ,  I run it in a centos6.5 machine. It always hang up at spark-tests step.  after two hours,  I have to press ctr-c. 
16/07/20 13:30:19 INFO CacheManager: Partition rdd_10_1 not found, computing it
16/07/20 13:30:19 INFO CacheManager: Partition rdd_10_0 not found, computing it
16/07/20 14:00:19 INFO BlockManagerInfo: Removed broadcast_0_piece0 on localhost:35587 in memory (size: 1667.0 B, free: 1087.1 MB)
^C16/07/20 16:59:09 INFO RabitTracker$TrackerProcessLogger: Traceback (most recent call last):
16/07/20 16:59:09 INFO RabitTracker$TrackerProcessLogger:   File "/tmp/tracker5428704971120844141.py", line 480, in <module>
16/07/20 16:59:09 INFO RabitTracker$TrackerProcessLogger:     main()
16/07/20 16:59:09 INFO RabitTracker$TrackerProcessLogger:   File "/tmp/tracker5428704971120844141.py", line 475, in main
16/07/20 16:59:09 INFO RabitTracker$TrackerProcessLogger:     start_rabit_tracker(args)
16/07/20 16:59:09 INFO RabitTracker$TrackerProcessLogger:   File "/tmp/tracker5428704971120844141.py", line 442, in start_rabit_tracker
16/07/20 16:59:09 INFO RabitTracker$TrackerProcessLogger:     rabit.join()
16/07/20 16:59:09 INFO RabitTracker$TrackerProcessLogger:   File "/tmp/tracker5428704971120844141.py", line 332, in join

## Another problem occured when I skip tests and run a test program in spark1.5 cluster.  An error called "ClassNotFound:XGBoostError.class"  always arise.  and program hang up too. I think there may be some relation between these two program. So I put them together. I will appreciate If anyone can help me.

16/07/20 17:07:25 WARN ThrowableSerializationWrapper: Task exception could not be deserialized
java.lang.ClassNotFoundException: ml.dmlc.xgboost4j.java.XGBoostError
	at java.net.URLClassLoader$1.run(URLClassLoader.java:366)
	at java.net.URLClassLoader$1.run(URLClassLoader.java:355)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.net.URLClassLoader.findClass(URLClassLoader.java:354)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:425)
	at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:308)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:358)
	at java.lang.Class.forName0(Native Method)
	at java.lang.Class.forName(Class.java:274)
	at org.apache.spark.serializer.JavaDeserializationStream$$anon

**Comment by dusj** [comment]
[Uploading ClassNotFound.txt…]()

**Comment by dusj** [comment]
[Uploading MvnPackagError.txt…]()
[Uploading MvnPackagError.pdf…]()

**Comment by CodingCat** [comment]
I cannot see what happened in `mvn package` case, it seems that your tracker script cannot be run

**Comment by dusj** [comment]
@CodingCat  thinks for your reply. There's one things I have forgot to say. The spark-cluster use a python2.6, and xgboost has some code in python2.7. I don't have permission to change the cluster. So I have changed the tracker.py to run in cluster. The Only thing I have changed is "import argparse" --> "import optparse"  and change some code about argparse, I dont think it's matters. Is this problem comes with python2.6 and I have to use python2.7?  thinks a lot.

**Comment by dusj** [comment]
## Logs before task stop.
16/07/21 11:50:38 INFO Client: Application report for application_1468926081807_414233 (state: RUNNING)
16/07/21 11:50:39 INFO Client: Application report for application_1468926081807_414233 (state: FINISHED)
16/07/21 11:50:39 INFO Client: 
	 client token: Token { kind: YARN_CLIENT_TOKEN, service:  }
	 diagnostics: N/A
	 ApplicationMaster host: 10.16.47.28
	 ApplicationMaster RPC port: 0
	 queue: root.hadoop-waimai.etltest
	 start time: 1469072773519
	 final status: FAILED
	 tracking URL: http://rz-data-hdp-rm01.rz.sankuai.com:8088/proxy/application_1468926081807_414233/
	 user: hadoop-waimai
Exception in thread "main" org.apache.spark.SparkException: Application application_1468926081807_414233 finished with failed status
	at org.apache.spark.deploy.yarn.Client.run(Client.scala:920)
	at org.apache.spark.deploy.yarn.Client$.main(Client.scala:966)
	at org.apache.spark.deploy.yarn.Client.main(Client.scala)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:606)
	at org.apache.spark.deploy.SparkSubmit$.org$apache$spark$deploy$SparkSubmit$$runMain(SparkSubmit.scala:672)
	at org.apache.spark.deploy.SparkSubmit$.doRunMain$1(SparkSubmit.scala:180)
	at org.apache.spark.deploy.SparkSubmit$.submit(SparkSubmit.scala:205)
	at org.apache.spark.deploy.SparkSubmit$.main(SparkSubmit.scala:120)
	at org.apache.spark.deploy.SparkSubmit.main(SparkSubmit.scala)
16/07/21 11:50:39 INFO ShutdownHookManager: Shutdown hook called
16/07/21 11:50:39 INFO ShutdownHookManager: Deleting directory /tmp/spark-656cdaf9-7adb-477d-9e00-8a9e0ff85366
KILL SPARK APPLICATION:  
    export HADOOP_JAR_AUTHENTICATION=KERBEROS
    export HADOOP_JAR_KERBEROS_KEYTAB_FILE=/etc/hadoop/keytabs/hadoop-launcher.keytab
    export HADOOP_JAR_KERBEROS_PRINCIPAL=hadoop-launcher/_HOST@SANKUAI.COM
    export HADOOP_PROXY_USER=hadoop-waimai
    /opt/meituan/hadoop/bin/yarn application -kill application_1468926081807_414233
16/07/21 11:50:40 INFO client.RMProxy: Connecting to ResourceManager at rz-data-hdp-rm01.rz.sankuai.com/10.16.32.3:8032
Application application_1468926081807_414233 has already finished 
Traceback (most recent call last):
  File "/opt/meituan/warehouse/ETL/sqlweaver/../sqlweaver/step.py", line 119, in act
    self.actionclass.run(step = self)
  File "/opt/meituan/warehouse/ETL/sqlweaver/../sqlweaver/action/base.py", line 60, in run
    cls.__run__(step)
  File "/opt/meituan/warehouse/ETL/sqlweaver/../sqlweaver/action/sparkjobsubmit.py", line 43, in __run__
    handler.submit_job(step.template, step.args['submit_user'])
  File "/opt/meituan/warehouse/ETL/sqlweaver/../sqlweaver/handler/SparkHandler.py", line 128, in submit_job
    raise RuntimeError(msg_f)
RuntimeError: <StringIO.StringIO instance at 0x2dfa9e0>
Traceback (most recent call last):
  File "/opt/meituan/warehouse/ETL/sqlweaver/../sqlweaver/engine/koala.py", line 34, in process
    step.act()
  File "/opt/meituan/warehouse/ETL/sqlweaver/../sqlweaver/step.py", line 128, in act
    raise e
RuntimeError: <StringIO.StringIO instance at 0x2dfa9e0>
Fail in Action Step(SparkJobSubmit)

**Comment by CodingCat** [comment]
I think it is likely the modification of the tracker introduces some bugs

@tqchen , the second case where python 2.6 brings the issue

**Comment by dusj** [comment]
I find the reason: one test cant pass. The test is in xgbosot-spark test, called "test with dense vectors containing missing value". I will continue debug this.

**Comment by dusj** [comment]
it is a problem about python2.6

**Comment by omdv** [comment]
I actually have this issue with python 2.7.9 on google cloud dataproc cluster, running Debian 8 jessie.

Stops at:
16/08/24 21:23:26 INFO CacheManager: Partition rdd_10_0 not found, computing it
16/08/24 21:23:26 INFO CacheManager: Partition rdd_10_1 not found, computing it

**Comment by borntoburnyo** [comment]
@omdv Can you share how to run xgboost on google cloud dataproc, I got stuck.. Thanks!
