### ISSUE TITLE
v0.4 DMatrix error, "file offset not calculated correctly"

### ISSUE THREAD

**Issue by flyingdisc** [dmlc/xgboost#1390]
Yesterday I used **previous** version of XGBoost (I forget the version, maybe 0.32), I could read a large libsvm file **succesfully**, in both Python and R version. (OS: Windows 7)

Today I installed newest version (0.4) in Python and R. 
For Python I followed this installation instruction: https://github.com/dmlc/xgboost/issues/1316. 
For R, I installed weekly updated drat repo, https://github.com/dmlc/xgboost/tree/master/R-package. 

Then, I read the same libsvm file, I got this error in Python, 

```
[11:40:04] src/io/input_split_base.cc:182: curr=3900499184,begin=0,end=18446744073315083504,fileptr=0,fileoffset=18446744073315083504
[11:40:04] dmlc-core/include/dmlc/logging.h:245: [11:40:04] src/io/input_split_base.cc:190: file offset not calculated correctly
Traceback (most recent call last):
  File "create_inter4.py", line 488, in <module>
    test_svm()
  File "create_inter4.py", line 482, in test_svm
    df = xgb.DMatrix("eval_interactions.svm")
  File "C:\Anaconda2\lib\site-packages\xgboost-0.4-py2.7.egg\xgboost\core.py", line 262, in __init__
    ctypes.byref(self.handle)))
  File "C:\Anaconda2\lib\site-packages\xgboost-0.4-py2.7.egg\xgboost\core.py", line 127, in _check_call
    raise XGBoostError(_LIB.XGBGetLastError())
xgboost.core.XGBoostError: [11:40:04] src/io/input_split_base.cc:190: file offset not calculated correctly
```

The same error in R: 

```
[11:43:19] amalgamation/../dmlc-core/src/io/input_split_base.cc:182: curr=3900499184,begin=0,end=18446744073315083504,fileptr=0,fileoffset=18446744073315083504
Error in xgb.DMatrix("eval_interactions.svm") : 
  [11:43:19] amalgamation/../dmlc-core/src/io/input_split_base.cc:190: file offset not calculated correctly
```

What's wrong? Thank you. 

Note: the libsvm file is created by using sklearn's `dump_svmlight_file()`. 
Then I tried to create the libsvm text file with my own script. Both got the same error.

**Comment by pommedeterresautee** [comment]
Old version. Closing.
