### ISSUE TITLE
[jvm-packages] Running xgboost on the yarn-cluster  with the error [/lib64/libc.so.6: version `GLIBC_2.14']

### ISSUE THREAD

**Issue by yxzf** [dmlc/xgboost#1391]
I successfully compile the jvm-packages on a centos 7.0 with gcc-4.8.2. And it also can run on the local spark-1.5.1.

Then I submit the demo on the yarn-cluster, and I have the error. 
=================================================
16/07/22 20:54:13 WARN scheduler.TaskSetManager: Lost task 1.0 in stage 5.0 (TID 11, rz-data-hdp-dn2113.rz.***.com): java.lang.UnsatisfiedLinkError: /data8/hadoop/yarn/nm-local-dir/usercache/hadoop-pay-dev/appcache/application_1468926081807_765036/container_1468926081807_765036_01_000003/tmp/libxgboost4j4481460359283600466.so: /lib64/libc.so.6: version `GLIBC_2.14' not found (required by /data8/hadoop/yarn/nm-local-dir/usercache/hadoop-pay-dev/appcache/application_1468926081807_765036/container_1468926081807_765036_01_000003/tmp/libxgboost4j4481460359283600466.so)
	at java.lang.ClassLoader$NativeLibrary.load(Native Method)
	at java.lang.ClassLoader.loadLibrary1(ClassLoader.java:1965)
	at java.lang.ClassLoader.loadLibrary0(ClassLoader.java:1890)
	at java.lang.ClassLoader.loadLibrary(ClassLoader.java:1851)
	at java.lang.Runtime.load0(Runtime.java:795)
	at java.lang.System.load(System.java:1062)
	at ml.dmlc.xgboost4j.java.NativeLibLoader.loadLibraryFromJar(NativeLibLoader.java:67)
	at ml.dmlc.xgboost4j.java.NativeLibLoader.smartLoad(NativeLibLoader.java:153)
	at ml.dmlc.xgboost4j.java.NativeLibLoader.initXGBoost(NativeLibLoader.java:41)
	at ml.dmlc.xgboost4j.java.Rabit.<clinit>(Rabit.java:18)
	at ml.dmlc.xgboost4j.scala.spark.XGBoost$$anonfun$buildDistributedBoosters$1.apply(XGBoost.scala:63)
	at ml.dmlc.xgboost4j.scala.spark.XGBoost$$anonfun$buildDistributedBoosters$1.apply(XGBoost.scala:61)
	at org.apache.spark.rdd.RDD$$anonfun$mapPartitions$1$$anonfun$apply$17.apply(RDD.scala:706)
	at org.apache.spark.rdd.RDD$$anonfun$mapPartitions$1$$anonfun$apply$17.apply(RDD.scala:706)
	at org.apache.spark.rdd.MapPartitionsRDD.compute(MapPartitionsRDD.scala:38)
	at org.apache.spark.rdd.RDD.computeOrReadCheckpoint(RDD.scala:297)
	at org.apache.spark.CacheManager.getOrCompute(CacheManager.scala:69)
	at org.apache.spark.rdd.RDD.iterator(RDD.scala:262)
	at org.apache.spark.scheduler.ResultTask.runTask(ResultTask.scala:66)
	at org.apache.spark.scheduler.Task.run(Task.scala:88)
	at org.apache.spark.executor.Executor$TaskRunner.run(Executor.scala:214)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615)
	at java.lang.Thread.run(Thread.java:745)

16/07/22 20:54:13 INFO scheduler.TaskSetManager: Starting task 1.1 in stage 5.0 (TID 13, rz-data-hdp-dn2113.rz.***.com, PROCESS_LOCAL, 2170 bytes)
16/07/22 20:54:13 WARN scheduler.TaskSetManager: Lost task 0.0 in stage 5.0 (TID 10, rz-data-hdp-dn2113.rz.***.com): java.lang.NoClassDefFoundError: Could not initialize class ml.dmlc.xgboost4j.java.Rabit
	at ml.dmlc.xgboost4j.scala.spark.XGBoost$$anonfun$buildDistributedBoosters$1.apply(XGBoost.scala:63)
	at ml.dmlc.xgboost4j.scala.spark.XGBoost$$anonfun$buildDistributedBoosters$1.apply(XGBoost.scala:61)
	at org.apache.spark.rdd.RDD$$anonfun$mapPartitions$1$$anonfun$apply$17.apply(RDD.scala:706)
	at org.apache.spark.rdd.RDD$$anonfun$mapPartitions$1$$anonfun$apply$17.apply(RDD.scala:706)
	at org.apache.spark.rdd.MapPartitionsRDD.compute(MapPartitionsRDD.scala:38)
	at org.apache.spark.rdd.RDD.computeOrReadCheckpoint(RDD.scala:297)
	at org.apache.spark.CacheManager.getOrCompute(CacheManager.scala:69)
	at org.apache.spark.rdd.RDD.iterator(RDD.scala:262)
	at org.apache.spark.scheduler.ResultTask.runTask(ResultTask.scala:66)
	at org.apache.spark.scheduler.Task.run(Task.scala:88)
	at org.apache.spark.executor.Executor$TaskRunner.run(Executor.scala:214)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615)
	at java.lang.Thread.run(Thread.java:745)
=================================================

**Comment by CodingCat** [comment]
it might be caused by the different native dev env between your local machine and the cluster, 

as it said `/lib64/libc.so.6: version `GLIBC_2.14' not found `

**Comment by CodingCat** [comment]
you can compile xgboost in the cluster and run....

**Comment by zhangweijiqn** [comment]
the same problem:
16/09/22 21:18:16.339 WARN TaskSetManager: Lost task 3.0 in stage 4.0 (TID 11, BDS-TEST-004): java.lang.UnsatisfiedLinkError: /export/tmp/hadoop-tmp/nm-local-dir/usercache/root/appcache/application_1473064938887_0277/container_1473064938887_0277_01_000003/tmp/libxgboost4j2443518406039170105.so: /lib64/libc.so.6: version `GLIBC_2.15' not found (required by /export/tmp/hadoop-tmp/nm-local-dir/usercache/root/appcache/application_1473064938887_0277/container_1473064938887_0277_01_000003/tmp/libxgboost4j2443518406039170105.so)
        at java.lang.ClassLoader$NativeLibrary.load(Native Method)
        at java.lang.ClassLoader.loadLibrary0(ClassLoader.java:1938)
        at java.lang.ClassLoader.loadLibrary(ClassLoader.java:1821)
        at java.lang.Runtime.load0(Runtime.java:809)
        at java.lang.System.load(System.java:1086)
        at ml.dmlc.xgboost4j.java.NativeLibLoader.loadLibraryFromJar(NativeLibLoader.java:67)
        at ml.dmlc.xgboost4j.java.NativeLibLoader.smartLoad(NativeLibLoader.java:153)
        at ml.dmlc.xgboost4j.java.NativeLibLoader.initXGBoost(NativeLibLoader.java:41)
        at ml.dmlc.xgboost4j.java.Rabit.<clinit>(Rabit.java:18)
        at ml.dmlc.xgboost4j.scala.spark.XGBoost$$anonfun$buildDistributedBoosters$1.apply(XGBoost.scala:88)
        at ml.dmlc.xgboost4j.scala.spark.XGBoost$$anonfun$buildDistributedBoosters$1.apply(XGBoost.scala:86)
        at org.apache.spark.rdd.RDD$$anonfun$mapPartitions$1$$anonfun$apply$23.apply(RDD.scala:766)
        at org.apache.spark.rdd.RDD$$anonfun$mapPartitions$1$$anonfun$apply$23.apply(RDD.scala:766)
        at org.apache.spark.rdd.MapPartitionsRDD.compute(MapPartitionsRDD.scala:38)
        at org.apache.spark.rdd.RDD.computeOrReadCheckpoint(RDD.scala:319)
        at org.apache.spark.rdd.RDD$$anonfun$8.apply(RDD.scala:332)
        at org.apache.spark.rdd.RDD$$anonfun$8.apply(RDD.scala:330)
        at org.apache.spark.storage.BlockManager$$anonfun$doPutIterator$1.apply(BlockManager.scala:919)
        at org.apache.spark.storage.BlockManager$$anonfun$doPutIterator$1.apply(BlockManager.scala:910)
        at org.apache.spark.storage.BlockManager.doPut(BlockManager.scala:866)
        at org.apache.spark.storage.BlockManager.doPutIterator(BlockManager.scala:910)
        at org.apache.spark.storage.BlockManager.getOrElseUpdate(BlockManager.scala:668)
        at org.apache.spark.rdd.RDD.getOrCompute(RDD.scala:330)
        at org.apache.spark.rdd.RDD.iterator(RDD.scala:281)
        at org.apache.spark.scheduler.ResultTask.runTask(ResultTask.scala:70)
        at org.apache.spark.scheduler.Task.run(Task.scala:85)
        at org.apache.spark.executor.Executor$TaskRunner.run(Executor.scala:274)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
        at java.lang.Thread.run(Thread.java:745)

**Comment by wpopielarski** [comment]
@CodingCat I'm not sure about your advice but I can be wrong. My local version is 2.19 and I was able to compile and run xgboost on my local but same build is saying me that 2.15 is required. It looks like some `C` code is declaring this dependency so probably the only way is just to bumping up GLIBC to at least 2.15

**Comment by CodingCat** [comment]
can you try the pre-built version from maven https://mvnrepository.com/artifact/ml.dmlc/xgboost4j-spark/0.72

it uses a very old of glibc to compile, so should be compatible for most scenarios

**Comment by wpopielarski** [comment]
@CodingCat sorry for confusing you, you're right with advice to build xgboost on cluster there it targets to be used

**Comment by CodingCat** [comment]
@wpopielarski as I mentioned, we have released pre-built version from maven, you can directly refer to the dependency in your project

**Comment by wpopielarski** [comment]
link you gave is just pure jvm artifact, you would need to give a link to jar with dependencies, I'm really sad that my admins are not willing to bump up glic version :sob:
