### ISSUE TITLE
Is there any solutions or suggestions?

### ISSUE THREAD

**Issue by RamonYeung** [dmlc/xgboost#1440]
```linux
Traceback (most recent call last):
    import xgboost
  File "D:\Anaconda2\lib\site-packages\xgboost-0.6-py2.7.egg\xgboost\__init__.py", line 11, in <module>
    from .core import DMatrix, Booster
  File "D:\Anaconda2\lib\site-packages\xgboost-0.6-py2.7.egg\xgboost\core.py", line 112, in <module>
    _LIB = _load_lib()
  File "D:\Anaconda2\lib\site-packages\xgboost-0.6-py2.7.egg\xgboost\core.py", line 106, in _load_lib
    lib = ctypes.cdll.LoadLibrary(lib_path[0])
  File "D:\Anaconda2\lib\ctypes\__init__.py", line 440, in LoadLibrary
    return self._dlltype(name)
  File "D:\Anaconda2\lib\ctypes\__init__.py", line 362, in __init__
    self._handle = _dlopen(self._name, mode)
WindowsError: [Error 127] 
```

OS: Win 8.1 
Python Version: 2.7.12

**Comment by RamonYeung** [comment]
I fixed this by re-install Anaconda (one of Python distributions) because I guess there are some damage about my origin standard Python module named `ctypes`. 

Maybe I should do the `conda remove` and `conda install` stuff. 

:)
