### ISSUE TITLE
error in xgboost sklearn api

### ISSUE THREAD

**Issue by upperli** [dmlc/xgboost#1483]
the fit function doesn't work when set the eval_set in xgboost 0.60.It works in xgboost 0.47

**Comment by terrytangyuan** [comment]
Could you post a reproducible example?

**Comment by upperli** [comment]
`
clf = xgb.XGBClassifier(learning_rate=0.1,n_estimators=100,max_depth=9,subsample=0.9,colsample_bytree=0.7)

clf.fit(train_x, train_y,eval_set=[(test_x,test_y)],eval_metric = pr_metric, verbose = 1)
`
where pr_metric is:
`
def pr_metric(y_predicted, y_true):
    y = y_true.get_label()
    precision, recall, _ = precision_recall_curve(y == 0, 1 - y_predicted)
    max_recall = 0.0
    for p, r in zip(precision, recall):
        if p >= 0.97 and r > max_recall:
            max_recall = r
    return ('97%% Precision Recall',max_recall)
`

the error is:
`
Traceback (most recent call last):
  File "step2_train.py", line 118, in <module>
    run() 
  File "step2_train.py", line 78, in run
    clf.fit(train_x, train_y,sample_weight = train_y + 0.8,eval_set=[(test_x,test_y)],eval_metric = pr_metric, verbose = 1)
  File "/usr/local/lib/python2.7/dist-packages/xgboost-0.6-py2.7.egg/xgboost/sklearn.py", line 445, in fit
    verbose_eval=verbose)
  File "/usr/local/lib/python2.7/dist-packages/xgboost-0.6-py2.7.egg/xgboost/training.py", line 203, in train
    xgb_model=xgb_model, callbacks=callbacks)
  File "/usr/local/lib/python2.7/dist-packages/xgboost-0.6-py2.7.egg/xgboost/training.py", line 90, in _train_internal
    evaluation_result_list = [(k, float(v)) for k, v in res[1:]]
ValueError: need more than 1 value to unpack
`
