### ISSUE TITLE
STUCK at RabitTracker.waitFor

### ISSUE THREAD

**Issue by regzhuce** [dmlc/xgboost#1595]
For master branch, it's stuck at RabitTracker.waitFor event when I run the test cases, such as ml.dmlc.xgboost4j.scala.spark.XGBoostGeneralSuite.test("test model consistency after save and load").

Didn't you guys pass the test cases when you merge code master? Can not image that.

I got this by jstack:
`"ScalaTest-run-running-XGBoostGeneralSuite" prio=5 tid=0x00007fe365002000 nid=0x1703 in Object.wait() [0x0000700000216000]
   java.lang.Thread.State: WAITING (on object monitor)
	at java.lang.Object.wait(Native Method)
	- waiting on <0x00000007004a44a8> (a java.lang.UNIXProcess)
	at java.lang.Object.wait(Object.java:503)
	at java.lang.UNIXProcess.waitFor(UNIXProcess.java:262)
	- locked <0x00000007004a44a8> (a java.lang.UNIXProcess)
	at ml.dmlc.xgboost4j.java.RabitTracker.waitFor(RabitTracker.java:147)
	at ml.dmlc.xgboost4j.scala.spark.XGBoost$.trainWithRDD(XGBoost.scala:209)
	at ml.dmlc.xgboost4j.scala.spark.XGBoostGeneralSuite$$anonfun$7.apply$mcV$sp(XGBoostGeneralSuite.scala:169)
	at ml.dmlc.xgboost4j.scala.spark.XGBoostGeneralSuite$$anonfun$7.apply(XGBoostGeneralSuite.scala:159)
	at ml.dmlc.xgboost4j.scala.spark.XGBoostGeneralSuite$$anonfun$7.apply(XGBoostGeneralSuite.scala:159)
	at org.scalatest.Transformer$$anonfun$apply$1.apply$mcV$sp(Transformer.scala:22)
	at org.scalatest.OutcomeOf$class.outcomeOf(OutcomeOf.scala:85)
	at org.scalatest.OutcomeOf$.outcomeOf(OutcomeOf.scala:104)
	at org.scalatest.Transformer.apply(Transformer.scala:22)
	at org.scalatest.Transformer.apply(Transformer.scala:20)
	at org.scalatest.FunSuiteLike$$anon$1.apply(FunSuiteLike.scala:166)
	at org.scalatest.Suite$class.withFixture(Suite.scala:1122)
	at org.scalatest.FunSuite.withFixture(FunSuite.scala:1555)
	at org.scalatest.FunSuiteLike$class.invokeWithFixture$1(FunSuiteLike.scala:163)
	at org.scalatest.FunSuiteLike$$anonfun$runTest$1.apply(FunSuiteLike.scala:175)
	at org.scalatest.FunSuiteLike$$anonfun$runTest$1.apply(FunSuiteLike.scala:175)
	at org.scalatest.SuperEngine.runTestImpl(Engine.scala:306)
	at org.scalatest.FunSuiteLike$class.runTest(FunSuiteLike.scala:175)
	at ml.dmlc.xgboost4j.scala.spark.SharedSparkContext.org$scalatest$BeforeAndAfter$$super$runTest(SharedSparkContext.scala:22)
	at org.scalatest.BeforeAndAfter$class.runTest(BeforeAndAfter.scala:200)
	at ml.dmlc.xgboost4j.scala.spark.SharedSparkContext.runTest(SharedSparkContext.scala:22)
	at org.scalatest.FunSuiteLike$$anonfun$runTests$1.apply(FunSuiteLike.scala:208)
	at org.scalatest.FunSuiteLike$$anonfun$runTests$1.apply(FunSuiteLike.scala:208)
	at org.scalatest.SuperEngine$$anonfun$traverseSubNodes$1$1.apply(Engine.scala:413)
	at org.scalatest.SuperEngine$$anonfun$traverseSubNodes$1$1.apply(Engine.scala:401)
	at scala.collection.immutable.List.foreach(List.scala:381)
	at org.scalatest.SuperEngine.traverseSubNodes$1(Engine.scala:401)
	at org.scalatest.SuperEngine.org$scalatest$SuperEngine$$runTestsInBranch(Engine.scala:396)
	at org.scalatest.SuperEngine.runTestsImpl(Engine.scala:483)
	at org.scalatest.FunSuiteLike$class.runTests(FunSuiteLike.scala:208)
	at org.scalatest.FunSuite.runTests(FunSuite.scala:1555)
	at org.scalatest.Suite$class.run(Suite.scala:1424)
	at org.scalatest.FunSuite.org$scalatest$FunSuiteLike$$super$run(FunSuite.scala:1555)
	at org.scalatest.FunSuiteLike$$anonfun$run$1.apply(FunSuiteLike.scala:212)
	at org.scalatest.FunSuiteLike$$anonfun$run$1.apply(FunSuiteLike.scala:212)
	at org.scalatest.SuperEngine.runImpl(Engine.scala:545)
	at org.scalatest.FunSuiteLike$class.run(FunSuiteLike.scala:212)
	at ml.dmlc.xgboost4j.scala.spark.SharedSparkContext.org$scalatest$BeforeAndAfter$$super$run(SharedSparkContext.scala:22)
	at org.scalatest.BeforeAndAfter$class.run(BeforeAndAfter.scala:241)
	at ml.dmlc.xgboost4j.scala.spark.SharedSparkContext.run(SharedSparkContext.scala:22)`

**Comment by CodingCat** [comment]
Yes, we passed the test cases

**Comment by regzhuce** [comment]
But I cannot pass them on my Mac laptop.
What' wrong?
