### ISSUE TITLE
[jvm-packages] XGBoost in spark-shell: SIGSEGV at libjvm.so

### ISSUE THREAD

**Issue by tcarette** [dmlc/xgboost#1635]
I have the same problem as in issue #1061 at XGBoost.train on a dataset of 12k (1% of my full dataset for the test) rows with about 4500 features. But the fix doesn't seem to work for me: I start my spark-shell (v2.0.0) in local mode on a 16Gb ram MacBook Pro with

spark-shell --jars xgboost4j-spark-0.7-jar-with-dependencies.jar --master local[*] --driver-memory 12G --conf "spark.serializer=org.apache.spark.serializer.KryoSerializer" --conf "spark.kryo.classesToRegister=ml.dmlc.xgboost4j.java.Booster"

Here is the way I call XGBoost.train (it's just a test, so I didn't really pay attention to the options)
```
val data = MLUtils.loadLibSVMFile(sc,outputFolder + modelFolder + "training")
  .sample(withReplacement=false,fraction=0.01)
  .persist()

val paramMap = Map(
  "eta" -> 0.1f,
  "max_depth" -> 2,
  "objective" -> "binary:logistic",
  "eval_metric" -> "merror")

val model = XGBoost.train(
  data,
  paramMap,
  round = 5,
  nWorkers = 8,
  useExternalMemory = true)      
```             

The jar is built on commit 37bc122c90b7c1337403f797fb7b01fc6abd5b36. 

Here is the error

```
#
# A fatal error has been detected by the Java Runtime Environment:
#
#  SIGSEGV (0xb) at pc=0x000000010e17cacc, pid=61751, tid=43267
#
# JRE version: Java(TM) SE Runtime Environment (8.0_91-b14) (build 1.8.0_91-b14)
# Java VM: Java HotSpot(TM) 64-Bit Server VM (25.91-b14 mixed mode bsd-amd64 compressed oops)
# Problematic frame:
# V  [libjvm.dylib+0x57cacc]  UTF8::unicode_length(char const*)+0x4
[hs_err_pid61751.log.zip](https://github.com/dmlc/xgboost/files/508252/hs_err_pid61751.log.zip)


```

logs: [hs_err_pid61751.log.zip](https://github.com/dmlc/xgboost/files/508264/hs_err_pid61751.log.zip)

For the sake of completeness (but I guess it's unrelated), I have a lot of warnings of the type
```
16/10/04 12:50:33 WARN BlockManager: Putting block rdd_4_183 failed
16/10/04 12:50:33 WARN MemoryStore: Not enough space to cache rdd_4_182 in memory! (computed 7.1 MB so far)
```
when loading the data and running the model.

**Comment by CodingCat** [comment]
try to remove `"eval_metric" -> "merror"` if you're working on a binary classification problem

**Comment by tcarette** [comment]
right... I didn't even check. But I added it because I saw something somewhere. The behaviour doesn't change with or without.

**Comment by CodingCat** [comment]
from the log you provide, I can see the program crashes when evaluating model, and I cannot reproduce it without `"eval_metric" -> "merror"`

BTW, if you have only 4 cores in your laptop, nWorkers shall be no less than 4 since XGBoost  requires all workers running simultaneously

**Comment by tcarette** [comment]
Ok, however, it worked with an error when I increased the sampling fraction
```
Tracker started, with env={}                                                    
Exception in thread "Thread-30" java.lang.InterruptedException
        at java.util.concurrent.locks.AbstractQueuedSynchronizer.acquireSharedInterruptibly(AbstractQueuedSynchronizer.java:1302)
        at scala.concurrent.impl.Promise$DefaultPromise.tryAwait(Promise.scala:202)
        at scala.concurrent.impl.Promise$DefaultPromise.ready(Promise.scala:218)
        at scala.concurrent.impl.Promise$DefaultPromise.ready(Promise.scala:153)
        at org.apache.spark.scheduler.DAGScheduler.runJob(DAGScheduler.scala:623)
        at org.apache.spark.SparkContext.runJob(SparkContext.scala:1871)
        at org.apache.spark.SparkContext.runJob(SparkContext.scala:1884)
        at org.apache.spark.SparkContext.runJob(SparkContext.scala:1897)
        at org.apache.spark.SparkContext.runJob(SparkContext.scala:1911)
        at org.apache.spark.rdd.RDD$$anonfun$foreachPartition$1.apply(RDD.scala:883)
        at org.apache.spark.rdd.RDD$$anonfun$foreachPartition$1.apply(RDD.scala:881)
        at org.apache.spark.rdd.RDDOperationScope$.withScope(RDDOperationScope.scala:151)
        at org.apache.spark.rdd.RDDOperationScope$.withScope(RDDOperationScope.scala:112)
        at org.apache.spark.rdd.RDD.withScope(RDD.scala:358)
        at org.apache.spark.rdd.RDD.foreachPartition(RDD.scala:881)
        at ml.dmlc.xgboost4j.scala.spark.XGBoost$$anon$2.run(XGBoost.scala:205)
ml.dmlc.xgboost4j.java.XGBoostError: XGBoostModel training failed
  at ml.dmlc.xgboost4j.scala.spark.XGBoost$.trainWithRDD(XGBoost.scala:222)
  at ml.dmlc.xgboost4j.scala.spark.XGBoost$.train(XGBoost.scala:164)
  ... 53 elided
```

But still failed with both errors when increasing the sampling fraction to 50%

```
# A fatal error has been detected by the Java Runtime Environment:
#
#  SIGSEGV (0xb) at pc=0x0000000102d130a5, pid=65253, tid=42759
#
# JRE version: Java(TM) SE Runtime Environment (8.0_91-b14) (build 1.8.0_91-b14)
# Java VM: Java HotSpot(TM) 64-Bit Server VM (25.91-b14 mixed mode bsd-amd64 compressed oops)
# Problematic frame:
# V  [libjvm.dylib+0x3130a5]
```

logs: [hs_err_pid65253.log.zip](https://github.com/dmlc/xgboost/files/509138/hs_err_pid65253.log.zip)


PS: there are 4 cores in my i7, but it sums to 8 logical processors, right?

**Comment by CodingCat** [comment]
depends....e.g. the i7 on my macbook pro does not have hyperthreading enabled

for the first error, `Tracker started, with env={} ` means that your rabit does not start correctly 

for the second error, the java frame is different with the previous one....I think it might be related to the fact that the RDD occupies a lot of memory and GC reclaimed some space and somehow makes the program access the illegal native memory space

**Comment by tcarette** [comment]
Ok, thanks, I'll check the rabit stuff.

For the main problem, I guess I'll have to try a smaller model...
