### ISSUE TITLE
[jvm-packages] The program runs problem & xgboost4j-0.5-maven package error.

### ISSUE THREAD

**Issue by jeromehj** [dmlc/xgboost#1682]
For bugs or installation issues, please provide the following information.
The more information you provide, the more easily we will be able to offer
help and advice.

## Environment info
Operating System: Linux localhost 2.6.32-431.el6.x86_64 #1 SMP Fri Nov 22 03:15:09 UTC 2013 x86_64 x86_64 x86_64 GNU/Linux  .  centos 
 
Compiler:  JDK 1.7 ， spark 1.6.1 , scala 2.10 

Package used (python/R/jvm/C++): jvm

`xgboost` version used: 0.5

url :  https://github.com/dmlc/xgboost/tree/v0.60

question：

The official did not describe，I searched the xgboost engineering didn't find the "tracker. Py" .

Strives for the Compilation step of the project.

thanks

After the operation error information：

16/10/19 11:35:56 INFO DAGScheduler: Job 2 finished: collect at DistTrainWithSpark.scala:42, took 0.397495 s
16/10/19 11:35:56 ERROR RabitTracker: load tracker library failed.
16/10/19 11:35:56 ERROR RabitTracker: java.io.FileNotFoundException: File /tracker.py was not found inside JAR.
16/10/19 11:35:56 WARN SparkConf: The configuration key 'spark.kryoserializer.buffer.max.mb' has been deprecated as of Spark 1.4 and and may be removed in the future. Please use the new key 'spark.kryoserializer.buffer.max' instead.
16/10/19 11:35:56 WARN SparkConf: The configuration key 'spark.akka.askTimeout' has been deprecated as of Spark 1.4 and and may be removed in the future. Please use the new key 'spark.rpc.askTimeout' instead.
Tracker started, with env={}
16/10/19 11:35:56 INFO XGBoostSpark: repartitioning training set to 2 partitions
16/10/19 11:35:56 INFO RabitTracker$TrackerProcessLogger: python: can't open file 'null': [Errno 2] No such file or directory
16/10/19 11:35:56 INFO RabitTracker$TrackerProcessLogger: Tracker Process ends with exit code 2
16/10/19 11:35:56 INFO RabitTracker: Tracker Process ends with exit code 2
16/10/19 11:35:56 INFO XGBoostSpark: Rabit returns with exit code 2
Exception in thread "main" ml.dmlc.xgboost4j.java.XGBoostError: XGBoostModel training failed
        at ml.dmlc.xgboost4j.scala.spark.XGBoost$.train(XGBoost.scala:142)
        at ml.dmlc.xgboost4j.scala.example.spark.DistTrainWithSpark$.main(DistTrainWithSpark.scala:48)
        at ml.dmlc.xgboost4j.scala.example.spark.DistTrainWithSpark.main(DistTrainWithSpark.scala)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:606)
        at org.apache.spark.deploy.SparkSubmit$.org$apache$spark$deploy$SparkSubmit$$runMain(SparkSubmit.scala:685)
        at org.apache.spark.deploy.SparkSubmit$.doRunMain$1(SparkSubmit.scala:180)
        at org.apache.spark.deploy.SparkSubmit$.submit(SparkSubmit.scala:205)
        at org.apache.spark.deploy.SparkSubmit$.main(SparkSubmit.scala:120)
        at org.apache.spark.deploy.SparkSubmit.main(SparkSubmit.scala)

**Comment by CodingCat** [comment]
`Tracker started, with env={}` means that the tracker is not started correctly , tracker script is maintained in dmlc-core repo

**Comment by Lintong-common** [comment]
how to resolve this problem?
