### ISSUE TITLE
[jvm-packages]  during train:  NoClassDefFoundError: Could not initialize class ml.dmlc.xgboost4j.java.Rabit

### ISSUE THREAD

**Issue by cnglen** [dmlc/xgboost#1687]
Tracker started, with env={DMLC_TRACKER_URI=10.8.84.18, DMLC_NUM_WORKER=100, DMLC_TRACKER_PORT=9091, DMLC_NUM_SERVER=0}
16/10/21 12:44:14 ERROR scheduler.TaskSetManager: Task 78 in stage 43.0 failed 4 times; aborting job
Exception in thread "Thread-133" org.apache.spark.SparkException: Job aborted due to stage failure: Task 78 in stage 43.0 failed 4 times, most recent failure: Lost task 78.3 in stage 43.0 (TID 6027, sh02xxxx7152.hadoop.abc2.xxxxcorp.com): java.lang.NoClassDefFoundError: Could not initialize class ml.dmlc.xgboost4j.java.Rabit
    at ml.dmlc.xgboost4j.scala.spark.XGBoost$$anonfun$buildDistributedBoosters$1.apply(XGBoost.scala:92)
    at ml.dmlc.xgboost4j.scala.spark.XGBoost$$anonfun$buildDistributedBoosters$1.apply(XGBoost.scala:90)
    at org.apache.spark.rdd.RDD$$anonfun$mapPartitions$1$$anonfun$apply$20.apply(RDD.scala:710)
    at org.apache.spark.rdd.RDD$$anonfun$mapPartitions$1$$anonfun$apply$20.apply(RDD.scala:710)
    at org.apache.spark.rdd.MapPartitionsRDD.compute(MapPartitionsRDD.scala:38)
    at org.apache.spark.rdd.RDD.computeOrReadCheckpoint(RDD.scala:306)
    at org.apache.spark.CacheManager.getOrCompute(CacheManager.scala:69)
    at org.apache.spark.rdd.RDD.iterator(RDD.scala:268)
    at org.apache.spark.scheduler.ResultTask.runTask(ResultTask.scala:66)
    at org.apache.spark.scheduler.Task.run(Task.scala:89)
    at org.apache.spark.executor.Executor$TaskRunner.run(Executor.scala:214)
    at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
    at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615)
    at java.lang.Thread.run(Thread.java:745)

Driver stacktrace:
    at org.apache.spark.scheduler.DAGScheduler.org$apache$spark$scheduler$DAGScheduler$$failJobAndIndependentStages(DAGScheduler.scala:1431)
    at org.apache.spark.scheduler.DAGScheduler$$anonfun$abortStage$1.apply(DAGScheduler.scala:1419)
    at org.apache.spark.scheduler.DAGScheduler$$anonfun$abortStage$1.apply(DAGScheduler.scala:1418)
    at scala.collection.mutable.ResizableArray$class.foreach(ResizableArray.scala:59)
    at scala.collection.mutable.ArrayBuffer.foreach(ArrayBuffer.scala:47)
    at org.apache.spark.scheduler.DAGScheduler.abortStage(DAGScheduler.scala:1418)
    at org.apache.spark.scheduler.DAGScheduler$$anonfun$handleTaskSetFailed$1.apply(DAGScheduler.scala:799)
    at org.apache.spark.scheduler.DAGScheduler$$anonfun$handleTaskSetFailed$1.apply(DAGScheduler.scala:799)
    at scala.Option.foreach(Option.scala:236)
    at org.apache.spark.scheduler.DAGScheduler.handleTaskSetFailed(DAGScheduler.scala:799)
    at org.apache.spark.scheduler.DAGSchedulerEventProcessLoop.doOnReceive(DAGScheduler.scala:1640)
    at org.apache.spark.scheduler.DAGSchedulerEventProcessLoop.onReceive(DAGScheduler.scala:1599)
    at org.apache.spark.scheduler.DAGSchedulerEventProcessLoop.onReceive(DAGScheduler.scala:1588)
    at org.apache.spark.util.EventLoop$$anon$1.run(EventLoop.scala:48)
    at org.apache.spark.scheduler.DAGScheduler.runJob(DAGScheduler.scala:620)
    at org.apache.spark.SparkContext.runJob(SparkContext.scala:1832)
    at org.apache.spark.SparkContext.runJob(SparkContext.scala:1845)
    at org.apache.spark.SparkContext.runJob(SparkContext.scala:1858)
    at org.apache.spark.SparkContext.runJob(SparkContext.scala:1929)
    at org.apache.spark.rdd.RDD$$anonfun$foreachPartition$1.apply(RDD.scala:920)
    at org.apache.spark.rdd.RDD$$anonfun$foreachPartition$1.apply(RDD.scala:918)
    at org.apache.spark.rdd.RDDOperationScope$.withScope(RDDOperationScope.scala:150)
    at org.apache.spark.rdd.RDDOperationScope$.withScope(RDDOperationScope.scala:111)
    at org.apache.spark.rdd.RDD.withScope(RDD.scala:316)
    at org.apache.spark.rdd.RDD.foreachPartition(RDD.scala:918)
    at ml.dmlc.xgboost4j.scala.spark.XGBoost$$anon$2.run(XGBoost.scala:229)
Caused by: java.lang.NoClassDefFoundError: Could not initialize class ml.dmlc.xgboost4j.java.Rabit
    at ml.dmlc.xgboost4j.scala.spark.XGBoost$$anonfun$buildDistributedBoosters$1.apply(XGBoost.scala:92)
    at ml.dmlc.xgboost4j.scala.spark.XGBoost$$anonfun$buildDistributedBoosters$1.apply(XGBoost.scala:90)
    at org.apache.spark.rdd.RDD$$anonfun$mapPartitions$1$$anonfun$apply$20.apply(RDD.scala:710)
    at org.apache.spark.rdd.RDD$$anonfun$mapPartitions$1$$anonfun$apply$20.apply(RDD.scala:710)
    at org.apache.spark.rdd.MapPartitionsRDD.compute(MapPartitionsRDD.scala:38)
    at org.apache.spark.rdd.RDD.computeOrReadCheckpoint(RDD.scala:306)
    at org.apache.spark.CacheManager.getOrCompute(CacheManager.scala:69)
    at org.apache.spark.rdd.RDD.iterator(RDD.scala:268)
    at org.apache.spark.scheduler.ResultTask.runTask(ResultTask.scala:66)
    at org.apache.spark.scheduler.Task.run(Task.scala:89)
    at org.apache.spark.executor.Executor$TaskRunner.run(Executor.scala:214)
    at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
    at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615)
    at java.lang.Thread.run(Thread.java:745)
16/10/21 12:44:15 ERROR cluster.YarnScheduler: Lost executor 12 on xxxx11095hw2288.hadoop.ny2.xxxxcorp.com: Container marked as failed: container_e19_1475054520611_4318873_01_000015 on host: xxxx11095hw2288.hadoop.ny2.xxxxcorp.com. Exit status: 50. Diagnostics: Exception from container-launch.
Container id: container_e19_1475054520611_4318873_01_000015
Exit code: 50
Stack trace: ExitCodeException exitCode=50: 
    at org.apache.hadoop.util.Shell.runCommand(Shell.java:561)
    at org.apache.hadoop.util.Shell.run(Shell.java:478)
    at org.apache.hadoop.util.Shell$ShellCommandExecutor.execute(Shell.java:738)
    at org.apache.hadoop.yarn.server.nodemanager.LinuxContainerExecutor.launchContainer(LinuxContainerExecutor.java:367)
    at org.apache.hadoop.yarn.server.nodemanager.containermanager.launcher.ContainerLaunch.call(ContainerLaunch.java:302)
    at org.apache.hadoop.yarn.server.nodemanager.containermanager.launcher.ContainerLaunch.call(ContainerLaunch.java:82)
    at java.util.concurrent.FutureTask.run(FutureTask.java:262)
    at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
    at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615)
    at java.lang.Thread.run(Thread.java:745)

Shell output: main : command provided 1
main : run as user is ddlearner
main : requested yarn user is ddlearner
Writing to tmp file /opt/data/3/yarn/local/nmPrivate/application_1475054520611_4318873/container_e19_1475054520611_4318873_01_000015/container_e19_1475054520611_4318873_01_000015.pid.tmp

Container exited with a non-zero exit code 50

16/10/21 12:44:15 ERROR cluster.YarnScheduler: Lost executor 15 on xxxx11095hw2288.hadoop.ny2.xxxxcorp.com: Container marked as failed: container_e19_1475054520611_4318873_01_000018 on host: xxxx11095hw2288.hadoop.ny2.xxxxcorp.com. Exit status: 50. Diagnostics: Exception from container-launch.
Container id: container_e19_1475054520611_4318873_01_000018
Exit code: 50
Stack trace: ExitCodeException exitCode=50: 
    at org.apache.hadoop.util.Shell.runCommand(Shell.java:561)
    at org.apache.hadoop.util.Shell.run(Shell.java:478)
    at org.apache.hadoop.util.Shell$ShellCommandExecutor.execute(Shell.java:738)
    at org.apache.hadoop.yarn.server.nodemanager.LinuxContainerExecutor.launchContainer(LinuxContainerExecutor.java:367)
    at org.apache.hadoop.yarn.server.nodemanager.containermanager.launcher.ContainerLaunch.call(ContainerLaunch.java:302)
    at org.apache.hadoop.yarn.server.nodemanager.containermanager.launcher.ContainerLaunch.call(ContainerLaunch.java:82)
    at java.util.concurrent.FutureTask.run(FutureTask.java:262)
    at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
    at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615)
    at java.lang.Thread.run(Thread.java:745)

Shell output: main : command provided 1
main : run as user is ddlearner
main : requested yarn user is ddlearner
Writing to tmp file /opt/data/1/yarn/local/nmPrivate/application_1475054520611_4318873/container_e19_1475054520611_4318873_01_000018/container_e19_1475054520611_4318873_01_000018.pid.tmp

Container exited with a non-zero exit code 50

16/10/21 12:44:15 ERROR cluster.YarnScheduler: Lost executor 47 on xxxx10539hw2288.hadoop.ny2.xxxxcorp.com: Container marked as failed: container_e19_1475054520611_4318873_01_000060 on host: xxxx10539hw2288.hadoop.ny2.xxxxcorp.com. Exit status: 50. Diagnostics: Exception from container-launch.
Container id: container_e19_1475054520611_4318873_01_000060
Exit code: 50
Stack trace: ExitCodeException exitCode=50: 
    at org.apache.hadoop.util.Shell.runCommand(Shell.java:561)
    at org.apache.hadoop.util.Shell.run(Shell.java:478)
    at org.apache.hadoop.util.Shell$ShellCommandExecutor.execute(Shell.java:738)
    at org.apache.hadoop.yarn.server.nodemanager.LinuxContainerExecutor.launchContainer(LinuxContainerExecutor.java:367)
    at org.apache.hadoop.yarn.server.nodemanager.containermanager.launcher.ContainerLaunch.call(ContainerLaunch.java:302)
    at org.apache.hadoop.yarn.server.nodemanager.containermanager.launcher.ContainerLaunch.call(ContainerLaunch.java:82)
    at java.util.concurrent.FutureTask.run(FutureTask.java:262)
    at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
    at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615)
    at java.lang.Thread.run(Thread.java:745)

Shell output: main : command provided 1
main : run as user is ddlearner
main : requested yarn user is ddlearner
Writing to tmp file /opt/data/3/yarn/local/nmPrivate/application_1475054520611_4318873/container_e19_1475054520611_4318873_01_000060/container_e19_1475054520611_4318873_01_000060.pid.tmp
## Environment info

Operating System: Linux

Compiler: gcc 6.1.1

Package used (python/R/jvm/C++): jvm

`xgboost` version used: 

If installing from source, please provide 
commit e79a803a3060bd4d75954e3a9dc2d893eb7a0a9b

Building  for spark 1.6.1, generate jar after update some code as follows:

> find ./ -name "_.scala"|xargs sed -i -e 's/Dataset[_]/DataFrame/g'
> find ./ -name "_.scala"|xargs sed -i -e 's/org.apache.spark.ml.feature/org.apache.spark.mllib.regression/g'
> find ./ -name "_.scala"|xargs sed -i -e 's/org.apache.spark.ml.linalg/org.apache.spark.mllib.linalg/g'
> find ./ -name "_.scala"|xargs sed -i -e 's/import org.apache.spark.sql.Dataset/import org.apache.spark.sql.DataFrame/g'
> find ./ -name "_.scala"|xargs sed -i -e 's/import org.apache.spark.sql.Dataset/import org.apache.spark.sql.DataFrame/g'
> find ./ -name "_.scala"|xargs sed -i -e 's/import org.apache.spark.sql.{Dataset/import org.apache.spark.sql.{DataFrame/g'
> find ./ -name "_.scala"|xargs sed -i -e 's/val sparkSession = SparkSession.builder().appName("XGBoostDFSuite").getOrCreate()/val sc = SparkContext.getOrCreate(new SparkConf().setAppName("XGBoostDFSuitef"))\n      val sqlContext = new org.apache.spark.sql.SQLContext(sc)/g'
> find ./ -name "_.scala"|xargs sed -i -e 's/sparkSession/sqlContext/g'
> find ./ -name "*.scala"|xargs sed -i -e "s/import org.apache.spark.SparkContext/import org.apache.spark.{SparkContext, SparkConf}/"

Then changing two lines order of : 
-       val sc = SparkContext.getOrCreate(new SparkConf().setAppName("XGBoostDFSuitef"))
-       val labeledPointsRDD = sparkContext.getOrElse(sc).parallelize(rowList, numWorkers)

[INFO] 
[INFO] --- maven-jar-plugin:2.4:jar (default-jar) @ xgboost4j-example ---
[INFO] Building jar: /media/sf_workspace/repos/hotel_rank/lib/xgboost/jvm-packages/xgboost4j-example/target/xgboost4j-example-0.7.jar
[INFO] 
[INFO] --- maven-assembly-plugin:2.6:single (make-assembly) @ xgboost4j-example ---
[INFO] Building jar: /media/sf_workspace/repos/hotel_rank/lib/xgboost/jvm-packages/xgboost4j-example/target/xgboost4j-example-0.7-jar-with-dependencies.jar
[INFO] ------------------------------------------------------------------------
[INFO] Reactor Summary:
[INFO] 
[INFO] xgboost-jvm ........................................ SUCCESS [  3.556 s]
[INFO] xgboost4j .......................................... SUCCESS [ 16.697 s]
[INFO] xgboost4j-spark .................................... SUCCESS [01:08 min]
[INFO] xgboost4j-example .................................. SUCCESS [ 29.672 s]
[INFO] ------------------------------------------------------------------------
[INFO] BUILD SUCCESS
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 01:58 min
[INFO] Finished at: 2016-10-21T10:14:32+08:00
[INFO] Final Memory: 219M/966M
[INFO] ------------------------------------------------------------------------
## Steps to reproduce

1.
2.
3.
## What have you tried?

1.
2.
3.

**Comment by pommedeterresautee** [comment]
Old bug, no answer. Closing
