### ISSUE TITLE
Error importing xgboost on windows

### ISSUE THREAD

**Issue by siddjain** [dmlc/xgboost#1693]
For bugs or installation issues, please provide the following information.
The more information you provide, the more easily we will be able to offer
help and advice.

## Environment info
Operating System: Windows 10

Compiler: N/A

Package used (python/R/jvm/C++): python

`xgboost` version used: 0.6

If installing from source, please provide 

1. The commit hash (`git rev-parse HEAD`)
2. Logs will be helpful (If logs are large, please upload as attachment).

If you are using python package, please provide

1. The python version and distribution
2.7 installed from Python(x,y) for windows

2. The command to install `xgboost` if you are not installing from source
I downloaded libxgboost.dll from http://www.picnet.com.au/blogs/guido/post/2016/09/22/xgboost-windows-x64-binaries-for-download/ and ran following commands:
python setup.py install
which gave this output:
creating c:\python27\lib\site-packages\xgboost-0.6-py2.7.egg
Extracting xgboost-0.6-py2.7.egg to c:\python27\lib\site-packages
Adding xgboost 0.6 to easy-install.pth file

Installed c:\python27\lib\site-packages\xgboost-0.6-py2.7.egg
Processing dependencies for xgboost==0.6
Searching for scipy==0.15.1
Best match: scipy 0.15.1
Adding scipy 0.15.1 to easy-install.pth file

Using c:\python27\lib\site-packages
Searching for numpy==1.9.2
Best match: numpy 1.9.2
Adding numpy 1.9.2 to easy-install.pth file

Using c:\python27\lib\site-packages
Finished processing dependencies for xgboost==0.6

If you are using R package, please provide

1. The R `sessionInfo()`
2. The command to install `xgboost` if you are not installing from source

## Steps to reproduce

trying to import xgboost gives following error:
```
>>> import xgboost
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "xgboost\__init__.py", line 11, in <module>
    from .core import DMatrix, Booster
  File "xgboost\core.py", line 112, in <module>
    _LIB = _load_lib()
  File "xgboost\core.py", line 106, in _load_lib
    lib = ctypes.cdll.LoadLibrary(lib_path[0])
  File "C:\Python27\lib\ctypes\__init__.py", line 443, in LoadLibrary
    return self._dlltype(name)
  File "C:\Python27\lib\ctypes\__init__.py", line 365, in __init__
    self._handle = _dlopen(self._name, mode)
WindowsError: [Error 193] %1 is not a valid Win32 application
```
## What have you tried?

1. Googling
2.
3.

**Comment by siddjain** [comment]
This happened because I had a 32bit installation of python and was using 64 bit binary of libxgboost.dll
