### ISSUE TITLE
[jvm-package] XGBoost4J successfuly built but can't import ml.dmlc.*

### ISSUE THREAD

**Issue by greghor** [dmlc/xgboost#1702]
I carefully followed the installation instructions from here, paid attention to set JAVA_HOME=/Library/Java/JavaVirtualMachines/jdk1.8.0_65.jdk/Contents/Home/

The installation through mvn package returns BUILD SUCCESS. However, when I tried to run BasicWalkThrough.scala from the example folder I got an error on 

The installation through `mvn package` returns BUILD SUCCESS. However, when I tried to run BasicWalkThrough.scala from the example folder I got an error on 

`<console>:14: error: not found: value ml
       import ml.dmlc.xgboost4j.java.{DMatrix => JDMatrix}`

Can anybody help to fix this please?

## Environment info
Operating System: OSX 10.12

**Comment by CodingCat** [comment]
which jar file are you using ?

**Comment by greghor** [comment]
Thanks for your fast reply, where can I find this information? (sorry I am a newbie)

**Comment by CodingCat** [comment]
what's the command line you're using to run the example?

**Comment by greghor** [comment]
I use the scala repl and then 
`:load BasicWalkThrough.scala`

from the example repo

**Comment by CodingCat** [comment]
use the following command:

`java -cp path_to_exampledirectory/xgboost4j-example-0.7-jar-with-dependencies.jar ml.dmlc.xgboost4j.scala.example.BasicWalkThrough `

**Comment by greghor** [comment]
ok, 

I run  (from the example repo)

`java -cp xgboost4j-example-0.7-jar-with-dependencies.jar ml.dmlc.xgboost4j.scala.example.BasicWalkThrough`

and I get the error

'error: cannot find or load the main class ml.dmlc.xgboost4j.scala.example.BasicWalkThrough`

**Comment by CodingCat** [comment]
does `xgboost4j-example-0.7-jar-with-dependencies.jar ` locate in your current working directory? you have to precisely locate xgboost4j-example-0.7-jar-with-dependencies.jar in your command

**Comment by greghor** [comment]
Good point! now running (still from example repo)
`java -cp /Users/greghor/anaconda2/lib/python2.7/site-packages/xgboost/jvm-packages/xgboost4j-example/target/xgboost4j-example-0.7-jar-with-dependencies.jar ml.dmlc.xgboost4j.scala.example.BasicWalkThrough`

gives error

`the main method is not static in the class ml.dmlc.xgboost4j.scala.example.BasicWalkThrough`

May I also ask you to explain what does this `java -cp command`?  why shoudl we use it?

**Comment by CodingCat** [comment]
http://docs.oracle.com/javase/7/docs/technotes/tools/windows/java.html search `-cp`

eh...I'm surprised to find that the examples are defined as class instead of object in example directory, and I forgot why it happens....you may want to move main() function in BasicWalkThrough.scala starting from Line 29 to Line 88 (above function checkPredicts() )

**Comment by greghor** [comment]
Well I made the modifications, but I still get the same error, should I explicitly recompile since I have the feeling that the changes were not accounted? (sorry again for the stupid questions, but I know literally nothing in java...)

**Comment by CodingCat** [comment]
yeah, you need to compile and package it after changes

**Comment by greghor** [comment]
may I ask you to explain how to do that? 

my final goal being to use XGBoost through a zeppelin notebook environement, I am quite confused and don't really understand why java dependency show up a this point.

Btw I really appreciate your help, thank you very much for taking time to answer my questions

(I need to leave my office now but will be connected again in approx ~ 1h)

**Comment by CodingCat** [comment]
I have fixed the issue in https://github.com/dmlc/xgboost/pull/1703, you can compile and package XGBoost as usual after I merged that

**Comment by greghor** [comment]
ok so shall I pull the full dlmc repo and build the jvm-packages again or shall I  only pull the example repo?

**Comment by CodingCat** [comment]
you cannot pull only example directory, and you can only pull all updates from repo

**Comment by greghor** [comment]
ok thanks, I will therefore pull once the change have been merged

**Comment by CodingCat** [comment]
I merged that and you may want to change the following lines to match the actual training and test paths 

```scala
val trainMax = new DMatrix("../../demo/data/agaricus.txt.train")
val testMax = new DMatrix("../../demo/data/agaricus.txt.test")
```

**Comment by greghor** [comment]
Hi CodingCat, I ve 'mvn package' after the pull and I tried again the command 'java -cp /Users/greghor/anaconda2/lib/python2.7/site-packages/xgboost/jvm-packages/xgboost4j-example/target/xgboost4j-example-0.7-jar-with-dependencies.jar ml.dmlc.xgboost4j.scala.example.BasicWalkThrough'. 

I get now the following error 

```
[09:25:39] dmlc-core/include/dmlc/logging.h:235: [09:25:39] src/io/local_filesys.cc:86: LocalFileSystem.ListDirectory ../../demo/data error: No such file or directory
Exception in thread "main" ml.dmlc.xgboost4j.java.XGBoostError: [09:25:39] src/io/local_filesys.cc:86: LocalFileSystem.ListDirectory ../../demo/data error: No such file or directory
	at ml.dmlc.xgboost4j.java.JNIErrorHandle.checkCall(JNIErrorHandle.java:48)
	at ml.dmlc.xgboost4j.java.DMatrix.<init>(DMatrix.java:83)
	at ml.dmlc.xgboost4j.scala.DMatrix.<init>(DMatrix.scala:31)
	at ml.dmlc.xgboost4j.scala.example.BasicWalkThrough$.main(BasicWalkThrough.scala:29)
	at ml.dmlc.xgboost4j.scala.example.BasicWalkThrough.main(BasicWalkThrough.scala)
```

did I do smth wrong?

**Comment by CodingCat** [comment]
see my last comment, you have to modify those two lines to point to the right directory 

or 

your run the library in the directory of xgboost4j-examples

**Comment by greghor** [comment]
I missunderstood your last comment, sorry for that

after setting the path correctlty, I got a new error :(

```
 6513x127 matrix with 143286 entries loaded from /Users/greghor/Downloads/demoXGBoost4J/agaricus.txt.train
[15:43:58] 1611x127 matrix with 35442 entries loaded from /Users/greghor/Downloads/demoXGBoost4J/agaricus.txt.test
[0]	train-error:0.046522	test-error:0.042831
[1]	train-error:0.022263	test-error:0.021726
[15:43:58] dmlc-core/include/dmlc/logging.h:235: [15:43:58] src/io/local_filesys.cc:154: Check failed: allow_null  LocalFileSystem: fail to open "/Users/greghor/anaconda2/lib/python2.7/site-packages/xgboost/jvm-packages/xgboost4j-example/src/main/scala/ml/dmlc/xgboost4j/scala/example/./model/dump.raw.txt"
Exception in thread "main" ml.dmlc.xgboost4j.java.XGBoostError: [15:43:58] src/io/local_filesys.cc:154: Check failed: allow_null  LocalFileSystem: fail to open "/Users/greghor/anaconda2/lib/python2.7/site-packages/xgboost/jvm-packages/xgboost4j-example/src/main/scala/ml/dmlc/xgboost4j/scala/example/./model/dump.raw.txt"
	at ml.dmlc.xgboost4j.java.JNIErrorHandle.checkCall(JNIErrorHandle.java:48)
	at ml.dmlc.xgboost4j.java.Booster.getModelDump(Booster.java:324)
	at ml.dmlc.xgboost4j.scala.Booster.getModelDump(Booster.scala:171)
	at ml.dmlc.xgboost4j.scala.example.BasicWalkThrough$.main(BasicWalkThrough.scala:54)
	at ml.dmlc.xgboost4j.scala.example.BasicWalkThrough.main(BasicWalkThrough.scala)
```
any idea on what is  going wrong here?
