### ISSUE TITLE
osx installation failure 0.6a2

### ISSUE THREAD

**Issue by geoHeil** [dmlc/xgboost#1728]
I tried to upgrade xgboost on my system from 0.6 to 0.6a2. Unfortunately, installation fails.

## Environment info
Operating System:
osx 10.12.1
Compiler:
export CC=gcc-6
export CXX=gcc-6
export MPICXX=mpicxx

Package used (python/R/jvm/C++):

`xgboost` version used: 0.6a2 latest from pip

If you are using python package, please provide

1. The python version and distribution: 3.5

## Steps to reproduce

1. pip3 install xgboost

```
pip3 install xgboost
Collecting xgboost
  Downloading xgboost-0.6a2.tar.gz (1.2MB)
    100% |████████████████████████████████| 1.2MB 1.0MB/s
    Complete output from command python setup.py egg_info:
    rm -f -rf build build_plugin lib bin *~ */*~ */*/*~ */*/*/*~ */*.o */*/*.o */*/*/*.o xgboost
    clang-omp++ -std=c++0x -Wall -O3 -msse2  -Wno-unknown-pragmas -funroll-loops -Iinclude   -Idmlc-core/include -Irabit/include -fPIC -fopenmp -MM -MT build/learner.o src/learner.cc >build/learner.d
    /bin/sh: clang-omp++: command not found
    make: *** [build/learner.o] Error 127
    make: *** Waiting for unfinished jobs....
    clang-omp++ -std=c++0x -Wall -O3 -msse2  -Wno-unknown-pragmas -funroll-loops -Iinclude   -Idmlc-core/include -Irabit/include -fPIC -fopenmp -MM -MT build/logging.o src/logging.cc >build/logging.d
    /bin/sh: clang-omp++: command not found
    make: *** [build/logging.o] Error 127
    -----------------------------
    Building multi-thread xgboost failed
    Start to build single-thread xgboost
    rm -f -rf build build_plugin lib bin *~ */*~ */*/*~ */*/*/*~ */*.o */*/*.o */*/*/*.o xgboost
    clang-omp++ -std=c++0x -Wall -O3 -msse2  -Wno-unknown-pragmas -funroll-loops -Iinclude   -Idmlc-core/include -Irabit/include -fPIC -fopenmp -MM -MT build/learner.o src/learner.cc >build/learner.d
    /bin/sh: clang-omp++: command not found
    make: *** [build/learner.o] Error 127
    make: *** Waiting for unfinished jobs....
    clang-omp++ -std=c++0x -Wall -O3 -msse2  -Wno-unknown-pragmas -funroll-loops -Iinclude   -Idmlc-core/include -Irabit/include -fPIC -fopenmp -MM -MT build/logging.o src/logging.cc >build/logging.d
    /bin/sh: clang-omp++: command not found
    make: *** [build/logging.o] Error 127
    Successfully build single-thread xgboost
    If you want multi-threaded version
    See additional instructions in doc/build.md
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/private/var/folders/zm/bts0g37j0l9637sjxb3b700h0000gn/T/pip-build-xh80yjqs/xgboost/setup.py", line 29, in <module>
        LIB_PATH = libpath['find_lib_path']()
      File "/private/var/folders/zm/bts0g37j0l9637sjxb3b700h0000gn/T/pip-build-xh80yjqs/xgboost/xgboost/libpath.py", line 45, in find_lib_path
        'List of candidates:\n' + ('\n'.join(dll_path)))
    XGBoostLibraryNotFound: Cannot find XGBoost Libarary in the candicate path, did you install compilers and run build.sh in root path?
    List of candidates:
    /private/var/folders/zm/bts0g37j0l9637sjxb3b700h0000gn/T/pip-build-xh80yjqs/xgboost/xgboost/libxgboost.so
    /private/var/folders/zm/bts0g37j0l9637sjxb3b700h0000gn/T/pip-build-xh80yjqs/xgboost/xgboost/../../lib/libxgboost.so
    /private/var/folders/zm/bts0g37j0l9637sjxb3b700h0000gn/T/pip-build-xh80yjqs/xgboost/xgboost/./lib/libxgboost.so
```

**Comment by geoHeil** [comment]
a build from source for 0.60. fails as well 
```
"___cxa_throw", referenced from:
      dmlc::LogMessageFatal::~LogMessageFatal() in cli_main.o
      dmlc::parameter::FieldEntry<bool>::Set(void*, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&) const in cli_main.o
      dmlc::parameter::FieldEntryBase<dmlc::parameter::FieldEntry<bool>, bool>::SetDefault(void*) const in cli_main.o
      dmlc::parameter::FieldEntryBase<dmlc::parameter::FieldEntry<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > >, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > >::SetDefault(void*) const in cli_main.o
      dmlc::parameter::FieldEntryBase<dmlc::parameter::FieldEntry<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > >, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > >::Set(void*, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&) const in cli_main.o
      dmlc::parameter::FieldEntryBase<dmlc::parameter::FieldEntry<int>, int>::SetDefault(void*) const in cli_main.o
      dmlc::parameter::FieldEntryNumeric<dmlc::parameter::FieldEntry<int>, int>::Check(void*) const in cli_main.o
      ...
  "___dynamic_cast", referenced from:
      std::__detail::_Scanner<char>::_Scanner(char const*, char const*, std::regex_constants::syntax_option_type, std::locale) in libdmlc.a(input_split_base.o)
  "___gxx_personality_v0", referenced from:
      Dwarf Exception Unwind Info (__eh_frame) in cli_main.o
      Dwarf Exception Unwind Info (__eh_frame) in learner.o
      Dwarf Exception Unwind Info (__eh_frame) in logging.o
      Dwarf Exception Unwind Info (__eh_frame) in c_api.o
      Dwarf Exception Unwind Info (__eh_frame) in c_api_error.o
      Dwarf Exception Unwind Info (__eh_frame) in common.o
      Dwarf Exception Unwind Info (__eh_frame) in data.o
      ...
ld: symbol(s) not found for architecture x86_64
collect2: error: ld returned 1 exit status
```

**Comment by geoHeil** [comment]
I found https://github.com/dmlc/xgboost/issues/1647 which describes the same problem. An xcode-select install does not fix the problem.

However this proposed solution works for me
> 
> ```
> brew tap homebrew/boneyard
> brew install clang-omp
> ```

**Comment by yi-ji** [comment]
```
brew tap homebrew/boneyard
brew install clang-omp
```

That doesn't help either.
