### ISSUE TITLE
[jvm-package] ml.dmlc.xgboost4j.scala.example.CustomEval$EvalError cannot be cast to ml.dmlc.xgboost4j.scala.ObjectiveTrait

### ISSUE THREAD

**Issue by joandre** [dmlc/xgboost#1740]
When a custom eval class is used in XGBoost.trainDataFrame and specify a custom eval class, I get the following error.

```
Exception in thread "main" java.lang.ClassCastException: ml.dmlc.xgboost4j.scala.example.CustomEval$EvalError cannot be cast to ml.dmlc.xgboost4j.scala.ObjectiveTrait
	at ml.dmlc.xgboost4j.scala.spark.XGBoostEstimator.train(XGBoostEstimator.scala:120)
	at ml.dmlc.xgboost4j.scala.spark.XGBoostEstimator.train(XGBoostEstimator.scala:34)
	at org.apache.spark.ml.Predictor.fit(Predictor.scala:90)
	at ml.dmlc.xgboost4j.scala.spark.XGBoost$.trainWithDataFrame(XGBoost.scala:163)
	at ml.dmlc.xgboost4j.scala.example.CustomEval$.main(SimpleXGBoost.scala:163)
	at ml.dmlc.xgboost4j.scala.example.CustomEval.main(SimpleXGBoost.scala)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
```

I used the same eval class than in this [example](https://github.com/dmlc/xgboost/blob/master/jvm-packages/xgboost4j-example/src/main/scala/ml/dmlc/xgboost4j/scala/example/CustomObjective.scala).

```
import scala.collection.mutable.ListBuffer
import ml.dmlc.xgboost4j.java.XGBoostError
import ml.dmlc.xgboost4j.scala.spark.XGBoost
import ml.dmlc.xgboost4j.scala.{DMatrix, EvalTrait, ObjectiveTrait}
import org.apache.commons.logging.{Log, LogFactory}
import org.apache.spark.ml.linalg.Vectors
import org.apache.spark.sql.SparkSession

object CustomEval {
  class EvalError extends EvalTrait {

    val logger = LogFactory.getLog(classOf[EvalError])

    private[xgboost4j] var evalMetric: String = "custom_error"

    /**
      * get evaluate metric
      *
      * @return evalMetric
      */
    override def getMetric: String = evalMetric

    /**
      * evaluate with predicts and data
      *
      * @param predicts predictions as array
      * @param dmat     data matrix to evaluate
      * @return result of the metric
      */
    override def eval(predicts: Array[Array[Float]], dmat: DMatrix): Float = {
      var error: Float = 0f
      var labels: Array[Float] = null
      try {
        labels = dmat.getLabel
      } catch {
        case ex: XGBoostError =>
          logger.error(ex)
          return -1f
      }
      val nrow: Int = predicts.length
      for (i <- 0 until nrow) {
        if (labels(i) == 0.0 && predicts(i)(0) > 0) {
          error += 1
        } else if (labels(i) == 1.0 && predicts(i)(0) <= 0) {
          error += 1
        }
      }
      error / labels.length
    }
  }

def main(args: Array[String]): Unit = {

    // create SparkSession
    val spark = SparkSession
      .builder()
      .appName("SimpleXGBoost Application")
      .master("local[*]")
      .getOrCreate()

    val training = spark.createDataFrame(Seq(
      (1.0, Vectors.dense(0.0, 1.1, 0.1)),
      (0.0, Vectors.dense(2.0, 1.0, -1.0)),
      (0.0, Vectors.dense(2.0, 1.3, 1.0)),
      (1.0, Vectors.dense(0.0, 1.2, -0.5))
    )).toDF("label", "features")

    val paramMap = List(
      "eta" -> 1.0,
      "max_depth" -> 2,
      "silent" -> 1).toMap

    val round = 2
    val workers = 4
    // train a model
    val xgBoostModel = XGBoost.trainWithDataFrame(
      training, paramMap, round, workers, eval = new EvalError)

    spark.stop()
  }
}
```
I will make a pull-request as I have fixed this issue in a local version. This comes from a typo in GeneralParams class where customEval name was set to "custom_obj" instead of "custom_eval".

**Comment by CodingCat** [comment]
resolved by https://github.com/dmlc/xgboost/pull/1741
