### ISSUE TITLE
Amazon EMR dmlc Error

### ISSUE THREAD

**Issue by aialenti** [dmlc/xgboost#1768]
Hi,

I read some other issues and I have noticed that there is something similar to my problem, but I wasn't able to solve it.

I am simply trying to run the xgboost on AWS example, and I decided to use Amazon EMR because I had some issues with yarn-ec2 (it didn't set the HADOOP_HOME env variable and it didn't add any slave even doe the commands were correct).

Anyway I was able to correctly compile xgboost on the Amazon VM, (M1 instaces, Amazon Linux AMI 2016.09, Hadoop 2.7.x), but when I submit the job using dmlc (train and test are in a S3 bucket), Hadoop stucks trying to run the two instances.

Actually I tried to find a solution online, but the error is not talking for me. Do you know where the problem could be? Thank you ;)

The error log that I have from yarn is the following:

Container: container_1478981353056_0003_01_000002 on MACHINE_IP
=======================================================================================================
LogType:stderr
Log Upload Time:Sat Nov 12 22:00:31 +0000 2016
LogLength:398
Log Contents:
[21:59:03] start ip-172-31-45-238:0
[21:59:03] Load part of data 0 of 2 parts
[21:59:03] rabit/include/rabit/./internal/../../dmlc/././logging.h:245: [21:59:03] src/io/s3_filesys.cc:779: Check failed: curl_easy_perform(curl) == CURLE_OK 
terminate called after throwing an instance of 'dmlc::Error'
  what():  [21:59:03] src/io/s3_filesys.cc:779: Check failed: curl_easy_perform(curl) == CURLE_OK 
End of LogType:stderr

LogType:stdout
Log Upload Time:Sat Nov 12 22:00:31 +0000 2016
LogLength:0
Log Contents:
End of LogType:stdout

Container: container_1478981353056_0003_01_000003 on MACHINE_IP
=======================================================================================================
LogType:stderr
Log Upload Time:Sat Nov 12 22:00:31 +0000 2016
LogLength:398
Log Contents:
[21:59:03] start ip-172-31-45-238:1
[21:59:03] Load part of data 1 of 2 parts
[21:59:03] rabit/include/rabit/./internal/../../dmlc/././logging.h:245: [21:59:03] src/io/s3_filesys.cc:779: Check failed: curl_easy_perform(curl) == CURLE_OK 
terminate called after throwing an instance of 'dmlc::Error'
  what():  [21:59:03] src/io/s3_filesys.cc:779: Check failed: curl_easy_perform(curl) == CURLE_OK 
End of LogType:stderr

LogType:stdout
Log Upload Time:Sat Nov 12 22:00:31 +0000 2016
LogLength:0
Log Contents:
End of LogType:stdout

Container: container_1478981353056_0003_01_000004 on MACHINE_IP
=======================================================================================================
LogType:stderr
Log Upload Time:Sat Nov 12 22:00:31 +0000 2016
LogLength:0
Log Contents:
End of LogType:stderr

LogType:stdout
Log Upload Time:Sat Nov 12 22:00:31 +0000 2016
LogLength:32
Log Contents:
Usage: launcher.py your command
End of LogType:stdout

Container: container_1478981353056_0003_01_000005 on MACHINE_IP
=======================================================================================================
LogType:stderr
Log Upload Time:Sat Nov 12 22:00:31 +0000 2016
LogLength:0
Log Contents:
End of LogType:stderr

LogType:stdout
Log Upload Time:Sat Nov 12 22:00:31 +0000 2016
LogLength:32
Log Contents:
Usage: launcher.py your command
End of LogType:stdout

Container: container_1478981353056_0003_01_000006 on MACHINE_IP
=======================================================================================================
LogType:stderr
Log Upload Time:Sat Nov 12 22:00:31 +0000 2016
LogLength:0
Log Contents:
End of LogType:stderr

LogType:stdout
Log Upload Time:Sat Nov 12 22:00:31 +0000 2016
LogLength:32
Log Contents:
Usage: launcher.py your command
End of LogType:stdout

Container: container_1478981353056_0003_01_000007 on MACHINE_IP
=======================================================================================================
LogType:stderr
Log Upload Time:Sat Nov 12 22:00:31 +0000 2016
LogLength:0
Log Contents:
End of LogType:stderr

LogType:stdout
Log Upload Time:Sat Nov 12 22:00:31 +0000 2016
LogLength:32
Log Contents:
Usage: launcher.py your command
End of LogType:stdout

**Moreover, looking at the container log, everything seems to start with the following error:**

16/11/12 21:30:49 INFO impl.NMClientAsyncImpl: Processing Event EventType: START_CONTAINER for Container container_1478981353056_0001_01_000003
16/11/12 21:30:49 INFO impl.ContainerManagementProtocolProxy: Opening proxy : MACHINE_IP
16/11/12 21:30:49 INFO dmlc.ApplicationMaster: onContainerStarted Invoked
16/11/12 21:30:50 INFO dmlc.ApplicationMaster: [DMLC] Task 0 exited with status 250 Diagnostics:Exception from container-launch.
Container id: container_1478981353056_0001_01_000002
Exit code: 250
Stack trace: ExitCodeException exitCode=250: 
	at org.apache.hadoop.util.Shell.runCommand(Shell.java:582)
	at org.apache.hadoop.util.Shell.run(Shell.java:479)
	at org.apache.hadoop.util.Shell$ShellCommandExecutor.execute(Shell.java:773)
	at org.apache.hadoop.yarn.server.nodemanager.DefaultContainerExecutor.launchContainer(DefaultContainerExecutor.java:212)
	at org.apache.hadoop.yarn.server.nodemanager.containermanager.launcher.ContainerLaunch.call(ContainerLaunch.java:302)
	at org.apache.hadoop.yarn.server.nodemanager.containermanager.launcher.ContainerLaunch.call(ContainerLaunch.java:82)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)

Container exited with a non-zero exit code 250

**Comment by aialenti** [comment]
I tried again the official guide and I think I am one step forward. Now the execution stucks at this point:

16/11/13 01:15:17 INFO dmlc.Client: jobname=DMLC[nworker=2]:xgboost,username=ubuntu
16/11/13 01:15:17 INFO dmlc.Client: Submitting application application_1478998588039_0003
16/11/13 01:15:17 INFO impl.YarnClientImpl: Submitted application application_1478998588039_0003


And yarn logs say:

Container: container_1478998588039_0003_01_000003 on ip-172-31-46-141.us-west-2.compute.internal_46327
========================================================================================================
LogType:stderr
Log Upload Time:13-Nov-2016 01:18:55
LogLength:36
Log Contents:
AssertError:ReConnectLink failure 4

LogType:stdout
Log Upload Time:13-Nov-2016 01:18:55
LogLength:0
Log Contents:

Any idea?
