### ISSUE TITLE
[jvm-packages] Error from Runing xgboost-spark on the spark2.0 cluster(no xgboost installed)

### ISSUE THREAD

**Issue by msjbear** [dmlc/xgboost#1773]
## Environment info
Operating System: ubuntu16.04
Compiler: JDK7
Package used: jvm

`xgboost-jvm` version used 0.7:

1. I just compile successfully the jvm-packages using maven3.3.9
2. getting the following packages:
```
xgboost4j-spark-0.7.jar
xgboost4j-spark-0.7-jar-with-dependencies.jar
xgboost4j-example-0.7-jar-with-dependencies.jar
xgboost4j-example-0.7.jar
```
3. upload the `xgboost4j-spark-0.7-jar-with-dependencies.jar` and `xgboost4j-example-0.7-jar-with-dependencies.jar` to the spark2.0 cluster without installing xgboost
4. running the following script in the spark2.0 cluster
```
spark-submit  \
--name   "spark xgboost algo" \
--master  yarn \
--deploy-mode cluster \
--class ml.dmlc.xgboost4j.scala.example.spark.SparkWithRDD \
--properties-file ./conf/spark-defaults.conf \
--num-executors 20  \
--executor-memory 20g  \
--executor-cores 2 \
--driver-memory 20g   \
--jars ./examples/jars/scopt_2.11-3.3.0.jar,./libs/xgboost4j-spark-0.7-jar-with-dependencies.jar \
--queue bdp_jmart_risk.bdp_jmart_risk_hkh \
./libs/xgboost4j-example-0.7-jar-with-dependencies.jar \
2 10 \
hdfs://ns2/user/mart_risk/sjmei/input/sample_libsvm_data.txt \
hdfs://ns2/user/mart_risk/sjmei/input/sample_libsvm_data.txt \
hdfs://ns2/user/mart_risk/sjmei/tests
```
5. When I run xgboost-spark on spark-2.0 cluster, but I got those errors:
```
[2016-11-14T18:58:22.859+08:00] [ERROR] xgboost4j.java.RabitTracker.<clinit>(RabitTracker.java 31) [Driver] : load tracker library failed.
[2016-11-14T18:58:22.860+08:00] [ERROR] xgboost4j.java.RabitTracker.<clinit>(RabitTracker.java 32) [Driver] : java.io.FileNotFoundException: File /tracker.py was not found inside JAR.
[2016-11-14T18:58:22.871+08:00] [INFO] xgboost4j.java.RabitTracker$TrackerProcessLogger.run(RabitTracker.java 48) [Thread-42] : python: can't open file 'null': [Errno 2] No such file or directory
[2016-11-14T18:58:22.871+08:00] [INFO] xgboost4j.java.RabitTracker$TrackerProcessLogger.run(RabitTracker.java 51) [Thread-42] : Tracker Process ends with exit code 2
[2016-11-14T18:58:22.871+08:00] [INFO] XGBoostSpark.repartitionData(XGBoost.scala 73) [Driver] : repartitioning training set to 10 partitions
[2016-11-14T18:58:22.902+08:00] [INFO] xgboost4j.java.RabitTracker.waitFor(RabitTracker.java 149) [Driver] : Tracker Process ends with exit code 2
[2016-11-14T18:58:22.902+08:00] [INFO] XGBoostSpark.trainWithRDD(XGBoost.scala 259) [Driver] : Rabit returns with exit code 2
[2016-11-14T18:58:22.904+08:00] [ERROR] deploy.yarn.ApplicationMaster.logError(Logging.scala 91) [Driver] : User class threw exception: ml.dmlc.xgboost4j.java.XGBoostError: XGBoostModel training failed
ml.dmlc.xgboost4j.java.XGBoostError: XGBoostModel training failed
```

What steps was I missed?

**Comment by CodingCat** [comment]
did you clone the github repo with `--recursive` option

**Comment by xydrolase** [comment]
Or run 
`git submodule init`
`git submodule update`
and then recompile.

**Comment by msjbear** [comment]
@CodingCat, @xydrolase Thank you , I'll try it

**Comment by Lintong-common** [comment]
Starting Xgboost 
17/06/07 10:32:19 ERROR RabitTracker: load tracker library failed.
17/06/07 10:32:19 ERROR RabitTracker: java.io.FileNotFoundException: File /tracker.py was not found inside JAR.
Tracker started, with env={}
17/06/07 10:32:19 INFO RabitTracker$TrackerProcessLogger: python: can't open file 'null': [Errno 2] No such file or directory
17/06/07 10:32:19 INFO RabitTracker$TrackerProcessLogger: Tracker Process ends with exit code 2
17/06/07 10:32:19 INFO XGBoostSpark: repartitioning training set to 4 partitions
17/06/07 10:32:19 INFO RabitTracker: Tracker Process ends with exit code 2
17/06/07 10:32:19 INFO XGBoostSpark: Rabit returns with exit code 2
Exception in thread "main" ml.dmlc.xgboost4j.java.XGBoostError: XGBoostModel training failed
	at ml.dmlc.xgboost4j.scala.spark.XGBoost$.trainWithRDD(XGBoost.scala:222)
	at ml.dmlc.xgboost4j.scala.spark.XGBoost$.train(XGBoost.scala:164)
	at kaggle.HousePrices$.main(HousePrices.scala:358)
	at kaggle.HousePrices.main(HousePrices.scala)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at com.intellij.rt.execution.application.AppMain.main(AppMain.java:147)
Exception in thread "Thread-15" java.lang.InterruptedException
	at java.util.concurrent.locks.AbstractQueuedSynchronizer.acquireSharedInterruptibly(AbstractQueuedSynchronizer.java:1302)
	at scala.concurrent.impl.Promise$DefaultPromise.tryAwait(Promise.scala:202)
	at scala.concurrent.impl.Promise$DefaultPromise.ready(Promise.scala:218)
	at scala.concurrent.impl.Promise$DefaultPromise.ready(Promise.scala:153)
	at org.apache.spark.scheduler.DAGScheduler.runJob(DAGScheduler.scala:623)
	at org.apache.spark.SparkContext.runJob(SparkContext.scala:1871)
	at org.apache.spark.SparkContext.runJob(SparkContext.scala:1884)
	at org.apache.spark.SparkContext.runJob(SparkContext.scala:1897)
	at org.apache.spark.SparkContext.runJob(SparkContext.scala:1911)
	at org.apache.spark.rdd.RDD$$anonfun$foreachPartition$1.apply(RDD.scala:883)
	at org.apache.spark.rdd.RDD$$anonfun$foreachPartition$1.apply(RDD.scala:881)
	at org.apache.spark.rdd.RDDOperationScope$.withScope(RDDOperationScope.scala:151)
	at org.apache.spark.rdd.RDDOperationScope$.withScope(RDDOperationScope.scala:112)
	at org.apache.spark.rdd.RDD.withScope(RDD.scala:358)
	at org.apache.spark.rdd.RDD.foreachPartition(RDD.scala:881)
	at ml.dmlc.xgboost4j.scala.spark.XGBoost$$anon$2.run(XGBoost.scala:205)
17/06/07 10:32:19 ERROR LiveListenerBus: SparkListenerBus has already stopped! Dropping event SparkListenerStageCompleted(org.apache.spark.scheduler.StageInfo@2ee9b606)
17/06/07 10:32:19 ERROR LiveListenerBus: SparkListenerBus has already stopped! Dropping event SparkListenerJobEnd(13,1496802739645,JobFailed(org.apache.spark.SparkException: Job aborted due to stage failure: Task serialization failed: java.lang.IllegalStateException: Cannot call methods on a stopped SparkContext.
This stopped SparkContext was created at:

org.apache.spark.sql.SparkSession$Builder.getOrCreate(SparkSession.scala:823)
kaggle.HousePrices$.main(HousePrices.scala:221)
kaggle.HousePrices.main(HousePrices.scala)
sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
java.lang.reflect.Method.invoke(Method.java:498)
com.intellij.rt.execution.application.AppMain.main(AppMain.java:147)

The currently active SparkContext was created at:

org.apache.spark.sql.SparkSession$Builder.getOrCreate(SparkSession.scala:823)
kaggle.HousePrices$.main(HousePrices.scala:221)
kaggle.HousePrices.main(HousePrices.scala)
sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
java.lang.reflect.Method.invoke(Method.java:498)
com.intellij.rt.execution.application.AppMain.main(AppMain.java:147)
         
java.lang.IllegalStateException: Cannot call methods on a stopped SparkContext.
This stopped SparkContext was created at:

org.apache.spark.sql.SparkSession$Builder.getOrCreate(SparkSession.scala:823)
kaggle.HousePrices$.main(HousePrices.scala:221)
kaggle.HousePrices.main(HousePrices.scala)
sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
java.lang.reflect.Method.invoke(Method.java:498)
com.intellij.rt.execution.application.AppMain.main(AppMain.java:147)

The currently active SparkContext was created at:

org.apache.spark.sql.SparkSession$Builder.getOrCreate(SparkSession.scala:823)
kaggle.HousePrices$.main(HousePrices.scala:221)
kaggle.HousePrices.main(HousePrices.scala)
sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
java.lang.reflect.Method.invoke(Method.java:498)
com.intellij.rt.execution.application.AppMain.main(AppMain.java:147)
         
	at org.apache.spark.SparkContext.assertNotStopped(SparkContext.scala:104)
	at org.apache.spark.SparkContext.broadcast(SparkContext.scala:1367)
	at org.apache.spark.scheduler.DAGScheduler.submitMissingTasks(DAGScheduler.scala:1012)
	at org.apache.spark.scheduler.DAGScheduler.org$apache$spark$scheduler$DAGScheduler$$submitStage(DAGScheduler.scala:933)
	at org.apache.spark.scheduler.DAGScheduler$$anonfun$org$apache$spark$scheduler$DAGScheduler$$submitStage$4.apply(DAGScheduler.scala:936)
	at org.apache.spark.scheduler.DAGScheduler$$anonfun$org$apache$spark$scheduler$DAGScheduler$$submitStage$4.apply(DAGScheduler.scala:935)
	at scala.collection.immutable.List.foreach(List.scala:381)
	at org.apache.spark.scheduler.DAGScheduler.org$apache$spark$scheduler$DAGScheduler$$submitStage(DAGScheduler.scala:935)
	at org.apache.spark.scheduler.DAGScheduler.handleJobSubmitted(DAGScheduler.scala:873)
	at org.apache.spark.scheduler.DAGSchedulerEventProcessLoop.doOnReceive(DAGScheduler.scala:1626)
	at org.apache.spark.scheduler.DAGSchedulerEventProcessLoop.onReceive(DAGScheduler.scala:1618)
	at org.apache.spark.scheduler.DAGSchedulerEventProcessLoop.onReceive(DAGScheduler.scala:1607)
	at org.apache.spark.util.EventLoop$$anon$1.run(EventLoop.scala:48)
))

error occured when use ml.dmlc.xgboost4j.scala.spark.XGBoost
