### ISSUE TITLE
Unknown uint field name

### ISSUE THREAD

**Issue by cycloidistic** [dmlc/xgboost#1787]
## Environment info
Operating System: Windows 10 Pro (64 bit)
Compiler: g++ version 4.8.3
Package used: python
`xgboost` version used: 0.60
Python version and distribution: Python 3.5.2, Anaconda 4.2.0 (64-bit)
Command to install `xgboost`: python setup.py install

## Steps to reproduce
When I run this script:
```
import xgboost as xgb
import numpy as np

d = xgb.DMatrix('agaricus.txt.test')
a = np.array([1])
d.set_uint_info('foo', a)
d.get_uint_info('foo')
```
I get the following error message:
```
[15:33:41] c:\dev\libs\xgboost\dmlc-core\include\dmlc\./logging.h:235: [15:33:41] C:\dev\libs\xgboost\src\c_api\c_api.cc:456: Unknown uint field name foo
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "C:\Users\adamd\AppData\Local\Continuum\Anaconda2\envs\py35\lib\site-packages\xgboost-0.6-py3.5.egg\xgboost\core.py", line 365, in get_uint_info
    ctypes.byref(ret)))
  File "C:\Users\adamd\AppData\Local\Continuum\Anaconda2\envs\py35\lib\site-packages\xgboost-0.6-py3.5.egg\xgboost\core.py", line 127, in _check_call
    raise XGBoostError(_LIB.XGBGetLastError())
xgboost.core.XGBoostError: b'[15:33:41] C:\\dev\\libs\\xgboost\\src\\c_api\\c_api.cc:456: Unknown uint field name foo'
```

## What have you tried?

I've looked at the [documentation](http://xgboost.readthedocs.io/en/latest/python/python_api.html) for `set_uint_info()` and `get_uint_info()` and I'm not sure if I'm using them incorrectly or if there is an issue.

**Comment by ungil** [comment]
The only uint field valid is "root_index".

**Comment by cycloidistic** [comment]
@ungil Ok. Thank you for pointing that out. Although I then tried the following:

```
import xgboost as xgb
import numpy as np

d = xgb.DMatrix('agaricus.txt.test')
d.get_uint_info('root_index')
```

And I get the following error:

```
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "C:\Users\adamd\AppData\Local\Continuum\Anaconda2\envs\py35\lib\site-packages\xgboost-0.6-py3.5.egg\xgboost\core.py", line 366, in get_uint_info
    return ctypes2numpy(ret, length.value, np.uint32)
  File "C:\Users\adamd\AppData\Local\Continuum\Anaconda2\envs\py35\lib\site-packages\xgboost-0.6-py3.5.egg\xgboost\core.py", line 134, in ctypes2numpy
    raise RuntimeError('expected float pointer')
RuntimeError: expected float pointer
```

Is this expected behaviour? Also, where could I have looked to realise that "root_index" is the only valid field? So far as I can tell the [Python API Reference](http://xgboost.readthedocs.io/en/latest/python/python_api.html#xgboost.DMatrix.get_uint_info) doesn't  mention this.

**Comment by WebbYang** [comment]
I also got this problem. How do we check what's inside the data?

**Comment by KOLANICH** [comment]
@tqchen
