### ISSUE TITLE
[xgboost4j-spark] Error CHECK(batch.index != nullptr) at simple_csr_source.cc:44

### ISSUE THREAD

**Issue by fc1plusx** [dmlc/xgboost#1827]
Using xgboost4j-spark I had the above error when testing (_transform_ method). I could speculate that this was related to the data containing an empty partition and/or too many small partitions, since apparently it was solved by repartitioning it. Nevertheless, I was unfortunately unable to replicate the issue in a minimal example with local toy datasets. Maybe this could also be related to #940. The error happens both when testing locally and on a EMR cluster.

Environment: xgboost version is the one available on the master as of 23 Nov 2016, scala 2.11.8, spark 2.0.1

**Comment by CodingCat** [comment]
can you provide more information about the test you run? how many partitions? how to reproduce it?

**Comment by fc1plusx** [comment]
Sure! The original data is about 30-40 MB, with some empty partitions. After loading and some pre-processing it results into 150K elements divided into 288 partitions. When running `transform` directly, the program fails with the above error (see also the stack trace below). If I repartition to 287, or even to 288 (so just a shuffle of the data), it works nicely.

As I said in the first comment, unfortunately, I was not able to reproduce the issue with a small hand-crafted dataset and a toy program, but for this failing dataset, the error is really reproducible: it always happens, and it can always be solved by repartitioning.

`ml.dmlc.xgboost4j.java.XGBoostError: [18:11:28] src/data/simple_csr_source.cc:44: Check failed: batch.index != nullptr 
  at ml.dmlc.xgboost4j.java.JNIErrorHandle.checkCall(JNIErrorHandle.java:48)
  at ml.dmlc.xgboost4j.java.DMatrix.<init>(DMatrix.java:68)
  at ml.dmlc.xgboost4j.scala.DMatrix.<init>(DMatrix.scala:42)
  at ml.dmlc.xgboost4j.scala.spark.XGBoostModel$$anonfun$produceRowRDD$1.apply(XGBoostModel.scala:254)
  at ml.dmlc.xgboost4j.scala.spark.XGBoostModel$$anonfun$produceRowRDD$1.apply(XGBoostModel.scala:239)
  at org.apache.spark.rdd.RDD$$anonfun$mapPartitions$1$$anonfun$apply$23.apply(RDD.scala:785)
  at org.apache.spark.rdd.RDD$$anonfun$mapPartitions$1$$anonfun$apply$23.apply(RDD.scala:785)
  at org.apache.spark.rdd.MapPartitionsRDD.compute(MapPartitionsRDD.scala:38)
  at org.apache.spark.rdd.RDD.computeOrReadCheckpoint(RDD.scala:319)
  at org.apache.spark.rdd.RDD.iterator(RDD.scala:283)
  at org.apache.spark.rdd.MapPartitionsRDD.compute(MapPartitionsRDD.scala:38)
  at org.apache.spark.rdd.RDD.computeOrReadCheckpoint(RDD.scala:319)
  at org.apache.spark.rdd.RDD.iterator(RDD.scala:283)
  at org.apache.spark.rdd.MapPartitionsRDD.compute(MapPartitionsRDD.scala:38)
  at org.apache.spark.rdd.RDD.computeOrReadCheckpoint(RDD.scala:319)
  at org.apache.spark.rdd.RDD.iterator(RDD.scala:283)
  at org.apache.spark.rdd.MapPartitionsRDD.compute(MapPartitionsRDD.scala:38)
  at org.apache.spark.rdd.RDD.computeOrReadCheckpoint(RDD.scala:319)
  at org.apache.spark.rdd.RDD.iterator(RDD.scala:283)
  at org.apache.spark.rdd.MapPartitionsRDD.compute(MapPartitionsRDD.scala:38)
  at org.apache.spark.rdd.RDD.computeOrReadCheckpoint(RDD.scala:319)
  at org.apache.spark.rdd.RDD.iterator(RDD.scala:283)
  at org.apache.spark.rdd.MapPartitionsRDD.compute(MapPartitionsRDD.scala:38)
  at org.apache.spark.rdd.RDD.computeOrReadCheckpoint(RDD.scala:319)
  at org.apache.spark.rdd.RDD.iterator(RDD.scala:283)
  at org.apache.spark.rdd.MapPartitionsRDD.compute(MapPartitionsRDD.scala:38)
  at org.apache.spark.rdd.RDD.computeOrReadCheckpoint(RDD.scala:319)
  at org.apache.spark.rdd.RDD$$anonfun$8.apply(RDD.scala:332)
  at org.apache.spark.rdd.RDD$$anonfun$8.apply(RDD.scala:330)
  at org.apache.spark.storage.BlockManager$$anonfun$doPutIterator$1.apply(BlockManager.scala:951)
  at org.apache.spark.storage.BlockManager$$anonfun$doPutIterator$1.apply(BlockManager.scala:926)
  at org.apache.spark.storage.BlockManager.doPut(BlockManager.scala:866)
  at org.apache.spark.storage.BlockManager.doPutIterator(BlockManager.scala:926)
  at org.apache.spark.storage.BlockManager.getOrElseUpdate(BlockManager.scala:670)
  at org.apache.spark.rdd.RDD.getOrCompute(RDD.scala:330)
  at org.apache.spark.rdd.RDD.iterator(RDD.scala:281)
  at org.apache.spark.scheduler.ResultTask.runTask(ResultTask.scala:70)
  at org.apache.spark.scheduler.Task.run(Task.scala:86)
  at org.apache.spark.executor.Executor$TaskRunner.run(Executor.scala:274)
  at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
  at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
  at java.lang.Thread.run(Thread.java:745)`

**Comment by CodingCat** [comment]
I think it is a potential bug

in the current code base, there have been some if clauses to prevent processing empty partitions...so we shall not call native layer code with a empty partition

if possible, would you check what is the value of batch.label  (it is an array), https://github.com/dmlc/xgboost/blob/master/src/data/simple_csr_source.cc#L38 ?

**Comment by fc1plusx** [comment]
Before the failure, batch.label contains only zeros. Does this help in identifying the issue?

**Comment by fc1plusx** [comment]
Don't know if this helps but could be worth to mention: the last message in the log (after Spark retries the execute the task, and re-fails) is "rabit::Init is already called in this thread". This does not appear every time, but most of them.

**Comment by CodingCat** [comment]
It's more than one zeros? Just like a partition of data?

**Comment by fc1plusx** [comment]
The size (batch.size) is more than one (don't remember the exact value, is it important?) and all the values in batch.label are 0.

**Comment by CodingCat** [comment]
ok, I will check it

**Comment by glennq** [comment]
@CodingCat Wondering what's the current state of this bug? I'm had the exact same error when trying to predict for one example

**Comment by abelousova** [comment]
@CodingCat I also have the same error on this simple example:

`
import ml.dmlc.xgboost4j.scala.{XGBoost => XGBoostLocal, DMatrix}
import ml.dmlc.xgboost4j.scala.spark.{XGBoost => XGBoostSpark, XGBoostRegressionModel}
import org.apache.spark.ml.linalg.{Vector => MLVector, Vectors}
import org.apache.spark.sql.Row

case class Test(features: MLVector, id: Int)

val booster = XGBoostLocal.loadModel("xgboost.model")
val model = new XGBoostRegressionModel(booster)

val testDF = spark.createDataFrame(Seq(Test(Vectors.sparse(5000, Array.empty, Array.empty), 1)))

model.transform(testDF).show
`

Here `Test(Vectors.sparse(5000, Array.empty, Array.empty)` means row of zeros. The following code evaluates without error:

`
import ml.dmlc.xgboost4j.scala.{XGBoost => XGBoostLocal, DMatrix}
import ml.dmlc.xgboost4j.scala.spark.{XGBoost => XGBoostSpark, XGBoostRegressionModel}
import org.apache.spark.ml.linalg.{Vector => MLVector, Vectors}
import org.apache.spark.sql.Row

case class Test(features: MLVector, id: Int)

val booster = XGBoostLocal.loadModel("xgboost.model")
val model = new XGBoostRegressionModel(booster)

val testDF = spark.createDataFrame(Seq(Test(Vectors.sparse(5000, Array(1), Array(0.0)), 1)))

model.transform(testDF).show
`  
So, it seems to happen only if array of indices is empty

**Comment by tmoerman** [comment]
Same error. 
To reproduce, you can check out following repo:
https://github.com/tmoerman/brassica/tree/903e897da28b0da89cab9eb7da641772760e373a

I run the XGBoostKaggleBosch test from within IntelliJ with java-8-oracle on ubuntu 16.10
(you need to download the data files in the test/resources folder, instructions included there)

```
Tracker started, with env={DMLC_NUM_SERVER=0, DMLC_TRACKER_URI=192.168.0.115, DMLC_TRACKER_PORT=9097, DMLC_NUM_WORKER=4}
[Stage 8:=======================================================> (86 + 2) / 88][22:45:24] dmlc-core/include/dmlc/./logging.h:300: [22:45:24] src/data/././sparse_batch_page.h:91: Check failed: batch.index != nullptr 

Stack trace returned 5 entries:
[bt] (0) /tmp/libxgboost4j3201111363368296041.so(_ZN7xgboost4data16SparsePageSource6CreateEPN4dmlc6ParserIjEERKNSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEEE+0x30b5) [0x7fcbf3480ca5]
[bt] (1) /tmp/libxgboost4j3201111363368296041.so(_ZN7xgboost7DMatrix6CreateEPN4dmlc6ParserIjEERKNSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEEE+0x1eb) [0x7fcbf349086b]
[bt] (2) /tmp/libxgboost4j3201111363368296041.so(XGDMatrixCreateFromDataIter+0x13f) [0x7fcbf355116f]
[bt] (3) /tmp/libxgboost4j3201111363368296041.so(Java_ml_dmlc_xgboost4j_java_XGBoostJNI_XGDMatrixCreateFromDataIter+0x53) [0x7fcbf33dda33]
[bt] (4) [0x7fd0ebf7ab94]

[22:45:24] SparsePage::Writer Finished writing to 66fb8e77-11cd-4064-a2d9-193ecd5b7003-9-dtrain_cache-2.row.page
17/02/08 22:45:24 WARN BlockManager: Putting block rdd_36_2 failed
17/02/08 22:45:24 ERROR Executor: Exception in task 2.0 in stage 9.0 (TID 224)
ml.dmlc.xgboost4j.java.XGBoostError: [22:45:24] src/data/././sparse_batch_page.h:91: Check failed: batch.index != nullptr 

Stack trace returned 5 entries:
[bt] (0) /tmp/libxgboost4j3201111363368296041.so(_ZN7xgboost4data16SparsePageSource6CreateEPN4dmlc6ParserIjEERKNSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEEE+0x30b5) [0x7fcbf3480ca5]
[bt] (1) /tmp/libxgboost4j3201111363368296041.so(_ZN7xgboost7DMatrix6CreateEPN4dmlc6ParserIjEERKNSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEEE+0x1eb) [0x7fcbf349086b]
[bt] (2) /tmp/libxgboost4j3201111363368296041.so(XGDMatrixCreateFromDataIter+0x13f) [0x7fcbf355116f]
[bt] (3) /tmp/libxgboost4j3201111363368296041.so(Java_ml_dmlc_xgboost4j_java_XGBoostJNI_XGDMatrixCreateFromDataIter+0x53) [0x7fcbf33dda33]
[bt] (4) [0x7fd0ebf7ab94]

	at ml.dmlc.xgboost4j.java.JNIErrorHandle.checkCall(JNIErrorHandle.java:48)
	at ml.dmlc.xgboost4j.java.DMatrix.<init>(DMatrix.java:68)
	at ml.dmlc.xgboost4j.scala.spark.XGBoost$$anonfun$buildDistributedBoosters$1.apply(XGBoost.scala:125)
	at ml.dmlc.xgboost4j.scala.spark.XGBoost$$anonfun$buildDistributedBoosters$1.apply(XGBoost.scala:111)
	at org.apache.spark.rdd.RDD$$anonfun$mapPartitions$1$$anonfun$apply$23.apply(RDD.scala:766)
	at org.apache.spark.rdd.RDD$$anonfun$mapPartitions$1$$anonfun$apply$23.apply(RDD.scala:766)
	at org.apache.spark.rdd.MapPartitionsRDD.compute(MapPartitionsRDD.scala:38)
	at org.apache.spark.rdd.RDD.computeOrReadCheckpoint(RDD.scala:319)
	at org.apache.spark.rdd.RDD$$anonfun$8.apply(RDD.scala:332)
	at org.apache.spark.rdd.RDD$$anonfun$8.apply(RDD.scala:330)
	at org.apache.spark.storage.BlockManager$$anonfun$doPutIterator$1.apply(BlockManager.scala:919)
	at org.apache.spark.storage.BlockManager$$anonfun$doPutIterator$1.apply(BlockManager.scala:910)
	at org.apache.spark.storage.BlockManager.doPut(BlockManager.scala:866)
	at org.apache.spark.storage.BlockManager.doPutIterator(BlockManager.scala:910)
	at org.apache.spark.storage.BlockManager.getOrElseUpdate(BlockManager.scala:668)
	at org.apache.spark.rdd.RDD.getOrCompute(RDD.scala:330)
	at org.apache.spark.rdd.RDD.iterator(RDD.scala:281)
	at org.apache.spark.scheduler.ResultTask.runTask(ResultTask.scala:70)
	at org.apache.spark.scheduler.Task.run(Task.scala:85)
	at org.apache.spark.executor.Executor$TaskRunner.run(Executor.scala:274)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
17/02/08 22:45:24 WARN TaskSetManager: Lost task 2.0 in stage 9.0 (TID 224, localhost): ml.dmlc.xgboost4j.java.XGBoostError: [22:45:24] src/data/././sparse_batch_page.h:91: Check failed: batch.index != nullptr 
```

Hope this is helpful.

**Comment by convexquad** [comment]
I have also recently encountered this assertion. @abelousova is correct, in that the cause of this issue is attempting to pass data that is entirely sparse to XGBoost. Here is an even shorter unit test that I have added to my code that demonstrates the problem.
```
package com.linkedin.xgboost.ml.training

import ml.dmlc.xgboost4j.scala.spark.DataUtils
import org.apache.spark.ml.linalg.{SparseVector, Vector}
import org.testng.Assert.assertNotEquals
import org.testng.annotations.Test

class XGBoostReadSparseVectorTest {
  @Test
  def testConvertSparseVector() : Unit = {
    val features : Seq[Vector] = Seq(new SparseVector(size = 10, indices = Array[Int](), values = Array[Double]()))

    import DataUtils._
    val xgbIterator = DataUtils.fromSparkVectorToXGBoostPointsJava(features.iterator)

    // Check that the matrix was actually initialized
    val javaDMatrix = new ml.dmlc.xgboost4j.java.DMatrix(xgbIterator, null)
    assertNotEquals(javaDMatrix.getHandle, 0)
  }
}
```
This unit test will fail with the `batch.index != nullptr` assertion. I have been tracing the problem through to the underlying C++ code, and the following things happen. First, the Java `DMatrix` class calls native code through JNI that ends up in the native `XGDMatrixCreateFromDataIter` method in `./src/c_api/c_api.cc`. This method creates a `NativeDataIter parser(data_handle, **callback)` and calls `DMatrix::Create(&parser, scache)`.

The `NativeDataIter` class has a `SetData` method that does the following:
```
class NativeDataIter : public dmlc::Parser<uint32_t> {
  ...
  // callback to set the data
  void SetData(const XGBoostBatchCSR& batch) {
    ...
    if (batch.index != nullptr) {
      index_.insert(index_.end(), batch.index + offset_[0], batch.index + offset_.back());
    }
    ...
    block_.index = dmlc::BeginPtr(index_);
  }
}

// From: dmlc-core/include/dmlc/base.h, the dmlc::BeginPtr method does this:
template<typename T> inline T *BeginPtr(std::vector<T> &vec) {  // NOLINT(*)
  if (vec.size() == 0) {
    return NULL;
  } else {
    return &vec[0];
  }
}
```
So you can see that if you pass entirely sparse data to XGBoost, the `NativeDataIter` parser will get a batch of rows (that is entirely sparse), and will end up setting `block_.index = NULL` since the feature index on the batch is also null.

I think this code all makes complete sense. However, the null index ends up propagating through to `src/data/simple_csr_source.cc`, causing the assertion to fail.

**Comment by convexquad** [comment]
Basically, I think the solution to this issue is to remove the failing assertion in `src/data/simple_csr_source.cc`, i.e. comment out the line `CHECK(batch.index != nullptr)`.

I think this assertion is invalid. When `batch.index == NULL`, it indicates that the batch of data is entirely sparse. This should be a valid case handled by XGBoost without error.

There is an argument to be made that users should never pass XGBoost entirely sparse data, as it is likely that this condition indicates that something is wrong with the data. However, this argument is not right. At LinkedIn, we are using trained XGBoost models to evaluate larger and larger incoming datasets.

Our data workflows often one-hot encode the incoming features, since the data is often fed into multiple machine learning models (most of which use non-XGBoost linear methods). Because the distribution of values used with the one-hot encoding tend to shift over time, it is often the case that the incoming features no longer match many of the one-hot encoded features used to train the model (and are thus dropped). Every once in a while, none of the one-hot features match the features used to train the model (and are thus all dropped), and so the input to the model ends up being entirely sparse. While it's true that the output of the model won't be very helpful, this should definitely NOT cause an assertion failure in production.

That's my argument for why dropping this assertion makes sense. Please note - this is as far as I have traced the code. Currently I don't believe that dropping this assertion can make other problems appear, but I am not sure about that! Perhaps others that know the code better can double-check.

I'll post a (very short) pull request for this soon.

**Comment by CodingCat** [comment]
@convexquad , thanks for finding it out

I am not sure about whether completely moving the assertion will break other things, 

I didn't track into that part, but will changing the assertion to 

```c++
CHECK(batch.size == 0 || batch.index != nullptr)
```

safer?

**Comment by convexquad** [comment]
@CodingCat I don't think that changing the assertion to `CHECK(batch.size == 0 || batch.index != nullptr)` will help, because `batch.size` refers to the number of rows, while I think `batch.index` refers to the first column (feature) with dense values.

It is possible to give XGBoost a batch of several rows at once, but all with completely sparse data - this will trigger this assertion (but my claim is that it should not).

**Comment by CodingCat** [comment]
I see, I thought size refers to vector length as in Spark, then your change makes sense
