### ISSUE TITLE
Unknown Updater grow_gpu

### ISSUE THREAD

**Issue by JoshuaC3** [dmlc/xgboost#1905]
@RAMitchell I am currently getting the following,

```XGBoostError: b'[17:52:27] src/tree/tree_updater.cc:18: Unknown tree updater grow_gpu'```

To get to this stage I did the following:
1) Downloaded cub-1.6.4 and unzip into '/home/josh'
2) Then in terminal the following,
```
git clone --recursive https://github.com/dmlc/xgboost
cd xgboost
mkdir build
cd build
cmake .. -DPLUGIN_UPDATER_GPU=ON -DCUB_DIRECTORY=/home/josh/cub-1.6.4
make
```
Also tried instead of `make`, `cd ..; make -j4`

3) for the python package
```
sudo pip3 uninstall xgboost
cd python-package/
sudo python3 setup.py install
```

## Environment info
Operating System: Ubuntu 16.04

`xgboost` version used: latest from git clone (0.6a2 I believe).

If installing from source, please provide 

1. The commit hash (`git rev-parse HEAD`): unsure of how to find
2. Logs attached

If you are using python package, please provide

1. The python version and distribution: 3.5.2 from https://www.python.org/downloads/
2. The command to install `xgboost` if you are not installing from source: included above I believe.

**Comment by JoshuaC3** [comment]
@RAMitchell

**Comment by JoshuaC3** [comment]
[cmake_logs.txt](https://github.com/dmlc/xgboost/files/671271/cmake_logs.txt)
[make_j4_logs.txt](https://github.com/dmlc/xgboost/files/671273/make_j4_logs.txt)
[make_logs.txt](https://github.com/dmlc/xgboost/files/671274/make_logs.txt)
[python_logs.txt](https://github.com/dmlc/xgboost/files/671276/python_logs.txt)

**Comment by xysmas** [comment]
I have the exact same error:

`XGBoostError: b'[14:50:42] src/tree/tree_updater.cc:18: Unknown tree updater grow_gpu'
`

I installed cub 1.6.4, have cmake 3.7, and am on python 3.5.2 (anaconda). 

commit: 1957e6fb4dd823f94251e7378abef03cba05f545

the build commands were: 
```
git clone --recursive https://github.com/dmlc/xgboost
cd xgboost
mkdir build
cd build
cmake .. -DPLUGIN_UPDATER_GPU=ON -DCUB_DIRECTORY=/home/agonzales/git/cub-1.6.4
make
```

**Comment by RAMitchell** [comment]
According to the logs the shared library seems to have been built correctly.

Can you test if the CLI version works with the parameter? This will show if it is a python installation problem or something else.

**Comment by xysmas** [comment]
```
agonzales@beast01n:~/git/xgboost/demo/gpu_acceleration > python bosch.py
[10:14:47] dmlc-core/include/dmlc/./logging.h:235: [10:14:47] src/tree/tree_updater.cc:18: Unknown tree updater grow_gpu
Traceback (most recent call last):
  File "bosch.py", line 38, in <module>
    bst = xgb.train(param, dtrain, num_round)
  File "/home/agonzales/anaconda3/envs/keras_extract/lib/python3.5/site-packages/xgboost-0.6-py3.5.egg/xgboost/training.py", line 204, in train
    xgb_model=xgb_model, callbacks=callbacks)
  File "/home/agonzales/anaconda3/envs/keras_extract/lib/python3.5/site-packages/xgboost-0.6-py3.5.egg/xgboost/training.py", line 74, in _train_internal
    bst.update(dtrain, i, obj)
  File "/home/agonzales/anaconda3/envs/keras_extract/lib/python3.5/site-packages/xgboost-0.6-py3.5.egg/xgboost/core.py", line 819, in update
    _check_call(_LIB.XGBoosterUpdateOneIter(self.handle, iteration, dtrain.handle))
  File "/home/agonzales/anaconda3/envs/keras_extract/lib/python3.5/site-packages/xgboost-0.6-py3.5.egg/xgboost/core.py", line 127, in _check_call
    raise XGBoostError(_LIB.XGBGetLastError())
xgboost.core.XGBoostError: b'[10:14:47] src/tree/tree_updater.cc:18: Unknown tree updater grow_gpu'
```

@RAMitchell 
Same issue. XGB works great without it after a fresh install, including with the gpu compilation options.

**Comment by xysmas** [comment]
@RAMitchell I tested it with a virtual python2 install (exactly the same steps and xgb version as my above comment) and it works:

```
(keras_converter) agonzales@beast01n:~/git/xgboost/demo/gpu_acceleration > python bosch.py
[10:22:53] Allocated 2651/10532 MB on GeForce GTX TITAN X
Fold 0: [0]	eval-auc:0.687821, Boost Time 10.2420949936
[10:23:03] Allocated 2649/10524 MB on GeForce GTX TITAN X
Fold 1: [0]	eval-auc:0.699437, Boost Time 7.22127199173
[10:23:12] Allocated 2650/10524 MB on GeForce GTX TITAN X
Fold 2: [0]	eval-auc:0.679232, Boost Time 7.27566719055
[10:23:22] Allocated 2648/10524 MB on GeForce GTX TITAN X
Fold 3: [0]	eval-auc:0.663752, Boost Time 7.22304797173
[10:23:31] Allocated 2650/10524 MB on GeForce GTX TITAN X
Fold 4: [0]	eval-auc:0.698049, Boost Time 7.10676598549
```

**Comment by xysmas** [comment]
And now, after a bit of messing around, it compiles and works on my anaconda python3, though the process is a bit weird.


```
(keras_extract) agonzales@beast01n:~/git/xgboost > pip uninstall xgboost
Uninstalling xgboost-0.6:
  /home/agonzales/anaconda3/envs/keras_extract/lib/python3.5/site-packages/xgboost-0.6-py3.5.egg
Proceed (y/n)? y
  Successfully uninstalled xgboost-0.6
(keras_extract) agonzales@beast01n:~/git/xgboost > make clean
rm -f -rf build build_plugin lib bin *~ */*~ */*/*~ */*/*/*~ */*.o */*/*.o */*/*/*.o xgboost
rm -f -rf build_tests *.gcov tests/cpp/xgboost_test
(keras_extract) agonzales@beast01n:~/git/xgboost > mkdir build
(keras_extract) agonzales@beast01n:~/git/xgboost > cd build/
(keras_extract) agonzales@beast01n:~/git/xgboost/build > cmake .. -DPLUGIN_UPDATER_GPU=ON -DCUB_DIRECTORY=/home/agonzales/git/cub-1.6.4
-- The C compiler identification is GNU 4.8.4
-- The CXX compiler identification is GNU 4.8.4
-- Check for working C compiler: /usr/bin/cc
-- Check for working C compiler: /usr/bin/cc -- works
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Detecting C compile features
-- Detecting C compile features - done
-- Check for working CXX compiler: /usr/bin/c++
-- Check for working CXX compiler: /usr/bin/c++ -- works
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Detecting CXX compile features
-- Detecting CXX compile features - done
-- Try OpenMP C flag = [-fopenmp]
-- Performing Test OpenMP_FLAG_DETECTED
-- Performing Test OpenMP_FLAG_DETECTED - Success
-- Try OpenMP CXX flag = [-fopenmp]
-- Performing Test OpenMP_FLAG_DETECTED
-- Performing Test OpenMP_FLAG_DETECTED - Success
-- Found OpenMP: -fopenmp
-- Performing Test COMPILER_SUPPORTS_CXX11
-- Performing Test COMPILER_SUPPORTS_CXX11 - Success
-- Performing Test COMPILER_SUPPORTS_CXX0X
-- Performing Test COMPILER_SUPPORTS_CXX0X - Success
-- Performing Test SUPPORT_CXX0X
-- Performing Test SUPPORT_CXX0X - Success
-- Performing Test SUPPORT_MSSE2
-- Performing Test SUPPORT_MSSE2 - Success
-- Looking for pthread.h
-- Looking for pthread.h - found
-- Looking for pthread_create
-- Looking for pthread_create - not found
-- Looking for pthread_create in pthreads
-- Looking for pthread_create in pthreads - not found
-- Looking for pthread_create in pthread
-- Looking for pthread_create in pthread - found
-- Found Threads: TRUE
-- Configuring done
-- Generating done
-- Build files have been written to: /home/agonzales/git/xgboost/build

```

```
(keras_extract) agonzales@beast01n:~/git/xgboost/build > make all -j8
[  1%] Building NVCC (Device) object CMakeFiles/updater_gpu.dir/plugin/updater_gpu/src/updater_gpu_generated_gpu_builder.cu.o
Scanning dependencies of target rabit
Scanning dependencies of target dmlccore
[  2%] Building CXX object CMakeFiles/rabit.dir/rabit/src/allreduce_base.cc.o
[  3%] Building CXX object CMakeFiles/rabit.dir/rabit/src/allreduce_robust.cc.o
[  4%] Building CXX object CMakeFiles/rabit.dir/rabit/src/engine.cc.o
[  5%] Building CXX object dmlc-core/CMakeFiles/dmlccore.dir/src/config.cc.o
[  7%] Building CXX object CMakeFiles/rabit.dir/rabit/src/c_api.cc.o
[  8%] Building CXX object dmlc-core/CMakeFiles/dmlccore.dir/src/data.cc.o
[  9%] Building CXX object dmlc-core/CMakeFiles/dmlccore.dir/src/io.cc.o
[ 10%] Building CXX object dmlc-core/CMakeFiles/dmlccore.dir/src/recordio.cc.o
[ 11%] Building CXX object dmlc-core/CMakeFiles/dmlccore.dir/src/io/line_split.cc.o
[ 13%] Building CXX object dmlc-core/CMakeFiles/dmlccore.dir/src/io/recordio_split.cc.o
[ 14%] Building CXX object dmlc-core/CMakeFiles/dmlccore.dir/src/io/input_split_base.cc.o
[ 15%] Building CXX object dmlc-core/CMakeFiles/dmlccore.dir/src/io/local_filesys.cc.o
/home/agonzales/git/xgboost/plugin/updater_gpu/src/gpu_data.cuh(127): error: expected a "{" introducing a lambda body

/home/agonzales/git/xgboost/plugin/updater_gpu/src/gpu_data.cuh(127): error: expected a ")"

/home/agonzales/git/xgboost/plugin/updater_gpu/src/gpu_data.cuh(131): warning: parsing restarts here after previous syntax error
.... <LOTS OF ERROR OUTPUT OMMITTED> ...

/home/agonzales/git/xgboost/plugin/updater_gpu/src/gpu_builder.cu(281): error: identifier "RegTree" is undefined

/home/agonzales/git/xgboost/plugin/updater_gpu/src/gpu_builder.cu(281): error: identifier "tree" is undefined

/home/agonzales/git/xgboost/plugin/updater_gpu/src/gpu_builder.cu(281): error: expected a ";"

/home/agonzales/git/xgboost/plugin/updater_gpu/src/gpu_builder.cu(302): warning: parsing restarts here after previous syntax error

/home/agonzales/git/xgboost/plugin/updater_gpu/src/gpu_builder.cu(303): error: expected a declaration

At end of source: warning: parsing restarts here after previous syntax error

[ 16%] Linking CXX static library librabit.a
[ 16%] Built target rabit
/usr/include/c++/4.8/bits/stl_vector.h(87): error: "_Tp_alloc_type" is not a nonstatic data member or base class of class "std::_Vector_base<<error-type>, std::allocator<<error-type>>>::_Vector_impl"
          detected during:
            instantiation of "std::_Vector_base<_Tp, _Alloc>::_Vector_impl::_Vector_impl() [with _Tp=<error-type>, _Alloc=std::allocator<<error-type>>]"
(125): here
            instantiation of "std::_Vector_base<_Tp, _Alloc>::_Vector_base() [with _Tp=<error-type>, _Alloc=std::allocator<<error-type>>]"
(249): here
            instantiation of "std::vector<_Tp, _Alloc>::vector() [with _Tp=<error-type>, _Alloc=std::allocator<<error-type>>]"
/home/agonzales/git/xgboost/plugin/updater_gpu/src/gpu_builder.cu(206): here

Error limit reached.
100 errors detected in the compilation of "/tmp/tmpxft_00005557_00000000-7_gpu_builder.cpp1.ii".
Compilation terminated.
CMake Error at updater_gpu_generated_gpu_builder.cu.o.cmake:282 (message):
  Error generating file
  /home/agonzales/git/xgboost/build/CMakeFiles/updater_gpu.dir/plugin/updater_gpu/src/./updater_gpu_generated_gpu_builder.cu.o


make[2]: *** [CMakeFiles/updater_gpu.dir/plugin/updater_gpu/src/updater_gpu_generated_gpu_builder.cu.o] Error 1
make[1]: *** [CMakeFiles/updater_gpu.dir/all] Error 2
make[1]: *** Waiting for unfinished jobs....
[ 17%] Linking CXX static library libdmlccore.a
[ 17%] Built target dmlccore
make: *** [all] Error 2
```

I accidentally did this:

```
keras_extract) agonzales@beast01n:~/git/xgboost/build > make clean
(keras_extract) agonzales@beast01n:~/git/xgboost/build > make all -j8
-- Configuring done
-- Generating done
-- Build files have been written to: /home/agonzales/git/xgboost/build
[  1%] Building CXX object CMakeFiles/rabit.dir/rabit/src/engine.cc.o
[  2%] Building CXX object CMakeFiles/rabit.dir/rabit/src/allreduce_base.cc.o
[  3%] Building CXX object CMakeFiles/rabit.dir/rabit/src/allreduce_robust.cc.o
[  4%] Building CXX object CMakeFiles/rabit.dir/rabit/src/c_api.cc.o
[  5%] Building CXX object dmlc-core/CMakeFiles/dmlccore.dir/src/config.cc.o
[  7%] Building CXX object dmlc-core/CMakeFiles/dmlccore.dir/src/data.cc.o
[  8%] Building CXX object dmlc-core/CMakeFiles/dmlccore.dir/src/io.cc.o
[  9%] Building NVCC (Device) object CMakeFiles/updater_gpu.dir/plugin/updater_gpu/src/updater_gpu_generated_gpu_builder.cu.o
[ 10%] Building CXX object dmlc-core/CMakeFiles/dmlccore.dir/src/recordio.cc.o
[ 11%] Building CXX object dmlc-core/CMakeFiles/dmlccore.dir/src/io/line_split.cc.o
[ 13%] Building CXX object dmlc-core/CMakeFiles/dmlccore.dir/src/io/recordio_split.cc.o
[ 14%] Building CXX object dmlc-core/CMakeFiles/dmlccore.dir/src/io/input_split_base.cc.o
[ 15%] Building CXX object dmlc-core/CMakeFiles/dmlccore.dir/src/io/local_filesys.cc.o
/home/agonzales/git/xgboost/include/xgboost/././feature_map.h(66): warning: type qualifier on return type is meaningless

[ 16%] Linking CXX static library librabit.a
[ 16%] Built target rabit
[ 17%] Linking CXX static library libdmlccore.a
[ 17%] Built target dmlccore
/home/agonzales/git/xgboost/include/xgboost/././feature_map.h(66): warning: type qualifier on return type is meaningless

/home/agonzales/git/xgboost/plugin/updater_gpu/src/device_helpers.cuh: In destructor ‘dh::bulk_allocator::~bulk_allocator()’:
/home/agonzales/git/xgboost/plugin/updater_gpu/src/device_helpers.cuh:369:19: warning: NULL used in arithmetic [-Wpointer-arith]
     if (!d_ptr == NULL) {
                   ^
Scanning dependencies of target updater_gpu
[ 19%] Linking CXX static library libupdater_gpu.a
[ 19%] Built target updater_gpu
Scanning dependencies of target xgboost
Scanning dependencies of target libxgboost
[ 20%] Building CXX object CMakeFiles/xgboost.dir/src/common/common.cc.o
[ 21%] Building CXX object CMakeFiles/xgboost.dir/src/c_api/c_api.cc.o
[ 22%] Building CXX object CMakeFiles/xgboost.dir/src/c_api/c_api_error.cc.o
[ 23%] Building CXX object CMakeFiles/xgboost.dir/src/data/data.cc.o
[ 25%] Building CXX object CMakeFiles/xgboost.dir/src/data/sparse_page_dmatrix.cc.o
[ 26%] Building CXX object CMakeFiles/xgboost.dir/src/data/simple_csr_source.cc.o
[ 27%] Building CXX object CMakeFiles/xgboost.dir/src/data/simple_dmatrix.cc.o
[ 28%] Building CXX object CMakeFiles/libxgboost.dir/src/c_api/c_api.cc.o
[ 29%] Building CXX object CMakeFiles/libxgboost.dir/src/c_api/c_api_error.cc.o
[ 30%] Building CXX object CMakeFiles/libxgboost.dir/src/common/common.cc.o
[ 32%] Building CXX object CMakeFiles/xgboost.dir/src/data/sparse_page_raw_format.cc.o
[ 33%] Building CXX object CMakeFiles/xgboost.dir/src/data/sparse_page_source.cc.o
[ 34%] Building CXX object CMakeFiles/libxgboost.dir/src/data/data.cc.o
[ 35%] Building CXX object CMakeFiles/libxgboost.dir/src/data/simple_csr_source.cc.o
[ 36%] Building CXX object CMakeFiles/libxgboost.dir/src/data/simple_dmatrix.cc.o
[ 38%] Building CXX object CMakeFiles/libxgboost.dir/src/data/sparse_page_dmatrix.cc.o
[ 39%] Building CXX object CMakeFiles/xgboost.dir/src/data/sparse_page_writer.cc.o
[ 40%] Building CXX object CMakeFiles/libxgboost.dir/src/data/sparse_page_raw_format.cc.o
[ 41%] Building CXX object CMakeFiles/xgboost.dir/src/gbm/gblinear.cc.o
[ 42%] Building CXX object CMakeFiles/xgboost.dir/src/gbm/gbm.cc.o
[ 44%] Building CXX object CMakeFiles/xgboost.dir/src/gbm/gbtree.cc.o
[ 45%] Building CXX object CMakeFiles/libxgboost.dir/src/data/sparse_page_source.cc.o
[ 46%] Building CXX object CMakeFiles/libxgboost.dir/src/data/sparse_page_writer.cc.o
[ 47%] Building CXX object CMakeFiles/libxgboost.dir/src/gbm/gblinear.cc.o
[ 48%] Building CXX object CMakeFiles/xgboost.dir/src/metric/elementwise_metric.cc.o
[ 50%] Building CXX object CMakeFiles/libxgboost.dir/src/gbm/gbm.cc.o
[ 51%] Building CXX object CMakeFiles/libxgboost.dir/src/gbm/gbtree.cc.o
[ 52%] Building CXX object CMakeFiles/xgboost.dir/src/metric/metric.cc.o
[ 53%] Building CXX object CMakeFiles/xgboost.dir/src/metric/multiclass_metric.cc.o
[ 54%] Building CXX object CMakeFiles/xgboost.dir/src/metric/rank_metric.cc.o
[ 55%] Building CXX object CMakeFiles/libxgboost.dir/src/metric/elementwise_metric.cc.o
[ 57%] Building CXX object CMakeFiles/libxgboost.dir/src/metric/metric.cc.o
[ 58%] Building CXX object CMakeFiles/libxgboost.dir/src/metric/multiclass_metric.cc.o
[ 59%] Building CXX object CMakeFiles/libxgboost.dir/src/metric/rank_metric.cc.o
[ 60%] Building CXX object CMakeFiles/libxgboost.dir/src/objective/multiclass_obj.cc.o
[ 61%] Building CXX object CMakeFiles/xgboost.dir/src/objective/multiclass_obj.cc.o
[ 63%] Building CXX object CMakeFiles/xgboost.dir/src/objective/objective.cc.o
[ 64%] Building CXX object CMakeFiles/xgboost.dir/src/objective/rank_obj.cc.o
[ 65%] Building CXX object CMakeFiles/libxgboost.dir/src/objective/objective.cc.o
[ 66%] Building CXX object CMakeFiles/libxgboost.dir/src/objective/rank_obj.cc.o
[ 67%] Building CXX object CMakeFiles/libxgboost.dir/src/objective/regression_obj.cc.o
[ 69%] Building CXX object CMakeFiles/xgboost.dir/src/objective/regression_obj.cc.o
[ 70%] Building CXX object CMakeFiles/xgboost.dir/src/tree/tree_model.cc.o
[ 71%] Building CXX object CMakeFiles/xgboost.dir/src/tree/tree_updater.cc.o
[ 72%] Building CXX object CMakeFiles/libxgboost.dir/src/tree/tree_model.cc.o
[ 73%] Building CXX object CMakeFiles/xgboost.dir/src/tree/updater_colmaker.cc.o
[ 75%] Building CXX object CMakeFiles/libxgboost.dir/src/tree/tree_updater.cc.o
[ 76%] Building CXX object CMakeFiles/xgboost.dir/src/tree/updater_histmaker.cc.o
[ 77%] Building CXX object CMakeFiles/libxgboost.dir/src/tree/updater_colmaker.cc.o
[ 78%] Building CXX object CMakeFiles/libxgboost.dir/src/tree/updater_histmaker.cc.o
[ 79%] Building CXX object CMakeFiles/libxgboost.dir/src/tree/updater_prune.cc.o
[ 80%] Building CXX object CMakeFiles/xgboost.dir/src/tree/updater_prune.cc.o
[ 82%] Building CXX object CMakeFiles/libxgboost.dir/src/tree/updater_refresh.cc.o
[ 83%] Building CXX object CMakeFiles/xgboost.dir/src/tree/updater_refresh.cc.o
[ 84%] Building CXX object CMakeFiles/libxgboost.dir/src/tree/updater_skmaker.cc.o
[ 85%] Building CXX object CMakeFiles/xgboost.dir/src/tree/updater_skmaker.cc.o
[ 86%] Building CXX object CMakeFiles/libxgboost.dir/src/tree/updater_sync.cc.o
[ 88%] Building CXX object CMakeFiles/xgboost.dir/src/tree/updater_sync.cc.o
[ 89%] Building CXX object CMakeFiles/libxgboost.dir/src/cli_main.cc.o
[ 90%] Building CXX object CMakeFiles/xgboost.dir/src/cli_main.cc.o
[ 91%] Building CXX object CMakeFiles/xgboost.dir/src/learner.cc.o
[ 92%] Building CXX object CMakeFiles/libxgboost.dir/src/learner.cc.o
[ 94%] Building CXX object CMakeFiles/xgboost.dir/src/logging.cc.o
[ 95%] Building CXX object CMakeFiles/xgboost.dir/plugin/updater_gpu/src/updater_gpu.cc.o
[ 96%] Building CXX object CMakeFiles/libxgboost.dir/src/logging.cc.o
[ 97%] Building CXX object CMakeFiles/libxgboost.dir/plugin/updater_gpu/src/updater_gpu.cc.o
[ 98%] Linking CXX executable ../xgboost
[ 98%] Built target xgboost
[100%] Linking CXX shared library ../lib/libxgboost.so
[100%] Built target libxgboost
```

And then went ahead with the rest of it anyway:

```
(keras_extract) agonzales@beast01n:~/git/xgboost/build > cd ../python-package/
(keras_extract) agonzales@beast01n:~/git/xgboost/python-package > python setup.py install
Install libxgboost from: ['/home/agonzales/git/xgboost/python-package/xgboost/../../lib/libxgboost.so']
running install
running bdist_egg
running egg_info
writing dependency_links to xgboost.egg-info/dependency_links.txt
writing requirements to xgboost.egg-info/requires.txt
writing xgboost.egg-info/PKG-INFO
writing top-level names to xgboost.egg-info/top_level.txt
reading manifest file 'xgboost.egg-info/SOURCES.txt'
reading manifest template 'MANIFEST.in'
warning: no files found matching '*' under directory 'xgboost/include'
warning: no files found matching '*' under directory 'xgboost/src'
warning: no files found matching '*' under directory 'xgboost/make'
warning: no files found matching '*' under directory 'xgboost/rabit'
warning: no files found matching '*' under directory 'xgboost/lib'
warning: no files found matching '*' under directory 'xgboost/dmlc-core'
warning: no previously-included files matching '*.o' found anywhere in distribution
warning: no previously-included files matching '*.a' found anywhere in distribution
warning: no previously-included files matching '*.pyo' found anywhere in distribution
warning: no previously-included files matching '*.pyc' found anywhere in distribution
writing manifest file 'xgboost.egg-info/SOURCES.txt'
installing library code to build/bdist.linux-x86_64/egg
running install_lib
running build_py
creating build/bdist.linux-x86_64/egg
creating build/bdist.linux-x86_64/egg/xgboost
copying build/lib/xgboost/libpath.py -> build/bdist.linux-x86_64/egg/xgboost
copying build/lib/xgboost/__init__.py -> build/bdist.linux-x86_64/egg/xgboost
copying build/lib/xgboost/rabit.py -> build/bdist.linux-x86_64/egg/xgboost
copying build/lib/xgboost/training.py -> build/bdist.linux-x86_64/egg/xgboost
copying build/lib/xgboost/sklearn.py -> build/bdist.linux-x86_64/egg/xgboost
copying build/lib/xgboost/plotting.py -> build/bdist.linux-x86_64/egg/xgboost
copying build/lib/xgboost/compat.py -> build/bdist.linux-x86_64/egg/xgboost
copying build/lib/xgboost/callback.py -> build/bdist.linux-x86_64/egg/xgboost
copying build/lib/xgboost/core.py -> build/bdist.linux-x86_64/egg/xgboost
copying build/lib/xgboost/build-python.sh -> build/bdist.linux-x86_64/egg/xgboost
copying build/lib/xgboost/VERSION -> build/bdist.linux-x86_64/egg/xgboost
byte-compiling build/bdist.linux-x86_64/egg/xgboost/libpath.py to libpath.cpython-35.pyc
byte-compiling build/bdist.linux-x86_64/egg/xgboost/__init__.py to __init__.cpython-35.pyc
byte-compiling build/bdist.linux-x86_64/egg/xgboost/rabit.py to rabit.cpython-35.pyc
byte-compiling build/bdist.linux-x86_64/egg/xgboost/training.py to training.cpython-35.pyc
byte-compiling build/bdist.linux-x86_64/egg/xgboost/sklearn.py to sklearn.cpython-35.pyc
byte-compiling build/bdist.linux-x86_64/egg/xgboost/plotting.py to plotting.cpython-35.pyc
byte-compiling build/bdist.linux-x86_64/egg/xgboost/compat.py to compat.cpython-35.pyc
byte-compiling build/bdist.linux-x86_64/egg/xgboost/callback.py to callback.cpython-35.pyc
byte-compiling build/bdist.linux-x86_64/egg/xgboost/core.py to core.cpython-35.pyc
installing package data to build/bdist.linux-x86_64/egg
running install_data
copying /home/agonzales/git/xgboost/python-package/xgboost/../../lib/libxgboost.so -> build/bdist.linux-x86_64/egg/xgboost
creating build/bdist.linux-x86_64/egg/EGG-INFO
copying xgboost.egg-info/PKG-INFO -> build/bdist.linux-x86_64/egg/EGG-INFO
copying xgboost.egg-info/SOURCES.txt -> build/bdist.linux-x86_64/egg/EGG-INFO
copying xgboost.egg-info/dependency_links.txt -> build/bdist.linux-x86_64/egg/EGG-INFO
copying xgboost.egg-info/not-zip-safe -> build/bdist.linux-x86_64/egg/EGG-INFO
copying xgboost.egg-info/requires.txt -> build/bdist.linux-x86_64/egg/EGG-INFO
copying xgboost.egg-info/top_level.txt -> build/bdist.linux-x86_64/egg/EGG-INFO
creating 'dist/xgboost-0.6-py3.5.egg' and adding 'build/bdist.linux-x86_64/egg' to it
removing 'build/bdist.linux-x86_64/egg' (and everything under it)
Processing xgboost-0.6-py3.5.egg
creating /home/agonzales/anaconda3/envs/keras_extract/lib/python3.5/site-packages/xgboost-0.6-py3.5.egg
Extracting xgboost-0.6-py3.5.egg to /home/agonzales/anaconda3/envs/keras_extract/lib/python3.5/site-packages
Adding xgboost 0.6 to easy-install.pth file

Installed /home/agonzales/anaconda3/envs/keras_extract/lib/python3.5/site-packages/xgboost-0.6-py3.5.egg
Processing dependencies for xgboost==0.6
Searching for scipy==0.18.0
Best match: scipy 0.18.0
Adding scipy 0.18.0 to easy-install.pth file

Using /home/agonzales/anaconda3/envs/keras_extract/lib/python3.5/site-packages
Searching for numpy==1.11.1
Best match: numpy 1.11.1
Adding numpy 1.11.1 to easy-install.pth file

Using /home/agonzales/anaconda3/envs/keras_extract/lib/python3.5/site-packages
Finished processing dependencies for xgboost==0.6
```

Running the command line test:
```
(keras_extract) agonzales@beast01n:~/git/xgboost/build > cd ../demo/gpu_acceleration/
(keras_extract) agonzales@beast01n:~/git/xgboost/demo/gpu_acceleration > python bosch.py
[10:55:46] Allocated 2651/10532 MB on GeForce GTX TITAN X
Fold 0: [0]	eval-auc:0.713140, Boost Time 10.291077136993408
[10:55:59] Allocated 2650/10524 MB on GeForce GTX TITAN X
Fold 1: [0]	eval-auc:0.692409, Boost Time 7.394563674926758
[10:56:12] Allocated 2651/10524 MB on GeForce GTX TITAN X
Fold 2: [0]	eval-auc:0.684183, Boost Time 7.361444711685181
[10:56:25] Allocated 2648/10524 MB on GeForce GTX TITAN X
Fold 3: [0]	eval-auc:0.676257, Boost Time 7.309280872344971
[10:56:37] Allocated 2650/10524 MB on GeForce GTX TITAN X
Fold 4: [0]	eval-auc:0.679325, Boost Time 7.381667613983154
```

**Comment by benoua** [comment]
I did the same stage as you, but the make did not go through. I had to runit twice : 

- git clone --recursive https://github.com/dmlc/xgboost
- cd xgboost
- mkdir build
- cd build
- cmake .. -DPLUGIN_UPDATER_GPU=ON -DCUB_DIRECTORY=/home/josh/cub-1.6.4
- make
- make

**Comment by HanWangwang** [comment]
@xysmas    @贝努阿      guys，I try to install gpu_group in Windows 7.The step of cmake is successful with VS 2015，but I cant find makefile in xgboost/build.very sad,please help me.
