### ISSUE TITLE
[jvm-packages] xgboost-spark: model builds from spark java but throws exception

### ISSUE THREAD

**Issue by logisticDigressionSplitter** [dmlc/xgboost#1911]
## Environment info
MacOS 15.6.0 
xgboost: xgboost4j-spark-0.7-jar-with-dependencies.jar
JVM: 1.8
Spark: 2.0.1 / spark-core_2.11

## Code to invoke
```java
RDD<LabeledPoint> xgBoostData = ....
Map<String, Object> params = new HashMap<String, Object>();
params.put("max_depth", 14);
params.put("silent", 0);
params.put("booster", "gbtree");
params.put("num_class", stringIndexerModel.labels().length);
params.put("objective", "multi:softmax");
XGBoostModel xgbModel = null;
try {
	 xgbModel = XGBoost.train(xgBoostData, toScalaImmMap(params), 15, 4, null, null, true,				Float.NaN);
} catch (Exception ex) {
			ex.printStackTrace();
}
```
## Data
(2.0,(64000,[10684,41331,55946],[9.008534631779964,9.008534631779964,9.008534631779964]))
(4.0,(64000,[5589,13390,46801],[1.0003529699251523,1.0003529699251523,1.0003529699251523]))

**Total Rows: 109256**

**Here is an output during runtime....**
[10:22:41] src/tree/updater_prune.cc:74: tree pruning end, 1 roots, 262 extra nodes, 0 pruned nodes, max_depth=14
[10:22:42] src/tree/updater_prune.cc:74: tree pruning end, 1 roots, 278 extra nodes, 0 pruned nodes, max_depth=14
[14]	train-merror:0.197599

## Problem
The moment 

XGBoost.train(xgBoostData, toScalaImmMap(params), 15, 4, null, null, true,Float.NaN);

line gets invoked, the exception below gets thrown, but the model keeps building.

```java
10:47:47.023 [Thread-37] ERROR ml.dmlc.xgboost4j.java.RabitTracker - Uncaught exception thrown by worker:
java.lang.InterruptedException: null
	at java.util.concurrent.locks.AbstractQueuedSynchronizer.acquireSharedInterruptibly(AbstractQueuedSynchronizer.java:1302)
	at scala.concurrent.impl.Promise$DefaultPromise.tryAwait(Promise.scala:202)
	at scala.concurrent.impl.Promise$DefaultPromise.ready(Promise.scala:218)
	at scala.concurrent.impl.Promise$DefaultPromise.ready(Promise.scala:153)
	at org.apache.spark.scheduler.DAGScheduler.runJob(DAGScheduler.scala:623)
	at org.apache.spark.SparkContext.runJob(SparkContext.scala:1890)
	at org.apache.spark.SparkContext.runJob(SparkContext.scala:1903)
	at org.apache.spark.SparkContext.runJob(SparkContext.scala:1916)
	at org.apache.spark.SparkContext.runJob(SparkContext.scala:1930)
	at org.apache.spark.rdd.RDD$$anonfun$foreachPartition$1.apply(RDD.scala:902)
	at org.apache.spark.rdd.RDD$$anonfun$foreachPartition$1.apply(RDD.scala:900)
	at org.apache.spark.rdd.RDDOperationScope$.withScope(RDDOperationScope.scala:151)
	at org.apache.spark.rdd.RDDOperationScope$.withScope(RDDOperationScope.scala:112)
	at org.apache.spark.rdd.RDD.withScope(RDD.scala:358)
	at org.apache.spark.rdd.RDD.foreachPartition(RDD.scala:900)
```
and 
```java
ml.dmlc.xgboost4j.java.XGBoostError: XGBoostModel training failed
	at ml.dmlc.xgboost4j.scala.spark.XGBoost$.postTrackerReturnProcessing(XGBoost.scala:316)
	at ml.dmlc.xgboost4j.scala.spark.XGBoost$.trainWithRDD(XGBoost.scala:297)
	at ml.dmlc.xgboost4j.scala.spark.XGBoost$.train(XGBoost.scala:213)
	at ml.dmlc.xgboost4j.scala.spark.XGBoost.train(XGBoost.scala)
	at com.xyz.spark.pipeline.XGBoostClassifierPipeline.trainXGBoostModel(XGBoostClassifierPipeline.java:146)
	at com.xyz.spark.pipeline.XGBoostClassifierPipeline.trainAndEvaluate(XGBoostClassifierPipeline.java:213)
	at com.xyz.spark.pipeline.XGBoostClassifierPipeline.run(XGBoostClassifierPipeline.java:222)
	at com.xyz.spark.pipeline.XGBoostClassifierPipeline.main(XGBoostClassifierPipeline.java:255)
```

**Comment by CodingCat** [comment]
there is something wrong in your worker, please post the log in executors

**Comment by logisticDigressionSplitter** [comment]
I ended up figuring it out. I had to switch to scala tracker and it worked.
This 
```java
TrackerConf tracker_conf = new TrackerConf(scala.concurrent.duration.Duration.create(500, TimeUnit.SECONDS),"scala");
...
params.put("tracker_conf", tracker_conf);
...
```
does the trick. Thank you for your follow up.
