### ISSUE TITLE
[jvm-package] xgboost4j-spark no connection to rabit

### ISSUE THREAD

**Issue by geoHeil** [dmlc/xgboost#1924]
For bugs or installation issues, please provide the following information.
The more information you provide, the more easily we will be able to offer
help and advice.

## Environment info
Operating System: osx 10.12.2

`xgboost` version used: current master branch, xgboost4j

```
XGBoostDFSuite:
Using Spark's default log4j profile: org/apache/spark/log4j-defaults.properties
17/01/02 11:56:52 INFO SparkContext: Running Spark version 2.0.2
17/01/02 11:56:53 WARN NativeCodeLoader: Unable to load native-hadoop library for your platform... using builtin-java classes where applicable
17/01/02 11:56:53 INFO SecurityManager: Changing view acls to: geoHeil
17/01/02 11:56:53 INFO SecurityManager: Changing modify acls to: geoHeil
17/01/02 11:56:53 INFO SecurityManager: Changing view acls groups to:
17/01/02 11:56:53 INFO SecurityManager: Changing modify acls groups to:
17/01/02 11:56:53 INFO SecurityManager: SecurityManager: authentication disabled; ui acls disabled; users  with view permissions: Set(geoHeil); groups with view permissions: Set(); users  with modify permissions: Set(geoHeil); groups with modify permissions: Set()
17/01/02 11:56:53 INFO Utils: Successfully started service 'sparkDriver' on port 49904.
17/01/02 11:56:53 INFO SparkEnv: Registering MapOutputTracker
17/01/02 11:56:53 INFO SparkEnv: Registering BlockManagerMaster
17/01/02 11:56:53 INFO DiskBlockManager: Created local directory at /private/var/folders/zm/bts0g37j0l9637sjxb3b700h0000gn/T/blockmgr-5cbba0d1-f6c4-4d9e-aa90-6e514cf97eff
17/01/02 11:56:53 INFO MemoryStore: MemoryStore started with capacity 2004.6 MB
17/01/02 11:56:53 INFO SparkEnv: Registering OutputCommitCoordinator
17/01/02 11:56:53 INFO Utils: Successfully started service 'SparkUI' on port 4040.
17/01/02 11:56:53 INFO SparkUI: Bound SparkUI to 0.0.0.0, and started at http://128.131.237.249:4040
17/01/02 11:56:54 INFO Executor: Starting executor ID driver on host localhost
17/01/02 11:56:54 INFO Utils: Successfully started service 'org.apache.spark.network.netty.NettyBlockTransferService' on port 49905.
17/01/02 11:56:54 INFO NettyBlockTransferService: Server created on 128.131.237.249:49905
17/01/02 11:56:54 INFO BlockManagerMaster: Registering BlockManager BlockManagerId(driver, 128.131.237.249, 49905)
17/01/02 11:56:54 INFO BlockManagerMasterEndpoint: Registering block manager 128.131.237.249:49905 with 2004.6 MB RAM, BlockManagerId(driver, 128.131.237.249, 49905)
17/01/02 11:56:54 INFO BlockManagerMaster: Registered BlockManager BlockManagerId(driver, 128.131.237.249, 49905)
Tracker started, with env={DMLC_NUM_SERVER=0, DMLC_TRACKER_URI=128.131.237.249, DMLC_TRACKER_PORT=9091, DMLC_NUM_WORKER=8}
retry connect to ip(retry time 1): [128.131.237.249]
retry connect to ip(retry time 1): [128.131.237.249]
retry connect to ip(retry time 1): [128.131.237.249]
retry connect to ip(retry time 1): [128.131.237.249]
retry connect to ip(retry time 1): [128.131.237.249]
retry connect to ip(retry time 1): [128.131.237.249]
retry connect to ip(retry time 1): [128.131.237.249]
retry connect to ip(retry time 1): [128.131.237.249]
retry connect to ip(retry time 2): [128.131.237.249]
retry connect to ip(retry time 2): [128.131.237.249]
retry connect to ip(retry time 2): [128.131.237.249]
retry connect to ip(retry time 2): [128.131.237.249]
retry connect to ip(retry time 2): [128.131.237.249]
retry connect to ip(retry time 2): [128.131.237.249]
retry connect to ip(retry time 2): [128.131.237.249]
retry connect to ip(retry time 2): [128.131.237.249]
retry connect to ip(retry time 3): [128.131.237.249]
retry connect to ip(retry time 3): [128.131.237.249]
retry connect to ip(retry time 3): [128.131.237.249]
retry connect to ip(retry time 3): [128.131.237.249]
retry connect to ip(retry time 3): [128.131.237.249]
retry connect to ip(retry time 3): [128.131.237.249]
retry connect to ip(retry time 3): [128.131.237.249]
retry connect to ip(retry time 3): [128.131.237.249]
retry connect to ip(retry time 4): [128.131.237.249]
retry connect to ip(retry time 4): [128.131.237.249]
retry connect to ip(retry time 4): [128.131.237.249]
retry connect to ip(retry time 4): [128.131.237.249]
retry connect to ip(retry time 4): [128.131.237.249]
retry connect to ip(retry time 4): [128.131.237.249]
retry connect to ip(retry time 4): [128.131.237.249]
retry connect to ip(retry time 4): [128.131.237.249]
connect to (failed): [128.131.237.249]
Socket Connect Error:Invalid argument
connect to (failed): [128.131.237.249]
connect to (failed): [128.131.237.249]
connect to (failed): [128.131.237.249]
connect to (failed): [128.131.237.249]
Socket Connect Error:Invalid argument
connect to (failed): [128.131.237.249]
connect to (failed): [128.131.237.249]
connect to (failed): [128.131.237.249]
Socket Connect Error:Invalid argument
Socket Connect Error:Invalid argument
Socket Connect Error:Invalid argument
Socket Connect Error:Invalid argument
Socket Connect Error:Invalid argument
Socket Connect Error:Invalid argument
[INFO] ------------------------------------------------------------------------
[INFO] Reactor Summary:
[INFO]
[INFO] xgboost-jvm ........................................ SUCCESS [  3.546 s]
[INFO] xgboost4j .......................................... SUCCESS [ 23.662 s]
[INFO] xgboost4j-spark .................................... FAILURE [01:45 min]
[INFO] xgboost4j-flink .................................... SKIPPED
[INFO] xgboost4j-example .................................. SKIPPED
```
## Steps to reproduce

1. execute `mvn install` the problem is this happens only sometimes. (works fine on ubuntu)

## What have you tried?

1. Rebooting (helping sometimes)
2. combination of rebooting + deleting `.m2` and `.ivy` caches (helping sometimes)

**Comment by xydrolase** [comment]
How many network interfaces do you have on the machine?
Were you using the Python or Scala Rabit tracker?

**Comment by geoHeil** [comment]
I was using the default implementation. This is still the pyton variant isn't it? How can I configure whether python or scala implementation is chosen?

It is just a normal macbook pro. So there are 2 real interfaces for WiFi and Ethernet and Thunderbolt ports as well as some virtual interfaces from docker, virtual box and parallels. 

```
networksetup -listallhardwareports
Hardware Port: Wi-Fi
Device: en0
Ethernet Address: id1

Hardware Port: Bluetooth PAN
Device: en3
Ethernet Address: id2

Hardware Port: Thunderbolt 1
Device: en1
Ethernet Address: id3

Hardware Port: Thunderbolt 2
Device: en2
Ethernet Address: id4

Hardware Port: Thunderbolt Bridge
Device: bridge0
Ethernet Address: id5

VLAN Configurations
===================
```

**Comment by geoHeil** [comment]
In fact, I could track down the problem and am pretty sure that when connected to a VPN the main error reported above is caused.

**Comment by xydrolase** [comment]
You can change the tracker configuration by using parameter `trackerConf` in the parameter map.

See https://github.com/dmlc/xgboost/blob/e7fbc8591fa7277ee4c474b7371c48c11b34cbde/jvm-packages/xgboost4j-spark/src/test/scala/ml/dmlc/xgboost4j/scala/spark/XGBoostGeneralSuite.scala#L112 for example.

**Comment by geoHeil** [comment]
Thanks. Can confirm that it is the VPN. 
Strange, that "local" connections are affected as well.

**Comment by douglasren** [comment]
18/03/02 15:33:03 WARN hdfs.BlockReaderFactory: I/O error constructing remote block reader.
java.net.SocketTimeoutException: 60000 millis timeout while waiting for channel to be ready for read. ch : java.nio.channels.SocketChannel[connected local=/10.10.0.156:35700 remote=/10.10.0.149:50010]
	at org.apache.hadoop.net.SocketIOWithTimeout.doIO(SocketIOWithTimeout.java:164)
	at org.apache.hadoop.net.SocketInputStream.read(SocketInputStream.java:161)
	at org.apache.hadoop.net.SocketInputStream.read(SocketInputStream.java:131)
	at org.apache.hadoop.net.SocketInputStream.read(SocketInputStream.java:118)
	at java.io.FilterInputStream.read(FilterInputStream.java:83)
	at org.apache.hadoop.hdfs.protocolPB.PBHelper.vintPrefixed(PBHelper.java:2272)
	at org.apache.hadoop.hdfs.RemoteBlockReader2.newBlockReader(RemoteBlockReader2.java:430)
	at org.apache.hadoop.hdfs.BlockReaderFactory.getRemoteBlockReader(BlockReaderFactory.java:881)
	at org.apache.hadoop.hdfs.BlockReaderFactory.getRemoteBlockReaderFromTcp(BlockReaderFactory.java:759)
	at org.apache.hadoop.hdfs.BlockReaderFactory.build(BlockReaderFactory.java:376)
	at org.apache.hadoop.hdfs.DFSInputStream.blockSeekTo(DFSInputStream.java:658)
	at org.apache.hadoop.hdfs.DFSInputStream.readWithStrategy(DFSInputStream.java:895)
	at org.apache.hadoop.hdfs.DFSInputStream.read(DFSInputStream.java:954)
	at org.apache.hadoop.hdfs.DFSInputStream.read(DFSInputStream.java:748)
	at java.io.FilterInputStream.read(FilterInputStream.java:83)
	at parquet.bytes.BytesUtils.readIntLittleEndian(BytesUtils.java:66)
	at parquet.hadoop.ParquetFileReader.readFooter(ParquetFileReader.java:419)
	at parquet.hadoop.ParquetFileReader.readFooter(ParquetFileReader.java:386)
	at org.apache.spark.sql.execution.datasources.parquet.SpecificParquetRecordReaderBase.initialize(SpecificParquetRecordReaderBase.java:107)
	at org.apache.spark.sql.execution.datasources.parquet.VectorizedParquetRecordReader.initialize(VectorizedParquetRecordReader.java:109)
	at org.apache.spark.sql.execution.datasources.parquet.ParquetFileFormat$$anonfun$buildReader$1.apply(ParquetFileFormat.scala:382)
	at org.apache.spark.sql.execution.datasources.parquet.ParquetFileFormat$$anonfun$buildReader$1.apply(ParquetFileFormat.scala:356)
	at org.apache.spark.sql.execution.datasources.FileScanRDD$$anon$1.nextIterator(FileScanRDD.scala:168)
	at org.apache.spark.sql.execution.datasources.FileScanRDD$$anon$1.hasNext(FileScanRDD.scala:109)
	at org.apache.spark.sql.catalyst.expressions.GeneratedClass$GeneratedIterator.scan_nextBatch$(Unknown Source)
	at org.apache.spark.sql.catalyst.expressions.GeneratedClass$GeneratedIterator.processNext(Unknown Source)
	at org.apache.spark.sql.execution.BufferedRowIterator.hasNext(BufferedRowIterator.java:43)
	at org.apache.spark.sql.execution.WholeStageCodegenExec$$anonfun$8$$anon$1.hasNext(WholeStageCodegenExec.scala:377)
	at scala.collection.Iterator$$anon$11.hasNext(Iterator.scala:408)
	at scala.collection.Iterator$$anon$11.hasNext(Iterator.scala:408)
	at scala.collection.Iterator$$anon$11.hasNext(Iterator.scala:408)
	at scala.collection.Iterator$$anon$11.hasNext(Iterator.scala:408)
	at org.apache.spark.sql.catalyst.expressions.GeneratedClass$GeneratedIterator.processNext(Unknown Source)
	at org.apache.spark.sql.execution.BufferedRowIterator.hasNext(BufferedRowIterator.java:43)
	at org.apache.spark.sql.execution.WholeStageCodegenExec$$anonfun$8$$anon$1.hasNext(WholeStageCodegenExec.scala:377)
	at org.apache.spark.sql.execution.columnar.InMemoryRelation$$anonfun$1$$anon$1.next(InMemoryRelation.scala:99)
	at org.apache.spark.sql.execution.columnar.InMemoryRelation$$anonfun$1$$anon$1.next(InMemoryRelation.scala:91)
	at org.apache.spark.storage.memory.MemoryStore.putIteratorAsValues(MemoryStore.scala:216)
	at org.apache.spark.storage.BlockManager$$anonfun$doPutIterator$1.apply(BlockManager.scala:1016)
	at org.apache.spark.storage.BlockManager$$anonfun$doPutIterator$1.apply(BlockManager.scala:1007)
	at org.apache.spark.storage.BlockManager.doPut(BlockManager.scala:947)
	at org.apache.spark.storage.BlockManager.doPutIterator(BlockManager.scala:1007)
	at org.apache.spark.storage.BlockManager.getOrElseUpdate(BlockManager.scala:711)
	at org.apache.spark.rdd.RDD.getOrCompute(RDD.scala:334)
	at org.apache.spark.rdd.RDD.iterator(RDD.scala:285)
	at org.apache.spark.rdd.MapPartitionsRDD.compute(MapPartitionsRDD.scala:38)
	at org.apache.spark.rdd.RDD.computeOrReadCheckpoint(RDD.scala:323)
	at org.apache.spark.rdd.RDD.iterator(RDD.scala:287)
	at org.apache.spark.rdd.MapPartitionsRDD.compute(MapPartitionsRDD.scala:38)
	at org.apache.spark.rdd.RDD.computeOrReadCheckpoint(RDD.scala:323)
	at org.apache.spark.rdd.RDD.iterator(RDD.scala:287)
	at org.apache.spark.rdd.MapPartitionsRDD.compute(MapPartitionsRDD.scala:38)
	at org.apache.spark.rdd.RDD.computeOrReadCheckpoint(RDD.scala:323)
	at org.apache.spark.rdd.RDD.iterator(RDD.scala:287)
	at org.apache.spark.scheduler.ShuffleMapTask.runTask(ShuffleMapTask.scala:96)
	at org.apache.spark.scheduler.ShuffleMapTask.runTask(ShuffleMapTask.scala:53)
	at org.apache.spark.scheduler.Task.run(Task.scala:99)
	at org.apache.spark.executor.Executor$TaskRunner.run(Executor.scala:325)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:748)
18/03/02 15:33:03 WARN hdfs.DFSClient: Failed to connect to /10.10.0.149:50010 for block, add to deadNodes and continue. java.net.SocketTimeoutException: 60000 millis timeout while waiting for channel to be ready for read. ch : java.nio.channels.SocketChannel[connected local=/10.10.0.156:35700 remote=/10.10.0.149:50010]
java.net.SocketTimeoutException: 60000 millis timeout while waiting for channel to be ready for read. ch : java.nio.channels.SocketChannel[connected local=/10.10.0.156:35700 remote=/10.10.0.149:50010]
	at org.apache.hadoop.net.SocketIOWithTimeout.doIO(SocketIOWithTimeout.java:164)
	at org.apache.hadoop.net.SocketInputStream.read(SocketInputStream.java:161)
	at org.apache.hadoop.net.SocketInputStream.read(SocketInputStream.java:131)
	at org.apache.hadoop.net.SocketInputStream.read(SocketInputStream.java:118)
	at java.io.FilterInputStream.read(FilterInputStream.java:83)
	at org.apache.hadoop.hdfs.protocolPB.PBHelper.vintPrefixed(PBHelper.java:2272)
	at org.apache.hadoop.hdfs.RemoteBlockReader2.newBlockReader(RemoteBlockReader2.java:430)
	at org.apache.hadoop.hdfs.BlockReaderFactory.getRemoteBlockReader(BlockReaderFactory.java:881)
	at org.apache.hadoop.hdfs.BlockReaderFactory.getRemoteBlockReaderFromTcp(BlockReaderFactory.java:759)
	at org.apache.hadoop.hdfs.BlockReaderFactory.build(BlockReaderFactory.java:376)
	at org.apache.hadoop.hdfs.DFSInputStream.blockSeekTo(DFSInputStream.java:658)
	at org.apache.hadoop.hdfs.DFSInputStream.readWithStrategy(DFSInputStream.java:895)
	at org.apache.hadoop.hdfs.DFSInputStream.read(DFSInputStream.java:954)
	at org.apache.hadoop.hdfs.DFSInputStream.read(DFSInputStream.java:748)
	at java.io.FilterInputStream.read(FilterInputStream.java:83)
	at parquet.bytes.BytesUtils.readIntLittleEndian(BytesUtils.java:66)
	at parquet.hadoop.ParquetFileReader.readFooter(ParquetFileReader.java:419)
	at parquet.hadoop.ParquetFileReader.readFooter(ParquetFileReader.java:386)
	at org.apache.spark.sql.execution.datasources.parquet.SpecificParquetRecordReaderBase.initialize(SpecificParquetRecordReaderBase.java:107)
	at org.apache.spark.sql.execution.datasources.parquet.VectorizedParquetRecordReader.initialize(VectorizedParquetRecordReader.java:109)
	at org.apache.spark.sql.execution.datasources.parquet.ParquetFileFormat$$anonfun$buildReader$1.apply(ParquetFileFormat.scala:382)
	at org.apache.spark.sql.execution.datasources.parquet.ParquetFileFormat$$anonfun$buildReader$1.apply(ParquetFileFormat.scala:356)
	at org.apache.spark.sql.execution.datasources.FileScanRDD$$anon$1.nextIterator(FileScanRDD.scala:168)
	at org.apache.spark.sql.execution.datasources.FileScanRDD$$anon$1.hasNext(FileScanRDD.scala:109)
	at org.apache.spark.sql.catalyst.expressions.GeneratedClass$GeneratedIterator.scan_nextBatch$(Unknown Source)
	at org.apache.spark.sql.catalyst.expressions.GeneratedClass$GeneratedIterator.processNext(Unknown Source)
	at org.apache.spark.sql.execution.BufferedRowIterator.hasNext(BufferedRowIterator.java:43)
	at org.apache.spark.sql.execution.WholeStageCodegenExec$$anonfun$8$$anon$1.hasNext(WholeStageCodegenExec.scala:377)
	at scala.collection.Iterator$$anon$11.hasNext(Iterator.scala:408)
	at scala.collection.Iterator$$anon$11.hasNext(Iterator.scala:408)
	at scala.collection.Iterator$$anon$11.hasNext(Iterator.scala:408)
	at scala.collection.Iterator$$anon$11.hasNext(Iterator.scala:408)
	at org.apache.spark.sql.catalyst.expressions.GeneratedClass$GeneratedIterator.processNext(Unknown Source)
	at org.apache.spark.sql.execution.BufferedRowIterator.hasNext(BufferedRowIterator.java:43)
	at org.apache.spark.sql.execution.WholeStageCodegenExec$$anonfun$8$$anon$1.hasNext(WholeStageCodegenExec.scala:377)
	at org.apache.spark.sql.execution.columnar.InMemoryRelation$$anonfun$1$$anon$1.next(InMemoryRelation.scala:99)
	at org.apache.spark.sql.execution.columnar.InMemoryRelation$$anonfun$1$$anon$1.next(InMemoryRelation.scala:91)
	at org.apache.spark.storage.memory.MemoryStore.putIteratorAsValues(MemoryStore.scala:216)
	at org.apache.spark.storage.BlockManager$$anonfun$doPutIterator$1.apply(BlockManager.scala:1016)
	at org.apache.spark.storage.BlockManager$$anonfun$doPutIterator$1.apply(BlockManager.scala:1007)
	at org.apache.spark.storage.BlockManager.doPut(BlockManager.scala:947)
	at org.apache.spark.storage.BlockManager.doPutIterator(BlockManager.scala:1007)
	at org.apache.spark.storage.BlockManager.getOrElseUpdate(BlockManager.scala:711)
	at org.apache.spark.rdd.RDD.getOrCompute(RDD.scala:334)
	at org.apache.spark.rdd.RDD.iterator(RDD.scala:285)
	at org.apache.spark.rdd.MapPartitionsRDD.compute(MapPartitionsRDD.scala:38)
	at org.apache.spark.rdd.RDD.computeOrReadCheckpoint(RDD.scala:323)
	at org.apache.spark.rdd.RDD.iterator(RDD.scala:287)
	at org.apache.spark.rdd.MapPartitionsRDD.compute(MapPartitionsRDD.scala:38)
	at org.apache.spark.rdd.RDD.computeOrReadCheckpoint(RDD.scala:323)
	at org.apache.spark.rdd.RDD.iterator(RDD.scala:287)
	at org.apache.spark.rdd.MapPartitionsRDD.compute(MapPartitionsRDD.scala:38)
	at org.apache.spark.rdd.RDD.computeOrReadCheckpoint(RDD.scala:323)
	at org.apache.spark.rdd.RDD.iterator(RDD.scala:287)
	at org.apache.spark.scheduler.ShuffleMapTask.runTask(ShuffleMapTask.scala:96)
	at org.apache.spark.scheduler.ShuffleMapTask.runTask(ShuffleMapTask.scala:53)
	at org.apache.spark.scheduler.Task.run(Task.scala:99)
	at org.apache.spark.executor.Executor$TaskRunner.run(Executor.scala:325)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:748)
18/03/02 15:33:03 INFO hdfs.DFSClient: Successfully connected to /10.10.0.81:50010 for BP-1869368597-42.62.88.109-1461261349246:blk_3451834844_2378452488

18/03/02 15:34:38 INFO storage.BlockManager: Found block rdd_7_391 locally
retry connect to ip(retry time 1): [10.10.0.23]
retry connect to ip(retry time 1): [10.10.0.23]
retry connect to ip(retry time 1): [10.10.0.23]
retry connect to ip(retry time 1): [10.10.0.23]
retry connect to ip(retry time 1): [10.10.0.23]
retry connect to ip(retry time 1): [10.10.0.23]
retry connect to ip(retry time 1): [10.10.0.23]
retry connect to ip(retry time 1): [10.10.0.23]
retry connect to ip(retry time 1): [10.10.0.23]
retry connect to ip(retry time 1): [10.10.0.23]
retry connect to ip(retry time 2): [10.10.0.23]
retry connect to ip(retry time 2): [10.10.0.23]
retry connect to ip(retry time 2): [10.10.0.23]
retry connect to ip(retry time 2): [10.10.0.23]
retry connect to ip(retry time 2): [10.10.0.23]
retry connect to ip(retry time 2): [10.10.0.23]
retry connect to ip(retry time 2): [10.10.0.23]
retry connect to ip(retry time 2): [10.10.0.23]
retry connect to ip(retry time 2): [10.10.0.23]
retry connect to ip(retry time 2): [10.10.0.23]
retry connect to ip(retry time 3): [10.10.0.23]
retry connect to ip(retry time 3): [10.10.0.23]
retry connect to ip(retry time 3): [10.10.0.23]
retry connect to ip(retry time 3): [10.10.0.23]
retry connect to ip(retry time 3): [10.10.0.23]
retry connect to ip(retry time 3): [10.10.0.23]
retry connect to ip(retry time 3): [10.10.0.23]
retry connect to ip(retry time 3): [10.10.0.23]
retry connect to ip(retry time 3): [10.10.0.23]
retry connect to ip(retry time 3): [10.10.0.23]
retry connect to ip(retry time 4): [10.10.0.23]
retry connect to ip(retry time 4): [10.10.0.23]
retry connect to ip(retry time 4): [10.10.0.23]
retry connect to ip(retry time 4): [10.10.0.23]
retry connect to ip(retry time 4): [10.10.0.23]
retry connect to ip(retry time 4): [10.10.0.23]
retry connect to ip(retry time 4): [10.10.0.23]
retry connect to ip(retry time 4): [10.10.0.23]
retry connect to ip(retry time 4): [10.10.0.23]
retry connect to ip(retry time 4): [10.10.0.23]
connect to (failed): [10.10.0.23]
connect to (failed): [10.10.0.23]
connect to (failed): [10.10.0.23]
connect to (failed): [10.10.0.23]
connect to (failed): [10.10.0.23]
connect to (failed): [10.10.0.23]
Socket Connect Error:Connection refused
Socket Connect Error:Connection refused
Socket Connect Error:Connection refused
Socket Connect Error:Connection refused
Socket Connect Error:Connection refused
Socket Connect Error:Connection refused
pure virtual method called
terminate called without an active exception


I met the same problem, when run xgboost(v0.7) on yarn spark 2.1. I have try many times, the problem can be repeated
