### ISSUE TITLE
Can I output the xgboost R dmatrix to file and then load it by xgboost4j ?

### ISSUE THREAD

**Issue by penolove** [dmlc/xgboost#1942]
## Environment info
Operating System: 

Compiler: Centos

Package used (python/R/jvm/C++):

`xgboost` version used:
java : ml.dmlc.xgboost4j.0.7
R : > packageVersion("xgboost") : ‘0.4.0’

If you are using R package, please provide
> sessionInfo()
R version 3.1.3 (2015-03-09)
Platform: x86_64-w64-mingw32/x64 (64-bit)
Running under: Windows 7 x64 (build 7601) Service Pack 1

locale:
[1] LC_COLLATE=Chinese (Traditional)_Taiwan.950  LC_CTYPE=Chinese (Traditional)_Taiwan.950   
[3] LC_MONETARY=Chinese (Traditional)_Taiwan.950 LC_NUMERIC=C                                
[5] LC_TIME=Chinese (Traditional)_Taiwan.950    

attached base packages:
[1] stats     graphics  grDevices utils     datasets  methods   base     

other attached packages:
[1] xgboost_0.4-0

loaded via a namespace (and not attached):
[1] chron_2.3-45     data.table_1.9.6 grid_3.1.3       lattice_0.20-30  magrittr_1.5    
[6] Matrix_1.1-5     stringi_0.5-5    stringr_1.0.0    tools_3.1.3 

## Steps to reproduce
1.
r : xgb.DMatrix.save(dtrain, 'xgb.DMatrix.data')
java:  DMatrix trainMat = new DMatrix("/home/stream/Desktop/stupidjava/mvn2017/HelloXgb4J
/src/data/xgb.DMatrix.data");

java will occurs : 
[15:57:17] dmlc-core/include/dmlc/logging.h:235: [15:57:17] src/data/data.cc:51: Check failed: (version) == (kVersion) MetaInfo: invalid format
Exception in thread "main" ml.dmlc.xgboost4j.java.XGBoostError: [15:57:17] src/data/data.cc:51: Check failed: (version) == (kVersion) MetaInfo: invalid format
	at ml.dmlc.xgboost4j.java.JNIErrorHandle.checkCall(JNIErrorHandle.java:48)
	at ml.dmlc.xgboost4j.java.DMatrix.<init>(DMatrix.java:83)
	at com.myMaven.app.App.main(App.java:36)

## What have you tried?
1. I have tried that model outputed by R can be reused in java , I'm wondering if it's possible using R

**Comment by penolove** [comment]
Hi , R install with xgboost using the same compile version  as java solve this problem!!
