### ISSUE TITLE
Exception in thread "main" java.lang.NoClassDefFoundError: ml/dmlc/xgboost4j/scala/spark/XGBoost

### ISSUE THREAD

**Issue by philipus** [dmlc/xgboost#1948]
For bugs or installation issues, please provide the following information.
The more information you provide, the more easily we will be able to offer
help and advice.

## Environment info
Operating System: win 7

Compiler: gcc / java / mingw

Package used (python/R/jvm/C++): jvm

`xgboost` version used: 0.5

If installing from source, please provide 

1. The commit hash (`git rev-parse HEAD`)
2. Logs will be helpful (If logs are large, please upload as attachment).

Exception in thread "main" java.lang.NoClassDefFoundError: ml/dmlc/xgboost4j/scala/spark/XGBoost$
        at DistTrainWithSpark$.main(DistTrainWithSpark.scala:36)
        at DistTrainWithSpark.main(DistTrainWithSpark.scala)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:498)
        at org.apache.spark.deploy.SparkSubmit$.org$apache$spark$deploy$SparkSubmit$$runMain(SparkSubmit.scala:728)
        at org.apache.spark.deploy.SparkSubmit$.doRunMain$1(SparkSubmit.scala:177)
        at org.apache.spark.deploy.SparkSubmit$.submit(SparkSubmit.scala:202)
        at org.apache.spark.deploy.SparkSubmit$.main(SparkSubmit.scala:116)
        at org.apache.spark.deploy.SparkSubmit.main(SparkSubmit.scala)
Caused by: java.lang.ClassNotFoundException: ml.dmlc.xgboost4j.scala.spark.XGBoost$
        at java.net.URLClassLoader.findClass(URLClassLoader.java:381)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:357)

installed xgboost from source for jvm:

...
after a hard time :-) i managed to install xgboost4j:
   mvn -Dspark.version=2.0.2 install

If you are using python package, please provide

1. The python version and distribution
2. The command to install `xgboost` if you are not installing from source

If you are using R package, please provide

1. The R `sessionInfo()`
2. The command to install `xgboost` if you are not installing from source

## Steps to reproduce

1. compiled "DistTrainWithSpark.scala" sample -> success
2. 
/c/PFiles/spark/bin/spark-submit.cmd --class "DistTrainWithSpark" --master local[*] target/scala-2.10/disttrainwithspark_2.10-1.0.jar 1000 /c/PFiles/xgboost/demo/data/agaricus.txt.train /c/Users/ffloegel/DEV/DistTrainWithSpark/

3.  sparkConf.registerKryoClasses(Array(classOf[Booster])) compiled but i didnt managed to run using "/c/PFiles/spark/bin/spark-submit.cmd target/scala-2.10/disttrainwithspark_2.10-1.0.jar 1000 /c/PFiles/xgboost/demo/data/agaricus.txt.train /c/Users/ffloegel/DEV/DistTrainWithSpark/" the code

-> Exception in thread "main" java.lang.NoClassDefFoundError: ml/dmlc/xgboost4j/java/Booster 

4. so I used simply val sc = new SparkContext() and try to run the command like in (2)

## What have you tried?

1. 
try to load the xgbosst4j jar file manualy using

"/c/PFiles/spark/bin/spark-submit.cmd --class "DistTrainWithSpark" --master local[*] --jars /c/PFiles/xgboost/jvm-packages/xgboost4j/target/xgboost4j-0.5.jar target/scala-2.10/disttrainwithspark_2.10-1.0.jar 1000 /c/PFiles/xgboost/demo/data/agaricus.txt.train /c/Users/ffloegel/DEV/DistTrainWithSpark/"

but that failed completely....

2.
3.

so it compiled but it didnt run....
val trainRDD = MLUtils.loadLibSVMFile(sc, inputTrainPath) 

was ok but

val model = XGBoost.train(trainRDD, paramMap, numRound, nWorkers = 5, useExternalMemory = true)

didnt work

**Comment by pommedeterresautee** [comment]
Old question, no answer. Closing
