### ISSUE TITLE
Problems installing XGBoost-4j CentOS6

### ISSUE THREAD

**Issue by damienrj** [dmlc/xgboost#1994]
Hello,
I am trying to get XGBoost-4j installed on a CentOS6 box.  However when I try to follow the directions [here](https://xgboost.readthedocs.io/en/latest/jvm/index.html#installation) I get the following error:

```Jan 30, 2017 11:35:48 PM ml.dmlc.xgboost4j.java.NativeLibLoader smartLoad
SEVERE: failed to load library from both native path and jar
Jan 30, 2017 11:35:48 PM ml.dmlc.xgboost4j.java.DMatrix <clinit>
SEVERE: load native library failed.
Jan 30, 2017 11:35:48 PM ml.dmlc.xgboost4j.java.DMatrix <clinit>
SEVERE: java.io.FileNotFoundException: File /lib/libxgboost4j.so was not found inside JAR.
*** RUN ABORTED ***
  java.lang.UnsatisfiedLinkError: ml.dmlc.xgboost4j.java.XGBoostJNI.XGDMatrixCreateFromFile(Ljava/lang/String;I[J)I
  at ml.dmlc.xgboost4j.java.XGBoostJNI.XGDMatrixCreateFromFile(Native Method)
  at ml.dmlc.xgboost4j.java.DMatrix.<init>(DMatrix.java:83)
  at ml.dmlc.xgboost4j.scala.DMatrix.<init>(DMatrix.scala:31)
  at ml.dmlc.xgboost4j.scala.ScalaBoosterImplSuite$$anonfun$3.apply(ScalaBoosterImplSuite.scala:81)
  at ml.dmlc.xgboost4j.scala.ScalaBoosterImplSuite$$anonfun$3.apply(ScalaBoosterImplSuite.scala:80)
  at org.scalatest.OutcomeOf$class.outcomeOf(OutcomeOf.scala:85)
  at org.scalatest.OutcomeOf$.outcomeOf(OutcomeOf.scala:104)
  at org.scalatest.Transformer.apply(Transformer.scala:22)
  at org.scalatest.Transformer.apply(Transformer.scala:20)
  at org.scalatest.FunSuiteLike$$anon$1.apply(FunSuiteLike.scala:186)
  ...
[INFO] ------------------------------------------------------------------------
[INFO] Reactor Summary:
[INFO]
[INFO] xgboost-jvm ....................................... SUCCESS [3.139s]
[INFO] xgboost4j ......................................... FAILURE [3.797s]
[INFO] xgboost4j-spark ................................... SKIPPED
[INFO] xgboost4j-flink ................................... SKIPPED
[INFO] xgboost4j-example ................................. SKIPPED
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
```

However, in one post it was suggested to to mvn compile which does seem to work without errors, but then I still get the errors if I try `mvn package` or `mvn install`.  Are there some steps missing to build the libxgboost4j.so file?

**Comment by CodingCat** [comment]
can you check whether you can successfully compile native libraries?

**Comment by damienrj** [comment]
It looks like when I tried compiling with `create_jni` that is is failing due to a compiler age issue. I was able to get the normal xgboost compiled with a local newer compliler, and I will trying using the `libxgboost.so` generated from that.

**Comment by Lintong-common** [comment]
failure on Ubuntu 16.04
[ERROR] Command execution failed.
org.apache.commons.exec.ExecuteException: Process exited with an error: 127 (Exit value: 127)
	at org.apache.commons.exec.DefaultExecutor.executeInternal(DefaultExecutor.java:404)
	at org.apache.commons.exec.DefaultExecutor.execute(DefaultExecutor.java:166)
	at org.codehaus.mojo.exec.ExecMojo.executeCommandLine(ExecMojo.java:804)
	at org.codehaus.mojo.exec.ExecMojo.executeCommandLine(ExecMojo.java:751)
	at org.codehaus.mojo.exec.ExecMojo.execute(ExecMojo.java:313)
	at org.apache.maven.plugin.DefaultBuildPluginManager.executeMojo(DefaultBuildPluginManager.java:134)
	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:207)
	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:153)
	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:145)
	at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject(LifecycleModuleBuilder.java:116)
	at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject(LifecycleModuleBuilder.java:80)
	at org.apache.maven.lifecycle.internal.builder.singlethreaded.SingleThreadedBuilder.build(SingleThreadedBuilder.java:51)
	at org.apache.maven.lifecycle.internal.LifecycleStarter.execute(LifecycleStarter.java:128)
	at org.apache.maven.DefaultMaven.doExecute(DefaultMaven.java:307)
	at org.apache.maven.DefaultMaven.doExecute(DefaultMaven.java:193)
	at org.apache.maven.DefaultMaven.execute(DefaultMaven.java:106)
	at org.apache.maven.cli.MavenCli.execute(MavenCli.java:863)
	at org.apache.maven.cli.MavenCli.doMain(MavenCli.java:288)
	at org.apache.maven.cli.MavenCli.main(MavenCli.java:199)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.codehaus.plexus.classworlds.launcher.Launcher.launchEnhanced(Launcher.java:289)
	at org.codehaus.plexus.classworlds.launcher.Launcher.launch(Launcher.java:229)
	at org.codehaus.plexus.classworlds.launcher.Launcher.mainWithExitCode(Launcher.java:415)
	at org.codehaus.plexus.classworlds.launcher.Launcher.main(Launcher.java:356)
[INFO] ------------------------------------------------------------------------
[INFO] Reactor Summary:
[INFO] 
[INFO] xgboost-jvm ........................................ SUCCESS [06:39 min]
[INFO] xgboost4j .......................................... FAILURE [  5.562 s]
[INFO] xgboost4j-spark .................................... SKIPPED
[INFO] xgboost4j-flink .................................... SKIPPED
[INFO] xgboost4j-example .................................. SKIPPED
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 06:44 min
[INFO] Finished at: 2017-06-04T18:50:05+08:00
[INFO] Final Memory: 21M/203M
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal org.codehaus.mojo:exec-maven-plugin:1.6.0:exec (native) on project xgboost4j: Command execution failed. Process exited with an error: 127 (Exit value: 127) -> [Help 1]
[ERROR] 
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR] 
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/MojoExecutionException
[ERROR] 
[ERROR] After correcting the problems, you can resume the build with the command
[ERROR]   mvn <goals> -rf :xgboost4j

**Comment by marvin520** [comment]
any one can resolve this problem?

**Comment by superbobry** [comment]
@marvin520 can you detail your case? Does the compilation fail as well?
