### ISSUE TITLE
[jvm-packages] xgboost4j does not compile on windows 10

### ISSUE THREAD

**Issue by aszalucha** [dmlc/xgboost#2017]
I downloaded the latest version of xgboost from github, I compiled xgboost with MS VS 2015 and now when I try to
` mvn package`
 in jvm-packages folder I get the following errors ... 

```
[INFO] There are 82 errors reported by Checkstyle 6.11.2 with checkstyle.xml ruleset.
[ERROR] src\main\java\ml\dmlc\xgboost4j\java\XGBoostJNI.java:[2] (regexp) RegexpSingleline: No trailing whitespace allow
ed.
[ERROR] src\main\java\ml\dmlc\xgboost4j\java\XGBoostJNI.java:[7] (regexp) RegexpSingleline: No trailing whitespace allow
ed.
[ERROR] src\main\java\ml\dmlc\xgboost4j\java\XGBoostJNI.java:[23] (sizes) LineLength: Line is longer than 100 characters
 (found 104).
[ERROR] src\main\java\ml\dmlc\xgboost4j\java\XGBoostJNI.java:[28,16] (modifier) ModifierOrder: 'static' modifier out of
order with the JLS suggestions.
[ERROR] src\main\java\ml\dmlc\xgboost4j\java\XGBoostJNI.java:[28,37] (naming) MethodName: Method name 'XGBGetLastError'
must match pattern '^[a-z][a-z0-9][a-zA-Z0-9_]*$'.
[ERROR] src\main\java\ml\dmlc\xgboost4j\java\XGBoostJNI.java:[30,16] (modifier) ModifierOrder: 'static' modifier out of
order with the JLS suggestions.
[ERROR] src\main\java\ml\dmlc\xgboost4j\java\XGBoostJNI.java:[30,34] (naming) MethodName: Method name 'XGDMatrixCreateFr
omFile' must match pattern '^[a-z][a-z0-9][a-zA-Z0-9_]*$'.
[ERROR] src\main\java\ml\dmlc\xgboost4j\java\XGBoostJNI.java:[32,9] (modifier) ModifierOrder: 'static' modifier out of o
rder with the JLS suggestions.
[ERROR] src\main\java\ml\dmlc\xgboost4j\java\XGBoostJNI.java:[32,27] (naming) MethodName: Method name 'XGDMatrixCreateFr
omDataIter' must match pattern '^[a-z][a-z0-9][a-zA-Z0-9_]*$'.
[ERROR] src\main\java\ml\dmlc\xgboost4j\java\XGBoostJNI.java:[35] (sizes) LineLength: Line is longer than 100 characters
 (found 101).
[ERROR] src\main\java\ml\dmlc\xgboost4j\java\XGBoostJNI.java:[35,16] (modifier) ModifierOrder: 'static' modifier out of
order with the JLS suggestions.
[ERROR] src\main\java\ml\dmlc\xgboost4j\java\XGBoostJNI.java:[35,34] (naming) MethodName: Method name 'XGDMatrixCreateFr
omCSREx' must match pattern '^[a-z][a-z0-9][a-zA-Z0-9_]*$'.
[ERROR] src\main\java\ml\dmlc\xgboost4j\java\XGBoostJNI.java:[38] (sizes) LineLength: Line is longer than 100 characters
 (found 101).
[ERROR] src\main\java\ml\dmlc\xgboost4j\java\XGBoostJNI.java:[38,16] (modifier) ModifierOrder: 'static' modifier out of
order with the JLS suggestions.
[ERROR] src\main\java\ml\dmlc\xgboost4j\java\XGBoostJNI.java:[38,34] (naming) MethodName: Method name 'XGDMatrixCreateFr
omCSCEx' must match pattern '^[a-z][a-z0-9][a-zA-Z0-9_]*$'.
[ERROR] src\main\java\ml\dmlc\xgboost4j\java\XGBoostJNI.java:[41,16] (modifier) ModifierOrder: 'static' modifier out of
order with the JLS suggestions.
[ERROR] src\main\java\ml\dmlc\xgboost4j\java\XGBoostJNI.java:[41,34] (naming) MethodName: Method name 'XGDMatrixCreateFr
omMat' must match pattern '^[a-z][a-z0-9][a-zA-Z0-9_]*$'.
[ERROR] src\main\java\ml\dmlc\xgboost4j\java\XGBoostJNI.java:[44,16] (modifier) ModifierOrder: 'static' modifier out of
order with the JLS suggestions.
[ERROR] src\main\java\ml\dmlc\xgboost4j\java\XGBoostJNI.java:[44,34] (naming) MethodName: Method name 'XGDMatrixSliceDMa
trix' must match pattern '^[a-z][a-z0-9][a-zA-Z0-9_]*$'.
[ERROR] src\main\java\ml\dmlc\xgboost4j\java\XGBoostJNI.java:[46,16] (modifier) ModifierOrder: 'static' modifier out of
order with the JLS suggestions.
[ERROR] src\main\java\ml\dmlc\xgboost4j\java\XGBoostJNI.java:[46,34] (naming) MethodName: Method name 'XGDMatrixFree' mu
st match pattern '^[a-z][a-z0-9][a-zA-Z0-9_]*$'.
[ERROR] src\main\java\ml\dmlc\xgboost4j\java\XGBoostJNI.java:[48,16] (modifier) ModifierOrder: 'static' modifier out of
order with the JLS suggestions.
[ERROR] src\main\java\ml\dmlc\xgboost4j\java\XGBoostJNI.java:[48,34] (naming) MethodName: Method name 'XGDMatrixSaveBina
ry' must match pattern '^[a-z][a-z0-9][a-zA-Z0-9_]*$'.
[ERROR] src\main\java\ml\dmlc\xgboost4j\java\XGBoostJNI.java:[50,16] (modifier) ModifierOrder: 'static' modifier out of
order with the JLS suggestions.
[ERROR] src\main\java\ml\dmlc\xgboost4j\java\XGBoostJNI.java:[50,34] (naming) MethodName: Method name 'XGDMatrixSetFloat
Info' must match pattern '^[a-z][a-z0-9][a-zA-Z0-9_]*$'.
[ERROR] src\main\java\ml\dmlc\xgboost4j\java\XGBoostJNI.java:[52,16] (modifier) ModifierOrder: 'static' modifier out of
order with the JLS suggestions.
[ERROR] src\main\java\ml\dmlc\xgboost4j\java\XGBoostJNI.java:[52,34] (naming) MethodName: Method name 'XGDMatrixSetUIntI
nfo' must match pattern '^[a-z][a-z0-9][a-zA-Z0-9_]*$'.
[ERROR] src\main\java\ml\dmlc\xgboost4j\java\XGBoostJNI.java:[54,16] (modifier) ModifierOrder: 'static' modifier out of
order with the JLS suggestions.
[ERROR] src\main\java\ml\dmlc\xgboost4j\java\XGBoostJNI.java:[54,34] (naming) MethodName: Method name 'XGDMatrixSetGroup
' must match pattern '^[a-z][a-z0-9][a-zA-Z0-9_]*$'.
[ERROR] src\main\java\ml\dmlc\xgboost4j\java\XGBoostJNI.java:[56,16] (modifier) ModifierOrder: 'static' modifier out of
order with the JLS suggestions.
[ERROR] src\main\java\ml\dmlc\xgboost4j\java\XGBoostJNI.java:[56,34] (naming) MethodName: Method name 'XGDMatrixGetFloat
Info' must match pattern '^[a-z][a-z0-9][a-zA-Z0-9_]*$'.
[ERROR] src\main\java\ml\dmlc\xgboost4j\java\XGBoostJNI.java:[58,16] (modifier) ModifierOrder: 'static' modifier out of
order with the JLS suggestions.
[ERROR] src\main\java\ml\dmlc\xgboost4j\java\XGBoostJNI.java:[58,34] (naming) MethodName: Method name 'XGDMatrixGetUIntI
nfo' must match pattern '^[a-z][a-z0-9][a-zA-Z0-9_]*$'.
[ERROR] src\main\java\ml\dmlc\xgboost4j\java\XGBoostJNI.java:[60,16] (modifier) ModifierOrder: 'static' modifier out of
order with the JLS suggestions.
[ERROR] src\main\java\ml\dmlc\xgboost4j\java\XGBoostJNI.java:[60,34] (naming) MethodName: Method name 'XGDMatrixNumRow'
must match pattern '^[a-z][a-z0-9][a-zA-Z0-9_]*$'.
[ERROR] src\main\java\ml\dmlc\xgboost4j\java\XGBoostJNI.java:[62,16] (modifier) ModifierOrder: 'static' modifier out of
order with the JLS suggestions.
[ERROR] src\main\java\ml\dmlc\xgboost4j\java\XGBoostJNI.java:[62,34] (naming) MethodName: Method name 'XGBoosterCreate'
must match pattern '^[a-z][a-z0-9][a-zA-Z0-9_]*$'.
[ERROR] src\main\java\ml\dmlc\xgboost4j\java\XGBoostJNI.java:[64,16] (modifier) ModifierOrder: 'static' modifier out of
order with the JLS suggestions.
[ERROR] src\main\java\ml\dmlc\xgboost4j\java\XGBoostJNI.java:[64,34] (naming) MethodName: Method name 'XGBoosterFree' mu
st match pattern '^[a-z][a-z0-9][a-zA-Z0-9_]*$'.
[ERROR] src\main\java\ml\dmlc\xgboost4j\java\XGBoostJNI.java:[66,16] (modifier) ModifierOrder: 'static' modifier out of
order with the JLS suggestions.
[ERROR] src\main\java\ml\dmlc\xgboost4j\java\XGBoostJNI.java:[66,34] (naming) MethodName: Method name 'XGBoosterSetParam
' must match pattern '^[a-z][a-z0-9][a-zA-Z0-9_]*$'.
[ERROR] src\main\java\ml\dmlc\xgboost4j\java\XGBoostJNI.java:[68,16] (modifier) ModifierOrder: 'static' modifier out of
order with the JLS suggestions.
[ERROR] src\main\java\ml\dmlc\xgboost4j\java\XGBoostJNI.java:[68,34] (naming) MethodName: Method name 'XGBoosterUpdateOn
eIter' must match pattern '^[a-z][a-z0-9][a-zA-Z0-9_]*$'.
[ERROR] src\main\java\ml\dmlc\xgboost4j\java\XGBoostJNI.java:[70,16] (modifier) ModifierOrder: 'static' modifier out of
order with the JLS suggestions.
[ERROR] src\main\java\ml\dmlc\xgboost4j\java\XGBoostJNI.java:[70,34] (naming) MethodName: Method name 'XGBoosterBoostOne
Iter' must match pattern '^[a-z][a-z0-9][a-zA-Z0-9_]*$'.
[ERROR] src\main\java\ml\dmlc\xgboost4j\java\XGBoostJNI.java:[73,16] (modifier) ModifierOrder: 'static' modifier out of
order with the JLS suggestions.
[ERROR] src\main\java\ml\dmlc\xgboost4j\java\XGBoostJNI.java:[73,34] (naming) MethodName: Method name 'XGBoosterEvalOneI
ter' must match pattern '^[a-z][a-z0-9][a-zA-Z0-9_]*$'.
[ERROR] src\main\java\ml\dmlc\xgboost4j\java\XGBoostJNI.java:[76,16] (modifier) ModifierOrder: 'static' modifier out of
order with the JLS suggestions.
[ERROR] src\main\java\ml\dmlc\xgboost4j\java\XGBoostJNI.java:[76,34] (naming) MethodName: Method name 'XGBoosterPredict'
 must match pattern '^[a-z][a-z0-9][a-zA-Z0-9_]*$'.
[ERROR] src\main\java\ml\dmlc\xgboost4j\java\XGBoostJNI.java:[79,16] (modifier) ModifierOrder: 'static' modifier out of
order with the JLS suggestions.
[ERROR] src\main\java\ml\dmlc\xgboost4j\java\XGBoostJNI.java:[79,34] (naming) MethodName: Method name 'XGBoosterLoadMode
l' must match pattern '^[a-z][a-z0-9][a-zA-Z0-9_]*$'.
[ERROR] src\main\java\ml\dmlc\xgboost4j\java\XGBoostJNI.java:[81,16] (modifier) ModifierOrder: 'static' modifier out of
order with the JLS suggestions.
[ERROR] src\main\java\ml\dmlc\xgboost4j\java\XGBoostJNI.java:[81,34] (naming) MethodName: Method name 'XGBoosterSaveMode
l' must match pattern '^[a-z][a-z0-9][a-zA-Z0-9_]*$'.
[ERROR] src\main\java\ml\dmlc\xgboost4j\java\XGBoostJNI.java:[83,16] (modifier) ModifierOrder: 'static' modifier out of
order with the JLS suggestions.
[ERROR] src\main\java\ml\dmlc\xgboost4j\java\XGBoostJNI.java:[83,34] (naming) MethodName: Method name 'XGBoosterLoadMode
lFromBuffer' must match pattern '^[a-z][a-z0-9][a-zA-Z0-9_]*$'.
[ERROR] src\main\java\ml\dmlc\xgboost4j\java\XGBoostJNI.java:[85,16] (modifier) ModifierOrder: 'static' modifier out of
order with the JLS suggestions.
[ERROR] src\main\java\ml\dmlc\xgboost4j\java\XGBoostJNI.java:[85,34] (naming) MethodName: Method name 'XGBoosterGetModel
Raw' must match pattern '^[a-z][a-z0-9][a-zA-Z0-9_]*$'.
[ERROR] src\main\java\ml\dmlc\xgboost4j\java\XGBoostJNI.java:[87,16] (modifier) ModifierOrder: 'static' modifier out of
order with the JLS suggestions.
[ERROR] src\main\java\ml\dmlc\xgboost4j\java\XGBoostJNI.java:[87,34] (naming) MethodName: Method name 'XGBoosterDumpMode
l' must match pattern '^[a-z][a-z0-9][a-zA-Z0-9_]*$'.
[ERROR] src\main\java\ml\dmlc\xgboost4j\java\XGBoostJNI.java:[90,16] (modifier) ModifierOrder: 'static' modifier out of
order with the JLS suggestions.
[ERROR] src\main\java\ml\dmlc\xgboost4j\java\XGBoostJNI.java:[90,34] (naming) MethodName: Method name 'XGBoosterGetAttr'
 must match pattern '^[a-z][a-z0-9][a-zA-Z0-9_]*$'.
[ERROR] src\main\java\ml\dmlc\xgboost4j\java\XGBoostJNI.java:[91,16] (modifier) ModifierOrder: 'static' modifier out of
order with the JLS suggestions.
[ERROR] src\main\java\ml\dmlc\xgboost4j\java\XGBoostJNI.java:[91,34] (naming) MethodName: Method name 'XGBoosterSetAttr'
 must match pattern '^[a-z][a-z0-9][a-zA-Z0-9_]*$'.
[ERROR] src\main\java\ml\dmlc\xgboost4j\java\XGBoostJNI.java:[92,16] (modifier) ModifierOrder: 'static' modifier out of
order with the JLS suggestions.
[ERROR] src\main\java\ml\dmlc\xgboost4j\java\XGBoostJNI.java:[92,34] (naming) MethodName: Method name 'XGBoosterLoadRabi
tCheckpoint' must match pattern '^[a-z][a-z0-9][a-zA-Z0-9_]*$'.
[ERROR] src\main\java\ml\dmlc\xgboost4j\java\XGBoostJNI.java:[93,16] (modifier) ModifierOrder: 'static' modifier out of
order with the JLS suggestions.
[ERROR] src\main\java\ml\dmlc\xgboost4j\java\XGBoostJNI.java:[93,34] (naming) MethodName: Method name 'XGBoosterSaveRabi
tCheckpoint' must match pattern '^[a-z][a-z0-9][a-zA-Z0-9_]*$'.
[ERROR] src\main\java\ml\dmlc\xgboost4j\java\XGBoostJNI.java:[96,16] (modifier) ModifierOrder: 'static' modifier out of
order with the JLS suggestions.
[ERROR] src\main\java\ml\dmlc\xgboost4j\java\XGBoostJNI.java:[96,34] (naming) MethodName: Method name 'RabitInit' must m
atch pattern '^[a-z][a-z0-9][a-zA-Z0-9_]*$'.
[ERROR] src\main\java\ml\dmlc\xgboost4j\java\XGBoostJNI.java:[97,16] (modifier) ModifierOrder: 'static' modifier out of
order with the JLS suggestions.
[ERROR] src\main\java\ml\dmlc\xgboost4j\java\XGBoostJNI.java:[97,34] (naming) MethodName: Method name 'RabitFinalize' mu
st match pattern '^[a-z][a-z0-9][a-zA-Z0-9_]*$'.
[ERROR] src\main\java\ml\dmlc\xgboost4j\java\XGBoostJNI.java:[98,16] (modifier) ModifierOrder: 'static' modifier out of
order with the JLS suggestions.
[ERROR] src\main\java\ml\dmlc\xgboost4j\java\XGBoostJNI.java:[98,34] (naming) MethodName: Method name 'RabitTrackerPrint
' must match pattern '^[a-z][a-z0-9][a-zA-Z0-9_]*$'.
[ERROR] src\main\java\ml\dmlc\xgboost4j\java\XGBoostJNI.java:[99,16] (modifier) ModifierOrder: 'static' modifier out of
order with the JLS suggestions.
[ERROR] src\main\java\ml\dmlc\xgboost4j\java\XGBoostJNI.java:[99,34] (naming) MethodName: Method name 'RabitGetRank' mus
t match pattern '^[a-z][a-z0-9][a-zA-Z0-9_]*$'.
[ERROR] src\main\java\ml\dmlc\xgboost4j\java\XGBoostJNI.java:[100,16] (modifier) ModifierOrder: 'static' modifier out of
 order with the JLS suggestions.
[ERROR] src\main\java\ml\dmlc\xgboost4j\java\XGBoostJNI.java:[100,34] (naming) MethodName: Method name 'RabitGetWorldSiz
e' must match pattern '^[a-z][a-z0-9][a-zA-Z0-9_]*$'.
[ERROR] src\main\java\ml\dmlc\xgboost4j\java\XGBoostJNI.java:[101,16] (modifier) ModifierOrder: 'static' modifier out of
 order with the JLS suggestions.
[ERROR] src\main\java\ml\dmlc\xgboost4j\java\XGBoostJNI.java:[101,34] (naming) MethodName: Method name 'RabitVersionNumb
er' must match pattern '^[a-z][a-z0-9][a-zA-Z0-9_]*$'.
[ERROR] src\main\java\ml\dmlc\xgboost4j\java\XGBoostJNI.java:[105,9] (modifier) ModifierOrder: 'static' modifier out of
order with the JLS suggestions.
[ERROR] src\main\java\ml\dmlc\xgboost4j\java\XGBoostJNI.java:[105,27] (naming) MethodName: Method name 'RabitAllreduce'
must match pattern '^[a-z][a-z0-9][a-zA-Z0-9_]*$'.
[ERROR] src\main\java\ml\dmlc\xgboost4j\java\XGBoostJNI.java:[107] (regexp) RegexpSingleline: No trailing whitespace all
owed.
[INFO] ------------------------------------------------------------------------
[INFO] Reactor Summary:
[INFO]
[INFO] xgboost-jvm ........................................ SUCCESS [  6.480 s]
[INFO] xgboost4j .......................................... FAILURE [  4.468 s]
[INFO] xgboost4j-spark .................................... SKIPPED
[INFO] xgboost4j-flink .................................... SKIPPED
[INFO] xgboost4j-example .................................. SKIPPED
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 11.105 s
[INFO] Finished at: 2017-02-07T12:54:05+01:00
[INFO] Final Memory: 19M/220M
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal org.apache.maven.plugins:maven-checkstyle-plugin:2.17:check (checkstyle) on project xgboo
st4j: You have 82 Checkstyle violations. -> [Help 1]
org.apache.maven.lifecycle.LifecycleExecutionException: Failed to execute goal org.apache.maven.plugins:maven-checkstyle
-plugin:2.17:check (checkstyle) on project xgboost4j: You have 82 Checkstyle violations.
        at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:212)
        at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:153)
        at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:145)
        at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject(LifecycleModuleBuilder.java:116)
        at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject(LifecycleModuleBuilder.java:80)
        at org.apache.maven.lifecycle.internal.builder.singlethreaded.SingleThreadedBuilder.build(SingleThreadedBuilder.
java:51)
        at org.apache.maven.lifecycle.internal.LifecycleStarter.execute(LifecycleStarter.java:128)
        at org.apache.maven.DefaultMaven.doExecute(DefaultMaven.java:307)
        at org.apache.maven.DefaultMaven.doExecute(DefaultMaven.java:193)
        at org.apache.maven.DefaultMaven.execute(DefaultMaven.java:106)
        at org.apache.maven.cli.MavenCli.execute(MavenCli.java:863)
        at org.apache.maven.cli.MavenCli.doMain(MavenCli.java:288)
        at org.apache.maven.cli.MavenCli.main(MavenCli.java:199)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:498)
        at org.codehaus.plexus.classworlds.launcher.Launcher.launchEnhanced(Launcher.java:289)
        at org.codehaus.plexus.classworlds.launcher.Launcher.launch(Launcher.java:229)
        at org.codehaus.plexus.classworlds.launcher.Launcher.mainWithExitCode(Launcher.java:415)
        at org.codehaus.plexus.classworlds.launcher.Launcher.main(Launcher.java:356)
Caused by: org.apache.maven.plugin.MojoFailureException: You have 82 Checkstyle violations.
        at org.apache.maven.plugin.checkstyle.CheckstyleViolationCheckMojo.execute(CheckstyleViolationCheckMojo.java:588
)
        at org.apache.maven.plugin.DefaultBuildPluginManager.executeMojo(DefaultBuildPluginManager.java:134)
        at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:207)
        ... 20 more
[ERROR]
[ERROR]
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/MojoFailureException
[ERROR]
[ERROR] After correcting the problems, you can resume the build with the command
[ERROR]   mvn <goals> -rf :xgboost4j
PS C:\Users\Jarek Brzozowski\xgboost\jvm-packages>
```

**Comment by aprelkin** [comment]
How did you compile the JVM target with Visual Studio 2015?
With which command?
