### ISSUE TITLE
[jvm-packages] flaky test of training with Scala-implemented Rabit tracker

### ISSUE THREAD

**Issue by CodingCat** [dmlc/xgboost#2069]
In the last two weeks, I met several failures when running unit tests with my laptop (4 cores)

@xydrolase 

```
[INFO] [02/26/2017 17:43:20.474] [RabitTracker-akka.actor.default-dispatcher-3] [akka://RabitTracker/user/Handler] Tracker listening @ 192.168.0.196:54157
[INFO] [02/26/2017 17:43:20.475] [RabitTracker-akka.actor.default-dispatcher-3] [akka://RabitTracker/user/Handler] Worker connection timeout is 1 minute.
[INFO] [02/26/2017 17:43:20.537] [RabitTracker-akka.actor.default-dispatcher-5] [akka://RabitTracker/user/Handler] Received start signal from 192.168.0.196 [rank: 0]
[INFO] [02/26/2017 17:43:20.538] [RabitTracker-akka.actor.default-dispatcher-7] [akka://RabitTracker/user/Handler] Received start signal from 192.168.0.196 [rank: 1]
[INFO] [02/26/2017 17:43:20.545] [RabitTracker-akka.actor.default-dispatcher-12] [akka://RabitTracker/user/Handler] Received start signal from 192.168.0.196 [rank: 2]
[INFO] [02/26/2017 17:43:20.549] [RabitTracker-akka.actor.default-dispatcher-5] [akka://RabitTracker/user/Handler] Worker 192.168.0.196 (rank: 0) has started.
[INFO] [02/26/2017 17:43:20.550] [RabitTracker-akka.actor.default-dispatcher-5] [akka://RabitTracker/user/Handler] Worker 192.168.0.196 (rank: 1) has started.
[INFO] [02/26/2017 17:43:20.552] [RabitTracker-akka.actor.default-dispatcher-10] [akka://RabitTracker/user/Handler] Worker 192.168.0.196 (rank: 2) has started.
[INFO] [02/26/2017 17:43:20.562] [RabitTracker-akka.actor.default-dispatcher-5] [akka://RabitTracker/user/Handler] Received start signal from 192.168.0.196 [rank: 3]
[17:43:20] SparsePage::Writer Finished writing to XGBoostSuite-7-dtrain_cache-1.row.page
[17:43:20] SparsePageSource: Finished writing to XGBoostSuite-7-dtrain_cache-1
[INFO] [02/26/2017 17:43:20.570] [RabitTracker-akka.actor.default-dispatcher-4] [akka://RabitTracker/user/Handler] Worker 192.168.0.196 (rank: 3) has started.
[INFO] [02/26/2017 17:43:20.570] [RabitTracker-akka.actor.default-dispatcher-4] [akka://RabitTracker/user/Handler] All workers have started.
[17:43:20] SparsePage::Writer Finished writing to XGBoostSuite-7-dtrain_cache-2.row.page
[17:43:20] SparsePageSource: Finished writing to XGBoostSuite-7-dtrain_cache-2
[17:43:20] SparsePage::Writer Finished writing to XGBoostSuite-7-dtrain_cache-0.row.page
[17:43:20] SparsePageSource: Finished writing to XGBoostSuite-7-dtrain_cache-0
[17:43:20] SparsePage::Writer Finished writing to XGBoostSuite-7-dtrain_cache-3.row.page
[17:43:20] SparsePageSource: Finished writing to XGBoostSuite-7-dtrain_cache-3
[[1177::4433::2200]]  SSppaarrsseePPaaggee::::WWrriitteerr  FFiinniisshheedd  wwrriittiinngg  ttoo  XXGGBBoooossttSSuuiittee--77--ddttrraaiinn__ccaacchhee--32..ccooll..ppaaggee

[17:43:20] SparsePage::Writer Finished writing to XGBoostSuite-7-dtrain_cache-0.col.page
[17:43:20] SparsePage::Writer Finished writing to XGBoostSuite-7-dtrain_cache-1.col.page
[INFO] [02/26/2017 17:43:20.703] [RabitTracker-akka.actor.default-dispatcher-7] [akka://RabitTracker/user/Handler] [0]	train-error:0.000614
[INFO] [02/26/2017 17:43:20.745] [RabitTracker-akka.actor.default-dispatcher-8] [akka://RabitTracker/user/Handler] [1]	train-error:0.000000
[INFO] [02/26/2017 17:43:20.786] [RabitTracker-akka.actor.default-dispatcher-2] [akka://RabitTracker/user/Handler] [2]	train-error:0.000000
[ERROR] [02/26/2017 17:43:20.855] [RabitTracker-akka.actor.default-dispatcher-12] [akka://RabitTracker/user/Handler/ConnectionHandler-4499fd0b-51f1-4dc1-9628-ba6ef2a46ce0] null
java.nio.BufferUnderflowException
	at java.nio.Buffer.nextGetIndex(Buffer.java:506)
	at java.nio.HeapByteBuffer.getInt(HeapByteBuffer.java:361)
	at ml.dmlc.xgboost4j.scala.rabit.util.RabitTrackerHelpers$ByteBufferHelpers.getString(RabitTrackerHelpers.scala:33)
	at ml.dmlc.xgboost4j.scala.rabit.handler.RabitWorkerHandler.decodeCommand(RabitWorkerHandler.scala:105)
	at ml.dmlc.xgboost4j.scala.rabit.handler.RabitWorkerHandler$$anonfun$3$$anonfun$11.apply(RabitWorkerHandler.scala:129)
	at ml.dmlc.xgboost4j.scala.rabit.handler.RabitWorkerHandler$$anonfun$3$$anonfun$11.apply(RabitWorkerHandler.scala:129)
	at scala.util.Try$.apply(Try.scala:192)
	at ml.dmlc.xgboost4j.scala.rabit.handler.RabitWorkerHandler$$anonfun$3.applyOrElse(RabitWorkerHandler.scala:129)
	at ml.dmlc.xgboost4j.scala.rabit.handler.RabitWorkerHandler$$anonfun$3.applyOrElse(RabitWorkerHandler.scala:125)
	at scala.runtime.AbstractPartialFunction.apply(AbstractPartialFunction.scala:36)
	at akka.actor.FSM$class.processEvent(FSM.scala:604)
	at ml.dmlc.xgboost4j.scala.rabit.handler.RabitWorkerHandler.processEvent(RabitWorkerHandler.scala:39)
	at akka.actor.FSM$class.akka$actor$FSM$$processMsg(FSM.scala:598)
	at akka.actor.FSM$$anonfun$receive$1.applyOrElse(FSM.scala:592)
	at akka.actor.Actor$class.aroundReceive(Actor.scala:467)
	at ml.dmlc.xgboost4j.scala.rabit.handler.RabitWorkerHandler.aroundReceive(RabitWorkerHandler.scala:39)
	at akka.actor.ActorCell.receiveMessage(ActorCell.scala:516)
	at akka.actor.ActorCell.invoke(ActorCell.scala:487)
	at akka.dispatch.Mailbox.processMailbox(Mailbox.scala:238)
	at akka.dispatch.Mailbox.run(Mailbox.scala:220)
	at akka.dispatch.ForkJoinExecutorConfigurator$AkkaForkJoinTask.exec(AbstractDispatcher.scala:397)
	at scala.concurrent.forkjoin.ForkJoinTask.doExec(ForkJoinTask.java:260)
	at scala.concurrent.forkjoin.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1339)
	at scala.concurrent.forkjoin.ForkJoinPool.runWorker(ForkJoinPool.java:1979)
	at scala.concurrent.forkjoin.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:107)

[ERROR] [02/26/2017 17:43:20.860] [RabitTracker-akka.actor.default-dispatcher-2] [LocalActorRefProvider(akka://RabitTracker)] guardian failed, shutting down system
java.lang.AssertionError: assertion failed
	at scala.Predef$.assert(Predef.scala:156)
	at ml.dmlc.xgboost4j.scala.rabit.handler.RabitWorkerHandler$$anonfun$2.applyOrElse(RabitWorkerHandler.scala:116)
	at ml.dmlc.xgboost4j.scala.rabit.handler.RabitWorkerHandler$$anonfun$2.applyOrElse(RabitWorkerHandler.scala:114)
	at scala.runtime.AbstractPartialFunction.apply(AbstractPartialFunction.scala:36)
	at akka.actor.FSM$class.processEvent(FSM.scala:604)
	at ml.dmlc.xgboost4j.scala.rabit.handler.RabitWorkerHandler.processEvent(RabitWorkerHandler.scala:39)
	at akka.actor.FSM$class.akka$actor$FSM$$processMsg(FSM.scala:598)
	at akka.actor.FSM$$anonfun$receive$1.applyOrElse(FSM.scala:592)
	at akka.actor.Actor$class.aroundReceive(Actor.scala:467)
	at ml.dmlc.xgboost4j.scala.rabit.handler.RabitWorkerHandler.aroundReceive(RabitWorkerHandler.scala:39)
	at akka.actor.ActorCell.receiveMessage(ActorCell.scala:516)
	at akka.actor.ActorCell.invoke(ActorCell.scala:487)
	at akka.dispatch.Mailbox.processMailbox(Mailbox.scala:238)
	at akka.dispatch.Mailbox.run(Mailbox.scala:220)
	at akka.dispatch.ForkJoinExecutorConfigurator$AkkaForkJoinTask.exec(AbstractDispatcher.scala:397)
	at scala.concurrent.forkjoin.ForkJoinTask.doExec(ForkJoinTask.java:260)
	at scala.concurrent.forkjoin.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1339)
	at scala.concurrent.forkjoin.ForkJoinPool.runWorker(ForkJoinPool.java:1979)
	at scala.concurrent.forkjoin.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:107)

[ERROR] [02/26/2017 17:43:20.860] [RabitTracker-akka.actor.default-dispatcher-2] [akka://RabitTracker/user] assertion failed
java.lang.AssertionError: assertion failed
	at scala.Predef$.assert(Predef.scala:156)
	at ml.dmlc.xgboost4j.scala.rabit.handler.RabitWorkerHandler$$anonfun$2.applyOrElse(RabitWorkerHandler.scala:116)
	at ml.dmlc.xgboost4j.scala.rabit.handler.RabitWorkerHandler$$anonfun$2.applyOrElse(RabitWorkerHandler.scala:114)
	at scala.runtime.AbstractPartialFunction.apply(AbstractPartialFunction.scala:36)
	at akka.actor.FSM$class.processEvent(FSM.scala:604)
	at ml.dmlc.xgboost4j.scala.rabit.handler.RabitWorkerHandler.processEvent(RabitWorkerHandler.scala:39)
	at akka.actor.FSM$class.akka$actor$FSM$$processMsg(FSM.scala:598)
	at akka.actor.FSM$$anonfun$receive$1.applyOrElse(FSM.scala:592)
	at akka.actor.Actor$class.aroundReceive(Actor.scala:467)
	at ml.dmlc.xgboost4j.scala.rabit.handler.RabitWorkerHandler.aroundReceive(RabitWorkerHandler.scala:39)
	at akka.actor.ActorCell.receiveMessage(ActorCell.scala:516)
	at akka.actor.ActorCell.invoke(ActorCell.scala:487)
	at akka.dispatch.Mailbox.processMailbox(Mailbox.scala:238)
	at akka.dispatch.Mailbox.run(Mailbox.scala:220)
	at akka.dispatch.ForkJoinExecutorConfigurator$AkkaForkJoinTask.exec(AbstractDispatcher.scala:397)
	at scala.concurrent.forkjoin.ForkJoinTask.doExec(ForkJoinTask.java:260)
	at scala.concurrent.forkjoin.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1339)
	at scala.concurrent.forkjoin.ForkJoinPool.runWorker(ForkJoinPool.java:1979)
	at scala.concurrent.forkjoin.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:107)

retry connect to ip(retry time 1): [192.168.0.196]

[Stage 7:>                                                          (0 + 4) / 4]retry connect to ip(retry time 2): [192.168.0.196]
retry connect to ip(retry time 3): [192.168.0.196]
retry connect to ip(retry time 4): [192.168.0.196]
connect to (failed): [192.168.0.196]
Socket Connect Error:Invalid argument
```

**Comment by xydrolase** [comment]
I'll look into it. Thanks.

**Comment by xydrolase** [comment]
I'll try to replicate this on my Mac laptop, and on a Linux instance.

**Comment by xydrolase** [comment]
@CodingCat Does the test fail sporadically?

**Comment by CodingCat** [comment]
yes

**Comment by xydrolase** [comment]
Somehow I stupidly put `BufferOverflowException` in the place of `BufferUnderflowException`, and my unit test supposedly to test the exception handling was not properly constructed. 

Check out the PR for the bugfix.

**Comment by CodingCat** [comment]
resolved
