### ISSUE TITLE
pip install for xgboost 0.6a2 fails on missing <omp.h> file on MacOS Sierra

### ISSUE THREAD

**Issue by jimthompson5802** [dmlc/xgboost#2149]
When I attempt to install xgboost with pip, it fails.  One error message is the inability to find <omp.h> include file.  

I can find the omp.h file in the homebrew Cellar directory, i.e.,
/usr/local/Cellar/libiomp/20150701/include/libiomp
Jim-MacBook-Pro:libiomp jim$ ls
omp.h		omp_lib.f	omp_lib.f90	omp_lib.h

I tried adding the `--global-option='-I/usr/local/Cellar/libiomp/20150701/include/libiomp'` to the pip command but that did not seem to help, e.g.,
`pip install --global-option='-I/usr/local/Cellar/libiomp/20150701/include/libiomp' xgboost`

Any guidance will be appreciated.

Below are the install messages and information on my configuration.

#### install command
pip install xgboost

######resulting output from pip command
(dnn-th) Jim-MacBook-Pro:~ jim$ pip install xgboost
Collecting xgboost
  Using cached xgboost-0.6a2.tar.gz
    Complete output from command python setup.py egg_info:
    rm -f -rf build build_plugin lib bin *~ */*~ */*/*~ */*/*/*~ */*.o */*/*.o */*/*/*.o xgboost
    clang-omp++ -std=c++0x -Wall -O3 -msse2  -Wno-unknown-pragmas -funroll-loops -Iinclude   -Idmlc-core/include -Irabit/include -fPIC -fopenmp -MM -MT build/learner.o src/learner.cc >build/learner.d
    clang-omp++ -std=c++0x -Wall -O3 -msse2  -Wno-unknown-pragmas -funroll-loops -Iinclude   -Idmlc-core/include -Irabit/include -fPIC -fopenmp -MM -MT build/logging.o src/logging.cc >build/logging.d
    clang-omp++ -std=c++0x -Wall -O3 -msse2  -Wno-unknown-pragmas -funroll-loops -Iinclude   -Idmlc-core/include -Irabit/include -fPIC -fopenmp -MM -MT build/c_api/c_api.o src/c_api/c_api.cc >build/c_api/c_api.d
    clang-omp++ -std=c++0x -Wall -O3 -msse2  -Wno-unknown-pragmas -funroll-loops -Iinclude   -Idmlc-core/include -Irabit/include -fPIC -fopenmp -MM -MT build/c_api/c_api_error.o src/c_api/c_api_error.cc >build/c_api/c_api_error.d
    In file included from src/learner.cc:7:
    In file included from include/xgboost/logging.h:13:
    In file included from include/xgboost/./base.h:10:
    dmlc-core/include/dmlc/omp.h:9:10: error: 'omp.h' file not found with <angled> include; use "quotes" instead
    #include <omp.h>
             ^~~~~~~
             "omp.h"
    In file included from src/logging.cc:7:
    In file included from include/xgboost/logging.h:13:
    In file included from include/xgboost/./base.h:10:
    dmlc-core/include/dmlc/omp.h:9:10: error: 'omp.h' file not found with <angled> include; use "quotes" instead
    #include <omp.h>
             ^~~~~~~
             "omp.h"
    1 error generated.
    make: *** [build/logging.o] Error 1
    make: *** Waiting for unfinished jobs....
    1 error generated.
    make: *** [build/learner.o] Error 1
    In file included from src/c_api/c_api.cc:3:
    In file included from include/xgboost/data.h:15:
    In file included from include/xgboost/./base.h:10:
    dmlc-core/include/dmlc/omp.h:9:10: error: 'omp.h' file not found with <angled> include; use "quotes" instead
    #include <omp.h>
             ^~~~~~~
             "omp.h"
    clang-omp++ -c -std=c++0x -Wall -O3 -msse2  -Wno-unknown-pragmas -funroll-loops -Iinclude   -Idmlc-core/include -Irabit/include -fPIC -fopenmp -c src/c_api/c_api_error.cc -o build/c_api/c_api_error.o
    1 error generated.
    make: *** [build/c_api/c_api.o] Error 1
    -----------------------------
    Building multi-thread xgboost failed
    Start to build single-thread xgboost
    rm -f -rf build build_plugin lib bin *~ */*~ */*/*~ */*/*/*~ */*.o */*/*.o */*/*/*.o xgboost
    clang-omp++ -std=c++0x -Wall -O3 -msse2  -Wno-unknown-pragmas -funroll-loops -Iinclude   -Idmlc-core/include -Irabit/include -fPIC -fopenmp -MM -MT build/learner.o src/learner.cc >build/learner.d
    clang-omp++ -std=c++0x -Wall -O3 -msse2  -Wno-unknown-pragmas -funroll-loops -Iinclude   -Idmlc-core/include -Irabit/include -fPIC -fopenmp -MM -MT build/logging.o src/logging.cc >build/logging.d
    clang-omp++ -std=c++0x -Wall -O3 -msse2  -Wno-unknown-pragmas -funroll-loops -Iinclude   -Idmlc-core/include -Irabit/include -fPIC -fopenmp -MM -MT build/c_api/c_api.o src/c_api/c_api.cc >build/c_api/c_api.d
    clang-omp++ -std=c++0x -Wall -O3 -msse2  -Wno-unknown-pragmas -funroll-loops -Iinclude   -Idmlc-core/include -Irabit/include -fPIC -fopenmp -MM -MT build/c_api/c_api_error.o src/c_api/c_api_error.cc >build/c_api/c_api_error.d
    In file included from src/learner.cc:7:
    In file included from include/xgboost/logging.h:13:
    In file included from include/xgboost/./base.h:10:
    dmlc-core/include/dmlc/omp.h:9:10: error: 'omp.h' file not found with <angled> include; use "quotes" instead
    #include <omp.h>
             ^~~~~~~
             "omp.h"
    In file included from src/logging.cc:7:
    In file included from include/xgboost/logging.h:13:
    In file included from include/xgboost/./base.h:10:
    dmlc-core/include/dmlc/omp.h:9:10: error: 'omp.h' file not found with <angled> include; use "quotes" instead
    #include <omp.h>
             ^~~~~~~
             "omp.h"
    1 error generated.
    1 error generated.
    make: *** [build/logging.o] Error 1
    make: *** Waiting for unfinished jobs....
    make: *** [build/learner.o] Error 1
    clang-omp++ -c -std=c++0x -Wall -O3 -msse2  -Wno-unknown-pragmas -funroll-loops -Iinclude   -Idmlc-core/include -Irabit/include -fPIC -fopenmp -c src/c_api/c_api_error.cc -o build/c_api/c_api_error.o
    In file included from src/c_api/c_api.cc:3:
    In file included from include/xgboost/data.h:15:
    In file included from include/xgboost/./base.h:10:
    dmlc-core/include/dmlc/omp.h:9:10: error: 'omp.h' file not found with <angled> include; use "quotes" instead
    #include <omp.h>
             ^~~~~~~
             "omp.h"
    1 error generated.
    make: *** [build/c_api/c_api.o] Error 1
    Successfully build single-thread xgboost
    If you want multi-threaded version
    See additional instructions in doc/build.md
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/private/var/folders/8_/h2tjc94d2y5fwx8dhbcrnbfc0000gn/T/pip-build-mj2bb4e8/xgboost/setup.py", line 29, in <module>
        LIB_PATH = libpath['find_lib_path']()
      File "/private/var/folders/8_/h2tjc94d2y5fwx8dhbcrnbfc0000gn/T/pip-build-mj2bb4e8/xgboost/xgboost/libpath.py", line 45, in find_lib_path
        'List of candidates:\n' + ('\n'.join(dll_path)))
    XGBoostLibraryNotFound: Cannot find XGBoost Libarary in the candicate path, did you install compilers and run build.sh in root path?
    List of candidates:
    /private/var/folders/8_/h2tjc94d2y5fwx8dhbcrnbfc0000gn/T/pip-build-mj2bb4e8/xgboost/xgboost/libxgboost.so
    /private/var/folders/8_/h2tjc94d2y5fwx8dhbcrnbfc0000gn/T/pip-build-mj2bb4e8/xgboost/xgboost/../../lib/libxgboost.so
    /private/var/folders/8_/h2tjc94d2y5fwx8dhbcrnbfc0000gn/T/pip-build-mj2bb4e8/xgboost/xgboost/./lib/libxgboost.so
    
    ----------------------------------------
Command "python setup.py egg_info" failed with error code 1 in /private/var/folders/8_/h2tjc94d2y5fwx8dhbcrnbfc0000gn/T/pip-build-mj2bb4e8/xgboost/

###### MacOS Version
(dnn-th) Jim-MacBook-Pro:~ jim$ sw_vers
ProductName:	Mac OS X
ProductVersion:	10.12.3
BuildVersion:	16D32

###### Python version
(dnn-th) Jim-MacBook-Pro:~ jim$ python
Python 3.5.2 |Anaconda 4.3.0 (x86_64)| (default, Jul  2 2016, 17:52:12) 
[GCC 4.2.1 Compatible Apple LLVM 4.2 (clang-425.0.28)] on darwin
Type "help", "copyright", "credits" or "license" for more information.

##### pip version
pip 9.0.1 from /Users/jim/anaconda3/envs/dnn-th/lib/python3.5/site-packages (python 3.5)

###### Homebrew installed software
(dnn-th) Jim-MacBook-Pro:~ jim$ brew list --versions
arpack 3.4.0
bison 3.0.4
boost 1.58.0 1.59.0 1.62.0
cairo 1.14.6_1 1.14.8
clang-omp 2015-04-01
cmake 3.7.2
curl 7.52.1
czmq 3.0.2_3 4.0.1
fontconfig 2.12.1_2
freetype 2.7 2.7.1
gawk 4.1.4_1
gcc 5.3.0 6.2.0 6.3.0_1
gettext 0.19.8.1
ghostscript 9.20
git 2.11.0 2.7.2
glib 2.50.1 2.50.2
gmp 6.0.0a 6.1.0 6.1.1 6.1.2
gnu-sed 4.3
gobject-introspection 1.50.0
graphviz 2.38.0_1
isl 0.15 0.17.1 0.18
jpeg 8d
libffi 3.0.13 3.2.1
libiomp 20150227 20150701
libmpc 1.0.3
libpng 1.6.26 1.6.28
libsodium 1.0.11 1.0.8
libtiff 4.0.6_3 4.0.7 4.0.7_1
little-cms2 2.8
llvm 4.0.0
lzip 1.18
maven 3.3.9
mpfr 3.1.3 3.1.5
openjpeg 2.1.2
pandoc 1.14.0.4 1.15.0.6 1.15.1.1 1.19.1
pcre 8.39
pixman 0.34.0
pkg-config 0.29.1_2
poppler 0.48.0 0.49.0
readline 7.0.1
swig 3.0.10 3.0.10_1
texinfo 6.3
veclibfort 0.4.2_3
vowpal-wabbit 8.0 8.0_1 8.3.0
zeromq 4.1.3 4.1.4 4.2.0
zeromq40 4.0.5 4.0.8

**Comment by jimthompson5802** [comment]
After digging around a bit, found solution.  I had to set C_INCLUDE_PATH and CPLUS_INCLUDE_PATH to the location of the omp.h file, e.g,.

`export C_INCLUDE_PATH='/usr/local/Cellar/libiomp/20150701/include/libiomp'`
`export CPLUS_INCLUDE_PATH='/usr/local/Cellar/libiomp/20150701/include/libiomp'`

`pip install xgboost`

installation of xgboost completed successfully
