### ISSUE TITLE
Issue installing from pip or repo

### ISSUE THREAD

**Issue by aiguofer** [dmlc/xgboost#2206]
For bugs or installation issues, please provide the following information.
The more information you provide, the more easily we will be able to offer
help and advice.

## Environment info
Operating System:
Fedora 26

Compiler:
g++ (GCC) 7.0.1 20170309 (Red Hat 7.0.1-0.12)

Package used (python/R/jvm/C++):
python

`xgboost` version used:
6a2

If installing from source, please provide 

1. The commit hash (`git rev-parse HEAD`)
31e800f340db0577328332ac2f20fd3125df5e00

2. Logs will be helpful (If logs are large, please upload as attachment).
The relevant section:
```
    In file included from src/data/sparse_page_writer.cc:8:0:
    src/data/./sparse_batch_page.h:238:46: error: ‘function’ is not a member of ‘std’
                                             std::function<SparsePage::Format* ()> > {
                                                  ^~~~~~~~
    src/data/./sparse_batch_page.h:238:46: note: suggested alternative: ‘is_function’
                                             std::function<SparsePage::Format* ()> > {
                                                  ^~~~~~~~
                                                  is_function
    src/data/./sparse_batch_page.h:238:46: error: ‘function’ is not a member of ‘std’
    src/data/./sparse_batch_page.h:238:46: note: suggested alternative: ‘is_function’
                                             std::function<SparsePage::Format* ()> > {
                                                  ^~~~~~~~
                                                  is_function
    src/data/./sparse_batch_page.h:238:77: error: template argument 2 is invalid
                                             std::function<SparsePage::Format* ()> > {
                                                                                 ^
    src/data/./sparse_batch_page.h:238:79: error: expected ‘{’ before ‘>’ token
                                             std::function<SparsePage::Format* ()> > {
                                                                                   ^
    src/data/./sparse_batch_page.h:238:79: error: expected unqualified-id before ‘>’ token
    make: *** [Makefile:107: build/data/sparse_page_writer.o] Error 1
    make: *** Waiting for unfinished jobs....
    Successfully build single-thread xgboost
    If you want multi-threaded version
    See additional instructions in doc/build.md
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/tmp.YZ9YwvrLMv/pip-build-n7kkhn7h/xgboost/setup.py", line 29, in <module>
        LIB_PATH = libpath['find_lib_path']()
      File "/tmp/tmp.YZ9YwvrLMv/pip-build-n7kkhn7h/xgboost/xgboost/libpath.py", line 45, in find_lib_path
        'List of candidates:\n' + ('\n'.join(dll_path)))
    XGBoostLibraryNotFound: Cannot find XGBoost Libarary in the candicate path, did you install compilers and run build.sh in root path?
    List of candidates:
    /tmp/tmp.YZ9YwvrLMv/pip-build-n7kkhn7h/xgboost/xgboost/libxgboost.so
    /tmp/tmp.YZ9YwvrLMv/pip-build-n7kkhn7h/xgboost/xgboost/../../lib/libxgboost.so
    /tmp/tmp.YZ9YwvrLMv/pip-build-n7kkhn7h/xgboost/xgboost/./lib/libxgboost.so
```
If you are using python package, please provide

1. The python version and distribution
Python 2.7.13

2. The command to install `xgboost` if you are not installing from source
pip install -v xgboost

## Steps to reproduce

1. Run `pip install -v xgboost`
2. Watch it crash and burn
3.

## What have you tried?

1. `git clone --recursive https://github.com/dmlc/xgboost && cd xgboost && make`
2. Watch same error building
3.

**Comment by fingertap** [comment]
I have the same problem. The current 0.6x versions all crash. I am using 0.4a30 instead. There are many problems though. For example, it fails when you try `deepcopy`.

**Comment by bneijt** [comment]
I have been able to build using `g++-5 (GCC) 5.4.0` but I had to exchange that for the system default to complete the last link step `g++ (GCC) 7.1.1 20170630`.

My bash history says:
```
make clean
make CC=g++-5
make CC=g++
```
end that resulted in a build on my system. Not yet tested if it actually runs as a python library yet!
