### ISSUE TITLE
unable to build setup.sh & pip build doesn't import

### ISSUE THREAD

**Issue by dyln** [dmlc/xgboost#2287]
i have the same problem that several people mentioned here.

## Environment info
Operating System: MACOS 10.10.5
Compiler: gcc

Package used (python/R/jvm/C++):
`xgboost` version used: latest from git.

i have tried to update gcc using `brew install gcc --without-multilib`, it upgraded my old version 6.something to 7.01. didn't worked, i also tried to install gcc5 `brew install gcc5 --without-multilib` it also got installed.
but  `gcc --version` returned(after both installation):
caners-MacBook-Pro:make canereren$ gcc --version
```
Configured with: --prefix=/Applications/Xcode.app/Contents/Developer/usr --with-gxx-include-dir=/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.10.sdk/usr/include/c++/4.2.1
Apple LLVM version 6.1.0 (clang-602.0.53) (based on LLVM 3.6.0svn)
Target: x86_64-apple-darwin14.5.0
Thread model: posix
```
beside of it i can't update my xcode via app store. i thought maybe problem coused by outdated xcode. i will try if you suggest so.

here the outputs i get:
```
caners-MacBook-Pro:xgboost canereren$ cp make/minimum.mk ./config.mk; make -j4
g++ -std=c++11 -Wall -Wno-unknown-pragmas -Iinclude   -Idmlc-core/include -Irabit/include -O3 -funroll-loops -msse2 -fPIC -DDISABLE_OPENMP -MM -MT build/logging.o src/logging.cc >build/logging.d
g++ -std=c++11 -Wall -Wno-unknown-pragmas -Iinclude   -Idmlc-core/include -Irabit/include -O3 -funroll-loops -msse2 -fPIC -DDISABLE_OPENMP -MM -MT build/c_api/c_api_error.o src/c_api/c_api_error.cc >build/c_api/c_api_error.d
g++ -std=c++11 -Wall -Wno-unknown-pragmas -Iinclude   -Idmlc-core/include -Irabit/include -O3 -funroll-loops -msse2 -fPIC -DDISABLE_OPENMP -MM -MT build/c_api/c_api.o src/c_api/c_api.cc >build/c_api/c_api.d
g++ -std=c++11 -Wall -Wno-unknown-pragmas -Iinclude   -Idmlc-core/include -Irabit/include -O3 -funroll-loops -msse2 -fPIC -DDISABLE_OPENMP -MM -MT build/learner.o src/learner.cc >build/learner.d
g++ -c -std=c++11 -Wall -Wno-unknown-pragmas -Iinclude   -Idmlc-core/include -Irabit/include -O3 -funroll-loops -msse2 -fPIC -DDISABLE_OPENMP src/c_api/c_api_error.cc -o build/c_api/c_api_error.o
g++ -c -std=c++11 -Wall -Wno-unknown-pragmas -Iinclude   -Idmlc-core/include -Irabit/include -O3 -funroll-loops -msse2 -fPIC -DDISABLE_OPENMP src/logging.cc -o build/logging.o
g++ -c -std=c++11 -Wall -Wno-unknown-pragmas -Iinclude   -Idmlc-core/include -Irabit/include -O3 -funroll-loops -msse2 -fPIC -DDISABLE_OPENMP src/c_api/c_api.cc -o build/c_api/c_api.o
g++ -c -std=c++11 -Wall -Wno-unknown-pragmas -Iinclude   -Idmlc-core/include -Irabit/include -O3 -funroll-loops -msse2 -fPIC -DDISABLE_OPENMP src/learner.cc -o build/learner.o
In file included from src/c_api/c_api_error.cc:6:
dmlc-core/include/dmlc/thread_local.h:40:12: error: thread-local storage is not supported for the
      current target
    static thread_local T inst;
           ^
1 error generated.
make: *** [Makefile:119: build/c_api/c_api_error.o] Error 1
make: *** Waiting for unfinished jobs....
In file included from src/c_api/c_api.cc:7:
dmlc-core/include/dmlc/thread_local.h:40:12: error: thread-local storage is not supported for the
      current target
    static thread_local T inst;
           ^
1 error generated.
make: *** [Makefile:117: build/c_api/c_api.o] Error 1

```

```
caners-MacBook-Pro:xgboost canereren$ cd python-package/
caners-MacBook-Pro:python-package canereren$ sudo python setup.py install
Traceback (most recent call last):
  File "setup.py", line 19, in <module>
    LIB_PATH = [os.path.relpath(libfile, CURRENT_DIR) for libfile in libpath['find_lib_path']()]
  File "xgboost/libpath.py", line 46, in find_lib_path
    'List of candidates:\n' + ('\n'.join(dll_path)))
XGBoostLibraryNotFound: Cannot find XGBoost Library in the candidate path, did you install compilers and run build.sh in root path?
List of candidates:
/Users/canereren/xgboost/python-package/xgboost/libxgboost.so
/Users/canereren/xgboost/python-package/xgboost/../../lib/libxgboost.so
/Users/canereren/xgboost/python-package/xgboost/./lib/libxgboost.so
/Users/canereren/anaconda/xgboost/libxgboost.so
caners-MacBook-Pro:python-package canereren$ 
```
```
caners-MacBook-Pro:python-package canereren$ sudo -H pip install xgboost 
Collecting xgboost
  Using cached xgboost-0.6a2.tar.gz
Requirement already satisfied: numpy in /Users/canereren/anaconda/lib/python3.6/site-packages (from xgboost)
Requirement already satisfied: scipy in /Users/canereren/anaconda/lib/python3.6/site-packages (from xgboost)
Requirement already satisfied: scikit-learn in /Users/canereren/anaconda/lib/python3.6/site-packages (from xgboost)
Building wheels for collected packages: xgboost
  Running setup.py bdist_wheel for xgboost ... done
  Stored in directory: /var/root/Library/Caches/pip/wheels/5e/c1/d6/522af54e5cc001fad4dd855117f8bf61b11d56443e06672e26
Successfully built xgboost
Installing collected packages: xgboost
Successfully installed xgboost-0.6a2
```
pip seems to work (because of gcc5 i think, wasn't like this yesterday) but i can't import package from xgboost in python(anaconda 3.6)

```
caners-MacBook-Pro:Section 49 - XGBoost canereren$ python3 xgboost.py 
Traceback (most recent call last):
  File "xgboost.py", line 30, in <module>
    from xgboost import XGBClassifier
  File "/Users/canereren/Documents/workspace/Machine Learning A-Z /Part 10 - Model Selection & Boosting/Section 49 - XGBoost/xgboost.py", line 30, in <module>
    from xgboost import XGBClassifier
ImportError: cannot import name 'XGBClassifier'
```
my path:
```
caners-MacBook-Pro:Section 49 - XGBoost canereren$ $PATH
-bash: /Users/canereren/anaconda/bin:/Library/Frameworks/Python.framework/Versions/3.5/bin:/Users/canereren/Library/Haskell/bin:/usr/local/bin:/Users/canereren/.local/bin:/Users/canereren/.cabal/bin:/Applications/ghc-7.10.3.app/Contents/bin:/opt/local/bin:/opt/local/sbin:/Library/Frameworks/Python.framework/Versions/2.7/bin:/Library/Frameworks/Python.framework/Versions/2.7/bin:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin:/opt/X11/bin:/Library/TeX/texbin:/Applications/Wireshark.app/Contents/MacOS: No such file or directory
```

what can be the issue, i feel very lost on this?

thanks.

**Comment by dyln** [comment]
```
caners-MacBook-Pro:Section 49 - XGBoost canereren$ $PATH
-bash: /Users/canereren/anaconda/bin:/Library/Frameworks/Python.framework/Versions/3.5/bin:/Users/canereren/Library/Haskell/bin:/usr/local/bin:/Users/canereren/.local/bin:/Users/canereren/.cabal/bin:/Applications/ghc-7.10.3.app/Contents/bin:/opt/local/bin:/opt/local/sbin:/Library/Frameworks/Python.framework/Versions/2.7/bin:/Library/Frameworks/Python.framework/Versions/2.7/bin:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin:/opt/X11/bin:/Library/TeX/texbin:/Applications/Wireshark.app/Contents/MacOS: No such file or directory
```

**Comment by dyln** [comment]
decided to update MACOS to 10.12.4 (sierra), so i can update xcode to latest version 8.2.

successfully built and import python package.
