### ISSUE TITLE
Unknown tree updater errors during test & benchmarking

### ISSUE THREAD

**Issue by saj1919** [dmlc/xgboost#2413]
After installing xgboost, I tried to run `updater_gpu` test module and benchmarking as shown here - [XGBoost-Updater-GPU-PlugIn](https://github.com/dmlc/xgboost/blob/master/plugin/updater_gpu/README.md). But they are failing with follwing errors.

```
(gpu_env) root@tegra-ubuntu:~# python xgboost/plugin/updater_gpu/benchmark/benchmark.py --algorithm all
Generating dataset: 1000000 rows * 50 columns
Training with 'grow_gpu'
[11:11:45] dmlc-core/include/dmlc/./logging.h:300: [11:11:45] src/tree/tree_updater.cc:18: Unknown tree updater grow_gpu

Stack trace returned 9 entries:
[bt] (0) /root/gpu_env/local/lib/python2.7/site-packages/xgboost-0.6-py2.7.egg/xgboost/libxgboost.so(_ZN7xgboost11TreeUpdater6CreateERKNSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEEE+0x300) [0x7f86bf5f50]
[bt] (1) /root/gpu_env/local/lib/python2.7/site-packages/xgboost-0.6-py2.7.egg/xgboost/libxgboost.so(_ZN7xgboost3gbm6GBTree11InitUpdaterEv+0x1a4) [0x7f86c6550c]
[bt] (2) /root/gpu_env/local/lib/python2.7/site-packages/xgboost-0.6-py2.7.egg/xgboost/libxgboost.so(_ZN7xgboost3gbm6GBTree13BoostNewTreesERKSt6vectorINS_9bst_gpairESaIS3_EEPNS_7DMatrixEiPS2_ISt10unique_ptrINS_7RegTreeESt14default_deleteISB_EESaISE_EE+0x4c) [0x7f86c69a44]
[bt] (3) /root/gpu_env/local/lib/python2.7/site-packages/xgboost-0.6-py2.7.egg/xgboost/libxgboost.so(_ZN7xgboost3gbm6GBTree7DoBoostEPNS_7DMatrixEPSt6vectorINS_9bst_gpairESaIS5_EEPNS_11ObjFunctionE+0x6d4) [0x7f86c6ac74]
[bt] (4) /root/gpu_env/local/lib/python2.7/site-packages/xgboost-0.6-py2.7.egg/xgboost/libxgboost.so(_ZN7xgboost11LearnerImpl13UpdateOneIterEiPNS_7DMatrixE+0x1ac) [0x7f86b45434]
[bt] (5) /root/gpu_env/local/lib/python2.7/site-packages/xgboost-0.6-py2.7.egg/xgboost/libxgboost.so(XGBoosterUpdateOneIter+0x48) [0x7f86c79aa8]
[bt] (6) /usr/lib/aarch64-linux-gnu/libffi.so.6(ffi_call_SYSV+0x64) [0x7f8e58ee60]
[bt] (7) /usr/lib/aarch64-linux-gnu/libffi.so.6(ffi_call+0xc0) [0x7f8e58f7b8]
[bt] (8) /root/gpu_env/lib/python2.7/lib-dynload/_ctypes.aarch64-linux-gnu.so(_ctypes_callproc+0x670) [0x7f8e5aeb30]

Traceback (most recent call last):
  File "xgboost/plugin/updater_gpu/benchmark/benchmark.py", line 48, in <module>
    run_benchmark(args, 'grow_gpu', 'grow_colmaker')
  File "xgboost/plugin/updater_gpu/benchmark/benchmark.py", line 25, in run_benchmark
    xgb.train(param, dtrain, args.iterations)
  File "/root/gpu_env/local/lib/python2.7/site-packages/xgboost-0.6-py2.7.egg/xgboost/training.py", line 204, in train
    xgb_model=xgb_model, callbacks=callbacks)
  File "/root/gpu_env/local/lib/python2.7/site-packages/xgboost-0.6-py2.7.egg/xgboost/training.py", line 74, in _train_internal
    bst.update(dtrain, i, obj)
  File "/root/gpu_env/local/lib/python2.7/site-packages/xgboost-0.6-py2.7.egg/xgboost/core.py", line 827, in update
    dtrain.handle))
  File "/root/gpu_env/local/lib/python2.7/site-packages/xgboost-0.6-py2.7.egg/xgboost/core.py", line 130, in _check_call
    raise XGBoostError(_LIB.XGBGetLastError())
xgboost.core.XGBoostError: [11:11:45] src/tree/tree_updater.cc:18: Unknown tree updater grow_gpu

Stack trace returned 9 entries:
[bt] (0) /root/gpu_env/local/lib/python2.7/site-packages/xgboost-0.6-py2.7.egg/xgboost/libxgboost.so(_ZN7xgboost11TreeUpdater6CreateERKNSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEEE+0x300) [0x7f86bf5f50]
[bt] (1) /root/gpu_env/local/lib/python2.7/site-packages/xgboost-0.6-py2.7.egg/xgboost/libxgboost.so(_ZN7xgboost3gbm6GBTree11InitUpdaterEv+0x1a4) [0x7f86c6550c]
[bt] (2) /root/gpu_env/local/lib/python2.7/site-packages/xgboost-0.6-py2.7.egg/xgboost/libxgboost.so(_ZN7xgboost3gbm6GBTree13BoostNewTreesERKSt6vectorINS_9bst_gpairESaIS3_EEPNS_7DMatrixEiPS2_ISt10unique_ptrINS_7RegTreeESt14default_deleteISB_EESaISE_EE+0x4c) [0x7f86c69a44]
[bt] (3) /root/gpu_env/local/lib/python2.7/site-packages/xgboost-0.6-py2.7.egg/xgboost/libxgboost.so(_ZN7xgboost3gbm6GBTree7DoBoostEPNS_7DMatrixEPSt6vectorINS_9bst_gpairESaIS5_EEPNS_11ObjFunctionE+0x6d4) [0x7f86c6ac74]
[bt] (4) /root/gpu_env/local/lib/python2.7/site-packages/xgboost-0.6-py2.7.egg/xgboost/libxgboost.so(_ZN7xgboost11LearnerImpl13UpdateOneIterEiPNS_7DMatrixE+0x1ac) [0x7f86b45434]
[bt] (5) /root/gpu_env/local/lib/python2.7/site-packages/xgboost-0.6-py2.7.egg/xgboost/libxgboost.so(XGBoosterUpdateOneIter+0x48) [0x7f86c79aa8]
[bt] (6) /usr/lib/aarch64-linux-gnu/libffi.so.6(ffi_call_SYSV+0x64) [0x7f8e58ee60]
[bt] (7) /usr/lib/aarch64-linux-gnu/libffi.so.6(ffi_call+0xc0) [0x7f8e58f7b8]
[bt] (8) /root/gpu_env/lib/python2.7/lib-dynload/_ctypes.aarch64-linux-gnu.so(_ctypes_callproc+0x670) [0x7f8e5aeb30]

(gpu_env) root@tegra-ubuntu:~# 

```

Similarly, test cases also fail ->

```
(gpu_env) root@tegra-ubuntu:~/xgboost/plugin/updater_gpu# python -m nose test/python/
[11:15:33] 6513x127 matrix with 143286 entries loaded from ../../demo/data/agaricus.txt.train
[11:15:33] 1611x127 matrix with 35442 entries loaded from ../../demo/data/agaricus.txt.test
[11:15:33] dmlc-core/include/dmlc/./logging.h:300: [11:15:33] src/tree/tree_updater.cc:18: Unknown tree updater grow_gpu

Stack trace returned 9 entries:
[bt] (0) /root/gpu_env/local/lib/python2.7/site-packages/xgboost-0.6-py2.7.egg/xgboost/libxgboost.so(_ZN7xgboost11TreeUpdater6CreateERKNSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEEE+0x300) [0x7f75eb0f50]
[bt] (1) /root/gpu_env/local/lib/python2.7/site-packages/xgboost-0.6-py2.7.egg/xgboost/libxgboost.so(_ZN7xgboost3gbm6GBTree11InitUpdaterEv+0x1a4) [0x7f75f2050c]
[bt] (2) /root/gpu_env/local/lib/python2.7/site-packages/xgboost-0.6-py2.7.egg/xgboost/libxgboost.so(_ZN7xgboost3gbm6GBTree13BoostNewTreesERKSt6vectorINS_9bst_gpairESaIS3_EEPNS_7DMatrixEiPS2_ISt10unique_ptrINS_7RegTreeESt14default_deleteISB_EESaISE_EE+0x4c) [0x7f75f24a44]
[bt] (3) /root/gpu_env/local/lib/python2.7/site-packages/xgboost-0.6-py2.7.egg/xgboost/libxgboost.so(_ZN7xgboost3gbm6GBTree7DoBoostEPNS_7DMatrixEPSt6vectorINS_9bst_gpairESaIS5_EEPNS_11ObjFunctionE+0x6d4) [0x7f75f25c74]
[bt] (4) /root/gpu_env/local/lib/python2.7/site-packages/xgboost-0.6-py2.7.egg/xgboost/libxgboost.so(_ZN7xgboost11LearnerImpl13UpdateOneIterEiPNS_7DMatrixE+0x1ac) [0x7f75e00434]
[bt] (5) /root/gpu_env/local/lib/python2.7/site-packages/xgboost-0.6-py2.7.egg/xgboost/libxgboost.so(XGBoosterUpdateOneIter+0x48) [0x7f75f34aa8]
[bt] (6) /usr/lib/aarch64-linux-gnu/libffi.so.6(ffi_call_SYSV+0x64) [0x7f7d3e5e60]
[bt] (7) /usr/lib/aarch64-linux-gnu/libffi.so.6(ffi_call+0xc0) [0x7f7d3e67b8]
[bt] (8) /root/gpu_env/lib/python2.7/lib-dynload/_ctypes.aarch64-linux-gnu.so(_ctypes_callproc+0x670) [0x7f7d426b30]

E[11:15:33] dmlc-core/include/dmlc/./logging.h:300: [11:15:33] src/tree/tree_updater.cc:18: Unknown tree updater grow_gpu_hist

Stack trace returned 9 entries:
[bt] (0) /root/gpu_env/local/lib/python2.7/site-packages/xgboost-0.6-py2.7.egg/xgboost/libxgboost.so(_ZN7xgboost11TreeUpdater6CreateERKNSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEEE+0x300) [0x7f75eb0f50]
[bt] (1) /root/gpu_env/local/lib/python2.7/site-packages/xgboost-0.6-py2.7.egg/xgboost/libxgboost.so(_ZN7xgboost3gbm6GBTree11InitUpdaterEv+0x1a4) [0x7f75f2050c]
[bt] (2) /root/gpu_env/local/lib/python2.7/site-packages/xgboost-0.6-py2.7.egg/xgboost/libxgboost.so(_ZN7xgboost3gbm6GBTree13BoostNewTreesERKSt6vectorINS_9bst_gpairESaIS3_EEPNS_7DMatrixEiPS2_ISt10unique_ptrINS_7RegTreeESt14default_deleteISB_EESaISE_EE+0x4c) [0x7f75f24a44]
[bt] (3) /root/gpu_env/local/lib/python2.7/site-packages/xgboost-0.6-py2.7.egg/xgboost/libxgboost.so(_ZN7xgboost3gbm6GBTree7DoBoostEPNS_7DMatrixEPSt6vectorINS_9bst_gpairESaIS5_EEPNS_11ObjFunctionE+0x6d4) [0x7f75f25c74]
[bt] (4) /root/gpu_env/local/lib/python2.7/site-packages/xgboost-0.6-py2.7.egg/xgboost/libxgboost.so(_ZN7xgboost11LearnerImpl13UpdateOneIterEiPNS_7DMatrixE+0x1ac) [0x7f75e00434]
[bt] (5) /root/gpu_env/local/lib/python2.7/site-packages/xgboost-0.6-py2.7.egg/xgboost/libxgboost.so(XGBoosterUpdateOneIter+0x48) [0x7f75f34aa8]
[bt] (6) /usr/lib/aarch64-linux-gnu/libffi.so.6(ffi_call_SYSV+0x64) [0x7f7d3e5e60]
[bt] (7) /usr/lib/aarch64-linux-gnu/libffi.so.6(ffi_call+0xc0) [0x7f7d3e67b8]
[bt] (8) /root/gpu_env/lib/python2.7/lib-dynload/_ctypes.aarch64-linux-gnu.so(_ctypes_callproc+0x670) [0x7f7d426b30]

E
======================================================================
ERROR: test_grow_gpu (test.TestGPU)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/root/xgboost/plugin/updater_gpu/test/python/test.py", line 50, in test_grow_gpu
    evals_result=ag_res2)
  File "/root/gpu_env/local/lib/python2.7/site-packages/xgboost-0.6-py2.7.egg/xgboost/training.py", line 204, in train
    xgb_model=xgb_model, callbacks=callbacks)
  File "/root/gpu_env/local/lib/python2.7/site-packages/xgboost-0.6-py2.7.egg/xgboost/training.py", line 74, in _train_internal
    bst.update(dtrain, i, obj)
  File "/root/gpu_env/local/lib/python2.7/site-packages/xgboost-0.6-py2.7.egg/xgboost/core.py", line 827, in update
    dtrain.handle))
  File "/root/gpu_env/local/lib/python2.7/site-packages/xgboost-0.6-py2.7.egg/xgboost/core.py", line 130, in _check_call
    raise XGBoostError(_LIB.XGBGetLastError())
XGBoostError: [11:15:33] src/tree/tree_updater.cc:18: Unknown tree updater grow_gpu

Stack trace returned 9 entries:
[bt] (0) /root/gpu_env/local/lib/python2.7/site-packages/xgboost-0.6-py2.7.egg/xgboost/libxgboost.so(_ZN7xgboost11TreeUpdater6CreateERKNSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEEE+0x300) [0x7f75eb0f50]
[bt] (1) /root/gpu_env/local/lib/python2.7/site-packages/xgboost-0.6-py2.7.egg/xgboost/libxgboost.so(_ZN7xgboost3gbm6GBTree11InitUpdaterEv+0x1a4) [0x7f75f2050c]
[bt] (2) /root/gpu_env/local/lib/python2.7/site-packages/xgboost-0.6-py2.7.egg/xgboost/libxgboost.so(_ZN7xgboost3gbm6GBTree13BoostNewTreesERKSt6vectorINS_9bst_gpairESaIS3_EEPNS_7DMatrixEiPS2_ISt10unique_ptrINS_7RegTreeESt14default_deleteISB_EESaISE_EE+0x4c) [0x7f75f24a44]
[bt] (3) /root/gpu_env/local/lib/python2.7/site-packages/xgboost-0.6-py2.7.egg/xgboost/libxgboost.so(_ZN7xgboost3gbm6GBTree7DoBoostEPNS_7DMatrixEPSt6vectorINS_9bst_gpairESaIS5_EEPNS_11ObjFunctionE+0x6d4) [0x7f75f25c74]
[bt] (4) /root/gpu_env/local/lib/python2.7/site-packages/xgboost-0.6-py2.7.egg/xgboost/libxgboost.so(_ZN7xgboost11LearnerImpl13UpdateOneIterEiPNS_7DMatrixE+0x1ac) [0x7f75e00434]
[bt] (5) /root/gpu_env/local/lib/python2.7/site-packages/xgboost-0.6-py2.7.egg/xgboost/libxgboost.so(XGBoosterUpdateOneIter+0x48) [0x7f75f34aa8]
[bt] (6) /usr/lib/aarch64-linux-gnu/libffi.so.6(ffi_call_SYSV+0x64) [0x7f7d3e5e60]
[bt] (7) /usr/lib/aarch64-linux-gnu/libffi.so.6(ffi_call+0xc0) [0x7f7d3e67b8]
[bt] (8) /root/gpu_env/lib/python2.7/lib-dynload/_ctypes.aarch64-linux-gnu.so(_ctypes_callproc+0x670) [0x7f7d426b30]

-------------------- >> begin captured stdout << ---------------------
[0]	train-auc:0.958228	test-auc:0.960373
[1]	train-auc:0.981413	test-auc:0.97993
[2]	train-auc:0.99707	test-auc:0.998518
[3]	train-auc:0.998757	test-auc:0.998943
[4]	train-auc:0.999298	test-auc:0.99983
[5]	train-auc:0.999585	test-auc:1
[6]	train-auc:0.999585	test-auc:1
[7]	train-auc:0.999916	test-auc:1
[8]	train-auc:0.999916	test-auc:1
[9]	train-auc:1	test-auc:1

--------------------- >> end captured stdout << ----------------------

======================================================================
ERROR: test_grow_gpu_hist (test.TestGPU)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/root/xgboost/plugin/updater_gpu/test/python/test.py", line 162, in test_grow_gpu_hist
    evals_result=ag_res2)
  File "/root/gpu_env/local/lib/python2.7/site-packages/xgboost-0.6-py2.7.egg/xgboost/training.py", line 204, in train
    xgb_model=xgb_model, callbacks=callbacks)
  File "/root/gpu_env/local/lib/python2.7/site-packages/xgboost-0.6-py2.7.egg/xgboost/training.py", line 74, in _train_internal
    bst.update(dtrain, i, obj)
  File "/root/gpu_env/local/lib/python2.7/site-packages/xgboost-0.6-py2.7.egg/xgboost/core.py", line 827, in update
    dtrain.handle))
  File "/root/gpu_env/local/lib/python2.7/site-packages/xgboost-0.6-py2.7.egg/xgboost/core.py", line 130, in _check_call
    raise XGBoostError(_LIB.XGBGetLastError())
XGBoostError: [11:15:33] src/tree/tree_updater.cc:18: Unknown tree updater grow_gpu_hist

Stack trace returned 9 entries:
[bt] (0) /root/gpu_env/local/lib/python2.7/site-packages/xgboost-0.6-py2.7.egg/xgboost/libxgboost.so(_ZN7xgboost11TreeUpdater6CreateERKNSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEEE+0x300) [0x7f75eb0f50]
[bt] (1) /root/gpu_env/local/lib/python2.7/site-packages/xgboost-0.6-py2.7.egg/xgboost/libxgboost.so(_ZN7xgboost3gbm6GBTree11InitUpdaterEv+0x1a4) [0x7f75f2050c]
[bt] (2) /root/gpu_env/local/lib/python2.7/site-packages/xgboost-0.6-py2.7.egg/xgboost/libxgboost.so(_ZN7xgboost3gbm6GBTree13BoostNewTreesERKSt6vectorINS_9bst_gpairESaIS3_EEPNS_7DMatrixEiPS2_ISt10unique_ptrINS_7RegTreeESt14default_deleteISB_EESaISE_EE+0x4c) [0x7f75f24a44]
[bt] (3) /root/gpu_env/local/lib/python2.7/site-packages/xgboost-0.6-py2.7.egg/xgboost/libxgboost.so(_ZN7xgboost3gbm6GBTree7DoBoostEPNS_7DMatrixEPSt6vectorINS_9bst_gpairESaIS5_EEPNS_11ObjFunctionE+0x6d4) [0x7f75f25c74]
[bt] (4) /root/gpu_env/local/lib/python2.7/site-packages/xgboost-0.6-py2.7.egg/xgboost/libxgboost.so(_ZN7xgboost11LearnerImpl13UpdateOneIterEiPNS_7DMatrixE+0x1ac) [0x7f75e00434]
[bt] (5) /root/gpu_env/local/lib/python2.7/site-packages/xgboost-0.6-py2.7.egg/xgboost/libxgboost.so(XGBoosterUpdateOneIter+0x48) [0x7f75f34aa8]
[bt] (6) /usr/lib/aarch64-linux-gnu/libffi.so.6(ffi_call_SYSV+0x64) [0x7f7d3e5e60]
[bt] (7) /usr/lib/aarch64-linux-gnu/libffi.so.6(ffi_call+0xc0) [0x7f7d3e67b8]
[bt] (8) /root/gpu_env/lib/python2.7/lib-dynload/_ctypes.aarch64-linux-gnu.so(_ctypes_callproc+0x670) [0x7f7d426b30]

-------------------- >> begin captured stdout << ---------------------
[0]	train-auc:0.987112	test-auc:0.986255
[1]	train-auc:0.999936	test-auc:1
[2]	train-auc:1	test-auc:1
[3]	train-auc:1	test-auc:1
[4]	train-auc:1	test-auc:1
[5]	train-auc:1	test-auc:1
[6]	train-auc:1	test-auc:1
[7]	train-auc:1	test-auc:1
[8]	train-auc:1	test-auc:1
[9]	train-auc:1	test-auc:1

--------------------- >> end captured stdout << ----------------------

----------------------------------------------------------------------
Ran 2 tests in 0.901s

FAILED (errors=2)

```

## Environment info
Machine:
```
(gpu_env) root@tegra-ubuntu:~/xgboost# uname -r
3.10.96-tegra
```

Operating System:
```
(gpu_env) root@tegra-ubuntu:~/xgboost/plugin/updater_gpu# cat /etc/*-release
DISTRIB_ID=Ubuntu
DISTRIB_RELEASE=16.04
DISTRIB_CODENAME=xenial
```

Compiler:
```
(gpu_env) root@tegra-ubuntu:~/xgboost/plugin/updater_gpu# g++ --version
g++ (Ubuntu/Linaro 5.4.0-6ubuntu1~16.04.4) 5.4.0 20160609

(gpu_env) root@tegra-ubuntu:~/xgboost/plugin/updater_gpu# gcc --version
gcc (Ubuntu/Linaro 5.4.0-6ubuntu1~16.04.4) 5.4.0 20160609
```

Package used (python/R/jvm/C++):
`Python 2.7.12`

`xgboost` version used:
```
Python 2.7.12 (default, Nov 19 2016, 06:48:10) 
[GCC 5.4.0 20160609] on linux2
Type "help", "copyright", "credits" or "license" for more information.
>>> import xgboost
>>> xgboost.__version__
'0.6'
```

The commit hash (`git rev-parse HEAD`)
```
(gpu_env) root@tegra-ubuntu:~/xgboost# git rev-parse HEAD
0db37c05bdcd56885a6eef2e1158b9c77eddefbe
```

## Steps to reproduce

1. Git clone xgboost. Following [this](https://github.com/dmlc/xgboost/issues/1545)
2. Removed the -msse2 in line 51 of Makefile, which is the CFLAGS cmd and removed --msse2 in Makefile including rabit & dmlc-core dir.
3. Installed python pkg - `cd python-package; sudo python setup.py install`
4.`python xgboost/plugin/updater_gpu/benchmark/benchmark.py --algorithm all`
5. `python -m nose test/python/`

## What have you tried?

1. Not much .. initially thought of error due to arm architecture but xgboost got installed properly.
Not sure what and where to try out.

**Comment by RAMitchell** [comment]
Did you follow the install instructions from the GPU plug-in readme?
