### ISSUE TITLE
version `GLIBCXX_3.4.22' not found (required by /home/uname/anaconda3/lib/python3.6/site-packages/xgboost/./lib/libxgboost.so)

### ISSUE THREAD

**Issue by rakshithvasudev** [dmlc/xgboost#2538]
Hello folks,

I have Anaconda Installed.

I Installed xgboost from pip, when I import xgboost it says  "version `GLIBCXX_3.4.22' not found ".
I've already tried the solutions provided here. Things like conda install libgcc doesn't do anything for me. It's already installed but doesn't seem to help.

## Environment info
Operating System: Ubuntu 17.04
`xgboost` version used:  0.6a2  
Compiler: Python

## Log
Python 3.6.1 |Anaconda custom (64-bit)| (default, May 11 2017, 13:09:58) 
[GCC 4.4.7 20120313 (Red Hat 4.4.7-1)] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import xgboost
/home/rakshith/anaconda3/lib/python3.6/site-packages/sklearn/cross_validation.py:44: DeprecationWarning: This module was deprecated in version 0.18 in favor of the model_selection module into which all the refactored classes and functions are moved. Also note that the interface of the new CV iterators are different from that of this module. This module will be removed in 0.20.
  "This module will be removed in 0.20.", DeprecationWarning)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/rakshith/anaconda3/lib/python3.6/site-packages/xgboost/__init__.py", line 11, in <module>
    from .core import DMatrix, Booster
  File "/home/rakshith/anaconda3/lib/python3.6/site-packages/xgboost/core.py", line 112, in <module>
    _LIB = _load_lib()
  File "/home/rakshith/anaconda3/lib/python3.6/site-packages/xgboost/core.py", line 106, in _load_lib
    lib = ctypes.cdll.LoadLibrary(lib_path[0])
  File "/home/rakshith/anaconda3/lib/python3.6/ctypes/__init__.py", line 426, in LoadLibrary
    return self._dlltype(name)
  File "/home/rakshith/anaconda3/lib/python3.6/ctypes/__init__.py", line 348, in __init__
    self._handle = _dlopen(self._name, mode)
OSError: /home/rakshith/anaconda3/lib/python3.6/site-packages/scipy/sparse/../../../../libstdc++.so.6: version `GLIBCXX_3.4.22' not found (required by /home/rakshith/anaconda3/lib/python3.6/site-packages/xgboost/./lib/libxgboost.so)
 

PS: I tried installing by cloning the repo as indicated here: http://xgboost.readthedocs.io/en/latest/build.html#building-on-ubuntu-debian

That method tells me I don't have numpy installed. Could somebody please help me in this regard?

**Comment by rakshithvasudev** [comment]
Conda's official command fixed it.

`conda install -c conda-forge keras  `

But with this warning: 
/home/rakshith/anaconda3/lib/python3.6/site-packages/sklearn/cross_validation.py:44: DeprecationWarning: This module was deprecated in version 0.18 in favor of the model_selection module into which all the refactored classes and functions are moved. Also note that the interface of the new CV iterators are different from that of this module. This module will be removed in 0.20.  "This module will be removed in 0.20.", DeprecationWarning)

which is okay, I suppose.
