### ISSUE TITLE
subprocess.CalledProcessError: Command 'cmake --build . --config Release' returned non-zero exit status 2

### ISSUE THREAD

**Issue by yuhulian** [dmlc/xgboost#2547]
```
[simon@localhost build]$ cat /etc/issue
CentOS release 6.5 (Final)
```

```
[simon@localhost build]$ cmake --version
cmake version 3.9.0
```

```
CMake suite maintained and supported by Kitware (kitware.com/cmake).
[simon@localhost build]$ gcc -v
Using built-in specs.
COLLECT_GCC=gcc
COLLECT_LTO_WRAPPER=/usr/local/libexec/gcc/x86_64-unknown-linux-gnu/4.8.2/lto-wrapper
Target: x86_64-unknown-linux-gnu
Configured with: ./configure
Thread model: posix
gcc version 4.8.2 (GCC) 
```

```
[simon@localhost xgboost]$ cd jvm-packages/
[simon@localhost jvm-packages]$ mvn clean install
[INFO] Scanning for projects...
[WARNING] 
[WARNING] Some problems were encountered while building the effective model for ml.dmlc:xgboost4j:jar:0.7
[WARNING] 'build.plugins.plugin.version' for org.codehaus.mojo:exec-maven-plugin is missing. @ line 54, column 19
[WARNING] 
[WARNING] It is highly recommended to fix these problems because they threaten the stability of your build.
[WARNING] 
[WARNING] For this reason, future Maven versions might no longer support building such malformed projects.
[WARNING] 
[INFO] ------------------------------------------------------------------------
[INFO] Reactor Build Order:
[INFO] 
[INFO] xgboost-jvm
[INFO] xgboost4j
[INFO] xgboost4j-spark
[INFO] xgboost4j-flink
[INFO] xgboost4j-example
[INFO] 
[INFO] ------------------------------------------------------------------------
[INFO] Building xgboost-jvm 0.7
[INFO] ------------------------------------------------------------------------
[INFO] 
[INFO] --- maven-clean-plugin:2.5:clean (default-clean) @ xgboost-jvm ---
[INFO] 
[INFO] --- scalastyle-maven-plugin:0.8.0:check (checkstyle) @ xgboost-jvm ---
[WARNING] sourceDirectory is not specified or does not exist value=/home/simon/xgboost/jvm-packages/src/main/scala
[WARNING] testSourceDirectory is not specified or does not exist value=/home/simon/xgboost/jvm-packages/src/test/scala
Processed 0 file(s)
Found 0 errors
Found 0 warnings
Found 0 infos
Finished in 199 ms
[INFO] 
[INFO] --- maven-checkstyle-plugin:2.17:check (checkstyle) @ xgboost-jvm ---
[INFO] 
[INFO] --- scala-maven-plugin:3.2.2:compile (default) @ xgboost-jvm ---
[WARNING]  Expected all dependencies to require Scala version: 2.11.8
[WARNING]  ml.dmlc:xgboost-jvm:0.7 requires scala version: 2.11.8
[WARNING]  org.scala-lang:scala-compiler:2.11.8 requires scala version: 2.11.8
[WARNING]  org.scala-lang.modules:scala-xml_2.11:1.0.4 requires scala version: 2.11.4
[WARNING] Multiple versions of scala libraries detected!
[INFO] No sources to compile
[INFO] 
[INFO] --- scala-maven-plugin:3.2.2:compile (scala-compile-first) @ xgboost-jvm ---
[WARNING]  Expected all dependencies to require Scala version: 2.11.8
[WARNING]  ml.dmlc:xgboost-jvm:0.7 requires scala version: 2.11.8
[WARNING]  org.scala-lang:scala-compiler:2.11.8 requires scala version: 2.11.8
[WARNING]  org.scala-lang.modules:scala-xml_2.11:1.0.4 requires scala version: 2.11.4
[WARNING] Multiple versions of scala libraries detected!
[INFO] No sources to compile
[INFO] 
[INFO] --- scala-maven-plugin:3.2.2:add-source (scala-compile-first) @ xgboost-jvm ---
[INFO] Add Source directory: /home/simon/xgboost/jvm-packages/src/main/scala
[INFO] Add Test Source directory: /home/simon/xgboost/jvm-packages/src/test/scala
[INFO] 
[INFO] --- scala-maven-plugin:3.2.2:compile (compile) @ xgboost-jvm ---
[WARNING]  Expected all dependencies to require Scala version: 2.11.8
[WARNING]  ml.dmlc:xgboost-jvm:0.7 requires scala version: 2.11.8
[WARNING]  org.scala-lang:scala-compiler:2.11.8 requires scala version: 2.11.8
[WARNING]  org.scala-lang.modules:scala-xml_2.11:1.0.4 requires scala version: 2.11.4
[WARNING] Multiple versions of scala libraries detected!
[INFO] No sources to compile
[INFO] 
[INFO] --- scala-maven-plugin:3.2.2:testCompile (test-compile) @ xgboost-jvm ---
[WARNING]  Expected all dependencies to require Scala version: 2.11.8
[WARNING]  ml.dmlc:xgboost-jvm:0.7 requires scala version: 2.11.8
[WARNING]  org.scala-lang:scala-compiler:2.11.8 requires scala version: 2.11.8
[WARNING]  org.scala-lang.modules:scala-xml_2.11:1.0.4 requires scala version: 2.11.4
[WARNING] Multiple versions of scala libraries detected!
[INFO] No sources to compile
[INFO] 
[INFO] --- scalatest-maven-plugin:1.0:test (test) @ xgboost-jvm ---
Discovery starting.
Discovery completed in 204 milliseconds.
Run starting. Expected test count is: 0
DiscoverySuite:
Run completed in 433 milliseconds.
Total number of tests run: 0
Suites: completed 1, aborted 0
Tests: succeeded 0, failed 0, canceled 0, ignored 0, pending 0
No tests were executed.
[INFO] 
[INFO] --- maven-assembly-plugin:2.6:single (make-assembly) @ xgboost-jvm ---
[INFO] Assemblies have been skipped per configuration of the skipAssembly parameter.
[INFO] 
[INFO] --- maven-source-plugin:3.0.1:jar-no-fork (attach-sources) @ xgboost-jvm ---
[INFO] 
[INFO] --- maven-install-plugin:2.4:install (default-install) @ xgboost-jvm ---
[INFO] Installing /home/simon/xgboost/jvm-packages/pom.xml to /home/simon/.m2/repository/ml/dmlc/xgboost-jvm/0.7/xgboost-jvm-0.7.pom
[INFO] 
[INFO] ------------------------------------------------------------------------
[INFO] Building xgboost4j 0.7
[INFO] ------------------------------------------------------------------------
[INFO] 
[INFO] --- maven-clean-plugin:2.5:clean (default-clean) @ xgboost4j ---
[INFO] 
[INFO] --- scalastyle-maven-plugin:0.8.0:check (checkstyle) @ xgboost4j ---
Processed 13 file(s)
Found 0 errors
Found 0 warnings
Found 0 infos
Finished in 3431 ms
[INFO] 
[INFO] --- maven-checkstyle-plugin:2.17:check (checkstyle) @ xgboost4j ---
[INFO] 
[INFO] --- exec-maven-plugin:1.6.0:exec (native) @ xgboost4j ---
-- The C compiler identification is GNU 4.4.7
-- The CXX compiler identification is GNU 4.4.7
-- Check for working C compiler: /usr/bin/cc
-- Check for working C compiler: /usr/bin/cc -- works
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Detecting C compile features
-- Detecting C compile features - done
-- Check for working CXX compiler: /usr/bin/c++
-- Check for working CXX compiler: /usr/bin/c++ -- works
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Detecting CXX compile features
-- Detecting CXX compile features - done
-- Found OpenMP_C: -fopenmp (found version "3.0") 
-- Found OpenMP_CXX: -fopenmp (found version "3.0") 
-- Setting build type to 'Release' as none was specified.
-- Performing Test SUPPORT_CXX0X
-- Performing Test SUPPORT_CXX0X - Success
-- Performing Test SUPPORT_MSSE2
-- Performing Test SUPPORT_MSSE2 - Success
-- Found OpenMP_C: -fopenmp (found version "3.0") 
-- Found OpenMP_CXX: -fopenmp (found version "3.0") 
-- Configuring done
-- Generating done
-- Build files have been written to: /home/simon/xgboost/build
Scanning dependencies of target rabit
[  1%] Building CXX object CMakeFiles/rabit.dir/rabit/src/allreduce_base.cc.o
In file included from /home/simon/xgboost/rabit/src/./../include/rabit/internal/../../dmlc/./logging.h:15,
                 from /home/simon/xgboost/rabit/src/./../include/rabit/internal/../../dmlc/io.h:14,
                 from /home/simon/xgboost/rabit/src/./../include/rabit/internal/../serializable.h:12,
                 from /home/simon/xgboost/rabit/src/./../include/rabit/internal/engine.h:10,
                 from /home/simon/xgboost/rabit/src/./allreduce_base.h:19,
                 from /home/simon/xgboost/rabit/src/allreduce_base.cc:14:
/home/simon/xgboost/rabit/src/./../include/rabit/internal/../../dmlc/././base.h:105: note: #pragma message: Will need g++-4.6 or higher to compile allthe features in dmlc-core, compile without c++0x, some features may be disabled
In file included from /home/simon/xgboost/rabit/src/./../include/rabit/internal/../../dmlc/io.h:14,
                 from /home/simon/xgboost/rabit/src/./../include/rabit/internal/../serializable.h:12,
                 from /home/simon/xgboost/rabit/src/./../include/rabit/internal/engine.h:10,
                 from /home/simon/xgboost/rabit/src/./allreduce_base.h:19,
                 from /home/simon/xgboost/rabit/src/allreduce_base.cc:14:
/home/simon/xgboost/rabit/src/./../include/rabit/internal/../../dmlc/./logging.h: In constructor ‘dmlc::LogCheckError::LogCheckError()’:
/home/simon/xgboost/rabit/src/./../include/rabit/internal/../../dmlc/./logging.h:66: error: ‘nullptr’ was not declared in this scope
/home/simon/xgboost/rabit/src/./../include/rabit/internal/../../dmlc/./logging.h: In destructor ‘dmlc::LogCheckError::~LogCheckError()’:
/home/simon/xgboost/rabit/src/./../include/rabit/internal/../../dmlc/./logging.h:68: error: ‘nullptr’ was not declared in this scope
/home/simon/xgboost/rabit/src/./../include/rabit/internal/../../dmlc/./logging.h: In member function ‘dmlc::LogCheckError::operator bool()’:
/home/simon/xgboost/rabit/src/./../include/rabit/internal/../../dmlc/./logging.h:69: error: ‘nullptr’ was not declared in this scope
In file included from /home/simon/xgboost/rabit/src/./../include/rabit/internal/../../dmlc/io.h:14,
                 from /home/simon/xgboost/rabit/src/./../include/rabit/internal/../serializable.h:12,
                 from /home/simon/xgboost/rabit/src/./../include/rabit/internal/engine.h:10,
                 from /home/simon/xgboost/rabit/src/./allreduce_base.h:19,
                 from /home/simon/xgboost/rabit/src/allreduce_base.cc:14:
/home/simon/xgboost/rabit/src/./../include/rabit/internal/../../dmlc/./logging.h: In destructor ‘dmlc::LogMessageFatal::~LogMessageFatal()’:
/home/simon/xgboost/rabit/src/./../include/rabit/internal/../../dmlc/./logging.h:289: error: ‘nullptr’ was not declared in this scope
gmake[2]: *** [CMakeFiles/rabit.dir/rabit/src/allreduce_base.cc.o] Error 1
gmake[1]: *** [CMakeFiles/rabit.dir/all] Error 2
gmake: *** [all] Error 2
building Java wrapper
cd ..
mkdir -p build
cd build
cmake .. -DUSE_S3:BOOL=OFF -DUSE_OPENMP:BOOL=ON -DPLUGIN_UPDATER_GPU:BOOL=OFF -DUSE_AZURE:BOOL=OFF -DUSE_HDFS:BOOL=OFF -DJVM_BINDINGS:BOOL=ON
cmake --build . --config Release
Traceback (most recent call last):
  File "create_jni.py", line 89, in <module>
    run("cmake --build . --config Release")
  File "create_jni.py", line 51, in run
    subprocess.check_call(command, shell=True, **kwargs)
  File "/usr/lib64/python2.6/subprocess.py", line 505, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command 'cmake --build . --config Release' returned non-zero exit status 2
[ERROR] Command execution failed.
org.apache.commons.exec.ExecuteException: Process exited with an error: 1 (Exit value: 1)
	at org.apache.commons.exec.DefaultExecutor.executeInternal(DefaultExecutor.java:404)
	at org.apache.commons.exec.DefaultExecutor.execute(DefaultExecutor.java:166)
	at org.codehaus.mojo.exec.ExecMojo.executeCommandLine(ExecMojo.java:804)
	at org.codehaus.mojo.exec.ExecMojo.executeCommandLine(ExecMojo.java:751)
	at org.codehaus.mojo.exec.ExecMojo.execute(ExecMojo.java:313)
	at org.apache.maven.plugin.DefaultBuildPluginManager.executeMojo(DefaultBuildPluginManager.java:134)
	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:208)
	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:154)
	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:146)
	at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject(LifecycleModuleBuilder.java:117)
	at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject(LifecycleModuleBuilder.java:81)
	at org.apache.maven.lifecycle.internal.builder.singlethreaded.SingleThreadedBuilder.build(SingleThreadedBuilder.java:51)
	at org.apache.maven.lifecycle.internal.LifecycleStarter.execute(LifecycleStarter.java:128)
	at org.apache.maven.DefaultMaven.doExecute(DefaultMaven.java:309)
	at org.apache.maven.DefaultMaven.doExecute(DefaultMaven.java:194)
	at org.apache.maven.DefaultMaven.execute(DefaultMaven.java:107)
	at org.apache.maven.cli.MavenCli.execute(MavenCli.java:993)
	at org.apache.maven.cli.MavenCli.doMain(MavenCli.java:345)
	at org.apache.maven.cli.MavenCli.main(MavenCli.java:191)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.codehaus.plexus.classworlds.launcher.Launcher.launchEnhanced(Launcher.java:289)
	at org.codehaus.plexus.classworlds.launcher.Launcher.launch(Launcher.java:229)
	at org.codehaus.plexus.classworlds.launcher.Launcher.mainWithExitCode(Launcher.java:415)
	at org.codehaus.plexus.classworlds.launcher.Launcher.main(Launcher.java:356)
[INFO] ------------------------------------------------------------------------
[INFO] Reactor Summary:
[INFO] 
[INFO] xgboost-jvm ........................................ SUCCESS [ 12.419 s]
[INFO] xgboost4j .......................................... FAILURE [ 12.182 s]
[INFO] xgboost4j-spark .................................... SKIPPED
[INFO] xgboost4j-flink .................................... SKIPPED
[INFO] xgboost4j-example .................................. SKIPPED
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 25.120 s
[INFO] Finished at: 2017-07-25T02:22:11-07:00
[INFO] Final Memory: 18M/44M
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal org.codehaus.mojo:exec-maven-plugin:1.6.0:exec (native) on project xgboost4j: Command execution failed.: Process exited with an error: 1 (Exit value: 1) -> [Help 1]
[ERROR] 
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR] 
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/MojoExecutionException
[ERROR] 
[ERROR] After correcting the problems, you can resume the build with the command
[ERROR]   mvn <goals> -rf :xgboost4j
```

```

[simon@localhost jvm-packages]$ cd ../build
[simon@localhost build]$ ls
c_api  cli_main.d  cli_main.o  CMakeCache.txt  CMakeFiles  cmake_install.cmake  common  data  dmlc-core  gbm  learner.d  learner.o  logging.d  logging.o  Makefile  metric  objective  tree
[simon@localhost build]$ cmake --build . --config Release
[  1%] Building CXX object CMakeFiles/rabit.dir/rabit/src/allreduce_base.cc.o
In file included from /home/simon/xgboost/rabit/src/./../include/rabit/internal/../../dmlc/./logging.h:15,
                 from /home/simon/xgboost/rabit/src/./../include/rabit/internal/../../dmlc/io.h:14,
                 from /home/simon/xgboost/rabit/src/./../include/rabit/internal/../serializable.h:12,
                 from /home/simon/xgboost/rabit/src/./../include/rabit/internal/engine.h:10,
                 from /home/simon/xgboost/rabit/src/./allreduce_base.h:19,
                 from /home/simon/xgboost/rabit/src/allreduce_base.cc:14:
/home/simon/xgboost/rabit/src/./../include/rabit/internal/../../dmlc/././base.h:105: note: #pragma message: Will need g++-4.6 or higher to compile allthe features in dmlc-core, compile without c++0x, some features may be disabled
In file included from /home/simon/xgboost/rabit/src/./../include/rabit/internal/../../dmlc/io.h:14,
                 from /home/simon/xgboost/rabit/src/./../include/rabit/internal/../serializable.h:12,
                 from /home/simon/xgboost/rabit/src/./../include/rabit/internal/engine.h:10,
                 from /home/simon/xgboost/rabit/src/./allreduce_base.h:19,
                 from /home/simon/xgboost/rabit/src/allreduce_base.cc:14:
/home/simon/xgboost/rabit/src/./../include/rabit/internal/../../dmlc/./logging.h: In constructor ‘dmlc::LogCheckError::LogCheckError()’:
/home/simon/xgboost/rabit/src/./../include/rabit/internal/../../dmlc/./logging.h:66: error: ‘nullptr’ was not declared in this scope
/home/simon/xgboost/rabit/src/./../include/rabit/internal/../../dmlc/./logging.h: In destructor ‘dmlc::LogCheckError::~LogCheckError()’:
/home/simon/xgboost/rabit/src/./../include/rabit/internal/../../dmlc/./logging.h:68: error: ‘nullptr’ was not declared in this scope
/home/simon/xgboost/rabit/src/./../include/rabit/internal/../../dmlc/./logging.h: In member function ‘dmlc::LogCheckError::operator bool()’:
/home/simon/xgboost/rabit/src/./../include/rabit/internal/../../dmlc/./logging.h:69: error: ‘nullptr’ was not declared in this scope
In file included from /home/simon/xgboost/rabit/src/./../include/rabit/internal/../../dmlc/io.h:14,
                 from /home/simon/xgboost/rabit/src/./../include/rabit/internal/../serializable.h:12,
                 from /home/simon/xgboost/rabit/src/./../include/rabit/internal/engine.h:10,
                 from /home/simon/xgboost/rabit/src/./allreduce_base.h:19,
                 from /home/simon/xgboost/rabit/src/allreduce_base.cc:14:
/home/simon/xgboost/rabit/src/./../include/rabit/internal/../../dmlc/./logging.h: In destructor ‘dmlc::LogMessageFatal::~LogMessageFatal()’:
/home/simon/xgboost/rabit/src/./../include/rabit/internal/../../dmlc/./logging.h:289: error: ‘nullptr’ was not declared in this scope
gmake[2]: *** [CMakeFiles/rabit.dir/rabit/src/allreduce_base.cc.o] Error 1
gmake[1]: *** [CMakeFiles/rabit.dir/all] Error 2
gmake: *** [all] Error 2
```

**Comment by superbobry** [comment]
You need newer GCC version (>= 4.6) to build XGBoost. You can get it on CentOS by using devtoolset-4, see [this](https://github.com/criteo-forks/xgboost-jars/blob/master/travis/docker.sh) Docker script.

```
/home/simon/xgboost/rabit/src/./../include/rabit/internal/../../dmlc/./logging.h:289: error: ‘nullptr’ was not declared in this scope
```

**Comment by yuhulian** [comment]
@superbobry 
I ran the script and i have already install devtoolset-4
and my gcc version is 4.8.2

```

++ yum -y install centos-release-scl-rh
Loaded plugins: fastestmirror, refresh-packagekit, security
Loading mirror speeds from cached hostfile
 * base: mirrors.aliyun.com
 * epel: mirrors.ustc.edu.cn
 * extras: mirrors.aliyun.com
 * updates: mirrors.aliyun.com
Setting up Install Process
Package centos-release-scl-rh-2-3.el6.centos.noarch already installed and latest version
Nothing to do
++ yum -y install devtoolset-4-gcc devtoolset-4-gcc-c++
Loaded plugins: fastestmirror, refresh-packagekit, security
Loading mirror speeds from cached hostfile
 * base: mirrors.aliyun.com
 * epel: mirrors.tuna.tsinghua.edu.cn
 * extras: mirrors.aliyun.com
 * updates: mirrors.aliyun.com
Setting up Install Process
Package devtoolset-4-gcc-5.3.1-6.1.el6.x86_64 already installed and latest version
Package devtoolset-4-gcc-c++-5.3.1-6.1.el6.x86_64 already installed and latest version
Nothing to do
++ source /opt/rh/devtoolset-4/enable
+++ test -e /opt/rh/rh-java-common/enable
+++ . scl_source enable rh-java-common
++++ _scl_source_help='Usage: source scl_source <action> [<collection> ...]

Don'\''t use this script outside of SCL scriptlets!

Options:
    -h, --help    display this help and exit'
++++ '[' 2 -eq 0 -o enable = -h -o enable = --help ']'
++++ '[' -z '' ']'
++++ _recursion=false
++++ '[' -z '' ']'
++++ _scl_scriptlet_name=enable
++++ shift 1
++++ '[' -z '' ']'
++++ _scl_dir=/etc/scl/conf
++++ '[' '!' -e /etc/scl/conf ']'
++++ _scl_dir=/etc/scl/prefixes
++++ for arg in '"$@"'
++++ _scl_prefix_file=/etc/scl/prefixes/rh-java-common
+++++ cat /etc/scl/prefixes/rh-java-common
++++ _scl_prefix=/opt/rh
++++ '[' 0 -ne 0 ']'
++++ /usr/bin/scl_enabled rh-java-common
```

**Comment by superbobry** [comment]
Make sure you also set CC and CXX environment variables. The version of GCC in devtoolset-4 is 5.2.1 see [this](https://access.redhat.com/documentation/en-US/Red_Hat_Developer_Toolset/4/html/4.0_Release_Notes/DTS4.0_Release.html).

**Comment by yangxudong** [comment]
do anyone has some solutions for this issue?
