### ISSUE TITLE
Poor memory usage in scipy.sparse to DMatrix conversion

### ISSUE THREAD

**Issue by soluwalana** [dmlc/xgboost#2785]
When indices / indptr are an array of np.int64 the following line causes an error:

https://github.com/dmlc/xgboost/blob/78c4188cec31425f708d238160ea3afb67a7250a/python-package/xgboost/core.py#L160-L162

```
Traceback (most recent call last):
  File "run_xgboost.py", line 142, in <module>
    main()
  File "run_xgboost.py", line 116, in main
    dtrain = xgb.DMatrix(X, label=y, weight=weights)
  File "/usr/local/lib/python3.5/dist-packages/xgboost-0.6-py3.5.egg/xgboost/core.py", line 276, in __init__
    self._init_from_csc(data)
  File "/usr/local/lib/python3.5/dist-packages/xgboost-0.6-py3.5.egg/xgboost/core.py", line 322, in _init_from_csc
    c_array(ctypes.c_uint, csc.indices),
  File "/usr/local/lib/python3.5/dist-packages/xgboost-0.6-py3.5.egg/xgboost/core.py", line 162, in c_array
    return (ctype * len(values))(*values)
SystemError: ../Objects/tupleobject.c:71: bad argument to internal function
```

It is easy to reproduce with this minimal bit of code:

```python
>>> import ctypes
>>> import numpy as np
>>> a = np.ones(np.iinfo(np.int32).max + 1, dtype=np.uint32)
>>> a[-1] = np.iinfo(np.int32).max + 123
>>> start = time.time()
>>> (ctypes.c_uint * len(a))(*a)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
SystemError: ../Objects/tupleobject.c:71: bad argument to internal function
>>> print(time.time() - start)
130.310668945331865
```

Also for my input array, which consumes 8GB of memory, the `c_array` function causes an explosion of memory usage up to 75GB, and it takes a horribly long 130 seconds at 100% cpu usage before failure.

This doesn't appear to be an out of memory issue as the machine that I am on still has 25GB of memory left when the error occurs. 

This happens in python 3.5 and python 3.6

I have a potential solution:

```python
(ctypes.c_uint * len(values)).from_buffer_copy(values)
```

If the input array is 8GB this solution only doubles the memory to 16GB, and it takes only 7 seconds.

```
>>> import time
>>> start = time.time(); x = (ctypes.c_uint * len(a)).from_buffer_copy(a); print(time.time() - start)
7.331865310668945
```

**Comment by soluwalana** [comment]
probably needs some checks on the dtype of the incoming array for buffer length and change the buffer size of the np.array if it doesn't match and can be converted
