### ISSUE TITLE
[jvm-packages] xgboost4j-spark RabitTracker error

### ISSUE THREAD

**Issue by hrxu01** [dmlc/xgboost#2918]
Operating System:
Linux n3-023-041 3.16.0-4-amd64 #1 SMP Debian 3.16.36-1+deb8u2 (2016-10-19) x86_64 GNU/Linux

Compiler:
cmake 3.10
gcc (Debian 4.9.2-10) 4.9.2
spark 2.2

Package used (python/R/jvm/C++):
jvm

`xgboost` version used:
0.7

The commit hash (`git rev-parse HEAD`)
c51adb49b66cc402858580880ce32969d64a05be

Logs will be helpful (If logs are large, please upload as attachment).
[mvn.log](https://github.com/dmlc/xgboost/files/1520884/mvn.log)

first i use maven install with test skiped, and with agaricus data set i train and test ok. But when it come to my own data, which is much bigger, I got ml.dmlc.xgboost4j.java.XGBoostError: XGBoostModel training failed. 

val model = XGBoost.trainWithRDD(test_lp, paramMap, numRound, nWorkers=1, eval = null, useExternalMemory =false, missing=Float.NaN)
Tracker started, with env={DMLC_NUM_SERVER=0, DMLC_TRACKER_URI=(right ip, i hidde it), DMLC_TRACKER_PORT=9093, DMLC_NUM_WORKER=1}
[Stage 0:======================================================>(199 + 1) / 200]17/12/01 16:30:18 ERROR YarnScheduler: Lost executor 11 on n10-178-154.byted.org: Container marked as failed: container_e36_1512104708816_24545_01_000015 on host: n10-178-154.byted.org. Exit status: 134. Diagnostics: Exception from container-launch.
Container id: container_e36_1512104708816_24545_01_000015
Exit code: 134
Stack trace: ExitCodeException exitCode=134:
	at org.apache.hadoop.util.Shell.runCommand(Shell.java:538)
	at org.apache.hadoop.util.Shell.run(Shell.java:455)
	at org.apache.hadoop.util.Shell$ShellCommandExecutor.execute(Shell.java:715)
	at org.apache.hadoop.yarn.server.nodemanager.LinuxContainerExecutor.launchContainer(LinuxContainerExecutor.java:323)
	at org.apache.hadoop.yarn.server.nodemanager.containermanager.launcher.ContainerLaunch.call(ContainerLaunch.java:300)
	at org.apache.hadoop.yarn.server.nodemanager.containermanager.launcher.ContainerLaunch.call(ContainerLaunch.java:82)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:748)

17/12/01 16:32:40 ERROR RabitTracker: Uncaught exception thrown by worker:
java.lang.InterruptedException
	at java.util.concurrent.locks.AbstractQueuedSynchronizer.doAcquireSharedInterruptibly(AbstractQueuedSynchronizer.java:998)
	at java.util.concurrent.locks.AbstractQueuedSynchronizer.acquireSharedInterruptibly(AbstractQueuedSynchronizer.java:1304)
	at scala.concurrent.impl.Promise$DefaultPromise.tryAwait(Promise.scala:202)
	at scala.concurrent.impl.Promise$DefaultPromise.ready(Promise.scala:218)
	at scala.concurrent.impl.Promise$DefaultPromise.ready(Promise.scala:153)
	at org.apache.spark.util.ThreadUtils$.awaitReady(ThreadUtils.scala:222)
	at org.apache.spark.scheduler.DAGScheduler.runJob(DAGScheduler.scala:621)
	at org.apache.spark.SparkContext.runJob(SparkContext.scala:2044)
	at org.apache.spark.SparkContext.runJob(SparkContext.scala:2065)
	at org.apache.spark.SparkContext.runJob(SparkContext.scala:2084)
	at org.apache.spark.SparkContext.runJob(SparkContext.scala:2109)
	at org.apache.spark.rdd.RDD$$anonfun$foreachPartition$1.apply(RDD.scala:945)
	at org.apache.spark.rdd.RDD$$anonfun$foreachPartition$1.apply(RDD.scala:943)
	at org.apache.spark.rdd.RDDOperationScope$.withScope(RDDOperationScope.scala:151)
	at org.apache.spark.rdd.RDDOperationScope$.withScope(RDDOperationScope.scala:112)
	at org.apache.spark.rdd.RDD.withScope(RDD.scala:371)
	at org.apache.spark.rdd.RDD.foreachPartition(RDD.scala:943)
	at ml.dmlc.xgboost4j.scala.spark.XGBoost$$anon$1.run(XGBoost.scala:339)
17/12/01 16:32:40 WARN ExecutorAllocationManager: No stages are running, but numRunningTasks != 0
ml.dmlc.xgboost4j.java.XGBoostError: XGBoostModel training failed
  at ml.dmlc.xgboost4j.scala.spark.XGBoost$.postTrackerReturnProcessing(XGBoost.scala:382)
  at ml.dmlc.xgboost4j.scala.spark.XGBoost$.trainDistributed(XGBoost.scala:347)
  at ml.dmlc.xgboost4j.scala.spark.XGBoost$.trainWithRDD(XGBoost.scala:292)
  ... 49 elided

It seems like some problem with RabitTracker. I re run mvn clean package with test, and it fails. I paste the log in mvn.log up. Hope get help , thanks a lot.

**Comment by hrxu01** [comment]
Might caused by NaN in my dataset, is this normal? no support Nan

**Comment by superbobry** [comment]
Can you provide the full log? I suspect the issue could be unrelated to the tracker.

**Comment by hrxu01** [comment]
It should be caused by Float.NaN in dataset. I replace it with -1, and run normally. BTW,  I compile the jar from master branch, so there should be some bug or somthing

**Comment by superbobry** [comment]
Could you provide a small sample of your data reproducing the issue? `Float.NaN` is treated as a  missing value and is therefore removed from the data before training.

**Comment by jiang1983** [comment]
I met this problem too, the input is labeledpoint with Float.NaN.

**Comment by chinesejie** [comment]
In my case, env: centos6.3, xgboost0.7, java-1.8 
Centos6.3's default python is python2.6,  xgboost0.7 can be compiled well.

but run with python2.6  will throw Uncaught exception thrown by worker of java.util.concurrent.locks.AbstractQueuedSynchronizer.doAcquireSharedInterruptibly.

The exception is not  obvious to understand.

Upgrade to python 2.7 will solve it.
