### ISSUE TITLE
xgboost in Python can not run 

### ISSUE THREAD

**Issue by zhuqunxi** [dmlc/xgboost#2940]
For bugs or installation issues, please provide the following information.
The more information you provide, the more easily we will be able to offer
help and advice.

## Environment info
Operating System:

Compiler:

Package used (python/R/jvm/C++):

`xgboost` version used:

If installing from source, please provide 

1. The commit hash (`git rev-parse HEAD`)
2. Logs will be helpful (If logs are large, please upload as attachment).

If you are using jvm package, please 

1. add [jvm-packages] in the title to make it quickly be identified
2. the gcc version and distribution

If you are using python package, please provide

1. The python version and distribution
2. The command to install `xgboost` if you are not installing from source

If you are using R package, please provide

1. The R `sessionInfo()`
2. The command to install `xgboost` if you are not installing from source

## Steps to reproduce

1.
2.
3.

## What have you tried?

1.
2.
3.

**Comment by zhuqunxi** [comment]
Traceback (most recent call last):
  File "E:/linwei/神经/葛/CancerML/xg.py", line 7, in <module>
    import xgboost as xgb
  File "C:\Users\ZhuQu\Anaconda3\lib\site-packages\xgboost-0.6-py3.5.egg\xgboost\__init__.py", line 11, in <module>
    from .core import DMatrix, Booster
  File "C:\Users\ZhuQu\Anaconda3\lib\site-packages\xgboost-0.6-py3.5.egg\xgboost\core.py", line 119, in <module>
    _LIB = _load_lib()
  File "C:\Users\ZhuQu\Anaconda3\lib\site-packages\xgboost-0.6-py3.5.egg\xgboost\core.py", line 112, in _load_lib
    lib = ctypes.cdll.LoadLibrary(lib_path[0])
  File "C:\Users\ZhuQu\Anaconda3\lib\ctypes\__init__.py", line 427, in LoadLibrary
    print('bbbbbbbbbbb',self._dlltype(name))
  File "C:\Users\ZhuQu\Anaconda3\lib\ctypes\__init__.py", line 348, in __init__
    self._handle = _dlopen(self._name, mode)
OSError: [WinError 127] 找不到指定的程序。

**Comment by zhuqunxi** [comment]
Traceback (most recent call last):
  File "E:/linwei/神经/葛/CancerML/xg.py", line 7, in <module>
    import xgboost as xgb
  File "C:\Users\ZhuQu\Anaconda3\lib\site-packages\xgboost-0.6-py3.5.egg\xgboost\__init__.py", line 11, in <module>
    from .core import DMatrix, Booster
  File "C:\Users\ZhuQu\Anaconda3\lib\site-packages\xgboost-0.6-py3.5.egg\xgboost\core.py", line 119, in <module>
    _LIB = _load_lib()
  File "C:\Users\ZhuQu\Anaconda3\lib\site-packages\xgboost-0.6-py3.5.egg\xgboost\core.py", line 112, in _load_lib
    lib = ctypes.cdll.LoadLibrary(lib_path[0])
  File "C:\Users\ZhuQu\Anaconda3\lib\ctypes\__init__.py", line 427, in LoadLibrary
    print('bbbbbbbbbbb',self._dlltype(name))
  File "C:\Users\ZhuQu\Anaconda3\lib\ctypes\__init__.py", line 348, in __init__
    self._handle = _dlopen(self._name, mode)
OSError: [WinError 127] 找不到指定的程序。

**Comment by cinqs** [comment]
你可以尝试重新安装一下XGB,


`pip install --upgrade xgboost`, 

如果还是不行的话，可以使用官方教程尝试在你的机器上make source installation.
