### ISSUE TITLE
[jvm-packages]  java.lang.ArrayStoreException: [Z

### ISSUE THREAD

**Issue by universewill** [dmlc/xgboost#2979]
I run xgboost on spark clusters, and always run into this error. Is there any solution or hint?
The error is as follow:

```
17/12/26 13:23:45 WARN conf.HiveConf: HiveConf of name hive.server2.logging.operation.verbose does not exist
17/12/26 13:23:48 WARN scheduler.TaskSetManager: Lost task 63.0 in stage 1.0 (TID 0, node.storage62, executor 8): java.io.IOException: java.lang.ArrayStoreException: [Z
	at org.apache.spark.util.Utils$.tryOrIOException(Utils.scala:1310)
	at org.apache.spark.broadcast.TorrentBroadcast.readBroadcastBlock(TorrentBroadcast.scala:206)
	at org.apache.spark.broadcast.TorrentBroadcast._value$lzycompute(TorrentBroadcast.scala:66)
	at org.apache.spark.broadcast.TorrentBroadcast._value(TorrentBroadcast.scala:66)
	at org.apache.spark.broadcast.TorrentBroadcast.getValue(TorrentBroadcast.scala:96)
	at org.apache.spark.broadcast.Broadcast.value(Broadcast.scala:70)
	at org.apache.spark.scheduler.ShuffleMapTask.runTask(ShuffleMapTask.scala:86)
	at org.apache.spark.scheduler.ShuffleMapTask.runTask(ShuffleMapTask.scala:53)
	at org.apache.spark.scheduler.Task.run(Task.scala:108)
	at org.apache.spark.executor.Executor$TaskRunner.run(Executor.scala:335)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
Caused by: java.lang.ArrayStoreException: [Z
	at scala.runtime.ScalaRunTime$.array_update(ScalaRunTime.scala:90)
	at org.apache.spark.util.collection.PrimitiveVector.$plus$eq(PrimitiveVector.scala:43)
	at org.apache.spark.util.collection.SizeTrackingVector.$plus$eq(SizeTrackingVector.scala:30)
	at org.apache.spark.storage.memory.MemoryStore.putIteratorAsValues(MemoryStore.scala:216)
	at org.apache.spark.storage.BlockManager$$anonfun$doPutIterator$1.apply(BlockManager.scala:1038)
	at org.apache.spark.storage.BlockManager$$anonfun$doPutIterator$1.apply(BlockManager.scala:1029)
	at org.apache.spark.storage.BlockManager.doPut(BlockManager.scala:969)
	at org.apache.spark.storage.BlockManager.doPutIterator(BlockManager.scala:1029)
	at org.apache.spark.storage.BlockManager.putIterator(BlockManager.scala:792)
	at org.apache.spark.storage.BlockManager.putSingle(BlockManager.scala:1350)
	at org.apache.spark.broadcast.TorrentBroadcast$$anonfun$readBroadcastBlock$1.apply(TorrentBroadcast.scala:231)
	at org.apache.spark.util.Utils$.tryOrIOException(Utils.scala:1303)
	... 12 more

17/12/26 13:23:48 ERROR scheduler.TaskSetManager: Task 63 in stage 1.0 failed 4 times; aborting job
17/12/26 13:23:48 ERROR yarn.ApplicationMaster: User class threw exception: ml.dmlc.xgboost4j.java.XGBoostError: XGBoostModel training failed
ml.dmlc.xgboost4j.java.XGBoostError: XGBoostModel training failed
	at ml.dmlc.xgboost4j.scala.spark.XGBoost$.postTrackerReturnProcessing(XGBoost.scala:332)
	at ml.dmlc.xgboost4j.scala.spark.XGBoost$.trainWithRDD(XGBoost.scala:308)
	at com.ximalaya.brain.train.risk.IpTrainWithXgboost$.train(IpTrainWithXgboost.scala:161)
	at com.ximalaya.brain.train.risk.IpTrainWithXgboost$.run(IpTrainWithXgboost.scala:46)
	at com.ximalaya.brain.train.risk.IpTrainWithXgboost$.main(IpTrainWithXgboost.scala:29)
	at com.ximalaya.brain.train.risk.IpTrainWithXgboost.main(IpTrainWithXgboost.scala)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at org.apache.spark.deploy.yarn.ApplicationMaster$$anon$2.run(ApplicationMaster.scala:635)
```

**Comment by superbobry** [comment]
Can you post the code fragment leading to the error? My guess would be that the exception is unrelated to XGBoost, as it happens within Spark during a broadcast operation.

**Comment by bali0019** [comment]
Did this ever get fixed? I am running into the same issue when i deploy my spark driver program on Apache Mesos cluster

**Comment by yvirin-apixio** [comment]
Same thing here. Getting the error only when trying to run remotely, locally it works.

**Comment by pekaalto** [comment]
I had the same problem and it disappeared when I excluded Kryo from xgboost dependency. i.e did this: 
`"ml.dmlc" % "xgboost4j-spark" % "0.80" exclude("com.esotericsoftware.kryo", "kryo")`
