### ISSUE TITLE
 [jvm-packages] java.lang.UnsatisfiedLinkError when loading model 

### ISSUE THREAD

**Issue by datazhen** [dmlc/xgboost#3067]
## Environment info
Operating System:
mac 10.12.5
Compiler:scala
Package used (python/R/jvm/C++):jvm
`xgboost` version used:0.7
gcc:7
## Steps to reproduce
I have a xgboost model file which is created by python in  centos with gcc-6.
Then I loaded it by scala in mac with gcc-7  but error occur
```
import ml.dmlc.xgboost4j.scala.{Booster, XGBoost => SXGBoost}
val model = SXGBoost.loadModel("model.file")
```
Exception in thread "main" java.lang.UnsatisfiedLinkError: /private/var/folders/f4/xvx6q5h12h3_w_6x7ysksfth0000gn/T/libxgboost4j1221256701545281887.dylib: dlopen(/private/var/folders/f4/xvx6q5h12h3_w_6x7ysksfth0000gn/T/libxgboost4j1221256701545281887.dylib, 1): Library not loaded: /usr/local/opt/gcc/lib**/gcc/6**/libgomp.1.dylib
  Referenced from: /private/var/folders/f4/xvx6q5h12h3_w_6x7ysksfth0000gn/T/libxgboost4j1221256701545281887.dylib
  Reason: image not found
	at java.lang.ClassLoader$NativeLibrary.load(Native Method)
	at java.lang.ClassLoader.loadLibrary0(ClassLoader.java:1941)
	at java.lang.ClassLoader.loadLibrary(ClassLoader.java:1824)
	at java.lang.Runtime.load0(Runtime.java:809)
	at java.lang.System.load(System.java:1086)
	at ml.dmlc.xgboost4j.java.NativeLibLoader.loadLibraryFromJar(NativeLibLoader.java:67)
	at ml.dmlc.xgboost4j.java.NativeLibLoader.smartLoad(NativeLibLoader.java:153)
	at ml.dmlc.xgboost4j.java.NativeLibLoader.initXGBoost(NativeLibLoader.java:41)
	at ml.dmlc.xgboost4j.java.Booster.<clinit>(Booster.java:41)
	at ml.dmlc.xgboost4j.java.XGBoost.loadModel(XGBoost.java:41)
	at ml.dmlc.xgboost4j.scala.XGBoost$.loadModel(XGBoost.scala:120)
	at com.wz.app$.main(app.scala:42)
	at com.wz.app.main(app.scala)

Process finished with exit code 1

**Comment by Craigacp** [comment]
It failed to find libgomp, so you should brew install gcc-6.
