### ISSUE TITLE
clang: error: unsupported option '-fopenmp' on OSX

### ISSUE THREAD

**Issue by ablx** [dmlc/xgboost#3082]
## Environment info
Operating System:
macOS High Sierra 10.13.2

Compiler:
> gcc --version
gcc (Homebrew GCC 5.5.0_2) 5.5.0
Copyright (C) 2015 Free Software Foundation, Inc.
This is free software; see the source for copying conditions.  There is NO
warranty; not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.
Package used (python/R/jvm/C++):

`xgboost` version used: latest from pip ( xgboost-0.7.post3.tar.gz)

If installing from source, please provide 

1. The commit hash (`git rev-parse HEAD`)
14a8e2d4909bc1ebc810d0833c3f2613a5a74fa5
2. Logs will be helpful (If logs are large, please upload as attachment).
```
pip3 install xgboost
Collecting xgboost
  Using cached xgboost-0.7.post3.tar.gz
    Complete output from command python setup.py egg_info:
    ++ pwd
    + oldpath=/private/var/folders/dp/cwkbsr654p10mfx8pn2zlyvm0000gn/T/pip-build-bonibbfq/xgboost
    + cd ./xgboost/
    + [[ darwin17 == \d\a\r\w\i\n* ]]
    + LIB_XGBOOST=libxgboost.dylib
    + make lib/libxgboost.dylib -j4
    Makefile:31: MAKE [/Library/Developer/CommandLineTools/usr/bin/make] - checked OK
    c++ -std=c++11 -Wall -Wno-unknown-pragmas -Iinclude   -I/private/var/folders/dp/cwkbsr654p10mfx8pn2zlyvm0000gn/T/pip-build-bonibbfq/xgboost/xgboost/dmlc-core/include -Irabit/include -I/include -O3 -funroll-loops -msse2 -fPIC -fopenmp -MM -MT build/logging.o src/logging.cc >build/logging.d
    c++ -std=c++11 -Wall -Wno-unknown-pragmas -Iinclude   -I/private/var/folders/dp/cwkbsr654p10mfx8pn2zlyvm0000gn/T/pip-build-bonibbfq/xgboost/xgboost/dmlc-core/include -Irabit/include -I/include -O3 -funroll-loops -msse2 -fPIC -fopenmp -MM -MT build/learner.o src/learner.cc >build/learner.d
    c++ -std=c++11 -Wall -Wno-unknown-pragmas -Iinclude   -I/private/var/folders/dp/cwkbsr654p10mfx8pn2zlyvm0000gn/T/pip-build-bonibbfq/xgboost/xgboost/dmlc-core/include -Irabit/include -I/include -O3 -funroll-loops -msse2 -fPIC -fopenmp -MM -MT build/c_api/c_api.o src/c_api/c_api.cc >build/c_api/c_api.d
    c++ -std=c++11 -Wall -Wno-unknown-pragmas -Iinclude   -I/private/var/folders/dp/cwkbsr654p10mfx8pn2zlyvm0000gn/T/pip-build-bonibbfq/xgboost/xgboost/dmlc-core/include -Irabit/include -I/include -O3 -funroll-loops -msse2 -fPIC -fopenmp -MM -MT build/c_api/c_api_error.o src/c_api/c_api_error.cc >build/c_api/c_api_error.d
    clang: error: unsupported option '-fopenmp'
    clang: error: unsupported option '-fopenmp'
    clang: error: clangunsupported option '-fopenmp': error:
    unsupported option '-fopenmp'
    make: *** [build/c_api/c_api_error.o] Error 1
    make: *** Waiting for unfinished jobs....
    make: *** [build/c_api/c_api.o] Error 1
    make: *** [build/logging.o] Error 1
    make: *** [build/learner.o] Error 1
    + echo -----------------------------
    -----------------------------
    + echo 'Building multi-thread xgboost failed'
    Building multi-thread xgboost failed
    + echo 'Start to build single-thread xgboost'
    Start to build single-thread xgboost
    + make clean
    Makefile:31: MAKE [/Library/Developer/CommandLineTools/usr/bin/make] - checked OK
    rm -f -rf build build_plugin lib bin *~ */*~ */*/*~ */*/*/*~ */*.o */*/*.o */*/*/*.o #xgboost
    rm -f -rf build_tests *.gcov tests/cpp/xgboost_test
    cd R-package/src; rm -f -rf rabit src include dmlc-core amalgamation *.so *.dll; cd /private/var/folders/dp/cwkbsr654p10mfx8pn2zlyvm0000gn/T/pip-build-bonibbfq/xgboost/xgboost
    /bin/sh: line 0: cd: R-package/src: No such file or directory
    + make lib/libxgboost.dylib -j4 USE_OPENMP=0
    Makefile:31: MAKE [/Library/Developer/CommandLineTools/usr/bin/make] - checked OK
    Makefile:43: /private/var/folders/dp/cwkbsr654p10mfx8pn2zlyvm0000gn/T/pip-build-bonibbfq/xgboost/xgboost/dmlc-core/make/dmlc.mk: No such file or directory
    make: *** No rule to make target `/private/var/folders/dp/cwkbsr654p10mfx8pn2zlyvm0000gn/T/pip-build-bonibbfq/xgboost/xgboost/dmlc-core/make/dmlc.mk'.  Stop.
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/private/var/folders/dp/cwkbsr654p10mfx8pn2zlyvm0000gn/T/pip-build-bonibbfq/xgboost/setup.py", line 37, in <module>
        LIB_PATH = libpath['find_lib_path']()
      File "/private/var/folders/dp/cwkbsr654p10mfx8pn2zlyvm0000gn/T/pip-build-bonibbfq/xgboost/xgboost/libpath.py", line 49, in find_lib_path
        'List of candidates:\n' + ('\n'.join(dll_path)))
    XGBoostLibraryNotFound: Cannot find XGBoost Library in the candidate path, did you install compilers and run build.sh in root path?
    List of candidates:
    /private/var/folders/dp/cwkbsr654p10mfx8pn2zlyvm0000gn/T/pip-build-bonibbfq/xgboost/xgboost/libxgboost.dylib
    /private/var/folders/dp/cwkbsr654p10mfx8pn2zlyvm0000gn/T/pip-build-bonibbfq/xgboost/xgboost/../../lib/libxgboost.dylib
    /private/var/folders/dp/cwkbsr654p10mfx8pn2zlyvm0000gn/T/pip-build-bonibbfq/xgboost/xgboost/./lib/libxgboost.dylib
    /Users/mirco/Documents/comparative-arguments/ve/bin/../xgboost/libxgboost.dylib
    
    ----------------------------------------
Command "python setup.py egg_info" failed with error code 1 in /private/var/folders/dp/cwkbsr654p10mfx8pn2zlyvm0000gn/T/pip-build-bonibbfq/xgboost/
```

## Steps to reproduce
I followed the install instructions for OS X (installed gcc-5 and used pip)

## What have you tried?
I tried to install from source (with gcc-7 and clang) as described in the documentation which also fails with `clang: error: unsupported option '-fopenmp`
[from_source.txt](https://github.com/dmlc/xgboost/files/1674671/from_source.txt)

**Comment by ablx** [comment]
What worked:
```
git clone --recursive https://github.com/dmlc/xgboost.git
cd xgboost
./build.sh
cd python-package
python setup.py install
```

https://stackoverflow.com/questions/43327020/xgboostlibrarynotfound-cannot-find-xgboost-library-in-the-candidate-path-did-y
