### ISSUE TITLE
[jvm packages] java.lang.NoSuchMethodError: ml.dmlc.xgboost4j.LabeledPoint.fromSparseVector

### ISSUE THREAD

**Issue by Sinan81** [dmlc/xgboost#3106]
## Environment info
Operating System:
centos 6 & 7
Compiler:
gcc 7.2
Package used (python/R/jvm/C++):
jvm
`xgboost` version used:
0.7 & 0.8 latest snapshot

````
...
	at java.lang.Thread.run(Thread.java:748)
java.lang.NoSuchMethodError: ml.dmlc.xgboost4j.LabeledPoint.fromSparseVector(F[I[F)Lml/dmlc/xgboost4j/LabeledPoint;
	at org.aertslab.grnboost.util.ExpressionCSCMa$$$$a76aac699277cd72e6f3d5aaf37272d5$$$$ointsIterator$1.apply(BreezeUtils.scala:77)
...
````
## Steps to reproduce

1. compile xgboost
2. compile [GRNBoost](https://github.com/aertslab/GRNBoost/blob/master/docs/installation.md)
3. run like 
````
spark-submit --class org.aertslab.grnboost.GRNBoost --master local[*] --deploy-mode client --jars /path/to/xgboost4j-0.8-SNAPSHOT.jar /path/to/GRNBoost/target/scala-2.11/GRNBoost.jar infer --input inputfile.txt --output outputfile.txt --regulators regulators.txt --cfg-run
````

## What have you tried?

1. compiled on two different hosts to make sure it is not an OS related issue.

**Comment by Sinan81** [comment]
I figured out the problem which was that i was using xgboost*jar under xgboost/ as opposed to the one under local maven repository (at ~/.m2). 
This issue can be closed.
