### ISSUE TITLE
Hang during model.predict

### ISSUE THREAD

**Issue by pseudotensor** [dmlc/xgboost#3110]
gdb attach shows back trace of below.  Looks like openmp deadlock in PredLoopSpecalize().

```
#0  0x00007f048a3edd22 in ?? () from /usr/lib/x86_64-linux-gnu/libgomp.so.1
#1  0x00007f048a3ec889 in ?? () from /usr/lib/x86_64-linux-gnu/libgomp.so.1
#2  0x00007f0481b31d12 in xgboost::predictor::CPUPredictor::PredLoopSpecalize(xgboost::DMatrix*, std::vector<float, std::allocator<float> >*, xgboost::gbm::GBTreeModel const&, int, unsigned int, unsigned int) () from /home/jon/.pyenv/versions/3.6.4/lib/python3.6/site-packages/xgboost/libxgboost.so
#3  0x00007f0481b32912 in xgboost::predictor::CPUPredictor::PredictBatch(xgboost::DMatrix*, std::vector<float, std::allocator<float> >*, xgboost::gbm::GBTreeModel const&, int, unsigned int) () from /home/jon/.pyenv/versions/3.6.4/lib/python3.6/site-packages/xgboost/libxgboost.so
#4  0x00007f0481abc6e6 in xgboost::LearnerImpl::PredictRaw(xgboost::DMatrix*, std::vector<float, std::allocator<float> >*, unsigned int) const ()
   from /home/jon/.pyenv/versions/3.6.4/lib/python3.6/site-packages/xgboost/libxgboost.so
#5  0x00007f0481abc7bc in xgboost::LearnerImpl::Predict(xgboost::DMatrix*, bool, std::vector<float, std::allocator<float> >*, unsigned int, bool, bool, bool) const () from /home/jon/.pyenv/versions/3.6.4/lib/python3.6/site-packages/xgboost/libxgboost.so
#6  0x00007f0481a01f20 in XGBoosterPredict () from /home/jon/.pyenv/versions/3.6.4/lib/python3.6/site-packages/xgboost/libxgboost.so
#7  0x00007f05491bb356 in ffi_call_unix64 () at /tmp/python-build.20180124024630.24362/Python-3.6.4/Modules/_ctypes/libffi/src/x86/unix64.S:76
#8  0x00007f05491ba0b1 in ffi_call (cif=cif@entry=0x7f054a7e00b0, fn=fn@entry=0x7f0481a01e80 <XGBoosterPredict>, rvalue=rvalue@entry=0x7f054a7dff60, 
    avalue=avalue@entry=0x7f054a7dff20) at /tmp/python-build.20180124024630.24362/Python-3.6.4/Modules/_ctypes/libffi/src/x86/ffi64.c:525
#9  0x00007f05491b176f in _call_function_pointer (argcount=6, resmem=0x7f054a7dff60, restype=<optimized out>, atypes=<optimized out>, 
    avalues=0x7f054a7dff20, pProc=0x7f0481a01e80 <XGBoosterPredict>, flags=4353)
    at /tmp/python-build.20180124024630.24362/Python-3.6.4/Modules/_ctypes/callproc.c:809
#10 _ctypes_callproc (pProc=pProc@entry=0x7f0481a01e80 <XGBoosterPredict>, argtuple=argtuple@entry=0x7f048af22108, flags=4353, 
    argtypes=argtypes@entry=0x0, restype=0x7f053c082e88, checker=0x0)
    at /tmp/python-build.20180124024630.24362/Python-3.6.4/Modules/_ctypes/callproc.c:1147
#11 0x00007f05491a86d9 in PyCFuncPtr_call (self=<optimized out>, inargs=<optimized out>, kwds=<optimized out>)
    at /tmp/python-build.20180124024630.24362/Python-3.6.4/Modules/_ctypes/_ctypes.c:3962
#12 0x0000000000453442 in _PyObject_FastCallDict (func=0x7f048acde048, args=0x7f053eac6a90, nargs=6, kwargs=0x0) at Objects/abstract.c:2331
#13 0x0000000000540408 in call_function (pp_stack=pp_stack@entry=0x7f054a7e02f0, oparg=oparg@entry=6, kwnames=kwnames@entry=0x0) at Python/ceval.c:4848
#14 0x00000000005426bd in _PyEval_EvalFrameDefault (f=<optimized out>, throwflag=<optimized out>) at Python/ceval.c:3322
#15 0x00000000005402a5 in PyEval_EvalFrameEx (throwflag=0, f=0x7f053eac68a8) at Python/ceval.c:753
#16 _PyEval_EvalCodeWithName (_co=0x7f048a636c90, globals=globals@entry=0x7f04d48b55a0, locals=locals@entry=0x0, args=<optimized out>, argcount=2, 
    kwnames=kwnames@entry=0x7f04c046d588, kwargs=0x7f0464003a08, kwcount=5, kwstep=1, defs=0x7f04d4088480, defcount=5, kwdefs=0x0, closure=0x0, 
    name=0x7f0509f51ce0, qualname=0x7f04d4055670) at Python/ceval.c:4153
#17 0x0000000000540557 in fast_function (kwnames=0x7f04c046d588, nargs=<optimized out>, stack=<optimized out>, func=0x7f04d4058f28)
    at Python/ceval.c:4965
#18 call_function (pp_stack=pp_stack@entry=0x7f054a7e0558, oparg=oparg@entry=6, kwnames=kwnames@entry=0x7f04c046d570) at Python/ceval.c:4845
#19 0x000000000054232b in _PyEval_EvalFrameDefault (f=<optimized out>, throwflag=<optimized out>) at Python/ceval.c:3338
#20 0x00000000005402a5 in PyEval_EvalFrameEx (throwflag=0, f=0x7f0464003828) at Python/ceval.c:753
#21 _PyEval_EvalCodeWithName (_co=_co@entry=0x7f04d4057660, globals=globals@entry=0x7f04d48e6510, locals=locals@entry=0x0, 
    args=args@entry=0x7f054a7e07b0, argcount=argcount@entry=2, kwnames=kwnames@entry=0x7f04d49fad80, kwargs=0x7f04d49fad88, kwcount=6, kwstep=2, 
    defs=0x7f04c046d0b8, defcount=5, kwdefs=0x0, closure=0x0, name=0x7f0500b8a4f0, qualname=0x7f04d497e5d0) at Python/ceval.c:4153
#22 0x00000000005491da in _PyFunction_FastCallDict (func=func@entry=0x7f04d48cd598, args=args@entry=0x7f054a7e07b0, nargs=nargs@entry=2, 
    kwargs=kwargs@entry=0x7f04d48bfb40) at Python/ceval.c:5057
#23 0x0000000000453580 in _PyObject_FastCallDict (func=0x7f04d48cd598, args=0x7f054a7e07b0, nargs=2, kwargs=0x7f04d48bfb40) at Objects/abstract.c:2310
#24 0x000000000045367a in _PyObject_Call_Prepend (func=0x7f04d48cd598, obj=<optimized out>, args=0x7f04c0108c88, kwargs=0x7f04d48bfb40)
    at Objects/abstract.c:2373
#25 0x000000000045325c in PyObject_Call (func=func@entry=0x7f04d4074088, args=args@entry=0x7f04c0108c88, kwargs=kwargs@entry=0x7f04d48bfb40)
    at Objects/abstract.c:2261
#26 0x00000000005443ba in do_call_core (kwdict=0x7f04d48bfb40, callargs=0x7f04c0108c88, func=0x7f04d4074088) at Python/ceval.c:5093
#27 _PyEval_EvalFrameDefault (f=<optimized out>, throwflag=<optimized out>) at Python/ceval.c:3391
#28 0x00000000005402a5 in PyEval_EvalFrameEx (throwflag=0, f=0x7f0484000fc8) at Python/ceval.c:753
#29 _PyEval_EvalCodeWithName (_co=_co@entry=0x7f0500bc4390, globals=globals@entry=0x7f0500bb3ca8, locals=locals@entry=0x0, 
    args=args@entry=0x7f054a7e0b50, argcount=argcount@entry=2, kwnames=kwnames@entry=0x7f04d49faea0, kwargs=0x7f04d49faea8, kwcount=6, kwstep=2, 
    defs=0x0, defcount=0, kwdefs=0x0, closure=0x0, name=0x7f0500b8a470, qualname=0x7f0500b85858) at Python/ceval.c:4153
#30 0x00000000005491da in _PyFunction_FastCallDict (func=func@entry=0x7f04d59cc730, args=args@entry=0x7f054a7e0b50, nargs=nargs@entry=2, 
    kwargs=kwargs@entry=0x7f0489cfcbd0) at Python/ceval.c:5057

```

**Comment by hcho3** [comment]
Do you have a small script that re-produces the issue?

**Comment by hcho3** [comment]
@pseudotensor Can you re-open the issue when you have a reproducible script? Thanks!
