### ISSUE TITLE
[jvm-packages] compile xgboost jar failed

### ISSUE THREAD

**Issue by xixi2715** [dmlc/xgboost#3129]
## Environment info
Operating System: centos 6.6

Package used (python/R/jvm/C++): jvm

gcc version:4.8.2

##problem
I got error like this:
[INFO] --- exec-maven-plugin:1.6.0:exec (native) @ xgboost4j ---
-- Configuring done
-- Generating done
-- Build files have been written to: /home/zhaoyf/yinfeng/xgboost/build
[  1%] Building CXX object CMakeFiles/rabit.dir/rabit/src/allreduce_base.cc.o
In file included from /home/zhaoyf/yinfeng/xgboost/rabit/src/./../include/rabit/internal/../../dmlc/./logging.h:15,
                 from /home/zhaoyf/yinfeng/xgboost/rabit/src/./../include/rabit/internal/../../dmlc/io.h:14,
                 from /home/zhaoyf/yinfeng/xgboost/rabit/src/./../include/rabit/internal/../serializable.h:12,
                 from /home/zhaoyf/yinfeng/xgboost/rabit/src/./../include/rabit/internal/engine.h:10,
                 from /home/zhaoyf/yinfeng/xgboost/rabit/src/./allreduce_base.h:19,
                 from /home/zhaoyf/yinfeng/xgboost/rabit/src/allreduce_base.cc:14:
/home/zhaoyf/yinfeng/xgboost/rabit/src/./../include/rabit/internal/../../dmlc/././base.h:105: 附注：#pragma message：Will need g++-4.6 or higher to compile allthe features in dmlc-core, compile without c++0x, some features may be disabled
In file included from /home/zhaoyf/yinfeng/xgboost/rabit/src/./../include/rabit/internal/../../dmlc/io.h:14,
                 from /home/zhaoyf/yinfeng/xgboost/rabit/src/./../include/rabit/internal/../serializable.h:12,
                 from /home/zhaoyf/yinfeng/xgboost/rabit/src/./../include/rabit/internal/engine.h:10,
                 from /home/zhaoyf/yinfeng/xgboost/rabit/src/./allreduce_base.h:19,
                 from /home/zhaoyf/yinfeng/xgboost/rabit/src/allreduce_base.cc:14:
/home/zhaoyf/yinfeng/xgboost/rabit/src/./../include/rabit/internal/../../dmlc/./logging.h: In constructor ‘dmlc::LogCheckError::LogCheckError()’:
/home/zhaoyf/yinfeng/xgboost/rabit/src/./../include/rabit/internal/../../dmlc/./logging.h:66: 错误：‘nullptr’在此作用域中尚未声明
/home/zhaoyf/yinfeng/xgboost/rabit/src/./../include/rabit/internal/../../dmlc/./logging.h: In destructor ‘dmlc::LogCheckError::~LogCheckError()’:
/home/zhaoyf/yinfeng/xgboost/rabit/src/./../include/rabit/internal/../../dmlc/./logging.h:68: 错误：‘nullptr’在此作用域中尚未声明
/home/zhaoyf/yinfeng/xgboost/rabit/src/./../include/rabit/internal/../../dmlc/./logging.h: In member function ‘dmlc::LogCheckError::operator bool()’:
/home/zhaoyf/yinfeng/xgboost/rabit/src/./../include/rabit/internal/../../dmlc/./logging.h:69: 错误：‘nullptr’在此作用域中尚未声明
In file included from /home/zhaoyf/yinfeng/xgboost/rabit/src/./../include/rabit/internal/../../dmlc/io.h:14,
                 from /home/zhaoyf/yinfeng/xgboost/rabit/src/./../include/rabit/internal/../serializable.h:12,
                 from /home/zhaoyf/yinfeng/xgboost/rabit/src/./../include/rabit/internal/engine.h:10,
                 from /home/zhaoyf/yinfeng/xgboost/rabit/src/./allreduce_base.h:19,
                 from /home/zhaoyf/yinfeng/xgboost/rabit/src/allreduce_base.cc:14:
/home/zhaoyf/yinfeng/xgboost/rabit/src/./../include/rabit/internal/../../dmlc/./logging.h: In destructor ‘dmlc::LogMessageFatal::~LogMessageFatal()’:
/home/zhaoyf/yinfeng/xgboost/rabit/src/./../include/rabit/internal/../../dmlc/./logging.h:289: 错误：‘nullptr’在此作用域中尚未声明
gmake[2]: *** [CMakeFiles/rabit.dir/rabit/src/allreduce_base.cc.o] 错误 1
gmake[1]: *** [CMakeFiles/rabit.dir/all] 错误 2
gmake: *** [all] 错误 2
building Java wrapper
cd ..
mkdir -p build
cd build
cmake .. -DUSE_S3:BOOL=OFF -DUSE_OPENMP:BOOL=ON -DPLUGIN_UPDATER_GPU:BOOL=OFF -DUSE_AZURE:BOOL=OFF -DUSE_HDFS:BOOL=OFF -DJVM_BINDINGS:BOOL=ON
cmake --build . --config Release
Traceback (most recent call last):
  File "create_jni.py", line 89, in <module>
    run("cmake --build . --config Release")
  File "create_jni.py", line 51, in run
    subprocess.check_call(command, shell=True, **kwargs)
  File "/usr/local/lib/python2.7/subprocess.py", line 540, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command 'cmake --build . --config Release' returned non-zero exit status 2
[ERROR] Command execution failed.
org.apache.commons.exec.ExecuteException: Process exited with an error: 1 (Exit value: 1)
	at org.apache.commons.exec.DefaultExecutor.executeInternal(DefaultExecutor.java:404)
	at org.apache.commons.exec.DefaultExecutor.execute(DefaultExecutor.java:166)
	at org.codehaus.mojo.exec.ExecMojo.executeCommandLine(ExecMojo.java:804)
	at org.codehaus.mojo.exec.ExecMojo.executeCommandLine(ExecMojo.java:751)
	at org.codehaus.mojo.exec.ExecMojo.execute(ExecMojo.java:313)
	at org.apache.maven.plugin.DefaultBuildPluginManager.executeMojo(DefaultBuildPluginManager.java:134)
	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:207)
	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:153)
	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:145)
	at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject(LifecycleModuleBuilder.java:116)
	at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject(LifecycleModuleBuilder.java:80)
	at org.apache.maven.lifecycle.internal.builder.singlethreaded.SingleThreadedBuilder.build(SingleThreadedBuilder.java:51)
	at org.apache.maven.lifecycle.internal.LifecycleStarter.execute(LifecycleStarter.java:128)
	at org.apache.maven.DefaultMaven.doExecute(DefaultMaven.java:307)
	at org.apache.maven.DefaultMaven.doExecute(DefaultMaven.java:193)
	at org.apache.maven.DefaultMaven.execute(DefaultMaven.java:106)
	at org.apache.maven.cli.MavenCli.execute(MavenCli.java:863)
	at org.apache.maven.cli.MavenCli.doMain(MavenCli.java:288)
	at org.apache.maven.cli.MavenCli.main(MavenCli.java:199)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:606)
	at org.codehaus.plexus.classworlds.launcher.Launcher.launchEnhanced(Launcher.java:289)
	at org.codehaus.plexus.classworlds.launcher.Launcher.launch(Launcher.java:229)
	at org.codehaus.plexus.classworlds.launcher.Launcher.mainWithExitCode(Launcher.java:415)
	at org.codehaus.plexus.classworlds.launcher.Launcher.main(Launcher.java:356)
[INFO] ------------------------------------------------------------------------
[INFO] Reactor Summary:
[INFO]
[INFO] xgboost-jvm ........................................ SUCCESS [  6.653 s]
[INFO] xgboost4j .......................................... FAILURE [  3.503 s]
[INFO] xgboost4j-spark .................................... SKIPPED
[INFO] xgboost4j-flink .................................... SKIPPED
[INFO] xgboost4j-example .................................. SKIPPED
[INFO] ------------------------------------------------------------------------

I can understand how this happened, can anyone help me? Thanks ver much.

**Comment by Sinan81** [comment]
Does it compile without errors if you skip tests:
`mvn -DskipTests install`
What python version are you using? I would suggest python 2.7 or 3.4

**Comment by Sinan81** [comment]
Can you also try exporting preferred compilers beforehand so that cmake doesn't pick up the system gcc (4.4.7) as opposed to gcc 4.8.2
export CC=/path/to/preferred/gcc
export CXX=/path/to/preferred/c++

**Comment by Sinan81** [comment]
What version of cmake are you using?

**Comment by xixi2715** [comment]
@Sinan81 ，my cmake version is 3.6.1, the python version that I used is 2.7.10.  It still can't compile successfully by using mvn -DskipTests install. I will try to export CC and CXX path. Thanks very much.

**Comment by tqchen** [comment]
The build questions are now welcomed at https://discuss.xgboost.ai/
