### ISSUE TITLE
java.lang.NoSuchMethodError: org.apache.spark.scheduler.LiveListenerBus.removeListener

### ISSUE THREAD

**Issue by dimon777** [dmlc/xgboost#3208]
For bugs or installation issues, please provide the following information.
The more information you provide, the more easily we will be able to offer
help and advice.

## Environment info
Operating System: MacOSX $ 10.12.6

Compiler: gcc-7

Package used (python/R/jvm/C++): python

`xgboost` version used: commit b08762066113db81b6872dfcc2c8f253ac092da4

If installing from source, please provide 

1. The commit hash (`git rev-parse HEAD`)
b08762066113db81b6872dfcc2c8f253ac092da4

2. Logs will be helpful (If logs are large, please upload as attachment).

1. add [jvm-packages] in the title to make it quickly be identified

2. the gcc version and distribution

If you are using python package, please provide

1. The python version and distribution: python 3.6

2. The command to install `xgboost` if you are not installing from source

## Steps to reproduce

1. Compile xgboost from source on MacOSX
2. Install spark 2.3 standalone 
3. Install https://github.com/apache/incubator-toree
4. Install https://github.com/jupyter-scala/jupyter-scala
5. Fire up jupyter-notebook, choose apache toree scala kernel

Observe error below

## What have you tried?

1. Installing apache-toree via pip and compiling it form source

The problem seems to be caused by XGBoost.

ERROR:

numRound: Int = 10
numWorkers: Int = 4
paramMap: scala.collection.immutable.Map[String,Any] = Map(min_child_weight -> 3.0, base_score -> 0.005, colsample_bylevel -> 0.9, silent -> 1, seed -> 49, subsample -> 1.0, max_depth -> 10, objective -> reg:linear, eval_metric -> auc, eta -> 0.023, colsample_bytree -> 0.82)
java.lang.NoSuchMethodError: org.apache.spark.scheduler.LiveListenerBus.removeListener(Ljava/lang/Object;)V
  at org.apache.spark.SparkParallelismTracker.safeExecute(SparkParallelismTracker.scala:84)
  at org.apache.spark.SparkParallelismTracker.execute(SparkParallelismTracker.scala:107)
  at ml.dmlc.xgboost4j.scala.spark.XGBoost$$anonfun$trainDistributed$4.apply(XGBoost.scala:354)
  at ml.dmlc.xgboost4j.scala.spark.XGBoost$$anonfun$trainDistributed$4.apply(XGBoost.scala:337)
  at scala.collection.TraversableLike$$anonfun$map$1.apply(TraversableLike.scala:234)
  at scala.collection.TraversableLike$$anonfun$map$1.apply(TraversableLike.scala:234)
  at scala.collection.immutable.List.foreach(List.scala:381)
  at scala.collection.TraversableLike$class.map(TraversableLike.scala:234)
  at scala.collection.immutable.List.map(List.scala:285)
  at ml.dmlc.xgboost4j.scala.spark.XGBoost$.trainDistributed(XGBoost.scala:336)
  at ml.dmlc.xgboost4j.scala.spark.XGBoostEstimator.train(XGBoostEstimator.scala:139)
  at ml.dmlc.xgboost4j.scala.spark.XGBoostEstimator.train(XGBoostEstimator.scala:36)
  at org.apache.spark.ml.Predictor.fit(Predictor.scala:118)
  at ml.dmlc.xgboost4j.scala.spark.XGBoost$.trainWithDataFrame(XGBoost.scala:193)

**Comment by CodingCat** [comment]
you have either incompatible version of Spark/Scala

**Comment by wpopielarski** [comment]
looking in `jvm-xgboost/pom.xml` 2.2.1 spark version can be found. Just bump it to 2.3.0 and build I guess.

**Comment by belkacemlahouel** [comment]
Still not sure about how to fix it?
