### ISSUE TITLE
Exception in thread "main" java.lang.NoSuchMethodError: org.apache.spark.scheduler.LiveListenerBus.removeListener(Lorg/apache/spark/scheduler/SparkListenerInterface;)V

### ISSUE THREAD

**Issue by mumuyanyan** [dmlc/xgboost#3266]
The code is:
val xgboostModel = XGBoost
      .trainWithDataFrame(trainML, paramMap, numRound, 2,
        obj = null, eval = null, useExternalMemory = false, Float.NaN,
        "features", "Survived")
val testPrediction = xgboostModel.transform(testML)
testPrediction.show()

i have following problem

Exception in thread "main" java.lang.NoSuchMethodError: org.apache.spark.scheduler.LiveListenerBus.removeListener(Lorg/apache/spark/scheduler/SparkListenerInterface;)V
	at org.apache.spark.SparkParallelismTracker.safeExecute(SparkParallelismTracker.scala:84)
	at org.apache.spark.SparkParallelismTracker.execute(SparkParallelismTracker.scala:107)
	at ml.dmlc.xgboost4j.scala.spark.XGBoost$$anonfun$trainDistributed$4.apply(XGBoost.scala:354)
	at ml.dmlc.xgboost4j.scala.spark.XGBoost$$anonfun$trainDistributed$4.apply(XGBoost.scala:337)
	at scala.collection.TraversableLike$$anonfun$map$1.apply(TraversableLike.scala:234)
	at scala.collection.TraversableLike$$anonfun$map$1.apply(TraversableLike.scala:234)
	at scala.collection.immutable.List.foreach(List.scala:381)
	at scala.collection.TraversableLike$class.map(TraversableLike.scala:234)
	at scala.collection.immutable.List.map(List.scala:285)
	at ml.dmlc.xgboost4j.scala.spark.XGBoost$.trainDistributed(XGBoost.scala:336)
	at ml.dmlc.xgboost4j.scala.spark.XGBoostEstimator.train(XGBoostEstimator.scala:139)
	at ml.dmlc.xgboost4j.scala.spark.XGBoostEstimator.train(XGBoostEstimator.scala:36)
	at org.apache.spark.ml.Predictor.fit(Predictor.scala:96)
	at ml.dmlc.xgboost4j.scala.spark.XGBoost$.trainWithDataFrame(XGBoost.scala:193)
	at com.cmb.study.spark.ml.titanicTest$.main(titanicTest.scala:242)
	at com.cmb.study.spark.ml.titanicTest.main(titanicTest.scala)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at com.intellij.rt.execution.application.AppMain.main(AppMain.java:147)

**Comment by liushuainudt** [comment]
I have the same problem with the spark of version 2.1, but work find in the spark with version 2.3 .

**Comment by belkacemlahouel** [comment]
May be related to #3208

**Comment by hcho3** [comment]
Make sure to use Spark 2.3 or later. Any future installation / usage questions are welcomed at https://discuss.xgboost.ai/.
