### ISSUE TITLE
Scipy SVD is conflicting with XGBoost

### ISSUE THREAD

**Issue by hantingxie** [dmlc/xgboost#3378]
This issue is initially discovered in https://github.com/scikit-learn/scikit-learn/issues/8236.

On some devices (MacBook in my case), you may hit Segmanetation fault caused by the Scipy SVD if you import XGboost as well. There might be some low-level conflicts between the packing of these two libraries.

## Environment info
Operating System:
Darwin-16.7.0-x86_64-i386-64bit

Compiler:
Apple LLVM version 9.0.0 (clang-900.0.39.2)
Target: x86_64-apple-darwin16.7.0

Package used (python/R/jvm/C++):
Python

`xgboost` version used:
('XGBoost', '0.71')

`scipy` version used:
('SciPy', '0.19.1')

If installing from source, please provide 

If you are using python package, please provide

1. The python version and distribution
Python 2.7.13 :: Anaconda custom (64-bit)

2. The command to install `xgboost` if you are not installing from source
pip install xgboost

## Steps to reproduce
```python
import numpy as np
from scipy import linalg

import xgboost # this causes conflicts, remove this to pass !!!!

num_samples = [
    100,
    500
]

svds_to_use = [np.linalg.svd, linalg.svd]

for num_sample in num_samples:
    for svd_to_use in svds_to_use:
        print('using {}.{} on {} samples'.format(
            svd_to_use.__module__, svd_to_use.__name__, num_sample))
        x = np.random.sample((num_sample, 100))
        n_samples, n_features = x.shape
        # Center data
        mean = np.mean(x, axis=0)
        x_transformed = x - mean

        u, s, v = svd_to_use(x_transformed, full_matrices=False)
        print('passes')
```
## What have you tried?
1. I've noticed that using np.lingal.svd instead of scipy svd can solve the issue. It has been shown in the code above

2. Note that I can only reproduce this error with Python 2 but not on Python 3.

3. According to the discussions below, this issue only happens when you have 
3. I have tried to use gdb to get further details. Since that I'm using the Anaconda, there is no debugging symbols available, so the results might be useless:

```shell
Reading symbols from python...(no debugging symbols found)...done.
(gdb) run
Starting program: /Users/hanting/anaconda/envs/python2/bin/python seg_error.py
[New Thread 0x1903 of process 28604]
warning: unhandled dyld version (15)

Thread 2 received signal EXC_SOFTWARE, Software generated exception.
0x0000000100005000 in ?? ()
(gdb) bt
#0  0x0000000100005000 in ?? ()
#1  0x0000000100000000 in ?? ()
#2  0x0000000000000002 in ?? ()
#3  0x00007fff5fbffc10 in ?? ()
#4  0x00007fff5fbffc40 in ?? ()
#5  0x0000000000000000 in ?? ()
```

## Solution
The solution is that you should install both Scipy and XGBoost with either PyPi or Conda, but not a mixture of them. Please see the discussions at https://github.com/dmlc/xgboost/issues/3378#issuecomment-396895755.

**Comment by hantingxie** [comment]
Hi @rth , I think I narrowed this issue further down with your help!

Firstly, xgboost was installed from PyPi, but that doesn't seem to be the cause of the problem.

The interesting fact I noticed is that the Scipy I used was the pre-installed version (0.19.1-py27hf01dd8f_3) from conda. Even if I upgraded it to Scipy 1.1 (1.1.0-py27hcaad992_0), the issue still holds.

Surprisingly, when I uninstalled the conda Scipy and install a PyPi Scipy, everything starts to work. I tried three different versions of Scipy (0.19.1, 1.0, 1.1), All versions can pass. Therefore, this issue now becomes a conflict between the Conda Scipy and PyPI XGBoost now.

**Comment by rth** [comment]
> tqchen closed this 4 hours ago

Any comments why?  Do you think this not a valid or a resolved issue?

**Comment by hcho3** [comment]
This issue was closed due to the current triaging. We try to aggressive close issues from now on so opened issues can get attended to. I went ahead and re-opened it.

**Comment by rth** [comment]
Thanks for your explanations and maintenance work!

**Comment by hcho3** [comment]
Related issue: https://github.com/ContinuumIO/anaconda-issues/issues/8803

At the end of this link, a user claims that the issue was "solved".
