### ISSUE TITLE
/root/repo/xgboost/src/tree/updater_gpu_hist.cu:671: GPU plugin exception: GPU: an illegal memory access was encountered

### ISSUE THREAD

**Issue by pseudotensor** [dmlc/xgboost#3390]
```
import pickle
(model, X, y, sample_weight, kwargs) = pickle.load(open("ce87c8d2-34cb-4053-b891-df56827bc4e4_beforexgbobj.dat", "rb"))
model.fit(X, y, sample_weight=sample_weight, **kwargs)
```

Note, the pickle file is about 28GB and will create a very large core dump (>60GB) if you let it continue for a while after the failure message:

```
jon@mr-dl10:/data/jon/tmp.illegalaccess_realpickles/h2oai_experiment_rikilere$ python ce87c8d2-34cb-4053-b891-df56827bc4e4_beforexgbobj.dat.py
[13:39:18] Allocated 4212MB on [1] GeForce GTX 1080 Ti, 5639MB remaining.
[13:39:32] Allocated 2680MB on [1] GeForce GTX 1080 Ti, 3723MB remaining.
[13:39:32] Allocated 30MB on [1] GeForce GTX 1080 Ti, 3691MB remaining.
[13:39:33] /root/repo/xgboost/rabit/include/rabit/./internal/../../dmlc/./logging.h:300: [13:39:33] /root/repo/xgboost/src/tree/updater_gpu_hist.cu:671: GPU plugin exception: GPU: an illegal memory access was encountered


Stack trace returned 10 entries:
[bt] (0) /home/jon/.pyenv/versions/3.6.4/lib/python3.6/site-packages/xgboost/libxgboost.so(_ZN4dmlc15LogMessageFatalD2Ev+0x29) [0x7f0cf9bd24f9]
[bt] (1) /home/jon/.pyenv/versions/3.6.4/lib/python3.6/site-packages/xgboost/libxgboost.so(_ZN7xgboost4tree12GPUHistMaker6UpdateEPNS_16HostDeviceVectorINS_6detail20GradientPairInternalIfEEEEPNS_7DMatrixERKSt6vectorIPNS_7RegTreeESaISC_EE+0x447) [0x7f0cf9e0ade7]
[bt] (2) /home/jon/.pyenv/versions/3.6.4/lib/python3.6/site-packages/xgboost/libxgboost.so(_ZN7xgboost3gbm6GBTree13BoostNewTreesEPNS_16HostDeviceVectorINS_6detail20GradientPairInternalIfEEEEPNS_7DMatrixEiPSt6vectorISt10unique_ptrINS_7RegTreeESt14default_deleteISC_EESaISF_EE+0x80b) [0x7f0cf9c53deb]
[bt] (3) /home/jon/.pyenv/versions/3.6.4/lib/python3.6/site-packages/xgboost/libxgboost.so(_ZN7xgboost3gbm6GBTree7DoBoostEPNS_7DMatrixEPNS_16HostDeviceVectorINS_6detail20GradientPairInternalIfEEEEPNS_11ObjFunctionE+0x825) [0x7f0cf9c54825]
[bt] (4) /home/jon/.pyenv/versions/3.6.4/lib/python3.6/site-packages/xgboost/libxgboost.so(_ZN7xgboost11LearnerImpl13UpdateOneIterEiPNS_7DMatrixE+0x3e5) [0x7f0cf9c60165]
[bt] (5) /home/jon/.pyenv/versions/3.6.4/lib/python3.6/site-packages/xgboost/libxgboost.so(XGBoosterUpdateOneIter+0x2b) [0x7f0cf9bdd7ab]
[bt] (6) /usr/lib/x86_64-linux-gnu/libffi.so.6(ffi_call_unix64+0x4c) [0x7f0d61e10e40]
[bt] (7) /usr/lib/x86_64-linux-gnu/libffi.so.6(ffi_call+0x2eb) [0x7f0d61e108ab]
[bt] (8) /home/jon/.pyenv/versions/3.6.4/lib/python3.6/lib-dynload/_ctypes.cpython-36m-x86_64-linux-gnu.so(_ctypes_callproc+0x2cf) [0x7f0d62054d2f]
[bt] (9) /home/jon/.pyenv/versions/3.6.4/lib/python3.6/lib-dynload/_ctypes.cpython-36m-x86_64-linux-gnu.so(+0x8c69) [0x7f0d6204bc69]

Traceback (most recent call last):
  File "ce87c8d2-34cb-4053-b891-df56827bc4e4_beforexgbobj.dat.py", line 3, in <module>
    model.fit(X, y, sample_weight=sample_weight, **kwargs)
  File "/home/jon/.pyenv/versions/3.6.4/lib/python3.6/site-packages/xgboost/sklearn.py", line 314, in fit
    verbose_eval=verbose, xgb_model=xgb_model)
  File "/home/jon/.pyenv/versions/3.6.4/lib/python3.6/site-packages/xgboost/training.py", line 220, in train
    xgb_model=xgb_model, callbacks=callbacks)
  File "/home/jon/.pyenv/versions/3.6.4/lib/python3.6/site-packages/xgboost/training.py", line 79, in _train_internal
    bst.update(dtrain, i, obj)
  File "/home/jon/.pyenv/versions/3.6.4/lib/python3.6/site-packages/xgboost/core.py", line 1009, in update
    dtrain.handle))
  File "/home/jon/.pyenv/versions/3.6.4/lib/python3.6/site-packages/xgboost/core.py", line 131, in _check_call
    raise XGBoostError(_LIB.XGBGetLastError())
xgboost.core.XGBoostError: b'[13:39:33] /root/repo/xgboost/src/tree/updater_gpu_hist.cu:671: GPU plugin exception: GPU: an illegal memory access was encountered\n\n\nStack trace returned 10 entries:\n[bt] (0) /home/jon/.pyenv/versions/3.6.4/lib/python3.6/site-packages/xgboost/libxgboost.so(_ZN4dmlc15LogMessageFatalD2Ev+0x29) [0x7f0cf9bd24f9]\n[bt] (1) /home/jon/.pyenv/versions/3.6.4/lib/python3.6/site-packages/xgboost/libxgboost.so(_ZN7xgboost4tree12GPUHistMaker6UpdateEPNS_16HostDeviceVectorINS_6detail20GradientPairInternalIfEEEEPNS_7DMatrixERKSt6vectorIPNS_7RegTreeESaISC_EE+0x447) [0x7f0cf9e0ade7]\n[bt] (2) /home/jon/.pyenv/versions/3.6.4/lib/python3.6/site-packages/xgboost/libxgboost.so(_ZN7xgboost3gbm6GBTree13BoostNewTreesEPNS_16HostDeviceVectorINS_6detail20GradientPairInternalIfEEEEPNS_7DMatrixEiPSt6vectorISt10unique_ptrINS_7RegTreeESt14default_deleteISC_EESaISF_EE+0x80b) [0x7f0cf9c53deb]\n[bt] (3) /home/jon/.pyenv/versions/3.6.4/lib/python3.6/site-packages/xgboost/libxgboost.so(_ZN7xgboost3gbm6GBTree7DoBoostEPNS_7DMatrixEPNS_16HostDeviceVectorINS_6detail20GradientPairInternalIfEEEEPNS_11ObjFunctionE+0x825) [0x7f0cf9c54825]\n[bt] (4) /home/jon/.pyenv/versions/3.6.4/lib/python3.6/site-packages/xgboost/libxgboost.so(_ZN7xgboost11LearnerImpl13UpdateOneIterEiPNS_7DMatrixE+0x3e5) [0x7f0cf9c60165]\n[bt] (5) /home/jon/.pyenv/versions/3.6.4/lib/python3.6/site-packages/xgboost/libxgboost.so(XGBoosterUpdateOneIter+0x2b) [0x7f0cf9bdd7ab]\n[bt] (6) /usr/lib/x86_64-linux-gnu/libffi.so.6(ffi_call_unix64+0x4c) [0x7f0d61e10e40]\n[bt] (7) /usr/lib/x86_64-linux-gnu/libffi.so.6(ffi_call+0x2eb) [0x7f0d61e108ab]\n[bt] (8) /home/jon/.pyenv/versions/3.6.4/lib/python3.6/lib-dynload/_ctypes.cpython-36m-x86_64-linux-gnu.so(_ctypes_callproc+0x2cf) [0x7f0d62054d2f]\n[bt] (9) /home/jon/.pyenv/versions/3.6.4/lib/python3.6/lib-dynload/_ctypes.cpython-36m-x86_64-linux-gnu.so(+0x8c69) [0x7f0d6204bc69]\n'
[13:39:33] ======== Monitor: Learner ========
[13:39:33] GetGradient:  1.515164s
[13:39:33] PredictRaw:   0.286842s
[13:39:33] UpdateOneIter:        0.000000s
[13:39:33] Learner Lifetime:     74.047044s
terminate called after throwing an instance of 'thrust::system::system_error'
  what():  parallel_for failed: an illegal memory access was encountered
```

@RAMitchell 

This may be a different case than usual illegal memory access, but it's at least one.

**Comment by pseudotensor** [comment]
https://s3.amazonaws.com/h2o-datasets/h2o4gpu/data/ce87c8d2-34cb-4053-b891-df56827bc4e4_beforexgbobj.dat

**Comment by RAMitchell** [comment]
Im only able to reproduce this sometimes so no success in debugging so far. Will see if any similar issues come up.

**Comment by pseudotensor** [comment]
Ok, it happens commonly for larger data sets for us.

**Comment by pseudotensor** [comment]
This shouldn't be closed.  It's an urgent reproducible issue.

**Comment by hcho3** [comment]
This issue was closed due to the current triaging. We try to aggressive close issues from now on so opened issues like this can get attended to. I went ahead and re-opened it.

**Comment by trivialfis** [comment]
GPU Hist is quite different now.  Feel free to open a new issue if this error still persists.
