### ISSUE TITLE
Unexpected UnicodeEncodeError on .predict()

### ISSUE THREAD

**Issue by chinskiy** [dmlc/xgboost#3399]
## Environment info
Operating System: Linux

Compiler: 
gcc

Package used (python/R/jvm/C++):
Python. Bug reproducable in **Python 2 only**

`xgboost` version used:
0.71

## Reproducable example

```
# -*- coding: utf-8 -*-

import xgboost as xgb
import pandas as pd

params = {
    "booster": "gbtree",
}

X = pd.DataFrame([
    {u'z': 1, u'xé': 1},
    {u'z': 2, u'xé': 2},
    {u'z': 1, u'xé': 3},
])
y = pd.DataFrame([
    {u'y': 0},
    {u'y': 1},
    {u'y': 1},
])

dmatrix = xgb.DMatrix(X, label=y)


booster = xgb.train(params,
                    dmatrix)

data_test = pd.DataFrame([
    {u'z': 2, u'q': 3, u'y': 0}
])


dmatrix = xgb.DMatrix(data_test)

booster.predict(dmatrix)

```
## Actual behaviour
```
Traceback (most recent call last):
  File "bug.py", line 34, in <module>
    booster.predict(dmatrix)
  File "/usr/local/lib/python2.7/dist-packages/xgboost/core.py", line 1050, in predict
    self._validate_features(data)
  File "/usr/local/lib/python2.7/dist-packages/xgboost/core.py", line 1300, in _validate_features
    msg += ('\nexpected ' + ', '.join(str(s) for s in dat_missing) +
  File "/usr/local/lib/python2.7/dist-packages/xgboost/core.py", line 1300, in <genexpr>
    msg += ('\nexpected ' + ', '.join(str(s) for s in dat_missing) +
UnicodeEncodeError: 'ascii' codec can't encode character u'\xe9' in position 1: ordinal not in range(128)
```
## Expected behaviour
```
Traceback (most recent call last):
  File "bug.py", line 34, in <module>
    booster.predict(dmatrix)
  File "/usr/local/lib/python3.5/dist-packages/xgboost/core.py", line 1050, in predict
    self._validate_features(data)
  File "/usr/local/lib/python3.5/dist-packages/xgboost/core.py", line 1308, in _validate_features
    data.feature_names))
ValueError: feature_names mismatch: ['xé', 'z'] ['q', 'y', 'z']
expected xé in input data
training data did not have the following fields: q, y
```

**Comment by chinskiy** [comment]
@tqchen can you tell more details why this issue was closed?
