### ISSUE TITLE
python: .../site-packages/xgboost/./lib/libxgboost.so: cannot allocate memory in static TLS block

### ISSUE THREAD

**Issue by wookietreiber** [dmlc/xgboost#3425]
For bugs or installation issues, please provide the following information.
The more information you provide, the more easily we will be able to offer
help and advice.

## Environment info
Operating System:

```console
$ cat /etc/system-release
CentOS release 6.9 (Final)
```

Compiler:

```console
$ gcc --version
gcc (GCC) 4.9.4
```

Package used (python/R/jvm/C++): **python**

`xgboost` version used: 0.71 (required explicitly by [zamba](http://zamba.drivendata.org/docs/install.html))

If installing from source, please provide 

1. The commit hash (`git rev-parse HEAD`): 230cb9b78782df54445ce582452170460ba01bfd, i.e. v0.71

If you are using python package, please provide

1. The python version and distribution: 

    ```console
    $ python --version
    Python 3.6.0
    ```

2. The command to install `xgboost` if you are not installing from source

    ```console
    $ pip install xgboost==0.71
    ```

## Steps to reproduce

The software on our HPC cluster is installed to non-standard paths, e.g. xgboost is installed to `/usr/local/xgboost/0.71-1`. We make this software available via the [Lmod](http://lmod.readthedocs.io/en/latest/) software module system.

```console
$ module load python/3 gcc/4 xgboost/cpu
$ module list

Currently Loaded Modules:
  1) zlib/1.2.8-4      5) libedit/20160903-3.1-1   9) gcc/4/9.4-1
  2) openssl/1.0.2-1   6) sqlite/3.15.1-1         10) xgboost/cpu/0.71-1
  3) readline/6.3-2    7) bzip2/1.0.6-3
  4) ncurses/5.9-1     8) python/3/6.0-1



$ virtualenv xgboost-python
Using base prefix '/usr/local/python/3.6.0-1'
New python executable in /home/user/xgboost-python/bin/python
Installing setuptools, pip, wheel...done.
$ source xgboost-python/bin/activate
$ pip install xgboost==0.71
Collecting xgboost==0.71
Collecting numpy (from xgboost==0.71)
  Using cached https://files.pythonhosted.org/packages/68/1e/116ad560de97694e2d0c1843a7a0075cc9f49e922454d32f49a80eb6f1f2/numpy-1.14.5-cp36-cp36m-manylinux1_x86_64.whl
Collecting scipy (from xgboost==0.71)
  Using cached https://files.pythonhosted.org/packages/a8/0b/f163da98d3a01b3e0ef1cab8dd2123c34aee2bafbb1c5bffa354cc8a1730/scipy-1.1.0-cp36-cp36m-manylinux1_x86_64.whl
Installing collected packages: numpy, scipy, xgboost
Successfully installed numpy-1.14.5 scipy-1.1.0 xgboost-0.71
$ python
Python 3.6.0 (default, Jan 25 2017, 14:47:42)
[GCC 4.9.4] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import xgboost as xgb
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/user/xgboost-python/lib/python3.6/site-packages/xgboost/__init__.py", line 11, in <module>
    from .core import DMatrix, Booster
  File "/home/user/xgboost-python/lib/python3.6/site-packages/xgboost/core.py", line 115, in <module>
    _LIB = _load_lib()
  File "/home/user/xgboost-python/lib/python3.6/site-packages/xgboost/core.py", line 109, in _load_lib
    lib = ctypes.cdll.LoadLibrary(lib_path[0])
  File "/usr/local/python/3.6.0-1/lib/python3.6/ctypes/__init__.py", line 422, in LoadLibrary
    return self._dlltype(name)
  File "/usr/local/python/3.6.0-1/lib/python3.6/ctypes/__init__.py", line 344, in __init__
    self._handle = _dlopen(self._name, mode)
OSError: /home/user/xgboost-python/lib/python3.6/site-packages/xgboost/./lib/libxgboost.so: cannot allocate memory in static TLS block
```

**Comment by wookietreiber** [comment]
What works, however, is when I manually pre-load the library:

```console
$ LD_PRELOAD=/home/user/xgboost-python/lib/python3.6/site-packages/xgboost/./lib/libxgboost.so python
Python 3.6.0 (default, Jan 25 2017, 14:47:42)
[GCC 4.9.4] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import xgboost as xgb
>>> xgb.__name__
'xgboost'
```

Is there some compilation option or python trick to make this safe / auto-pre-load or is that something that should be added to the documentation?

**Comment by wookietreiber** [comment]
Note, that GCC has options regarding thread local storage (TLS): search in `man gcc` for **mtls**. It's possible, that one of these options might help regarding this issue.

**Comment by wookietreiber** [comment]
Just confirmed that this is reproducible on CentOS 7, too:

```console
$ cat /etc/system-release
CentOS Linux release 7.5.1804 (Core)
$ ml python/3 gcc/4 xgboost/cpu
$ virtualenv xgboost-python-centos-7
Using base prefix '/usr/local/python/3.6.0-1'
New python executable in /home/user/xgboost-python-centos-7/bin/python
Installing setuptools, pip, wheel...done.
$ source xgboost-python-centos-7/bin/activate
$ pip install xgboost==0.71
Collecting xgboost==0.71
Collecting numpy (from xgboost==0.71)
  Using cached https://files.pythonhosted.org/packages/68/1e/116ad560de97694e2d0c1843a7a0075cc9f49e922454d32f49a80eb6f1f2/numpy-1.14.5-cp36-cp36m-manylinux1_x86_64.whl
Collecting scipy (from xgboost==0.71)
  Using cached https://files.pythonhosted.org/packages/a8/0b/f163da98d3a01b3e0ef1cab8dd2123c34aee2bafbb1c5bffa354cc8a1730/scipy-1.1.0-cp36-cp36m-manylinux1_x86_64.whl
Installing collected packages: numpy, scipy, xgboost
Successfully installed numpy-1.14.5 scipy-1.1.0 xgboost-0.71
$ python
Python 3.6.0 (default, Jan 25 2017, 14:47:42)
[GCC 4.9.4] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import xgboost as xgb
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/user/xgboost-python-centos-7/lib/python3.6/site-packages/xgboost/__init__.py", line 11, in <module>
    from .core import DMatrix, Booster
  File "/home/user/xgboost-python-centos-7/lib/python3.6/site-packages/xgboost/core.py", line 115, in <module>
    _LIB = _load_lib()
  File "/home/user/xgboost-python-centos-7/lib/python3.6/site-packages/xgboost/core.py", line 109, in _load_lib
    lib = ctypes.cdll.LoadLibrary(lib_path[0])
  File "/usr/local/python/3.6.0-1/lib/python3.6/ctypes/__init__.py", line 422, in LoadLibrary
    return self._dlltype(name)
  File "/usr/local/python/3.6.0-1/lib/python3.6/ctypes/__init__.py", line 344, in __init__
    self._handle = _dlopen(self._name, mode)
OSError: /home/user/xgboost-python-centos-7/lib/python3.6/site-packages/xgboost/./lib/libxgboost.so: cannot allocate memory in static TLS block
```

**Comment by hcho3** [comment]
This issue was closed due to the current triaging. We try to aggressive close issues from now on so opened issues can get attended to. (Before, you'd get hundreds of issues not getting any responses.) I went ahead and re-opened it.

**Comment by tqchen** [comment]
We are moving the installation related discussions to https://discuss.xgboost.ai/, please make a separate post there. Thanks!

**Comment by hcho3** [comment]
@tqchen This looks more like a bug rather than installation question, no?

**Comment by tqchen** [comment]
Since this is more related to installation on a specific problem, and likely relates to the target platform get used,  I would encourage discussion on the forum instead :)

**Comment by tqchen** [comment]
We can always open issue to track the solution once we have steps on how to fix it
