### ISSUE TITLE
base_score error in XGBoost 0.8 and Spark 2.3.0

### ISSUE THREAD

**Issue by whitish** [dmlc/xgboost#3604]
scalaVersion := "2.11.8"
Spark version 2.3.0.
XGBoost version: 0.80 (`libraryDependencies += "ml.dmlc" % "xgboost4j-spark" % "0.80"`)
OS: Linux version 3.13.0-146-generic (buildd@lcy01-amd64-012) (gcc version 4.8.4 (Ubuntu 4.8.4-2ubuntu1~14.04.4) )

```
echo $LC_NUMERIC
en_US.UTF-8

```

The error arises when building a pipeline, e.g.:

```
    val xgbParams = Map("eta" -> 0.1f,
      "max_depth" -> 2,
      "objective" -> "binary:logistic",
      "num_round" -> 100,
      "num_workers" -> 1
    )

    val xgbClassifier = new XGBoostClassifier(xgbParams)
      .setFeaturesCol("features")
      .setLabelCol("Label")

    // Build the pipeline
    val pipeline = new Pipeline().setStages(Array(
      vectorAssembler,
      xgbClassifier))

   val model1 = pipeline.fit(data_train)

```

Error:
(Everything went well until step 'xgbClassifier')
```
18/08/17 16:29:56 WARN BlockManager: Putting block rdd_41_0 failed due to exception ml.dmlc.xgboost4j.java.XGBoostError: [16:29:56] /xgboost/src/objective/./regression_loss.h:62: Check failed: base_score > 0.0f && base_score < 1.0f base_score must be in (0,1) for logistic loss
Stack trace returned 6 entries:
[bt] (0) /tmp/libxgboost4j2116547509983459234.so(dmlc::StackTrace()+0x19d) [0x7f728ebcf15d]
[bt] (1) /tmp/libxgboost4j2116547509983459234.so(dmlc::LogMessageFatal::~LogMessageFatal()+0x18) [0x7f728ebd0008]
[bt] (2) /tmp/libxgboost4j2116547509983459234.so(xgboost::obj::LogisticRegression::ProbToMargin(float)+0x85) [0x7f728ecc41e5]
[bt] (3) /tmp/libxgboost4j2116547509983459234.so(xgboost::LearnerImpl::LazyInitModel()+0x48f) [0x7f728ec5ee0f]
[bt] (4) /tmp/libxgboost4j2116547509983459234.so(XGBoosterUpdateOneIter+0x52) [0x7f728ebd3032]
[bt] (5) [0x7f7315017a14]

18/08/17 16:29:56 WARN BlockManager: Block rdd_41_0 could not be removed as it was not found on disk or in memory
18/08/17 16:29:56 INFO RabitTracker$TrackerProcessLogger: Tracker Process ends with exit code 0
18/08/17 16:29:56 ERROR Executor: Exception in task 0.0 in stage 9.0 (TID 9)
ml.dmlc.xgboost4j.java.XGBoostError: [16:29:56] /xgboost/src/objective/./regression_loss.h:62: Check failed: base_score > 0.0f && base_score < 1.0f base_score must be in (0,1) for logistic loss

Stack trace returned 6 entries:
[bt] (0) /tmp/libxgboost4j2116547509983459234.so(dmlc::StackTrace()+0x19d) [0x7f728ebcf15d]
[bt] (1) /tmp/libxgboost4j2116547509983459234.so(dmlc::LogMessageFatal::~LogMessageFatal()+0x18) [0x7f728ebd0008]
[bt] (2) /tmp/libxgboost4j2116547509983459234.so(xgboost::obj::LogisticRegression::ProbToMargin(float)+0x85) [0x7f728ecc41e5]
[bt] (3) /tmp/libxgboost4j2116547509983459234.so(xgboost::LearnerImpl::LazyInitModel()+0x48f) [0x7f728ec5ee0f]
[bt] (4) /tmp/libxgboost4j2116547509983459234.so(XGBoosterUpdateOneIter+0x52) [0x7f728ebd3032]
[bt] (5) [0x7f7315017a14]


	at ml.dmlc.xgboost4j.java.XGBoostJNI.checkCall(XGBoostJNI.java:48)
	at ml.dmlc.xgboost4j.java.Booster.update(Booster.java:124)
	at ml.dmlc.xgboost4j.java.XGBoost.train(XGBoost.java:182)
	at ml.dmlc.xgboost4j.scala.XGBoost$.train(XGBoost.scala:64)
	at ml.dmlc.xgboost4j.scala.spark.XGBoost$$anonfun$buildDistributedBoosters$1.apply(XGBoost.scala:139)
	at ml.dmlc.xgboost4j.scala.spark.XGBoost$$anonfun$buildDistributedBoosters$1.apply(XGBoost.scala:116)
	at org.apache.spark.rdd.ZippedPartitionsRDD2.compute(ZippedPartitionsRDD.scala:89)
	at org.apache.spark.rdd.RDD.computeOrReadCheckpoint(RDD.scala:324)
	at org.apache.spark.rdd.RDD$$anonfun$7.apply(RDD.scala:337)
	at org.apache.spark.rdd.RDD$$anonfun$7.apply(RDD.scala:335)
	at org.apache.spark.storage.BlockManager$$anonfun$doPutIterator$1.apply(BlockManager.scala:1092)
	at org.apache.spark.storage.BlockManager$$anonfun$doPutIterator$1.apply(BlockManager.scala:1083)
	at org.apache.spark.storage.BlockManager.doPut(BlockManager.scala:1018)
	at org.apache.spark.storage.BlockManager.doPutIterator(BlockManager.scala:1083)
	at org.apache.spark.storage.BlockManager.getOrElseUpdate(BlockManager.scala:809)
	at org.apache.spark.rdd.RDD.getOrCompute(RDD.scala:335)
	at org.apache.spark.rdd.RDD.iterator(RDD.scala:286)
	at org.apache.spark.scheduler.ResultTask.runTask(ResultTask.scala:87)
	at org.apache.spark.scheduler.Task.run(Task.scala:109)
	at org.apache.spark.executor.Executor$TaskRunner.run(Executor.scala:345)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
18/08/17 16:29:56 WARN TaskSetManager: Lost task 0.0 in stage 9.0 (TID 9, localhost, executor driver): ml.dmlc.xgboost4j.java.XGBoostError: [16:29:56] /xgboost/src/objective/./regression_loss.h:62: Check failed: base_score > 0.0f && base_score < 1.0f base_score must be in (0,1) for logistic loss

```
And so on

**Comment by hcho3** [comment]
Try setting `LC_ALL` to `en_US.UTF-8`. Ensure that the cluster you are deploying XGBoost4J-Spark to has the same locale as well.

**Comment by whitish** [comment]
Right, the issue was in local cluster settings. Thank you!

**Comment by xino1010** [comment]
@hcho3 
nano ~/.bashrc
export LC_ALL=en_US.UTF-8
source ~/.bashrc
