### ISSUE TITLE
local variable 'lib' referenced before assignment

### ISSUE THREAD

**Issue by yananchen1989** [dmlc/xgboost#3616]
When I import xgboost in ipython of Anaconda, there comes the error:
```
UnboundLocalError                         Traceback (most recent call last)
<ipython-input-1-e528dc1a32ff> in <module>()
----> 1 import xgboost

/root/anaconda2/lib/python2.7/site-packages/xgboost/__init__.py in <module>()
      9 import os
     10
---> 11 from .core import DMatrix, Booster
     12 from .training import train, cv
     13 from . import rabit                   # noqa

/root/anaconda2/lib/python2.7/site-packages/xgboost/core.py in <module>()
    134
    135 # load the XGBoost library globally
--> 136 _LIB = _load_lib()
    137
    138

/root/anaconda2/lib/python2.7/site-packages/xgboost/core.py in _load_lib()
    126         except OSError:
    127             continue
--> 128     lib.XGBGetLastError.restype = ctypes.c_char_p
    129     lib.callback = _get_log_callback_func()
    130     if lib.XGBRegisterLogCallback(lib.callback) != 0:

UnboundLocalError: local variable 'lib' referenced before assignment
```
Any solutions ?

**Comment by hcho3** [comment]
Did you install from the source, or did you run `pip install xgboost`?

**Comment by yananchen1989** [comment]
@hcho3  I just use pip install method, without any other operations.

**Comment by hcho3** [comment]
Can you describe the OS environment? The binary wheel was built using CentOS 7.

**Comment by yananchen1989** [comment]
I also tried the 'make -j4' method as the official docs said.
My os is 
NAME="Ubuntu"
VERSION="14.04.5 LTS, Trusty Tahr"
ID=ubuntu
ID_LIKE=debian
PRETTY_NAME="Ubuntu 14.04.5 LTS"
VERSION_ID="14.04"

```
Makefile:31: MAKE [make] - checked OK
g++ -DDMLC_LOG_CUSTOMIZE=1 -std=c++11 -Wall -Wno-unknown-pragmas -Iinclude   -Idmlc-core/include -Irabit/include -I/include -O3 -funroll-loops -msse2 -fPIC -fopenmp -MM -MT build/learner.o src/learner.cc >build/learner.d
g++ -DDMLC_LOG_CUSTOMIZE=1 -std=c++11 -Wall -Wno-unknown-pragmas -Iinclude   -Idmlc-core/include -Irabit/include -I/include -O3 -funroll-loops -msse2 -fPIC -fopenmp -MM -MT build/logging.o src/logging.cc >build/logging.d
g++ -DDMLC_LOG_CUSTOMIZE=1 -std=c++11 -Wall -Wno-unknown-pragmas -Iinclude   -Idmlc-core/include -Irabit/include -I/include -O3 -funroll-loops -msse2 -fPIC -fopenmp -MM -MT build/c_api/c_api.o src/c_api/c_api.cc >build/c_api/c_api.d
g++ -DDMLC_LOG_CUSTOMIZE=1 -std=c++11 -Wall -Wno-unknown-pragmas -Iinclude   -Idmlc-core/include -Irabit/include -I/include -O3 -funroll-loops -msse2 -fPIC -fopenmp -MM -MT build/c_api/c_api_error.o src/c_api/c_api_error.cc >build/c_api/c_api_error.d
g++ -c -DDMLC_LOG_CUSTOMIZE=1 -std=c++11 -Wall -Wno-unknown-pragmas -Iinclude   -Idmlc-core/include -Irabit/include -I/include -O3 -funroll-loops -msse2 -fPIC -fopenmp src/c_api/c_api_error.cc -o build/c_api/c_api_error.o
g++ -c -DDMLC_LOG_CUSTOMIZE=1 -std=c++11 -Wall -Wno-unknown-pragmas -Iinclude   -Idmlc-core/include -Irabit/include -I/include -O3 -funroll-loops -msse2 -fPIC -fopenmp src/logging.cc -o build/logging.o
g++ -c -DDMLC_LOG_CUSTOMIZE=1 -std=c++11 -Wall -Wno-unknown-pragmas -Iinclude   -Idmlc-core/include -Irabit/include -I/include -O3 -funroll-loops -msse2 -fPIC -fopenmp src/c_api/c_api.cc -o build/c_api/c_api.o
g++ -c -DDMLC_LOG_CUSTOMIZE=1 -std=c++11 -Wall -Wno-unknown-pragmas -Iinclude   -Idmlc-core/include -Irabit/include -I/include -O3 -funroll-loops -msse2 -fPIC -fopenmp src/learner.cc -o build/learner.o
g++ -DDMLC_LOG_CUSTOMIZE=1 -std=c++11 -Wall -Wno-unknown-pragmas -Iinclude   -Idmlc-core/include -Irabit/include -I/include -O3 -funroll-loops -msse2 -fPIC -fopenmp -MM -MT build/common/common.o src/common/common.cc >build/common/common.d
g++ -c -DDMLC_LOG_CUSTOMIZE=1 -std=c++11 -Wall -Wno-unknown-pragmas -Iinclude   -Idmlc-core/include -Irabit/include -I/include -O3 -funroll-loops -msse2 -fPIC -fopenmp src/common/common.cc -o build/common/common.o
src/c_api/c_api.cc: In function 'int XGDMatrixCreateFromDT(void**, const char**, xgboost::bst_ulong, xgboost::bst_ulong, void**, int)':
src/c_api/c_api.cc:621:26: warning: comparison between signed and unsigned integer expressions [-Wsign-compare]
     for (auto j = 0; j < ncol; ++j) {
                          ^
g++ -DDMLC_LOG_CUSTOMIZE=1 -std=c++11 -Wall -Wno-unknown-pragmas -Iinclude   -Idmlc-core/include -Irabit/include -I/include -O3 -funroll-loops -msse2 -fPIC -fopenmp -MM -MT build/common/hist_util.o src/common/hist_util.cc >build/common/hist_util.d
g++ -c -DDMLC_LOG_CUSTOMIZE=1 -std=c++11 -Wall -Wno-unknown-pragmas -Iinclude   -Idmlc-core/include -Irabit/include -I/include -O3 -funroll-loops -msse2 -fPIC -fopenmp src/common/hist_util.cc -o build/common/hist_util.o
g++ -DDMLC_LOG_CUSTOMIZE=1 -std=c++11 -Wall -Wno-unknown-pragmas -Iinclude   -Idmlc-core/include -Irabit/include -I/include -O3 -funroll-loops -msse2 -fPIC -fopenmp -MM -MT build/common/host_device_vector.o src/common/host_device_vector.cc >build/common/host_device_vector.d
g++ -c -DDMLC_LOG_CUSTOMIZE=1 -std=c++11 -Wall -Wno-unknown-pragmas -Iinclude   -Idmlc-core/include -Irabit/include -I/include -O3 -funroll-loops -msse2 -fPIC -fopenmp src/common/host_device_vector.cc -o build/common/host_device_vector.o
g++ -DDMLC_LOG_CUSTOMIZE=1 -std=c++11 -Wall -Wno-unknown-pragmas -Iinclude   -Idmlc-core/include -Irabit/include -I/include -O3 -funroll-loops -msse2 -fPIC -fopenmp -MM -MT build/data/data.o src/data/data.cc >build/data/data.d
g++ -c -DDMLC_LOG_CUSTOMIZE=1 -std=c++11 -Wall -Wno-unknown-pragmas -Iinclude   -Idmlc-core/include -Irabit/include -I/include -O3 -funroll-loops -msse2 -fPIC -fopenmp src/data/data.cc -o build/data/data.o
g++ -DDMLC_LOG_CUSTOMIZE=1 -std=c++11 -Wall -Wno-unknown-pragmas -Iinclude   -Idmlc-core/include -Irabit/include -I/include -O3 -funroll-loops -msse2 -fPIC -fopenmp -MM -MT build/data/simple_csr_source.o src/data/simple_csr_source.cc >build/data/simple_csr_source.d
g++ -c -DDMLC_LOG_CUSTOMIZE=1 -std=c++11 -Wall -Wno-unknown-pragmas -Iinclude   -Idmlc-core/include -Irabit/include -I/include -O3 -funroll-loops -msse2 -fPIC -fopenmp src/data/simple_csr_source.cc -o build/data/simple_csr_source.o
g++ -DDMLC_LOG_CUSTOMIZE=1 -std=c++11 -Wall -Wno-unknown-pragmas -Iinclude   -Idmlc-core/include -Irabit/include -I/include -O3 -funroll-loops -msse2 -fPIC -fopenmp -MM -MT build/data/simple_dmatrix.o src/data/simple_dmatrix.cc >build/data/simple_dmatrix.d
g++ -c -DDMLC_LOG_CUSTOMIZE=1 -std=c++11 -Wall -Wno-unknown-pragmas -Iinclude   -Idmlc-core/include -Irabit/include -I/include -O3 -funroll-loops -msse2 -fPIC -fopenmp src/data/simple_dmatrix.cc -o build/data/simple_dmatrix.o
g++ -DDMLC_LOG_CUSTOMIZE=1 -std=c++11 -Wall -Wno-unknown-pragmas -Iinclude   -Idmlc-core/include -Irabit/include -I/include -O3 -funroll-loops -msse2 -fPIC -fopenmp -MM -MT build/data/sparse_page_dmatrix.o src/data/sparse_page_dmatrix.cc >build/data/sparse_page_dmatrix.d
g++ -c -DDMLC_LOG_CUSTOMIZE=1 -std=c++11 -Wall -Wno-unknown-pragmas -Iinclude   -Idmlc-core/include -Irabit/include -I/include -O3 -funroll-loops -msse2 -fPIC -fopenmp src/data/sparse_page_dmatrix.cc -o build/data/sparse_page_dmatrix.o
g++ -DDMLC_LOG_CUSTOMIZE=1 -std=c++11 -Wall
```

**Comment by hcho3** [comment]
Under the `lib/` directory, you should be able to find the shared library `libxgboost.so`. Now in Python shell, try running
```python
import ctypes
lib = ctypes.cdll.LoadLibrary('./lib/libxgboost.so')
```
What do you get?

**Comment by yananchen1989** [comment]
@hcho3 
```
In [1]: import ctypes
   ...: lib = ctypes.cdll.LoadLibrary('./lib/libxgboost.so')
   ...:
---------------------------------------------------------------------------
OSError                                   Traceback (most recent call last)
<ipython-input-1-a13b00577bc1> in <module>()
      1 import ctypes
----> 2 lib = ctypes.cdll.LoadLibrary('./lib/libxgboost.so')

/root/anaconda2/lib/python2.7/ctypes/__init__.pyc in LoadLibrary(self, name)
    442
    443     def LoadLibrary(self, name):
--> 444         return self._dlltype(name)
    445
    446 cdll = LibraryLoader(CDLL)

/root/anaconda2/lib/python2.7/ctypes/__init__.pyc in __init__(self, name, mode, handle, use_errno, use_last_error)
    364
    365         if handle is None:
--> 366             self._handle = _dlopen(self._name, mode)
    367         else:
    368             self._handle = handle

OSError: ./lib/libxgboost.so: wrong ELF class: ELFCLASS64
```

```
root@a21-14:/home/sdev/yanan/xgboost# make -j4
Makefile:31: MAKE [make] - checked OK
make: Nothing to be done for `all'.
```

**Comment by yananchen1989** [comment]
By the way, I have installed anaconda firstly.

**Comment by hcho3** [comment]
Are you using 32-bit system?

**Comment by hcho3** [comment]
Or is your Python 32-bits?

**Comment by yananchen1989** [comment]
@hcho3  Linux a21-14 4.4.0-133-generic #159~14.04.1-Ubuntu SMP Fri Aug 10 08:17:48 UTC 2018 x86_64 x86_64 x86_64 GNU/Linux

**Comment by yananchen1989** [comment]
Python 2.7.15

**Comment by hcho3** [comment]
Run
```python
import struct
print( 8 * struct.calcsize("P"))'
```
to see if your Python is 32-bit or 64-bit?

**Comment by yananchen1989** [comment]
32 bit  @hcho3

**Comment by hcho3** [comment]
Got it. You'll have to uninstall your current Anaconda and install the 64-bit Anaconda. Your Python is compiled for 32-bit and thus cannot load `libxgboost.so`, which is 64-bit.

**Comment by hcho3** [comment]
I will submit a pull request to display a better error message.

**Comment by yananchen1989** [comment]
@hcho3  I have installed 64-bit anaconda now.
I go to the path of xgboost execute `make -j4`
```
Makefile:31: MAKE [make] - checked OK
make: Nothing to be done for `all'.
```

What should I do? remove the xgboost folder and git clone again ?

**Comment by yananchen1989** [comment]
New python version: Python 3.6.5

**Comment by hcho3** [comment]
You should be able to run `pip install xgboost` now

**Comment by yananchen1989** [comment]
@hcho3  Thanks. Works fine.

**Comment by alexwwang** [comment]
I met the same problem under venv in [python:3.6.6-slim docker image](https://github.com/docker-library/python/blob/8350b865d28bc0f4a05111398392ec701d449058/3.6/stretch/slim/Dockerfile).
Neither compile to install nor pip install, it does not work and give out this error.
Seems it's not a problem of 32-bit in this situation.

**Comment by hcho3** [comment]
@alexwwang Can you run
```python
import ctypes
lib = ctypes.cdll.LoadLibrary('./lib/libxgboost.so')
```

**Comment by alexwwang** [comment]
I am so confused by the result as shown in the screenshot.

![image](https://user-images.githubusercontent.com/856746/44624635-bc218e80-a925-11e8-876a-3ab96bbe9550.png)

**Comment by alexwwang** [comment]
even failed with the so file under python package dir:
![image](https://user-images.githubusercontent.com/856746/44624681-0ce5b700-a927-11e8-92f7-34f159fdc20a.png)

**Comment by hcho3** [comment]
```
OSError: libgomp.so.1: cannot open shared object file: No such file or directory
```
It looks like `libxgboost.so` is missing. XGBoost uses OpenMP for multi-threading. Try installing [libomp-dev package](https://packages.debian.org/stretch/libomp-dev).

**Comment by alexwwang** [comment]
Thanks. I will have a try. I though it was the fault of missing libgomp1 pack so I am dealing with it.

**Comment by hcho3** [comment]
Actually, yes, libgomp1 would be a better fit, since XGBoost was compiled with GCC

**Comment by hcho3** [comment]
I wonder if static linking with libgomp1 would be desirable

**Comment by alexwwang** [comment]
Thanks. I am trying it. I modified my docker img and am now install xgboost to make a try again.

**Comment by alexwwang** [comment]
Not sure if static linking would be desirable. Wait for a second pls.

**Comment by alexwwang** [comment]
Seems no error prompts again.
Maybe it would work in the production.
I'll have a try then.
Thanks for your hints.~

![image](https://user-images.githubusercontent.com/856746/44624894-a617cc00-a92d-11e8-80d6-990c48c4ef9a.png)

**Comment by alexwwang** [comment]
Some more words as a hint for this error:
It seems that xgboost need to load resource from libxgboost.so when importing and initializing. This error actually means that this process failed so it appears that the local variable 'lib' referenced before assignment. 

Maybe it would be better and clearer to give some hint when failed to load the resource file. But before that, if anyone others met this error again, please check if the resource file `libxgboost.so` could be loaded successfully.

Thanks to @hcho3 again for providing above hints to help me understand what happened about this error.

**Comment by hcho3** [comment]
@alexwwang No problem. Your post should help me write a better error message.

**Comment by alexwwang** [comment]
Glad to be helpful. 😊

**Comment by cerebrumaize** [comment]
Got the same problem when import xgboost. My venv is py3.7, windows 10, x64. I installed from the source. The error is also fail to import libxgboost.so when executing `lib = ctypes.cdll.LoadLibrary('./lib/libxgboost.so')`

**Comment by hcho3** [comment]
@cerebrumaize Can you run
```python
import ctypes
lib = ctypes.cdll.LoadLibrary('./lib/libxgboost.so')
```
and see what kind of error message you are getting?

**Comment by hcho3** [comment]
@cerebrumaize For Windows, try installing Microsoft Visual C++ Redistributable.

**Comment by cerebrumaize** [comment]
```
>>> import ctypes
>>> lib = ctypes.cdll.LoadLibrary('./lib/libxgboost.so')
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "D:\python3d7\lib\ctypes\__init__.py", line 434, in LoadLibrary
    return self._dlltype(name)
  File "D:\python3d7\lib\ctypes\__init__.py", line 356, in __init__
    self._handle = _dlopen(self._name, mode)
OSError: [WinError 126] The specified module could not be found
```
* error message for `LoadLibrary` is listed above, just cannot find `so` file.
* And I did install Microsoft Visual C++ Redistributable for Visual Studio 2017 and Microsoft Visual C++ 2008/2010/2012/2013/2017 Redistributable.

**Comment by hcho3** [comment]
@cerebrumaize I meant to say `./lib/xgboost.dll`, not `./lib/libxgboost.so`.

**Comment by cerebrumaize** [comment]
```
>>> import ctypes
>>> lib = ctypes.cdll.LoadLibrary('./lib/xgboost.dll')
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "D:\python3d7\lib\ctypes\__init__.py", line 434, in LoadLibrary
    return self._dlltype(name)
  File "D:\python3d7\lib\ctypes\__init__.py", line 356, in __init__
    self._handle = _dlopen(self._name, mode)
OSError: [WinError 126] The specified module could not be found
```
sorry, it's similar though.

**Comment by hcho3** [comment]
@cerebrumaize Try running `ctypes.cdll.LoadLibrary('D:\workspaces\py3d7env\Lib\site-packages\xgboost-0.80-py3.7.egg\xgboost\xgboost.dll')`?

**Comment by hcho3** [comment]
@cerebrumaize Also, what compiler are you using?

**Comment by cerebrumaize** [comment]
```
>>> ctypes.cdll.LoadLibrary('D:\workspaces\py3d7env\Lib\site-packages\xgboost-0.80-py3.7.egg\xgboost\xgboost.dll')
  File "<stdin>", line 1
SyntaxError: (unicode error) 'unicodeescape' codec can't decode bytes in position 40-41: truncated \xXX escape
```
My compiler is latest mingw64's mingw32-make.exe

**Comment by hcho3** [comment]
@cerebrumaize We'll need to escape backslashes:
```python
ctypes.cdll.LoadLibrary('D:\\workspaces\\py3d7env\\Lib\\site-packages\\xgboost-0.80-py3.7.egg\\xgboost\\xgboost.dll')
```

**Comment by cerebrumaize** [comment]
```
>>> ctypes.cdll.LoadLibrary('D:\\workspaces\\py3d7env\\Lib\\site-packages\\xgboost-0.80-py3.7.egg\\xgboost\\xgboost.dll')
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "D:\python3d7\lib\ctypes\__init__.py", line 434, in LoadLibrary
    return self._dlltype(name)
  File "D:\python3d7\lib\ctypes\__init__.py", line 356, in __init__
    self._handle = _dlopen(self._name, mode)
OSError: [WinError 193] %1 is not a valid Win32 application
```
It says the dll is not a valid Win32 application.

**Comment by hcho3** [comment]
@cerebrumaize Make sure you are running 64-bit Python by running
```python
import struct
print(8 * struct.calcsize("P"))
```
You should get 64. Also, make sure to use 64-bit MinGW.

**Comment by cerebrumaize** [comment]
You are right. I was using 32 py. After I reinstalled, xgboost is loaded successfully. Thank you very much for your time and patience.

**Comment by lokercy** [comment]
Up until this step I have similar output as @cerebrumaize 

> @cerebrumaize We'll need to escape backslashes:
> 
> ```python
> ctypes.cdll.LoadLibrary('D:\\workspaces\\py3d7env\\Lib\\site-packages\\xgboost-0.80-py3.7.egg\\xgboost\\xgboost.dll')
> ```

But then I get a different error message:

`>>> ctypes.cdll.LoadLibrary('D:\\workspaces\\py3d7env\\Lib\\site-packages\\xgboost-0.80-py3.7.egg\\xgboost\\xgboost.dll')
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "C:\Python37\lib\ctypes\__init__.py", line 434, in LoadLibrary
    return self._dlltype(name)
  File "C:\Python37\lib\ctypes\__init__.py", line 356, in __init__
    self._handle = _dlopen(self._name, mode)
OSError: [WinError 126] The specified module could not be found`

and I'm already at 64-bit python:
'
>>> import struct
>>> print(8 * struct.calcsize("P"))
64'

Is there anything else that could lead to this?

**Comment by hcho3** [comment]
@lokercy Try installing Microsoft Visual C++ Redistributable.

**Comment by lokercy** [comment]
@hcho3 yeah... That's it. And it also fix my other issue with lightGBM. Thanks!
