### ISSUE TITLE
different prediction result - xgboost 0.6 / 0.8

### ISSUE THREAD

**Issue by Ravisik** [dmlc/xgboost#3664]
Hey guys,
I recently updated my Xgboost (0.6 to 0.8). 
Basically, I just want to keep on using an old model trained using the version 0.6. It seems that I have to retrain the model for it. 
```
XGBClassifier(base_score=0.4, colsample_bylevel=1, colsample_bytree=0.7,
                          gamma=0.00, learning_rate=0.3, max_delta_step=0.5, max_depth=6,
                          min_child_weight=0.5, missing=None, n_estimators=250,
                          objective='reg:logistic', reg_alpha=0.8, reg_lambda=1,
                          scale_pos_weight=0.10, seed=0, silent=True, subsample=0.7)
```

The problem is that the new trained model gives different prediction ! Do you have some clue about this? 

Thanks a lot,
Florian

**Comment by hcho3** [comment]
> It seems that I have to retrain the model for it

Can you elaborate more about this? How was your old model saved?

**Comment by Ravisik** [comment]
Hi,
Thanks for your quick response.
I save my old model in a pickle, so I can't use it with the new version : 
```
test_dmatrix = DMatrix(data, missing=self.missing, nthread=self.n_jobs)
AttributeError: 'XGBClassifier' object has no attribute 'n_jobs'
```
There was no "n_jobs" in the version 0.6, it seems to cause the error. It is why I thought about training again a model using xgboost 0.8 keeping the same parameters.

**Comment by hcho3** [comment]
Yes, `n_jobs` parameter was added to later versions, to be more consistent with scikit-learn. Re-training with the same parameters generally doesn't guarantee that you'd get the same model, so it's better to find a way to make use of your existing model. 

For now, you should install XGBoost 0.60 and run
```python
import pickle
import xgboost

# Unpickle model
with open('./your_model.pkl', 'rb') as f:
  bst = pickle.load(f)

# Export model as binary format
bst._Booster.save_model('your_model_binary.model')
```
Now you should be able to use the model in binary format with XGBoost 0.80.

In general, the binary format (given by `Booster.save_model()`) provides for better backward compatibility than `pickle`. In the future, you should use `XGBClassifier.save_model()` method to preserve the model.

**Comment by Ravisik** [comment]
Ok, thanks a lot for your help!

**Comment by Ravisik** [comment]
oups...
I can't install the 0.6 version anymore...
`pip install xgboost==0.6a2`

```
Makefile:105: recipe for target 'build/data/sparse_page_writer.o' failed
    make: *** [build/data/sparse_page_writer.o] Error 1
    make: *** Waiting for unfinished jobs....
    Successfully build single-thread xgboost
    If you want multi-threaded version
    See additional instructions in doc/build.md
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-install-Lskrjq/xgboost/setup.py", line 29, in <module>
        LIB_PATH = libpath['find_lib_path']()
      File "/tmp/pip-install-Lskrjq/xgboost/xgboost/libpath.py", line 45, in find_lib_path
        'List of candidates:\n' + ('\n'.join(dll_path)))
    __builtin__.XGBoostLibraryNotFound: Cannot find XGBoost Libarary in the candicate path, did you install compilers and run build.sh in root path?
    List of candidates:
    /tmp/pip-install-Lskrjq/xgboost/xgboost/libxgboost.so
    /tmp/pip-install-Lskrjq/xgboost/xgboost/../../lib/libxgboost.so
    /tmp/pip-install-Lskrjq/xgboost/xgboost/./lib/libxgboost.so
    
    ----------------------------------------
Command "python setup.py egg_info" failed with error code 1 in /tmp/pip-install-Lskrjq/xgboost/
```
I tried using directly the source code, same problem... I tried installing version 0.4 / 0.8, no problem...

**Comment by hcho3** [comment]
Try running
```
git clone --recursive https://github.com/dmlc/xgboost -b v0.60
cd xgboost
make
```

**Comment by Ravisik** [comment]
Thanks for your time. I got this error: 

```
In file included from src/data/sparse_page_writer.cc:8:0:
src/data/./sparse_batch_page.h:238:46: error: ‘function’ is not a member of ‘std’
                                         std::function<SparsePage::Format* ()> > {
                                              ^~~~~~~~
src/data/./sparse_batch_page.h:238:46: note: suggested alternative: ‘is_function’
                                         std::function<SparsePage::Format* ()> > {
                                              ^~~~~~~~
                                              is_function
src/data/./sparse_batch_page.h:238:46: error: ‘function’ is not a member of ‘std’
src/data/./sparse_batch_page.h:238:46: note: suggested alternative: ‘is_function’
                                         std::function<SparsePage::Format* ()> > {
                                              ^~~~~~~~
                                              is_function
src/data/./sparse_batch_page.h:238:77: error: template argument 2 is invalid
                                       std::function<SparsePage::Format* ()> > {
                                                                           ^
src/data/./sparse_batch_page.h:238:79: error: expected ‘{’ before ‘>’ token
                                       std::function<SparsePage::Format* ()> > {
                                                                             ^
src/data/./sparse_batch_page.h:238:79: error: expected unqualified-id before ‘>’ token
Makefile:97: recipe for target 'build/data/sparse_page_writer.o' failed
make: *** [build/data/sparse_page_writer.o] Error 1

```

**Comment by hcho3** [comment]
What's your GCC version?

**Comment by Ravisik** [comment]
Hi,
gcc is already the newest version (4:7.3.0-3ubuntu2)

**Comment by Ravisik** [comment]
Hi,
gcc version 7.3.0 (Ubuntu 7.3.0-16ubuntu3)

**Comment by hcho3** [comment]
Can you post the full log of `make`?

**Comment by Ravisik** [comment]
```
g++ -std=c++0x -Wall -O3 -msse2  -Wno-unknown-pragmas -funroll-loops -Iinclude   -Idmlc-core/include -Irabit/include -fPIC -fopenmp -MM -MT build/logging.o src/logging.cc >build/logging.d
g++ -c -std=c++0x -Wall -O3 -msse2  -Wno-unknown-pragmas -funroll-loops -Iinclude   -Idmlc-core/include -Irabit/include -fPIC -fopenmp -c src/logging.cc -o build/logging.o
g++ -std=c++0x -Wall -O3 -msse2  -Wno-unknown-pragmas -funroll-loops -Iinclude   -Idmlc-core/include -Irabit/include -fPIC -fopenmp -MM -MT build/learner.o src/learner.cc >build/learner.d
g++ -c -std=c++0x -Wall -O3 -msse2  -Wno-unknown-pragmas -funroll-loops -Iinclude   -Idmlc-core/include -Irabit/include -fPIC -fopenmp -c src/learner.cc -o build/learner.o
g++ -std=c++0x -Wall -O3 -msse2  -Wno-unknown-pragmas -funroll-loops -Iinclude   -Idmlc-core/include -Irabit/include -fPIC -fopenmp -MM -MT build/common/common.o src/common/common.cc >build/common/common.d
g++ -c -std=c++0x -Wall -O3 -msse2  -Wno-unknown-pragmas -funroll-loops -Iinclude   -Idmlc-core/include -Irabit/include -fPIC -fopenmp -c src/common/common.cc -o build/common/common.o
g++ -std=c++0x -Wall -O3 -msse2  -Wno-unknown-pragmas -funroll-loops -Iinclude   -Idmlc-core/include -Irabit/include -fPIC -fopenmp -MM -MT build/metric/metric.o src/metric/metric.cc >build/metric/metric.d
g++ -c -std=c++0x -Wall -O3 -msse2  -Wno-unknown-pragmas -funroll-loops -Iinclude   -Idmlc-core/include -Irabit/include -fPIC -fopenmp -c src/metric/metric.cc -o build/metric/metric.o
g++ -std=c++0x -Wall -O3 -msse2  -Wno-unknown-pragmas -funroll-loops -Iinclude   -Idmlc-core/include -Irabit/include -fPIC -fopenmp -MM -MT build/metric/rank_metric.o src/metric/rank_metric.cc >build/metric/rank_metric.d
g++ -c -std=c++0x -Wall -O3 -msse2  -Wno-unknown-pragmas -funroll-loops -Iinclude   -Idmlc-core/include -Irabit/include -fPIC -fopenmp -c src/metric/rank_metric.cc -o build/metric/rank_metric.o
g++ -std=c++0x -Wall -O3 -msse2  -Wno-unknown-pragmas -funroll-loops -Iinclude   -Idmlc-core/include -Irabit/include -fPIC -fopenmp -MM -MT build/metric/elementwise_metric.o src/metric/elementwise_metric.cc >build/metric/elementwise_metric.d
g++ -c -std=c++0x -Wall -O3 -msse2  -Wno-unknown-pragmas -funroll-loops -Iinclude   -Idmlc-core/include -Irabit/include -fPIC -fopenmp -c src/metric/elementwise_metric.cc -o build/metric/elementwise_metric.o
g++ -std=c++0x -Wall -O3 -msse2  -Wno-unknown-pragmas -funroll-loops -Iinclude   -Idmlc-core/include -Irabit/include -fPIC -fopenmp -MM -MT build/metric/multiclass_metric.o src/metric/multiclass_metric.cc >build/metric/multiclass_metric.d
g++ -c -std=c++0x -Wall -O3 -msse2  -Wno-unknown-pragmas -funroll-loops -Iinclude   -Idmlc-core/include -Irabit/include -fPIC -fopenmp -c src/metric/multiclass_metric.cc -o build/metric/multiclass_metric.o
g++ -std=c++0x -Wall -O3 -msse2  -Wno-unknown-pragmas -funroll-loops -Iinclude   -Idmlc-core/include -Irabit/include -fPIC -fopenmp -MM -MT build/objective/multiclass_obj.o src/objective/multiclass_obj.cc >build/objective/multiclass_obj.d
g++ -c -std=c++0x -Wall -O3 -msse2  -Wno-unknown-pragmas -funroll-loops -Iinclude   -Idmlc-core/include -Irabit/include -fPIC -fopenmp -c src/objective/multiclass_obj.cc -o build/objective/multiclass_obj.o
g++ -std=c++0x -Wall -O3 -msse2  -Wno-unknown-pragmas -funroll-loops -Iinclude   -Idmlc-core/include -Irabit/include -fPIC -fopenmp -MM -MT build/objective/objective.o src/objective/objective.cc >build/objective/objective.d
g++ -c -std=c++0x -Wall -O3 -msse2  -Wno-unknown-pragmas -funroll-loops -Iinclude   -Idmlc-core/include -Irabit/include -fPIC -fopenmp -c src/objective/objective.cc -o build/objective/objective.o
g++ -std=c++0x -Wall -O3 -msse2  -Wno-unknown-pragmas -funroll-loops -Iinclude   -Idmlc-core/include -Irabit/include -fPIC -fopenmp -MM -MT build/objective/rank_obj.o src/objective/rank_obj.cc >build/objective/rank_obj.d
g++ -c -std=c++0x -Wall -O3 -msse2  -Wno-unknown-pragmas -funroll-loops -Iinclude   -Idmlc-core/include -Irabit/include -fPIC -fopenmp -c src/objective/rank_obj.cc -o build/objective/rank_obj.o
g++ -std=c++0x -Wall -O3 -msse2  -Wno-unknown-pragmas -funroll-loops -Iinclude   -Idmlc-core/include -Irabit/include -fPIC -fopenmp -MM -MT build/objective/regression_obj.o src/objective/regression_obj.cc >build/objective/regression_obj.d
g++ -c -std=c++0x -Wall -O3 -msse2  -Wno-unknown-pragmas -funroll-loops -Iinclude   -Idmlc-core/include -Irabit/include -fPIC -fopenmp -c src/objective/regression_obj.cc -o build/objective/regression_obj.o
g++ -std=c++0x -Wall -O3 -msse2  -Wno-unknown-pragmas -funroll-loops -Iinclude   -Idmlc-core/include -Irabit/include -fPIC -fopenmp -MM -MT build/data/sparse_page_dmatrix.o src/data/sparse_page_dmatrix.cc >build/data/sparse_page_dmatrix.d
g++ -c -std=c++0x -Wall -O3 -msse2  -Wno-unknown-pragmas -funroll-loops -Iinclude   -Idmlc-core/include -Irabit/include -fPIC -fopenmp -c src/data/sparse_page_dmatrix.cc -o build/data/sparse_page_dmatrix.o
g++ -std=c++0x -Wall -O3 -msse2  -Wno-unknown-pragmas -funroll-loops -Iinclude   -Idmlc-core/include -Irabit/include -fPIC -fopenmp -MM -MT build/data/sparse_page_source.o src/data/sparse_page_source.cc >build/data/sparse_page_source.d
g++ -c -std=c++0x -Wall -O3 -msse2  -Wno-unknown-pragmas -funroll-loops -Iinclude   -Idmlc-core/include -Irabit/include -fPIC -fopenmp -c src/data/sparse_page_source.cc -o build/data/sparse_page_source.o
g++ -std=c++0x -Wall -O3 -msse2  -Wno-unknown-pragmas -funroll-loops -Iinclude   -Idmlc-core/include -Irabit/include -fPIC -fopenmp -MM -MT build/data/sparse_page_writer.o src/data/sparse_page_writer.cc >build/data/sparse_page_writer.d
g++ -c -std=c++0x -Wall -O3 -msse2  -Wno-unknown-pragmas -funroll-loops -Iinclude   -Idmlc-core/include -Irabit/include -fPIC -fopenmp -c src/data/sparse_page_writer.cc -o build/data/sparse_page_writer.o
In file included from src/data/sparse_page_writer.cc:8:0:
src/data/./sparse_batch_page.h:238:46: error: ‘function’ is not a member of ‘std’
                                         std::function<SparsePage::Format* ()> > {
                                              ^~~~~~~~
src/data/./sparse_batch_page.h:238:46: note: suggested alternative: ‘is_function’
                                         std::function<SparsePage::Format* ()> > {
                                              ^~~~~~~~
                                              is_function
src/data/./sparse_batch_page.h:238:46: error: ‘function’ is not a member of ‘std’
src/data/./sparse_batch_page.h:238:46: note: suggested alternative: ‘is_function’
                                         std::function<SparsePage::Format* ()> > {
                                              ^~~~~~~~
                                              is_function
src/data/./sparse_batch_page.h:238:77: error: template argument 2 is invalid
                                       std::function<SparsePage::Format* ()> > {
                                                                           ^
src/data/./sparse_batch_page.h:238:79: error: expected ‘{’ before ‘>’ token
                                       std::function<SparsePage::Format* ()> > {
                                                                             ^
src/data/./sparse_batch_page.h:238:79: error: expected unqualified-id before ‘>’ token
Makefile:97: recipe for target 'build/data/sparse_page_writer.o' failed
make: *** [build/data/sparse_page_writer.o] Error 1

```

**Comment by hcho3** [comment]
@Ravisik The 0.6 version had problem building with GCC 7. Later versions (0.7x and 0.80) build successfully with GCC 7 and 8. For now, can you install GCC 5? You can run
```
CC=gcc-5 CXX=g++-5 pip install --no-cache-dir xgboost==0.6a2
```
to install XGBoost 0.6 with GCC 5

**Comment by Ravisik** [comment]
Hey, I still have the same problem with this command.
```

/*.o */*/*.o */*/*/*.o xgboost
    g++-5 -std=c++0x -Wall -O3 -msse2  -Wno-unknown-pragmas -funroll-loops -Iinclude   -Idmlc-core/include -Irabit/include -fPIC -fopenmp -MM -MT build/logging.o src/logging.cc >build/logging.d
    g++-5 -std=c++0x -Wall -O3 -msse2  -Wno-unknown-pragmas -funroll-loops -Iinclude   -Idmlc-core/include -Irabit/include -fPIC -fopenmp -MM -MT build/learner.o src/learner.cc >build/learner.d
    g++-5 -std=c++0x -Wall -O3 -msse2  -Wno-unknown-pragmas -funroll-loops -Iinclude   -Idmlc-core/include -Irabit/include -fPIC -fopenmp -MM -MT build/common/common.o src/common/common.cc >build/common/common.d
    g++-5 -std=c++0x -Wall -O3 -msse2  -Wno-unknown-pragmas -funroll-loops -Iinclude   -Idmlc-core/include -Irabit/include -fPIC -fopenmp -MM -MT build/metric/metric.o src/metric/metric.cc >build/metric/metric.d
    /bin/sh: 1: g++-5: not found
    /bin/sh: 1: g++-5: not found
    Makefile:105: recipe for target 'build/logging.o' failed
    make: *** [build/logging.o] Error 127
    make: *** Waiting for unfinished jobs....
    Makefile:105: recipe for target 'build/learner.o' failed
    make: *** [build/learner.o] Error 127
    /bin/sh: 1: g++-5: not found
    Makefile:105: recipe for target 'build/common/common.o' failed
    make: *** [build/common/common.o] Error 127
    /bin/sh: 1: g++-5: not found
    Makefile:105: recipe for target 'build/metric/metric.o' failed
    make: *** [build/metric/metric.o] Error 127
    -----------------------------
    Building multi-thread xgboost failed
    Start to build single-thread xgboost
    rm -f -rf build build_plugin lib bin *~ */*~ */*/*~ */*/*/*~ */*.o */*/*.o */*/*/*.o xgboost
    g++-5 -std=c++0x -Wall -O3 -msse2  -Wno-unknown-pragmas -funroll-loops -Iinclude   -Idmlc-core/include -Irabit/include -fPIC -fopenmp -MM -MT build/logging.o src/logging.cc >build/logging.d
    g++-5 -std=c++0x -Wall -O3 -msse2  -Wno-unknown-pragmas -funroll-loops -Iinclude   -Idmlc-core/include -Irabit/include -fPIC -fopenmp -MM -MT build/learner.o src/learner.cc >build/learner.d
    g++-5 -std=c++0x -Wall -O3 -msse2  -Wno-unknown-pragmas -funroll-loops -Iinclude   -Idmlc-core/include -Irabit/include -fPIC -fopenmp -MM -MT build/common/common.o src/common/common.cc >build/common/common.d
    /bin/sh: 1: g++-5: not found
    g++-5 -std=c++0x -Wall -O3 -msse2  -Wno-unknown-pragmas -funroll-loops -Iinclude   -Idmlc-core/include -Irabit/include -fPIC -fopenmp -MM -MT build/metric/metric.o src/metric/metric.cc >build/metric/metric.d
    /bin/sh: 1: g++-5: not found
    Makefile:105: recipe for target 'build/logging.o' failed
    make: *** [build/logging.o] Error 127
    make: *** Waiting for unfinished jobs....
    Makefile:105: recipe for target 'build/learner.o' failed
    make: *** [build/learner.o] Error 127
    /bin/sh: 1: g++-5: not found
    Makefile:105: recipe for target 'build/common/common.o' failed
    make: *** [build/common/common.o] Error 127
    /bin/sh: 1: g++-5: not found
    Makefile:105: recipe for target 'build/metric/metric.o' failed
    make: *** [build/metric/metric.o] Error 127
    Successfully build single-thread xgboost
    If you want multi-threaded version
    See additional instructions in doc/build.md
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-install-5G8gZm/xgboost/setup.py", line 29, in <module>
        LIB_PATH = libpath['find_lib_path']()
      File "/tmp/pip-install-5G8gZm/xgboost/xgboost/libpath.py", line 45, in find_lib_path
        'List of candidates:\n' + ('\n'.join(dll_path)))
    __builtin__.XGBoostLibraryNotFound: Cannot find XGBoost Libarary in the candicate path, did you install compilers and run build.sh in root path?
    List of candidates:
    /tmp/pip-install-5G8gZm/xgboost/xgboost/libxgboost.so
    /tmp/pip-install-5G8gZm/xgboost/xgboost/../../lib/libxgboost.so
    /tmp/pip-install-5G8gZm/xgboost/xgboost/./lib/libxgboost.so
    
    ----------------------------------------
Command "python setup.py egg_info" failed with error code 1 in /tmp/pip-install-5G8gZm/xgboost/

```

**Comment by Ravisik** [comment]
thanks mate, perfect!
