### ISSUE TITLE
Get NoClassDefFoundError when running xgboost on yarn demo

### ISSUE THREAD

**Issue by edwardzjl** [dmlc/xgboost#3737]
## environment

* **java**: java1.8.0
* **hadoop**: hadoop-2.6.0-cdh5.11.1
* **CLASSPATH**: /opt/cloudera/parcels/CDH/lib/hadoop-mapreduce:/opt/cloudera/parcels/CDH/lib/hadoop/hadoop-common.jar:/usr/java/current/lib:.:
* **LD_LIBRARY_PATH**: /root/programs/xgboost/lib:/opt/cloudera/parcels/CDH/lib64:/usr/java/current/jre/lib/amd64/server:

## problem

followed the instructions on [tutorial](https://xgboost.readthedocs.io/en/latest/tutorials/aws_yarn.html)

after compiling, test/distributed/runtests.sh works fine, but demo job fails immediately after job submitted.

job log says:

> Error: A JNI error has occurred, please check your installation and try again
Exception in thread "main" java.lang.NoClassDefFoundError: org/apache/hadoop/io/DataOutputBuffer
	at java.lang.Class.getDeclaredMethods0(Native Method)
	at java.lang.Class.privateGetDeclaredMethods(Class.java:2701)
	at java.lang.Class.privateGetMethodRecursive(Class.java:3048)
	at java.lang.Class.getMethod0(Class.java:3018)
	at java.lang.Class.getMethod(Class.java:1784)
	at sun.launcher.LauncherHelper.validateMainClass(LauncherHelper.java:544)
	at sun.launcher.LauncherHelper.checkAndLoadMain(LauncherHelper.java:526)
Caused by: java.lang.ClassNotFoundException: org.apache.hadoop.io.DataOutputBuffer
	at java.net.URLClassLoader.findClass(URLClassLoader.java:381)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
	at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:338)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
	... 7 more

Is there sth wrong with my CLASSPATH or LD_LIBRARY_PATH settings?

I'm using cdh5.11.1 and the file architecture is different from apache-hadoop. Maybe it's the reason?

**Comment by hcho3** [comment]
Make sure that HDFS is enabled when compiling XGBoost4J. Modify `jvm-packages/create_jni.py` to replace `"USE_HDFS": "OFF"` with `"USE_HDFS": "ON"`.

**Comment by edwardzjl** [comment]
> 
> 
> Make sure that HDFS is enabled when compiling XGBoost4J. Modify `jvm-packages/create_jni.py` to replace `"USE_HDFS": "OFF"` with `"USE_HDFS": "ON"`.

recompiled but still getting the same error.

**Comment by hcho3** [comment]
```
Exception in thread "main" java.lang.NoClassDefFoundError: org/apache/hadoop/io/DataOutputBuffer
```
I think you want to use Apache Hadoop.

**Comment by hcho3** [comment]
Does using Apache Hadoop change anything?

**Comment by hcho3** [comment]
@edwardzjl Interesting. For now, the XGBoost4J doc should be updated to require Apache Hadoop.
