### ISSUE TITLE
[jvm-packages] RabitTracker Issue Xgboost-Spark

### ISSUE THREAD

**Issue by favila88** [dmlc/xgboost#3748]
Hi all,
I have been testing xgboost spark version during a while. So now I am facing the an error after some training iterations. My main problem is when I increase the the number of workers, it fails randomly. Only to clarify I am setting a correct number of workers with one is less than the executors that I am using. The training in some cases works, but in other cases it fail with the follow message:

[Stage 41:>                                                        (0 + 7) / 10][ERROR] [10/03/2018 15:25:04.555] [RabitTracker-akka.actor.default-dispatcher-15] [LocalActorRitTracker)] guardian failed, shutting down system
java.lang.AssertionError: assertion failed
        at scala.Predef$.assert(Predef.scala:156)
        at ml.dmlc.xgboost4j.scala.rabit.handler.WorkerDependencyResolver$$anonfun$receive$2.applyOrElse(RabitTrackerHandler.scala:298)
        at akka.actor.Actor$class.aroundReceive(Actor.scala:467)
        at ml.dmlc.xgboost4j.scala.rabit.handler.WorkerDependencyResolver.aroundReceive(RabitTrackerHandler.scala:264)
        at akka.actor.ActorCell.receiveMessage(ActorCell.scala:516)
        at akka.actor.ActorCell.invoke(ActorCell.scala:487)
        at akka.dispatch.Mailbox.processMailbox(Mailbox.scala:238)
        at akka.dispatch.Mailbox.run(Mailbox.scala:220)
        at akka.dispatch.ForkJoinExecutorConfigurator$AkkaForkJoinTask.exec(AbstractDispatcher.scala:397)
        at scala.concurrent.forkjoin.ForkJoinTask.doExec(ForkJoinTask.java:260)
        at scala.concurrent.forkjoin.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1339)
        at scala.concurrent.forkjoin.ForkJoinPool.runWorker(ForkJoinPool.java:1979)
        at scala.concurrent.forkjoin.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:107)

[ERROR] [10/03/2018 15:25:04.556] [RabitTracker-akka.actor.default-dispatcher-15] [akka://RabitTracker/user] assertion failed
java.lang.AssertionError: assertion failed
        at scala.Predef$.assert(Predef.scala:156)
        at ml.dmlc.xgboost4j.scala.rabit.handler.WorkerDependencyResolver$$anonfun$receive$2.applyOrElse(RabitTrackerHandler.scala:298)
        at akka.actor.Actor$class.aroundReceive(Actor.scala:467)
        at ml.dmlc.xgboost4j.scala.rabit.handler.WorkerDependencyResolver.aroundReceive(RabitTrackerHandler.scala:264)
        at akka.actor.ActorCell.receiveMessage(ActorCell.scala:516)
        at akka.actor.ActorCell.invoke(ActorCell.scala:487)
        at akka.dispatch.Mailbox.processMailbox(Mailbox.scala:238)
        at akka.dispatch.Mailbox.run(Mailbox.scala:220)
        at akka.dispatch.ForkJoinExecutorConfigurator$AkkaForkJoinTask.exec(AbstractDispatcher.scala:397)
        at scala.concurrent.forkjoin.ForkJoinTask.doExec(ForkJoinTask.java:260)
        at scala.concurrent.forkjoin.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1339)
        at scala.concurrent.forkjoin.ForkJoinPool.runWorker(ForkJoinPool.java:1979)
        at scala.concurrent.forkjoin.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:107)

I tried use what documentation suggest adding this parameters: 

- xgbClassifier.setCheckpointInterval(500)
- xgbClassifier.setCheckpointPath("./")

But it give me same error.

Here the parameters that I am using:

 `val paramMap = Map("num_workers" -> "10", "eta" -> "0.01", "max_depth" -> "3", "silent" -> "0","objective" -> "binary:logistic", "eval_metric" -> "logloss", "num_round" ->20000, "checkpoint_path" -> "./", "checkpoint_interval" -> 500)`

Please can you help with this issue.

Thanks,

**Comment by hcho3** [comment]
Maybe you are not able to secure all the workers you need? Currently, the workers will need to stay alive throughout all training; if one of them is killed, the whole training fails.

**Comment by hcho3** [comment]
@chenqin Have you run into a similar issue?

**Comment by CodingCat** [comment]
You can test with master branch...the issue should have been fixed

**Comment by chenqin** [comment]
As Nan pointed out, latest master or upcoming 0.81 should include fix. This particular case should be xgboost4j or xgboost4j spark related. Likely shutdown race condition. I would suggest also grep "Assert", "FD", "retry" in failed spark executor log as well. Some times it can surface rabit worker native layer assertion failures...
