### ISSUE TITLE
[jvm-packages] xgboost4j-flink example :DistTrainWithFlink  train error

### ISSUE THREAD

**Issue by neulyp** [dmlc/xgboost#3786]
用的是0.80的版本，然后trainData 和testData 是读到数据了，其他代码没有改变。怎么解决呀

ml.dmlc.xgboost4j.java.XGBoostError: [15:27:46] /xgboost/src/objective/regression_obj.cc:43: Check failed: info.labels_.size() != 0U (0 vs. 0) label set cannot be empty

Stack trace returned 6 entries:
[bt] (0) /tmp/libxgboost4j2193021052893805346.so(dmlc::StackTrace()+0x19d) [0x7fddbc4c715d]
[bt] (1) /tmp/libxgboost4j2193021052893805346.so(dmlc::LogMessageFatal::~LogMessageFatal()+0x18) [0x7fddbc4c8008]
[bt] (2) /tmp/libxgboost4j2193021052893805346.so(xgboost::obj::RegLossObj<xgboost::obj::LogisticClassification>::GetGradient(xgboost::HostDeviceVector<float>*, xgboost::MetaInfo const&, int, xgboost::HostDeviceVector<xgboost::detail::GradientPairInternal<float> >*)+0xce) [0x7fddbc5bd51e]
[bt] (3) /tmp/libxgboost4j2193021052893805346.so(xgboost::LearnerImpl::UpdateOneIter(int, xgboost::DMatrix*)+0x385) [0x7fddbc557a85]
[bt] (4) /tmp/libxgboost4j2193021052893805346.so(XGBoosterUpdateOneIter+0x35) [0x7fddbc4cb015]
[bt] (5) [0x7fddd9017a14]

	at ml.dmlc.xgboost4j.java.XGBoostJNI.checkCall(XGBoostJNI.java:48)
	at ml.dmlc.xgboost4j.java.Booster.update(Booster.java:124)
	at ml.dmlc.xgboost4j.java.XGBoost.train(XGBoost.java:182)
	at ml.dmlc.xgboost4j.scala.XGBoost$.train(XGBoost.scala:64)
	at ml.dmlc.xgboost4j.scala.flink.XGBoost$MapFunction.mapPartition(XGBoost.scala:60)
	at org.apache.flink.runtime.operators.MapPartitionDriver.run(MapPartitionDriver.java:103)
	at org.apache.flink.runtime.operators.BatchTask.run(BatchTask.java:503)
	at org.apache.flink.runtime.operators.BatchTask.invoke(BatchTask.java:368)
	at org.apache.flink.runtime.taskmanager.Task.run(Task.java:703)
	at java.lang.Thread.run(Thread.java:745)

**Comment by chenqin** [comment]
hey, do you have code and data sample to reproduce, have you set label columns?

**Comment by hcho3** [comment]
@neulyp Any updates?
