### ISSUE TITLE
[jvm-packages] Some errors in model training

### ISSUE THREAD

**Issue by haitongwan** [dmlc/xgboost#3824]
When I train the model, there's some errors.
Error Meassages:

ERROR ApplicationMaster: User class threw exception: ml.dmlc.xgboost4j.java.XGBoostError: XGBoostModel training failed
ml.dmlc.xgboost4j.java.XGBoostError: XGBoostModel training failed
	at ml.dmlc.xgboost4j.scala.spark.XGBoost$.ml$dmlc$xgboost4j$scala$spark$XGBoost$$postTrackerReturnProcessing(XGBoost.scala:283)
	at ml.dmlc.xgboost4j.scala.spark.XGBoost$$anonfun$trainDistributed$4.apply(XGBoost.scala:240)
	at ml.dmlc.xgboost4j.scala.spark.XGBoost$$anonfun$trainDistributed$4.apply(XGBoost.scala:222)
	at scala.collection.TraversableLike$$anonfun$map$1.apply(TraversableLike.scala:234)
	at scala.collection.TraversableLike$$anonfun$map$1.apply(TraversableLike.scala:234)
	at scala.collection.immutable.List.foreach(List.scala:381)
	at scala.collection.TraversableLike$class.map(TraversableLike.scala:234)
	at scala.collection.immutable.List.map(List.scala:285)
	at ml.dmlc.xgboost4j.scala.spark.XGBoost$.trainDistributed(XGBoost.scala:221)
	at ml.dmlc.xgboost4j.scala.spark.XGBoostClassifier.train(XGBoostClassifier.scala:191)
	at ml.dmlc.xgboost4j.scala.spark.XGBoostClassifier.train(XGBoostClassifier.scala:48)
	at org.apache.spark.ml.Predictor.fit(Predictor.scala:118)
	at com.qunar.train.xgboostdemo$.main(xgboostdemo.scala:53)
	at com.qunar.train.xgboostdemo.main(xgboostdemo.scala)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.apache.spark.deploy.yarn.ApplicationMaster$$anon$4.run(ApplicationMaster.scala:721)

I am looking forward to your reply.

**Comment by hcho3** [comment]
Do you have more log? Normally, you'd have some log for training failure.

**Comment by haitongwan** [comment]
18/10/24 17:09:54 INFO ContextCleaner: Cleaned accumulator 74
18/10/24 17:09:54 INFO ContextCleaner: Cleaned accumulator 194
18/10/24 17:09:54 INFO RabitTracker: Tracker Process ends with exit code 1
18/10/24 17:09:54 INFO XGBoostSpark: Rabit returns with exit code 1
18/10/24 17:09:54 ERROR ApplicationMaster: User class threw exception: ml.dmlc.xgboost4j.java.XGBoostError: XGBoostModel training failed
ml.dmlc.xgboost4j.java.XGBoostError: XGBoostModel training failed
	at ml.dmlc.xgboost4j.scala.spark.XGBoost$.ml$dmlc$xgboost4j$scala$spark$XGBoost$$postTrackerReturnProcessing(XGBoost.scala:283)
	at ml.dmlc.xgboost4j.scala.spark.XGBoost$$anonfun$trainDistributed$4.apply(XGBoost.scala:240)
	at ml.dmlc.xgboost4j.scala.spark.XGBoost$$anonfun$trainDistributed$4.apply(XGBoost.scala:222)
	at scala.collection.TraversableLike$$anonfun$map$1.apply(TraversableLike.scala:234)
	at scala.collection.TraversableLike$$anonfun$map$1.apply(TraversableLike.scala:234)
	at scala.collection.immutable.List.foreach(List.scala:381)
	at scala.collection.TraversableLike$class.map(TraversableLike.scala:234)
	at scala.collection.immutable.List.map(List.scala:285)
	at ml.dmlc.xgboost4j.scala.spark.XGBoost$.trainDistributed(XGBoost.scala:221)
	at ml.dmlc.xgboost4j.scala.spark.XGBoostClassifier.train(XGBoostClassifier.scala:191)
	at ml.dmlc.xgboost4j.scala.spark.XGBoostClassifier.train(XGBoostClassifier.scala:48)
	at org.apache.spark.ml.Predictor.fit(Predictor.scala:118)
	at com.qunar.train.xgboostdemo$.main(xgboostdemo.scala:53)
	at com.qunar.train.xgboostdemo.main(xgboostdemo.scala)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.apache.spark.deploy.yarn.ApplicationMaster$$anon$4.run(ApplicationMaster.scala:721)
18/10/24 17:09:54 INFO ApplicationMaster: Final app status: FAILED, exitCode: 15, (reason: User class threw exception: ml.dmlc.xgboost4j.java.XGBoostError: XGBoostModel training failed
	at ml.dmlc.xgboost4j.scala.spark.XGBoost$.ml$dmlc$xgboost4j$scala$spark$XGBoost$$postTrackerReturnProcessing(XGBoost.scala:283)
	at ml.dmlc.xgboost4j.scala.spark.XGBoost$$anonfun$trainDistributed$4.apply(XGBoost.scala:240)
	at ml.dmlc.xgboost4j.scala.spark.XGBoost$$anonfun$trainDistributed$4.apply(XGBoost.scala:222)
	at scala.collection.TraversableLike$$anonfun$map$1.apply(TraversableLike.scala:234)
	at scala.collection.TraversableLike$$anonfun$map$1.apply(TraversableLike.scala:234)
	at scala.collection.immutable.List.foreach(List.scala:381)
	at scala.collection.TraversableLike$class.map(TraversableLike.scala:234)
	at scala.collection.immutable.List.map(List.scala:285)
	at ml.dmlc.xgboost4j.scala.spark.XGBoost$.trainDistributed(XGBoost.scala:221)
	at ml.dmlc.xgboost4j.scala.spark.XGBoostClassifier.train(XGBoostClassifier.scala:191)
	at ml.dmlc.xgboost4j.scala.spark.XGBoostClassifier.train(XGBoostClassifier.scala:48)
	at org.apache.spark.ml.Predictor.fit(Predictor.scala:118)
	at com.qunar.train.xgboostdemo$.main(xgboostdemo.scala:53)
	at com.qunar.train.xgboostdemo.main(xgboostdemo.scala)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.apache.spark.deploy.yarn.ApplicationMaster$$anon$4.run(ApplicationMaster.scala:721)
)
18/10/24 17:09:54 INFO SparkContext: Invoking stop() from shutdown hook
18/10/24 17:09:54 INFO AbstractConnector: Stopped Spark@4b84604{HTTP/1.1,[http/1.1]}{0.0.0.0:0}

There's no log for training failure in the error log.
Error occurred when I executed the following code.
"val xgbClassificationModel = xgbClassifier.fit(xgbInput)"

**Comment by hcho3** [comment]
@CodingCat @yanboliang Is there a way to obtain a more informative error message other than "XGBoostModel training failed"?

**Comment by CodingCat** [comment]
anything there before the line `18/10/24 17:09:54 INFO RabitTracker: Tracker Process ends with exit code 1` your tracker exists in an unexpected way

**Comment by CodingCat** [comment]
@hcho3, actually this information only indicates training is failed, we need to look at somewhere else in the spark log

**Comment by haitongwan** [comment]
RabitTracker$TrackerProcessLogger: Traceback (most recent call last):
18/10/25 14:33:09 INFO RabitTracker$TrackerProcessLogger:   File "/data1/hadoop/log/nm-local-dir/usercache/traindev/appcache/application_1539143604999_1250/container_1539143604999_1250_01_000001/tmp/tracker3615953946870815164.py", line 19, in <module>
18/10/25 14:33:09 INFO RabitTracker$TrackerProcessLogger:     import argparse
18/10/25 14:33:09 INFO RabitTracker$TrackerProcessLogger: ImportError: No module named argparse
18/10/25 14:33:09 INFO RabitTracker$TrackerProcessLogger: Tracker Process ends with exit code 1

Is that why?Should all machines be installed?

**Comment by CodingCat** [comment]
your tracker is not even started you need to install argparse in the machine you started tracker.....

**Comment by hcho3** [comment]
@CodingCat So XGBoost4J-Spark requires Python? We may want to document it.

**Comment by CodingCat** [comment]
Yes, that’s for rabit’s tracker...

**Comment by hcho3** [comment]
@CodingCat Got it. I'll add it to the doc.
BTW, it seems like there are two variants of Rabit tracker, one in Python and another in Scala:
https://github.com/dmlc/xgboost/blob/4ae225a08d3ff75d8d3a9f59ca477680cad2579c/jvm-packages/xgboost4j-spark/src/main/scala/ml/dmlc/xgboost4j/scala/spark/XGBoost.scala#L169-L171

Is the Scala tracker ever used?

**Comment by CodingCat** [comment]
Scala Tracker was developed because some users say they have very old version python in the cluster and they cannot upgrade due to some reason

I don't think many users are using it in production...by default, python based tracker is started

**Comment by hcho3** [comment]
Should we add Python as requirement for XGBoost4J-Spark then? Or say "recommended"?
