### ISSUE TITLE
[jvm-packages] What's the best practice to set parameters and configurations for running XGBoost Spark on large data?

### ISSUE THREAD

**Issue by FredYao** [dmlc/xgboost#3908]
I was using the Spark version of XGBoost4j, and training on a dataset sized 3.0G. I set the model's training parameters as:
`val xgbParam = Map("eta" -> 0.1f,
			"max_depth" -> 5,
			"objective" -> "binary:logistic",
			"num_round" -> 100,
			"colsample_bylevel" -> 0.7f,
			"tracker_conf" -> TrackerConf(0L, "scala"))`
My submit command was `spark-submit --master yarn --deploy-mode client --class XXX --num-executors 2000 --executor-memory 2g --conf "spark.executor.memoryOverhead=2g" --jars YYY.jar  /path-to-class`. 
3.0G was not really a big data, so I set the memory of each executor as 2G, and memory-overhead also 2G. However, I kept receiving errors like:

2018-11-15 17:28:22 INFO  YarnSchedulerBackend$YarnDriverEndpoint:54 - Asked to remove non-existent executor 798
2018-11-15 17:28:22 INFO  AsyncEventQueue:75 - Stopping listener queue shared.
java.lang.InterruptedException: ExecutorLost during XGBoost Training: ExecutorLostFailure (executor 798 exited caused by one of the running tasks) Reason: Container killed by YARN for exceeding memory limits. 5.0 GB of 5 GB physical memory used. Consider boosting spark.yarn.executor.memoryOverhead.
	at org.apache.spark.TaskFailedListener.onTaskEnd(SparkParallelismTracker.scala:118)
	at org.apache.spark.scheduler.SparkListenerBus$class.doPostEvent(SparkListenerBus.scala:45)
	at org.apache.spark.scheduler.AsyncEventQueue.doPostEvent(AsyncEventQueue.scala:37)
	at org.apache.spark.scheduler.AsyncEventQueue.doPostEvent(AsyncEventQueue.scala:37)
	at org.apache.spark.util.ListenerBus$class.postToAll(ListenerBus.scala:82)
	at org.apache.spark.scheduler.AsyncEventQueue.org$apache$spark$scheduler$AsyncEventQueue$$super$postToAll(AsyncEventQueue.scala:89)
	at org.apache.spark.scheduler.AsyncEventQueue$$anonfun$org$apache$spark$scheduler$AsyncEventQueue$$dispatch$1.apply(AsyncEventQueue.scala:89)
	at scala.util.DynamicVariable.withValue(DynamicVariable.scala:58)
	at org.apache.spark.scheduler.AsyncEventQueue.org$apache$spark$scheduler$AsyncEventQueue$$dispatch(AsyncEventQueue.scala:83)
	at org.apache.spark.scheduler.AsyncEventQueue$$anon$1$$anonfun$run$1.apply$mcV$sp(AsyncEventQueue.scala:79)
	at org.apache.spark.util.Utils$.tryOrStopSparkContext(Utils.scala:1319)
	at org.apache.spark.scheduler.AsyncEventQueue$$anon$1.run(AsyncEventQueue.scala:78)

And the Spark UI always stuck at the stage  'foreachPartition at XGBoost.scala:233'. Can anyone give me some guidance for running XGBoost4j-spark on large dataset? Thanks!

**Comment by CodingCat** [comment]
what's the format of your dataset and does your application only do training without any preprocessing  of data?

**Comment by FredYao** [comment]
@LeoLee1 , I have used the maximum memory that an executor can provide (i.e., 8G). It makes less sense to assume that each executor should have super large memory in a cluster.  

`./bin/spark-submit --master yarn --deploy-mode client --class XXX  --num-executors 100 --executor-memory 7g --executor-cores 4 --conf spark.storage.memoryFraction=0.5 --conf spark.shuffle.memoryFraction=0.5 --jars YYY.jar  /path/to/class`

It said that '... used up all physical memory 8G (maximum-allowed memory) ..." 
My data is 3G totally and has 100 partitions (30M each).

**Comment by FredYao** [comment]
@CodingCat , the dataset is in CSV format. My pipeline does some feature engineering before feeding the data into XGBoost. However, from Spark UI, I saw that it got stuck at XGBoost foreachPartion stage.

**Comment by CodingCat** [comment]
@FredYao it doesn't mean XGBoost is the bottleneck, if you didn't persist your dataframe before feeding to xgboostclassifier/regressor, only foreachPartition will show up as that's the job triggering everything

**Comment by CodingCat** [comment]
BTW you may want to post your code and UI screenshot

**Comment by LeoLee1** [comment]
@FredYao What is the version of your Spark Cluster?  I'm not sure, but here is my tricky method. I think that it's not related with Spark version of XGBoost4j, but handling it with RDD. Just refer to the below.

1) Repartition and mapPartitions : RDD.repartition(4*100*12).mapPartitions(iterative function) 
2) Coalesce and mapPartitions : RDD.coalesce(4*100*12).mapPartitions(iterative function)

You can control the num of partitions and choose one of the upper with respect to your code/cluster. BTW it would be better that your code and log or spark UI will be posted if possible. 

`./bin/spark-submit` --master yarn --deploy-mode client --class XXX --num-executors 100 --executor-memory 4g --executor-cores 4 --conf spark.yarn.executor.memoryOverhead=2048 --jars YYY.jar /path/to/class

**Comment by thvasilo** [comment]
@FredYao is your actual dataset 3GB? In that case I'd recommend just creating a file artifact after your pre-processing and using the base XGBoost to run your training, avoiding, Spark, partitioning etc. that is really a lot of overhead for such small input. 

On many occasions I've been able to train datasets of multiple gigabytes on a laptop with 16G of memory.

**Comment by FredYao** [comment]
@CodingCat , I created a pipeline with the last step being a XGBoostClassifier. However, if I replaced the last step with any other spark-ml learning methods (e.g., RandomForest), it worked fine on the dataset, and finished all the training in 20-25 minutes. I will post my code for XGBoost and Spark UI later.

**Comment by FredYao** [comment]
@thvasilo , thanks for your advice. My raw input data was 3.0G stored in HDFS with 100 partitions. I created a pipeline with a XGBoostClassifier as the last stage. So I did not know exactly what the input size to XGBoostClassifier. The input could be larger after some preorpcessing and feature engineerings in the pipeline. However, I need to get this run on a cluster instead of a personal computer, since this is for a production deployment.

**Comment by CodingCat** [comment]
I noticed that you used 100 * 4 G memory in total to train 3G dataset...and failed...it doesn’t make any sense...must be something wrong in somewhere

I am working with 4+ T dataset with only 5-T memory budget...no problem at all...so it’s necessary to know your xgb version, code, spark ui, etc.

**Comment by FredYao** [comment]
@CodingCat , my spark version is 2.3.0 and XGBoost version is 0.80. 
Code:
`	def main(args: Array[String]): Unit = {
		
		val spark = SparkSession.builder()
			.getOrCreate()
		
		import spark.implicits._
		
		// data schema 
		val customSchema = StructType(Array(
			StructField("url", StringType, true),
			StructField("postal_code", StringType, true),
			StructField("label", ByteType, true)
		))

		// file location
		val filename = "/path/to/data/part-*"

		// read raw data 
		var rawData = spark.read.format("csv").option("delimiter", ">").option("header","false").schema(customSchema).load(filename)

		// fetch high frequent URLs 
		val topUrls = rawData.groupBy("url").count.orderBy($"count".desc).limit(100)
		val urlData = rawData.join(topUrls, Seq("url"), "left")
						.withColumn("url", when($"count".isNull, lit(null)).otherwise($"url")).drop("count")
		
		// fetch high frequent POSTAL_CODEs 
		val topPostalCodes = rawData.groupBy("postal_code").count.orderBy($"count".desc).limit(100)
		val postalData = urlData.join(topPostalCodes, Seq("postal_code"), "left")
						.withColumn("postal_code", when($"count".isNull, lit(null)).otherwise($"postal_code")).drop("count")
		
		// feature processing
		val sIndexer1 = new StringIndexer().setInputCol("url").setOutputCol("indexed_url").setHandleInvalid("keep")
		val sIndexer2 = new StringIndexer().setInputCol("postal_code").setOutputCol("indexed_postal_code").setHandleInvalid("keep")
		val encoder = new OneHotEncoderEstimator().setInputCols(Array(sIndexer1.getOutputCol, sIndexer2.getOutputCol)).setOutputCols(Array("encoded_url", "encoded_postal_code")).setDropLast(false)
		val vectorAssembler = new VectorAssembler().setInputCols(encoder.getOutputCols).setOutputCol("assembled_features")
		val xgbParam = Map("eta" -> 0.1f,
			"max_depth" -> 5,
			"objective" -> "binary:logistic",
			"num_round" -> 100,
			"colsample_bylevel" -> 0.7f,
			"tracker_conf" -> TrackerConf(0L, "scala"))
		val xgbClassifier = new XGBoostClassifier(xgbParam).setFeaturesCol(vectorAssembler.getOutputCol).setLabelCol("label").setMissing(-1.0f)
		val pipeline = new Pipeline().setStages(Array(sIndexer1, sIndexer2, encoder, vectorAssembler, xgbClassifier))

		val model = pipeline.fit(postalData)
		val preds = model.transform(postalData)
		
		spark.stop()
		
	}`

Spark UI:
![xgb1](https://user-images.githubusercontent.com/4297204/48733403-765c2580-ebf7-11e8-8b09-153075f5990f.png)
![xgb2](https://user-images.githubusercontent.com/4297204/48733297-15cce880-ebf7-11e8-8524-15551ea1fdd9.png)
![xgb3](https://user-images.githubusercontent.com/4297204/48733298-182f4280-ebf7-11e8-9aec-cab2e51b8738.png)

**Comment by CodingCat** [comment]
you didn't specify `num_workers` or call `setNumWorkers` with XGBClassifier so that all data are collected to a single task (as num_workers is 1 by default)

read https://xgboost.readthedocs.io/en/latest/jvm/xgboost4j_spark_tutorial.html#parallel-distributed-training

**Comment by CodingCat** [comment]
BTW I suggest upgrade to 0.81 if you work with very large dataset as we fixed a memory leak in 0.81

**Comment by FredYao** [comment]
@CodingCat , thanks for pointing that out. I will try by setting num_workders. Before you mentioned this, I thought it was supposed to be the number of executors specified while submitting the Spark job. BTW, is it necessary to set num_workers (for xgboost) as same as num_executors ?

**Comment by CodingCat** [comment]
no...you have to set it as a value no larger than the total number of cores you claimed in your spark app, i.e. executor-cores * num-executors

**Comment by FredYao** [comment]
I tried by setting num_workers as 1000 in XGBoostClassifier, and submit the job using num-executors=2000 (by default, executor-cores = 1). There are some errors. I am not sure if the errors were brought because of the memory leak you mentioned (version 0.80)

`

2018-11-19 16:43:04 INFO  MapOutputTrackerMasterEndpoint:54 - Asked to send map output locations for shuffle 19 to 10.0.30.42:57778
2018-11-19 16:43:04 WARN  TaskSetManager:66 - Lost task 259.0 in stage 32.3 (TID 9192, executor 1756): FetchFailed(null, shuffleId=19, mapId=-1, reduceId=259, message=
org.apache.spark.shuffle.MetadataFetchFailedException: Missing an output location for shuffle 19
	at org.apache.spark.MapOutputTracker$$anonfun$convertMapStatuses$2.apply(MapOutputTracker.scala:867)
	at org.apache.spark.MapOutputTracker$$anonfun$convertMapStatuses$2.apply(MapOutputTracker.scala:863)
	at scala.collection.TraversableLike$WithFilter$$anonfun$foreach$1.apply(TraversableLike.scala:733)
	at scala.collection.IndexedSeqOptimized$class.foreach(IndexedSeqOptimized.scala:33)
	at scala.collection.mutable.ArrayOps$ofRef.foreach(ArrayOps.scala:186)
	at scala.collection.TraversableLike$WithFilter.foreach(TraversableLike.scala:732)
	at org.apache.spark.MapOutputTracker$.convertMapStatuses(MapOutputTracker.scala:863)
	at org.apache.spark.MapOutputTrackerWorker.getMapSizesByExecutorId(MapOutputTracker.scala:677)
	at org.apache.spark.shuffle.BlockStoreShuffleReader.read(BlockStoreShuffleReader.scala:49)
	at org.apache.spark.rdd.ShuffledRDD.compute(ShuffledRDD.scala:105)
	at org.apache.spark.rdd.RDD.computeOrReadCheckpoint(RDD.scala:324)
	at org.apache.spark.rdd.RDD.iterator(RDD.scala:288)
	at org.apache.spark.rdd.CoalescedRDD$$anonfun$compute$1.apply(CoalescedRDD.scala:100)
	at org.apache.spark.rdd.CoalescedRDD$$anonfun$compute$1.apply(CoalescedRDD.scala:99)
	at scala.collection.Iterator$$anon$12.nextCur(Iterator.scala:434)
	at scala.collection.Iterator$$anon$12.hasNext(Iterator.scala:440)
	at scala.collection.Iterator$$anon$11.hasNext(Iterator.scala:408)
	at scala.collection.Iterator$class.isEmpty(Iterator.scala:330)
	at scala.collection.AbstractIterator.isEmpty(Iterator.scala:1336)
	at ml.dmlc.xgboost4j.scala.spark.XGBoost$$anonfun$buildDistributedBoosters$1.apply(XGBoost.scala:117)
	at ml.dmlc.xgboost4j.scala.spark.XGBoost$$anonfun$buildDistributedBoosters$1.apply(XGBoost.scala:116)
	at org.apache.spark.rdd.ZippedPartitionsRDD2.compute(ZippedPartitionsRDD.scala:89)
	at org.apache.spark.rdd.RDD.computeOrReadCheckpoint(RDD.scala:324)
	at org.apache.spark.rdd.RDD$$anonfun$7.apply(RDD.scala:337)
	at org.apache.spark.rdd.RDD$$anonfun$7.apply(RDD.scala:335)
	at org.apache.spark.storage.BlockManager$$anonfun$doPutIterator$1.apply(BlockManager.scala:1092)
	at org.apache.spark.storage.BlockManager$$anonfun$doPutIterator$1.apply(BlockManager.scala:1083)
	at org.apache.spark.storage.BlockManager.doPut(BlockManager.scala:1018)
	at org.apache.spark.storage.BlockManager.doPutIterator(BlockManager.scala:1083)
	at org.apache.spark.storage.BlockManager.getOrElseUpdate(BlockManager.scala:809)
	at org.apache.spark.rdd.RDD.getOrCompute(RDD.scala:335)
	at org.apache.spark.rdd.RDD.iterator(RDD.scala:286)
	at org.apache.spark.scheduler.ResultTask.runTask(ResultTask.scala:87)
	at org.apache.spark.scheduler.Task.run(Task.scala:109)
	at org.apache.spark.executor.Executor$TaskRunner.run(Executor.scala:345)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
`

![xgb1](https://user-images.githubusercontent.com/4297204/48744301-8ede3700-ec1b-11e8-9bd1-21b4e7caaed6.png)
![xgb2](https://user-images.githubusercontent.com/4297204/48744306-91409100-ec1b-11e8-938a-a41038c641d9.png)

**Comment by CodingCat** [comment]
It looks like some executor got killed, please look at your logs and see if you can find something related

**Comment by CodingCat** [comment]
wait....according to your screenshot, you have at most 890 cores in your system, and you set worker number as 1000...how your training can even proceed? XGBoost requires all workers must be started before move forward to training

can you check if there is still anything wrong in your code, etc.?

**Comment by FredYao** [comment]
@CodingCat , I have run the scripts on my local machine. It was good. When I submit it to yarn cluster, I changed the worker number to 100 when I executed the job. The command I used is
`spark-submit --master yarn --deploy-mode client --num-executors 100 --executor-cores 4 --class XXX --queue QQQ --executor-memory 4g --conf spark.executor.memoryOverhead=2048 --jars /path/to/jars /path/to/class`
In my scala scripts, I set num_workers of XGBoost as 100. The dataset size is still 3G with 100 partitions (each being 30M). However, I was not able to run it successfully. I am not sure if the errors were caused by some configurations of the yarn cluster. 

2018-11-20 14:53:53 WARN  Executor:87 - Issue communicating with driver in heartbeater
org.apache.spark.rpc.RpcTimeoutException: Futures timed out after [10 seconds]. This timeout is controlled by spark.executor.heartbeatInterval
	at org.apache.spark.rpc.RpcTimeout.org$apache$spark$rpc$RpcTimeout$$createRpcTimeoutException(RpcTimeout.scala:47)
	at org.apache.spark.rpc.RpcTimeout$$anonfun$addMessageIfTimeout$1.applyOrElse(RpcTimeout.scala:62)
	at org.apache.spark.rpc.RpcTimeout$$anonfun$addMessageIfTimeout$1.applyOrElse(RpcTimeout.scala:58)
	at scala.runtime.AbstractPartialFunction.apply(AbstractPartialFunction.scala:36)
	at org.apache.spark.rpc.RpcTimeout.awaitResult(RpcTimeout.scala:76)
	at org.apache.spark.rpc.RpcEndpointRef.askSync(RpcEndpointRef.scala:92)
	at org.apache.spark.executor.Executor.org$apache$spark$executor$Executor$$reportHeartBeat(Executor.scala:785)
	at org.apache.spark.executor.Executor$$anon$2$$anonfun$run$1.apply$mcV$sp(Executor.scala:814)
	at org.apache.spark.executor.Executor$$anon$2$$anonfun$run$1.apply(Executor.scala:814)
	at org.apache.spark.executor.Executor$$anon$2$$anonfun$run$1.apply(Executor.scala:814)
	at org.apache.spark.util.Utils$.logUncaughtExceptions(Utils.scala:1988)
	at org.apache.spark.executor.Executor$$anon$2.run(Executor.scala:814)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.runAndReset(FutureTask.java:308)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$301(ScheduledThreadPoolExecutor.java:180)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:294)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
Caused by: java.util.concurrent.TimeoutException: Futures timed out after [10 seconds]
	at scala.concurrent.impl.Promise$DefaultPromise.ready(Promise.scala:219)
	at scala.concurrent.impl.Promise$DefaultPromise.result(Promise.scala:223)
	at org.apache.spark.util.ThreadUtils$.awaitResult(ThreadUtils.scala:201)
	at org.apache.spark.rpc.RpcTimeout.awaitResult(RpcTimeout.scala:75)


2018-11-20 14:56:48 INFO  BlockManagerMaster:54 - Removal of executor 177 requested
2018-11-20 14:56:48 INFO  BlockManagerMasterEndpoint:54 - Trying to remove executor 177 from BlockManagerMaster.
2018-11-20 14:56:48 INFO  YarnSchedulerBackend$YarnDriverEndpoint:54 - Asked to remove non-existent executor 177
2018-11-20 14:56:48 ERROR YarnScheduler:70 - Lost executor 115 on xxx.yyy.com: Container marked as failed: container_1542712054221_5591_01_334784 on host: xxx.yyy.com. Exit status: 255. Diagnostics: Exception from container-launch.
Container id: container_1542712054221_5591_01_334784
Exit code: 255
Stack trace: ExitCodeException exitCode=255: 
	at org.apache.hadoop.util.Shell.runCommand(Shell.java:543)
	at org.apache.hadoop.util.Shell.run(Shell.java:460)
	at org.apache.hadoop.util.Shell$ShellCommandExecutor.execute(Shell.java:720)
	at org.apache.hadoop.yarn.server.nodemanager.DefaultContainerExecutor.__launchContainer__(DefaultContainerExecutor.java:210)
	at org.apache.hadoop.yarn.server.nodemanager.DefaultContainerExecutor.launchContainer(DefaultContainerExecutor.java)
	at org.apache.hadoop.yarn.server.nodemanager.containermanager.launcher.ContainerLaunch.call(ContainerLaunch.java:302)
	at org.apache.hadoop.yarn.server.nodemanager.containermanager.launcher.ContainerLaunch.call(ContainerLaunch.java:82)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)

**Comment by CodingCat** [comment]
ERROR YarnScheduler:70 - Lost executor 115 on xxx.yyy.com: Container marked as failed: container_1542712054221_5591_01_334784 on host: xxx.yyy.com. Exit status: 255. Diagnostics: Exception from container-launch.


Your executor was crashed for some reason, you need to look at the executor log

**Comment by LeoLee1** [comment]
@FredYao Thanks for sharing the code and logs with us. I think that there's some missing config for spark Driver. Please refer to the below URL. I found some WARN message in the logs, but not sure about your cluster status and environments.

> https://spark.apache.org/docs/2.3.0/configuration.html 

spark.driver.maxResultSize | 1g | Limit of total size of serialized results of all partitions for each Spark action (e.g. collect) in bytes. Should be at least 1M, or 0 for unlimited. Jobs will be aborted if the total size is above this limit. Having a high limit may cause out-of-memory errors in driver (depends on spark.driver.memory and memory overhead of objects in JVM). Setting a proper limit can protect the driver from out-of-memory errors.

spark.driver.memory | 1g | Amount of memory to use for the driver process, i.e. where SparkContext is initialized, in MiB unless otherwise specified (e.g. 1g, 2g). Note: In client mode, this config must not be set through the SparkConf directly in your application, because the driver JVM has already started at that point. Instead, please set this through the --driver-memory command line option or in your default properties file.

Python code example
`
conf = SparkConf().setAppName("XGBOOST4j Spark")
conf.set("spark.driver.maxResultSize", "0")
conf.set("spark.network.timeout", "3600s")
conf.set("spark.sql.broadcastTimeout", "1200")
conf.set("spark.executor.heartbeatInterval","1800s")
conf.set("spark.rpc.message.maxSize", "1024")
`
