### ISSUE TITLE
Spark XGBoostClassificationModel transform doesn't work with Structured Streaming

### ISSUE THREAD

**Issue by collinscangarella** [dmlc/xgboost#3993]
**Environment Info**
jvm+spark, version 0.8.1

**Steps to Reproduce**

1. Train a XGBoostClassificationModel and then pass a streaming DataFrame to model.transform().
2. This error occurs:

```
Caused by: org.apache.spark.sql.AnalysisException: Queries with streaming sources must be executed with writeStream.start();;
	...
	at org.apache.spark.sql.Dataset.rdd(Dataset.scala:3036)
	at ml.dmlc.xgboost4j.scala.spark.XGBoostClassificationModel.transformInternal(XGBoostClassifier.scala:293)
	at ml.dmlc.xgboost4j.scala.spark.XGBoostClassificationModel.transform(XGBoostClassifier.scala:415)
	...
```

I'm aware of [this issue](https://github.com/dmlc/xgboost/issues/3382) - which has a slightly different stack track and is for the XGBoostModel instead of the XGBoostClassificationModel. The problem is again that `rdd.mapPartitions` is called - which doesn't work with spark streaming.

**Comment by collinscangarella** [comment]
I read a bit more about 3382 and realized that it is the same issue as this. I assumed that the PR referenced in the issue fixed the underlying problem - but after digging through the PR I realized that it only provides a workaround. As it doesn't document the workaround I wanted to include it here in a comment before closing this issue.

XGBoost4J-Spark doesn't support structured streaming. Any call to the `transform` method calls `rdd.mapPartitions`, something which you can't do with spark streaming. However, you can work around this by using streaming for most of the pipeline while making individual predict calls with the model. Here's a code example of how to do that if you have a single pipeline for feature extraction and model prediction:

```
row.select("value.*")
  .transform(dataframe => {
    val featureExtractors = pipeline.stages.init
    val model = pipeline.stages.last.asInstanceOf[XGBoostClassificationModel]
    val features = featureExtractors.foldLeft(dataframe){ (data, transformer) => transformer.transform(data)}
    features.map(row => Results.Prediction(
      row.getAs[String](Dataset.cols.ID),
      model.predict(row.getAs[Vector](featureCol))))
  })
```
This assumes that you have a single XGBoostClassificationModel at the end of the pipeline. It separates out the feature extractors and the model, transforms using the feature extractors (to keep as much in spark streaming as possible), and maps each feature vector, calling model.predict every time. 

Here's an example if you have two separate pipelines, one for feature extraction and another for model prediction:
```
row.select("value.*")
  .transform(dataframe => {
    val model = modelPipeline.stages.first.asInstanceOf[XGBoostClassificationModel]
    val features = featurePipeline.transform(dataframe)
    features.map(row => Results.Prediction(
      row.getAs[String](Dataset.cols.ID),
      model.predict(row.getAs[Vector](featureCol))))
  })
```
You'll notice that these both take place in the same transform step. The reason for this is because spark doesn't approve of pipeline references in a map step and will throw a serialization exception.

This obviously isn't very performant and is quite hackey - but it is a workaround for anyone who needs it.
