### ISSUE TITLE
OSError: xgboost/libxgboost.so: ELF file OS ABI invalid

### ISSUE THREAD

**Issue by yayawcx** [dmlc/xgboost#4012]
Error message:
>>> import xgboost as xgb
/home/work/.jumbo/lib/python2.7/site-packages/sklearn/externals/joblib/_multiprocessing_helpers.py:28: UserWarning: This platform lacks a functioning sem_open implementation, therefore, the required synchronization primitives needed will not function, see issue 3770..  joblib will operate in serial mode
  warnings.warn('%s.  joblib will operate in serial mode' % (e,))
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/work/.jumbo/lib/python2.7/site-packages/xgboost-0.6-py2.7.egg/xgboost/__init__.py", line 11, in <module>
    from .core import DMatrix, Booster
  File "/home/work/.jumbo/lib/python2.7/site-packages/xgboost-0.6-py2.7.egg/xgboost/core.py", line 115, in <module>
    _LIB = _load_lib()
  File "/home/work/.jumbo/lib/python2.7/site-packages/xgboost-0.6-py2.7.egg/xgboost/core.py", line 109, in _load_lib
    lib = ctypes.cdll.LoadLibrary(lib_path[0])
  File "/home/work/.jumbo/lib/python2.7/ctypes/__init__.py", line 443, in LoadLibrary
    return self._dlltype(name)
  File "/home/work/.jumbo/lib/python2.7/ctypes/__init__.py", line 365, in __init__
    self._handle = _dlopen(self._name, mode)
OSError: /home/work/.jumbo/lib/python2.7/site-packages/xgboost-0.6-py2.7.egg/xgboost/libxgboost.so: ELF file OS ABI invalid

**Comment by trivialfis** [comment]
@yayawcx  Can you please provide the following information:
- OS Platform, including CPU architecture(x86-64 or i686), name of distribution, libc version. (Is it in docker environment? )
- XGBoost version.
- How did you install XGBoost? (pip, conda, compiling from source or something else).

**Comment by trivialfis** [comment]
@yayawcx More information is needed.  Closing for now and feel free to reopen.
