### ISSUE TITLE
RabitTracker reported 'assertion failed' 

### ISSUE THREAD

**Issue by FredYao** [dmlc/xgboost#4025]
When I was training a XGBoostClassifier, I got the following errors reported by RabitTracker. Does anyone have idea about the errors? Thanks!

XGBoost version: 0.81
Spark version: 2.3.0

XGBoost param:
```
val xgbParam = Map("eta" -> 0.1f,
			"max_depth" -> 6,
			"objective" -> "binary:logistic",
			"num_round" -> 10,
			"colsample_bylevel" -> 0.7f,
			"tracker_conf" -> TrackerConf(10000L, "scala"),
			"num_workers" -> 10,
			"nthread" -> 1
		)
```

[ERROR] [12/26/2018 11:57:24.494] [RabitTracker-akka.actor.default-dispatcher-3] [akka://RabitTracker/user] assertion failed
java.lang.AssertionError: assertion failed
	at scala.Predef$.assert(Predef.scala:156)
	at ml.dmlc.xgboost4j.scala.rabit.handler.WorkerDependencyResolver$$anonfun$receive$2.applyOrElse(RabitTrackerHandler.scala:298)
	at akka.actor.Actor$class.aroundReceive(Actor.scala:467)
	at ml.dmlc.xgboost4j.scala.rabit.handler.WorkerDependencyResolver.aroundReceive(RabitTrackerHandler.scala:264)
	at akka.actor.ActorCell.receiveMessage(ActorCell.scala:516)
	at akka.actor.ActorCell.invoke(ActorCell.scala:487)
	at akka.dispatch.Mailbox.processMailbox(Mailbox.scala:238)
	at akka.dispatch.Mailbox.run(Mailbox.scala:220)
	at akka.dispatch.ForkJoinExecutorConfigurator$AkkaForkJoinTask.exec(AbstractDispatcher.scala:397)
	at scala.concurrent.forkjoin.ForkJoinTask.doExec(ForkJoinTask.java:260)
	at scala.concurrent.forkjoin.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1339)
	at scala.concurrent.forkjoin.ForkJoinPool.runWorker(ForkJoinPool.java:1979)
	at scala.concurrent.forkjoin.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:107)

[INFO] [12/26/2018 11:57:24.494] [RabitTracker-akka.actor.default-dispatcher-24] [akka://RabitTracker/user/Handler/ConnectionHandler-f4097d95-afb2-4e79-9374-4aa44443c1b5] Message [akka.io.Tcp$Received] from Actor[akka://RabitTracker/system/IO-TCP/selectors/$a/17#819618349] to Actor[akka://RabitTracker/user/Handler/ConnectionHandler-f4097d95-afb2-4e79-9374-4aa44443c1b5#-1191377347] was not delivered. [1] dead letters encountered. This logging can be turned off or adjusted with configuration settings 'akka.log-dead-letters' and 'akka.log-dead-letters-during-shutdown'.
[INFO] [12/26/2018 11:57:24.494] [RabitTracker-akka.actor.default-dispatcher-24] [akka://RabitTracker/user/Handler/Resolver] Message [ml.dmlc.xgboost4j.scala.rabit.handler.RabitWorkerHandler$RequestAwaitConnWorkers] from Actor[akka://RabitTracker/user/Handler/ConnectionHandler-5ea01c2d-3d8d-47db-9b1e-c95f0ba851de#-998170151] to Actor[akka://RabitTracker/user/Handler/Resolver#1758013260] was not delivered. [2] dead letters encountered. This logging can be turned off or adjusted with configuration settings 'akka.log-dead-letters' and 'akka.log-dead-letters-during-shutdown'.

**Comment by chenqin** [comment]
Hi @FredYao,

Can you post value of 

- spark.task.cpus 
- spark.executor.cpus
- spark.executor.instances

AFAIK, the assertion might assume there are enough number of spark tasks can run in parallel should be >= numWorkers.
Meanwhile, I noticed you use scala tracker which has been out of maintenance for a while. Can you give a try to python tracker and see if problem still reproducible? 

cc @CodingCat 

Chen

**Comment by FredYao** [comment]
@chenqin ,

I used the following setting when submit my application:
--conf spark.task.cpus=1
--executor-cores 2
--num-executors 100
However, I did not explicitly set spark.executor.cpus.

I think the number of spark tasks are > numWorkers. The reason I used scala-tracker is because my cluster did not support python 2.7+.

**Comment by CodingCat** [comment]
add [jvm-packages] in the title to help us identify the topic and in future the usage discussion should go to https://discuss.xgboost.ai/
