### ISSUE TITLE
Tracker issue with XGBoost in PySpark

### ISSUE THREAD

**Issue by vectosaurus** [dmlc/xgboost#4048]
I am using XGBoost in PySpark using by placing these two jars [xgboost4j][1] and [xgboost4j-spark][2] in `$SPARK_HOME/jars` folder. 

When I try to fit the `XGBoostClassifier` model I get an error with the following message

> py4j.protocol.Py4JJavaError: An error occurred while calling o413.fit.
> : ml.dmlc.xgboost4j.java.XGBoostError: XGBoostModel training failed

I looked for the tracker in trace and noticed that it is not binding to the localhost. This is the tracker info

    Tracker started, with env={}

I am using a Mac and so checked for the `/etc/hosts` file 

    ##
    # Host Database
    #
    # localhost is used to configure the loopback interface
    # when the system is booting.  Do not change this entry.
    ##
    127.0.0.1	localhost.localdomain localhost
    255.255.255.255	broadcasthost
    ::1             localhost
    127.0.0.1 myusername

Everything looks fine in the `hosts` file.  Any idea why the tracker isn't initialising correctly?

I am using 
Mac 10.14
spark 2.3.1
xgboost 0.80
py4j 0.10.7 

  [1]: https://mvnrepository.com/artifact/ml.dmlc/xgboost4j/0.80
  [2]: https://mvnrepository.com/artifact/ml.dmlc/xgboost4j-spark/0.80

*Error trace*

    Tracker started, with env={}
    2019-01-07 12:50:19 ERROR RabitTracker:91 - Uncaught exception thrown by worker:
    java.lang.InterruptedException
    	at java.util.concurrent.locks.AbstractQueuedSynchronizer.doAcquireSharedInterruptibly(AbstractQueuedSynchronizer.java:998)
    	at java.util.concurrent.locks.AbstractQueuedSynchronizer.acquireSharedInterruptibly(AbstractQueuedSynchronizer.java:1304)
    	at scala.concurrent.impl.Promise$DefaultPromise.tryAwait(Promise.scala:202)
    	at scala.concurrent.impl.Promise$DefaultPromise.ready(Promise.scala:218)
    	at scala.concurrent.impl.Promise$DefaultPromise.ready(Promise.scala:153)
    	at org.apache.spark.util.ThreadUtils$.awaitReady(ThreadUtils.scala:222)
    	at org.apache.spark.scheduler.DAGScheduler.runJob(DAGScheduler.scala:633)
    	at org.apache.spark.SparkContext.runJob(SparkContext.scala:2034)
    	at org.apache.spark.SparkContext.runJob(SparkContext.scala:2055)
    	at org.apache.spark.SparkContext.runJob(SparkContext.scala:2074)
    	at org.apache.spark.SparkContext.runJob(SparkContext.scala:2099)
    	at org.apache.spark.rdd.RDD$$anonfun$foreachPartition$1.apply(RDD.scala:929)
    	at org.apache.spark.rdd.RDD$$anonfun$foreachPartition$1.apply(RDD.scala:927)
    	at org.apache.spark.rdd.RDDOperationScope$.withScope(RDDOperationScope.scala:151)
    	at org.apache.spark.rdd.RDDOperationScope$.withScope(RDDOperationScope.scala:112)
    	at org.apache.spark.rdd.RDD.withScope(RDD.scala:363)
    	at org.apache.spark.rdd.RDD.foreachPartition(RDD.scala:927)
    	at ml.dmlc.xgboost4j.scala.spark.XGBoost$$anonfun$trainDistributed$4$$anon$1.run(XGBoost.scala:233)

    Traceback (most recent call last):
      File "<stdin>", line 2, in <module>
      File "/Users/myusername/Downloads/ml_project/ml_project/features/variable_selection.py", line 130, in fit
        self.ttv.fit(target_col, X, test=None, validation=None)
      File "/Users/myusername/Downloads/ml_project/ml_project/models/train_test_validator.py", line 636, in fit
        upper_bounds, self.curr_model_num_iter, is_integer_variable)
      File "/Users/myusername/Downloads/ml_project/ml_project/models/train_test_validator.py", line 253, in model_tuner
        num_iter, is_integer_variable, random_state=42)
      File "/Users/myusername/Downloads/ml_project/ml_project/models/hyperparam_optimizers.py", line 200, in aml_forest_maximize
        is_integer_variable, random_state=random_state)
      File "/Users/myusername/Downloads/ml_project/ml_project/models/hyperparam_optimizers.py", line 179, in aml_forest_minimize
        return forest_minimize(objective_calculator, space, n_calls=num_iter, random_state=random_state, n_random_starts=n_random_starts, base_estimator="RF", n_jobs=-1)
      File "/usr/local/lib/python3.7/site-packages/skopt/optimizer/forest.py", line 161, in forest_minimize
        callback=callback, acq_optimizer="sampling")
      File "/usr/local/lib/python3.7/site-packages/skopt/optimizer/base.py", line 248, in base_minimize
        next_y = func(next_x)
      File "/Users/myusername/Downloads/ml_project/ml_project/models/train_test_validator.py", line 487, in objective_calculator
        model_fit = init_model.fit(train)  # fit model
      File "/Users/myusername/Downloads/spark/python/pyspark/ml/base.py", line 132, in fit
        return self._fit(dataset)
      File "/Users/myusername/Downloads/spark/python/pyspark/ml/wrapper.py", line 288, in _fit
        java_model = self._fit_java(dataset)
      File "/Users/myusername/Downloads/spark/python/pyspark/ml/wrapper.py", line 285, in _fit_java
        return self._java_obj.fit(dataset._jdf)
      File "/Users/myusername/Downloads/spark/python/lib/py4j-0.10.7-src.zip/py4j/java_gateway.py", line 1257, in __call__
      File "/Users/myusername/Downloads/spark/python/pyspark/sql/utils.py", line 63, in deco
        return f(*a, **kw)
      File "/Users/myusername/Downloads/spark/python/lib/py4j-0.10.7-src.zip/py4j/protocol.py", line 328, in get_return_value
    py4j.protocol.Py4JJavaError: An error occurred while calling o413.fit.
    : ml.dmlc.xgboost4j.java.XGBoostError: XGBoostModel training failed
    	at ml.dmlc.xgboost4j.scala.spark.XGBoost$.ml$dmlc$xgboost4j$scala$spark$XGBoost$$postTrackerReturnProcessing(XGBoost.scala:283)
    	at ml.dmlc.xgboost4j.scala.spark.XGBoost$$anonfun$trainDistributed$4.apply(XGBoost.scala:240)
    	at ml.dmlc.xgboost4j.scala.spark.XGBoost$$anonfun$trainDistributed$4.apply(XGBoost.scala:222)
    	at scala.collection.TraversableLike$$anonfun$map$1.apply(TraversableLike.scala:234)
    	at scala.collection.TraversableLike$$anonfun$map$1.apply(TraversableLike.scala:234)
    	at scala.collection.immutable.List.foreach(List.scala:381)
    	at scala.collection.TraversableLike$class.map(TraversableLike.scala:234)
    	at scala.collection.immutable.List.map(List.scala:285)
    	at ml.dmlc.xgboost4j.scala.spark.XGBoost$.trainDistributed(XGBoost.scala:221)
    	at ml.dmlc.xgboost4j.scala.spark.XGBoostClassifier.train(XGBoostClassifier.scala:191)
    	at ml.dmlc.xgboost4j.scala.spark.XGBoostClassifier.train(XGBoostClassifier.scala:48)
    	at org.apache.spark.ml.Predictor.fit(Predictor.scala:118)
    	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
    	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
    	at java.lang.reflect.Method.invoke(Method.java:498)
    	at py4j.reflection.MethodInvoker.invoke(MethodInvoker.java:244)
    	at py4j.reflection.ReflectionEngine.invoke(ReflectionEngine.java:357)
    	at py4j.Gateway.invoke(Gateway.java:282)
    	at py4j.commands.AbstractCommand.invokeMethod(AbstractCommand.java:132)
    	at py4j.commands.CallCommand.execute(CallCommand.java:79)
    	at py4j.GatewayConnection.run(GatewayConnection.java:238)
    	at java.lang.Thread.run(Thread.java:748)

**Comment by hcho3** [comment]
It is now possible to specify the host IP manually (you'll need to use Scala tracker): #3833
