### ISSUE TITLE
[BLOCKING] xgboost.core.XGBoostError: b'[10:49:41] /root/repo/xgboost/src/common/hist_util.cc:152: Check failed: cut.cut.size() > 0U (0 vs. 0)

### ISSUE THREAD

**Issue by pseudotensor** [dmlc/xgboost#4085]
[failcut.zip](https://github.com/dmlc/xgboost/files/2804394/failcut.zip)

```
Traceback (most recent call last):
  File "9e6890f4-6d04-4331-b595-8e2b6c9638e9_beforexgbobj.dat.py", line 23, in <module>
    model.fit(X, y, sample_weight=sample_weight, **kwargs)
  File "/home/jon/.pyenv/versions/3.6.4/lib/python3.6/site-packages/xgboost/sklearn.py", line 738, in fit
    callbacks=callbacks)
  File "/home/jon/.pyenv/versions/3.6.4/lib/python3.6/site-packages/xgboost/training.py", line 227, in train
    xgb_model=xgb_model, callbacks=callbacks)
  File "/home/jon/.pyenv/versions/3.6.4/lib/python3.6/site-packages/xgboost/training.py", line 74, in _train_internal
    bst.update(dtrain, i, obj)
  File "/home/jon/.pyenv/versions/3.6.4/lib/python3.6/site-packages/xgboost/core.py", line 1065, in update
    dtrain.handle))
  File "/home/jon/.pyenv/versions/3.6.4/lib/python3.6/site-packages/xgboost/core.py", line 178, in _check_call
    raise XGBoostError(_LIB.XGBGetLastError())
xgboost.core.XGBoostError: b'[10:49:27] /root/repo/xgboost/src/common/hist_util.cc:152: Check failed: cut.cut.size() > 0U (0 vs. 0) \n\nStack trace returned 10 entries:\n[bt] (0) /home/jon/.pyenv/versions/3.6.4/lib/python3.6/site-packages/xgboost/./lib/libxgboost.so(_ZN4dmlc15LogMessageFatalD2Ev+0x26) [0x7f5c93f04c06]\n[bt] (1) /home/jon/.pyenv/versions/3.6.4/lib/python3.6/site-packages/xgboost/./lib/libxgboost.so(_ZN7xgboost6common16GHistIndexMatrix4InitEPNS_7DMatrixEi+0x6a6) [0x7f5c93f299e6]\n[bt] (2) /home/jon/.pyenv/versions/3.6.4/lib/python3.6/site-packages/xgboost/./lib/libxgboost.so(_ZN7xgboost4tree17QuantileHistMaker6UpdateEPNS_16HostDeviceVectorINS_6detail20GradientPairInternalIfEEEEPNS_7DMatrixERKSt6vectorIPNS_7RegTreeESaISC_EE+0x29e) [0x7f5c9402d1ae]\n[bt] (3) /home/jon/.pyenv/versions/3.6.4/lib/python3.6/site-packages/xgboost/./lib/libxgboost.so(_ZN7xgboost3gbm6GBTree13BoostNewTreesEPNS_16HostDeviceVectorINS_6detail20GradientPairInternalIfEEEEPNS_7DMatrixEiPSt6vectorISt10unique_ptrINS_7RegTreeESt14default_deleteISC_EESaISF_EE+0x777) [0x7f5c93f7fe17]\n[bt] (4) /home/jon/.pyenv/versions/3.6.4/lib/python3.6/site-packages/xgboost/./lib/libxgboost.so(_ZN7xgboost3gbm6GBTree7DoBoostEPNS_7DMatrixEPNS_16HostDeviceVectorINS_6detail20GradientPairInternalIfEEEEPNS_11ObjFunctionE+0x845) [0x7f5c93f810d5]\n[bt] (5) /home/jon/.pyenv/versions/3.6.4/lib/python3.6/site-packages/xgboost/./lib/libxgboost.so(_ZN7xgboost11LearnerImpl13UpdateOneIterEiPNS_7DMatrixE+0x400) [0x7f5c93f8f930]\n[bt] (6) /home/jon/.pyenv/versions/3.6.4/lib/python3.6/site-packages/xgboost/./lib/libxgboost.so(XGBoosterUpdateOneIter+0x35) [0x7f5c93f13385]\n[bt] (7) /usr/lib/x86_64-linux-gnu/libffi.so.6(ffi_call_unix64+0x4c) [0x7f5d5e47be40]\n[bt] (8) /usr/lib/x86_64-linux-gnu/libffi.so.6(ffi_call+0x2eb) [0x7f5d5e47b8ab]\n[bt] (9) /home/jon/.pyenv/versions/3.6.4/lib/python3.6/lib-dynload/_ctypes.cpython-36m-x86_64-linux-gnu.so(_ctypes_callproc+0x2cf) [0x7f5d5e6c1d2f]\n'
jon@mr-dl10:/data/jon/h2oai/tmp/seeds/3176099$ emacs -nw 9e6890f4-6d04-4331-b595-8e2b6c9638e9_beforexgbobj.dat.py
jon@mr-dl10:/data/jon/h2oai/tmp/seeds/3176099$ python 9e6890f4-6d04-4331-b595-8e2b6c9638e9_beforexgbobj.dat.py
[10:49:41] /root/repo/xgboost/rabit/include/rabit/./internal/../../dmlc/./logging.h:300: [10:49:41] /root/repo/xgboost/src/common/hist_util.cc:152: Check failed: cut.cut.size() > 0U (0 vs. 0) 

Stack trace returned 10 entries:
[bt] (0) /home/jon/.pyenv/versions/3.6.4/lib/python3.6/site-packages/xgboost/./lib/libxgboost.so(_ZN4dmlc15LogMessageFatalD2Ev+0x26) [0x7fde59835c06]
[bt] (1) /home/jon/.pyenv/versions/3.6.4/lib/python3.6/site-packages/xgboost/./lib/libxgboost.so(_ZN7xgboost6common16GHistIndexMatrix4InitEPNS_7DMatrixEi+0x6a6) [0x7fde5985a9e6]
[bt] (2) /home/jon/.pyenv/versions/3.6.4/lib/python3.6/site-packages/xgboost/./lib/libxgboost.so(_ZN7xgboost4tree17QuantileHistMaker6UpdateEPNS_16HostDeviceVectorINS_6detail20GradientPairInternalIfEEEEPNS_7DMatrixERKSt6vectorIPNS_7RegTreeESaISC_EE+0x29e) [0x7fde5995e1ae]
[bt] (3) /home/jon/.pyenv/versions/3.6.4/lib/python3.6/site-packages/xgboost/./lib/libxgboost.so(_ZN7xgboost3gbm6GBTree13BoostNewTreesEPNS_16HostDeviceVectorINS_6detail20GradientPairInternalIfEEEEPNS_7DMatrixEiPSt6vectorISt10unique_ptrINS_7RegTreeESt14default_deleteISC_EESaISF_EE+0x777) [0x7fde598b0e17]
[bt] (4) /home/jon/.pyenv/versions/3.6.4/lib/python3.6/site-packages/xgboost/./lib/libxgboost.so(_ZN7xgboost3gbm6GBTree7DoBoostEPNS_7DMatrixEPNS_16HostDeviceVectorINS_6detail20GradientPairInternalIfEEEEPNS_11ObjFunctionE+0x845) [0x7fde598b20d5]
[bt] (5) /home/jon/.pyenv/versions/3.6.4/lib/python3.6/site-packages/xgboost/./lib/libxgboost.so(_ZN7xgboost11LearnerImpl13UpdateOneIterEiPNS_7DMatrixE+0x400) [0x7fde598c0930]
[bt] (6) /home/jon/.pyenv/versions/3.6.4/lib/python3.6/site-packages/xgboost/./lib/libxgboost.so(XGBoosterUpdateOneIter+0x35) [0x7fde59844385]
[bt] (7) /usr/lib/x86_64-linux-gnu/libffi.so.6(ffi_call_unix64+0x4c) [0x7fdf23dace40]
[bt] (8) /usr/lib/x86_64-linux-gnu/libffi.so.6(ffi_call+0x2eb) [0x7fdf23dac8ab]
[bt] (9) /home/jon/.pyenv/versions/3.6.4/lib/python3.6/lib-dynload/_ctypes.cpython-36m-x86_64-linux-gnu.so(_ctypes_callproc+0x2cf) [0x7fdf23ff2d2f]

Traceback (most recent call last):
  File "9e6890f4-6d04-4331-b595-8e2b6c9638e9_beforexgbobj.dat.py", line 23, in <module>
    model.fit(X, y, sample_weight=sample_weight, **kwargs)
  File "/home/jon/.pyenv/versions/3.6.4/lib/python3.6/site-packages/xgboost/sklearn.py", line 738, in fit
    callbacks=callbacks)
  File "/home/jon/.pyenv/versions/3.6.4/lib/python3.6/site-packages/xgboost/training.py", line 227, in train
    xgb_model=xgb_model, callbacks=callbacks)
  File "/home/jon/.pyenv/versions/3.6.4/lib/python3.6/site-packages/xgboost/training.py", line 74, in _train_internal
    bst.update(dtrain, i, obj)
  File "/home/jon/.pyenv/versions/3.6.4/lib/python3.6/site-packages/xgboost/core.py", line 1065, in update
    dtrain.handle))
  File "/home/jon/.pyenv/versions/3.6.4/lib/python3.6/site-packages/xgboost/core.py", line 178, in _check_call
    raise XGBoostError(_LIB.XGBGetLastError())
xgboost.core.XGBoostError: b'[10:49:41] /root/repo/xgboost/src/common/hist_util.cc:152: Check failed: cut.cut.size() > 0U (0 vs. 0) \n\nStack trace returned 10 entries:\n[bt] (0) /home/jon/.pyenv/versions/3.6.4/lib/python3.6/site-packages/xgboost/./lib/libxgboost.so(_ZN4dmlc15LogMessageFatalD2Ev+0x26) [0x7fde59835c06]\n[bt] (1) /home/jon/.pyenv/versions/3.6.4/lib/python3.6/site-packages/xgboost/./lib/libxgboost.so(_ZN7xgboost6common16GHistIndexMatrix4InitEPNS_7DMatrixEi+0x6a6) [0x7fde5985a9e6]\n[bt] (2) /home/jon/.pyenv/versions/3.6.4/lib/python3.6/site-packages/xgboost/./lib/libxgboost.so(_ZN7xgboost4tree17QuantileHistMaker6UpdateEPNS_16HostDeviceVectorINS_6detail20GradientPairInternalIfEEEEPNS_7DMatrixERKSt6vectorIPNS_7RegTreeESaISC_EE+0x29e) [0x7fde5995e1ae]\n[bt] (3) /home/jon/.pyenv/versions/3.6.4/lib/python3.6/site-packages/xgboost/./lib/libxgboost.so(_ZN7xgboost3gbm6GBTree13BoostNewTreesEPNS_16HostDeviceVectorINS_6detail20GradientPairInternalIfEEEEPNS_7DMatrixEiPSt6vectorISt10unique_ptrINS_7RegTreeESt14default_deleteISC_EESaISF_EE+0x777) [0x7fde598b0e17]\n[bt] (4) /home/jon/.pyenv/versions/3.6.4/lib/python3.6/site-packages/xgboost/./lib/libxgboost.so(_ZN7xgboost3gbm6GBTree7DoBoostEPNS_7DMatrixEPNS_16HostDeviceVectorINS_6detail20GradientPairInternalIfEEEEPNS_11ObjFunctionE+0x845) [0x7fde598b20d5]\n[bt] (5) /home/jon/.pyenv/versions/3.6.4/lib/python3.6/site-packages/xgboost/./lib/libxgboost.so(_ZN7xgboost11LearnerImpl13UpdateOneIterEiPNS_7DMatrixE+0x400) [0x7fde598c0930]\n[bt] (6) /home/jon/.pyenv/versions/3.6.4/lib/python3.6/site-packages/xgboost/./lib/libxgboost.so(XGBoosterUpdateOneIter+0x35) [0x7fde59844385]\n[bt] (7) /usr/lib/x86_64-linux-gnu/libffi.so.6(ffi_call_unix64+0x4c) [0x7fdf23dace40]\n[bt] (8) /usr/lib/x86_64-linux-gnu/libffi.so.6(ffi_call+0x2eb) [0x7fdf23dac8ab]\n[bt] (9) /home/jon/.pyenv/versions/3.6.4/lib/python3.6/lib-dynload/_ctypes.cpython-36m-x86_64-linux-gnu.so(_ctypes_callproc+0x2cf) [0x7fdf23ff2d2f]\n'
```

This problem has been in xgboost for a very long time.

Generally xgboost needs to at least go back to base average (for regression) or most frequent (for classification) case as a model.  LightGBM does this with its dummy trees.

**Comment by pseudotensor** [comment]
Can edit script, kwargs are not needed.

**Comment by pseudotensor** [comment]
Agreed.  Related to #4083 as well as linked above.

**Comment by hcho3** [comment]
Working on this now.

**Comment by hcho3** [comment]
@pseudotensor I think I have a fix now. I'll be testing it against the corner cases you have uploaded so far.
