### ISSUE TITLE
[jvm-packages] Exception while getting task result: java.io.InvalidClassException

### ISSUE THREAD

**Issue by FredYao** [dmlc/xgboost#4106]
I was using "**0.82-SNAPSHOT**" version, due to #4080:
'''
resolvers += "GitHub Repo" at "https://raw.githubusercontent.com/CodingCat/xgboost/maven-repo/"
"ml.dmlc" % "xgboost4j" % "0.82-SNAPSHOT",
"ml.dmlc" % "xgboost4j-spark" % "0.82-SNAPSHOT",
'''
Spark version: 2.3.0, with Yarn
XGBoostClassifier param:
'''
val xgbParam = Map("eta" -> 0.1f,
			"max_depth" -> 5,
			"objective" -> "binary:logistic",
			"num_round" -> 20,
			"tracker_conf" -> TrackerConf(30000L, "scala")
		)
'''

I tried to train a pipeline including a XGBoostClassifier as the last stage, however, got errors:
'''
2019-02-06 10:43:21 ERROR TaskResultGetter:91 - Exception while getting task result
java.io.InvalidClassException: ml.dmlc.xgboost4j.scala.Booster; local class incompatible: stream classdesc serialVersionUID = 4771308066752525587, local class serialVersionUID = -2549553583203158078
	at java.io.ObjectStreamClass.initNonProxy(ObjectStreamClass.java:616)
	at java.io.ObjectInputStream.readNonProxyDesc(ObjectInputStream.java:1829)
	at java.io.ObjectInputStream.readClassDesc(ObjectInputStream.java:1713)
	at java.io.ObjectInputStream.readOrdinaryObject(ObjectInputStream.java:1986)
	at java.io.ObjectInputStream.readObject0(ObjectInputStream.java:1535)
	at java.io.ObjectInputStream.defaultReadFields(ObjectInputStream.java:2231)
	at java.io.ObjectInputStream.readSerialData(ObjectInputStream.java:2155)
	at java.io.ObjectInputStream.readOrdinaryObject(ObjectInputStream.java:2013)
	at java.io.ObjectInputStream.readObject0(ObjectInputStream.java:1535)
	at java.io.ObjectInputStream.readArray(ObjectInputStream.java:1919)
	at java.io.ObjectInputStream.readObject0(ObjectInputStream.java:1529)
	at java.io.ObjectInputStream.readObject(ObjectInputStream.java:422)
	at org.apache.spark.serializer.JavaDeserializationStream.readObject(JavaSerializer.scala:75)
	at org.apache.spark.serializer.JavaSerializerInstance.deserialize(JavaSerializer.scala:108)
	at org.apache.spark.scheduler.DirectTaskResult.value(TaskResult.scala:88)
	at org.apache.spark.scheduler.TaskResultGetter$$anon$3$$anonfun$run$1.apply$mcV$sp(TaskResultGetter.scala:72)
	at org.apache.spark.scheduler.TaskResultGetter$$anon$3$$anonfun$run$1.apply(TaskResultGetter.scala:63)
	at org.apache.spark.scheduler.TaskResultGetter$$anon$3$$anonfun$run$1.apply(TaskResultGetter.scala:63)
	at org.apache.spark.util.Utils$.logUncaughtExceptions(Utils.scala:1988)
	at org.apache.spark.scheduler.TaskResultGetter$$anon$3.run(TaskResultGetter.scala:62)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
'''
![screenshot from 2019-02-06 10-48-29](https://user-images.githubusercontent.com/4297204/52365640-cd0a1c00-29fc-11e9-9224-d94dee2361d0.png)

**Comment by hcho3** [comment]
@FredYao Are you trying to load models saved by previous version of XGBoost4J-Spark?

**Comment by CodingCat** [comment]
answered in https://github.com/dmlc/xgboost/issues/4080
