### ISSUE TITLE
[jvm-packages] Opening RabitTracker UI Crashed Xgboost Training Job

### ISSUE THREAD

**Issue by dyf102** [dmlc/xgboost#4200]
Hi, 
I had an issue on xgboost4j-spark 0.81: when I tried to open the UI page, I got an exception on training job.  My spark version is 2.4.0 and it is in standalone model.

> 19/03/03 20:06:58 INFO ml.dmlc.xgboost4j.java.RabitTracker$TrackerProcessLogger: Exception in thread Thread-1:
> 19/03/03 20:06:58 INFO ml.dmlc.xgboost4j.java.RabitTracker$TrackerProcessLogger: Traceback (most recent call last):
> 19/03/03 20:06:58 INFO ml.dmlc.xgboost4j.java.RabitTracker$TrackerProcessLogger:   File "/opt/conda/default/lib/python3.7/threading.py", line 917, in _bootstrap_inner
> 19/03/03 20:06:58 INFO ml.dmlc.xgboost4j.java.RabitTracker$TrackerProcessLogger:     self.run()
> 19/03/03 20:06:58 INFO ml.dmlc.xgboost4j.java.RabitTracker$TrackerProcessLogger:   File "/opt/conda/default/lib/python3.7/threading.py", line 865, in run
> 19/03/03 20:06:58 INFO ml.dmlc.xgboost4j.java.RabitTracker$TrackerProcessLogger:     self._target(*self._args, **self._kwargs)
> 19/03/03 20:06:58 INFO ml.dmlc.xgboost4j.java.RabitTracker$TrackerProcessLogger:   File "/tmp/tracker6269121579213963786.py", line 324, in run
> 19/03/03 20:06:58 INFO ml.dmlc.xgboost4j.java.RabitTracker$TrackerProcessLogger:     self.accept_slaves(nslave)
> 19/03/03 20:06:58 INFO ml.dmlc.xgboost4j.java.RabitTracker$TrackerProcessLogger:   File "/tmp/tracker6269121579213963786.py", line 268, in accept_slaves
> 19/03/03 20:06:58 INFO ml.dmlc.xgboost4j.java.RabitTracker$TrackerProcessLogger:     s = SlaveEntry(fd, s_addr)
> 19/03/03 20:06:58 INFO ml.dmlc.xgboost4j.java.RabitTracker$TrackerProcessLogger:   File "/tmp/tracker6269121579213963786.py", line 64, in __init__
> 19/03/03 20:06:58 INFO ml.dmlc.xgboost4j.java.RabitTracker$TrackerProcessLogger:     assert magic == kMagic, 'invalid magic number=%d from %s' % (magic, self.host)
> 19/03/03 20:06:58 INFO ml.dmlc.xgboost4j.java.RabitTracker$TrackerProcessLogger: AssertionError: invalid magic number=542393671 from 10.128.0.41
> 19/03/03 20:06:58 INFO ml.dmlc.xgboost4j.java.RabitTracker$TrackerProcessLogger:
> 19/03/03 20:06:58 INFO ml.dmlc.xgboost4j.java.RabitTracker: Tracker Process ends with exit code 0
> 19/03/03 20:06:58 INFO ml.dmlc.xgboost4j.java.RabitTracker$TrackerProcessLogger: Tracker Process ends with exit code 0
> 19/03/03 20:06:58 INFO XGBoostSpark: Rabit returns with exit code 0
> 19/03/03 20:07:24 ERROR org.apache.spark.scheduler.cluster.YarnScheduler: Lost executor 3 on cluster-385c-m.c.ibdsg-app04-1becXXXX..internal: Container marked as failed: container_1551641555777_0008_01_000004 on host: cluster-385c-m.c.ibdsg-app04-1becXXXX.internal. Exit status: 255. Diagnostics: [2019-03-03 20:07:24.601]Exception from container-launch.

**Comment by hcho3** [comment]
I don't think we support Spark 2.4.0. Can you use Spark 2.3.x?

**Comment by dyf102** [comment]
@hcho3 I have tried Spark 2.3.2 with 0.8.2 Xgboost Spark. It still has the same issue.

The image that I am using is 
Cloud Dataproc image version: 1.3 (Debian 9, Hadoop 2.9, Spark 2.3)
on Google Cloud DataProc

**Comment by CodingCat** [comment]
Might be some python version issue, looks like the tracker cannot even interpret a integer sent from workers correctly

**Comment by dyf102** [comment]
@CodingCat The python version is Python 2.7.13 [GCC 6.3.0 20170516] on linux2

**Comment by shuyanmei** [comment]
@CodingCat @hcho3 
I have the same issue for both scala and python rabbit tracker

[ERROR] [03/08/2019 19:47:51.466] [RabitTracker-akka.actor.default-dispatcher-3] [LocalActorRefProvider(akka://RabitTracker)] guardian failed, shutting down system
java.lang.AssertionError: assertion failed
	at scala.Predef$.assert(Predef.scala:156)
	at ml.dmlc.xgboost4j.scala.rabit.handler.RabitWorkerHandler$$anonfun$2.applyOrElse(RabitWorkerHandler.scala:116)
	at ml.dmlc.xgboost4j.scala.rabit.handler.RabitWorkerHandler$$anonfun$2.applyOrElse(RabitWorkerHandler.scala:114)
	at scala.runtime.AbstractPartialFunction.apply(AbstractPartialFunction.scala:36)
	at akka.actor.FSM$class.processEvent(FSM.scala:604)
	at ml.dmlc.xgboost4j.scala.rabit.handler.RabitWorkerHandler.processEvent(RabitWorkerHandler.scala:39)
	at akka.actor.FSM$class.akka$actor$FSM$$processMsg(FSM.scala:598)
	at akka.actor.FSM$$anonfun$receive$1.applyOrElse(FSM.scala:592)
	at akka.actor.Actor$class.aroundReceive(Actor.scala:467)
	at ml.dmlc.xgboost4j.scala.rabit.handler.RabitWorkerHandler.aroundReceive(RabitWorkerHandler.scala:39)
	at akka.actor.ActorCell.receiveMessage(ActorCell.scala:516)
	at akka.actor.ActorCell.invoke(ActorCell.scala:487)
	at akka.dispatch.Mailbox.processMailbox(Mailbox.scala:238)
	at akka.dispatch.Mailbox.run(Mailbox.scala:220)
	at akka.dispatch.ForkJoinExecutorConfigurator$AkkaForkJoinTask.exec(AbstractDispatcher.scala:397)
	at scala.concurrent.forkjoin.ForkJoinTask.doExec(ForkJoinTask.java:260)
	at scala.concurrent.forkjoin.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1339)
	at scala.concurrent.forkjoin.ForkJoinPool.runWorker(ForkJoinPool.java:1979)
	at scala.concurrent.forkjoin.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:107)

[ERROR] [03/08/2019 19:47:51.466] [RabitTracker-akka.actor.default-dispatcher-3] [akka://RabitTracker/user] assertion failed
java.lang.AssertionError: assertion failed
	at scala.Predef$.assert(Predef.scala:156)
	at ml.dmlc.xgboost4j.scala.rabit.handler.RabitWorkerHandler$$anonfun$2.applyOrElse(RabitWorkerHandler.scala:116)
	at ml.dmlc.xgboost4j.scala.rabit.handler.RabitWorkerHandler$$anonfun$2.applyOrElse(RabitWorkerHandler.scala:114)
	at scala.runtime.AbstractPartialFunction.apply(AbstractPartialFunction.scala:36)
	at akka.actor.FSM$class.processEvent(FSM.scala:604)
	at ml.dmlc.xgboost4j.scala.rabit.handler.RabitWorkerHandler.processEvent(RabitWorkerHandler.scala:39)
	at akka.actor.FSM$class.akka$actor$FSM$$processMsg(FSM.scala:598)
	at akka.actor.FSM$$anonfun$receive$1.applyOrElse(FSM.scala:592)
	at akka.actor.Actor$class.aroundReceive(Actor.scala:467)
	at ml.dmlc.xgboost4j.scala.rabit.handler.RabitWorkerHandler.aroundReceive(RabitWorkerHandler.scala:39)
	at akka.actor.ActorCell.receiveMessage(ActorCell.scala:516)
	at akka.actor.ActorCell.invoke(ActorCell.scala:487)
	at akka.dispatch.Mailbox.processMailbox(Mailbox.scala:238)
	at akka.dispatch.Mailbox.run(Mailbox.scala:220)
	at akka.dispatch.ForkJoinExecutorConfigurator$AkkaForkJoinTask.exec(AbstractDispatcher.scala:397)
	at scala.concurrent.forkjoin.ForkJoinTask.doExec(ForkJoinTask.java:260)
	at scala.concurrent.forkjoin.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1339)
	at scala.concurrent.forkjoin.ForkJoinPool.runWorker(ForkJoinPool.java:1979)
	at scala.concurrent.forkjoin.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:107)

**Comment by CodingCat** [comment]
@cq this is an issue with rabit, where the tracker cannot interpret the magic number sent from workers, can you help to debug?

**Comment by CodingCat** [comment]
ping @chenqin

**Comment by chenqin** [comment]
@shuyanmei is the issue still relevant, if so can you try latest python tracker (via python3)
