### ISSUE TITLE
[jvm-packages] BinaryClassificationEvaluator fails with ArrayIndexOutOfBoundException while using XGBoostClassifier

### ISSUE THREAD

**Issue by neeleshkshukla** [dmlc/xgboost#4225]
BinaryClassificationEvaluator fails with ArratIndexOutOfBoundException:

2019-02-05T06:32:00.610Z] spark.org.apache.spark.scheduler.TaskSetManager WARN: appId: 0-AB, du: 1, message: Lost task 0.0 in stage 1012.0 (TID 1705, yarn, executor 1): java.lang.ArrayIndexOutOfBoundsException: 1    at org.apache.spark.ml.linalg.DenseVector.apply(Vectors.scala:462)    at org.apache.spark.ml.evaluation.BinaryClassificationEvaluator$$anonfun$1.apply(BinaryClassificationEvaluator.scala:82)    at org.apache.spark.ml.evaluation.BinaryClassificationEvaluator$$anonfun$1.apply(BinaryClassificationEvaluator.scala:81)    at scala.collection.Iterator$$anon$11.next(Iterator.scala:409)    at org.apache.spark.util.collection.ExternalSorter.insertAll(ExternalSorter.scala:193)    at org.apache.spark.shuffle.sort.SortShuffleWriter.write(SortShuffleWriter.scala:63)    at org.apache.spark.scheduler.ShuffleMapTask.runTask(ShuffleMapTask.scala:96)    at org.apache.spark.scheduler.ShuffleMapTask.runTask(ShuffleMapTask.scala:53)    at org.apache.spark.scheduler.Task.run(Task.scala:109)    at org.apache.spark.executor.Executor$TaskRunner.run(Executor.scala:345)    at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)    at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)    at java.lang.Thread.run(Thread.java:745)

There are two tricks to fix this issue:
1. Provide num_classes parameter with value 2. It works but it doesn't see right.
2. Use MulticlassClassificationEvaluator which we don't want as it has different performance metrics than BinaryClassificationEvaluator.

Fix 1 leads to another issue: If I am providing fix parameters, it is mandatory to provide the objective function otherwise XGBoostClassifier throws the error.
[12:51:54] Tree method is automatically selected to be 'approx' for distributed training.
19/03/07 12:51:56 INFO RabitTracker$TrackerProcessLogger: 2019-03-07 12:51:56,946 DEBUG Recieve shutdown signal from 0
19/03/07 12:51:56 INFO RabitTracker$TrackerProcessLogger: 2019-03-07 12:51:56,946 INFO @tracker All nodes finishes job
19/03/07 12:51:56 INFO RabitTracker$TrackerProcessLogger: 2019-03-07 12:51:56,946 INFO @tracker 2.01121807098 secs between node start and job finish
Exception in thread "spark-listener-group-shared" ErrorInXGBoostTraining: ExecutorLost during XGBoost Training: ml.dmlc.xgboost4j.java.XGBoostError: [12:51:54] /Users/nanzhu/code/xgboost/src/objective/regression_obj.cu:66: Check failed: preds.Size() == info.labels_.Size() (64 vs. 32) labels are not correctly providedpreds.size=64, label.size=32
 
Stack trace returned 7 entries:
[bt] (0) 0   libxgboost4j8899704699325273211.dylib 0x0000000128e1b7d6 dmlc::StackTrace() + 246
[bt] (1) 1   libxgboost4j8899704699325273211.dylib 0x0000000128e1b58f dmlc::LogMessageFatal::~LogMessageFatal() + 47
[bt] (2) 2   libxgboost4j8899704699325273211.dylib 0x0000000128ea5a5d xgboost::obj::RegLossObj<xgboost::obj::LinearSquareLoss>::GetGradient(xgboost::HostDeviceVector<float> const&, xgboost::MetaInfo const&, int, xgboost::HostDeviceVector<xgboost::detail::GradientPairInternal<float> >*) + 589
[bt] (3) 3   libxgboost4j8899704699325273211.dylib 0x0000000128e7c144 xgboost::LearnerImpl::UpdateOneIter(int, xgboost::DMatrix*) + 996
[bt] (4) 4   libxgboost4j8899704699325273211.dylib 0x0000000128e24464 XGBoosterUpdateOneIter + 180
[bt] (5) 5   ???                                 0x000000010b225667 0x0 + 4481767015
[bt] (6) 6   ???                                 0x000000010b214d00 0x0 + 4481699072
 
 
    at ml.dmlc.xgboost4j.java.XGBoostJNI.checkCall(XGBoostJNI.java:48)
    at ml.dmlc.xgboost4j.java.Booster.update(Booster.java:124)
    at ml.dmlc.xgboost4j.java.XGBoost.train(XGBoost.java:182)
    at ml.dmlc.xgboost4j.scala.XGBoost$.train(XGBoost.scala:64)
    at ml.dmlc.xgboost4j.scala.spark.XGBoost$.ml$dmlc$xgboost4j$scala$spark$XGBoost$$buildDistributedBooster(XGBoost.scala:141)
    at ml.dmlc.xgboost4j.scala.spark.XGBoost$$anonfun$trainDistributed$4$$anonfun$12.apply(XGBoost.scala:279)
    at ml.dmlc.xgboost4j.scala.spark.XGBoost$$anonfun$trainDistributed$4$$anonfun$12.apply(XGBoost.scala:275)
    at org.apache.spark.rdd.RDD$$anonfun$mapPartitions$1$$anonfun$apply$23.apply(RDD.scala:801)
    at org.apache.spark.rdd.RDD$$anonfun$mapPartitions$1$$anonfun$apply$23.apply(RDD.scala:801)
    at org.apache.spark.rdd.MapPartitionsRDD.compute(MapPartitionsRDD.scala:52)
    at org.apache.spark.rdd.RDD.computeOrReadCheckpoint(RDD.scala:324)
    at org.apache.spark.rdd.RDD$$anonfun$7.apply(RDD.scala:337)
    at org.apache.spark.rdd.RDD$$anonfun$7.apply(RDD.scala:335)
    at org.apache.spark.storage.BlockManager$$anonfun$doPutIterator$1.apply(BlockManager.scala:1165)
    at org.apache.spark.storage.BlockManager$$anonfun$doPutIterator$1.apply(BlockManager.scala:1156)
    at org.apache.spark.storage.BlockManager.doPut(BlockManager.scala:1091)
    at org.apache.spark.storage.BlockManager.doPutIterator(BlockManager.scala:1156)
    at org.apache.spark.storage.BlockManager.getOrElseUpdate(BlockManager.scala:882)
    at org.apache.spark.rdd.RDD.getOrCompute(RDD.scala:335)
    at org.apache.spark.rdd.RDD.iterator(RDD.scala:286)
    at org.apache.spark.scheduler.ResultTask.runTask(ResultTask.scala:90)
    at org.apache.spark.scheduler.Task.run(Task.scala:121)
    at org.apache.spark.executor.Executor$TaskRunner$$anonfun$10.apply(Executor.scala:402)
    at org.apache.spark.util.Utils$.tryWithSafeFinally(Utils.scala:1360)
    at org.apache.spark.executor.Executor$TaskRunner.run(Executor.scala:408)
    at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
    at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
    at java.lang.Thread.run(Thread.java:748)

**Comment by thvasilo** [comment]
My guess is this would be an issue of data formatting. In the non-distributed version XGB expects the labels for a binary problem to be 0 and 1 (not -1/+1 or any other format).

Is that the case for your data?

**Comment by neeleshkshukla** [comment]
Oh okay. Let me check.

**Comment by rachelsunrh** [comment]
hi, I meet the same problem, can you tell me how to solve it ? I have checked my data, the labels are 0 and 1
Lost task 0.0 in stage 6.0 (TID 6, 9.10.135.90, executor 1): ml.dmlc.xgboost4j.java.XGBoostError: [21:47:23] /data/angel/wenbinwei/xgboost-tdw/src/objective/regression_obj.cu:66: Check failed: preds.Size() == info.labels_.Size() (13026 vs. 6513) : labels are not correctly providedpreds.size=13026, label.size=6513
Stack trace:
  [bt] (0) /data7/yarnenv/local/usercache/lhotse/appcache/application_1555301652009_20695514/container_e10_1555301652009_20695514_01_000002/tmp/libxgboost4j_xeon4705135393324394044.so(dmlc::LogMessageFatal::~LogMessageFatal()+0x22) [0x7f94a7de7422]
  [bt] (1) /data7/yarnenv/local/usercache/lhotse/appcache/application_1555301652009_20695514/container_e10_1555301652009_20695514_01_000002/tmp/libxgboost4j_xeon4705135393324394044.so(xgboost::obj::RegLossObj<xgboost::obj::LogisticClassification>::GetGradient(xgboost::HostDeviceVector<float> const&, xgboost::MetaInfo const&, int, xgboost::HostDeviceVector<xgboost::detail::GradientPairInternal<float> >*)+0x20e) [0x7f94a7ef012e]
  [bt] (2) /data7/yarnenv/local/usercache/lhotse/appcache/application_1555301652009_20695514/container_e10_1555301652009_20695514_01_000002/tmp/libxgboost4j_xeon4705135393324394044.so(xgboost::LearnerImpl::UpdateOneIter(int, xgboost::DMatrix*)+0x362) [0x7f94a7e7dac2]
  [bt] (3) /data7/yarnenv/local/usercache/lhotse/appcache/application_1555301652009_20695514/container_e10_1555301652009_20695514_01_000002/tmp/libxgboost4j_xeon4705135393324394044.so(XGBoosterUpdateOneIter+0x35) [0x7f94a7dee9d5]
  [bt] (4) [0x7f94d5018667]


	at ml.dmlc.xgboost4j.java.XGBoostJNI.checkCall(XGBoostJNI.java:48)
	at ml.dmlc.xgboost4j.java.Booster.update(Booster.java:124)
	at ml.dmlc.xgboost4j.java.XGBoost.train(XGBoost.java:188)
	at ml.dmlc.xgboost4j.scala.XGBoost$.train(XGBoost.scala:64)
	at ml.dmlc.xgboost4j.scala.spark.XGBoost$.ml$dmlc$xgboost4j$scala$spark$XGBoost$$buildDistributedBooster(XGBoost.scala:141)
	at ml.dmlc.xgboost4j.scala.spark.XGBoost$$anonfun$trainDistributed$4$$anonfun$12.apply(XGBoost.scala:279)
	at ml.dmlc.xgboost4j.scala.spark.XGBoost$$anonfun$trainDistributed$4$$anonfun$12.apply(XGBoost.scala:275)
	at org.apache.spark.rdd.RDD$$anonfun$mapPartitions$1$$anonfun$apply$23.apply(RDD.scala:800)
	at org.apache.spark.rdd.RDD$$anonfun$mapPartitions$1$$anonfun$apply$23.apply(RDD.scala:800)
	at org.apache.spark.rdd.MapPartitionsRDD.compute(MapPartitionsRDD.scala:38)
	at org.apache.spark.rdd.RDD.computeOrReadCheckpoint(RDD.scala:324)
	at org.apache.spark.rdd.RDD$$anonfun$7.apply(RDD.scala:337)
	at org.apache.spark.rdd.RDD$$anonfun$7.apply(RDD.scala:335)
	at org.apache.spark.storage.BlockManager$$anonfun$doPutIterator$1.apply(BlockManager.scala:1092)
	at org.apache.spark.storage.BlockManager$$anonfun$doPutIterator$1.apply(BlockManager.scala:1083)
	at org.apache.spark.storage.BlockManager.doPut(BlockManager.scala:1018)
	at org.apache.spark.storage.BlockManager.doPutIterator(BlockManager.scala:1083)
	at org.apache.spark.storage.BlockManager.getOrElseUpdate(BlockManager.scala:809)
	at org.apache.spark.rdd.RDD.getOrCompute(RDD.scala:335)
	at org.apache.spark.rdd.RDD.iterator(RDD.scala:286)
	at org.apache.spark.scheduler.ResultTask.runTask(ResultTask.scala:87)
	at org.apache.spark.scheduler.Task.run(Task.scala:109)
	at org.apache.spark.executor.Executor$TaskRunner.run(Executor.scala:345)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
