### ISSUE TITLE
[jvm-package] exception on start

### ISSUE THREAD

**Issue by kirill-linnik** [dmlc/xgboost#4269]
Hi all,

First of all, thanks for making XGBoost available in Spark. Secondly, thanks for Windows support. 
I use version 0.81 with Windows drivers, and yesterday it worked just fine, while today, without any code change, it went to this:
```
2019-03-17 16:31:15.235  INFO 8112 --- [er-event-loop-0] o.apache.spark.scheduler.TaskSetManager  : Starting task 3.0 in stage 8.0 (TID 409, localhost, executor driver, partition 3, PROCESS_LOCAL, 39539587 bytes)
2019-03-17 16:31:15.235  WARN 8112 --- [ool-1-worker-13] XGBoostSpark                             : Unable to read total number of alive cores from REST API.Health Check will be ignored.
java.io.IOException: Server returned HTTP response code: 500 for URL: http://<server_name_censored>:4040/api/v1/applications/local-1552832991922/executors
	at sun.net.www.protocol.http.HttpURLConnection.getInputStream0(HttpURLConnection.java:1894)
	at sun.net.www.protocol.http.HttpURLConnection.getInputStream(HttpURLConnection.java:1492)
	at java.net.URL.openStream(URL.java:1045)
	at org.codehaus.jackson.JsonFactory._optimizedStreamFromURL(JsonFactory.java:935)
	at org.codehaus.jackson.JsonFactory.createJsonParser(JsonFactory.java:530)
	at org.codehaus.jackson.map.ObjectMapper.readTree(ObjectMapper.java:1590)
	at org.apache.spark.SparkParallelismTracker.org$apache$spark$SparkParallelismTracker$$numAliveCores(SparkParallelismTracker.scala:55)
	at org.apache.spark.SparkParallelismTracker$$anonfun$execute$1.apply$mcZ$sp(SparkParallelismTracker.scala:104)
	at org.apache.spark.SparkParallelismTracker$$anonfun$1.apply$mcV$sp(SparkParallelismTracker.scala:73)
	at org.apache.spark.SparkParallelismTracker$$anonfun$1.apply(SparkParallelismTracker.scala:73)
	at org.apache.spark.SparkParallelismTracker$$anonfun$1.apply(SparkParallelismTracker.scala:73)
	at scala.concurrent.impl.Future$PromiseCompletingRunnable.liftedTree1$1(Future.scala:24)
	at scala.concurrent.impl.Future$PromiseCompletingRunnable.run$$$capture(Future.scala:24)
	at scala.concurrent.impl.Future$PromiseCompletingRunnable.run(Future.scala)
	at scala.concurrent.impl.ExecutionContextImpl$AdaptedForkJoinTask.exec(ExecutionContextImpl.scala:121)
	at scala.concurrent.forkjoin.ForkJoinTask.doExec(ForkJoinTask.java:260)
	at scala.concurrent.forkjoin.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1339)
	at scala.concurrent.forkjoin.ForkJoinPool.runWorker(ForkJoinPool.java:1979)
	at scala.concurrent.forkjoin.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:107)
2019-03-17 16:31:15.235  INFO 8112 --- [   scheduling-1] ml.dmlc.xgboost4j.java.RabitTracker      : Tracker Process ends with exit code 1
2019-03-17 16:31:15.235  INFO 8112 --- [   scheduling-1] XGBoostSpark                             : Rabit returns with exit code 1
2019-03-17 16:31:15.235 ERROR 8112 --- [      Thread-31] ml.dmlc.xgboost4j.java.RabitTracker      : Uncaught exception thrown by worker:

java.lang.InterruptedException: null
	at java.util.concurrent.locks.AbstractQueuedSynchronizer.doAcquireSharedInterruptibly(AbstractQueuedSynchronizer.java:998) ~[na:1.8.0_201]
	at java.util.concurrent.locks.AbstractQueuedSynchronizer.acquireSharedInterruptibly(AbstractQueuedSynchronizer.java:1304) ~[na:1.8.0_201]
	at scala.concurrent.impl.Promise$DefaultPromise.tryAwait(Promise.scala:206) ~[scala-library-2.11.12.jar:na]
	at scala.concurrent.impl.Promise$DefaultPromise.ready(Promise.scala:222) ~[scala-library-2.11.12.jar:na]
	at scala.concurrent.impl.Promise$DefaultPromise.ready(Promise.scala:157) ~[scala-library-2.11.12.jar:na]
	at org.apache.spark.util.ThreadUtils$.awaitReady(ThreadUtils.scala:222) ~[spark-core_2.11-2.3.3.jar:2.3.3]
	at org.apache.spark.scheduler.DAGScheduler.runJob(DAGScheduler.scala:633) ~[spark-core_2.11-2.3.3.jar:2.3.3]
	at org.apache.spark.SparkContext.runJob(SparkContext.scala:2034) ~[spark-core_2.11-2.3.3.jar:2.3.3]
	at org.apache.spark.SparkContext.runJob(SparkContext.scala:2055) ~[spark-core_2.11-2.3.3.jar:2.3.3]
	at org.apache.spark.SparkContext.runJob(SparkContext.scala:2074) ~[spark-core_2.11-2.3.3.jar:2.3.3]
	at org.apache.spark.SparkContext.runJob(SparkContext.scala:2099) ~[spark-core_2.11-2.3.3.jar:2.3.3]
	at org.apache.spark.rdd.RDD$$anonfun$foreachPartition$1.apply(RDD.scala:935) ~[spark-core_2.11-2.3.3.jar:2.3.3]
	at org.apache.spark.rdd.RDD$$anonfun$foreachPartition$1.apply(RDD.scala:933) ~[spark-core_2.11-2.3.3.jar:2.3.3]
	at org.apache.spark.rdd.RDDOperationScope$.withScope(RDDOperationScope.scala:151) ~[spark-core_2.11-2.3.3.jar:2.3.3]
	at org.apache.spark.rdd.RDDOperationScope$.withScope(RDDOperationScope.scala:112) ~[spark-core_2.11-2.3.3.jar:2.3.3]
	at org.apache.spark.rdd.RDD.withScope(RDD.scala:363) ~[spark-core_2.11-2.3.3.jar:2.3.3]
	at org.apache.spark.rdd.RDD.foreachPartition(RDD.scala:933) ~[spark-core_2.11-2.3.3.jar:2.3.3]
	at ml.dmlc.xgboost4j.scala.spark.XGBoost$$anonfun$trainDistributed$4$$anon$1.run(XGBoost.scala:287) ~[xgboost4j-spark-0.81.jar:na]

2019-03-17 16:31:15.235 ERROR 8112 --- [   scheduling-1] o.s.s.s.TaskUtils$LoggingErrorHandler    : Unexpected error occurred in scheduled task.

org.apache.spark.SparkException: Exception thrown in awaitResult: 
	at org.apache.spark.util.ThreadUtils$.awaitResult(ThreadUtils.scala:205) ~[spark-core_2.11-2.3.3.jar:2.3.3]
	at org.apache.spark.ml.tuning.CrossValidator$$anonfun$4$$anonfun$6.apply(CrossValidator.scala:164) ~[spark-mllib_2.11-2.3.3.jar:2.3.3]
	at org.apache.spark.ml.tuning.CrossValidator$$anonfun$4$$anonfun$6.apply(CrossValidator.scala:164) ~[spark-mllib_2.11-2.3.3.jar:2.3.3]
	at scala.collection.TraversableLike$$anonfun$map$1.apply(TraversableLike.scala:234) ~[scala-library-2.11.12.jar:na]
	at scala.collection.TraversableLike$$anonfun$map$1.apply(TraversableLike.scala:234) ~[scala-library-2.11.12.jar:na]
	at scala.collection.IndexedSeqOptimized$class.foreach(IndexedSeqOptimized.scala:33) ~[scala-library-2.11.12.jar:na]
	at scala.collection.mutable.ArrayOps$ofRef.foreach(ArrayOps.scala:186) ~[scala-library-2.11.12.jar:na]
	at scala.collection.TraversableLike$class.map(TraversableLike.scala:234) ~[scala-library-2.11.12.jar:na]
	at scala.collection.mutable.ArrayOps$ofRef.map(ArrayOps.scala:186) ~[scala-library-2.11.12.jar:na]
	at org.apache.spark.ml.tuning.CrossValidator$$anonfun$4.apply(CrossValidator.scala:164) ~[spark-mllib_2.11-2.3.3.jar:2.3.3]
	at org.apache.spark.ml.tuning.CrossValidator$$anonfun$4.apply(CrossValidator.scala:144) ~[spark-mllib_2.11-2.3.3.jar:2.3.3]
	at scala.collection.TraversableLike$$anonfun$map$1.apply(TraversableLike.scala:234) ~[scala-library-2.11.12.jar:na]
	at scala.collection.TraversableLike$$anonfun$map$1.apply(TraversableLike.scala:234) ~[scala-library-2.11.12.jar:na]
	at scala.collection.IndexedSeqOptimized$class.foreach(IndexedSeqOptimized.scala:33) ~[scala-library-2.11.12.jar:na]
	at scala.collection.mutable.ArrayOps$ofRef.foreach(ArrayOps.scala:186) ~[scala-library-2.11.12.jar:na]
	at scala.collection.TraversableLike$class.map(TraversableLike.scala:234) ~[scala-library-2.11.12.jar:na]
	at scala.collection.mutable.ArrayOps$ofRef.map(ArrayOps.scala:186) ~[scala-library-2.11.12.jar:na]
	at org.apache.spark.ml.tuning.CrossValidator.fit(CrossValidator.scala:144) ~[spark-mllib_2.11-2.3.3.jar:2.3.3]
	at am.job.AccountScoringAnalyzer.trainAccountScoringModel(AccountScoringAnalyzer.java:89) ~[classes/:na]
	at am.job.AccountScoringAnalyzer.performAnalysis(AccountScoringAnalyzer.java:59) ~[classes/:na]
	at am.job.MainDataAnalyzerJob.performDataAnalyze(MainDataAnalyzerJob.java:35) ~[classes/:na]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[na:1.8.0_201]
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[na:1.8.0_201]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[na:1.8.0_201]
	at java.lang.reflect.Method.invoke(Method.java:498) ~[na:1.8.0_201]
	at org.springframework.scheduling.support.ScheduledMethodRunnable.run(ScheduledMethodRunnable.java:84) ~[spring-context-5.1.4.RELEASE.jar:5.1.4.RELEASE]
	at org.springframework.scheduling.support.DelegatingErrorHandlingRunnable.run(DelegatingErrorHandlingRunnable.java:54) ~[spring-context-5.1.4.RELEASE.jar:5.1.4.RELEASE]
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) [na:1.8.0_201]
	at java.util.concurrent.FutureTask.runAndReset$$$capture(FutureTask.java:308) [na:1.8.0_201]
	at java.util.concurrent.FutureTask.runAndReset(FutureTask.java) [na:1.8.0_201]
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$301(ScheduledThreadPoolExecutor.java:180) [na:1.8.0_201]
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:294) [na:1.8.0_201]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) [na:1.8.0_201]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) [na:1.8.0_201]
	at java.lang.Thread.run(Thread.java:748) [na:1.8.0_201]
Caused by: ml.dmlc.xgboost4j.java.XGBoostError: XGBoostModel training failed
	at ml.dmlc.xgboost4j.scala.spark.XGBoost$.ml$dmlc$xgboost4j$scala$spark$XGBoost$$postTrackerReturnProcessing(XGBoost.scala:364) ~[xgboost4j-spark-0.81.jar:na]
	at ml.dmlc.xgboost4j.scala.spark.XGBoost$$anonfun$trainDistributed$4.apply(XGBoost.scala:294) ~[xgboost4j-spark-0.81.jar:na]
	at ml.dmlc.xgboost4j.scala.spark.XGBoost$$anonfun$trainDistributed$4.apply(XGBoost.scala:256) ~[xgboost4j-spark-0.81.jar:na]
	at scala.collection.TraversableLike$$anonfun$map$1.apply(TraversableLike.scala:234) ~[scala-library-2.11.12.jar:na]
	at scala.collection.TraversableLike$$anonfun$map$1.apply(TraversableLike.scala:234) ~[scala-library-2.11.12.jar:na]
	at scala.collection.immutable.List.foreach(List.scala:392) ~[scala-library-2.11.12.jar:na]
	at scala.collection.TraversableLike$class.map(TraversableLike.scala:234) ~[scala-library-2.11.12.jar:na]
	at scala.collection.immutable.List.map(List.scala:296) ~[scala-library-2.11.12.jar:na]
	at ml.dmlc.xgboost4j.scala.spark.XGBoost$.trainDistributed(XGBoost.scala:255) ~[xgboost4j-spark-0.81.jar:na]
	at ml.dmlc.xgboost4j.scala.spark.XGBoostRegressor.train(XGBoostRegressor.scala:195) ~[xgboost4j-spark-0.81.jar:na]
	at ml.dmlc.xgboost4j.scala.spark.XGBoostRegressor.train(XGBoostRegressor.scala:48) ~[xgboost4j-spark-0.81.jar:na]
	at org.apache.spark.ml.Predictor.fit(Predictor.scala:118) ~[spark-mllib_2.11-2.3.3.jar:2.3.3]
	at org.apache.spark.ml.Predictor.fit(Predictor.scala:82) ~[spark-mllib_2.11-2.3.3.jar:2.3.3]
	at org.apache.spark.ml.Pipeline$$anonfun$fit$2.apply(Pipeline.scala:153) ~[spark-mllib_2.11-2.3.3.jar:2.3.3]
	at org.apache.spark.ml.Pipeline$$anonfun$fit$2.apply(Pipeline.scala:149) ~[spark-mllib_2.11-2.3.3.jar:2.3.3]
	at scala.collection.Iterator$class.foreach(Iterator.scala:891) ~[scala-library-2.11.12.jar:na]
	at scala.collection.AbstractIterator.foreach(Iterator.scala:1334) ~[scala-library-2.11.12.jar:na]
	at scala.collection.IterableViewLike$Transformed$class.foreach(IterableViewLike.scala:44) ~[scala-library-2.11.12.jar:na]
	at scala.collection.SeqViewLike$AbstractTransformed.foreach(SeqViewLike.scala:37) ~[scala-library-2.11.12.jar:na]
	at org.apache.spark.ml.Pipeline.fit(Pipeline.scala:149) ~[spark-mllib_2.11-2.3.3.jar:2.3.3]
	at org.apache.spark.ml.Pipeline.fit(Pipeline.scala:96) ~[spark-mllib_2.11-2.3.3.jar:2.3.3]
	at org.apache.spark.ml.Estimator.fit(Estimator.scala:61) ~[spark-mllib_2.11-2.3.3.jar:2.3.3]
	at org.apache.spark.ml.tuning.CrossValidator$$anonfun$4$$anonfun$5$$anonfun$apply$1.apply$mcD$sp(CrossValidator.scala:152) ~[spark-mllib_2.11-2.3.3.jar:2.3.3]
	at org.apache.spark.ml.tuning.CrossValidator$$anonfun$4$$anonfun$5$$anonfun$apply$1.apply(CrossValidator.scala:151) ~[spark-mllib_2.11-2.3.3.jar:2.3.3]
	at org.apache.spark.ml.tuning.CrossValidator$$anonfun$4$$anonfun$5$$anonfun$apply$1.apply(CrossValidator.scala:151) ~[spark-mllib_2.11-2.3.3.jar:2.3.3]
	at scala.concurrent.impl.Future$PromiseCompletingRunnable.liftedTree1$1(Future.scala:24) ~[scala-library-2.11.12.jar:na]
	at scala.concurrent.impl.Future$PromiseCompletingRunnable.run$$$capture(Future.scala:24) ~[scala-library-2.11.12.jar:na]
	at scala.concurrent.impl.Future$PromiseCompletingRunnable.run(Future.scala) ~[scala-library-2.11.12.jar:na]
	at org.spark_project.guava.util.concurrent.MoreExecutors$SameThreadExecutorService.execute(MoreExecutors.java:293) ~[spark-network-common_2.11-2.3.3.jar:2.3.3]
	at scala.concurrent.impl.ExecutionContextImpl$$anon$1.execute(ExecutionContextImpl.scala:136) ~[scala-library-2.11.12.jar:na]
	at scala.concurrent.impl.Future$.apply(Future.scala:31) ~[scala-library-2.11.12.jar:na]
	at scala.concurrent.Future$.apply(Future.scala:494) ~[scala-library-2.11.12.jar:na]
	at org.apache.spark.ml.tuning.CrossValidator$$anonfun$4$$anonfun$5.apply(CrossValidator.scala:160) ~[spark-mllib_2.11-2.3.3.jar:2.3.3]
	at org.apache.spark.ml.tuning.CrossValidator$$anonfun$4$$anonfun$5.apply(CrossValidator.scala:150) ~[spark-mllib_2.11-2.3.3.jar:2.3.3]
	at scala.collection.TraversableLike$$anonfun$map$1.apply(TraversableLike.scala:234) ~[scala-library-2.11.12.jar:na]
	at scala.collection.TraversableLike$$anonfun$map$1.apply(TraversableLike.scala:234) ~[scala-library-2.11.12.jar:na]
	at scala.collection.IndexedSeqOptimized$class.foreach(IndexedSeqOptimized.scala:33) ~[scala-library-2.11.12.jar:na]
	at scala.collection.mutable.ArrayOps$ofRef.foreach(ArrayOps.scala:186) ~[scala-library-2.11.12.jar:na]
	at scala.collection.TraversableLike$class.map(TraversableLike.scala:234) ~[scala-library-2.11.12.jar:na]
	at scala.collection.mutable.ArrayOps$ofRef.map(ArrayOps.scala:186) ~[scala-library-2.11.12.jar:na]
	at org.apache.spark.ml.tuning.CrossValidator$$anonfun$4.apply(CrossValidator.scala:150) ~[spark-mllib_2.11-2.3.3.jar:2.3.3]
	... 25 common frames omitted

```
The way I'm using it is quite straight-forward (in Java):

        VectorAssembler assembler = new VectorAssembler()
                .setInputCols(indexedFields)
                .setOutputCol("features");

        XGBoostRegressor xgBoost = new XGBoostRegressor()
                .setTrainTestRatio(0.2)
                .setNumWorkers(8);

        ParamMap[] paramMap = new ParamGridBuilder()
                .addGrid(xgBoost.maxDepth(), new int[]{3, 4, 5, 6, 7, 8, 9, 10})
                .addGrid(xgBoost.eta(), new double[]{0.01, 0.05, 0.1, 0.15, 0.2, 0.25, 0.3})
                .addGrid(xgBoost.subsample(), new double[]{0.5, 0.6, 0.7, 0.8, 0.9, 1})
                .build();

        RegressionEvaluator evaluator = new RegressionEvaluator();

        Pipeline pipeline = new Pipeline();
        pipeline.setStages(new PipelineStage[]{assembler, xgBoost});

        CrossValidator crossValidator = new CrossValidator()
                .setEstimator(pipeline)
                .setEvaluator(evaluator)
                .setEstimatorParamMaps(paramMap);

        CrossValidatorModel validatorModel = crossValidator.fit(modelData);

        Dataset<Row> predictions = validatorModel.bestModel().transform(modelData);

So no idea what could possibly go wrong. Maybe you are able to help me? Local instance, Java 1.8, Spark 2.3.3, Python 3.7.2

**Comment by kirill-linnik** [comment]
BTW, found this one in the logs:

```
2019-03-17 21:39:31.055  INFO 11128 --- [      Thread-33] .d.x.j.RabitTracker$TrackerProcessLogger : Traceback (most recent call last):
2019-03-17 21:39:31.055  INFO 11128 --- [      Thread-33] .d.x.j.RabitTracker$TrackerProcessLogger :   File "C:\Users\USER\AppData\Local\Temp\tracker8931727872945634711.py", line 487, in <module>
2019-03-17 21:39:31.055  INFO 11128 --- [      Thread-33] .d.x.j.RabitTracker$TrackerProcessLogger :     main()
2019-03-17 21:39:31.055  INFO 11128 --- [      Thread-33] .d.x.j.RabitTracker$TrackerProcessLogger :   File "C:\Users\USER\AppData\Local\Temp\tracker8931727872945634711.py", line 482, in main
2019-03-17 21:39:31.055  INFO 11128 --- [      Thread-33] .d.x.j.RabitTracker$TrackerProcessLogger :     start_rabit_tracker(args)
2019-03-17 21:39:31.055  INFO 11128 --- [      Thread-33] .d.x.j.RabitTracker$TrackerProcessLogger :   File "C:\Users\USER\AppData\Local\Temp\tracker8931727872945634711.py", line 444, in start_rabit_tracker
2019-03-17 21:39:31.055  INFO 11128 --- [      Thread-33] .d.x.j.RabitTracker$TrackerProcessLogger :     rabit = RabitTracker(hostIP=get_host_ip(args.host_ip), nslave=args.num_workers)
2019-03-17 21:39:31.056  INFO 11128 --- [      Thread-33] .d.x.j.RabitTracker$TrackerProcessLogger :   File "C:\Users\USER\AppData\Local\Temp\tracker8931727872945634711.py", line 145, in __init__
2019-03-17 21:39:31.056  INFO 11128 --- [      Thread-33] .d.x.j.RabitTracker$TrackerProcessLogger :     sock.bind((hostIP, port))
2019-03-17 21:39:31.056  INFO 11128 --- [      Thread-33] .d.x.j.RabitTracker$TrackerProcessLogger : OSError: [WinError 10048] Only one usage of each socket address (protocol/network address/port) is normally permitted
2019-03-17 21:39:31.056  INFO 11128 --- [      Thread-33] .d.x.j.RabitTracker$TrackerProcessLogger : Exception ignored in: <function RabitTracker.__del__ at 0x03A62ED0>
2019-03-17 21:39:31.056  INFO 11128 --- [      Thread-33] .d.x.j.RabitTracker$TrackerProcessLogger : Traceback (most recent call last):
2019-03-17 21:39:31.056  INFO 11128 --- [      Thread-33] .d.x.j.RabitTracker$TrackerProcessLogger :   File "C:\Users\USER\AppData\Local\Temp\tracker8931727872945634711.py", line 163, in __del__
2019-03-17 21:39:31.056  INFO 11128 --- [      Thread-33] .d.x.j.RabitTracker$TrackerProcessLogger :     self.sock.close()
2019-03-17 21:39:31.056  INFO 11128 --- [      Thread-33] .d.x.j.RabitTracker$TrackerProcessLogger : AttributeError: 'RabitTracker' object has no attribute 'sock'
2019-03-17 21:39:31.056  INFO 11128 --- [      Thread-33] .d.x.j.RabitTracker$TrackerProcessLogger : Tracker Process ends with exit code 1

```
...which is a bit strange, as rabit tries to find port from 9091 to 9999 and for sure there is at least one open there

**Comment by CodingCat** [comment]
according to the other post from you, it's highly related to https://www.stellarinfo.com/blog/how-to-fix-error-code-0xc0000005-in-windows/

**Comment by CodingCat** [comment]
and I am not trusting Spark on Windows at all
