### ISSUE TITLE
Out of memory even with small dataset

### ISSUE THREAD

**Issue by muscionig** [dmlc/xgboost#4286]
Hi,
I have a problem with running xgboost on my GPU, I am using python. Below my system information:

- OS: windows 10 
- Python version: 3.6.7
- Xgboost version: 0.82
- GPU: NVIDIA 1050M (driver: 23.21.13.9140)
- CUDA version: 10.1

The error that I am getting is that I am running out of memory:

```
Traceback (most recent call last):

  File "<ipython-input-1-a79435ebc0c9>", line 1, in <module>
    runfile('C:/Users/musci/OneDrive/Documenti/Git/test-xgboost-gpu/test.py', wdir='C:/Users/musci/OneDrive/Documenti/Git/test-xgboost-gpu')

  File "C:\Users\musci\Anaconda3\lib\site-packages\spyder_kernels\customize\spydercustomize.py", line 704, in runfile
    execfile(filename, namespace)

  File "C:\Users\musci\Anaconda3\lib\site-packages\spyder_kernels\customize\spydercustomize.py", line 108, in execfile
    exec(compile(f.read(), filename, 'exec'), namespace)

  File "C:/Users/musci/OneDrive/Documenti/Git/test-xgboost-gpu/test.py", line 89, in <module>
    res = classify_with_xgboost(train, train_label, test, test_label)

  File "C:/Users/musci/OneDrive/Documenti/Git/test-xgboost-gpu/test.py", line 62, in classify_with_xgboost
    model = xgb.train(param,dtrain, num_boost_round = 5)

  File "C:\Users\musci\Anaconda3\lib\site-packages\xgboost\training.py", line 216, in train
    xgb_model=xgb_model, callbacks=callbacks)

  File "C:\Users\musci\Anaconda3\lib\site-packages\xgboost\training.py", line 74, in _train_internal
    bst.update(dtrain, i, obj)

  File "C:\Users\musci\Anaconda3\lib\site-packages\xgboost\core.py", line 1110, in update
    dtrain.handle))

  File "C:\Users\musci\Anaconda3\lib\site-packages\xgboost\core.py", line 178, in _check_call
    raise XGBoostError(_LIB.XGBGetLastError())

XGBoostError: b'[01:56:07] C:/Users/Administrator/Desktop/xgboost/src/tree/updater_gpu.cu:602: grow_gpu exception: [01:56:07] c:\\users\\administrator\\desktop\\xgboost\\src\\common\\common.h:41: c:\\users\\administrator\\desktop\\xgboost\\src\\tree\\../common/device_helpers.cuh: 435: out of memory\n'
```

The code that I am using is the following:

```
import pandas as pd
import xgboost as xgb
import numpy as np
import random

import sklearn.metrics as mt

def evaluation(y_test, y_pred, f1_methods, fold = None, verbose = True):
    results = {}
    accuracy = mt.accuracy_score(y_test,y_pred)
    for f1_method in f1_methods:
        f_score = mt.f1_score(y_test,y_pred, average=f1_method)
        results['F1_score_'+f1_method] = f_score
    confusion_matrix = mt.confusion_matrix(y_test,y_pred) - np.identity(mt.confusion_matrix(y_test,y_pred).shape[0])
    results['Accuracy'] = accuracy   
    results['C_Matrix'] = confusion_matrix
    
    if verbose:
        print('----------------------------------')
        if fold is not None:
                print('Fold number: ' + str(fold))
        print("Accuracy: ", accuracy)
        for f1_method in f1_methods:
             print("F1 score: "+f1_method, results['F1_score_'+f1_method])
        print("Confusion matrix: \n", confusion_matrix)
        print('----------------------------------')
    return results.copy()

def create_train(dict_dfs, keys, dataset_to_select = None):
    df = pd.DataFrame()
    for key in keys:
        df = df.append(dict_dfs[key], ignore_index= True)
    if dataset_to_select is not None:
        return dataset_to_select.iloc[list(df.loc[:,0])]
    else:
        return df

def classify_with_xgboost(train,train_label,test,test_label):
    
    test = test[train.columns]
                
    dtrain = xgb.DMatrix(train, label=train_label)                                                
    # train                                                                                     
    param = {}
    param['objective'] = 'multi:softmax'
    param['booster'] = 'gbtree'
    param['eta'] = 0.1
    param['max_depth'] = 30
    param['silent'] = 1
    param['nthread'] = 4
    param['num_class'] = 3
    param['tree_method'] = 'gpu_exact'
    
      
    model = xgb.train(param,dtrain, num_boost_round = 5)
    
    dtest = xgb.DMatrix(test, label=test_label) 
    
    pred = model.predict(dtest)

    result = evaluation(list(test_label)+list(range(0,2)),list(pred)+list(range(0,2)),['weighted','macro'], verbose = True)
    
    return result

class_1 = pd.DataFrame()
class_2 = pd.DataFrame()
class_3 = pd.DataFrame()

class_1.loc[:,'F'] = np.random.normal(2,3,10000)
class_1.loc[:,'L'] = 0
class_2.loc[:,'F'] = np.random.normal(0,0.01,10000)
class_2.loc[:,'L'] = 1
class_3.loc[:,'F'] = np.random.normal(10,0.1,10000)
class_3.loc[:,'L'] = 2

df = class_1.append(class_2, ignore_index=True).append(class_3, ignore_index = True)

test_idx = random.sample(range(0, 30000), 5000)

train = df.loc[~df.index.isin(test_idx)]
train_label = train.pop('L')
test = df.loc[df.index.isin(test_idx)]
test_label = test.pop('L')

res = classify_with_xgboost(train, train_label, test, test_label)
```

If I remove the tree_method parameter the implementation work. I reinstalled my graphics driver, but nothing changed. I noticed from the task manager that when the training starts, the GPU compute power goes to 100%, but only for a very small amount of time. 
(Possible related issue: https://github.com/dmlc/xgboost/issues/2103)

**Comment by thvasilo** [comment]
You are using the parameter 'tree_depth' 30. This means you are trying to build trees 30 levels deep, where the last layer will have 2^30 leafs.

We mention in the [documentation](https://xgboost.readthedocs.io/en/latest/parameter.html):

> max_depth [default=6]
>
>    Maximum depth of a tree. Increasing this value will make the model more complex and more likely to overfit. 0 is only accepted in lossguided growing policy when tree_method is set as hist and it indicates no limit on depth. **Beware that XGBoost aggressively consumes memory when training a deep tree.**

I'd argue that our wording should be more explicit here, to make it clear that every one increase in this parameter leads to doubling the memory use.

**Comment by muscionig** [comment]
Ok, I changed it and now it is working. However, the result of df.info():
```
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 30000 entries, 0 to 29999
Data columns (total 2 columns):
F    30000 non-null float64
L    30000 non-null int64
dtypes: float64(1), int64(1)
memory usage: 468.8 KB
```

I would say that I understand that, but with 468KB of dataset in memory, it seems a little weird to me that xgboost is running out of memory. Am I missing something?

**Comment by RAMitchell** [comment]
@thvasilo this happens so often that we should even consider adding run-time warnings when users specify unusual parameters.

For example, if the user requests a tree configuration allowing more leaf nodes than training examples. I believe we can dramatically improve the user friendliness of xgboost.

It would be nice to do this in conjunction with the proposal to validate xgboost parameters (#4211).

**Comment by thvasilo** [comment]
@muscionig XGBoost is running out of memory because for every leaf it has to create a histogram data structure for every feature. So when you set the parameter to 30, apart from the need to maintain, for each iteration, one tree with 2^31-1 nodes, it also needs to estimate `num_features * num_leaves` histograms. When you have too many leaves this will lead to out of memory errors. As @RAMitchell mentioned, this is entirely unnecessary in your case, any max_depth above 14 would produce trees with more leaves than you have data points, as 2^15=32768. 

@RAMitchell definitely agree. @trivialfis seems to be on that, but looks like it depends on the JSON work first.
