### ISSUE TITLE
max_depth string to Int in ParamMapFuncs class error

### ISSUE THREAD

**Issue by Jarlene** [dmlc/xgboost#4297]
when i use xgboost to train a model with hpo; the hpo output max_dep="4.0" which is a string type,  but the method XGBoostToMLlibParams in ParamMapFuncs for IntParam do toString.toInt like this
![image](https://user-images.githubusercontent.com/14009650/55054022-39b6a400-5099-11e9-92d3-5a9ba1377540.png)

last exception as : 
java.lang.NumberFormatException: For input string: "4.0"
	at java.lang.NumberFormatException.forInputString(NumberFormatException.java:65)
	at java.lang.Integer.parseInt(Integer.java:580)
	at java.lang.Integer.parseInt(Integer.java:615)
	at scala.collection.immutable.StringLike$class.toInt(StringLike.scala:272)
	at scala.collection.immutable.StringOps.toInt(StringOps.scala:29)
	at ml.dmlc.xgboost4j.scala.spark.params.ParamMapFuncs$$anonfun$XGBoostToMLlibParams$2.apply(GeneralParams.scala:261)
	at ml.dmlc.xgboost4j.scala.spark.params.ParamMapFuncs$$anonfun$XGBoostToMLlibParams$2.apply(GeneralParams.scala:245)
	at scala.collection.TraversableLike$WithFilter$$anonfun$foreach$1.apply(TraversableLike.scala:733)
	at scala.collection.immutable.HashMap$HashMap1.foreach(HashMap.scala:221)
	at scala.collection.immutable.HashMap$HashTrieMap.foreach(HashMap.scala:428)
	at scala.collection.immutable.HashMap$HashTrieMap.foreach(HashMap.scala:428)
	at scala.collection.immutable.HashMap$HashTrieMap.foreach(HashMap.scala:428)
	at scala.collection.TraversableLike$WithFilter.foreach(TraversableLike.scala:732)
	at ml.dmlc.xgboost4j.scala.spark.params.ParamMapFuncs$class.XGBoostToMLlibParams(GeneralParams.scala:245)
	at ml.dmlc.xgboost4j.scala.spark.XGBoostClassifier.XGBoostToMLlibParams(XGBoostClassifier.scala:48)
	at ml.dmlc.xgboost4j.scala.spark.XGBoostClassifier.<init>(XGBoostClassifier.scala:61)
	at ml.dmlc.xgboost4j.scala.spark.XGBoostClassifier.<init>(XGBoostClassifier.scala:58)

**Comment by thvasilo** [comment]
I think you need to use a simple "4" here? `max_depth` is supposed to be an integer, and Scala can't convert the double value "4.0" to an integer.

```
scala> "4.0".toInt
java.lang.NumberFormatException: For input string: "4.0"
  at java.lang.NumberFormatException.forInputString(NumberFormatException.java:65)
  at java.lang.Integer.parseInt(Integer.java:580)
  at java.lang.Integer.parseInt(Integer.java:615)
  at scala.collection.immutable.StringLike.toInt(StringLike.scala:300)
  at scala.collection.immutable.StringLike.toInt$(StringLike.scala:300)
  at scala.collection.immutable.StringOps.toInt(StringOps.scala:29)
  ... 36 elided

scala> "4".toInt
res1: Int = 4
```
