### ISSUE TITLE
ml.dmlc.xgboost4j.java.XGBoostError: XGBoostModel training failed

### ISSUE THREAD

**Issue by charmby** [dmlc/xgboost#4382]
I run the xgboost spark example and come up with issue. I compiled xgboost4j jar with Maven on my Mac. And then I tried a training on Mac with spark local mode，that is ok. 
but i run in  spark-2.3.2, throw this exception

Compiler: JDK 1.8 ， spark 2.3.2 , scala 2.11.12
19/04/17 22:47:49 INFO cluster.YarnScheduler dag-scheduler-event-loop: Adding task set 4.0 with 1 tasks
19/04/17 22:47:49 INFO scheduler.TaskSetManager dispatcher-event-loop-10: Starting task 0.0 in stage 4.0 (TID 4, tjtx148-9-226.58os.org, executor 5, partition 0, NODE_LOCAL, 7781 bytes)
19/04/17 22:47:49 INFO storage.BlockManagerInfo dispatcher-event-loop-1: Added broadcast_7_piece0 in memory on tjtx148-9-226.58os.org:14359 (size: 4.1 KB, free: 6.9 GB)
19/04/17 22:47:49 INFO spark.MapOutputTrackerMasterEndpoint dispatcher-event-loop-13: Asked to send map output locations for shuffle 0 to 10.148.9.226:17395
19/04/17 22:47:49 INFO scheduler.TaskSetManager task-result-getter-0: Finished task 0.0 in stage 4.0 (TID 4) in 137 ms on tjtx148-9-226.58os.org (executor 5) (1/1)
19/04/17 22:47:49 INFO cluster.YarnScheduler task-result-getter-0: Removed TaskSet 4.0, whose tasks have all completed, from pool 
19/04/17 22:47:49 INFO scheduler.DAGScheduler dag-scheduler-event-loop: ResultStage 4 (take at Classifier.scala:111) finished in 0.149 s
19/04/17 22:47:49 INFO scheduler.DAGScheduler main: Job 3 finished: take at Classifier.scala:111, took 0.152682 s
19/04/17 22:47:49 INFO spark.XGBoostClassifier main: ml.dmlc.xgboost4j.scala.spark.XGBoostClassifier inferred 2 classes for labelCol=xgbc_9c56f4449ed7__labelCol since numClasses was not specified in the column metadata.
19/04/17 22:47:49 INFO codegen.CodeGenerator main: Code generated in 24.849769 ms
Tracker started, with env={}
19/04/17 22:47:49 INFO java.RabitTracker$TrackerProcessLogger Thread-37: Traceback (most recent call last):
19/04/17 22:47:49 INFO java.RabitTracker$TrackerProcessLogger Thread-37:   File "/tmp/tracker7867285321561281261.py", line 19, in <module>
19/04/17 22:47:49 INFO java.RabitTracker$TrackerProcessLogger Thread-37:     import argparse
19/04/17 22:47:49 INFO java.RabitTracker$TrackerProcessLogger Thread-37: ImportError: No module named argparse
19/04/17 22:47:49 INFO java.RabitTracker$TrackerProcessLogger Thread-37: Tracker Process ends with exit code 1
19/04/17 22:47:49 INFO spark.ContextCleaner Spark Context Cleaner: Cleaned accumulator 75
19/04/17 22:47:49 INFO spark.ContextCleaner Spark Context Cleaner: Cleaned accumulator 123
19/04/17 22:47:49 INFO spark.ContextCleaner Spark Context Cleaner: Cleaned accumulator 105
19/04/17 22:47:49 INFO spark.ContextCleaner Spark Context Cleaner: Cleaned accumulator 80

19/04/17 22:47:50 INFO java.RabitTracker main: Tracker Process ends with exit code 1
19/04/17 22:47:50 INFO XGBoostSpark main: Rabit returns with exit code 1
19/04/17 22:47:50 ERROR java.RabitTracker Thread-38: Uncaught exception thrown by worker:
java.lang.InterruptedException
	at java.util.concurrent.locks.AbstractQueuedSynchronizer.doAcquireSharedInterruptibly(AbstractQueuedSynchronizer.java:998)
	at java.util.concurrent.locks.AbstractQueuedSynchronizer.acquireSharedInterruptibly(AbstractQueuedSynchronizer.java:1304)
	at scala.concurrent.impl.Promise$DefaultPromise.tryAwait(Promise.scala:202)
	at scala.concurrent.impl.Promise$DefaultPromise.ready(Promise.scala:218)
	at scala.concurrent.impl.Promise$DefaultPromise.ready(Promise.scala:153)
	at org.apache.spark.util.ThreadUtils$.awaitReady(ThreadUtils.scala:233)
	at org.apache.spark.scheduler.DAGScheduler.runJob(DAGScheduler.scala:666)
	at org.apache.spark.SparkContext.runJob(SparkContext.scala:2035)
	at org.apache.spark.SparkContext.runJob(SparkContext.scala:2056)
	at org.apache.spark.SparkContext.runJob(SparkContext.scala:2075)
	at org.apache.spark.SparkContext.runJob(SparkContext.scala:2100)
	at org.apache.spark.rdd.RDD$$anonfun$foreachPartition$1.apply(RDD.scala:932)
	at org.apache.spark.rdd.RDD$$anonfun$foreachPartition$1.apply(RDD.scala:930)
	at org.apache.spark.rdd.RDDOperationScope$.withScope(RDDOperationScope.scala:151)
	at org.apache.spark.rdd.RDDOperationScope$.withScope(RDDOperationScope.scala:112)
	at org.apache.spark.rdd.RDD.withScope(RDD.scala:360)
	at org.apache.spark.rdd.RDD.foreachPartition(RDD.scala:930)
	at ml.dmlc.xgboost4j.scala.spark.XGBoost$$anonfun$trainDistributed$4$$anon$1.run(XGBoost.scala:287)
Exception in thread "main" ml.dmlc.xgboost4j.java.XGBoostError: XGBoostModel training failed
	at ml.dmlc.xgboost4j.scala.spark.XGBoost$.ml$dmlc$xgboost4j$scala$spark$XGBoost$$postTrackerReturnProcessing(XGBoost.scala:364)
	at ml.dmlc.xgboost4j.scala.spark.XGBoost$$anonfun$trainDistributed$4.apply(XGBoost.scala:294)
	at ml.dmlc.xgboost4j.scala.spark.XGBoost$$anonfun$trainDistributed$4.apply(XGBoost.scala:256)
	at scala.collection.TraversableLike$$anonfun$map$1.apply(TraversableLike.scala:234)
	at scala.collection.TraversableLike$$anonfun$map$1.apply(TraversableLike.scala:234)
	at scala.collection.immutable.List.foreach(List.scala:381)
	at scala.collection.TraversableLike$class.map(TraversableLike.scala:234)
	at scala.collection.immutable.List.map(List.scala:285)
	at ml.dmlc.xgboost4j.scala.spark.XGBoost$.trainDistributed(XGBoost.scala:255)
	at ml.dmlc.xgboost4j.scala.spark.XGBoostClassifier.train(XGBoostClassifier.scala:200)
	at ml.dmlc.xgboost4j.scala.spark.XGBoostClassifier.train(XGBoostClassifier.scala:48)
	at org.apache.spark.ml.Predictor.fit(Predictor.scala:118)

pom refrence is this.

       <dependency>
            <groupId>ml.dmlc</groupId>
            <artifactId>xgboost4j-spark</artifactId>
            <version>0.81</version>
            
        </dependency>

**Comment by CodingCat** [comment]
Check the line at 

ImportError: No module named argparse

You need to install it in your server

**Comment by charmby** [comment]
> Check the line at
> 
> ImportError: No module named argparse
> 
> You need to install it in your server

I don't have permission to install the company's cluster. But i can install it for driver machine. Whether it is ok with python3 on my driver machine？
