### ISSUE TITLE
[jvm-packages] java.io.InvalidClassException: ml.dmlc.xgboost4j.scala.spark.XGBoostClassificationModel; local class incompatible

### ISSUE THREAD

**Issue by charmby** [dmlc/xgboost#4385]
My training has failed all the time.  exception information is as follows：

19/04/19 00:32:33 INFO scheduler.DAGScheduler dag-scheduler-event-loop: Got job 6 (sortByKey at BinaryClassificationMetrics.scala:155) with 32 output partitions
19/04/19 00:32:33 INFO scheduler.DAGScheduler dag-scheduler-event-loop: Final stage: ResultStage 8 (sortByKey at BinaryClassificationMetrics.scala:155)
19/04/19 00:32:33 INFO scheduler.DAGScheduler dag-scheduler-event-loop: Parents of final stage: List(ShuffleMapStage 7)
19/04/19 00:32:33 INFO scheduler.DAGScheduler dag-scheduler-event-loop: Missing parents: List(ShuffleMapStage 7)
19/04/19 00:32:33 INFO scheduler.DAGScheduler dag-scheduler-event-loop: Submitting ShuffleMapStage 7 (MapPartitionsRDD[45] at map at BinaryClassificationEvaluator.scala:81), which has no missing parents
19/04/19 00:32:33 INFO memory.MemoryStore dag-scheduler-event-loop: Block broadcast_11 stored as values in memory (estimated size 111.1 KB, free 6.9 GB)
19/04/19 00:32:33 INFO memory.MemoryStore dag-scheduler-event-loop: Block broadcast_11_piece0 stored as bytes in memory (estimated size 36.6 KB, free 6.9 GB)
19/04/19 00:32:33 INFO storage.BlockManagerInfo dispatcher-event-loop-13: Added broadcast_11_piece0 in memory on tjtx-107-75.58os.org:14237 (size: 36.6 KB, free: 6.9 GB)
19/04/19 00:32:33 INFO spark.SparkContext dag-scheduler-event-loop: Created broadcast 11 from broadcast at DAGScheduler.scala:1110
19/04/19 00:32:33 INFO scheduler.DAGScheduler dag-scheduler-event-loop: Submitting 1 missing tasks from ShuffleMapStage 7 (MapPartitionsRDD[45] at map at BinaryClassificationEvaluator.scala:81) (first 15 tasks are for partitions Vector(0))
19/04/19 00:32:33 INFO cluster.YarnScheduler dag-scheduler-event-loop: Adding task set 7.0 with 1 tasks
19/04/19 00:32:33 INFO scheduler.TaskSetManager dispatcher-event-loop-8: Starting task 0.0 in stage 7.0 (TID 6, tjtx148-16-223.58os.org, executor 2, partition 0, PROCESS_LOCAL, 54193 bytes)
19/04/19 00:32:33 INFO storage.BlockManagerInfo dispatcher-event-loop-2: Added broadcast_11_piece0 in memory on tjtx148-16-223.58os.org:25462 (size: 36.6 KB, free: 4.5 GB)
19/04/19 00:32:33 WARN scheduler.TaskSetManager task-result-getter-2: Lost task 0.0 in stage 7.0 (TID 6, tjtx148-16-223.58os.org, executor 2): java.io.InvalidClassException: ml.dmlc.xgboost4j.scala.spark.XGBoostClassificationModel; local class incompatible: stream classdesc serialVersionUID = 3438839528981285596, local class serialVersionUID = 5574108146107596020

 at java.io.ObjectStreamClass.initNonProxy(ObjectStreamClass.java:616)
    at java.io.ObjectInputStream.readNonProxyDesc(ObjectInputStream.java:1623)
    at java.io.ObjectInputStream.readClassDesc(ObjectInputStream.java:1518)
    at java.io.ObjectInputStream.readOrdinaryObject(ObjectInputStream.java:1774)
    at java.io.ObjectInputStream.readObject0(ObjectInputStream.java:1351)
    at java.io.ObjectInputStream.defaultReadFields(ObjectInputStream.java:2000)
    at java.io.ObjectInputStream.readSerialData(ObjectInputStream.java:1924)
    at java.io.ObjectInputStream.readOrdinaryObject(ObjectInputStream.java:1801)
    at java.io.ObjectInputStream.readObject0(ObjectInputStream.java:1351)
    at java.io.ObjectInputStream.defaultReadFields(ObjectInputStream.java:2000)
    at java.io.ObjectInputStream.readSerialData(ObjectInputStream.java:1924)
    at java.io.ObjectInputStream.readOrdinaryObject(ObjectInputStream.java:1801)
    at java.io.ObjectInputStream.readObject0(ObjectInputStream.java:1351)
    at java.io.ObjectInputStream.defaultReadFields(ObjectInputStream.java:2000)
    at java.io.ObjectInputStream.readSerialData(ObjectInputStream.java:1924)
    at java.io.ObjectInputStream.readOrdinaryObject(ObjectInputStream.java:1801)
    at java.io.ObjectInputStream.readObject0(ObjectInputStream.java:1351)
    at java.io.ObjectInputStream.defaultReadFields(ObjectInputStream.java:2000)
    at java.io.ObjectInputStream.readSerialData(ObjectInputStream.java:1924)
    at java.io.ObjectInputStream.readOrdinaryObject(ObjectInputStream.java:1801)
    at java.io.ObjectInputStream.readObject0(ObjectInputStream.java:1351)
    at java.io.ObjectInputStream.readObject(ObjectInputStream.java:371)
    at scala.collection.immutable.List$SerializationProxy.readObject(List.scala:479)
    at sun.reflect.GeneratedMethodAccessor2.invoke(Unknown Source)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
    at java.lang.reflect.Method.invoke(Method.java:497)
    at java.io.ObjectStreamClass.invokeReadObject(ObjectStreamClass.java:1058)
    at java.io.ObjectInputStream.readSerialData(ObjectInputStream.java:1900)
    at java.io.ObjectInputStream.readOrdinaryObject(ObjectInputStream.java:1801)
    at java.io.ObjectInputStream.readObject0(ObjectInputStream.java:1351)

**Comment by CodingCat** [comment]
you need to provide more information like

xgboost version, spark version, runtime/dev environment, you compile xgboost or using maven dependency when asking for help on the issue
