### ISSUE TITLE
cannot get xgboost to work on sparse matrix

### ISSUE THREAD

**Issue by asimkievich** [dmlc/xgboost#440]
hi there, I have been running xgboost on sparse matrices for a while, but I am not getting it to work on sparse matrices (python). Here is the issue:

In[34]: X.__class__
Out[33]: scipy.sparse.coo.coo_matrix 

I also tried with csr matrices, both on X and y

In[35]: y.__class__
Out[34]: scipy.sparse.coo.coo_matrix

In[36]: xg_train = xgb.DMatrix(X, y)

In[37]: param = {'objective':'reg:linear','eta':0.4,
         'max_depth':8,'min_child_weight':3, 'subsample':.8, 'silent':1,
         'nthread':8,'colsample_bytree':.8,'gamma':0.001}

watchlist = [(xg_train,'train') ]
num_round = 250

In[38]: bst = xgb.train(param, xg_train, num_round,watchlist)

And this is what I get
Traceback (most recent call last):
  File "C:\Users\....\Anaconda3\lib\site-packages\IPython\core\interactiveshell.py", line 3035, in run_code
    exec(code_obj, self.user_global_ns, self.user_ns)
  File "<ipython-input-28-f66fa41ef2a0>", line 1, in <module>
    xg_train = xgb.DMatrix(X, y)
  File "C:\Users\....\Anaconda3\Lib\site-packages\xgboost\wrapper\xgboost.py", line 150, in __init__
    self.set_label(label)
  File "C:\Users\....\Anaconda3\Lib\site-packages\xgboost\wrapper\xgboost.py", line 229, in set_label
    self.set_float_info('label', label)
  File "C:\Users\....\Anaconda3\Lib\site-packages\xgboost\wrapper\xgboost.py", line 202, in set_float_info
    c_array(ctypes.c_float, data), len(data))
  File "C:\Users\....\Anaconda3\Lib\site-packages\xgboost\wrapper\xgboost.py", line 110, in c_array
    return (ctype * len(values))(*values)
  File "C:\Users\....\Anaconda3\lib\site-packages\scipy\sparse\base.py", line 192, in __len__
    raise TypeError("sparse matrix length is ambiguous; use getnnz()"
TypeError: sparse matrix length is ambiguous; use getnnz() or shape[0]
Traceback (most recent call last):
  File "C:\Users\Alejandro\Anaconda3\lib\site-packages\IPython\core\interactiveshell.py", line 3035, in run_code
    exec(code_obj, self.user_global_ns, self.user_ns)
  File "<ipython-input-29-45e3957527ef>", line 5, in <module>
    watchlist = [(xg_train,'train') ]
NameError: name 'xg_train' is not defined
Traceback (most recent call last):
  File "C:\Users\Alejandro\Anaconda3\lib\site-packages\IPython\core\interactiveshell.py", line 3035, in run_code
    exec(code_obj, self.user_global_ns, self.user_ns)
  File "<ipython-input-30-c8a37b29ce87>", line 1, in <module>
    bst = xgb.train(param, xg_train, num_round,watchlist)
NameError: name 'xg_train' is not defined

Also, it does not work either where X is a sparse matrix and y a ndarray

Thanks!
Best,

Alejandro

**Comment by asimkievich** [comment]
oh my, it did work with X being a coo sparse matrix and y being an nd array.

Issue can be closed.

**Comment by AWNystrom** [comment]
coo's not really very efficient for calculations though, right? Wouldn't it
be good for it to work on csr?
