### ISSUE TITLE
[jvm-packages] XGBoostModel training failed

### ISSUE THREAD

**Issue by clayms** [dmlc/xgboost#4413]
3 node cluster 
CDH 5.15
Spark 2.2.0
XGBoost 0.72 (xgboost4j-spark-0.8-SNAPSHOT-jar-with-dependencies.jar)
Python 2.7.12

Exact same code trains successfully on smaller dataframe.

Code excerpts:
Spark Session:
```
spark = (
    SparkSession.builder.appName('test')
    .master('yarn')
    .config('spark.kryoserializer.buffer.max', '256m')
    .config('spark.sql.cbo.enabled', True)
    .config('spark.sql.cbo.joinReorder.enabled', True)
    .config('spark.dynamicAllocation.minExecutors', 1)
    .config("spark.executor.cores", 4)
    .config('spark.executor.memory', '6g')
    .config('spark.yarn.executor.memoryOverhead', '4g')
    .config('spark.driver.maxResultSize', '2g')
    .config("spark.dynamicAllocation.enabled", True)
    .config("spark.jars", 'xgboost4j-spark-0.8-SNAPSHOT-jar-with-dependencies.jar')
    .getOrCreate()
)
```
XGBoost parameters
```
xgboost = XGBoostEstimator(
    # General Params
    nworkers=4, 
    silent=0, 
    
    # Column Params
    featuresCol="features", 
    labelCol="indexedLabel", 
    predictionCol="gbt_prediction", 
    weightCol="weight", 
    baseMarginCol="baseMargin", 
    
    # Booster Params
    booster="gbtree", 
    base_score=0.5, 
    objective="binary:logistic", 
    eval_metric="auc", 
    num_class=2, 
    num_round=1000, 
    seed=12345,
    
    # Tree Booster Params
    eta=0.01, 
    gamma=0.0, 
    max_depth=3, 
    subsample=0.6,
    colsample_bytree=0.3, 
    reg_lambda=0.8, 
    alpha=0.4
)

labelConverter = (
    IndexToString()
    .setInputCol("gbt_prediction")
    .setOutputCol("predictedLabel")
    .setLabels(labelIndexer.labels)
)

xgbt_pipeline = (
    Pipeline()
    .setStages([
        xgboost,
        labelConverter
        ])
)

xgbt_pipeline_model = xgbt_pipeline.fit( df_train )
```

Error:
```
Py4JJavaError: An error occurred while calling o644.fit.
: ml.dmlc.xgboost4j.java.XGBoostError: XGBoostModel training failed
	at ml.dmlc.xgboost4j.scala.spark.XGBoost$.ml$dmlc$xgboost4j$scala$spark$XGBoost$$postTrackerReturnProcessing(XGBoost.scala:406)
	at ml.dmlc.xgboost4j.scala.spark.XGBoost$$anonfun$trainDistributed$4.apply(XGBoost.scala:356)
	at ml.dmlc.xgboost4j.scala.spark.XGBoost$$anonfun$trainDistributed$4.apply(XGBoost.scala:337)
	at scala.collection.TraversableLike$$anonfun$map$1.apply(TraversableLike.scala:234)
	at scala.collection.TraversableLike$$anonfun$map$1.apply(TraversableLike.scala:234)
	at scala.collection.immutable.List.foreach(List.scala:381)
	at scala.collection.TraversableLike$class.map(TraversableLike.scala:234)
	at scala.collection.immutable.List.map(List.scala:285)
	at ml.dmlc.xgboost4j.scala.spark.XGBoost$.trainDistributed(XGBoost.scala:336)
	at ml.dmlc.xgboost4j.scala.spark.XGBoostEstimator.train(XGBoostEstimator.scala:139)
	at ml.dmlc.xgboost4j.scala.spark.XGBoostEstimator.train(XGBoostEstimator.scala:36)
	at org.apache.spark.ml.Predictor.fit(Predictor.scala:118)
	at org.apache.spark.ml.Predictor.fit(Predictor.scala:82)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at py4j.reflection.MethodInvoker.invoke(MethodInvoker.java:244)
	at py4j.reflection.ReflectionEngine.invoke(ReflectionEngine.java:357)
	at py4j.Gateway.invoke(Gateway.java:280)
	at py4j.commands.AbstractCommand.invokeMethod(AbstractCommand.java:132)
	at py4j.commands.CallCommand.execute(CallCommand.java:79)
	at py4j.GatewayConnection.run(GatewayConnection.java:214)
	at java.lang.Thread.run(Thread.java:745)
```

Error from failed worker node:
```
java.lang.IndexOutOfBoundsException: 2
	at scala.collection.LinearSeqOptimized$class.apply(LinearSeqOptimized.scala:65)
	at scala.collection.immutable.List.apply(List.scala:84)
	at ml.dmlc.xgboost4j.scala.spark.Watches$.apply(XGBoost.scala:520)
	at ml.dmlc.xgboost4j.scala.spark.XGBoost$$anonfun$buildDistributedBoosters$1.apply(XGBoost.scala:132)
	at ml.dmlc.xgboost4j.scala.spark.XGBoost$$anonfun$buildDistributedBoosters$1.apply(XGBoost.scala:117)
	at org.apache.spark.rdd.ZippedPartitionsRDD2.compute(ZippedPartitionsRDD.scala:89)
	at org.apache.spark.rdd.RDD.computeOrReadCheckpoint(RDD.scala:323)
	at org.apache.spark.rdd.RDD$$anonfun$8.apply(RDD.scala:336)
	at org.apache.spark.rdd.RDD$$anonfun$8.apply(RDD.scala:334)
	at org.apache.spark.storage.BlockManager$$anonfun$doPutIterator$1.apply(BlockManager.scala:1038)
	at org.apache.spark.storage.BlockManager$$anonfun$doPutIterator$1.apply(BlockManager.scala:1029)
	at org.apache.spark.storage.BlockManager.doPut(BlockManager.scala:969)
	at org.apache.spark.storage.BlockManager.doPutIterator(BlockManager.scala:1029)
	at org.apache.spark.storage.BlockManager.getOrElseUpdate(BlockManager.scala:760)
	at org.apache.spark.rdd.RDD.getOrCompute(RDD.scala:334)
	at org.apache.spark.rdd.RDD.iterator(RDD.scala:285)
	at org.apache.spark.scheduler.ResultTask.runTask(ResultTask.scala:87)
	at org.apache.spark.scheduler.Task.run(Task.scala:108)
	at org.apache.spark.executor.Executor$TaskRunner.run(Executor.scala:335)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
```

**Comment by CodingCat** [comment]
how you involve an Py4JJavaError?????

we don't support pyspark anyway

**Comment by clayms** [comment]
With the sparkxgb wrappers written by @thesuperzapper  here https://github.com/dmlc/xgboost/issues/1698#issuecomment-402338734

**Comment by clayms** [comment]
Got it working in pyspark.  
Simply removed the following config statement from my SparkSession.
```
.config("spark.executor.cores", 4)
```

The Scala code works if the SparkSession is started with the following set in 'spark-default.conf' file.
```
spark.executor.cores 4
```

Why does a pyspark SparkSession not able to run XGBoost if `spark.executor.cores` is set?
