### ISSUE TITLE
[jvm-packages] XgBoost loading error on windows using Java & Maven

### ISSUE THREAD

**Issue by sajagekar** [dmlc/xgboost#4416]
Hi,
I am trying to use XgBoost along with Java Maven project, it works when I directly call main class,but it throws below error when I create jar using maven build and execute it through command line or using Intellij.

Exception in thread "main" java.lang.IllegalStateException: Unable to load XGBooster
	at hex.genmodel.algos.xgboost.XGBoostNativeMojoModel.makeBooster(XGBoostNativeMojoModel.java:36)
	at hex.genmodel.algos.xgboost.XGBoostNativeMojoModel.<init>(XGBoostNativeMojoModel.java:29)
	at hex.genmodel.algos.xgboost.XGBoostMojoReader.makeModel(XGBoostMojoReader.java:41)
	at hex.genmodel.algos.xgboost.XGBoostMojoReader.makeModel(XGBoostMojoReader.java:10)
	at hex.genmodel.ModelMojoReader.readAll(ModelMojoReader.java:145)
	at hex.genmodel.ModelMojoReader.readFrom(ModelMojoReader.java:34)
	at hex.genmodel.MojoModel.load(MojoModel.java:37)
	at com.eliprio.pipeline.model.ModelScoring.extractModelParameters(ModelScoring.java:109)
	at com.eliprio.pipeline.model.ModelScoring.main(ModelScoring.java:78)
Caused by: ml.dmlc.xgboost4j.java.XGBoostError
	at ml.dmlc.xgboost4j.java.Booster.newKryoBooster(Booster.java:85)
	at ml.dmlc.xgboost4j.java.Booster.newBooster(Booster.java:74)
	at ml.dmlc.xgboost4j.java.Booster.loadModel(Booster.java:135)
	at ml.dmlc.xgboost4j.java.BoosterHelper.loadModel(BoosterHelper.java:14)
	at hex.genmodel.algos.xgboost.XGBoostNativeMojoModel.makeBooster(XGBoostNativeMojoModel.java:34)
	... 8 more
Below is the maven settings

<plugin>
                <groupId>org.apache.maven.plugins</groupId>
                <artifactId>maven-assembly-plugin</artifactId>
                <executions>
                    <execution>
                        <phase>package</phase>
                        <goals>
                            <goal>single</goal>
                        </goals>
                        <configuration>
                            <archive>
                                <manifest>
                                    <mainClass>
                                        {Main class}
                                    </mainClass>
                                </manifest>
                            </archive>
                            <descriptorRefs>
                                <descriptorRef>jar-with-dependencies</descriptorRef>
                            </descriptorRefs>
                            <appendAssemblyId>false</appendAssemblyId>
                        </configuration>
                    </execution>
                </executions>
            </plugin>
I have used Xgboost library which has windows dll.

**Comment by hcho3** [comment]
Can you look at the content of the JAR file and see if it contains DLL?

**Comment by sajagekar** [comment]
Yes, it does contain dll inside lib folder.

**Comment by hcho3** [comment]
Where did you get XGBoost4J JAR with the DLL? Did you build it yourself?

**Comment by sajagekar** [comment]
No, i found it on github somewhere,Long back ago. Recently we converted
project to maven and tried to build and execute . It does build but while
running jar it is giving error.

**Comment by hcho3** [comment]
@sajagekar Try using JARs from https://github.com/criteo-forks/xgboost-jars?

**Comment by sajagekar** [comment]
@hcho3 Do you mean , I should directly add 
<dependency>
    <groupId>ml.dmlc</groupId>
    <artifactId>xgboost4j</artifactId>
    <version>latest_version_num</version>
</dependency>
This dependancy and try?

**Comment by hcho3** [comment]
@sajagekar Get JARs from https://github.com/criteo-forks/xgboost-jars/releases

**Comment by sajagekar** [comment]
Hi,
I have downloaded jar from above link and integrated as maven dependency as below. but it is not getting added to jar file, and getting same error.

```
<dependency>
            <groupId>ml.dmlc</groupId>
            <artifactId>xgboost4j</artifactId>
            <version>0.82-criteo-20180821_2.11</version>
            <scope>system</scope>
            <systemPath>{baseDir}/libs/xgboost4j-0.82-criteo-20190412_2.11-win64.jar</systemPath>
        </dependency>
```

**Comment by hcho3** [comment]
Hmm, maybe you should try to build XGBoost4J yourself. Sorry I have no idea what's happening

**Comment by sajagekar** [comment]
Now looks problem with maven plugins, Thanks for pointing jar resources
