### ISSUE TITLE
AUCPR metric fails for learning-to-rank

### ISSUE THREAD

**Issue by hcho3** [dmlc/xgboost#4431]
Consider the following toy data for learning-to-rank:
```python
import numpy as np
from scipy.sparse import csr_matrix
import xgboost

Xrow = np.array([1, 2, 6, 8, 11, 14, 16, 17])
Xcol = np.array([0, 0, 1, 1,  2,  2,  3,  3])
X = csr_matrix((np.ones(shape=8), (Xrow, Xcol)), shape=(20, 4))
y = np.array([0.0, 1.0, 1.0, 0.0, 0.0,
              0.0, 1.0, 0.0, 1.0, 0.0,
              0.0, 1.0, 0.0, 0.0, 1.0,
              0.0, 1.0, 1.0, 0.0, 0.0])    # 1: relevant, 0: not relevant
group = np.array([5, 5, 5, 5], dtype=np.uint)
dtrain = xgboost.DMatrix(X, label=y)
dtrain.set_group(group)

params = {'eta': 1, 'tree_method': 'exact',
          'objective': 'rank:pairwise', 'eval_metric': 'aucpr',
          'max_depth': 1}
bst = xgboost.train(params, dtrain, 10, evals=[(dtrain, 'train')])
```

This example fails because of the following error in the AUCPR metric function:
```
Traceback (most recent call last):
  File "test.py", line 19, in <module>
    bst = xgboost.train(params, dtrain, 10, evals=[(dtrain, 'train')])
  File "/Users/chyunsu/Desktop/xgboost/python-package/xgboost/training.py", line 216, in train
    xgb_model=xgb_model, callbacks=callbacks)
  File "/Users/chyunsu/Desktop/xgboost/python-package/xgboost/training.py", line 84, in _train_internal
    bst_eval_set = bst.eval_set(evals, i, feval)
  File "/Users/chyunsu/Desktop/xgboost/python-package/xgboost/core.py", line 1172, in eval_set
    ctypes.byref(msg)))
  File "/Users/chyunsu/Desktop/xgboost/python-package/xgboost/core.py", line 176, in _check_call
    raise XGBoostError(py_str(_LIB.XGBGetLastError()))
xgboost.core.XGBoostError: [01:55:51] /Users/chyunsu/Desktop/xgboost/src/metric/rank_metric.cc:442: 
Check failed: !auc_gt_one: AUC-PR: AUC > 1.0
```

**Comment by hcho3** [comment]
@kretes Have you experienced a problem with AUCPR?

**Comment by kretes** [comment]
Never used that, however when I add it I receive an error, but a different one:

```
b'[11:16:52] /workspace/src/metric/rank_metric.cc:441: Check failed: !auc_error AUC-PR: the dataset only contains pos or neg samples

Stack trace returned 10 entries:
[bt] (0) /home/env_xgb_latest/xgboost/libxgboost.so(dmlc::StackTrace(unsigned long)+0x47) [0x7f54dd354fc7]
[bt] (1) /home/env_xgb_latest/xgboost/libxgboost.so(dmlc::LogMessageFatal::~LogMessageFatal()+0x1d) [0x7f54dd35542d]
[bt] (2) /home/env_xgb_latest/xgboost/libxgboost.so(xgboost::metric::EvalAucPR::Eval(xgboost::HostDeviceVector<float> const&, xgboost::MetaInfo const&, bool)+0xb0b) [0x7f54dd396dfb]
[bt] (3) /home/env_xgb_latest/xgboost/libxgboost.so(xgboost::LearnerImpl::EvalOneIter(int, std::vector<xgboost::DMatrix*, std::allocator<xgboost::DMatrix*> > const&, std::vector<std::string, std::allocator<std::string> > const&)+0x27b) [0x7f54dd42c1cb]
[bt] (4) /home/env_xgb_latest/xgboost/libxgboost.so(XGBoosterEvalOneIter+0x287) [0x7f54dd352b27]
[bt] (5) /home/env_xgb_latest/lib/python3.6/lib-dynload/../../libffi.so.6(ffi_call_unix64+0x4c) [0x7f5566a4fec0]
[bt] (6) /home/env_xgb_latest/lib/python3.6/lib-dynload/../../libffi.so.6(ffi_call+0x22d) [0x7f5566a4f87d]
[bt] (7) /home/env_xgb_latest/lib/python3.6/lib-dynload/_ctypes.cpython-36m-x86_64-linux-gnu.so(_ctypes_callproc+0x2ce) [0x7f5566c6600e]
[bt] (8) /home/env_xgb_latest/lib/python3.6/lib-dynload/_ctypes.cpython-36m-x86_64-linux-gnu.so(+0x13a45) [0x7f5566c66a45]
[bt] (9) /home/env_xgb_latest/bin/python(_PyObject_FastCallDict+0x8b) [0x7f5569ab993b]

'
```

**Comment by hcho3** [comment]
@kretes Thanks. The AUCPR metric seems to be quite buggy. I hope I can find time to teach myself the theory and fix it.

**Comment by hcho3** [comment]
@kretes I'd like to try to reproduce the error you posted. Do you have any sample data I can try?

**Comment by hcho3** [comment]
#4436 will fix this.
