### ISSUE TITLE
Saving XGBoost model is failing with NoSuchMethodError

### ISSUE THREAD

**Issue by neha-tomar** [dmlc/xgboost#4470]
I am using XGBoost4J latest release version 0.82 with Spark 2.4. I see below exception while saving the model.

`java.lang.NoSuchMethodError: org.json4s.jackson.JsonMethods$.parse(Lorg/json4s/JsonInput;Z)Lorg/json4s/JsonAST$JValue

	at ml.dmlc.xgboost4j.scala.spark.params.DefaultXGBoostParamsWriter$$anonfun$1$$anonfun$3.apply(DefaultXGBoostParamsWriter.scala:73)
	at ml.dmlc.xgboost4j.scala.spark.params.DefaultXGBoostParamsWriter$$anonfun$1$$anonfun$3.apply(DefaultXGBoostParamsWriter.scala:71)
	at scala.collection.TraversableLike$$anonfun$map$1.apply(TraversableLike.scala:234)
	at scala.collection.TraversableLike$$anonfun$map$1.apply(TraversableLike.scala:234)
	at scala.collection.mutable.ResizableArray$class.foreach(ResizableArray.scala:59)
	at scala.collection.mutable.ArrayBuffer.foreach(ArrayBuffer.scala:48)
	at scala.collection.TraversableLike$class.map(TraversableLike.scala:234)
	at scala.collection.AbstractTraversable.map(Traversable.scala:104)
	at ml.dmlc.xgboost4j.scala.spark.params.DefaultXGBoostParamsWriter$$anonfun$1.apply(DefaultXGBoostParamsWriter.scala:71)
	at ml.dmlc.xgboost4j.scala.spark.params.DefaultXGBoostParamsWriter$$anonfun$1.apply(DefaultXGBoostParamsWriter.scala:69)
	at scala.Option.getOrElse(Option.scala:121)
	at ml.dmlc.xgboost4j.scala.spark.params.DefaultXGBoostParamsWriter$.getMetadataToSave(DefaultXGBoostParamsWriter.scala:69)
	at ml.dmlc.xgboost4j.scala.spark.params.DefaultXGBoostParamsWriter$.saveMetadata(DefaultXGBoostParamsWriter.scala:51)
	at ml.dmlc.xgboost4j.scala.spark.XGBoostRegressionModel$XGBoostRegressionModelWriter.saveImpl(XGBoostRegressor.scala:421)
	at org.apache.spark.ml.util.MLWriter.save(ReadWrite.scala:180)
	at org.apache.spark.ml.Pipeline$SharedReadWrite$$anonfun$saveImpl$1.apply(Pipeline.scala:254)`

**Comment by CodingCat** [comment]
0.82 doesn’t support 2.4

**Comment by hcho3** [comment]
0.82 doesn't support Spark 2.4. Can you wait a little until 0.90 comes out?

**Comment by neha-tomar** [comment]
Thanks for replying. What are the timelines for 0.90?

**Comment by hcho3** [comment]
@neha-tomar It's coming out by end of this week

**Comment by neha-tomar** [comment]
In that case, I can wait for 0.90. I am using Spark 2.4 and need a version that works with that. At present, XGBoost4J documentation says "XGBoost4J-Spark requires Apache Spark 2.4+" and latest release is 0.82. It seems to be incorrect. Could you please provide more clarification in documentation regarding version compatibility. Also, I believe 0.90 would work with Spark 2.4 and above versions. Please confirm.

**Comment by hcho3** [comment]
@neha-tomar You are looking at the documentation for the latest master branch. https://xgboost.readthedocs.io/en/release_0.82/ is the documentation for 0.82 version.
And yes, 0.90 will work with Spark 2.4.3.
