### ISSUE TITLE
Check failed: distribution_.IsEmpty() when reuse DMatrix

### ISSUE THREAD

**Issue by sh1ng** [dmlc/xgboost#4518]
Related to #4513
Reproducible example: https://github.com/h2oai/h2o4gpu/blob/master/tests/python/open_data/gbm/test_xgboost.py 

```
Traceback (most recent call last):
  File "tests/python/open_data/gbm/test_xgboost.py", line 71, in <module>
    test_xgboost_covtype()
  File "tests/python/open_data/gbm/test_xgboost.py", line 67, in test_xgboost_covtype
    def test_xgboost_covtype(): fun()
  File "tests/python/open_data/gbm/test_xgboost.py", line 63, in fun
    (dtest, 'test')], evals_result=cpu_res)
  File "/home/sh1ng/dev/.venv/lib/python3.6/site-packages/xgboost/training.py", line 227, in train
    xgb_model=xgb_model, callbacks=callbacks)
  File "/home/sh1ng/dev/.venv/lib/python3.6/site-packages/xgboost/training.py", line 74, in _train_internal
    bst.update(dtrain, i, obj)
  File "/home/sh1ng/dev/.venv/lib/python3.6/site-packages/xgboost/core.py", line 1115, in update
    dtrain.handle))
  File "/home/sh1ng/dev/.venv/lib/python3.6/site-packages/xgboost/core.py", line 176, in _check_call
    raise XGBoostError(py_str(_LIB.XGBGetLastError()))
xgboost.core.XGBoostError: [12:43:48] /home/sh1ng/dev/h2o4gpu/xgboost/src/common/host_device_vector.cu:363: Check failed: distribution_.IsEmpty(): 
Stack trace:
  [bt] (0) /home/sh1ng/dev/.venv/lib/python3.6/site-packages/xgboost/./lib/libxgboost.so(dmlc::LogMessageFatal::~LogMessageFatal()+0x43) [0x7fe95bc7c323]
  [bt] (1) /home/sh1ng/dev/.venv/lib/python3.6/site-packages/xgboost/./lib/libxgboost.so(xgboost::HostDeviceVectorImpl<float>::Shard(xgboost::GPUDistribution const&)+0x86) [0x7fe95be28256]
  [bt] (2) /home/sh1ng/dev/.venv/lib/python3.6/site-packages/xgboost/./lib/libxgboost.so(xgboost::obj::SoftmaxMultiClassObj::GetGradient(xgboost::HostDeviceVector<float> const&, xgboost::MetaInfo const&, int, xgboost::HostDeviceVector<xgboost::detail::GradientPairInternal<float> >*)+0x205) [0x7fe95be6c535]
  [bt] (3) /home/sh1ng/dev/.venv/lib/python3.6/site-packages/xgboost/./lib/libxgboost.so(xgboost::LearnerImpl::UpdateOneIter(int, xgboost::DMatrix*)+0x276) [0x7fe95bd178a6]
  [bt] (4) /home/sh1ng/dev/.venv/lib/python3.6/site-packages/xgboost/./lib/libxgboost.so(XGBoosterUpdateOneIter+0x48) [0x7fe95bc876d8]
  [bt] (5) /usr/lib/x86_64-linux-gnu/libffi.so.6(ffi_call_unix64+0x4c) [0x7fe9a473ddae]
  [bt] (6) /usr/lib/x86_64-linux-gnu/libffi.so.6(ffi_call+0x22f) [0x7fe9a473d71f]
  [bt] (7) /home/sh1ng/dev/.venv/lib/python3.6/lib-dynload/_ctypes.cpython-36m-x86_64-linux-gnu.so(_ctypes_callproc+0x2b4) [0x7fe9a4951524]
  [bt] (8) /home/sh1ng/dev/.venv/lib/python3.6/lib-dynload/_ctypes.cpython-36m-x86_64-linux-gnu.so(+0x11b93) [0x7fe9a4951b93]


```

If `n_gpus` is specified it works. 
Also recreation of 
```
    # dtrain = xgb.DMatrix(X_train, label=y_train, nthread=-1)
    # dtest = xgb.DMatrix(X_test, label=y_test, nthread=-1)
```
before the second training step fixes the issue.
Is it some kind of bug related to internal `DMatrix`'s state or `DMatrix` is not supposed to be reusable? 
@trivialfis

**Comment by trivialfis** [comment]
Sorry that I won't be here until next week.
