### ISSUE TITLE
[jvm-packages] xgboost-0.81, Check failed: preds.Size() == info.labels_.Size()

### ISSUE THREAD

**Issue by rachelsunrh** [dmlc/xgboost#4524]
hi, when I train a xgboost model(0.81) use objective=binary:logistic, I meet the problem, can you tell me how to solve it ? I have checked my data, the labels are 0 and 1

Lost task 0.0 in stage 6.0 (TID 6, 9.10.135.90, executor 1): ml.dmlc.xgboost4j.java.XGBoostError: [21:47:23] /data/angel/wenbinwei/xgboost-tdw/src/objective/regression_obj.cu:66: Check failed: preds.Size() == info.labels_.Size() (13026 vs. 6513) : labels are not correctly providedpreds.size=13026, label.size=6513
Stack trace:
[bt] (0) /data7/yarnenv/local/usercache/lhotse/appcache/application_1555301652009_20695514/container_e10_1555301652009_20695514_01_000002/tmp/libxgboost4j_xeon4705135393324394044.so(dmlc::LogMessageFatal::~LogMessageFatal()+0x22) [0x7f94a7de7422]
[bt] (1) /data7/yarnenv/local/usercache/lhotse/appcache/application_1555301652009_20695514/container_e10_1555301652009_20695514_01_000002/tmp/libxgboost4j_xeon4705135393324394044.so(xgboost::obj::RegLossObjxgboost::obj::LogisticClassification::GetGradient(xgboost::HostDeviceVector const&, xgboost::MetaInfo const&, int, xgboost::HostDeviceVector<xgboost::detail::GradientPairInternal >)+0x20e) [0x7f94a7ef012e]
[bt] (2) /data7/yarnenv/local/usercache/lhotse/appcache/application_1555301652009_20695514/container_e10_1555301652009_20695514_01_000002/tmp/libxgboost4j_xeon4705135393324394044.so(xgboost::LearnerImpl::UpdateOneIter(int, xgboost::DMatrix)+0x362) [0x7f94a7e7dac2]
[bt] (3) /data7/yarnenv/local/usercache/lhotse/appcache/application_1555301652009_20695514/container_e10_1555301652009_20695514_01_000002/tmp/libxgboost4j_xeon4705135393324394044.so(XGBoosterUpdateOneIter+0x35) [0x7f94a7dee9d5]
[bt] (4) [0x7f94d5018667]

at ml.dmlc.xgboost4j.java.XGBoostJNI.checkCall(XGBoostJNI.java:48)
at ml.dmlc.xgboost4j.java.Booster.update(Booster.java:124)
at ml.dmlc.xgboost4j.java.XGBoost.train(XGBoost.java:188)
at ml.dmlc.xgboost4j.scala.XGBoost$.train(XGBoost.scala:64)
at ml.dmlc.xgboost4j.scala.spark.XGBoost$.ml$dmlc$xgboost4j$scala$spark$XGBoost$$buildDistributedBooster(XGBoost.scala:141)
at ml.dmlc.xgboost4j.scala.spark.XGBoost$$anonfun$trainDistributed$4$$anonfun$12.apply(XGBoost.scala:279)
at ml.dmlc.xgboost4j.scala.spark.XGBoost$$anonfun$trainDistributed$4$$anonfun$12.apply(XGBoost.scala:275)
at org.apache.spark.rdd.RDD$$anonfun$mapPartitions$1$$anonfun$apply$23.apply(RDD.scala:800)
at org.apache.spark.rdd.RDD$$anonfun$mapPartitions$1$$anonfun$apply$23.apply(RDD.scala:800)
at org.apache.spark.rdd.MapPartitionsRDD.compute(MapPartitionsRDD.scala:38)
at org.apache.spark.rdd.RDD.computeOrReadCheckpoint(RDD.scala:324)
at org.apache.spark.rdd.RDD$$anonfun$7.apply(RDD.scala:337)
at org.apache.spark.rdd.RDD$$anonfun$7.apply(RDD.scala:335)
at org.apache.spark.storage.BlockManager$$anonfun$doPutIterator$1.apply(BlockManager.scala:1092)
at org.apache.spark.storage.BlockManager$$anonfun$doPutIterator$1.apply(BlockManager.scala:1083)
at org.apache.spark.storage.BlockManager.doPut(BlockManager.scala:1018)
at org.apache.spark.storage.BlockManager.doPutIterator(BlockManager.scala:1083)
at org.apache.spark.storage.BlockManager.getOrElseUpdate(BlockManager.scala:809)
at org.apache.spark.rdd.RDD.getOrCompute(RDD.scala:335)
at org.apache.spark.rdd.RDD.iterator(RDD.scala:286)
at org.apache.spark.scheduler.ResultTask.runTask(ResultTask.scala:87)
at org.apache.spark.scheduler.Task.run(Task.scala:109)
at org.apache.spark.executor.Executor$TaskRunner.run(Executor.scala:345)
at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
at java.lang.Thread.run(Thread.java:748)

**Comment by CodingCat** [comment]
can you post your training param?
