### ISSUE TITLE
java.lang.NoClassDefFoundError: ml/dmlc/xgboost4j/scala/ObjectiveTrait

### ISSUE THREAD

**Issue by Jafee** [dmlc/xgboost#4666]
> spark-shell --jars xgboost4j-spark-0.90.jar

Spark session available as 'spark'.
Welcome to
      ____              __
     / __/__  ___ _____/ /__
    _\ \/ _ \/ _ `/ __/  '_/
   /___/ .__/\_,_/_/ /_/\_\   version 2.4.3
      /_/

Using Scala version 2.11.12 (Java HotSpot(TM) 64-Bit Server VM, Java 1.8.0_191)

```scala

import org.apache.spark.ml.{Pipeline, PipelineModel}
import org.apache.spark.ml.evaluation.MulticlassClassificationEvaluator
import org.apache.spark.ml.feature._
import org.apache.spark.ml.tuning._
import org.apache.spark.sql.SparkSession
import org.apache.spark.sql.types._

import ml.dmlc.xgboost4j.scala.spark.{XGBoostClassifier, XGBoostClassificationModel}


val booster = new XGBoostClassifier(
      Map("eta" -> 0.1f,
        "max_depth" -> 2,
        "objective" -> "multi:softprob",
        "num_class" -> 3,
        "num_round" -> 100,
        "num_workers" -> 2
      )
    )

```

java.lang.NoClassDefFoundError: ml/dmlc/xgboost4j/scala/ObjectiveTrait
  at java.lang.Class.getDeclaredMethods0(Native Method)
  at java.lang.Class.privateGetDeclaredMethods(Class.java:2701)
  at java.lang.Class.privateGetPublicMethods(Class.java:2902)
  at java.lang.Class.getMethods(Class.java:1615)
  at org.apache.spark.ml.param.Params$class.params(params.scala:675)
  at org.apache.spark.ml.PipelineStage.params$lzycompute(Pipeline.scala:42)
  at org.apache.spark.ml.PipelineStage.params(Pipeline.scala:42)
  at ml.dmlc.xgboost4j.scala.spark.params.ParamMapFuncs$$anonfun$XGBoostToMLlibParams$2.apply(GeneralParams.scala:254)
  at ml.dmlc.xgboost4j.scala.spark.params.ParamMapFuncs$$anonfun$XGBoostToMLlibParams$2.apply(GeneralParams.scala:245)
  at scala.collection.TraversableLike$WithFilter$$anonfun$foreach$1.apply(TraversableLike.scala:733)
  at scala.collection.immutable.HashMap$HashMap1.foreach(HashMap.scala:221)
  at scala.collection.immutable.HashMap$HashTrieMap.foreach(HashMap.scala:428)
  at scala.collection.TraversableLike$WithFilter.foreach(TraversableLike.scala:732)
  at ml.dmlc.xgboost4j.scala.spark.params.ParamMapFuncs$class.XGBoostToMLlibParams(GeneralParams.scala:245)
  at ml.dmlc.xgboost4j.scala.spark.XGBoostClassifier.XGBoostToMLlibParams(XGBoostClassifier.scala:44)
  at ml.dmlc.xgboost4j.scala.spark.XGBoostClassifier.<init>(XGBoostClassifier.scala:57)
  at ml.dmlc.xgboost4j.scala.spark.XGBoostClassifier.<init>(XGBoostClassifier.scala:54)
  ... 63 elided
Caused by: java.lang.ClassNotFoundException: ml.dmlc.xgboost4j.scala.ObjectiveTrait
  at java.net.URLClassLoader.findClass(URLClassLoader.java:382)
  at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
  at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
  ... 80 more

**Comment by CodingCat** [comment]
you need to include xgboost4j-0.90.jar as well
