### ISSUE TITLE
[jvm-package] XGBoost4J-Spark : Unable to get 250 workers for XGBoost training

### ISSUE THREAD

**Issue by chenxyGG** [dmlc/xgboost#4715]
**error logs:**

User class threw exception: java.lang.IllegalStateException: Unable to get 250 workers for XGBoost training
at org.apache.spark.SparkParallelismTracker.execute(SparkParallelismTracker.scala:109)
at ml.dmlc.xgboost4j.scala.spark.XGBoost$$anonfun$trainDistributed$2.apply(XGBoost.scala:457)
at ml.dmlc.xgboost4j.scala.spark.XGBoost$$anonfun$trainDistributed$2.apply(XGBoost.scala:435)
at scala.collection.TraversableLike$$anonfun$map$1.apply(TraversableLike.scala:234)
at scala.collection.TraversableLike$$anonfun$map$1.apply(TraversableLike.scala:234)
at scala.collection.immutable.List.foreach(List.scala:392)
at scala.collection.TraversableLike$class.map(TraversableLike.scala:234)
at scala.collection.immutable.List.map(List.scala:296)
at ml.dmlc.xgboost4j.scala.spark.XGBoost$.trainDistributed(XGBoost.scala:434)
at ml.dmlc.xgboost4j.scala.spark.XGBoostClassifier.train(XGBoostClassifier.scala:194)
at ml.dmlc.xgboost4j.scala.spark.XGBoostClassifier.train(XGBoostClassifier.scala:44)
at org.apache.spark.ml.Predictor.fit(Predictor.scala:118)
at com.xxx.algo.tag_model.ModelUtils$.train(ModelUtils.scala:18)
at com.xxx.algo.tag_model.TagModelBuild$.main(TagModelBuild.scala:56)
at com.xxxi.algo.tag_model.TagModelBuild.main(TagModelBuild.scala)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.lang.reflect.Method.invoke(Method.java:498)
at org.apache.spark.deploy.yarn.ApplicationMaster$$anon$2.run(ApplicationMaster.scala:688)

**version**
 

- <spark.version>2.4.0</spark.version>
-  <xgb4j.version>0.90</xgb4j.version>

**spark submit params**

- driver_memory=5G
- executor_num=250
- executor_core=1
- executor_core_memory=6G

**description**

set executor_num value to num_workers of xgboost, and the env of cluster has enough cores and memory ( which is about 91 machine in cluster and 16 cores in each machine ). 
so why this error happened?  

**part code**

```
properties.setProperty("gender.predict.xgb.params.num_workers", executorNum.toString)
properties.setProperty("gender.predict.xgb.params.nthread", executorCoreNum.toString)
```

 ```
val xgbBasicParam = Map(
"objective" -> paramsMap("objective"), 
"num_class" -> paramsMap("num_class").toInt, 
"num_round" -> paramsMap("num_round").toInt, 
"num_workers" -> paramsMap("num_workers").toInt, 
"nthread" -> paramsMap("nthread").toInt, 
"missing" -> paramsMap("missing").toInt
)
 val clf: XGBoostClassifier = new XGBoostClassifier(xgbBasicParam)
.setFeaturesCol("features")
.setLabelCol("label_index")

// set hy-params, such as clf.setEta(paramsMap("eta").toDouble)
xgbHyParamsSet(clf, paramsMap)
```

 ```
// get params map by prop file
 val paramsMap = getXgbParamsMap(prop, predictObj)
// set params of xgb model 
val clf = xgbClfBuild(paramsMap)
 Logger.info("debug numWorkers: " + clf.getNumWorkers)
 // the row num of df is about 5 million+ and feature size is about 420
  clf.fit(trainSampleDf)
```

**Comment by chenxyGG** [comment]
What is the true meaning of this parameter [ num_workers ]? machine num or core num or others ?

**Comment by chenxyGG** [comment]
**reason**

XGBoost4J-Spark requires that all of nthread * numWorkers cores should be available before the training runs.
XGBoost4J-Spark allows the user to setup a timeout threshold for claiming resources from the cluster. If the application cannot get enough resources within this time period, the application would fail instead of wasting resources for hanging long. To enable this feature, you can set with XGBoostClassifier/XGBoostRegressor:

**solution**

add timeoutRequestWorkers setting to XGBParamsMap

```
gender.predict.xgb.params.timeout_request_workers=60000L

val timeoutRequestWorkers = prop.getProperty("age.predict.xgb.params.timeout_request_workers")

"timeout_request_workers" -> paramsMap("timeout_request_workers").toLong
```
