### ISSUE TITLE
libhdfs.so.0.0.0: wrong ELF class: ELFCLASS32 when spark-submit xgboost java class on the yarn clusters

### ISSUE THREAD

**Issue by IreneTang93** [dmlc/xgboost#4720]
Hi,
I try to spark-submit xgboost java class on the yarn clusters.

The jars uploaded are produced under jvm-packages using "mvn clean package".
I edited these confs to utilize the hdfs:
```
make/config.mk  USE_HDFS=1
dmlc-core/make/config.mk  USE_HDFS=1
jvm-packages/create_jni.py  "USE_HDFS": "ON"
```
Also, I obey the steps in https://github.com/dmlc/dmlc-core/issues/10 to utilize cdh.

But, after I using the spark-submit to submit my job, the wrong ELF class: ELFCLASS32 happened in the running container of the yarn clusters.
The command I run, the jars uploaded are produced under jvm-packages: 
`spark-submit --class xgboostTreeModel --jars ../xgboost4j-spark-0.72.jar,../xgboost4j-0.72.jar xgboost.jar xgboost.jar`

And the error output:
>19/07/30 21:17:39 INFO yarn.ApplicationMaster: Waiting for spark context initialization...
19/07/30 21:17:39 ERROR yarn.ApplicationMaster: User class threw exception: java.lang.UnsatisfiedLinkError: /data2/mapred/local/usercache/hadoop/appcache/application_827396/container_1563872801052/tmp/libxgboost4j355029937936098148.so: libhdfs.so.0.0.0: wrong ELF class: ELFCLASS32
java.lang.UnsatisfiedLinkError: /data2/mapred/local/usercache/hadoop/appcache/application_827396//container_1563872801052/tmp/libxgboost4j355029937936098148.so: libhdfs.so.0.0.0: wrong ELF class: ELFCLASS32
	at java.lang.ClassLoader$NativeLibrary.load(Native Method)
	at java.lang.ClassLoader.loadLibrary1(ClassLoader.java:1965)
	at java.lang.ClassLoader.loadLibrary0(ClassLoader.java:1890)
	at java.lang.ClassLoader.loadLibrary(ClassLoader.java:1851)
	at java.lang.Runtime.load0(Runtime.java:795)
	at java.lang.System.load(System.java:1062)
	at ml.dmlc.xgboost4j.java.NativeLibLoader.loadLibraryFromJar(NativeLibLoader.java:66)
	at ml.dmlc.xgboost4j.java.NativeLibLoader.smartLoad(NativeLibLoader.java:152)
	at ml.dmlc.xgboost4j.java.NativeLibLoader.initXGBoost(NativeLibLoader.java:40)
	at ml.dmlc.xgboost4j.java.XGBoostJNI.<clinit>(XGBoostJNI.java:34)
	at ml.dmlc.xgboost4j.java.DMatrix.<init>(DMatrix.java:68)
	at xgboostTreeModel.main(xgboostTreeModel.java:10)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:606)
	at org.apache.spark.deploy.yarn.ApplicationMaster$$anon$2.run(ApplicationMaster.scala:638)
19/07/30 21:17:39 INFO yarn.ApplicationMaster: Final app status: FAILED, exitCode: 15, (reason: User class threw exception: java.lang.UnsatisfiedLinkError: /data2/mapred/local/usercache/hadoop/appcache/application_827396/container_1563872801052/tmp/libxgboost4j355029937936098148.so: libhdfs.so.0.0.0: wrong ELF class: ELFCLASS32)
19/07/30 21:17:39 ERROR yarn.ApplicationMaster: Uncaught exception: 
org.apache.spark.SparkException: Exception thrown in awaitResult: 
	at org.apache.spark.util.ThreadUtils$.awaitResult(ThreadUtils.scala:194)
	at org.apache.spark.deploy.yarn.ApplicationMaster.runDriver(ApplicationMaster.scala:401)
	at org.apache.spark.deploy.yarn.ApplicationMaster.run(ApplicationMaster.scala:254)
	at org.apache.spark.deploy.yarn.ApplicationMaster$$anonfun$main$1.apply$mcV$sp(ApplicationMaster.scala:767)
	at org.apache.spark.deploy.SparkHadoopUtil$$anon$1.run(SparkHadoopUtil.scala:75)
	at org.apache.spark.deploy.SparkHadoopUtil$$anon$1.run(SparkHadoopUtil.scala:74)
	at java.security.AccessController.doPrivileged(Native Method)
	at javax.security.auth.Subject.doAs(Subject.java:415)
	at org.apache.hadoop.security.UserGroupInformation.doAs(UserGroupInformation.java:1616)
	at org.apache.spark.deploy.SparkHadoopUtil.runAsSparkUser(SparkHadoopUtil.scala:74)
	at org.apache.spark.deploy.yarn.ApplicationMaster$.main(ApplicationMaster.scala:765)
	at org.apache.spark.deploy.yarn.ApplicationMaster.main(ApplicationMaster.scala)
Caused by: java.util.concurrent.ExecutionException: Boxed Error
	at scala.concurrent.impl.Promise$.resolver(Promise.scala:55)
	at scala.concurrent.impl.Promise$.scala$concurrent$impl$Promise$$resolveTry(Promise.scala:47)
	at scala.concurrent.impl.Promise$DefaultPromise.tryComplete(Promise.scala:244)
	at scala.concurrent.Promise$class.tryFailure(Promise.scala:112)
	at scala.concurrent.impl.Promise$DefaultPromise.tryFailure(Promise.scala:153)
	at org.apache.spark.deploy.yarn.ApplicationMaster$$anon$2.run(ApplicationMaster.scala:656)
Caused by: java.lang.UnsatisfiedLinkError: /data2/mapred/local/usercache/hadoop/appcache/application_827396/container_1563872801052/tmp/libxgboost4j355029937936098148.so: libhdfs.so.0.0.0: wrong ELF class: ELFCLASS32
	at java.lang.ClassLoader$NativeLibrary.load(Native Method)
	at java.lang.ClassLoader.loadLibrary1(ClassLoader.java:1965)
	at java.lang.ClassLoader.loadLibrary0(ClassLoader.java:1890)
	at java.lang.ClassLoader.loadLibrary(ClassLoader.java:1851)
	at java.lang.Runtime.load0(Runtime.java:795)
	at java.lang.System.load(System.java:1062)
	at ml.dmlc.xgboost4j.java.NativeLibLoader.loadLibraryFromJar(NativeLibLoader.java:66)
	at ml.dmlc.xgboost4j.java.NativeLibLoader.smartLoad(NativeLibLoader.java:152)
	at ml.dmlc.xgboost4j.java.NativeLibLoader.initXGBoost(NativeLibLoader.java:40)
	at ml.dmlc.xgboost4j.java.XGBoostJNI.<clinit>(XGBoostJNI.java:34)
	at ml.dmlc.xgboost4j.java.DMatrix.<init>(DMatrix.java:68)
	at xgboostTreeModel.main(xgboostTreeModel.java:10)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:606)
	at org.apache.spark.deploy.yarn.ApplicationMaster$$anon$2.run(ApplicationMaster.scala:638)
19/07/30 21:17:39 INFO yarn.ApplicationMaster: Unregistering ApplicationMaster with FAILED (diag message: User class threw exception: java.lang.UnsatisfiedLinkError: /data2/mapred/local/usercache/hadoop/appcache/application_827396/container_1563872801052/tmp/libxgboost4j355029937936098148.so: libhdfs.so.0.0.0: wrong ELF class: ELFCLASS32)
19/07/30 21:17:39 INFO yarn.ApplicationMaster: Deleting staging directory hdfs://hcat4cluster/spark-staging/.sparkStaging/application_827396
19/07/30 21:17:39 INFO util.ShutdownHookManager: Shutdown hook called

>

**Comment by chenxyGG** [comment]
Why not add spark4j-spark setting to your pom to building your project?

**Comment by IreneTang93** [comment]
> Why not add spark4j-spark setting to your pom to building your project?

Do you mean xgboost4j-spark of the spark4j-spark?

**Comment by IreneTang93** [comment]
The problem is solved by the following steps:
1. add dependency xgboost4j to my pom
2. recompiling the libhdfs.a after adding "-fPIC" to almost all CMAKE flags in CMakeCache under hadoop src.
3. use libhdfs.a to compile xgboost jars.

But after solving this problem, more problems came out due to so many dynamic lib *.so links to libxgboost4j.so,
such as 
libgomp.so.1: version `GOMP_4.0' not found；
libm.so.6: version `GLIBC_2.23' not found
I try to add "-static" to gcc command, but failed because
`/usr/bin/ld: attempted static link of dynamic object `/usr/java/jdk1.7.0_80/jre/lib/amd64/server/libjvm.so'
collect2: error: ld returned 1 exit status
make[2]: *** [../xgboost] Error 1
CMakeFiles/runxgboost.dir/build.make:176: recipe for target '../xgboost' failed
CMakeFiles/Makefile2:69: recipe for target 'CMakeFiles/runxgboost.dir/all' failed
make[1]: *** [CMakeFiles/runxgboost.dir/all] Error 2
Makefile:127: recipe for target 'all' failed
make: *** [all] Error 2`
Can anybody tell me how far I am from success? The installation of distributed xgboost has taken me days to try without documentation. If there are lots of pits like this need ability and time to make clear all relative c++ source code, may be it's time to give up... 
Really really need advices of you who has ever run distributed xgboost successfully on yarn.

**Comment by hcho3** [comment]
Looks like your cluster has old version of OpenMP runtime and GLIBC?

**Comment by IreneTang93** [comment]
> Looks like your cluster has old version of OpenMP runtime and GLIBC?

Yes, it has old version and I don't have right to change it. Is there any way to run xgboost on the old system?

**Comment by trivialfis** [comment]
Doesn't seem to be a problem for XGBoost to solve.  Closing.
