### ISSUE TITLE
XGBoost Training Failed, with 14GB csv data file

### ISSUE THREAD

**Issue by leizhanggit** [dmlc/xgboost#4721]
Hello, 

I am trying to train a model with 14GB csv data file. I just made a slight change of the spark demo code. (I have no problem to run the demo code with the mortgage data ) 

Here is the error:

```
------ Training ------
Tracker started, with env={DMLC_NUM_SERVER=0, DMLC_TRACKER_URI=10.139.64.33, DMLC_TRACKER_PORT=9091, DMLC_NUM_WORKER=1}
ml.dmlc.xgboost4j.java.XGBoostError: XGBoostModel training failed
```
and the debug message:

```

	at ml.dmlc.xgboost4j.scala.spark.XGBoost$.ml$dmlc$xgboost4j$scala$spark$XGBoost$$postTrackerReturnProcessing(XGBoost.scala:795)
	at ml.dmlc.xgboost4j.scala.spark.XGBoost$$anonfun$trainDistributedForGpuDataset$1.apply(XGBoost.scala:609)
	at ml.dmlc.xgboost4j.scala.spark.XGBoost$$anonfun$trainDistributedForGpuDataset$1.apply(XGBoost.scala:591)
	at scala.collection.TraversableLike$$anonfun$map$1.apply(TraversableLike.scala:234)
	at scala.collection.TraversableLike$$anonfun$map$1.apply(TraversableLike.scala:234)
	at scala.collection.immutable.List.foreach(List.scala:392)
	at scala.collection.TraversableLike$class.map(TraversableLike.scala:234)
	at scala.collection.immutable.List.map(List.scala:296)
	at ml.dmlc.xgboost4j.scala.spark.XGBoost$.trainDistributedForGpuDataset(XGBoost.scala:590)
	at ml.dmlc.xgboost4j.scala.spark.XGBoostClassifier.fit(XGBoostClassifier.scala:258)
	at linee6f0a941471544b887f97374bba146ad102.$read$$iw$$iw$$iw$$iw$$iw$$iw$$anonfun$1.apply(command-1436081708071208:14)
	at linee6f0a941471544b887f97374bba146ad102.$read$$iw$$iw$$iw$$iw$$iw$$iw$$anonfun$1.apply(command-1436081708071208:14)
	at linee6f0a941471544b887f97374bba146ad102.$read$$iw$$iw$$iw$$iw$$iw$$iw$Benchmark$.time(command-1436081708071208:4)
	at linee6f0a941471544b887f97374bba146ad102.$read$$iw$$iw$$iw$$iw$$iw$$iw.<init>(command-1436081708071208:13)
	at linee6f0a941471544b887f97374bba146ad102.$read$$iw$$iw$$iw$$iw$$iw.<init>(command-1436081708071208:73)
	at linee6f0a941471544b887f97374bba146ad102.$read$$iw$$iw$$iw$$iw.<init>(command-1436081708071208:75)
	at linee6f0a941471544b887f97374bba146ad102.$read$$iw$$iw$$iw.<init>(command-1436081708071208:77)
	at linee6f0a941471544b887f97374bba146ad102.$read$$iw$$iw.<init>(command-1436081708071208:79)
	at linee6f0a941471544b887f97374bba146ad102.$read$$iw.<init>(command-1436081708071208:81)
	at linee6f0a941471544b887f97374bba146ad102.$read.<init>(command-1436081708071208:83)
	at linee6f0a941471544b887f97374bba146ad102.$read$.<init>(command-1436081708071208:87)
	at linee6f0a941471544b887f97374bba146ad102.$read$.<clinit>(command-1436081708071208)
	at linee6f0a941471544b887f97374bba146ad102.$eval$.$print$lzycompute(<notebook>:7)
	at linee6f0a941471544b887f97374bba146ad102.$eval$.$print(<notebook>:6)
	at linee6f0a941471544b887f97374bba146ad102.$eval.$print(<notebook>)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at scala.tools.nsc.interpreter.IMain$ReadEvalPrint.call(IMain.scala:793)
	at scala.tools.nsc.interpreter.IMain$Request.loadAndRun(IMain.scala:1054)
	at scala.tools.nsc.interpreter.IMain$WrappedRequest$$anonfun$loadAndRunReq$1.apply(IMain.scala:645)
	at scala.tools.nsc.interpreter.IMain$WrappedRequest$$anonfun$loadAndRunReq$1.apply(IMain.scala:644)
	at scala.reflect.internal.util.ScalaClassLoader$class.asContext(ScalaClassLoader.scala:31)
	at scala.reflect.internal.util.AbstractFileClassLoader.asContext(AbstractFileClassLoader.scala:19)
	at scala.tools.nsc.interpreter.IMain$WrappedRequest.loadAndRunReq(IMain.scala:644)
	at scala.tools.nsc.interpreter.IMain.interpret(IMain.scala:576)
	at scala.tools.nsc.interpreter.IMain.interpret(IMain.scala:572)
	at com.databricks.backend.daemon.driver.DriverILoop.execute(DriverILoop.scala:215)
	at com.databricks.backend.daemon.driver.ScalaDriverLocal$$anonfun$repl$1.apply$mcV$sp(ScalaDriverLocal.scala:197)
	at com.databricks.backend.daemon.driver.ScalaDriverLocal$$anonfun$repl$1.apply(ScalaDriverLocal.scala:197)
	at com.databricks.backend.daemon.driver.ScalaDriverLocal$$anonfun$repl$1.apply(ScalaDriverLocal.scala:197)
	at com.databricks.backend.daemon.driver.DriverLocal$TrapExitInternal$.trapExit(DriverLocal.scala:653)
	at com.databricks.backend.daemon.driver.DriverLocal$TrapExit$.apply(DriverLocal.scala:606)
	at com.databricks.backend.daemon.driver.ScalaDriverLocal.repl(ScalaDriverLocal.scala:197)
	at com.databricks.backend.daemon.driver.DriverLocal$$anonfun$execute$8.apply(DriverLocal.scala:342)
	at com.databricks.backend.daemon.driver.DriverLocal$$anonfun$execute$8.apply(DriverLocal.scala:319)
	at com.databricks.logging.UsageLogging$$anonfun$withAttributionContext$1.apply(UsageLogging.scala:238)
	at scala.util.DynamicVariable.withValue(DynamicVariable.scala:58)
	at com.databricks.logging.UsageLogging$class.withAttributionContext(UsageLogging.scala:233)
	at com.databricks.backend.daemon.driver.DriverLocal.withAttributionContext(DriverLocal.scala:47)
	at com.databricks.logging.UsageLogging$class.withAttributionTags(UsageLogging.scala:271)
	at com.databricks.backend.daemon.driver.DriverLocal.withAttributionTags(DriverLocal.scala:47)
	at com.databricks.backend.daemon.driver.DriverLocal.execute(DriverLocal.scala:319)
	at com.databricks.backend.daemon.driver.DriverWrapper$$anonfun$tryExecutingCommand$2.apply(DriverWrapper.scala:644)
	at com.databricks.backend.daemon.driver.DriverWrapper$$anonfun$tryExecutingCommand$2.apply(DriverWrapper.scala:644)
	at scala.util.Try$.apply(Try.scala:192)
	at com.databricks.backend.daemon.driver.DriverWrapper.tryExecutingCommand(DriverWrapper.scala:639)
	at com.databricks.backend.daemon.driver.DriverWrapper.getCommandOutputAndError(DriverWrapper.scala:485)
	at com.databricks.backend.daemon.driver.DriverWrapper.executeCommand(DriverWrapper.scala:597)
	at com.databricks.backend.daemon.driver.DriverWrapper.runInnerLoop(DriverWrapper.scala:390)
	at com.databricks.backend.daemon.driver.DriverWrapper.runInner(DriverWrapper.scala:337)
	at com.databricks.backend.daemon.driver.DriverWrapper.run(DriverWrapper.scala:219)
	at java.lang.Thread.run(Thread.java:748)
```

Here is the configuration of the cluster:
Standard_NC6s_v3 (beta) .  (driver)
Standard_NC6s_v3 (beta) .   (worker)
5.4 ML (includes Apache Spark 2.4 

I recall there may be null values in the data columns. Could it be the problem?

**Comment by chenqin** [comment]
trainDistributedForGpuDataset @rongou

**Comment by CodingCat** [comment]
this is not a open source version of xgboost, please ask databricks what is
happening
