### ISSUE TITLE
[jvm-package] XGBoost4J-Spark The number of classes in dataset doesn't match 'num_class' in xgboost params

### ISSUE THREAD

**Issue by chenxyGG** [dmlc/xgboost#4723]
**Logs**

User class threw exception: java.lang.Exception: The number of classes in dataset doesn't match 'num_class' in xgboost params.
at ml.dmlc.xgboost4j.scala.spark.XGBoostClassifier.train(XGBoostClassifier.scala:172)
at ml.dmlc.xgboost4j.scala.spark.XGBoostClassifier.train(XGBoostClassifier.scala:44)
at org.apache.spark.ml.Predictor.fit(Predictor.scala:118)
at com.yoyi.algo.tag_model.ModelUtils$.train(ModelUtils.scala:19)
at com.yoyi.algo.tag_model.TagModelBuild$.main(TagModelBuild.scala:51)
at com.yoyi.algo.tag_model.TagModelBuild.main(TagModelBuild.scala)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.lang.reflect.Method.invoke(Method.java:498)
at org.apache.spark.deploy.yarn.ApplicationMaster$$anon$2.run(ApplicationMaster.scala:688)

**part code**
`
sampleRawDf.select("label").distinct().show()
`
+-----+
|label|
+-----+
|    3|
|    5|
|    6|
|    4|
|    2|
+-----+
```
  val clf = xgbClfBuild(paramsMap, predictObj)
    Logger.info("debug numWorkers: " + clf.getNumWorkers)
    Logger.info("debug numClass: " + clf.getNumClass)
    clf.fit(trainSampleDf)
```
- INFO utils.Logger$: debug numWorkers: 80
- INFO utils.Logger$: debug numClass: 8

The official document of xgboost note that : label must be in [0, num_class)
the label of this sample is show above this, and so why error happened ?

**Comment by CodingCat** [comment]
you have only 5 classes but set num_class as 8?

@hcho3 I don't think xgb support such scenario?

**Comment by hcho3** [comment]
@CodingCat I don't think so

**Comment by chenxyGG** [comment]
@CodingCat this train sample is filter by some condition, so the label of reserve samples is just these. And the importance is that if follow official docs , the label value is just required in legal range, as [0, num_class) , actually happened types of label is not in consideration.

**Comment by chenxyGG** [comment]
@hcho3 some ideas or suggestions ?

**Comment by hcho3** [comment]
@chenxyGG I don't think it makes sense to set num_class to 8 if there are actually only five distinct class values. XGBoost cannot produce a model for data labels it has never seen.

**Comment by chenxyGG** [comment]
First, the sample daily updated, and then the determinate maximum range of label which is [0,7], so it can not sure actual range of every day.
Do you have some new ideas ?

**Comment by hcho3** [comment]
@CodingCat Any idea about this use case?

**Comment by chenxyGG** [comment]
To make sure the sample num of each label is up to 0, try to add a little noise sample in each label partition during train process. 
Now, it's running. But obviously, it's unfriendly solution to label partition which has small sample or no sample @hcho3

**Comment by CodingCat** [comment]
it's a typical use case to use stringtoIndex and indextoString in spark mllib
