### ISSUE TITLE
Xgboost error while training

### ISSUE THREAD

**Issue by Akpadhy** [dmlc/xgboost#4750]
val vc = new VectorAssembler().setInputCols(Array("orders_prev60min",
"orders_prev_15min_avg",
"orders_prev30min",
"orders_prevdayhr",
"item_slot_o2p_avg_1D",
"orders_prev_15min_max",
"items_past_avg_prev60min",
"trend_items_past_avg_prev30_60min",
"O2P_avg_prev30min")).setOutputCol("features")

val xgbParam = Map(
      "max_depth" -> 10)
      
val xgbreg = new XGBoostRegressor(xgbParam).setFeaturesCol("features").setLabelCol("percent_bad_orders_30_or")

val pipeline = new Pipeline().setStages(Array(vc, xgbreg))
val model = pipeline.fit(train_data)

xgbParam: scala.collection.immutable.Map[String,Int] = Map(max_depth -> 10)
xgbreg: ml.dmlc.xgboost4j.scala.spark.XGBoostRegressor = xgbr_6f476f0668c8
pipeline: org.apache.spark.ml.Pipeline = pipeline_dce0f74cc50e
ml.dmlc.xgboost4j.java.XGBoostError: XGBoostModel training failed
  at ml.dmlc.xgboost4j.scala.spark.XGBoost$.ml$dmlc$xgboost4j$scala$spark$XGBoost$$postTrackerReturnProcessing(XGBoost.scala:364)
  at ml.dmlc.xgboost4j.scala.spark.XGBoost$$anonfun$trainDistributed$4.apply(XGBoost.scala:294)
  at ml.dmlc.xgboost4j.scala.spark.XGBoost$$anonfun$trainDistributed$4.apply(XGBoost.scala:256)
  at scala.collection.TraversableLike$$anonfun$map$1.apply(TraversableLike.scala:234)
  at scala.collection.TraversableLike$$anonfun$map$1.apply(TraversableLike.scala:234)
  at scala.collection.immutable.List.foreach(List.scala:392)
  at scala.collection.TraversableLike$class.map(TraversableLike.scala:234)
  at scala.collection.immutable.List.map(List.scala:296)
  at ml.dmlc.xgboost4j.scala.spark.XGBoost$.trainDistributed(XGBoost.scala:255)
  at ml.dmlc.xgboost4j.scala.spark.XGBoostRegressor.train(XGBoostRegressor.scala:195)
  at ml.dmlc.xgboost4j.scala.spark.XGBoostRegressor.train(XGBoostRegressor.scala:48)
  at org.apache.spark.ml.Predictor.fit(Predictor.scala:118)
  at org.apache.spark.ml.Predictor.fit(Predictor.scala:82)
  at org.apache.spark.ml.Pipeline$$anonfun$fit$2.apply(Pipeline.scala:153)
  at org.apache.spark.ml.Pipeline$$anonfun$fit$2.apply(Pipeline.scala:149)
  at scala.collection.Iterator$class.foreach(Iterator.scala:891)
  at scala.collection.AbstractIterator.foreach(Iterator.scala:1334)
  at scala.collection.IterableViewLike$Transformed$class.foreach(IterableViewLike.scala:44)
  at scala.collection.SeqViewLike$AbstractTransformed.foreach(SeqViewLike.scala:37)
  at org.apache.spark.ml.Pipeline.fit(Pipeline.scala:149)

**Comment by trivialfis** [comment]
Closing stalled issue with no reproducible example.
