### ISSUE TITLE
[JVM-packages] reg:squarederror/reg:squaredlogerror throwing error

### ISSUE THREAD

**Issue by naifmeh** [dmlc/xgboost#4760]
Setting reg:squarederror or reg:squaredlogerror is throwing the following error : 
`java.lang.IllegalArgumentException: xgbr_d46856a24d39 parameter objective given invalid value reg:squarederror`

I am using the xgboost4j-spark package, in its 0.90 version (latest stable one).

Here is the map parameter I am passing to the XGBoostRegressor : 

`val xgbParam = Map("eta" -> 0.05f, 
                  "max_depth" -> 10,
                   "objective" -> "reg:squarederror",
                   "booster"-> "gbtree",
                   "eval_metric" -> "mae",
                  "n_estimators"-> 250,
                  "reg_lambda" -> 2,
                  "gamma" -> 2,
                  "alpha" -> 2)`

**Comment by trivialfis** [comment]
@naifmeh Could you please give a complete back trace?

**Comment by naifmeh** [comment]
@trivialfis Sure, here it is : 

`
java.lang.IllegalArgumentException: xgbr_0c00fdea2675 parameter objective given invalid value reg:squarederror
at org.apache.spark.ml.param.Param.validate(params.scala:77)
	at org.apache.spark.ml.param.ParamPair.<init>(params.scala:656)
	at org.apache.spark.ml.param.Param.$minus$greater(params.scala:87)
	at org.apache.spark.ml.param.Params$class.set(params.scala:737)
	at org.apache.spark.ml.PipelineStage.set(Pipeline.scala:42)
	at ml.dmlc.xgboost4j.scala.spark.XGBoostRegressor.setObjective(XGBoostRegressor.scala:131)
	at linea5d1cf79e88c438da37acb40f9dd904e140.$read$$iw$$iw$$iw$$iw$$iw$$iw$$iw$$iw$$iw$$iw$$iw$$iw$$iw$$iw$$iw$$iw$$iw$$iw$$iw$$iw$$iw$$iw$$iw$$iw.<init>(command-2904330654045888:42)
	at linea5d1cf79e88c438da37acb40f9dd904e140.$read$$iw$$iw$$iw$$iw$$iw$$iw$$iw$$iw$$iw$$iw$$iw$$iw$$iw$$iw$$iw$$iw$$iw$$iw$$iw$$iw$$iw$$iw$$iw.<init>(command-2904330654045888:135)
	at linea5d1cf79e88c438da37acb40f9dd904e140.$read$$iw$$iw$$iw$$iw$$iw$$iw$$iw$$iw$$iw$$iw$$iw$$iw$$iw$$iw$$iw$$iw$$iw$$iw$$iw$$iw$$iw$$iw.<init>(command-2904330654045888:137)
	at linea5d1cf79e88c438da37acb40f9dd904e140.$read$$iw$$iw$$iw$$iw$$iw$$iw$$iw$$iw$$iw$$iw$$iw$$iw$$iw$$iw$$iw$$iw$$iw$$iw$$iw$$iw$$iw.<init>(command-2904330654045888:139)
	at linea5d1cf79e88c438da37acb40f9dd904e140.$read$$iw$$iw$$iw$$iw$$iw$$iw$$iw$$iw$$iw$$iw$$iw$$iw$$iw$$iw$$iw$$iw$$iw$$iw$$iw$$iw.<init>(command-2904330654045888:141)
	at linea5d1cf79e88c438da37acb40f9dd904e140.$read$$iw$$iw$$iw$$iw$$iw$$iw$$iw$$iw$$iw$$iw$$iw$$iw$$iw$$iw$$iw$$iw$$iw$$iw$$iw.<init>(command-2904330654045888:143)
	at linea5d1cf79e88c438da37acb40f9dd904e140.$read$$iw$$iw$$iw$$iw$$iw$$iw$$iw$$iw$$iw$$iw$$iw$$iw$$iw$$iw$$iw$$iw$$iw$$iw.<init>(command-2904330654045888:145)
	at linea5d1cf79e88c438da37acb40f9dd904e140.$read$$iw$$iw$$iw$$iw$$iw$$iw$$iw$$iw$$iw$$iw$$iw$$iw$$iw$$iw$$iw$$iw$$iw.<init>(command-2904330654045888:147)
	at linea5d1cf79e88c438da37acb40f9dd904e140.$read$$iw$$iw$$iw$$iw$$iw$$iw$$iw$$iw$$iw$$iw$$iw$$iw$$iw$$iw$$iw$$iw.<init>(command-2904330654045888:149)
	at linea5d1cf79e88c438da37acb40f9dd904e140.$read$$iw$$iw$$iw$$iw$$iw$$iw$$iw$$iw$$iw$$iw$$iw$$iw$$iw$$iw$$iw.<init>(command-2904330654045888:151)
	at linea5d1cf79e88c438da37acb40f9dd904e140.$read$$iw$$iw$$iw$$iw$$iw$$iw$$iw$$iw$$iw$$iw$$iw$$iw$$iw$$iw.<init>(command-2904330654045888:153)
	at linea5d1cf79e88c438da37acb40f9dd904e140.$read$$iw$$iw$$iw$$iw$$iw$$iw$$iw$$iw$$iw$$iw$$iw$$iw$$iw.<init>(command-2904330654045888:155)
	at linea5d1cf79e88c438da37acb40f9dd904e140.$read$$iw$$iw$$iw$$iw$$iw$$iw$$iw$$iw$$iw$$iw$$iw$$iw.<init>(command-2904330654045888:157)
	at linea5d1cf79e88c438da37acb40f9dd904e140.$read$$iw$$iw$$iw$$iw$$iw$$iw$$iw$$iw$$iw$$iw$$iw.<init>(command-2904330654045888:159)
	at linea5d1cf79e88c438da37acb40f9dd904e140.$read$$iw$$iw$$iw$$iw$$iw$$iw$$iw$$iw$$iw$$iw.<init>(command-2904330654045888:161)
	at linea5d1cf79e88c438da37acb40f9dd904e140.$read$$iw$$iw$$iw$$iw$$iw$$iw$$iw$$iw$$iw.<init>(command-2904330654045888:163)
	at linea5d1cf79e88c438da37acb40f9dd904e140.$read$$iw$$iw$$iw$$iw$$iw$$iw$$iw$$iw.<init>(command-2904330654045888:165)
	at linea5d1cf79e88c438da37acb40f9dd904e140.$read$$iw$$iw$$iw$$iw$$iw$$iw$$iw.<init>(command-2904330654045888:167)
	at linea5d1cf79e88c438da37acb40f9dd904e140.$read$$iw$$iw$$iw$$iw$$iw$$iw.<init>(command-2904330654045888:169)
	at linea5d1cf79e88c438da37acb40f9dd904e140.$read$$iw$$iw$$iw$$iw$$iw.<init>(command-2904330654045888:171)
	at linea5d1cf79e88c438da37acb40f9dd904e140.$read$$iw$$iw$$iw$$iw.<init>(command-2904330654045888:173)
	at linea5d1cf79e88c438da37acb40f9dd904e140.$read$$iw$$iw$$iw.<init>(command-2904330654045888:175)
	at linea5d1cf79e88c438da37acb40f9dd904e140.$read$$iw$$iw.<init>(command-2904330654045888:177)
	at linea5d1cf79e88c438da37acb40f9dd904e140.$read$$iw.<init>(command-2904330654045888:179)
	at linea5d1cf79e88c438da37acb40f9dd904e140.$read.<init>(command-2904330654045888:181)
	at linea5d1cf79e88c438da37acb40f9dd904e140.$read$.<init>(command-2904330654045888:185)
	at linea5d1cf79e88c438da37acb40f9dd904e140.$read$.<clinit>(command-2904330654045888)
	at linea5d1cf79e88c438da37acb40f9dd904e140.$eval$.$print$lzycompute(<notebook>:7)
	at linea5d1cf79e88c438da37acb40f9dd904e140.$eval$.$print(<notebook>:6)
	at linea5d1cf79e88c438da37acb40f9dd904e140.$eval.$print(<notebook>)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at scala.tools.nsc.interpreter.IMain$ReadEvalPrint.call(IMain.scala:786)
	at scala.tools.nsc.interpreter.IMain$Request.loadAndRun(IMain.scala:1047)
	at scala.tools.nsc.interpreter.IMain$WrappedRequest$$anonfun$loadAndRunReq$1.apply(IMain.scala:638)
	at scala.tools.nsc.interpreter.IMain$WrappedRequest$$anonfun$loadAndRunReq$1.apply(IMain.scala:637)
	at scala.reflect.internal.util.ScalaClassLoader$class.asContext(ScalaClassLoader.scala:31)
	at scala.reflect.internal.util.AbstractFileClassLoader.asContext(AbstractFileClassLoader.scala:19)
	at scala.tools.nsc.interpreter.IMain$WrappedRequest.loadAndRunReq(IMain.scala:637)
	at scala.tools.nsc.interpreter.IMain.interpret(IMain.scala:569)
	at scala.tools.nsc.interpreter.IMain.interpret(IMain.scala:565)
	at com.databricks.backend.daemon.driver.DriverILoop.execute(DriverILoop.scala:199)
	at com.databricks.backend.daemon.driver.ScalaDriverLocal$$anonfun$repl$1.apply$mcV$sp(ScalaDriverLocal.scala:189)
	at com.databricks.backend.daemon.driver.ScalaDriverLocal$$anonfun$repl$1.apply(ScalaDriverLocal.scala:189)
	at com.databricks.backend.daemon.driver.ScalaDriverLocal$$anonfun$repl$1.apply(ScalaDriverLocal.scala:189)
	at com.databricks.backend.daemon.driver.DriverLocal$TrapExitInternal$.trapExit(DriverLocal.scala:587)
	at com.databricks.backend.daemon.driver.DriverLocal$TrapExit$.apply(DriverLocal.scala:542)
	at com.databricks.backend.daemon.driver.ScalaDriverLocal.repl(ScalaDriverLocal.scala:189)
	at com.databricks.backend.daemon.driver.DriverLocal$$anonfun$execute$7.apply(DriverLocal.scala:324)
	at com.databricks.backend.daemon.driver.DriverLocal$$anonfun$execute$7.apply(DriverLocal.scala:304)
	at com.databricks.logging.UsageLogging$$anonfun$withAttributionContext$1.apply(UsageLogging.scala:235)
	at scala.util.DynamicVariable.withValue(DynamicVariable.scala:58)
	at com.databricks.logging.UsageLogging$class.withAttributionContext(UsageLogging.scala:230)
	at com.databricks.backend.daemon.driver.DriverLocal.withAttributionContext(DriverLocal.scala:45)
	at com.databricks.logging.UsageLogging$class.withAttributionTags(UsageLogging.scala:268)
	at com.databricks.backend.daemon.driver.DriverLocal.withAttributionTags(DriverLocal.scala:45)
	at com.databricks.backend.daemon.driver.DriverLocal.execute(DriverLocal.scala:304)
	at com.databricks.backend.daemon.driver.DriverWrapper$$anonfun$tryExecutingCommand$2.apply(DriverWrapper.scala:589)
	at com.databricks.backend.daemon.driver.DriverWrapper$$anonfun$tryExecutingCommand$2.apply(DriverWrapper.scala:589)
	at scala.util.Try$.apply(Try.scala:192)
	at com.databricks.backend.daemon.driver.DriverWrapper.tryExecutingCommand(DriverWrapper.scala:584)
	at com.databricks.backend.daemon.driver.DriverWrapper.getCommandOutputAndError(DriverWrapper.scala:475)
	at com.databricks.backend.daemon.driver.DriverWrapper.executeCommand(DriverWrapper.scala:542)
	at com.databricks.backend.daemon.driver.DriverWrapper.runInnerLoop(DriverWrapper.scala:381)
	at com.databricks.backend.daemon.driver.DriverWrapper.runInner(DriverWrapper.scala:328)
	at com.databricks.backend.daemon.driver.DriverWrapper.run(DriverWrapper.scala:215)
	at java.lang.Thread.run(Thread.java:748)
`

**Comment by trivialfis** [comment]
Okay, I should be careful of what I'm asking.  `reg:squaredlogerror` is only added after 0.90, I guess you are reading the latest doc built from master branch.  Will look into `reg:squarederror`.

**Comment by CodingCat** [comment]
we have a test with this parameter, https://github.com/dmlc/xgboost/blob/2d875ec0197d5a83e7d585daf472b8201aa97c51/jvm-packages/xgboost4j-spark/src/test/scala/ml/dmlc/xgboost4j/scala/spark/XGBoostRegressorSuite.scala

can you double check you are using 0.9?

**Comment by naifmeh** [comment]
@CodingCat 
I just checked and it seems to be the 0.90 that I got from maven. I will try re-executing the code tomorrow after re-uploading the jar as I have no access to it now.

Aren't you able to reproduce the error using the parameter map I provided ?

**Comment by hcho3** [comment]
> Aren't you able to reproduce the error using the parameter map I provided ?

No, we couldn't reproduce. We regularly run tests in XGBoostRegressorSuite:
https://github.com/dmlc/xgboost/blob/abdf894fcf371a1f1cf00eb8425f890e8aee1825/jvm-packages/xgboost4j-spark/src/test/scala/ml/dmlc/xgboost4j/scala/spark/XGBoostRegressorSuite.scala#L85-L91

Try using 1.0.0 from Maven.
