### ISSUE TITLE
Error when using xgb.plot.tree: Assertion failed

### ISSUE THREAD

**Issue by bakaburg1** [dmlc/xgboost#4768]
Hello, 
I wanted to visualize my model trees with:

`xgb.plot.tree(model = mod.y, feature_names = mod.y$feature_names)`

and I got this error in the View pane of RStudio:

```
Assertion failed: font->name, at: textspan.c,206,textspan_size at Error
    at Ga (http://localhost:14267/session/viewhtml18fb3fdf9d10/lib/viz-0.3/viz.js:49:124)
    at Fa (http://localhost:14267/session/viewhtml18fb3fdf9d10/lib/viz-0.3/viz.js:49:22)
    at ___assert_fail (http://localhost:14267/session/viewhtml18fb3fdf9d10/lib/viz-0.3/viz.js:1140:116)
    at $B (http://localhost:14267/session/viewhtml18fb3fdf9d10/lib/viz-0.3/viz.js:1158:126815)
    at vz (http://localhost:14267/session/viewhtml18fb3fdf9d10/lib/viz-0.3/viz.js:1160:88229)
    at mz (http://localhost:14267/session/viewhtml18fb3fdf9d10/lib/viz-0.3/viz.js:1160:83388)
    at nz (http://localhost:14267/session/viewhtml18fb3fdf9d10/lib/viz-0.3/viz.js:1160:84583)
    at EC (http://localhost:14267/session/viewhtml18fb3fdf9d10/lib/viz-0.3/viz.js:1158:136028)
    at Ff (http://localhost:14267/session/viewhtml18fb3fdf9d10/lib/viz-0.3/viz.js:1157:95783)
    at Lf (http://localhost:14267/session/viewhtml18fb3fdf9d10/lib/viz-0.3/viz.js:1157:100587)
```

**Comment by trivialfis** [comment]
Could you provide a reproducible script, also the used XGB version?

**Comment by trivialfis** [comment]
Stalled
