### ISSUE TITLE
[jvm-packages] xgboost4j-spark 0.72: customized objective function "obj_type" error

### ISSUE THREAD

**Issue by David082** [dmlc/xgboost#4809]
Hi, found the same question as
https://github.com/dmlc/xgboost/issues/3620
since xgboost4j-spark 0.8 support customized objective function

it looks like the xgboost4j-spark 0.72 still not support customized objective function

**Comment by David082** [comment]
meet the same error as below
<pre>
java.lang.IllegalArgumentException: requirement failed: parameter "obj_type" is not defined, you have to specify the objective type as classification or regression with a customized objective function
  at scala.Predef$.require(Predef.scala:224)
  at ml.dmlc.xgboost4j.scala.spark.XGBoost$.trainDistributed(XGBoost.scala:311)
  at ml.dmlc.xgboost4j.scala.spark.XGBoostEstimator.train(XGBoostEstimator.scala:139)
  at ml.dmlc.xgboost4j.scala.spark.XGBoostEstimator.train(XGBoostEstimator.scala:36)
  at org.apache.spark.ml.Predictor.fit(Predictor.scala:118)
  at ml.dmlc.xgboost4j.scala.spark.XGBoost$.trainWithDataFrame(XGBoost.scala:193)
  ... 55 elided
</pre>

**Comment by David082** [comment]
@hcho3 Our version of spark is 2.1.0, will cost much to update to 2.3.0, so any possibility to fix the issue in xgboost4j-spark 0.72?
