### ISSUE TITLE
Cannot find XGBoost Library in the candidate path [macOS]

### ISSUE THREAD

**Issue by megancooper** [dmlc/xgboost#4845]
I realize this is a common issue for xgboost installs via pip, but none of the proposed solutions are working for me.

python version `3.6.8`
using conda virtual env

I am trying to install xgboost, and have executed the following commands:
```
brew install gcc@8
pip3 install xgboost
```

this does not work and fails with the following long error output:
(Note, I am aware of issue #4477 and have also tried 
`export CC=/usr/local/bin/gcc-5; export CXX=/usr/local/bin/g++-5; pip3 install xgboost`
which in turn results in the same error)
```
...
    /var/folders/w3/r5y19dyj3tq0zyj3cgrlyrqw0000gn/T//cc0oze7i.s:36442:11: note: change section name to "__const"
            .section __TEXT,__const_coal,coalesced
                     ^      ~~~~~~~~~~~~
    /var/folders/w3/r5y19dyj3tq0zyj3cgrlyrqw0000gn/T//cc0oze7i.s:36448:11: warning: section "__const_coal" is deprecated
            .section __DATA,__const_coal,coalesced
                     ^      ~~~~~~~~~~~~
    /var/folders/w3/r5y19dyj3tq0zyj3cgrlyrqw0000gn/T//cc0oze7i.s:36448:11: note: change section name to "__const"
            .section __DATA,__const_coal,coalesced
                     ^      ~~~~~~~~~~~~
    /var/folders/w3/r5y19dyj3tq0zyj3cgrlyrqw0000gn/T//cc0oze7i.s:36465:11: warning: section "__const_coal" is deprecated
            .section __DATA,__const_coal,coalesced
                     ^      ~~~~~~~~~~~~
    /var/folders/w3/r5y19dyj3tq0zyj3cgrlyrqw0000gn/T//cc0oze7i.s:36465:11: note: change section name to "__const"
            .section __DATA,__const_coal,coalesced
                     ^      ~~~~~~~~~~~~
    g++-5 -DDMLC_LOG_CUSTOMIZE=1 -std=c++11 -Wall -Wno-unknown-pragmas -Iinclude   -Idmlc-core/include -Irabit/include -I/include -O3 -funroll-loops -msse2 -fPIC -DDISABLE_OPENMP -shared -o lib/libxgboost.dylib build/learner.o build/logging.o build/c_api/c_api.o build/c_api/c_api_error.o build/common/common.o build/common/hist_util.o build/common/host_device_vector.o build/data/data.o build/data/simple_csr_source.o build/data/simple_dmatrix.o build/data/sparse_page_dmatrix.o build/data/sparse_page_raw_format.o build/data/sparse_page_source.o build/data/sparse_page_writer.o build/gbm/gblinear.o build/gbm/gbm.o build/gbm/gbtree.o build/linear/linear_updater.o build/linear/updater_coordinate.o build/linear/updater_shotgun.o build/metric/elementwise_metric.o build/metric/metric.o build/metric/multiclass_metric.o build/metric/rank_metric.o build/objective/hinge.o build/objective/multiclass_obj.o build/objective/objective.o build/objective/rank_obj.o build/objective/regression_obj.o build/predictor/cpu_predictor.o build/predictor/predictor.o build/tree/split_evaluator.o build/tree/tree_model.o build/tree/tree_updater.o build/tree/updater_colmaker.o build/tree/updater_histmaker.o build/tree/updater_prune.o build/tree/updater_quantile_hist.o build/tree/updater_refresh.o build/tree/updater_skmaker.o build/tree/updater_sync.o dmlc-core/libdmlc.a rabit/lib/librabit.a -pthread -lm
    ld: warning: ignoring file dmlc-core/libdmlc.a, file was built for archive which is not the architecture being linked (x86_64): dmlc-core/libdmlc.a
    ld: warning: ignoring file rabit/lib/librabit.a, file was built for archive which is not the architecture being linked (x86_64): rabit/lib/librabit.a
    Undefined symbols for architecture x86_64:
      "_RabitLinkTag", referenced from:
          __GLOBAL__sub_I_c_api.cc in c_api.o
      "dmlc::SeekStream::CreateForRead(char const*, bool)", referenced from:
          xgboost::data::SparsePageSource::SparsePageSource(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&) in sparse_page_source.o
      "dmlc::Parser<unsigned int, float>::Create(char const*, unsigned int, unsigned int, char const*)", referenced from:
          xgboost::DMatrix::Load(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, bool, bool, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, unsigned long) in data.o
      "dmlc::Stream::Create(char const*, char const*, bool)", referenced from:
          _XGBoosterLoadModel in c_api.o
          _XGBoosterSaveModel in c_api.o
          _XGBoosterDumpModelEx in c_api.o
          xgboost::DMatrix::Load(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, bool, bool, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, unsigned long) in data.o
          xgboost::DMatrix::SaveToLocalFile(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&) in data.o
          xgboost::MetaTryLoadFloatInfo(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, std::vector<float, std::allocator<float> >*) in data.o
          xgboost::data::SparsePageSource::CacheExist(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&) in sparse_page_source.o
          ...
      "rabit::engine::Allreduce_(void*, unsigned long, unsigned long, void (*)(void const*, void*, int, MPI::Datatype const&), rabit::engine::mpi::DataType, rabit::engine::mpi::OpType, void (*)(void*), void*)", referenced from:
          xgboost::LearnerImpl::LazyInitModel()      in learner.o
          xgboost::DMatrix::Load(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, bool, bool, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, unsigned long) in data.o
          xgboost::metric::EvalEWiseBase<xgboost::metric::EvalRowRMSE>::Eval(xgboost::HostDeviceVector<float> const&, xgboost::MetaInfo const&, bool) in elementwise_metric.o
          xgboost::metric::EvalEWiseBase<xgboost::metric::EvalGammaDeviance>::Eval(xgboost::HostDeviceVector<float> const&, xgboost::MetaInfo const&, bool) in elementwise_metric.o
          xgboost::metric::EvalEWiseBase<xgboost::metric::EvalRowLogLoss>::Eval(xgboost::HostDeviceVector<float> const&, xgboost::MetaInfo const&, bool) in elementwise_metric.o
          xgboost::metric::EvalEWiseBase<xgboost::metric::EvalError>::Eval(xgboost::HostDeviceVector<float> const&, xgboost::MetaInfo const&, bool) in elementwise_metric.o
          xgboost::metric::EvalEWiseBase<xgboost::metric::EvalTweedieNLogLik>::Eval(xgboost::HostDeviceVector<float> const&, xgboost::MetaInfo const&, bool) in elementwise_metric.o
          ...
      "rabit::engine::ReduceHandle::Init(void (*)(void const*, void*, int, MPI::Datatype const&), unsigned long)", referenced from:
          xgboost::common::HistCutMatrix::Init(std::vector<xgboost::common::WXQuantileSketch<float, float>, std::allocator<xgboost::common::WXQuantileSketch<float, float> > >*, unsigned int) in hist_util.o
          xgboost::tree::DistColMaker::Update(xgboost::HostDeviceVector<xgboost::detail::GradientPairInternal<float> >*, xgboost::DMatrix*, std::vector<xgboost::RegTree*, std::allocator<xgboost::RegTree*> > const&) in updater_colmaker.o
          xgboost::tree::CQHistMaker::CQHistMaker() in updater_histmaker.o
          xgboost::tree::QuantileHistMaker::Update(xgboost::HostDeviceVector<xgboost::detail::GradientPairInternal<float> >*, xgboost::DMatrix*, std::vector<xgboost::RegTree*, std::allocator<xgboost::RegTree*> > const&) in updater_quantile_hist.o
          std::_Function_handler<xgboost::TreeUpdater* (), xgboost::tree::{lambda()#1}>::_M_invoke(std::_Any_data const&) in updater_refresh.o
          std::_Function_handler<xgboost::TreeUpdater* (), xgboost::tree::{lambda()#1}>::_M_invoke(std::_Any_data const&) in updater_skmaker.o
      "rabit::engine::ReduceHandle::TypeSize(MPI::Datatype const&)", referenced from:
          void rabit::SerializeReducerFunc_<xgboost::common::QuantileSketchTemplate<float, float, xgboost::common::WXQSummary<float, float> >::SummaryContainer>(void const*, void*, int, MPI::Datatype const&) in hist_util.o
          void rabit::SerializeReducerFunc_<xgboost::common::QuantileSketchTemplate<float, float, xgboost::common::WXQSummary<float, float> >::SummaryContainer>(void const*, void*, int, MPI::Datatype const&) in updater_histmaker.o
          void rabit::SerializeReducerFunc_<xgboost::common::QuantileSketchTemplate<float, float, xgboost::common::WXQSummary<float, float> >::SummaryContainer>(void const*, void*, int, MPI::Datatype const&) in updater_skmaker.o
      "rabit::engine::ReduceHandle::Allreduce(void*, unsigned long, unsigned long, void (*)(void*), void*)", referenced from:
          xgboost::common::HistCutMatrix::Init(std::vector<xgboost::common::WXQuantileSketch<float, float>, std::allocator<xgboost::common::WXQuantileSketch<float, float> > >*, unsigned int) in hist_util.o
          xgboost::tree::DistColMaker::Builder::SyncBestSolution(std::vector<int, std::allocator<int> > const&) in updater_colmaker.o
          xgboost::tree::CQHistMaker::CreateHist(std::vector<xgboost::detail::GradientPairInternal<float>, std::allocator<xgboost::detail::GradientPairInternal<float> > > const&, xgboost::DMatrix*, std::vector<unsigned int, std::allocator<unsigned int> > const&, xgboost::RegTree const&) in updater_histmaker.o
          xgboost::tree::GlobalProposalHistMaker::CreateHist(std::vector<xgboost::detail::GradientPairInternal<float>, std::allocator<xgboost::detail::GradientPairInternal<float> > > const&, xgboost::DMatrix*, std::vector<unsigned int, std::allocator<unsigned int> > const&, xgboost::RegTree const&) in updater_histmaker.o
          xgboost::tree::CQHistMaker::ResetPosAndPropose(std::vector<xgboost::detail::GradientPairInternal<float>, std::allocator<xgboost::detail::GradientPairInternal<float> > > const&, xgboost::DMatrix*, std::vector<unsigned int, std::allocator<unsigned int> > const&, xgboost::RegTree const&) in updater_histmaker.o
          xgboost::tree::QuantileHistMaker::Builder::BuildHist(std::vector<xgboost::detail::GradientPairInternal<float>, std::allocator<xgboost::detail::GradientPairInternal<float> > > const&, xgboost::common::RowSetCollection::Elem, xgboost::common::GHistIndexMatrix const&, xgboost::common::GHistIndexBlockMatrix const&, xgboost::common::Span<xgboost::tree::GradStats, -1ll>, bool) [clone .constprop.1004] in updater_quantile_hist.o
          xgboost::tree::QuantileHistMaker::Builder::SyncHistograms(int, int, xgboost::RegTree*) in updater_quantile_hist.o
          ...
      "rabit::engine::ReduceHandle::ReduceHandle()", referenced from:
          xgboost::common::HistCutMatrix::Init(std::vector<xgboost::common::WXQuantileSketch<float, float>, std::allocator<xgboost::common::WXQuantileSketch<float, float> > >*, unsigned int) in hist_util.o
          xgboost::tree::DistColMaker::Update(xgboost::HostDeviceVector<xgboost::detail::GradientPairInternal<float> >*, xgboost::DMatrix*, std::vector<xgboost::RegTree*, std::allocator<xgboost::RegTree*> > const&) in updater_colmaker.o
          xgboost::tree::CQHistMaker::CQHistMaker() in updater_histmaker.o
          xgboost::tree::QuantileHistMaker::Update(xgboost::HostDeviceVector<xgboost::detail::GradientPairInternal<float> >*, xgboost::DMatrix*, std::vector<xgboost::RegTree*, std::allocator<xgboost::RegTree*> > const&) in updater_quantile_hist.o
          std::_Function_handler<xgboost::TreeUpdater* (), xgboost::tree::{lambda()#1}>::_M_invoke(std::_Any_data const&) in updater_refresh.o
          std::_Function_handler<xgboost::TreeUpdater* (), xgboost::tree::{lambda()#1}>::_M_invoke(std::_Any_data const&) in updater_skmaker.o
      "rabit::engine::ReduceHandle::~ReduceHandle()", referenced from:
          xgboost::common::HistCutMatrix::Init(std::vector<xgboost::common::WXQuantileSketch<float, float>, std::allocator<xgboost::common::WXQuantileSketch<float, float> > >*, unsigned int) in hist_util.o
          xgboost::tree::DistColMaker::Update(xgboost::HostDeviceVector<xgboost::detail::GradientPairInternal<float> >*, xgboost::DMatrix*, std::vector<xgboost::RegTree*, std::allocator<xgboost::RegTree*> > const&) in updater_colmaker.o
          xgboost::tree::CQHistMaker::~CQHistMaker() in updater_histmaker.o
          xgboost::tree::HistMaker::~HistMaker() in updater_histmaker.o
          xgboost::tree::CQHistMaker::CQHistMaker() in updater_histmaker.o
          xgboost::tree::QuantileHistMaker::Update(xgboost::HostDeviceVector<xgboost::detail::GradientPairInternal<float> >*, xgboost::DMatrix*, std::vector<xgboost::RegTree*, std::allocator<xgboost::RegTree*> > const&) in updater_quantile_hist.o
          xgboost::tree::QuantileHistMaker::Builder::~Builder() in updater_quantile_hist.o
          ...
      "rabit::engine::GetEngine()", referenced from:
          xgboost::LearnerImpl::PerformTreeMethodHeuristic(xgboost::DMatrix*) in learner.o
          xgboost::LearnerImpl::BoostOneIter(int, xgboost::DMatrix*, xgboost::HostDeviceVector<xgboost::detail::GradientPairInternal<float> >*) in learner.o
          xgboost::LearnerImpl::Configure(std::vector<std::pair<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > >, std::allocator<std::pair<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > > > > const&) in learner.o
          xgboost::LearnerImpl::UpdateOneIter(int, xgboost::DMatrix*) in learner.o
          xgboost::TrackerLogger::~TrackerLogger() in logging.o
          xgboost::TrackerLogger::~TrackerLogger() in logging.o
          _XGBoosterLoadRabitCheckpoint in c_api.o
          ...
    ld: symbol(s) not found for architecture x86_64
    collect2: error: ld returned 1 exit status
    make: *** [lib/libxgboost.dylib] Error 1
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/private/var/folders/w3/r5y19dyj3tq0zyj3cgrlyrqw0000gn/T/pip-install-wuz52ugm/xgboost/setup.py", line 42, in <module>
        LIB_PATH = libpath['find_lib_path']()
      File "/private/var/folders/w3/r5y19dyj3tq0zyj3cgrlyrqw0000gn/T/pip-install-wuz52ugm/xgboost/xgboost/libpath.py", line 48, in find_lib_path
        'List of candidates:\n' + ('\n'.join(dll_path)))
    XGBoostLibraryNotFound: Cannot find XGBoost Library in the candidate path, did you install compilers and run build.sh in root path?
    List of candidates:
    /private/var/folders/w3/r5y19dyj3tq0zyj3cgrlyrqw0000gn/T/pip-install-wuz52ugm/xgboost/xgboost/libxgboost.dylib
    /private/var/folders/w3/r5y19dyj3tq0zyj3cgrlyrqw0000gn/T/pip-install-wuz52ugm/xgboost/xgboost/../../lib/libxgboost.dylib
    /private/var/folders/w3/r5y19dyj3tq0zyj3cgrlyrqw0000gn/T/pip-install-wuz52ugm/xgboost/xgboost/./lib/libxgboost.dylib
    /usr/local/Cellar/python/3.7.4/Frameworks/Python.framework/Versions/3.7/xgboost/libxgboost.dylib
    ----------------------------------------
ERROR: Command "python setup.py egg_info" failed with error code 1 in /private/var/folders/w3/r5y19dyj3tq0zyj3cgrlyrqw0000gn/T/pip-install-wuz52ugm/xgboost/
```

I have also tried installing via conda and the install works, BUT with this I end up seeing the following error when I run my script and try to import `xgboost`:
```
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/xgboost/__init__.py", line 11, in <module>
    from .core import DMatrix, Booster
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/xgboost/core.py", line 161, in <module>
    _LIB = _load_lib()
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/xgboost/core.py", line 123, in _load_lib
    lib_paths = find_lib_path()
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/xgboost/libpath.py", line 52, in find_lib_path
    'List of candidates:\n' + ('\n'.join(dll_path)))
xgboost.libpath.XGBoostLibraryNotFound: Cannot find XGBoost Library in the candidate path, did you install compilers and run build.sh in root path?
List of candidates:
/Library/Frameworks/Python.framework/Versions/3.6/lib/libxgboost.dylib
```

When I run `gcc -v` I see this:
```
Using built-in specs.
COLLECT_GCC=gcc-8
COLLECT_LTO_WRAPPER=/usr/local/Cellar/gcc@8/8.3.0/libexec/gcc/x86_64-apple-darwin18/8.3.0/lto-wrapper
Target: x86_64-apple-darwin18
Configured with: ../configure --build=x86_64-apple-darwin18 --prefix=/usr/local/Cellar/gcc@8/8.3.0 --libdir=/usr/local/Cellar/gcc@8/8.3.0/lib/gcc/8 --disable-nls --enable-checking=release --enable-languages=c,c++,objc,obj-c++,fortran --program-suffix=-8 --with-gmp=/usr/local/opt/gmp --with-mpfr=/usr/local/opt/mpfr --with-mpc=/usr/local/opt/libmpc --with-isl=/usr/local/opt/isl --with-system-zlib --with-pkgversion='Homebrew GCC 8.3.0' --with-bugurl=https://github.com/Homebrew/homebrew-core/issues --disable-multilib --with-native-system-header-dir=/usr/include --with-sysroot=/Library/Developer/CommandLineTools/SDKs/MacOSX.sdk
Thread model: posix
gcc version 8.3.0 (Homebrew GCC 8.3.0)
```

And `gc++ -v` shows this:
```
Configured with: --prefix=/Applications/Xcode.app/Contents/Developer/usr --with-gxx-include-dir=/usr/include/c++/4.2.1
Apple LLVM version 10.0.0 (clang-1000.11.45.5)
Target: x86_64-apple-darwin18.7.0
Thread model: posix
InstalledDir: /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin
```

Additionally, opened `/Library/Frameworks/Python.framework/Versions/3.6/lib/` and the file
`libxgboost.dylib` was not there. Is this file supposed to be generated when installing this package from pip or pip3?

**Edit: Just noticed this post that talked about apache spark and hadoop impacting this potentially. https://github.com/dmlc/xgboost/issues/3882
I did recently install apache livy and apache spark. Could this be be affecting my installation?**

Thank you for any and all help

**Comment by hcho3** [comment]
Take a look at https://github.com/dmlc/xgboost/issues/4949#issuecomment-542321729 to install XGBoost using Homebrew.
