### ISSUE TITLE
[jvm-package] YARN training throws errors

### ISSUE THREAD

**Issue by thvasilo** [dmlc/xgboost#4890]
I tried compiling XGBoost with S3 support and submitting a job, following the [old guide from 0.72](https://xgboost.readthedocs.io/en/release_0.72/tutorials/aws_yarn.html#).

Tested with 0.72, the job completes as expected. But under  master I'm getting this error:

```
 Log Type: stderr

Log Upload Time: Tue Sep 24 13:50:23 +0000 2019

Log Length: 940

Error: A JNI error has occurred, please check your installation and try again
Exception in thread "main" java.lang.NoClassDefFoundError: org/apache/hadoop/io/DataOutputBuffer
	at java.lang.Class.getDeclaredMethods0(Native Method)
	at java.lang.Class.privateGetDeclaredMethods(Class.java:2701)
	at java.lang.Class.privateGetMethodRecursive(Class.java:3048)
	at java.lang.Class.getMethod0(Class.java:3018)
	at java.lang.Class.getMethod(Class.java:1784)
	at sun.launcher.LauncherHelper.validateMainClass(LauncherHelper.java:544)
	at sun.launcher.LauncherHelper.checkAndLoadMain(LauncherHelper.java:526)
Caused by: java.lang.ClassNotFoundException: org.apache.hadoop.io.DataOutputBuffer
	at java.net.URLClassLoader.findClass(URLClassLoader.java:382)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
	at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:349)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
	... 7 more


Log Type: stdout

Log Upload Time: Tue Sep 24 13:50:23 +0000 2019

Log Length: 0 
```

Has anyone encountered something similar?  Any idea which change since 0.72 would cause something like this? My guess might be something like https://github.com/dmlc/dmlc-core/issues/538.

**Comment by hcho3** [comment]
Closing as stale. Please try the latest version of XGBoost.
