### ISSUE TITLE
[jvm-packages] AssertError:Allreduce: boundary error

### ISSUE THREAD

**Issue by EugeneDeng** [dmlc/xgboost#4981]
I still have the problem of "AssertError:Allreduce: boundary error" with the lastest version 0.90 when i train xgboost model on spark.

SLF4J: Class path contains multiple SLF4J bindings.
SLF4J: Found binding in [jar:file:/data/data10/yarn/nm/filecache/286223/spark_libs.zip/slf4j-log4j12-1.7.16.jar!/org/slf4j/impl/StaticLoggerBinder.class]
SLF4J: Found binding in [jar:file:/opt/cloudera/parcels/CDH-5.14.4-1.cdh5.14.4.p0.3/jars/slf4j-log4j12-1.7.5.jar!/org/slf4j/impl/StaticLoggerBinder.class]
SLF4J: See http://www.slf4j.org/codes.html#multiple_bindings for an explanation.
SLF4J: Actual binding is of type [org.slf4j.impl.Log4jLoggerFactory]
AssertError:Allreduce: boundary error

**Comment by trivialfis** [comment]
Could you provide a reproducible example?  I can't debug it without one.

**Comment by EugeneDeng** [comment]
@trivialfis Do you mean i send the training data to you?

**Comment by EugeneDeng** [comment]
@trivialfis would you please tell me what's the main cause of "boundary error"?  Maybe i can check if something is wrong with my training data.

**Comment by trivialfis** [comment]
@CodingCat @chenqin is the error coming from rabit?

**Comment by EugeneDeng** [comment]
@trivialfis  I think the error do come from rabit. See my logs from the terminal

2019-10-28 14:38:55 INFO  YarnClientSchedulerBackend:54 - Stopped 
2019-10-28 14:38:55 INFO  MapOutputTrackerMasterEndpoint:54 - MapOutputTrackerMasterEndpoint stopped!
2019-10-28 14:38:55 INFO  MemoryStore:54 - MemoryStore cleared 
2019-10-28 14:38:55 INFO  BlockManager:54 - BlockManager stopped 
2019-10-28 14:38:55 INFO  BlockManagerMaster:54 - BlockManagerMaster stopped 
2019-10-28 14:38:55 INFO  OutputCommitCoordinator$OutputCommitCoordinatorEndpoint:54 - OutputCommitCoordinator stopped!
2019-10-28 14:38:55 INFO  SparkContext:54 - Successfully stopped SparkContext
2019-10-28 14:39:00 INFO  RabitTracker$TrackerProcessLogger:61 - Tracker Process ends with exit code 143
2019-10-28 14:39:00 INFO  RabitTracker:196 - Tracker Process ends with exit code 143
2019-10-28 14:39:00 INFO  XGBoostSpark:458 - Rabit returns with exit code 143
Exception in thread "main" ml.dmlc.xgboost4j.java.XGBoostError: XGBoostModel training failed
    at ml.dmlc.xgboost4j.scala.spark.XGBoost$.ml$dmlc$xgboost4j$scala$spark$XGBoost$$postTrackerReturnProcessing(XGBoost.scala:582)
    at ml.dmlc.xgboost4j.scala.spark.XGBoost$$anonfun$trainDistributed$2.apply(XGBoost.scala:459)
    at ml.dmlc.xgboost4j.scala.spark.XGBoost$$anonfun$trainDistributed$2.apply(XGBoost.scala:435)
    at scala.collection.TraversableLike$$anonfun$map$1.apply(TraversableLike.scala:234)
    at scala.collection.TraversableLike$$anonfun$map$1.apply(TraversableLike.scala:234)
    at scala.collection.immutable.List.foreach(List.scala:392)
    at scala.collection.TraversableLike$class.map(TraversableLike.scala:234)
    at scala.collection.immutable.List.map(List.scala:296)
    at ml.dmlc.xgboost4j.scala.spark.XGBoost$.trainDistributed(XGBoost.scala:434)
    at ml.dmlc.xgboost4j.scala.spark.XGBoostClassifier.train(XGBoostClassifier.scala:194)
    at ml.dmlc.xgboost4j.scala.spark.XGBoostClassifier.train(XGBoostClassifier.scala:44)
    at org.apache.spark.ml.Predictor.fit(Predictor.scala:118)
    at com.oppo.video.recommend.spark.XgbTrainer$.training(XgbTrainer.scala:148)
    at com.oppo.video.recommend.spark.XgbTrainer$.main(XgbTrainer.scala:100)
    at com.oppo.video.recommend.spark.XgbTrainer.main(XgbTrainer.scala)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
    at java.lang.reflect.Method.invoke(Method.java:498)
    at org.apache.spark.deploy.JavaMainApplication.start(SparkApplication.scala:52)
    at org.apache.spark.deploy.SparkSubmit.org$apache$spark$deploy$SparkSubmit$$runMain(SparkSubmit.scala:849)
    at org.apache.spark.deploy.SparkSubmit.doRunMain$1(SparkSubmit.scala:167)
    at org.apache.spark.deploy.SparkSubmit.submit(SparkSubmit.scala:195)
    at org.apache.spark.deploy.SparkSubmit.doSubmit(SparkSubmit.scala:86)
    at org.apache.spark.deploy.SparkSubmit$$anon$2.doSubmit(SparkSubmit.scala:924)
    at org.apache.spark.deploy.SparkSubmit$.main(SparkSubmit.scala:933)
    at org.apache.spark.deploy.SparkSubmit.main(SparkSubmit.scala)
2019-10-28 14:39:00 INFO  ShutdownHookManager:54 - Shutdown hook called
2019-10-28 14:39:00 INFO  ShutdownHookManager:54 - Deleting directory /tmp/spark-da45bf9e-b65f-4bd1-9ee1-2dab86ef2d85
2019-10-28 14:39:00 INFO  ShutdownHookManager:54 - Deleting directory /tmp/spark-99cc6c3e-4c08-48bc-a7ce-34cec2db5151

**Comment by EugeneDeng** [comment]
> looks like this is an error from all reduce tree implementation, can we have more info how to repro this error?
> 
> ```
> // read data from parent
>       if (watcher.CheckRead(links[parent_index].sock) &&
>           total_size > size_down_in) {
>         ssize_t len = links[parent_index].sock.
>             Recv(sendrecvbuf + size_down_in, total_size - size_down_in);
>         if (len == 0) {
>           links[parent_index].sock.Close();
>           return ReportError(&links[parent_index], kRecvZeroLen);
>         }
>         if (len != -1) {
>           size_down_in += static_cast<size_t>(len);
>           utils::Assert(size_down_in <= size_up_out,
>                         "Allreduce: boundary error");
>         } else {
>           ReturnType ret = Errno2Return();
>           if (ret != kSuccess) {
>             return ReportError(&links[parent_index], ret);
>           }
>         }
>       }
> ```

This problem is still to be solved. What can cause "Allreduce: boundary error"?
