### ISSUE TITLE
[BUG] Running xgboost (gpu) in a for-loop leads to error

### ISSUE THREAD

**Issue by magehex** [dmlc/xgboost#5026]
**I want to run a solver in a for-loop and got following error:**

```
Traceback (most recent call last):
  File "<input>", line 13, in <module>
  File "/home/magehex/anaconda3/envs/reinbo/lib/python3.7/site-packages/xgboost/sklearn.py", line 687, in fit
    callbacks=callbacks)
  File "/home/magehex/anaconda3/envs/reinbo/lib/python3.7/site-packages/xgboost/training.py", line 219, in train
    xgb_model=xgb_model, callbacks=callbacks)
  File "/home/magehex/anaconda3/envs/reinbo/lib/python3.7/site-packages/xgboost/training.py", line 74, in _train_internal
    bst.update(dtrain, i, obj)
  File "/home/magehex/anaconda3/envs/reinbo/lib/python3.7/site-packages/xgboost/core.py", line 1240, in update
    dtrain.handle))
  File "/home/magehex/anaconda3/envs/reinbo/lib/python3.7/site-packages/xgboost/core.py", line 202, in _check_call
    raise XGBoostError(py_str(_LIB.XGBGetLastError()))
xgboost.core.XGBoostError: [18:41:03] /workspace/src/tree/updater_gpu_hist.cu:1004: Exception in gpu_hist: parallel_for failed: out of memory
Stack trace:
  [bt] (0) /home/magehex/anaconda3/envs/reinbo/xgboost/libxgboost.so(dmlc::LogMessageFatal::~LogMessageFatal()+0x24) [0x7fb248a64684]
  [bt] (1) /home/magehex/anaconda3/envs/reinbo/xgboost/libxgboost.so(xgboost::tree::GPUHistMakerSpecialised<xgboost::detail::GradientPairInternal<double> >::Update(xgboost::HostDeviceVector<xgboost::detail::GradientPairInternal<float> >*, xgboost::DMatrix*, std::vector<xgboost::RegTree*, std::allocator<xgboost::RegTree*> > const&)+0x47f) [0x7fb248cfd8cf]
  [bt] (2) /home/magehex/anaconda3/envs/reinbo/xgboost/libxgboost.so(xgboost::gbm::GBTree::BoostNewTrees(xgboost::HostDeviceVector<xgboost::detail::GradientPairInternal<float> >*, xgboost::DMatrix*, int, std::vector<std::unique_ptr<xgboost::RegTree, std::default_delete<xgboost::RegTree> >, std::allocator<std::unique_ptr<xgboost::RegTree, std::default_delete<xgboost::RegTree> > > >*)+0x9ae) [0x7fb248b04dae]
  [bt] (3) /home/magehex/anaconda3/envs/reinbo/xgboost/libxgboost.so(xgboost::gbm::GBTree::DoBoost(xgboost::DMatrix*, xgboost::HostDeviceVector<xgboost::detail::GradientPairInternal<float> >*, xgboost::ObjFunction*)+0x9ae) [0x7fb248b06bfe]
  [bt] (4) /home/magehex/anaconda3/envs/reinbo/xgboost/libxgboost.so(xgboost::LearnerImpl::UpdateOneIter(int, xgboost::DMatrix*)+0x379) [0x7fb248b26859]
  [bt] (5) /home/magehex/anaconda3/envs/reinbo/xgboost/libxgboost.so(XGBoosterUpdateOneIter+0x29) [0x7fb248a554d9]
  [bt] (6) /home/magehex/anaconda3/envs/reinbo/lib/python3.7/lib-dynload/../../libffi.so.6(ffi_call_unix64+0x4c) [0x7fb2e380aec0]
  [bt] (7) /home/magehex/anaconda3/envs/reinbo/lib/python3.7/lib-dynload/../../libffi.so.6(ffi_call+0x22d) [0x7fb2e380a87d]
  [bt] (8) /home/magehex/anaconda3/envs/reinbo/lib/python3.7/lib-dynload/_ctypes.cpython-37m-x86_64-linux-gnu.so(_ctypes_callproc+0x2ce) [0x7fb2e3a2001e]
```

**Steps/Code to reproduce bug**

```
import numpy as np
from sklearn.datasets.samples_generator import make_blobs
from xgboost import XGBClassifier


X, y = make_blobs(n_samples=1000, centers=2, n_features=380)
X = X.astype(np.float32)
y = y.astype(np.int32)

clf = XGBClassifier(tree_method='gpu_hist')

for i in range(1,1000):
    clf.fit(X,y)
```

**Environment details (please complete the following information):**

- Environment location: [Desktop PC]
- Linux Distro/Architecture: [ubuntu 18.04 amd64]
- GPU Model/Driver: [Quadro P600 and driver 418.87.01]
- CUDA: [10.1]

**Comment by trivialfis** [comment]
See https://github.com/dmlc/xgboost/issues/5029
