### ISSUE TITLE
[BUG] Using cros_val_score and xgboost gpu together leads to error

### ISSUE THREAD

**Issue by magehex** [dmlc/xgboost#5029]
I want to use cross_val_score from sklearn-package and xgboost with gpu support.

```
import numpy as np
from xgboost.sklearn import XGBClassifier
from sklearn.datasets.samples_generator import make_blobs
from sklearn.model_selection import cross_val_score


X, y = make_blobs(n_samples=100000, centers=2, n_features=380)
X = X.astype(np.float32)
y = y.astype(np.int32)

clf = XGBClassifier(tree_method='gpu_hist')

clf.fit(X,y)
cross_val_score(clf, X,y, cv=5, scoring='accuracy')
```

Then the following error appears

```
/home/magehex/anaconda3/envs/rb/lib/python3.7/site-packages/sklearn/model_selection/_validation.py:530: FutureWarning: From version 0.22, errors during fit will result in a cross validation score of NaN by default. Use error_score='raise' if you want an exception raised or error_score=np.nan to adopt the behavior from version 0.22.
  FutureWarning)
Traceback (most recent call last):
  File "<input>", line 14, in <module>
  File "/home/magehex/anaconda3/envs/rb/lib/python3.7/site-packages/sklearn/model_selection/_validation.py", line 391, in cross_val_score
    error_score=error_score)
  File "/home/magehex/anaconda3/envs/rb/lib/python3.7/site-packages/sklearn/model_selection/_validation.py", line 232, in cross_validate
    for train, test in cv.split(X, y, groups))
  File "/home/magehex/anaconda3/envs/rb/lib/python3.7/site-packages/joblib/parallel.py", line 1003, in __call__
    if self.dispatch_one_batch(iterator):
  File "/home/magehex/anaconda3/envs/rb/lib/python3.7/site-packages/joblib/parallel.py", line 834, in dispatch_one_batch
    self._dispatch(tasks)
  File "/home/magehex/anaconda3/envs/rb/lib/python3.7/site-packages/joblib/parallel.py", line 753, in _dispatch
    job = self._backend.apply_async(batch, callback=cb)
  File "/home/magehex/anaconda3/envs/rb/lib/python3.7/site-packages/joblib/_parallel_backends.py", line 201, in apply_async
    result = ImmediateResult(func)
  File "/home/magehex/anaconda3/envs/rb/lib/python3.7/site-packages/joblib/_parallel_backends.py", line 582, in __init__
    self.results = batch()
  File "/home/magehex/anaconda3/envs/rb/lib/python3.7/site-packages/joblib/parallel.py", line 256, in __call__
    for func, args, kwargs in self.items]
  File "/home/magehex/anaconda3/envs/rb/lib/python3.7/site-packages/joblib/parallel.py", line 256, in <listcomp>
    for func, args, kwargs in self.items]
  File "/home/magehex/anaconda3/envs/rb/lib/python3.7/site-packages/sklearn/model_selection/_validation.py", line 516, in _fit_and_score
    estimator.fit(X_train, y_train, **fit_params)
  File "/home/magehex/anaconda3/envs/rb/lib/python3.7/site-packages/xgboost/sklearn.py", line 687, in fit
    callbacks=callbacks)
  File "/home/magehex/anaconda3/envs/rb/lib/python3.7/site-packages/xgboost/training.py", line 219, in train
    xgb_model=xgb_model, callbacks=callbacks)
  File "/home/magehex/anaconda3/envs/rb/lib/python3.7/site-packages/xgboost/training.py", line 74, in _train_internal
    bst.update(dtrain, i, obj)
  File "/home/magehex/anaconda3/envs/rb/lib/python3.7/site-packages/xgboost/core.py", line 1240, in update
    dtrain.handle))
  File "/home/magehex/anaconda3/envs/rb/lib/python3.7/site-packages/xgboost/core.py", line 202, in _check_call
    raise XGBoostError(py_str(_LIB.XGBGetLastError()))
xgboost.core.XGBoostError: [18:02:15] /workspace/src/tree/updater_gpu_hist.cu:1004: Exception in gpu_hist: parallel_for failed: out of memory
Stack trace:
  [bt] (0) /home/magehex/anaconda3/envs/rb/xgboost/libxgboost.so(dmlc::LogMessageFatal::~LogMessageFatal()+0x24) [0x7fbaee152684]
  [bt] (1) /home/magehex/anaconda3/envs/rb/xgboost/libxgboost.so(xgboost::tree::GPUHistMakerSpecialised<xgboost::detail::GradientPairInternal<double> >::Update(xgboost::HostDeviceVector<xgboost::detail::GradientPairInternal<float> >*, xgboost::DMatrix*, std::vector<xgboost::RegTree*, std::allocator<xgboost::RegTree*> > const&)+0x47f) [0x7fbaee3eb8cf]
  [bt] (2) /home/magehex/anaconda3/envs/rb/xgboost/libxgboost.so(xgboost::gbm::GBTree::BoostNewTrees(xgboost::HostDeviceVector<xgboost::detail::GradientPairInternal<float> >*, xgboost::DMatrix*, int, std::vector<std::unique_ptr<xgboost::RegTree, std::default_delete<xgboost::RegTree> >, std::allocator<std::unique_ptr<xgboost::RegTree, std::default_delete<xgboost::RegTree> > > >*)+0x9ae) [0x7fbaee1f2dae]
  [bt] (3) /home/magehex/anaconda3/envs/rb/xgboost/libxgboost.so(xgboost::gbm::GBTree::DoBoost(xgboost::DMatrix*, xgboost::HostDeviceVector<xgboost::detail::GradientPairInternal<float> >*, xgboost::ObjFunction*)+0x9ae) [0x7fbaee1f4bfe]
  [bt] (4) /home/magehex/anaconda3/envs/rb/xgboost/libxgboost.so(xgboost::LearnerImpl::UpdateOneIter(int, xgboost::DMatrix*)+0x379) [0x7fbaee214859]
  [bt] (5) /home/magehex/anaconda3/envs/rb/xgboost/libxgboost.so(XGBoosterUpdateOneIter+0x29) [0x7fbaee1434d9]
  [bt] (6) /home/magehex/anaconda3/envs/rb/lib/python3.7/lib-dynload/../../libffi.so.6(ffi_call_unix64+0x4c) [0x7fbb88e53ec0]
  [bt] (7) /home/magehex/anaconda3/envs/rb/lib/python3.7/lib-dynload/../../libffi.so.6(ffi_call+0x22d) [0x7fbb88e5387d]
  [bt] (8) /home/magehex/anaconda3/envs/rb/lib/python3.7/lib-dynload/_ctypes.cpython-37m-x86_64-linux-gnu.so(_ctypes_callproc+0x2ce) [0x7fbb8906901e]
```

**Comment by trivialfis** [comment]
This one is a little bit tricky, see: https://github.com/dmlc/xgboost/issues/4843

**Comment by trivialfis** [comment]
The DMatrix object can now be freed up without first deleting the booster, this should be mitigated.  Closing.
