### ISSUE TITLE
[JVM-Package] Spark/scala survival:cox IllegalArgumentException

### ISSUE THREAD

**Issue by ssoftcheck** [dmlc/xgboost#5054]
When I try to create a XGBoostRegressor with cox objective I get this error, is surviva:cox not supported in the spark version?

val booster = new XGBoostRegressor(Map("objective" -> "survival:cox"))

Name: java.lang.IllegalArgumentException
Message: xgbr_04b4815c0b8f parameter objective given invalid value survival:cox.
StackTrace:   at org.apache.spark.ml.param.Param.validate(params.scala:77)
  at org.apache.spark.ml.param.ParamPair.<init>(params.scala:656)
  at org.apache.spark.ml.param.Param.$minus$greater(params.scala:87)
  at org.apache.spark.ml.param.Params$class.set(params.scala:737)
  at org.apache.spark.ml.PipelineStage.set(Pipeline.scala:42)
  at org.apache.spark.ml.param.Params$class.set(params.scala:744)
  at org.apache.spark.ml.PipelineStage.set(Pipeline.scala:42)
  at ml.dmlc.xgboost4j.scala.spark.params.ParamMapFuncs$$anonfun$XGBoostToMLlibParams$2.apply(GeneralParams.scala:265)
  at ml.dmlc.xgboost4j.scala.spark.params.ParamMapFuncs$$anonfun$XGBoostToMLlibParams$2.apply(GeneralParams.scala:245)
  at scala.collection.TraversableLike$WithFilter$$anonfun$foreach$1.apply(TraversableLike.scala:733)
  at scala.collection.immutable.Map$Map1.foreach(Map.scala:116)
  at scala.collection.TraversableLike$WithFilter.foreach(TraversableLike.scala:732)
  at ml.dmlc.xgboost4j.scala.spark.params.ParamMapFuncs$class.XGBoostToMLlibParams(GeneralParams.scala:245)
  at ml.dmlc.xgboost4j.scala.spark.XGBoostRegressor.XGBoostToMLlibParams(XGBoostRegressor.scala:48)
  at ml.dmlc.xgboost4j.scala.spark.XGBoostRegressor.<init>(XGBoostRegressor.scala:61)
  at ml.dmlc.xgboost4j.scala.spark.XGBoostRegressor.<init>(XGBoostRegressor.scala:58)

**Comment by shreyashankar** [comment]
I also have this issue: `SparkStatementException: java.lang.IllegalArgumentException: xgbr_3bdc3f1bb5cf parameter objective given invalid value survival:cox`

**Comment by ssoftcheck** [comment]
Hey I think this may be the solution,
Try editing LearningTaskParams.scala
And add "survival:cox" to supportedObjective and "cox-nloglik" to supportedEvalMetrics

Then rebuild the jar

**Comment by hcho3** [comment]
As of #4560, we expose all objectives to the Spark layer.
