### ISSUE TITLE
Extending XGBClassifier with **kwargs gives error about missing parameters

### ISSUE THREAD

**Issue by mglowacki100** [dmlc/xgboost#5100]
Hi,
I've tried to extend XGBClassifier with code as below. 
Basically, it adds handling feature names when data is pandas dataframe and fix issues with child class signature. There is a problem with `__init__`, mix-ins are not important. 
Analogous code for e.g. LogisticRegression from scikit works fine.
```
import copy
import pandas as pd
import xgboost as xgb


#mix-ins: 
class FeatureNames(object):
    def get_feature_names(self):
        if not isinstance(self.feature_names, list):
            raise ValueError('Must fit data first!')
        else:
            return self.feature_names


class FeatureImportances(object):
    def get_feature_importances(self):
        return dict(zip(self.get_feature_names(), self.feature_importances_))

        
class XGBClassifierN(FeatureImportances, FeatureNames, xgb.XGBClassifier):
    def __init__(self, **kwargs): 
        super().__init__(**kwargs)
        self.feature_names = None
   
    #hack from https://stackoverflow.com/questions/51430484/how-to-subclass-a-vectorizer-in-scikit-learn-without-repeating-all-parameters-in
    def get_params(self, deep=True):
        params = super().get_params(deep)
        cp = copy.copy(self)
        cp.__class__ = xgb.XGBClassifier
        params.update(cp.__class__.get_params(cp, deep))
        return params

    def fit(self, X, y=None):
        self.feature_names = list(X.columns)
        return super().fit(X, y)


XGBClassifierN()
print(XGBClassifierN())
```
Error message:
```
runfile('/home/mglowacki/Desktop/xg_example.py', wdir='/home/mglowacki/Desktop')
Traceback (most recent call last):

  File "<ipython-input-1-693451a0d6aa>", line 1, in <module>
    runfile('/home/mglowacki/Desktop/xg_example.py', wdir='/home/mglowacki/Desktop')

  File "/home/mglowacki/anaconda3/envs/py37/lib/python3.7/site-packages/spyder_kernels/customize/spydercustomize.py", line 827, in runfile
    execfile(filename, namespace)

  File "/home/mglowacki/anaconda3/envs/py37/lib/python3.7/site-packages/spyder_kernels/customize/spydercustomize.py", line 110, in execfile
    exec(compile(f.read(), filename, 'exec'), namespace)

  File "/home/mglowacki/Desktop/xg_example.py", line 48, in <module>
    print(XGBClassifierN())

  File "/home/mglowacki/anaconda3/envs/py37/lib/python3.7/site-packages/sklearn/base.py", line 251, in __repr__
    repr_ = pp.pformat(self)

  File "/home/mglowacki/anaconda3/envs/py37/lib/python3.7/pprint.py", line 144, in pformat
    self._format(object, sio, 0, 0, {}, 0)

  File "/home/mglowacki/anaconda3/envs/py37/lib/python3.7/pprint.py", line 161, in _format
    rep = self._repr(object, context, level)

  File "/home/mglowacki/anaconda3/envs/py37/lib/python3.7/pprint.py", line 393, in _repr
    self._depth, level)

  File "/home/mglowacki/anaconda3/envs/py37/lib/python3.7/site-packages/sklearn/utils/_pprint.py", line 170, in format
    changed_only=self._changed_only)

  File "/home/mglowacki/anaconda3/envs/py37/lib/python3.7/site-packages/sklearn/utils/_pprint.py", line 415, in _safe_repr
    params = object.get_params(deep=False)

  File "/home/mglowacki/Desktop/xg_example.py", line 36, in get_params
    params = super().get_params(deep)

  File "/home/mglowacki/anaconda3/envs/py37/lib/python3.7/site-packages/xgboost/sklearn.py", line 222, in get_params
    if params['missing'] is np.nan: #MG

KeyError: 'missing'
```
I've looked into source of `sklearn.py` and commenting-out two lines with `if params['missi...` seems to solve issue, even if there is NaN in the data. Below is monkey-patch quick-fix for this:
```
### https://github.com/dmlc/xgboost/blob/master/python-package/xgboost/sklearn.py line 222
def get_params(self, deep=False): 
    """Get parameters."""
    params = super(xgb.XGBModel, self).get_params(deep=deep)
    if isinstance(self.kwargs, dict):  # if kwargs is a dict, update params accordingly
        params.update(self.kwargs)
#MG if params['missing'] is np.nan:
#MG     params['missing'] = None  # sklearn doesn't handle nan. see #4725
    if not params.get('eval_metric', True):
        del params['eval_metric']  # don't give as None param to Booster
    return params
xgb.XGBModel.get_params = get_params
```
Here is direct link for issue 4725: https://github.com/scikit-learn/scikit-learn/pull/4725
I'm not sure if my fix is correct.

**Comment by trivialfis** [comment]
@mglowacki100 sklearn uses `inspect.signature` to find all parameters of `__init__` function,   in your case it's empty (well there is a **kwargs but it doesn't count).

**Comment by mglowacki100** [comment]
@trivialfis I'm not sure if I stated my issue clearly enough. Yes, in general this construction with `**kwargs` remove signature, but with 
```
    #hack from https://stackoverflow.com/questions/51430484/how-to-subclass-a-vectorizer-in-scikit-learn-without-repeating-all-parameters-in
    def get_params(self, deep=True):
        params = super().get_params(deep)
        cp = copy.copy(self)
        cp.__class__ = xgb.XGBClassifier
        params.update(cp.__class__.get_params(cp, deep))
        return params
```
I can get it back:
```
In [2]: XGBClassifierN()
Out[2]: 
XGBClassifierN(base_score=0.5, booster='gbtree', colsample_bylevel=1,
               colsample_bynode=1, colsample_bytree=1, gamma=0,
               learning_rate=0.1, max_delta_step=0, max_depth=3,
               min_child_weight=1, missing=nan, n_estimators=100, n_jobs=1,
               nthread=None, objective='binary:logistic', random_state=0,
               reg_alpha=0, reg_lambda=1, scale_pos_weight=1, seed=None,
               silent=None, subsample=1, verbosity=1)
```

The only problem is with two lines in `get_params` from original XGBClassifier. Removing: 
```
if params['missing'] is np.nan:
     params['missing'] = None
``` 
fix it.

Full code:
```
import copy
import pandas as pd
import xgboost as xgb


############patching of xgboost
### https://github.com/dmlc/xgboost/blob/master/python-package/xgboost/sklearn.py line 222
def get_params(self, deep=False): 
    """Get parameters."""
    params = super(xgb.XGBModel, self).get_params(deep=deep)
    if isinstance(self.kwargs, dict):  # if kwargs is a dict, update params accordingly
        params.update(self.kwargs)
#MG if params['missing'] is np.nan:
#MG     params['missing'] = None  # sklearn doesn't handle nan. see #4725
    if not params.get('eval_metric', True):
        del params['eval_metric']  # don't give as None param to Booster
    return params
xgb.XGBModel.get_params = get_params
############        


#mix-ins: 
class FeatureNames(object):
    def get_feature_names(self):
        if not isinstance(self.feature_names, list):
            raise ValueError('Must fit data first!')
        else:
            return self.feature_names


class FeatureImportances(object):
    def get_feature_importances(self):
        return dict(zip(self.get_feature_names(), self.feature_importances_))

        
class XGBClassifierN(FeatureImportances, FeatureNames, xgb.XGBClassifier):
    def __init__(self, **kwargs): 
        super().__init__(**kwargs)
        self.feature_names = None
   
    #hack from https://stackoverflow.com/questions/51430484/how-to-subclass-a-vectorizer-in-scikit-learn-without-repeating-all-parameters-in
    def get_params(self, deep=True):
        params = super().get_params(deep)
        cp = copy.copy(self)
        cp.__class__ = xgb.XGBClassifier
        params.update(cp.__class__.get_params(cp, deep))
        return params

    def fit(self, X, y=None):
        self.feature_names = list(X.columns)
        return super().fit(X, y)


XGBClassifierN()
print(XGBClassifierN().get_params())
```

**Comment by trivialfis** [comment]
Okay, the `get_params` in XGBoost doesn't have this workaround and it assumes there's always a valid dictionary from SKL.  Let me revise that.

**Comment by mglowacki100** [comment]
I've looked at `sklearn.py` and made changes that seems to work on my local machine, but I don't know if it is consistent with library approach and correct for all cases: 
https://gist.github.com/mglowacki100/d24ac8c853be4e1d359cfdf71b2fc526
A few remarks:
- less repetition in `__init__` but `get_params` works
- in original default for `n_jobs` in `XGBRanker` is -1 (accidental inconsistency?)
- `XGBRegressor` has its own `__init__`
- I've commented out `get_params` in `XGBModel`
- I moved up `gpu_id` to the `XGBModel`
- I've changed order in inheritance in `XGBClassifier` and `XGBRegressor`
- I set default `objective` in `XGBModel` to `None`

**Comment by trivialfis** [comment]
@mglowacki100 Could you please open a PR?  We have full set of tests there, also we can see the diff more clearly.  One minor thing, is "GetParamsFixIn" actually "GetParamsMixIn"? https://gist.github.com/mglowacki100/d24ac8c853be4e1d359cfdf71b2fc526#file-sklearn-py-L54

**Comment by mglowacki100** [comment]
@trivialfis I've changed to `GetParamsMixIn`. `FixIn` is just my name when `MixIn` fix something.

**Comment by trivialfis** [comment]
PR is merged.
