### ISSUE TITLE
xgboost hangs on the second execution

### ISSUE THREAD

**Issue by virilo** [dmlc/xgboost#512]
Hi,

I'm using xgboost with python 3.4, on ubuntu server 14.4 64-bits.

Last saturday, (september the 19th) I downloaded the trunk and compiled the code following your instructions.

After using GridSearchCV to fit, It is necessary to open a new ipython console.
Otherwise, it hangs on the second execution (even if I run again the same code).
It's a problem because I call twice to GridSearchCV

This is my dataset:

```
ipdb> X_train.__class__.__name__
'ndarray'

ipdb> X_train.shape
(18127, 106)

ipdb> y_train.__class__.__name__
'ndarray'

ipdb> y_train.shape
(18127,)
```

And this is my code:

```
my_model = xgb.XGBRegressor()
# Create the pipeline  
clf = Pipeline([('mym', my_model)])

param_grid = {'mym__objective': ['reg:linear'], 
          'mym__min_child_weight': [6], 
          'mym__subsample': [0.7], 
          'mym__colsample_bytree': [0.6], 
          'mym__silent': [1], 
          'mym__max_depth': [8], 
          'mym__learning_rate': [0.05], 
          'mym__max_delta_step' : [2], 
          'mym__n_estimators': [200]}

model = GridSearchCV(clf, param_grid, n_jobs=-1, scoring=custom_scorer, cv=2) 

model.fit(X_train, y_train)
```

The first time I execute the code, it runs ok, using all the cpus (I see it with top command)

The next time, it hangs on model.fit call.  It seems to be using just one CPU at 2%.  But I can see a lot of python processes with ps command
I did a thread dump to see that it was hanged on xgboost update function.  On core.py line 78: _check_call(_LIB.XGBoosterUpdateOneIter(self.handle, iteration, dtrain.handle))

Thread dump is attached.

Thanks a lot for your help and your xgboost!

Best regards

```
Current thread 0x00006e6673aa1740 (most recent call first):
  File "/home/test/anaconda3/lib/python3.4/site-packages/xgboost-0.4-py3.4.egg/xgboost/core.py", line 578 in update
  File "/home/test/anaconda3/lib/python3.4/site-packages/xgboost-0.4-py3.4.egg/xgboost/training.py", line 62 in train
  File "/home/test/anaconda3/lib/python3.4/site-packages/xgboost-0.4-py3.4.egg/xgboost/sklearn.py", line 189 in fit
  File "/home/test/anaconda3/lib/python3.4/site-packages/sklearn/pipeline.py", line 141 in fit
  File "/home/test/anaconda3/lib/python3.4/site-packages/sklearn/cross_validation.py", line 1459 in _fit_and_score
  File "/home/test/anaconda3/lib/python3.4/site-packages/sklearn/externals/joblib/parallel.py", line 94 in __call__
  File "/home/test/anaconda3/lib/python3.4/multiprocessing/pool.py", line 119 in worker
  File "/home/test/anaconda3/lib/python3.4/multiprocessing/process.py", line 93 in run
  File "/home/test/anaconda3/lib/python3.4/multiprocessing/process.py", line 254 in _bootstrap
  File "/home/test/anaconda3/lib/python3.4/multiprocessing/popen_fork.py", line 77 in _launch
  File "/home/test/anaconda3/lib/python3.4/multiprocessing/popen_fork.py", line 21 in __init__
  File "/home/test/anaconda3/lib/python3.4/multiprocessing/context.py", line 267 in _Popen
  File "/home/test/anaconda3/lib/python3.4/multiprocessing/process.py", line 105 in start
  File "/home/test/anaconda3/lib/python3.4/multiprocessing/pool.py", line 233 in _repopulate_pool
  File "/home/test/anaconda3/lib/python3.4/multiprocessing/pool.py", line 168 in __init__
  File "/home/test/anaconda3/lib/python3.4/site-packages/sklearn/externals/joblib/pool.py", line 422 in __init__
  File "/home/test/anaconda3/lib/python3.4/site-packages/sklearn/externals/joblib/pool.py", line 583 in __init__
  File "/home/test/anaconda3/lib/python3.4/site-packages/sklearn/externals/joblib/parallel.py", line 619 in __call__
  File "/home/test/anaconda3/lib/python3.4/site-packages/sklearn/grid_search.py", line 505 in _fit
  File "/home/test/anaconda3/lib/python3.4/site-packages/sklearn/grid_search.py", line 732 in fit
  File "/home/test/src_v1_11/my_MAIN.py", line 469
```

**Comment by ClimbsRocks** [comment]
I'm running into this exact same issue! Did you find any solutions @virilo ?

I think for me it's related to how XGBoost interacts with scikit-learn, and specifically how they handle multi-threading. 

When I try to Ctrl+C out of the hung program, here's what I run into: 

```
^C^C^CProcess PoolWorker-208:
Process PoolWorker-207:
Process PoolWorker-206:
Process PoolWorker-205:
Traceback (most recent call last):
Traceback (most recent call last):
Traceback (most recent call last):
  File "/usr/local/Cellar/python/2.7.12/Frameworks/Python.framework/Versions/2.7/lib/python2.7/multiprocessing/process.py", line 258, in _bootstrap
Traceback (most recent call last):
  File "/usr/local/Cellar/python/2.7.12/Frameworks/Python.framework/Versions/2.7/lib/python2.7/multiprocessing/process.py", line 258, in _bootstrap
  File "/usr/local/Cellar/python/2.7.12/Frameworks/Python.framework/Versions/2.7/lib/python2.7/multiprocessing/process.py", line 258, in _bootstrap
  File "/usr/local/Cellar/python/2.7.12/Frameworks/Python.framework/Versions/2.7/lib/python2.7/multiprocessing/process.py", line 258, in _bootstrap
    self.run()
    self.run()
  File "/usr/local/Cellar/python/2.7.12/Frameworks/Python.framework/Versions/2.7/lib/python2.7/multiprocessing/process.py", line 114, in run
    self.run()
  File "/usr/local/Cellar/python/2.7.12/Frameworks/Python.framework/Versions/2.7/lib/python2.7/multiprocessing/process.py", line 114, in run
    self._target(*self._args, **self._kwargs)
  File "/usr/local/Cellar/python/2.7.12/Frameworks/Python.framework/Versions/2.7/lib/python2.7/multiprocessing/pool.py", line 102, in worker
  File "/usr/local/Cellar/python/2.7.12/Frameworks/Python.framework/Versions/2.7/lib/python2.7/multiprocessing/process.py", line 114, in run
    self.run()
    self._target(*self._args, **self._kwargs)
    self._target(*self._args, **self._kwargs)
  File "/usr/local/Cellar/python/2.7.12/Frameworks/Python.framework/Versions/2.7/lib/python2.7/multiprocessing/pool.py", line 102, in worker
  File "/usr/local/Cellar/python/2.7.12/Frameworks/Python.framework/Versions/2.7/lib/python2.7/multiprocessing/pool.py", line 102, in worker
  File "/usr/local/Cellar/python/2.7.12/Frameworks/Python.framework/Versions/2.7/lib/python2.7/multiprocessing/process.py", line 114, in run
    self._target(*self._args, **self._kwargs)
  File "/usr/local/Cellar/python/2.7.12/Frameworks/Python.framework/Versions/2.7/lib/python2.7/multiprocessing/pool.py", line 102, in worker
    task = get()
  File "/usr/local/lib/python2.7/site-packages/sklearn/externals/joblib/pool.py", line 359, in get
    task = get()
    task = get()
    task = get()
  File "/usr/local/lib/python2.7/site-packages/sklearn/externals/joblib/pool.py", line 357, in get
  File "/usr/local/lib/python2.7/site-packages/sklearn/externals/joblib/pool.py", line 357, in get
  File "/usr/local/lib/python2.7/site-packages/sklearn/externals/joblib/pool.py", line 357, in get
    racquire()
    return recv()
    racquire()
KeyboardInterrupt
KeyboardInterrupt
KeyboardInterrupt
    racquire()
KeyboardInterrupt

```

That series of shell logs keeps going indefinitely, as far as I can tell, as long as I hold Ctrl+C.

**Comment by raquelhr** [comment]
Hello, 

I ran into this issue a couple of days ago and think this is probably somewhat related to #6627. The problem seems to be persistent only for xgboost (I tried a collection of different models in the same grid search and all worked fine except when it was xgboost’s turn). 

After removing the positional argument ’n_jobs’, my code now runs smoothly. You can still use ’n_jobs’ for other models, so it might be worth to specify a rule that removes n_jobs whenever the model is of xgboost-type.

I suspect this is owing to some kind of inconsistency between n_jobs (parameter of grid-search) and nthread (hyper-parameter of xgboost initialiser), as  @lesteve suggested in the post mentioned above, but it would be great if someone could share the specific details on this issue. 

I hope this helps!

**Comment by lesteve** [comment]
@raquelhr you probably want to edit your message to link to the scikit-learn issue: https://github.com/scikit-learn/scikit-learn/issues/6627. I'll be happy to remove mine afterwards.

**Comment by lesteve** [comment]
I think the relevant comment in the issue is actually:
https://github.com/scikit-learn/scikit-learn/issues/6627#issuecomment-206280089

For Python 3 users, it would be great if they could try to set the joblib start method to forkserver to see whether that fixes the problem. See https://pythonhosted.org/joblib/parallel.html#bad-interaction-of-multiprocessing-and-third-party-libraries for how to do it.

**Comment by virilo** [comment]
Hi ClimbsRocks,

We finally ended up executing a new python subprocess on each iteration (OS process):

```

print (Fore.BLACK + Back.GREEN + Style.DIM+ "Starting a new python process (say bye to Spyder debug!)" +  Style.RESET_ALL)

cmd = ["python", script_filename, "--args", your_args]
p = subprocess.Popen(cmd, stdout=subprocess.PIPE, stderr=subprocess.STDOUT)
pid = str(p.pid)
print (Fore.BLACK + Back.GREEN + Style.DIM+ "isolated process " + pid + Style.RESET_ALL)
sys.stdout.flush()

subprocess_in_execution= True        
while subprocess_in_execution:
    line = p.stdout.readline()
    if line:
        print (Fore.BLACK + Back.GREEN + Style.DIM+ "isolated process " + pid + ": " +  Style.RESET_ALL + str(line))
    else:
        subprocess_in_execution=False
        
print (Fore.BLACK + Back.GREEN + Style.DIM+ "Isolated process is finished. Here we are!" +  Style.RESET_ALL )
    
```


We were using this solution for a period of time.  But now, we don't need to use this workaround anymore.  It solved by itself, probably because:

 a) We stopped using GridSearchCV to start using our own iterator

 b) We updated xgboost python package to the most recent v4 update
Which xgboost version are you using?

Hope this helps.

Best regards,

Virilo
