### ISSUE TITLE
Unable to build xgboost 0.90 with GCC5.1.0

### ISSUE THREAD

**Issue by srams2018** [dmlc/xgboost#5127]
Hi Everyone,
getting below dmlc error while building xgboost 0.90 with GCC 5.1 and cmake version 3.16 .
Need your help on this.

```
/home/myadmin/GCC510/include/c++/5.1.0/thread:133:7: error: ‘std::thread::thread(_Callable&&, _Args&& ...) [with _Callable = dmlc::data::TextParserBase<IndexType, DType>::FillData(std::vector<dmlc::data::RowBlockContainer<IndexType, DType> >*) [with IndexType = unsigned int; DType = long int]::<lambda()>; _Args = {}]’, declared using local type ‘dmlc::data::TextParserBase<IndexType, DType>::FillData(std::vector<dmlc::data::RowBlockContainer<IndexType, DType> >*) [with IndexType = unsigned int; DType = long int]::<lambda()>’, is used but never defined [-fpermissive]
/home/myadmin/GCC510/include/c++/5.1.0/thread:133:7: error: ‘std::thread::thread(_Callable&&, _Args&& ...) [with _Callable = dmlc::data::TextParserBase<IndexType, DType>::FillData(std::vector<dmlc::data::RowBlockContainer<IndexType, DType> >*) [with IndexType = long unsigned int; DType = int]::<lambda()>; _Args = {}]’, declared using local type ‘dmlc::data::TextParserBase<IndexType, DType>::FillData(std::vector<dmlc::data::RowBlockContainer<IndexType, DType> >*) [with IndexType = long unsigned int; DType = int]::<lambda()>’, is used but never defined [-fpermissive]
/home/myadmin/GCC510/include/c++/5.1.0/thread:133:7: error: ‘std::thread::thread(_Callable&&, _Args&& ...) [with _Callable = dmlc::data::TextParserBase<IndexType, DType>::FillData(std::vector<dmlc::data::RowBlockContainer<IndexType, DType> >*) [with IndexType = unsigned int; DType = int]::<lambda()>; _Args = {}]’, declared using local type ‘dmlc::data::TextParserBase<IndexType, DType>::FillData(std::vector<dmlc::data::RowBlockContainer<IndexType, DType> >*) [with IndexType = unsigned int; DType = int]::<lambda()>’, is used but never defined [-fpermissive]
/home/myadmin/GCC510/include/c++/5.1.0/thread:133:7: error: ‘std::thread::thread(_Callable&&, _Args&& ...) [with _Callable = dmlc::data::TextParserBase<IndexType, DType>::FillData(std::vector<dmlc::data::RowBlockContainer<IndexType, DType> >*) [with IndexType = long unsigned int; DType = float]::<lambda()>; _Args = {}]’, declared using local type ‘dmlc::data::TextParserBase<IndexType, DType>::FillData(std::vector<dmlc::data::RowBlockContainer<IndexType, DType> >*) [with IndexType = long unsigned int; DType = float]::<lambda()>’, is used but never defined [-fpermissive]
/home/myadmin/GCC510/include/c++/5.1.0/thread:133:7: error: ‘std::thread::thread(_Callable&&, _Args&& ...) [with _Callable = dmlc::data::TextParserBase<IndexType, DType>::FillData(std::vector<dmlc::data::RowBlockContainer<IndexType, DType> >*) [with IndexType = unsigned int; DType = float]::<lambda()>; _Args = {}]’, declared using local type ‘dmlc::data::TextParserBase<IndexType, DType>::FillData(std::vector<dmlc::data::RowBlockContainer<IndexType, DType> >*) [with IndexType = unsigned int; DType = float]::<lambda()>’, is used but never defined [-fpermissive]
gmake[2]: *** [dmlc-core/CMakeFiles/dmlc.dir/src/data.cc.o] Error 1
gmake[2]: *** Waiting for unfinished jobs....
gmake[1]: *** [dmlc-core/CMakeFiles/dmlc.dir/all] Error 2
gmake[1]: *** Waiting for unfinished jobs....
[ 90%] Built target objxgboost
gmake: *** [all] Error 2
building Java wrapper
cd ..
mkdir -p build
cd build
cmake .. -DUSE_OPENMP:BOOL=ON -DUSE_HDFS:BOOL=OFF -DUSE_AZURE:BOOL=OFF -DUSE_S3:BOOL=OFF -DUSE_CUDA:BOOL=OFF -DJVM_BINDINGS:BOOL=ON
cmake --build . --config Release -- -j $(nproc)
Traceback (most recent call last):
  File "create_jni.py", line 93, in <module>
    run("cmake --build . --config Release" + maybe_parallel_build)
  File "create_jni.py", line 51, in run
    subprocess.check_call(command, shell=True, **kwargs)
  File "/apps/anaconda/4.3.1/3/lib/python3.6/subprocess.py", line 291, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command 'cmake --build . --config Release -- -j $(nproc)' returned non-zero exit status 2.
[ERROR] Command execution failed.
org.apache.commons.exec.ExecuteException: Process exited with an error: 1 (Exit value: 1)
        at org.apache.commons.exec.DefaultExecutor.executeInternal(DefaultExecutor.java:404)
        at org.apache.commons.exec.DefaultExecutor.execute(DefaultExecutor.java:166)
        at org.codehaus.mojo.exec.ExecMojo.executeCommandLine(ExecMojo.java:804)
        at org.codehaus.mojo.exec.ExecMojo.executeCommandLine(ExecMojo.java:751)
        at org.codehaus.mojo.exec.ExecMojo.execute(ExecMojo.java:313)
        at org.apache.maven.plugin.DefaultBuildPluginManager.executeMojo(DefaultBuildPluginManager.java:134)
        at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:208)
        at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:154)
        at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:146)
        at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject(LifecycleModuleBuilder.java:117)
        at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject(LifecycleModuleBuilder.java:81)
        at org.apache.maven.lifecycle.internal.builder.singlethreaded.SingleThreadedBuilder.build(SingleThreadedBuilder.java:51)
        at org.apache.maven.lifecycle.internal.LifecycleStarter.execute(LifecycleStarter.java:128)
        at org.apache.maven.DefaultMaven.doExecute(DefaultMaven.java:309)
        at org.apache.maven.DefaultMaven.doExecute(DefaultMaven.java:194)
        at org.apache.maven.DefaultMaven.execute(DefaultMaven.java:107)
        at org.apache.maven.cli.MavenCli.execute(MavenCli.java:993)
        at org.apache.maven.cli.MavenCli.doMain(MavenCli.java:345)
        at org.apache.maven.cli.MavenCli.main(MavenCli.java:191)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:498)
        at org.codehaus.plexus.classworlds.launcher.Launcher.launchEnhanced(Launcher.java:289)
        at org.codehaus.plexus.classworlds.launcher.Launcher.launch(Launcher.java:229)
        at org.codehaus.plexus.classworlds.launcher.Launcher.mainWithExitCode(Launcher.java:415)
        at org.codehaus.plexus.classworlds.launcher.Launcher.main(Launcher.java:356)
[INFO] ------------------------------------------------------------------------
[INFO] Reactor Summary:
[INFO]
[INFO] XGBoost JVM Package ................................ SUCCESS [  2.501 s]
[INFO] xgboost4j .......................................... FAILURE [ 18.353 s]
[INFO] xgboost4j-spark .................................... SKIPPED
[INFO] xgboost4j-flink .................................... SKIPPED
[INFO] xgboost4j-example .................................. SKIPPED
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
```

**Comment by trivialfis** [comment]
@srams2018 I tested it with 5.5.0 and it works fine.  I'm not sure how to workaround this compiler error.
