### ISSUE TITLE
[jvm-packages] Spylon-kernel java.lang.ClassCastException: ml.dmlc.xgboost4j.scala.Booster cannot be cast to ml.dmlc.xgboost4j.scala.Booster

### ISSUE THREAD

**Issue by brookwc** [dmlc/xgboost#5186]
I was using spylon to run a local jupyter scala notebook (following the iris example). 

attempt 1)
spark.version = 2.4.4
spylon-kernel = 0.4.1
scala = 2.11.8
xgboost4j-spark = 0.90

Then I hit the following error soon after training starts.

2020-01-07 14:21:16 WARN  XGBoostSpark:272 - train_test_ratio is deprecated since XGBoost 0.82, we recommend to explicitly pass a training and multiple evaluation datasets by passing 'eval_sets' and 'eval_set_names'
Tracker started, with env={DMLC_NUM_SERVER=0, DMLC_TRACKER_URI=17.237.4.96, DMLC_TRACKER_PORT=9091, DMLC_NUM_WORKER=2}
2020-01-07 14:21:16 WARN  XGBoostSpark:272 - train_test_ratio is deprecated since XGBoost 0.82, we recommend to explicitly pass a training and multiple evaluation datasets by passing 'eval_sets' and 'eval_set_names'
java.lang.ClassCastException: ml.dmlc.xgboost4j.scala.Booster cannot be cast to ml.dmlc.xgboost4j.scala.Booster
  at ml.dmlc.xgboost4j.scala.spark.XGBoost$.ml$dmlc$xgboost4j$scala$spark$XGBoost$$postTrackerReturnProcessing(XGBoost.scala:499)
  at ml.dmlc.xgboost4j.scala.spark.XGBoost$$anonfun$trainDistributed$1.apply(XGBoost.scala:404)
  at ml.dmlc.xgboost4j.scala.spark.XGBoost$$anonfun$trainDistributed$1.apply(XGBoost.scala:381)
  at scala.collection.TraversableLike$$anonfun$map$1.apply(TraversableLike.scala:234)
  at scala.collection.TraversableLike$$anonfun$map$1.apply(TraversableLike.scala:234)
  at scala.collection.immutable.List.foreach(List.scala:381)
  at scala.collection.TraversableLike$class.map(TraversableLike.scala:234)
  at scala.collection.immutable.List.map(List.scala:285)
  at ml.dmlc.xgboost4j.scala.spark.XGBoost$.trainDistributed(XGBoost.scala:380)
  at ml.dmlc.xgboost4j.scala.spark.XGBoostClassifier.train(XGBoostClassifier.scala:196)
  at ml.dmlc.xgboost4j.scala.spark.XGBoostClassifier.train(XGBoostClassifier.scala:48)
  at org.apache.spark.ml.Predictor.fit(Predictor.scala:118)
  ... 43 elided

attempt 2). I searched around the error and found https://github.com/dmlc/xgboost/issues/4218. It suggests things should work with my setting. Nevertheless I tried to install apache-spark@2.3.2 & xgboost4j-spark@0.82. But the error still remains.

Is this related to spylon kernel or how to fix the issue?

**Comment by hcho3** [comment]
Please upgrade to XGBoost4J-Spark 1.1.2 (for Spark 2.4.3) or XGBoost4J-Spark 1.2.1 (for Spark 3.0.0).
