### ISSUE TITLE
Can't install in python:3.7-slim container

### ISSUE THREAD

**Issue by smith-kyle** [dmlc/xgboost#5231]
Trying to install in the official Python 3.7 docker container throws an error
```
$ docker run -it python:3.7-slim bash
root@dd79bdfced0c:/# pip3 install xgboost
Collecting xgboost
  Downloading xgboost-0.90.tar.gz (676 kB)
     |████████████████████████████████| 676 kB 4.1 MB/s
    ERROR: Command errored out with exit status 1:
     command: /usr/local/bin/python -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/tmp/pip-install-7rpnls52/xgboost/setup.py'"'"'; __file__='"'"'/tmp/pip-install-7rpnls52/xgboost/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' egg_info --egg-base /tmp/pip-install-7rpnls52/xgboost/pip-egg-info
         cwd: /tmp/pip-install-7rpnls52/xgboost/
    Complete output (20 lines):
    + pwd
    + oldpath=/tmp/pip-install-7rpnls52/xgboost
    + cd ./xgboost/
    + echo
    + grep -q darwin
    + LIB_XGBOOST=libxgboost.so
    + make clean
    ./xgboost/build-python.sh: 40: ./xgboost/build-python.sh: make: not found
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-install-7rpnls52/xgboost/setup.py", line 42, in <module>
        LIB_PATH = libpath['find_lib_path']()
      File "/tmp/pip-install-7rpnls52/xgboost/xgboost/libpath.py", line 48, in find_lib_path
        'List of candidates:\n' + ('\n'.join(dll_path)))
    XGBoostLibraryNotFound: Cannot find XGBoost Library in the candidate path, did you install compilers and run build.sh in root path?
    List of candidates:
    /tmp/pip-install-7rpnls52/xgboost/xgboost/libxgboost.so
    /tmp/pip-install-7rpnls52/xgboost/xgboost/../../lib/libxgboost.so
    /tmp/pip-install-7rpnls52/xgboost/xgboost/./lib/libxgboost.so
    /usr/local/xgboost/libxgboost.so
    ----------------------------------------
ERROR: Command errored out with exit status 1: python setup.py egg_info Check the logs for full command output.
```

**Comment by smith-kyle** [comment]
Oh I see. It's because this image has pip 20 installed so it's the same issue as https://github.com/dmlc/xgboost/issues/5221.

I'll close this out.
