### ISSUE TITLE
Model trained with tree_method='gpu_hist' fails on Windows without GPU xgboost>0.80

### ISSUE THREAD

**Issue by BertrandNOEL** [dmlc/xgboost#5234]
I train a model on a server with a GPU using the following code
```python
import joblib
import xgboost as xgb
from sklearn.datasets import load_digits
digits = load_digits(2)
X = digits['data']
y = digits['target']
model = xgb.XGBClassifier(tree_method='gpu_hist')
model.fit(X, y)
joblib.dump(model, "model.pickle")
```
I send this model to a Windows machine, without GPU, and use the following code
```python
import joblib
import xgboost as xgb
import numpy as np
model = joblib.load("model.pickle")
model.predict_proba([np.zeros(len(model.get_booster().feature_names))])
```
I get the following results
```python
# With xgboost==0.80
array([[0.9027222 , 0.09727783]], dtype=float32)
# With xgboost>0.80 (tried 0.81 and 0.90)
array([[0.5, 0.5]], dtype=float32)
```
On Linux, I get the expected result (!=0.5)

I do not have access to a Windows machine with a GPU to test if it would change the output

Info on machines:
  * The Linux server where I train the model
```
> uname -a
Linux xxxxxx 3.10.0-1062.4.3.el7.x86_64 #1 SMP Wed Nov 13 23:58:53 UTC 2019 x86_64 x86_64 x86_64 GNU/Linux
> sudo lshw -C display
...
  *-display
       product: GV100GL [Tesla V100 PCIe 16GB]
       vendor: NVIDIA Corporation
...
> python --version
3.6.8
> pip freeze
joblib==0.14.1
numpy==1.18.1
scikit-learn==0.22.1
scipy==1.4.1
sklearn==0.0
xgboost==0.90
```
  * The Windows machine
```
> ~ uname -a
Windows 7
> ~ sudo lshw -C display
Intel(R) HD Graphics 520
> python --version
3.6.1
> pip freeze
joblib==0.14.1
numpy==1.18.1
scikit-learn==0.22.1
scipy==1.4.1
sklearn==0.0
xgboost==0.90
```

**Comment by trivialfis** [comment]
Could you try latest master branch?

**Comment by BertrandNOEL** [comment]
Installed at commit `0c7455276da88319b94567137e155a0b9f4eed77`
```bash
pip install https://s3-us-west-2.amazonaws.com/xgboost-nightly-builds/xgboost-1.0.0_SNAPSHOT%2B0c7455276da88319b94567137e155a0b9f4eed77-py2.py3-none-win_amd64.whl
```

Retrained a new model on the Linux server with 1.0, because loading a 0.90 xgboost pickle failed

On the Windows.
Got a new warning message
```python
>>> model = joblib.load("model.pickle")
[14:46:26] WARNING: C:\Users\Administrator\workspace\xgboost-win64_master\src\gbm\gbtree.cc:310: Loading from a raw memory buffer on CPU only machine.  Change tree_method to hist.
```

Previous code to call prediction does not work any more
```python
>>> model.predict_proba([np.zeros(len(model.get_booster().feature_names))])
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "C:\Utilisateurs\xx\venv\lib\site-packages\xgboost\sklearn.py", line 855, in predict_proba
    missing=self.missing, nthread=self.n_jobs)
  File "C:\Utilisateurs\xx\venv\lib\site-packages\xgboost\core.py", line 455, in __init__
    raise TypeError('Input data can not be a list.')
TypeError: Input data can not be a list.
```

I used
```python
>>> model.predict_proba(np.zeros((1, len(model.get_booster().feature_names))), validate_features=False)
array([[0.9707467, 0.0292533]], dtype=float32)
```

Looks like it is fixed! Perfect, thanks!

**Comment by trivialfis** [comment]
The warning message doesn't matter if you don't want to continue the previous training.  See the tutorial about saving model on master branch.

**Comment by BertrandNOEL** [comment]
Thanks. Tutorial for reference:
https://github.com/dmlc/xgboost/blob/master/doc/tutorials/saving_model.rst
