### ISSUE TITLE
setup.py problem at version 1.0

### ISSUE THREAD

**Issue by fabiorangel** [dmlc/xgboost#5331]
```
ERROR: Command errored out with exit status 1:
     command: /Users/fabio.rangel/Desktop/topic_classifier/.direnv/python-3.7.6/bin/python -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/private/var/folders/6y/1z5q9lm54x7f5pmr2t34zdf40000gq/T/pip-install-n7doqpk0/xgboost/setup.py'"'"'; __file__='"'"'/private/var/folders/6y/1z5q9lm54x7f5pmr2t34zdf40000gq/T/pip-install-n7doqpk0/xgboost/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' egg_info --egg-base /private/var/folders/6y/1z5q9lm54x7f5pmr2t34zdf40000gq/T/pip-install-n7doqpk0/xgboost/pip-egg-info
         cwd: /private/var/folders/6y/1z5q9lm54x7f5pmr2t34zdf40000gq/T/pip-install-n7doqpk0/xgboost/
    Complete output (27 lines):
    ++ pwd
    + oldpath=/private/var/folders/6y/1z5q9lm54x7f5pmr2t34zdf40000gq/T/pip-install-n7doqpk0/xgboost
    + cd ./xgboost/
    + mkdir -p build
    + cd build
    + cmake ..
    ./xgboost/build-python.sh: line 21: cmake: command not found
    + echo -----------------------------
    -----------------------------
    + echo 'Building multi-thread xgboost failed'
    Building multi-thread xgboost failed
    + echo 'Start to build single-thread xgboost'
    Start to build single-thread xgboost
    + cmake .. -DUSE_OPENMP=0
    ./xgboost/build-python.sh: line 27: cmake: command not found
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/private/var/folders/6y/1z5q9lm54x7f5pmr2t34zdf40000gq/T/pip-install-n7doqpk0/xgboost/setup.py", line 42, in <module>
        LIB_PATH = libpath['find_lib_path']()
      File "/private/var/folders/6y/1z5q9lm54x7f5pmr2t34zdf40000gq/T/pip-install-n7doqpk0/xgboost/xgboost/libpath.py", line 50, in find_lib_path
        'List of candidates:\n' + ('\n'.join(dll_path)))
    XGBoostLibraryNotFound: Cannot find XGBoost Library in the candidate path, did you install compilers and run build.sh in root path?
    List of candidates:
    /private/var/folders/6y/1z5q9lm54x7f5pmr2t34zdf40000gq/T/pip-install-n7doqpk0/xgboost/xgboost/libxgboost.dylib
    /private/var/folders/6y/1z5q9lm54x7f5pmr2t34zdf40000gq/T/pip-install-n7doqpk0/xgboost/xgboost/../../lib/libxgboost.dylib
    /private/var/folders/6y/1z5q9lm54x7f5pmr2t34zdf40000gq/T/pip-install-n7doqpk0/xgboost/xgboost/./lib/libxgboost.dylib
    /Users/fabio.rangel/Desktop/topic_classifier/.direnv/python-3.7.6/xgboost/libxgboost.dylib
    ----------------------------------------
ERROR: Command errored out with exit status 1: python setup.py egg_info Check the logs for full command output.
```

**Comment by trivialfis** [comment]
@fabiorangel You need CMake to build XGBoost.

**Comment by fabiorangel** [comment]
Sorry the lack of information, but something changed from past version to this one. This error is from a command:

`pip install -r requirements.txt` 

As the file did not provide the xgboost version, it started to deploy at version 1.0, which is getting this error. Before today's update, my deploy is getting this error and I needed to provide version 0.9 in the requirements.txt.

Thank you for your help.

**Comment by trivialfis** [comment]
I don't think anything has changed in that regard.  Just the binary wheel is not available yet?

**Comment by hcho3** [comment]
It looks like the OP is using another OS. Currently we provide binary wheels for Linux and Windows only.

**Comment by srossgupta** [comment]
`brew install cmake` worked for me on MacOS
