### ISSUE TITLE
Distributed XGBoost  run as YARN application error.

### ISSUE THREAD

**Issue by vivounicorn** [dmlc/xgboost#535]
Hi @tqchen 
Tianqi  asking for help
When i using distributed XGBoost  run as YARN application with example https://github.com/dmlc/wormhole/blob/master/learn/xgboost/run_yarn.sh 
I encountered the following error：
-------------------------------------------------------------------------------------------------------------------------------
Container: container_1426769619161_1614804_01_000004 on datanode37.data.a_28605
==================================================================================
LogType: stderr
LogLength: 533
Log Contents:
user defined debug:
-------------------------------------------------------------------------------------------------------------------------
/data/sysdir/hadoop-2.4.1/bin/hadoop classpath
/data/sysdir/hadoop-2.4.1/etc/hadoop:/data/sysdir/hadoop-2.4.1/share/hadoop/common/lib/*:/data/sysdir/hadoop-2.4.1/share/hadoop/common/*:/data/sysdir/hadoop-2.4.1/share/hadoop/hdfs:/data/sysdir/hadoop-2.4.1/share/hadoop/hdfs/lib/*:/data/sysdir/hadoop-2.4.1/share/hadoop/hdfs/*:/data/sysdir/hadoop-2.4.1/share/hadoop/yarn/lib/*:/data/sysdir/hadoop-2.4.1/share/hadoop/yarn/*:/data/sysdir/hadoop-2.4.1/share/hadoop/mapreduce/lib/*:/data/sysdir/hadoop-2.4.1/share/hadoop/mapreduce/*:/data/sysdir/hadoop-2.4.1/contrib/capacity-scheduler/*.jar
---------------------------------------------------------------------------------------------------------------------------

Traceback (most recent call last):
  File "./run_hdfs_prog.py", line 50, in <module>
    ret = subprocess.call(args = sys.argv[1:], env = env)
  File "/usr/lib64/python2.6/subprocess.py", line 478, in call
    p = Popen(*popenargs, **kwargs)
  File "/usr/lib64/python2.6/subprocess.py", line 639, in __init__
    errread, errwrite)
  File "/usr/lib64/python2.6/subprocess.py", line 1228, in _execute_child
    raise child_exception
OSError: [Errno 2] No such file or directory

LogType: stdout
LogLength: 0
Log Contents:

Container: container_1426769619161_1614804_01_000001 on datanode53.data.a_35813
==================================================================================
LogType: stderr
LogLength: 15702
Log Contents:
15/10/08 19:45:15 INFO dmlc.ApplicationMaster: Start AM as user=root
15/10/08 19:45:15 INFO dmlc.ApplicationMaster: Try to start 0 Servers and 2 Workers
15/10/08 19:45:15 INFO client.RMProxy: Connecting to ResourceManager at resourcemanager.data.a/192.168.201.53:8030
15/10/08 19:45:15 INFO impl.NMClientAsyncImpl: Upper bound of the thread pool size is 500
15/10/08 19:45:15 INFO impl.ContainerManagementProtocolProxy: yarn.client.max-nodemanagers-proxies : 500
15/10/08 19:45:15 INFO dmlc.ApplicationMaster: [DMLC] ApplicationMaster started
15/10/08 19:45:17 INFO impl.AMRMClientImpl: Received new token for : datanode46.data.a:53177
15/10/08 19:45:17 INFO impl.AMRMClientImpl: Received new token for : datanode48.data.a:60111
15/10/08 19:45:17 INFO dmlc.ApplicationMaster: {run_hdfs_prog.py=resource { scheme: "hdfs" port: -1 file: "/tmp/temp-dmlc-yarn-application_1426769619161_1614804/run_hdfs_prog.py" } size: 1510 timestamp: 1444304713473 type: FILE visibility: APPLICATION, dmlc-yarn.jar=resource { scheme: "hdfs" port: -1 file: "/tmp/temp-dmlc-yarn-application_1426769619161_1614804/dmlc-yarn.jar" } size: 19303 timestamp: 1444304713508 type: FILE visibility: APPLICATION, mushroom.hadoop.conf=resource { scheme: "hdfs" port: -1 file: "/tmp/temp-dmlc-yarn-application_1426769619161_1614804/mushroom.hadoop.conf" } size: 1084 timestamp: 1444304713555 type: FILE visibility: APPLICATION}
15/10/08 19:45:17 INFO dmlc.ApplicationMaster: {run_hdfs_prog.py=resource { scheme: "hdfs" port: -1 file: "/tmp/temp-dmlc-yarn-application_1426769619161_1614804/run_hdfs_prog.py" } size: 1510 timestamp: 1444304713473 type: FILE visibility: APPLICATION, dmlc-yarn.jar=resource { scheme: "hdfs" port: -1 file: "/tmp/temp-dmlc-yarn-application_1426769619161_1614804/dmlc-yarn.jar" } size: 19303 timestamp: 1444304713508 type: FILE visibility: APPLICATION, mushroom.hadoop.conf=resource { scheme: "hdfs" port: -1 file: "/tmp/temp-dmlc-yarn-application_1426769619161_1614804/mushroom.hadoop.conf" } size: 1084 timestamp: 1444304713555 type: FILE visibility: APPLICATION}
15/10/08 19:45:17 INFO impl.NMClientAsyncImpl: Processing Event EventType: START_CONTAINER for Container container_1426769619161_1614804_01_000002
15/10/08 19:45:17 INFO impl.NMClientAsyncImpl: Processing Event EventType: START_CONTAINER for Container container_1426769619161_1614804_01_000003
15/10/08 19:45:17 INFO impl.ContainerManagementProtocolProxy: Opening proxy : datanode46.data.a:53177
15/10/08 19:45:17 INFO impl.ContainerManagementProtocolProxy: Opening proxy : datanode48.data.a:60111
15/10/08 19:45:17 INFO dmlc.ApplicationMaster: onContainerStarted Invoked
15/10/08 19:45:17 INFO dmlc.ApplicationMaster: onContainerStarted Invoked
15/10/08 19:45:18 WARN dmlc.ApplicationMaster: KILLED_EXCEEDED_PMEM
15/10/08 19:45:18 INFO dmlc.ApplicationMaster: [DMLC] Task 0 exited with status 1 Diagnostics:Exception from container-launch: org.apache.hadoop.util.Shell$ExitCodeException:
org.apache.hadoop.util.Shell$ExitCodeException:
        at org.apache.hadoop.util.Shell.runCommand(Shell.java:505)
        at org.apache.hadoop.util.Shell.run(Shell.java:418)
        at org.apache.hadoop.util.Shell$ShellCommandExecutor.execute(Shell.java:650)
        at org.apache.hadoop.yarn.server.nodemanager.DefaultContainerExecutor.launchContainer(DefaultContainerExecutor.java:195)
        at org.apache.hadoop.yarn.server.nodemanager.containermanager.launcher.ContainerLaunch.call(ContainerLaunch.java:300)
        at org.apache.hadoop.yarn.server.nodemanager.containermanager.launcher.ContainerLaunch.call(ContainerLaunch.java:81)
        at java.util.concurrent.FutureTask$Sync.innerRun(FutureTask.java:334)
        at java.util.concurrent.FutureTask.run(FutureTask.java:166)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1110)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:603)
        at java.lang.Thread.run(Thread.java:722)

Container exited with a non-zero exit code 1

PS：when i compile dmlc-core i have set the flag USE_HDFS = 1 and comiple xgboost with commend "make dmlc=../dmlc-core"

thanks alot.

**Comment by vivounicorn** [comment]
Sorry，issue can be closed，I should guarantee all input files can be found，xgboost is compiled with default name "xgboost" not "xgboost.dmlc"
../dmlc-core/tracker/dmlc_yarn.py  -n $1 --vcores $2 -q test --jobname btest --log-level DEBUG --log-file /data2/home/dm/logs.dat  --yarn-scripts ../dmlc-core/yarn/\
    ../xgboost(xgboost.dmlc) mushroom.hadoop.conf nthread=$2\
    data=hdfs://$3/data/agaricus.txt.train\
    eval[test]=hdfs://$3/data/agaricus.txt.test\
    model_out=hdfs://$3/mushroom.final.model
