### ISSUE TITLE
Distributed XGBoost run as YARN application running slow

### ISSUE THREAD

**Issue by vivounicorn** [dmlc/xgboost#543]
@tqchen 
dear tianqi seek help！
     I have a small hadoop cluster(about 100 machines)，my training data set is 20G(also small)，
 after my job is submitted (nworkers=19 and ncores=2, mapred.cluster.max.map.memory.mb=8G)，I have logs as follows：
----------------------------------------------------------------------------------------------------------------------------
15/10/13 13:01:45 WARN util.NativeCodeLoader: Unable to load native-hadoop library for your platform... using builtin-java classes where applicable
15/10/13 13:01:46 INFO client.RMProxy: Connecting to ResourceManager at resourcemanager.data.lq/192.168.201.53:8032
15/10/13 13:01:47 INFO dmlc.Client: jobname=gbdt_lib_example,username=dm
15/10/13 13:01:47 INFO dmlc.Client: Submitting application application_1426769619161_1706895
15/10/13 13:01:47 INFO impl.YarnClientImpl: Submitted application application_1426769619161_1706895
2015-10-13 13:26:46,987 DEBUG Recieve start signal from 192.168.201.1; assign rank 0
2015-10-13 13:26:47,104 DEBUG Recieve start signal from 192.168.201.12; assign rank 1
2015-10-13 13:26:47,184 DEBUG Recieve start signal from 192.168.201.16; assign rank 2
2015-10-13 13:26:47,264 DEBUG Recieve start signal from 192.168.201.23; assign rank 3
2015-10-13 13:26:47,345 DEBUG Recieve start signal from 192.168.201.25; assign rank 4
2015-10-13 13:26:47,425 DEBUG Recieve start signal from 192.168.201.27; assign rank 5
2015-10-13 13:26:47,506 DEBUG Recieve start signal from 192.168.201.36; assign rank 6
2015-10-13 13:26:47,586 DEBUG Recieve start signal from 192.168.201.4; assign rank 7
2015-10-13 13:26:47,667 DEBUG Recieve start signal from 192.168.201.6; assign rank 8
2015-10-13 13:26:47,747 DEBUG Recieve start signal from 192.168.201.81; assign rank 9
2015-10-13 13:26:47,827 DEBUG Recieve start signal from 192.168.201.81; assign rank 10
2015-10-13 13:26:47,908 DEBUG Recieve start signal from 192.168.201.81; assign rank 11
2015-10-13 13:26:47,993 DEBUG Recieve start signal from 192.168.201.86; assign rank 12
2015-10-13 13:26:48,073 DEBUG Recieve start signal from 192.168.201.88; assign rank 13
2015-10-13 13:26:48,154 DEBUG Recieve start signal from 192.168.201.89; assign rank 14
2015-10-13 13:26:48,234 DEBUG Recieve start signal from 192.168.201.90; assign rank 15
2015-10-13 13:26:48,314 DEBUG Recieve start signal from 192.168.201.91; assign rank 16
2015-10-13 13:26:48,395 DEBUG Recieve start signal from 192.168.201.94; assign rank 17
2015-10-13 13:26:48,485 DEBUG Recieve start signal from 192.168.201.98; assign rank 18
2015-10-13 13:26:48,485 INFO @tracker All of 19 nodes getting started
2015-10-13 13:27:31,587 DEBUG Recieve start signal from 3
2015-10-13 13:27:35,893 DEBUG Recieve start signal from 5
2015-10-13 13:27:39,775 DEBUG Recieve start signal from 4
2015-10-13 13:27:40,984 DEBUG Recieve start signal from 2
2015-10-13 13:27:41,104 DEBUG Recieve start signal from 1
2015-10-13 13:27:48,450 DEBUG Recieve start signal from 6
2015-10-13 13:27:48,531 DEBUG Recieve start signal from 8
2015-10-13 13:27:51,895 DEBUG Recieve recover signal from 0
2015-10-13 13:28:31,592 DEBUG Recieve start signal from 7
2015-10-13 13:28:31,738 DEBUG Recieve start signal from 16
2015-10-13 13:28:31,819 DEBUG Recieve start signal from 0
2015-10-13 13:28:31,950 DEBUG Recieve start signal from 4
2015-10-13 13:28:32,031 DEBUG Recieve start signal from 2
2015-10-13 13:28:34,813 DEBUG Recieve start signal from 8

the job is very very slow and pending, is there something worng?
------------------------------------------------------------------------------------------------------------------------

PS：when I set nworkers=2 and ncores=2， the error is：
------------------------------------------------------------------------------------------------------------------------
[DMLC] Task 1 failed more than 3times
15/10/13 12:16:13 INFO impl.AMRMClientImpl: Waiting for application to be successfully unregistered.
Exception in thread "main" java.lang.Exception: Application not successful
        at org.apache.hadoop.yarn.dmlc.ApplicationMaster.run(ApplicationMaster.java:271)
        at org.apache.hadoop.yarn.dmlc.ApplicationMaster.main(ApplicationMaster.java:108)
stdout0
INFO dmlc.ApplicationMaster: [DMLC] Task 1 exited with status 143 Diagnostics:Container [pid=74321,containerID=container_1426769619161_1706629_01_000016] is running beyond physical memory limits. Current usage: 2.4 GB of 2 GB physical memory used; 4.0 GB of 4.2 GB virtual memory used. Killing container

it means  physical memory is not enough，may be number of workers is to small，so I set nworkers=19.
------------------------------------------------------------------------------------------------------------------------

**Comment by vivounicorn** [comment]
mapred.cluster.max.map.memory.mb=8G
