### ISSUE TITLE
[jvm-packages] java.lang.NoSuchMethodError: org.apache.spark.ml.param.shared.HasWeightCol.$init$(Lorg/apache/spark/ml/param/shared/HasWeightCol;)V

### ISSUE THREAD

**Issue by liuke1993** [dmlc/xgboost#5472]
Compile xgboost4j-spark_2.12-1.0.0.jar (release-1.0.0 version) from source on MacOSX
use spark 2.4.3 yarn, scala 2.11.8

code piece: 
val xgbClassifier = new XGBoostClassifier()

I got the following exception:
Exception in thread "main" java.lang.NoSuchMethodError: org.apache.spark.ml.param.shared.HasWeightCol.$init$(Lorg/apache/spark/ml/param/shared/HasWeightCol;)V
    at ml.dmlc.xgboost4j.scala.spark.XGBoostClassifier.<init>(XGBoostClassifier.scala:43)
    at ml.dmlc.xgboost4j.scala.spark.XGBoostClassifier.<init>(XGBoostClassifier.scala:46)
    at com.jd.ad.datamill.algorithms.user_coupon_xg.XGBoostTrainer$.trainXGBoost(XGBoostTrainer.scala:39)
    at com.jd.ad.datamill.algorithms.user_coupon_xg.XGBoostTrainer$.main(XGBoostTrainer.scala:235)
    at com.jd.ad.datamill.algorithms.user_coupon_xg.XGBoostTrainer.main(XGBoostTrainer.scala)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
    at java.lang.reflect.Method.invoke(Method.java:498)
    at org.apache.spark.deploy.JavaMainApplication.start(SparkApplication.scala:52)
    at org.apache.spark.deploy.SparkSubmit.org$apache$spark$deploy$SparkSubmit$$runMain(SparkSubmit.scala:928)
    at org.apache.spark.deploy.SparkSubmit.doRunMain$1(SparkSubmit.scala:172)
    at org.apache.spark.deploy.SparkSubmit.submit(SparkSubmit.scala:200)
    at org.apache.spark.deploy.SparkSubmit.doSubmit(SparkSubmit.scala:91)
    at org.apache.spark.deploy.SparkSubmit$$anon$2.doSubmit(SparkSubmit.scala:1003)
    at org.apache.spark.deploy.SparkSubmit$.main(SparkSubmit.scala:1013)
    at org.apache.spark.deploy.SparkSubmit.main(SparkSubmit.scala)

**Comment by pangjac** [comment]
The version matters. Based on your env settings(spark 2.4.3 yarn, scala 2.11.8), maybe you can try to compile [xgboost4j-spark_2.**11**_1.0.0.jar](https://mvnrepository.com/artifact/ml.dmlc/xgboost4j-spark_2.11/1.0.0), instead of using `...spark_2.12...`

**Comment by hcho3** [comment]
We also provide XGBoost4J artifacts compiled with Scala 2.11 on the Maven Central.
