### ISSUE TITLE
[jvm-packages] java.net.ConnectException: Connection refused

### ISSUE THREAD

**Issue by liuke1993** [dmlc/xgboost#5499]
use: xgboost4j-spark 0.90, spark 2.4.3, scala 2.11.12, java jdk1.8.0_121

code piece:
```
val trainDf = spark.read.parquet(trainDfPath).select("user_log_acct", "feature", "label")
val xgbClassifier = new XGBoostClassifier()
      .setEta(0.1)
      .setMaxDepth(6)
      .setNumEarlyStoppingRounds(15)
      .setNumClass(2)
      .setNumRound(100)
      .setNumWorkers(256)
      .setMissing(-1)
      .setObjective("multi:softmax")
      .setFeaturesCol("feature")
      .setLabelCol("label")

val xgbClassifierModel = xgbClassifier.fit(trainDf)
```
XGBoost Parameters:
20/04/09 11:59:17 [main] INFO XGBoostSpark: Running XGBoost 0.90 with parameters:
alpha -> 0.0
min_child_weight -> 1.0
sample_type -> uniform
base_score -> 0.5
colsample_bylevel -> 1.0
grow_policy -> depthwise
skip_drop -> 0.0
lambda_bias -> 0.0
silent -> 0
scale_pos_weight -> 1.0
seed -> 0
cache_training_set -> false
features_col -> feature
num_early_stopping_rounds -> 15
label_col -> label
num_workers -> 256
subsample -> 1.0
lambda -> 1.0
max_depth -> 6
probability_col -> probability
raw_prediction_col -> rawPrediction
tree_limit -> 0
num_class -> 2
custom_eval -> null
rate_drop -> 0.0
max_bin -> 16
train_test_ratio -> 1.0
use_external_memory -> false
objective -> multi:softmax
eval_metric -> merror
num_round -> 100
timeout_request_workers -> 1800000
missing -> -1.0
checkpoint_path ->
tracker_conf -> TrackerConf(0,python)
tree_method -> auto
max_delta_step -> 0.0
eta -> 0.1
verbosity -> 1
colsample_bytree -> 1.0
normalize_type -> tree
custom_obj -> null
gamma -> 0.0
sketch_eps -> 0.03
nthread -> 1
prediction_col -> prediction
checkpoint_interval -> -1

Exception:
```
WARN ProtobufRpcEngine: Call to 0.0.0.0/0.0.0.0:8033 error: Call From BJHTYD-Client-47-233.hadoop.jd.local/10.198.47.233 to 0.0.0.0:8033 failed on connection exception: java.net.ConnectException: Connection refused, endpoint:0.0.0.0/0.0.0.0:8033; For more details see:  http://wiki.apache.org/hadoop/ConnectionRefused
WARN ProtobufRpcEngine: Call to 0.0.0.0/0.0.0.0:8033 error: Call From BJHTYD-Client-47-233.hadoop.jd.local/10.198.47.233 to 0.0.0.0:8033 failed on connection exception: java.net.ConnectException: Connection refused, endpoint:0.0.0.0/0.0.0.0:8033; For more details see:  http://wiki.apache.org/hadoop/ConnectionRefused
20/04/09 11:59:21 [SparkUI-181] WARN ServletHandler:
javax.servlet.ServletException: Could not determine the proxy server for redirection
    at org.apache.hadoop.yarn.server.webproxy.amfilter.AmIpFilter.findRedirectUrl(AmIpFilter.java:183)
    at org.apache.hadoop.yarn.server.webproxy.amfilter.AmIpFilter.doFilter(AmIpFilter.java:138)
    at org.spark_project.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1759)
    at org.spark_project.jetty.servlet.ServletHandler.doHandle(ServletHandler.java:582)
    at org.spark_project.jetty.server.handler.ContextHandler.doHandle(ContextHandler.java:1180)
    at org.spark_project.jetty.servlet.ServletHandler.doScope(ServletHandler.java:512)
    at org.spark_project.jetty.server.handler.ContextHandler.doScope(ContextHandler.java:1112)
    at org.spark_project.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:141)
    at org.spark_project.jetty.server.handler.gzip.GzipHandler.handle(GzipHandler.java:493)
    at org.spark_project.jetty.server.handler.ContextHandlerCollection.handle(ContextHandlerCollection.java:213)
    at org.spark_project.jetty.server.handler.HandlerWrapper.handle(HandlerWrapper.java:134)
    at org.spark_project.jetty.server.Server.handle(Server.java:539)
    at org.spark_project.jetty.server.HttpChannel.handle(HttpChannel.java:333)
    at org.spark_project.jetty.server.HttpConnection.onFillable(HttpConnection.java:251)
    at org.spark_project.jetty.io.AbstractConnection$ReadCallback.succeeded(AbstractConnection.java:283)
    at org.spark_project.jetty.io.FillInterest.fillable(FillInterest.java:108)
    at org.spark_project.jetty.io.SelectChannelEndPoint$2.run(SelectChannelEndPoint.java:93)
    at org.spark_project.jetty.util.thread.strategy.ExecuteProduceConsume.executeProduceConsume(ExecuteProduceConsume.java:303)
    at org.spark_project.jetty.util.thread.strategy.ExecuteProduceConsume.produceConsume(ExecuteProduceConsume.java:148)
    at org.spark_project.jetty.util.thread.strategy.ExecuteProduceConsume.run(ExecuteProduceConsume.java:136)
    at org.spark_project.jetty.util.thread.QueuedThreadPool.runJob(QueuedThreadPool.java:671)
    at org.spark_project.jetty.util.thread.QueuedThreadPool$2.run(QueuedThreadPool.java:589)
    at java.lang.Thread.run(Thread.java:745)
20/04/09 11:59:21 [ForkJoinPool-1-worker-29] WARN XGBoostSpark: Unable to read total number of alive cores from REST API.Health Check will be ignored.
java.io.IOException: Server returned HTTP response code: 500 for URL: http://10.198.47.233:10124/api/v1/applications/application_9101216104803_1013311/executors
    at sun.net.www.protocol.http.HttpURLConnection.getInputStream0(HttpURLConnection.java:1876)
    at sun.net.www.protocol.http.HttpURLConnection.getInputStream(HttpURLConnection.java:1474)
    at java.net.URL.openStream(URL.java:1045)
    at org.codehaus.jackson.JsonFactory._optimizedStreamFromURL(JsonFactory.java:935)
    at org.codehaus.jackson.JsonFactory.createJsonParser(JsonFactory.java:530)
    at org.codehaus.jackson.map.ObjectMapper.readTree(ObjectMapper.java:1590)
    at org.apache.spark.SparkParallelismTracker.org$apache$spark$SparkParallelismTracker$$numAliveCores(SparkParallelismTracker.scala:55)
    at org.apache.spark.SparkParallelismTracker$$anonfun$execute$1.apply$mcZ$sp(SparkParallelismTracker.scala:106)
    at org.apache.spark.SparkParallelismTracker$$anonfun$1.apply$mcV$sp(SparkParallelismTracker.scala:73)
    at org.apache.spark.SparkParallelismTracker$$anonfun$1.apply(SparkParallelismTracker.scala:73)
    at org.apache.spark.SparkParallelismTracker$$anonfun$1.apply(SparkParallelismTracker.scala:73)
    at scala.concurrent.impl.Future$PromiseCompletingRunnable.liftedTree1$1(Future.scala:24)
    at scala.concurrent.impl.Future$PromiseCompletingRunnable.run(Future.scala:24)
    at scala.concurrent.impl.ExecutionContextImpl$AdaptedForkJoinTask.exec(ExecutionContextImpl.scala:121)
    at scala.concurrent.forkjoin.ForkJoinTask.doExec(ForkJoinTask.java:260)
    at scala.concurrent.forkjoin.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1339)
    at scala.concurrent.forkjoin.ForkJoinPool.runWorker(ForkJoinPool.java:1979)
    at scala.concurrent.forkjoin.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:107)

[spark-listener-group-shared] ERROR XGBoostTaskFailedListener: Training Task Failed during XGBoost Training: TaskKilled(another attempt succeeded,Vector(AccumulableInfo(103,None,Some(869),None,false,true,None), AccumulableInfo(105,None,Some(0),None,false,true,None), AccumulableInfo(120,None,Some(0),None,false,true,None), AccumulableInfo(121,None,Some(469244),None,false,true,None), AccumulableInfo(122,None,Some(15995438),None,false,true,None), AccumulableInfo(123,None,Some(29330),None,false,true,None)),Vector(LongAccumulator(id: 103, name: Some(internal.metrics.executorRunTime), value: 869), LongAccumulator(id: 105, name: Some(internal.metrics.resultSize), value: 0), LongAccumulator(id: 120, name: Some(internal.metrics.shuffle.write.recordsWritten), value: 0), LongAccumulator(id: 121, name: Some(internal.metrics.shuffle.write.writeTime), value: 469244), LongAccumulator(id: 122, name: Some(internal.metrics.input.bytesRead), value: 15995438), LongAccumulator(id: 123, name: Some(internal.metrics.input.recordsRead), value: 29330))), stopping SparkContext

[Thread-42] ERROR RabitTracker: Uncaught exception thrown by worker:
org.apache.spark.SparkException: Job 2 cancelled because SparkContext was shut down
    at org.apache.spark.scheduler.DAGScheduler$$anonfun$cleanUpAfterSchedulerStop$1.apply(DAGScheduler.scala:943)
    at org.apache.spark.scheduler.DAGScheduler$$anonfun$cleanUpAfterSchedulerStop$1.apply(DAGScheduler.scala:941)
    at scala.collection.mutable.HashSet.foreach(HashSet.scala:78)
    at org.apache.spark.scheduler.DAGScheduler.cleanUpAfterSchedulerStop(DAGScheduler.scala:941)
    at org.apache.spark.scheduler.DAGSchedulerEventProcessLoop.onStop(DAGScheduler.scala:2177)
    at org.apache.spark.util.EventLoop.stop(EventLoop.scala:84)
    at org.apache.spark.scheduler.DAGScheduler.stop(DAGScheduler.scala:2090)
    at org.apache.spark.SparkContext$$anonfun$stop$6.apply$mcV$sp(SparkContext.scala:2026)
    at org.apache.spark.util.Utils$.tryLogNonFatalError(Utils.scala:1343)
    at org.apache.spark.SparkContext.stop(SparkContext.scala:2025)
    at org.apache.spark.TaskFailedListener$$anon$1$$anonfun$run$1.apply$mcV$sp(SparkParallelismTracker.scala:131)
    at org.apache.spark.TaskFailedListener$$anon$1$$anonfun$run$1.apply(SparkParallelismTracker.scala:131)
    at org.apache.spark.TaskFailedListener$$anon$1$$anonfun$run$1.apply(SparkParallelismTracker.scala:131)
    at scala.util.DynamicVariable.withValue(DynamicVariable.scala:58)
    at org.apache.spark.TaskFailedListener$$anon$1.run(SparkParallelismTracker.scala:130)
    at org.apache.spark.scheduler.DAGScheduler.runJob(DAGScheduler.scala:748)
    at org.apache.spark.SparkContext.runJob(SparkContext.scala:2174)
    at org.apache.spark.SparkContext.runJob(SparkContext.scala:2195)
    at org.apache.spark.SparkContext.runJob(SparkContext.scala:2214)
    at org.apache.spark.SparkContext.runJob(SparkContext.scala:2239)
    at org.apache.spark.rdd.RDD$$anonfun$foreachPartition$1.apply(RDD.scala:941)
    at org.apache.spark.rdd.RDD$$anonfun$foreachPartition$1.apply(RDD.scala:939)
    at org.apache.spark.rdd.RDDOperationScope$.withScope(RDDOperationScope.scala:151)
    at org.apache.spark.rdd.RDDOperationScope$.withScope(RDDOperationScope.scala:112)
    at org.apache.spark.rdd.RDD.withScope(RDD.scala:369)
    at org.apache.spark.rdd.RDD.foreachPartition(RDD.scala:939)
    at ml.dmlc.xgboost4j.scala.spark.XGBoost$$anonfun$trainDistributed$2$$anon$1.run(XGBoost.scala:452)
20/04/09 12:00:34 [Thread-41] INFO RabitTracker$TrackerProcessLogger: Tracker Process ends with exit code 143
20/04/09 12:00:34 [main] INFO RabitTracker: Tracker Process ends with exit code 143
20/04/09 12:00:34 [main] INFO XGBoostSpark: Rabit returns with exit code 143
Exception in thread "main" ml.dmlc.xgboost4j.java.XGBoostError: XGBoostModel training failed
    at ml.dmlc.xgboost4j.scala.spark.XGBoost$.ml$dmlc$xgboost4j$scala$spark$XGBoost$$postTrackerReturnProcessing(XGBoost.scala:582)
    at ml.dmlc.xgboost4j.scala.spark.XGBoost$$anonfun$trainDistributed$2.apply(XGBoost.scala:459)
    at ml.dmlc.xgboost4j.scala.spark.XGBoost$$anonfun$trainDistributed$2.apply(XGBoost.scala:435)
    at scala.collection.TraversableLike$$anonfun$map$1.apply(TraversableLike.scala:234)
    at scala.collection.TraversableLike$$anonfun$map$1.apply(TraversableLike.scala:234)
    at scala.collection.immutable.List.foreach(List.scala:392)
    at scala.collection.TraversableLike$class.map(TraversableLike.scala:234)
    at scala.collection.immutable.List.map(List.scala:296)
    at ml.dmlc.xgboost4j.scala.spark.XGBoost$.trainDistributed(XGBoost.scala:434)
    at ml.dmlc.xgboost4j.scala.spark.XGBoostClassifier.train(XGBoostClassifier.scala:194)
    at ml.dmlc.xgboost4j.scala.spark.XGBoostClassifier.train(XGBoostClassifier.scala:44)
    at org.apache.spark.ml.Predictor.fit(Predictor.scala:118)
    at com.jd.ad.datamill.algorithms.user_coupon_xg.XGBoostTrainer$.trainXGBoost(XGBoostTrainer.scala:51)
    at com.jd.ad.datamill.algorithms.user_coupon_xg.XGBoostTrainer$.main(XGBoostTrainer.scala:235)
    at com.jd.ad.datamill.algorithms.user_coupon_xg.XGBoostTrainer.main(XGBoostTrainer.scala)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
    at java.lang.reflect.Method.invoke(Method.java:498)
    at org.apache.spark.deploy.JavaMainApplication.start(SparkApplication.scala:52)
    at org.apache.spark.deploy.SparkSubmit.org$apache$spark$deploy$SparkSubmit$$runMain(SparkSubmit.scala:928)
    at org.apache.spark.deploy.SparkSubmit.doRunMain$1(SparkSubmit.scala:172)
    at org.apache.spark.deploy.SparkSubmit.submit(SparkSubmit.scala:200)
    at org.apache.spark.deploy.SparkSubmit.doSubmit(SparkSubmit.scala:91)
    at org.apache.spark.deploy.SparkSubmit$$anon$2.doSubmit(SparkSubmit.scala:1003)
    at org.apache.spark.deploy.SparkSubmit$.main(SparkSubmit.scala:1013)
    at org.apache.spark.deploy.SparkSubmit.main(SparkSubmit.scala)
```

**Comment by hcho3** [comment]
It looks like the error has nothing to do with XGBoost. Can you try running another Spark application?
