### ISSUE TITLE
UnsatisfiedLinkError after building 1.0.2 for Windows 10 x64

### ISSUE THREAD

**Issue by Habitats** [dmlc/xgboost#5547]
I've built xgboost 1.0.2 for Windows 10 x64 using `cmake version 3.17.1` and `Visual Studio 2019 Version 16.5.4` using the following commands
```
cmake .. -G"Visual Studio 16 2019" -A x64
cmake --build . --config Release
```
and added the `xgboost4j.dll` (cmake made a `xgboost.dll` which I renamed) to the `jar`, but when I run my program I get the following error
```
Exception in thread "main" java.lang.reflect.InvocationTargetException
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at com.intellij.rt.execution.CommandLineWrapper.main(CommandLineWrapper.java:64)
Caused by: java.lang.UnsatisfiedLinkError: ml.dmlc.xgboost4j.java.XGBoostJNI.XGDMatrixCreateFromDataIter(Ljava/util/Iterator;Ljava/lang/String;[J)I
	at ml.dmlc.xgboost4j.java.XGBoostJNI.XGDMatrixCreateFromDataIter(Native Method)
	at ml.dmlc.xgboost4j.java.DMatrix.<init>(DMatrix.java:54)
	at ml.dmlc.xgboost4j.scala.DMatrix.<init>(DMatrix.scala:42)
        ...
```

The Jar is built for Scala 2.11, and it runs without issues on Linux with the `libxgboost4j.so`:
```
[INFO]                                                                                                                                                         
[INFO] --- scalatest-maven-plugin:1.0:test (test) @ xgboost4j-spark_2.11 ---                                                                                   
[INFO] Tests are skipped.                                                                                                                                      
[INFO]                                                                                                                                                         
[INFO] --- maven-jar-plugin:2.4:jar (default-jar) @ xgboost4j-spark_2.11 ---                                                                                   
[INFO] Building jar: /xgboost/jvm-packages/xgboost4j-spark/target/xgboost4j-spark_2.11-1.0.2.jar                                                               
[INFO] ------------------------------------------------------------------------                                                                                
[INFO] Reactor Summary for XGBoost JVM Package 1.0.2:                                                                                                          
[INFO]                                                                                                                                                         
[INFO] XGBoost JVM Package ................................ SUCCESS [ 10.862 s]                                                                                
[INFO] xgboost4j_2.11 ..................................... SUCCESS [07:32 min]                                                                                
[INFO] xgboost4j-spark_2.11 ............................... SUCCESS [02:09 min]                                                                                
[INFO] ------------------------------------------------------------------------                                                                                
[INFO] BUILD SUCCESS                                                                                                                                           
[INFO] ------------------------------------------------------------------------                                                                                
[INFO] Total time:  09:52 min                                                                                                                                  
[INFO] Finished at: 2020-04-16T06:57:55Z                                                                                                                       
[INFO] ------------------------------------------------------------------------            
```

Not sure what to make of that.

**Comment by hcho3** [comment]
You should add `-DJVM_BINDINGS=ON` when invoking cmake. This will give you xgboost4j.dll.

**Comment by Habitats** [comment]
That did actually work! Did I miss this in the docs? 🤔 I tried to follow this one: https://xgboost.readthedocs.io/en/latest/

**Comment by trivialfis** [comment]
For JVM package, running mvn command should be the only way to build the whole package as it also configures cmake flags.

**Comment by Habitats** [comment]
How could I go on about doing that @trivialfis ?

I need to build everything for Windows + Linux, and the way I'm doing it now is I'm building the jar+linux library in the provided Docker image, then manually building the Windows part, and injecting it into the linux-jar afterwards.

Is there a single command I could run to do all of this?

**Comment by trivialfis** [comment]
@Habitats I'm no expert on JAVA side.  Maybe @hcho3 can help, he published the maven packages recently. ;-)

**Comment by hcho3** [comment]
@Habitats Your use case is not documented in https://xgboost.readthedocs.io/en/latest/. You should do what you did:
1. Run `mvn package` on Linux and obtain a JAR file
2. Run `cmake -DJVM_BINDINGS=ON` on Windows to get `xgboost4j.dll`.
3. Add `xgboost4j.dll` into the JAR file.
