### ISSUE TITLE
java.lang.NoClassDefFoundError: scala/Product$class 	at ml.dmlc.xgboost4j.scala.spark.TrackerConf

### ISSUE THREAD

**Issue by liuandy-good** [dmlc/xgboost#5731]
Hi guys
I am trying the xgboost example with the instructions on https://github.com/rapidsai/spark-examples/blob/master/getting-started-guides/on-prem-cluster/standalone-python.md

get an error : **java.lang.NoClassDefFoundError: scala/Product$class** 
can anyone help on that? great thanks 

detail is below: 

Welcome to
      ____              __
     / __/__  ___ _____/ /__
    _\ \/ _ \/ _ `/ __/  '_/
   /___/ .__/\_,_/_/ /_/\_\   version 3.0.0-preview2
      /_/
         
Using Scala version 2.12.10 (OpenJDK 64-Bit Server VM, Java 1.8.0_252)
Type in expressions to have them evaluated.
Type :help for more information.

File "/home/ubuntu/xgboost4j_spark/libs/ai/rapids/spark/examples/main.py", line 21, in main
    getattr(import_module(args.mainClass), 'main')(args, xgboost_args)
  File "/home/ubuntu/xgboost4j_spark/libs/ai/rapids/spark/examples/mortgage/gpu_main.py", line 39, in main
    classifier = (XGBoostClassifier(**merge_dicts(default_params, xgboost_args))
  File "/home/ubuntu/spark3.0/python/lib/pyspark.zip/pyspark/__init__.py", line 111, in wrapper
  File "/home/ubuntu/xgboost4j_spark/libs/xgboost4j-spark_2.x-1.0.0-Beta5.jar/sparkxgb/xgboost.py", line 85, in __init__
  File "/home/ubuntu/xgboost4j_spark/libs/xgboost4j-spark_2.x-1.0.0-Beta5.jar/sparkxgb/common.py", line 69, in __init__
  File "/home/ubuntu/spark3.0/python/lib/pyspark.zip/pyspark/ml/wrapper.py", line 69, in _new_java_obj
  File "/home/ubuntu/spark3.0/python/lib/py4j-0.10.8.1-src.zip/py4j/java_gateway.py", line 1554, in __call__
  File "/home/ubuntu/spark3.0/python/lib/pyspark.zip/pyspark/sql/utils.py", line 98, in deco
  File "/home/ubuntu/spark3.0/python/lib/py4j-0.10.8.1-src.zip/py4j/protocol.py", line 328, in get_return_value
py4j.protocol.Py4JJavaError: An error occurred while calling None.ml.dmlc.xgboost4j.scala.spark.XGBoostClassifier.
: **java.lang.NoClassDefFoundError: scala/Product$class**
	at ml.dmlc.xgboost4j.scala.spark.TrackerConf.<init>(XGBoost.scala:55)
	at ml.dmlc.xgboost4j.scala.spark.TrackerConf$.apply(XGBoost.scala:58)
	at ml.dmlc.xgboost4j.scala.spark.params.GeneralParams$class.$init$(GeneralParams.scala:187)
	at ml.dmlc.xgboost4j.scala.spark.XGBoostClassifier.<init>(XGBoostClassifier.scala:52)
	at ml.dmlc.xgboost4j.scala.spark.XGBoostClassifier.<init>(XGBoostClassifier.scala:57)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
	at py4j.reflection.MethodInvoker.invoke(MethodInvoker.java:247)
	at py4j.reflection.ReflectionEngine.invoke(ReflectionEngine.java:357)
	at py4j.Gateway.invoke(Gateway.java:238)
	at py4j.commands.ConstructorCommand.invokeConstructor(ConstructorCommand.java:80)
	at py4j.commands.ConstructorCommand.execute(ConstructorCommand.java:69)
	at py4j.GatewayConnection.run(GatewayConnection.java:238)
	at java.lang.Thread.run(Thread.java:748)
**Caused by: java.lang.ClassNotFoundException: scala.Product$class**
	at java.net.URLClassLoader.findClass(URLClassLoader.java:382)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:418)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:351)
	... 16 more

**Comment by hcho3** [comment]
> version 3.0.0-preview2

We do not support Spark 3.0.0. Please use Spark 2.4.3.

**Comment by DTW1004** [comment]
> 

hello ，can it support pyspark3.1.2 now? which version xgboost4j.jar  should I choice?

**Comment by DTW1004** [comment]
> 

hello ，can it support pyspark3.1.2 now? which version xgboost4j.jar  should I choice?
