### ISSUE TITLE
An error occurred while calling o238.fit. : java.lang.IllegalStateException: SparkContext has been shutdown

### ISSUE THREAD

**Issue by rosefun** [dmlc/xgboost#5885]
My spark version is 2.3.2. I want to train a binary-classification XGBoostClassifier.
```
 assembler = VectorAssembler(inputCols=data_col, outputCol='features')
stringIndexer = StringIndexer(inputCol=label, outputCol="label")
xgboost = XGBoostClassifier(
    featuresCol="features",
    labelCol="label",
    predictionCol="prediction",
    missing=0.0
)
pipeline = Pipeline(stages=[assembler, stringIndexer, xgboost])
model = pipeline.fit(trainDF)
```

Error:

```
  File "/mnt/hadoop/yarn/local/usercache/hdfs/appcache/application_/container_1586930647033_6364_05_000001/pyspark.zip/pyspark/ml/base.py", line 132, in fit
  File "/mnt/hadoop/yarn/local/usercache/hdfs/appcache/application/container_1586930647033_6364_05_000001/pyspark.zip/pyspark/ml/pipeline.py", line 109, in _fit
  File "/mnt/hadoop/yarn/local/usercache/hdfs/appcache/application/container_1586930647033_6364_05_000001/pyspark.zip/pyspark/ml/base.py", line 132, in fit
  File "/mnt/hadoop/yarn/local/usercache/hdfs/appcache/application/container_1586930647033_6364_05_000001/pyspark.zip/pyspark/ml/wrapper.py", line 288, in _fit
  File "/mnt/hadoop/yarn/local/usercache/hdfs/appcache/application_/container_1586930647033_6364_05_000001/pyspark.zip/pyspark/ml/wrapper.py", line 285, in _fit_java
  File "/mnt/hadoop/yarn/local/usercache/hdfs/appcache/application/container_1586930647033_6364_05_000001/py4j-0.10.7-src.zip/py4j/java_gateway.py", line 1257, in __call__
  File "/mnt/hadoop/yarn/local/usercache/hdfs/appcache/application/container_1586930647033_6364_05_000001/pyspark.zip/pyspark/sql/utils.py", line 63, in deco
  File "/mnt/hadoop/yarn/local/usercache/hdfs/appcache/application/container_1586930647033_6364_05_000001/py4j-0.10.7-src.zip/py4j/protocol.py", line 328, in get_return_value
py4j.protocol.Py4JJavaError: An error occurred while calling o238.fit.
: java.lang.IllegalStateException: SparkContext has been shutdown
	at org.apache.spark.SparkContext.runJob(SparkContext.scala:2026)
	at org.apache.spark.SparkContext.runJob(SparkContext.scala:2055)
	at org.apache.spark.SparkContext.runJob(SparkContext.scala:2074)
	at org.apache.spark.rdd.RDD$$anonfun$take$1.apply(RDD.scala:1364)
	at org.apache.spark.rdd.RDDOperationScope$.withScope(RDDOperationScope.scala:151)
	at org.apache.spark.rdd.RDDOperationScope$.withScope(RDDOperationScope.scala:112)
	at org.apache.spark.rdd.RDD.withScope(RDD.scala:363)
	at org.apache.spark.rdd.RDD.take(RDD.scala:1337)
	at org.apache.spark.rdd.RDD$$anonfun$first$1.apply(RDD.scala:1378)
	at org.apache.spark.rdd.RDDOperationScope$.withScope(RDDOperationScope.scala:151)
	at org.apache.spark.rdd.RDDOperationScope$.withScope(RDDOperationScope.scala:112)
	at org.apache.spark.rdd.RDD.withScope(RDD.scala:363)
	at org.apache.spark.rdd.RDD.first(RDD.scala:1377)
	at ml.dmlc.xgboost4j.scala.spark.XGBoost$.ml$dmlc$xgboost4j$scala$spark$XGBoost$$postTrackerReturnProcessing(XGBoost.scala:570)
	at ml.dmlc.xgboost4j.scala.spark.XGBoost$$anonfun$trainDistributed$2.apply(XGBoost.scala:459)
	at ml.dmlc.xgboost4j.scala.spark.XGBoost$$anonfun$trainDistributed$2.apply(XGBoost.scala:435)
	at scala.collection.TraversableLike$$anonfun$map$1.apply(TraversableLike.scala:234)
	at scala.collection.TraversableLike$$anonfun$map$1.apply(TraversableLike.scala:234)
	at scala.collection.immutable.List.foreach(List.scala:381)
	at scala.collection.TraversableLike$class.map(TraversableLike.scala:234)
	at scala.collection.immutable.List.map(List.scala:285)
	at ml.dmlc.xgboost4j.scala.spark.XGBoost$.trainDistributed(XGBoost.scala:434)
	at ml.dmlc.xgboost4j.scala.spark.XGBoostClassifier.train(XGBoostClassifier.scala:194)
	at ml.dmlc.xgboost4j.scala.spark.XGBoostClassifier.train(XGBoostClassifier.scala:44)
	at org.apache.spark.ml.Predictor.fit(Predictor.scala:118)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at py4j.reflection.MethodInvoker.invoke(MethodInvoker.java:244)
	at py4j.reflection.ReflectionEngine.invoke(ReflectionEngine.java:357)
	at py4j.Gateway.invoke(Gateway.java:282)
	at py4j.commands.AbstractCommand.invokeMethod(AbstractCommand.java:132)
	at py4j.commands.CallCommand.execute(CallCommand.java:79)
	at py4j.GatewayConnection.run(GatewayConnection.java:238)
	at java.lang.Thread.run(Thread.java:748)

```

**Comment by thvasilo** [comment]
Hello @rosefun I guess you're trying to run distributed training, but doing it locally?

This is not a solution to your problem but what is your data size? If you run XGBoost on a single node, why not create a csv/libscm output and train using the local version on that?

**Comment by hcho3** [comment]
I don't think this project officially supports PySpark / Py4J. There is an ongoing PR #5658 to add PySpark API.
