### ISSUE TITLE
building issue visual studio maven plugin

### ISSUE THREAD

**Issue by Moisessalazar77** [dmlc/xgboost#5912]
Hello, the issue stem because I'm building with visual studio 2019 but the maven plugin is looking for for visual studio 2015. to make matter worse, my computer is x64 which require a lot of patches for vs2015. Any help will be appreciated. the build for vs2019 works find, I tested with a python virtualenv

CMake Error: Error: generator : Visual Studio 14 2015 Win64
Does not match the generator used previously: Visual Studio 16 2019
Either remove the CMakeCache.txt file and CMakeFiles directory or choose a different binary directory.
building Java wrapper
cd ..
Traceback (most recent call last):
  File "create_jni.py", line 92, in <module>
    run("cmake .. " + " ".join(args) + maybe_generator)
  File "create_jni.py", line 51, in run
    subprocess.check_call(command, shell=True, **kwargs)
  File "C:\python37\lib\subprocess.py", line 363, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command 'cmake .. -DUSE_OPENMP:BOOL=ON -DUSE_HDFS:BOOL=OFF -DUSE_AZURE:BOOL=OFF -DUSE_S3:BOOL=OFF -DUSE_CUDA:BOOL=OFF -DJVM_BINDINGS:BOOL=ON -G"Visual Studio 14 Win64"' returned non-zero exit status 1.
mkdir -p build
cd build
cmake .. -DUSE_OPENMP:BOOL=ON -DUSE_HDFS:BOOL=OFF -DUSE_AZURE:BOOL=OFF -DUSE_S3:BOOL=OFF -DUSE_CUDA:BOOL=OFF -DJVM_BINDINGS:BOOL=ON -G"Visual Studio 14 Win64"
[ERROR] Command execution failed.
org.apache.commons.exec.ExecuteException: Process exited with an error: 1 (Exit value: 1)
    at org.apache.commons.exec.DefaultExecutor.executeInternal (DefaultExecutor.java:404)
    at org.apache.commons.exec.DefaultExecutor.execute (DefaultExecutor.java:166)
    at org.codehaus.mojo.exec.ExecMojo.executeCommandLine (ExecMojo.java:982)
    at org.codehaus.mojo.exec.ExecMojo.executeCommandLine (ExecMojo.java:929)
    at org.codehaus.mojo.exec.ExecMojo.execute (ExecMojo.java:457)
    at org.apache.maven.plugin.DefaultBuildPluginManager.executeMojo (DefaultBuildPluginManager.java:137)
    at org.apache.maven.lifecycle.internal.MojoExecutor.execute (MojoExecutor.java:210)
    at org.apache.maven.lifecycle.internal.MojoExecutor.execute (MojoExecutor.java:156)
    at org.apache.maven.lifecycle.internal.MojoExecutor.execute (MojoExecutor.java:148)
    at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject (LifecycleModuleBuilder.java:117)
    at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject (LifecycleModuleBuilder.java:81)
    at org.apache.maven.lifecycle.internal.builder.singlethreaded.SingleThreadedBuilder.build (SingleThreadedBuilder.java:56)
    at org.apache.maven.lifecycle.internal.LifecycleStarter.execute (LifecycleStarter.java:128)
    at org.apache.maven.DefaultMaven.doExecute (DefaultMaven.java:305)
    at org.apache.maven.DefaultMaven.doExecute (DefaultMaven.java:192)
    at org.apache.maven.DefaultMaven.execute (DefaultMaven.java:105)
    at org.apache.maven.cli.MavenCli.execute (MavenCli.java:957)
    at org.apache.maven.cli.MavenCli.doMain (MavenCli.java:289)
    at org.apache.maven.cli.MavenCli.main (MavenCli.java:193)
    at sun.reflect.NativeMethodAccessorImpl.invoke0 (Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke (NativeMethodAccessorImpl.java:62)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke (DelegatingMethodAccessorImpl.java:43)
    at java.lang.reflect.Method.invoke (Method.java:498)
    at org.codehaus.plexus.classworlds.launcher.Launcher.launchEnhanced (Launcher.java:282)
    at org.codehaus.plexus.classworlds.launcher.Launcher.launch (Launcher.java:225)
    at org.codehaus.plexus.classworlds.launcher.Launcher.mainWithExitCode (Launcher.java:406)
    at org.codehaus.plexus.classworlds.launcher.Launcher.main (Launcher.java:347)

**Comment by trivialfis** [comment]
I fixed it on master branch, but it requires spark 3.0.  @hcho3 Can we back port that fix?

**Comment by trivialfis** [comment]
On a second thought, I assume you are not using spark as distributed training doesn't work on Windows.  Please pull in the latest master branch for the fix.  Feel free to reopen if there's any further issue.

**Comment by Moisessalazar77** [comment]
I did pull the latest snapshot 1.2.0 and it didn't work, did the build for 0.90 and the same issue appear. I using as a standalone system to concept proof code before developing. I'm using spark 2.4.0 and the latest maven version

**Comment by trivialfis** [comment]
I meant pulling in latest XGBoost from github repository and build it from source by running mvn in `jvm-packages` directory.  :-)

**Comment by trivialfis** [comment]
During which, you should clear the build directory by running git clean -xdf.

**Comment by Moisessalazar77** [comment]
which I did yesterday

**Comment by trivialfis** [comment]
Few seconds late, see above comment.  :-)

**Comment by trivialfis** [comment]
Let us know how does it go.

**Comment by Moisessalazar77** [comment]
thanks

**Comment by Moisessalazar77** [comment]
Nothing same issue. I'm following all the instructions to the letter

**Comment by Moisessalazar77** [comment]
No more possible solutions?

**Comment by trivialfis** [comment]
Could you please paste the new log?

**Comment by trivialfis** [comment]
```
CMake Error: Error: generator : Visual Studio 14 2015 Win64
Does not match the generator used previously: Visual Studio 16 2019
Either remove the CMakeCache.txt file and CMakeFiles directory or choose a different binary directory.
building Java wrapper
cd ..
Traceback (most recent call last):
```

Means you have a dirty build directory

**Comment by Moisessalazar77** [comment]
[INFO] --- exec-maven-plugin:1.6.0:exec (native) @ xgboost4j_2.12 ---
-- Selecting Windows SDK version  to target Windows 10.0.18362.
CMake Error at CMakeLists.txt:2 (project):
  Failed to run MSBuild command:

    MSBuild.exe


  to get the value of VCTargetsPath:

    The system cannot find the file specified



-- Configuring incomplete, errors occurred!
See also "C:/xgboost/build/CMakeFiles/CMakeOutput.log".
building Java wrapper
cd ..
mkdir -p build
cd build
cmake .. -DUSE_OPENMP:BOOL=ON -DUSE_HDFS:BOOL=OFF -DUSE_AZURE:BOOL=OFF -DUSE_S3:BOOL=OFF -DUSE_CUDA:BOOL=OFF -DJVM_BINDINGS:BOOL=ON -G"Visual Studio 14 Win64"
Traceback (most recent call last):
  File "create_jni.py", line 97, in <module>
    run("cmake .. " + " ".join(args) + maybe_generator)
  File "create_jni.py", line 51, in run
    subprocess.check_call(command, shell=True, **kwargs)
  File "C:\python37\lib\subprocess.py", line 363, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command 'cmake .. -DUSE_OPENMP:BOOL=ON -DUSE_HDFS:BOOL=OFF -DUSE_AZURE:BOOL=OFF -DUSE_S3:BOOL=OFF -DUSE_CUDA:BOOL=OFF -DJVM_BINDINGS:BOOL=ON -G"Visual Studio 14 Win64"' returned non-zero exit status 1.
[ERROR] Command execution failed.

**Comment by trivialfis** [comment]
I think your source tree doesn't include the fix. #5902

**Comment by Moisessalazar77** [comment]
I will pull and start everything again, let you know

**Comment by Moisessalazar77** [comment]
I managed to build the packages. Thanks

**Comment by trivialfis** [comment]
Good to know.  Thanks!

**Comment by Moisessalazar77** [comment]
can you please check this issue  https://github.com/dmlc/xgboost/issues/5916
