### ISSUE TITLE
Make json configuration locale-independent 

### ISSUE THREAD

**Issue by sh1ng** [dmlc/xgboost#5933]
Custom json serialization like  https://github.com/dmlc/xgboost/blob/970b4b3fa2001e389910d3f6fe2af0a2966c3bd7/src/learner.cc#L102 
is fragile 

```
import locale
import xgboost
import numpy as np
locale.setlocale(locale.LC_ALL, 'sk_SK')
model = xgboost.XGBClassifier(booster='gblinear')
X = np.random.rand(100,10)
y = np.random.rand(100) > 0.5
model.fit(X, y)
print(model)
print(model.get_booster().save_config())
model.fit(X, y)
```

```
XGBClassifier(base_score='0,500000', booster='gblinear', colsample_bylevel=None,
              colsample_bynode=None, colsample_bytree=None, gamma=None,
              gpu_id=-1, importance_type='gain', interaction_constraints=None,
              learning_rate=0.5, max_delta_step=None, max_depth=None,
              min_child_weight=None, missing=nan, monotone_constraints=None,
              n_estimators=100, n_jobs=0, num_parallel_tree=None,
              objective='binary:logistic', random_state=0, reg_alpha=0,
              reg_lambda=0, scale_pos_weight=1, subsample=None,
              tree_method=None, validate_parameters=1, verbosity=None)
{"learner":{"generic_param":{"enable_experimental_json_serialization":"0","gpu_id":"-1","gpu_page_size":"0","n_gpus":"0","n_jobs":"0","nthread":"0","random_state":"0","seed":"0","seed_per_iteration":"0","validate_parameters":"1"},"gradient_booster":{"gblinear_train_param":{"max_row_perbatch":"18446744073709551615","tolerance":"0","updater":"shotgun"},"name":"gblinear","updater":{"linear_train_param":{"alpha":"0","eta":"0.5","feature_selector":"cyclic","lambda":"0","learning_rate":"0.5","reg_alpha":"0","reg_lambda":"0"}}},"learner_model_param":{"base_score":"0,500000","num_class":"0","num_feature":"10"},"learner_train_param":{"booster":"gblinear","disable_default_eval_metric":"0","dsplit":"auto","objective":"binary:logistic"},"metrics":[],"objective":{"name":"binary:logistic","reg_loss_param":{"scale_pos_weight":"1"}}},"version":[1,1,1]}
Traceback (most recent call last):
  File "ab375d69-e91a-4c07-b83b-96afdaa201cc_afterxgbobj.dat.py", line 13, in <module>
    model.fit(X, y)
  File "/home/sh1ng/dev/h2oai_env/lib/python3.6/site-packages/xgboost/sklearn.py", line 824, in fit
    callbacks=callbacks)
  File "/home/sh1ng/dev/h2oai_env/lib/python3.6/site-packages/xgboost/training.py", line 212, in train
    xgb_model=xgb_model, callbacks=callbacks)
  File "/home/sh1ng/dev/h2oai_env/lib/python3.6/site-packages/xgboost/training.py", line 75, in _train_internal
    bst.update(dtrain, i, obj)
  File "/home/sh1ng/dev/h2oai_env/lib/python3.6/site-packages/xgboost/core.py", line 1369, in update
    dtrain.handle))
  File "/home/sh1ng/dev/h2oai_env/lib/python3.6/site-packages/xgboost/core.py", line 190, in _check_call
    raise XGBoostError(py_str(_LIB.XGBGetLastError()))
xgboost.core.XGBoostError: Some trailing characters could not be parsed: ',500000'
```

The problem is `base_score` value set to `0,500000`

I'd recommend to use well tested third party component for json, although it may look simple at the first glance it's quite challenging to implement it properly.

**Comment by trivialfis** [comment]
That's a bug for this parameter.

**Comment by trivialfis** [comment]
Will remove this specialization.

**Comment by hcho3** [comment]
> I'd recommend to use well tested third party component for json, although it may look simple at the first glance it's quite challenging to implement it properly.

We had extensive discussion in https://github.com/dmlc/xgboost/issues/3980 about the use of a third-party library. We decided against it, as it greatly complicates building XGBoost for various platforms and targets.
