### ISSUE TITLE
Use xgboost4j-spark 1.1.1 to run inference with model trained in python xgboost 0.90

### ISSUE THREAD

**Issue by qinglong1230** [dmlc/xgboost#6184]
```
Exception in thread "Executor task launch worker for task 20304" Exception in thread "Executor task launch worker for task 20305" java.lang.NoSuchMethodError: ml.dmlc.xgboost4j.LabeledPoint$.apply$default$5()F
	at ml.dmlc.xgboost4j.scala.spark.DataUtils$MLVectorToXGBLabeledPoint$.asXGB$extension(DataUtils.scala:69)
	at ml.dmlc.xgboost4j.scala.spark.XGBoostClassificationModel$$anonfun$6$$anon$1$$anonfun$7$$anonfun$9.apply(XGBoostClassifier.scala:322)
	at ml.dmlc.xgboost4j.scala.spark.XGBoostClassificationModel$$anonfun$6$$anon$1$$anonfun$7$$anonfun$9.apply(XGBoostClassifier.scala:322)
	at scala.collection.Iterator$$anon$11.next(Iterator.scala:409)
	at scala.collection.Iterator$$anon$11.next(Iterator.scala:409)
	at scala.collection.Iterator$$anon$11.next(Iterator.scala:409)
	at scala.collection.convert.Wrappers$IteratorWrapper.next(Wrappers.scala:31)
	at ml.dmlc.xgboost4j.java.DataBatch$BatchIterator.next(DataBatch.java:56)
	at ml.dmlc.xgboost4j.java.DataBatch$BatchIterator.next(DataBatch.java:36)
	at ml.dmlc.xgboost4j.java.XGBoostJNI.XGDMatrixCreateFromDataIter(Native Method)
	at ml.dmlc.xgboost4j.java.DMatrix.<init>(DMatrix.java:53)
	at ml.dmlc.xgboost4j.scala.DMatrix.<init>(DMatrix.scala:42)
	at ml.dmlc.xgboost4j.scala.spark.XGBoostClassificationModel$$anonfun$6$$anon$1$$anonfun$7.apply(XGBoostClassifier.scala:320)
	at ml.dmlc.xgboost4j.scala.spark.XGBoostClassificationModel$$anonfun$6$$anon$1$$anonfun$7.apply(XGBoostClassifier.scala:300)
	at scala.collection.Iterator$$anon$12.nextCur(Iterator.scala:434)
	at scala.collection.Iterator$$anon$12.hasNext(Iterator.scala:440)
	at ml.dmlc.xgboost4j.scala.spark.XGBoostClassificationModel$$anonfun$6$$anon$1.hasNext(XGBoostClassifier.scala:338)
	at scala.collection.Iterator$$anon$11.hasNext(Iterator.scala:408)
	at scala.collection.Iterator$$anon$11.hasNext(Iterator.scala:408)
	at org.apache.spark.sql.catalyst.expressions.GeneratedClass$GeneratedIterator.processNext(Unknown Source)
	at org.apache.spark.sql.execution.BufferedRowIterator.hasNext(BufferedRowIterator.java:43)
	at org.apache.spark.sql.execution.WholeStageCodegenExec$$anonfun$8$$anon$1.hasNext(WholeStageCodegenExec.scala:395)
	at scala.collection.Iterator$$anon$11.hasNext(Iterator.scala:408)
	at org.apache.spark.shuffle.sort.BypassMergeSortShuffleWriter.write(BypassMergeSortShuffleWriter.java:125)
	at org.apache.spark.scheduler.ShuffleMapTask.runTask(ShuffleMapTask.scala:96)
	at org.apache.spark.scheduler.ShuffleMapTask.runTask(ShuffleMapTask.scala:53)
	at org.apache.spark.scheduler.Task.run(Task.scala:108)
	at org.apache.spark.executor.Executor$TaskRunner.run(Executor.scala:338)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
```
We used to be able to use xgboost4j-spark 0.72 to run inference on spark with model trained in python xgboost 0.90. After upgrading xgboost4j and xgboost4j-spark to 1.1.1, we started to see issues above. Any ideas about how to fix the issue?

**Comment by hcho3** [comment]
@qinglong1230 How did you persist your XGBoost model? Depending on how you persisted the model, you may have issue with Scala version. XGBoost4J-Spark 0.90 used Scala 2.11 exclusively, whereas XGBoost4J-Spark 1.1.1 supports both Scala 2.11 and 2.12. Are you using Scala 2.12 artifact of XGBoost4J-Spark 1.1.1?

**Comment by qinglong1230** [comment]
I'm using scala 2.11 version which is my scala version. The model was trained and saved in python. I upload the model to s3 and use a bridge class like this: https://github.com/CodingCat/XGBoostExperiments/blob/master/xgboost_exp_0.80/src/main/scala/ml/dmlc/xgboost4j/scala/spark/XGBoostClassificationModelBridge.scala to load the model.

**Comment by hcho3** [comment]
So the issue is really that the bridge class is no longer functional in the new version?

**Comment by qinglong1230** [comment]
Not sure if that's the issue. We are using 0.72 which does not require a bridge class. But I also tested the bridge class in 0.90 and it works.

**Comment by hcho3** [comment]
I'm out of ideas, unfortunately. Not quite familiar with JVM ecosystem. Feel free to share if you happen to find a fix.

**Comment by qinglong1230** [comment]
Just tested it with 1.0.0. It seems the same code still works with xgboost4j 1.0.0 and xgboost4j-spark 1.0.0

**Comment by trivialfis** [comment]
Spark package has its own way of handling model.  We don't have any tests for their compatibility.
