### ISSUE TITLE
segmentation fault when using gblinear on GPU with cudf

### ISSUE THREAD

**Issue by pseudotensor** [dmlc/xgboost#6235]
Same specs/setup as here: https://github.com/dmlc/xgboost/issues/6232

```
import cudf
import pynvml
import numpy as np
import pandas as pd
import xgboost as xgb
from math import sqrt
from sklearn.model_selection import KFold, StratifiedKFold, GroupKFold
from sklearn.metrics import mean_squared_error,f1_score, accuracy_score
train = cudf.read_csv("creditcard.csv")
test = cudf.read_csv("creditcard.csv")
y = train['default payment next month']
train = train.drop(['default payment next month'], axis=1)
test = test.drop(['default payment next month'], axis=1)
from cuml import train_test_split
X_train, X_test, y_train, y_test = train_test_split(train, y, test_size=0.2, random_state=123)

params = {'learning_rate': 0.01, 'colsample_bytree' : 0.25, 'max_depth': 10, 'silent': True, 'booster': 'gblinear', 'updater': 'gpu_coord_descent', 'coordinate_selection': 'cyclic', 'tolerance': 1E-4, 'reg_lambda': 1E-3, 'reg_alpha': 5E-4, 'n_estimators': 5000, 'verbose_eval': 250}
model = xgb.XGBRegressor(**params)
eval_set = [(X_test, y_test), (X_train, y_train)]
model.fit(X_train, y_train, eval_set=eval_set)
prediction = model.predict(test)
```

fails with segfault (every time run)

Core shows:

```
Program terminated with signal SIGABRT, Aborted.
#0  __GI_raise (sig=sig@entry=6) at ../sysdeps/unix/sysv/linux/raise.c:51
51      ../sysdeps/unix/sysv/linux/raise.c: No such file or directory.
[Current thread is 1 (Thread 0x7f43fc1a9740 (LWP 24874))]
(gdb) bt
#0  __GI_raise (sig=sig@entry=6) at ../sysdeps/unix/sysv/linux/raise.c:51
#1  0x00007f43fb9e08b1 in __GI_abort () at abort.c:79
#2  0x00007f436885c84a in __gnu_cxx::__verbose_terminate_handler () at /home/nwani/m3/conda-bld/compilers_linux-64_1560109574129/work/.build/x86_64-conda_cos6-linux-gnu/src/gcc/libstdc++-v3/libsupc++/vterminate.cc:95
#3  0x00007f436885af47 in __cxxabiv1::__terminate (handler=<optimized out>) at /home/nwani/m3/conda-bld/compilers_linux-64_1560109574129/work/.build/x86_64-conda_cos6-linux-gnu/src/gcc/libstdc++-v3/libsupc++/eh_terminate.cc:47
#4  0x00007f436885af7d in std::terminate () at /home/nwani/m3/conda-bld/compilers_linux-64_1560109574129/work/.build/x86_64-conda_cos6-linux-gnu/src/gcc/libstdc++-v3/libsupc++/eh_terminate.cc:57
#5  0x00007f422d3518c5 in xgboost::common::Span<xgboost::Entry const, 18446744073709551615ul>::Span (this=<optimized out>, _ptr=<optimized out>, _count=<optimized out>) at /root/repo/xgboost/include/xgboost/span.h:421
#6  0x00007f422d3f0ac4 in xgboost::SparsePage::operator[] (i=<optimized out>, this=<optimized out>) at /root/repo/xgboost/include/xgboost/data.h:270
#7  xgboost::gbm::GBLinear::PredictBatchInternal (this=<optimized out>, p_fmat=<optimized out>, out_preds=<optimized out>) at /root/repo/xgboost/src/gbm/gblinear.cc:259
#8  0x00007f43f0c49e8c in GOMP_parallel (fn=0x7f422d3f0960 <_ZN7xgboost3gbm8GBLinear20PredictBatchInternalEPNS_7DMatrixEPSt6vectorIfSaIfEE._omp_fn.1(void)>, data=0x7ffef0f0e7a0, num_threads=2, flags=0)
    at /home/conda/feedstock_root/build_artifacts/ctng-compilers_1601682258120/work/.build/x86_64-conda-linux-gnu/src/gcc/libgomp/parallel.c:171
#9  0x00007f422d3f1dcc in xgboost::gbm::GBLinear::PredictBatchInternal (this=this@entry=0x55bac28107c0, p_fmat=p_fmat@entry=0x55bac8c19f40, out_preds=0x55bac8bf7218) at /root/repo/xgboost/src/gbm/gblinear.cc:251
#10 0x00007f422d3f23ac in xgboost::gbm::GBLinear::PredictBatch (this=0x55bac28107c0, p_fmat=0x55bac8c19f40, predts=0x55bac8b69390, training=<optimized out>, ntree_limit=<optimized out>) at /root/repo/xgboost/src/gbm/gblinear.cc:141
#11 0x00007f422d429aa9 in xgboost::LearnerImpl::PredictRaw (this=0x55bac239cad0, data=0x55bac8c19f40, out_preds=0x55bac8b69390, training=<optimized out>, ntree_limit=0) at /root/repo/xgboost/src/learner.cc:1117
#12 0x00007f422d439248 in xgboost::LearnerImpl::UpdateOneIter (this=0x55bac239cad0, iter=0, train=...) at /root/repo/xgboost/src/learner.cc:984
#13 0x00007f422d332ac4 in XGBoosterUpdateOneIter (handle=0x55bac239cad0, iter=0, dtrain=0x55bac24c2130) at /root/repo/xgboost/src/c_api/c_api.cc:443
#14 0x00007f43fa1b8630 in ffi_call_unix64 () from /home/jon/minicondadai/lib/python3.6/lib-dynload/../../libffi.so.6
#15 0x00007f43fa1b7fed in ffi_call () from /home/jon/minicondadai/lib/python3.6/lib-dynload/../../libffi.so.6
#16 0x00007f43fa1cef9e in _call_function_pointer (argcount=3, resmem=0x7ffef0f0f070, restype=<optimized out>, atypes=0x7ffef0f0f010, avalues=0x7ffef0f0f040, pProc=0x7f422d332a70 <XGBoosterUpdateOneIter(BoosterHandle, int, DMatrixHandle)>, flags=4353)
    at /usr/local/src/conda/python-3.6.10/Modules/_ctypes/callproc.c:831
#17 _ctypes_callproc () at /usr/local/src/conda/python-3.6.10/Modules/_ctypes/callproc.c:1195
#18 0x00007f43fa1cf9d5 in PyCFuncPtr_call () at /usr/local/src/conda/python-3.6.10/Modules/_ctypes/_ctypes.c:3970
#19 0x000055baa10a300b in _PyObject_FastCallDict () at /home/conda/feedstock_root/build_artifacts/python_1587744308058/work/Objects/abstract.c:2331
#20 0x000055baa113179e in call_function () at /home/conda/feedstock_root/build_artifacts/python_1587744308058/work/Python/ceval.c:4875
#21 0x000055baa115418a in _PyEval_EvalFrameDefault () at /home/conda/feedstock_root/build_artifacts/python_1587744308058/work/Python/ceval.c:3335
#22 0x000055baa10ff256 in _PyEval_EvalCodeWithName () at /home/conda/feedstock_root/build_artifacts/python_1587744308058/work/Python/ceval.c:4166
#23 0x000055baa1100231 in fast_function () at /home/conda/feedstock_root/build_artifacts/python_1587744308058/work/Python/ceval.c:4992
#24 0x000055baa1131725 in call_function () at /home/conda/feedstock_root/build_artifacts/python_1587744308058/work/Python/ceval.c:4872
#25 0x000055baa115418a in _PyEval_EvalFrameDefault () at /home/conda/feedstock_root/build_artifacts/python_1587744308058/work/Python/ceval.c:3335
#26 0x000055baa10ff256 in _PyEval_EvalCodeWithName () at /home/conda/feedstock_root/build_artifacts/python_1587744308058/work/Python/ceval.c:4166
#27 0x000055baa1100231 in fast_function () at /home/conda/feedstock_root/build_artifacts/python_1587744308058/work/Python/ceval.c:4992
#28 0x000055baa1131725 in call_function () at /home/conda/feedstock_root/build_artifacts/python_1587744308058/work/Python/ceval.c:4872
#29 0x000055baa1154f46 in _PyEval_EvalFrameDefault () at /home/conda/feedstock_root/build_artifacts/python_1587744308058/work/Python/ceval.c:3351
#30 0x000055baa10ff256 in _PyEval_EvalCodeWithName () at /home/conda/feedstock_root/build_artifacts/python_1587744308058/work/Python/ceval.c:4166
#31 0x000055baa1100231 in fast_function () at /home/conda/feedstock_root/build_artifacts/python_1587744308058/work/Python/ceval.c:4992
#32 0x000055baa1131725 in call_function () at /home/conda/feedstock_root/build_artifacts/python_1587744308058/work/Python/ceval.c:4872
#33 0x000055baa1154f46 in _PyEval_EvalFrameDefault () at /home/conda/feedstock_root/build_artifacts/python_1587744308058/work/Python/ceval.c:3351
#34 0x000055baa10ff68e in _PyEval_EvalCodeWithName () at /home/conda/feedstock_root/build_artifacts/python_1587744308058/work/Python/ceval.c:4166
#35 0x000055baa1100928 in _PyFunction_FastCallDict () at /home/conda/feedstock_root/build_artifacts/python_1587744308058/work/Python/ceval.c:5084
#36 0x000055baa10a31ef in _PyObject_FastCallDict () at /home/conda/feedstock_root/build_artifacts/python_1587744308058/work/Objects/abstract.c:2310
#37 0x000055baa10a7cf3 in _PyObject_Call_Prepend () at /home/conda/feedstock_root/build_artifacts/python_1587744308058/work/Objects/abstract.c:2373
#38 0x000055baa10a2c2e in PyObject_Call () at /home/conda/feedstock_root/build_artifacts/python_1587744308058/work/Objects/abstract.c:2261
#39 0x000055baa1155936 in do_call_core (kwdict=0x7f43f91727e0, callargs=0x7f43f9186608, func=0x7f42c1563dc8) at /home/conda/feedstock_root/build_artifacts/python_1587744308058/work/Python/ceval.c:5120
#40 _PyEval_EvalFrameDefault () at /home/conda/feedstock_root/build_artifacts/python_1587744308058/work/Python/ceval.c:3404

```

while otherwise identical non-cudf GPU way works:

```
import pandas as pd
import pynvml
import numpy as np
import pandas as pd
import xgboost as xgb
from math import sqrt
from sklearn.model_selection import KFold, StratifiedKFold, GroupKFold
from sklearn.metrics import mean_squared_error,f1_score, accuracy_score
train = pd.read_csv("creditcard.csv")
test = pd.read_csv("creditcard.csv")
y = train['default payment next month']
train = train.drop(['default payment next month'], axis=1)
test = test.drop(['default payment next month'], axis=1)
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(train, y, test_size=0.2, random_state=123)

params = {'learning_rate': 0.01, 'colsample_bytree' : 0.25, 'max_depth': 10, 'silent': True, 'booster': 'gblinear', 'updater': 'gpu_coord_descent', 'coordinate_selection': 'cyclic', 'tolerance': 1E-4, 'reg_lambda': 1E-3, 'reg_alpha': 5E-4, 'n_estimators': 5000, 'verbose_eval': 250}
model = xgb.XGBRegressor(**params)
eval_set = [(X_test, y_test), (X_train, y_train)]
model.fit(X_train, y_train, eval_set=eval_set)
prediction = model.predict(test)
```

@hcho3 @trivialfis 

Before I did this example, I found gblinear worked until I added eval_set.  But in the above, the segfault still occurs even if the eval_set is removed from the fit().

**Comment by pseudotensor** [comment]
rapids 0.15 with cudf 0.15 and cuml 0.15 also segfault same way.

**Comment by pseudotensor** [comment]
```
import cudf
import pynvml
import numpy as np
import pandas as pd
import xgboost as xgb
from math import sqrt
from sklearn.model_selection import KFold, StratifiedKFold, GroupKFold
from sklearn.metrics import mean_squared_error,f1_score, accuracy_score
train = cudf.read_csv("creditcard.csv")
test = cudf.read_csv("creditcard.csv")
y = train['default payment next month']
train = train.drop(['default payment next month'], axis=1)
test = test.drop(['default payment next month'], axis=1)
from cuml import train_test_split
X_train, X_test, y_train, y_test = train_test_split(train, y, test_size=0.2, random_state=123)

params = {'learning_rate': 0.5, 'silent': True, 'booster': 'gblinear', 'updater': 'gpu_coord_descent', 'coordinate_selection': 'cyclic', 'tolerance': 1E-4, 'reg_lambda': 1E-3, 'reg_alpha': 5E-4, 'n_estimators': 5000}
model = xgb.XGBRegressor(**params)
eval_set = [(X_test, y_test), (X_train, y_train)]
model.fit(X_train, y_train)
```

Note the other "tree" arguments don't matter, just doesn't use them.  But above is without them, still seg faults.

Only sometimes before the segfault I get extra message:

```
[xgboost] Condition _ptr || _count == 0 failed.
```

but not always.
