### ISSUE TITLE
Python binding error: TypeError: expected str, bytes or os.PathLike object, not NoneType

### ISSUE THREAD

**Issue by yurivict** [dmlc/xgboost#6291]
py37-xgboost-1.2.1 fails on FreeBSD:
```
$ cat /tmp/x.py 
import xgboost
$ python3.7 /tmp/x.py 
Traceback (most recent call last):
  File "/tmp/x.py", line 1, in <module>
    import xgboost
  File "/usr/local/lib/python3.7/site-packages/xgboost/__init__.py", line 9, in <module>
    from .core import DMatrix, DeviceQuantileDMatrix, Booster
  File "/usr/local/lib/python3.7/site-packages/xgboost/core.py", line 173, in <module>
    _LIB = _load_lib()
  File "/usr/local/lib/python3.7/site-packages/xgboost/core.py", line 132, in _load_lib
    lib_paths = find_lib_path()
  File "/usr/local/lib/python3.7/site-packages/xgboost/libpath.py", line 45, in find_lib_path
    dll_path = [os.path.join(p, 'libxgboost.so') for p in dll_path]
  File "/usr/local/lib/python3.7/site-packages/xgboost/libpath.py", line 45, in <listcomp>
    dll_path = [os.path.join(p, 'libxgboost.so') for p in dll_path]
  File "/usr/local/lib/python3.7/posixpath.py", line 80, in join
    a = os.fspath(a)
TypeError: expected str, bytes or os.PathLike object, not NoneType
```

The same happened with py37-xgboost-1.2.0

**Comment by yurivict** [comment]
Here is a suggested patch that corrects this problem from a FreeBSD user: https://bugs.freebsd.org/bugzilla/show_bug.cgi?id=247408#c0

**Comment by hcho3** [comment]
Great, let us apply the patch.

**Comment by yurivict** [comment]
@hcho3 I tried this patch, and it didn't resolve the problem.
Perhaps it worked in 1.2.0.

**Comment by yurivict** [comment]
Here is the patch that helps:
```
--- xgboost/libpath.py.orig     2020-10-12 22:10:16 UTC
+++ xgboost/libpath.py
@@ -4,6 +4,7 @@
 import os
 import platform
 import sys
+import sysconfig # from https://bugs.freebsd.org/bugzilla/show_bug.cgi?id=247408#c0
 
 
 class XGBoostLibraryNotFound(Exception):
@@ -20,6 +21,8 @@ def find_lib_path():
     """
     curr_path = os.path.dirname(os.path.abspath(os.path.expanduser(__file__)))
     dll_path = [
+       sysconfig.get_config_var('LIBDIR'), # from https://bugs.freebsd.org/bugzilla/show_bug.cgi?id=247408#c0
+       os.path.join(sys.prefix, 'xgboost'),
         # normal, after installation `lib` is copied into Python package tree.
         os.path.join(curr_path, 'lib'),
         # editable installation, no copying is performed.
```

**Comment by hcho3** [comment]
Patch applied in #6292

**Comment by trivialfis** [comment]
Closing as duplicated to https://github.com/dmlc/xgboost/issues/5705 .
