### ISSUE TITLE
[JVM-PACKAGES] XGBoostError: Check failed: jenv->ExceptionOccurred

### ISSUE THREAD

**Issue by shade307** [dmlc/xgboost#6338]
**Reference issue**: https://github.com/dmlc/xgboost/issues/5145

Facing similar issue while loading a spark xgboost pipeline model using Mleap 

Xgboost version used is 1.0.0
Mleap package version used is 0.16.0

**Step 1**: Used Onehot encoder , Vector Assembler and XGBoostClassifier to create a spark pipeline 
**Step 2**: Saved the model pipeline using mleap bundle 
**Step 3**: Loaded the spark mleap bundle file and loaded the spark pipeline model
**Step 4**: On prediction facing the error.

_Lost task 1.0 in stage 126.0 (TID 1377,, executor 3): ml.dmlc.xgboost4j.java.XGBoostError: [12:01:54] /xgboost/jvm-packages/xgboost4j/src/native/xgboost4j.cpp:146: [12:01:54] /xgboost/jvm-packages/xgboost4j/src/native/xgboost4j.cpp:68: Check failed: jenv->ExceptionOccurred(): 
Stack trace:
  [bt] (0) /tmp/hadoop-mapr/nm-local-dir/usercache/mapr/appcache/application_1603352207099_1026/container_e6091_1603352207099_1026_02_000004/tmp/libxgboost4j8679267658553668238.so(dmlc::LogMessageFatal::~LogMessageFatal()+0x57) [0x7ff46537f837]
  [bt] (1) /tmp/hadoop-mapr/nm-local-dir/usercache/mapr/appcache/application_1603352207099_1026/container_e6091_1603352207099_1026_02_000004/tmp/libxgboost4j8679267658553668238.so(XGBoost4jCallbackDataIterNext+0x2c3d) [0x7ff46537c51d]
  [bt] (2) /tmp/hadoop-mapr/nm-local-dir/usercache/mapr/appcache/application_1603352207099_1026/container_e6091_1603352207099_1026_02_000004/tmp/libxgboost4j8679267658553668238.so(xgboost::NativeDataIter::Next()+0x15) [0x7ff46538fec5]
  [bt] (3) /tmp/hadoop-mapr/nm-local-dir/usercache/mapr/appcache/application_1603352207099_1026/container_e6091_1603352207099_1026_02_000004/tmp/libxgboost4j8679267658553668238.so(xgboost::data::SimpleDMatrix::SimpleDMatrix<xgboost::data::FileAdapter>(xgboost::data::FileAdapter*, float, int)+0x2cf) [0x7ff4654206ff]
  [bt] (4) /tmp/hadoop-mapr/nm-local-dir/usercache/mapr/appcache/application_1603352207099_1026/container_e6091_1603352207099_1026_02_000004/tmp/libxgboost4j8679267658553668238.so(xgboost::DMatrix* xgboost::DMatrix::Create<xgboost::data::FileAdapter>(xgboost::data::FileAdapter*, float, int, std::string const&, unsigned long)+0x4f) [0x7ff4654120ff]
  [bt] (5) /tmp/hadoop-mapr/nm-local-dir/usercache/mapr/appcache/application_1603352207099_1026/container_e6091_1603352207099_1026_02_000004/tmp/libxgboost4j8679267658553668238.so(XGDMatrixCreateFromDataIter+0x170) [0x7ff465380920]
  [bt] (6) /tmp/hadoop-mapr/nm-local-dir/usercache/mapr/appcache/application_1603352207099_1026/container_e6091_1603352207099_1026_02_000004/tmp/libxgboost4j8679267658553668238.so(Java_ml_dmlc_xgboost4j_java_XGBoostJNI_XGDMatrixCreateFromDataIter+0x96) [0x7ff4653785a6]
  [bt] (7) [0x7ff4a1018407]

Stack trace:
  [bt] (0) /tmp/hadoop-mapr/nm-local-dir/usercache/mapr/appcache/application_1603352207099_1026/container_e6091_1603352207099_1026_02_000004/tmp/libxgboost4j8679267658553668238.so(dmlc::LogMessageFatal::~LogMessageFatal()+0x57) [0x7ff46537f837]
  [bt] (1) /tmp/hadoop-mapr/nm-local-dir/usercache/mapr/appcache/application_1603352207099_1026/container_e6091_1603352207099_1026_02_000004/tmp/libxgboost4j8679267658553668238.so(XGBoost4jCallbackDataIterNext+0x194f) [0x7ff46537b22f]
  [bt] (2) /tmp/hadoop-mapr/nm-local-dir/usercache/mapr/appcache/application_1603352207099_1026/container_e6091_1603352207099_1026_02_000004/tmp/libxgboost4j8679267658553668238.so(xgboost::NativeDataIter::Next()+0x15) [0x7ff46538fec5]
  [bt] (3) /tmp/hadoop-mapr/nm-local-dir/usercache/mapr/appcache/application_1603352207099_1026/container_e6091_1603352207099_1026_02_000004/tmp/libxgboost4j8679267658553668238.so(xgboost::data::SimpleDMatrix::SimpleDMatrix<xgboost::data::FileAdapter>(xgboost::data::FileAdapter*, float, int)+0x2cf) [0x7ff4654206ff]
  [bt] (4) /tmp/hadoop-mapr/nm-local-dir/usercache/mapr/appcache/application_1603352207099_1026/container_e6091_1603352207099_1026_02_000004/tmp/libxgboost4j8679267658553668238.so(xgboost::DMatrix* xgboost::DMatrix::Create<xgboost::data::FileAdapter>(xgboost::data::FileAdapter*, float, int, std::string const&, unsigned long)+0x4f) [0x7ff4654120ff]
  [bt] (5) /tmp/hadoop-mapr/nm-local-dir/usercache/mapr/appcache/application_1603352207099_1026/container_e6091_1603352207099_1026_02_000004/tmp/libxgboost4j8679267658553668238.so(XGDMatrixCreateFromDataIter+0x170) [0x7ff465380920]
  [bt] (6) /tmp/hadoop-mapr/nm-local-dir/usercache/mapr/appcache/application_1603352207099_1026/container_e6091_1603352207099_1026_02_000004/tmp/libxgboost4j8679267658553668238.so(Java_ml_dmlc_xgboost4j_java_XGBoostJNI_XGDMatrixCreateFromDataIter+0x96) [0x7ff4653785a6]
  [bt] (7) [0x7ff4a1018407]

	at ml.dmlc.xgboost4j.java.XGBoostJNI.checkCall(XGBoostJNI.java:48)
	at ml.dmlc.xgboost4j.java.DMatrix.<init>(DMatrix.java:54)
	at ml.dmlc.xgboost4j.scala.DMatrix.<init>(DMatrix.scala:42)
	at ml.dmlc.xgboost4j.scala.spark.XGBoostClassificationModel$$anonfun$6$$anon$1$$anonfun$7.apply(XGBoostClassifier.scala:320)
	at ml.dmlc.xgboost4j.scala.spark.XGBoostClassificationModel$$anonfun$6$$anon$1$$anonfun$7.apply(XGBoostClassifier.scala:300)
	at scala.collection.Iterator$$anon$12.nextCur(Iterator.scala:435)
	at scala.collection.Iterator$$anon$12.hasNext(Iterator.scala:441)
	at ml.dmlc.xgboost4j.scala.spark.XGBoostClassificationModel$$anonfun$6$$anon$1.hasNext(XGBoostClassifier.scala:338)
	at scala.collection.Iterator$$anon$11.hasNext(Iterator.scala:409)
	at scala.collection.Iterator$$anon$11.hasNext(Iterator.scala:409)
	at org.apache.spark.sql.catalyst.expressions.GeneratedClass$GeneratedIteratorForCodegenStage1.processNext(Unknown Source)
	at org.apache.spark.sql.execution.BufferedRowIterator.hasNext(BufferedRowIterator.java:43)
	at org.apache.spark.sql.execution.WholeStageCodegenExec$$anonfun$13$$anon$1.hasNext(WholeStageCodegenExec.scala:636)
	at org.apache.spark.sql.execution.UnsafeExternalRowSorter.sort(UnsafeExternalRowSorter.java:216)
	at org.apache.spark.sql.execution.exchange.ShuffleExchangeExec$$anonfun$2.apply(ShuffleExchangeExec.scala:297)
	at org.apache.spark.sql.execution.exchange.ShuffleExchangeExec$$anonfun$2.apply(ShuffleExchangeExec.scala:266)
	at org.apache.spark.rdd.RDD$$anonfun$mapPartitionsInternal$1$$anonfun$apply$24.apply(RDD.scala:836)
	at org.apache.spark.rdd.RDD$$anonfun$mapPartitionsInternal$1$$anonfun$apply$24.apply(RDD.scala:836)
	at org.apache.spark.rdd.MapPartitionsRDD.compute(MapPartitionsRDD.scala:52)
	at org.apache.spark.rdd.RDD.computeOrReadCheckpoint(RDD.scala:324)
	at org.apache.spark.rdd.RDD.iterator(RDD.scala:288)
	at org.apache.spark.rdd.MapPartitionsRDD.compute(MapPartitionsRDD.scala:52)
	at org.apache.spark.rdd.RDD.computeOrReadCheckpoint(RDD.scala:324)
	at org.apache.spark.rdd.RDD.iterator(RDD.scala:288)
	at org.apache.spark.scheduler.ShuffleMapTask.runTask(ShuffleMapTask.scala:99)
	at org.apache.spark.scheduler.ShuffleMapTask.runTask(ShuffleMapTask.scala:55)
	at org.apache.spark.scheduler.Task.run(Task.scala:123)
	at org.apache.spark.executor.Executor$TaskRunner$$anonfun$10.org$apache$spark$executor$Executor$TaskRunner$$anonfun$$res$1(Executor.scala:412)
	at org.apache.spark.executor.Executor$TaskRunner$$anonfun$10.apply(Executor.scala:419)
	at org.apache.spark.util.Utils$.tryWithSafeFinally(Utils.scala:1359)
	at org.apache.spark.executor.Executor$TaskRunner.run(Executor.scala:430)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)_

**Config used is**: val booster: XGBoostClassifier = new XGBoostClassifier(
           Map(
             "missing" -> 0.0,
             "booster" -> "gbtree",
             "objective" -> "multi:softprob",
             "eval_metric" -> "merror",
             "tree_method" -> "approx",
             "eta" -> 0.2,
             "gamma" -> 1.0,
             "alpha" ->0,
             "max_depth" -> 4,
             "num_class" -> 9,
             "nthread" -> 2,
             "num_early_stopping_rounds" -> 10,
             "maximize_evaluation_metrics" -> false,
             "timeout_request_workers" -> 60000L
           )
         ).setLabelCol(targetVar)

After loading the model pipeline, when used model.getMissing , got the value NaN instead of 0.0.

**Comment by trivialfis** [comment]
You have an exception raised in scala iterator.
