### ISSUE TITLE
pred_contribs via dask API fails: ValueError: Shape of passed values is ...

### ISSUE THREAD

**Issue by pseudotensor** [dmlc/xgboost#6568]
```
import pandas as pd
import xgboost as xgb
def fun():
    from dask.distributed import Client, wait
    from dask_cuda import LocalCUDACluster

    with LocalCUDACluster() as cluster:
        with Client(cluster) as client:

            import xgboost as xgb
            import dask_cudf

            import pickle
            (model, X, y, kwargs) = pickle.load(open("xgbissue6469.pkl", "rb"))
            import dask.dataframe as dd
            X = dd.from_pandas(X, chunksize=250).persist()
            y = dd.from_pandas(y, chunksize=250).persist()
            valid_X = kwargs['eval_set'][0][0]
            valid_y = kwargs['eval_set'][0][1]
            valid_X = dd.from_pandas(valid_X, chunksize=250).persist()
            valid_y = dd.from_pandas(valid_y, chunksize=250).persist()
            kwargs['eval_set'] = [(valid_X, valid_y)]
            #model = xgb.dask.DaskXGBClassifier(**model.get_params())
            model.fit(X, y, **kwargs)
            preds = xgb.dask.predict(client=client, model=model.get_booster(), data=X, pred_contribs=True).compute()
            print(preds.shape)

            print("here")

if __name__ == '__main__':
    fun()

```

[xgbissue6469.pkl.zip](https://github.com/dmlc/xgboost/files/5760107/xgbissue6469.pkl.zip)

```
Exception: ValueError('Shape of passed values is (250, 2), indices imply (250, 1)',)

/home/jon/minicondadai/lib/python3.6/site-packages/distributed/client.py:4786: RuntimeWarning: coroutine 'Client._close' was never awaited
  c.close(timeout=2)
Traceback (most recent call last):
  File "dask_cudf_scitkit_predcontribs.py", line 31, in <module>
    fun()
  File "dask_cudf_scitkit_predcontribs.py", line 25, in fun
    preds = xgb.dask.predict(client=client, model=model.get_booster(), data=X, pred_contribs=True).compute()
  File "/home/jon/minicondadai/lib/python3.6/site-packages/dask/base.py", line 166, in compute
    (result,) = compute(self, traverse=False, **kwargs)
  File "/home/jon/minicondadai/lib/python3.6/site-packages/dask/base.py", line 444, in compute
    results = schedule(dsk, keys, **kwargs)
  File "/home/jon/minicondadai/lib/python3.6/site-packages/distributed/client.py", line 2682, in get
    results = self.gather(packed, asynchronous=asynchronous, direct=direct)
  File "/home/jon/minicondadai/lib/python3.6/site-packages/distributed/client.py", line 1982, in gather
    asynchronous=asynchronous,
  File "/home/jon/minicondadai/lib/python3.6/site-packages/distributed/client.py", line 832, in sync
    self.loop, func, *args, callback_timeout=callback_timeout, **kwargs
  File "/home/jon/minicondadai/lib/python3.6/site-packages/distributed/utils.py", line 339, in sync
    raise exc.with_traceback(tb)
  File "/home/jon/minicondadai/lib/python3.6/site-packages/distributed/utils.py", line 323, in f
    result[0] = yield future
  File "/home/jon/minicondadai/lib/python3.6/site-packages/tornado/gen.py", line 735, in run
    value = future.result()
  File "/home/jon/minicondadai/lib/python3.6/site-packages/distributed/client.py", line 1841, in _gather
    raise exception.with_traceback(traceback)
  File "/home/jon/minicondadai/lib/python3.6/site-packages/dask/optimization.py", line 1022, in __call__
    return core.get(self.dsk, self.outkey, dict(zip(self.inkeys, args)))
  File "/home/jon/minicondadai/lib/python3.6/site-packages/dask/core.py", line 151, in get
    result = _execute_task(task, cache)
  File "/home/jon/minicondadai/lib/python3.6/site-packages/dask/core.py", line 121, in _execute_task
    return func(*(_execute_task(a, cache) for a in args))
  File "/home/jon/minicondadai/lib/python3.6/site-packages/dask/utils.py", line 31, in apply
    return func(*args, **kwargs)
  File "/home/jon/minicondadai/lib/python3.6/site-packages/dask/dataframe/core.py", line 5258, in apply_and_enforce
    df = func(*args, **kwargs)
  File "/home/jon/minicondadai/lib/python3.6/site-packages/xgboost/dask.py", line 822, in mapped_predict
    predt = DataFrame(predt, columns=['prediction'])
  File "/home/jon/minicondadai/lib/python3.6/site-packages/pandas/core/frame.py", line 440, in __init__
    mgr = init_ndarray(data, index, columns, dtype=dtype, copy=copy)
  File "/home/jon/minicondadai/lib/python3.6/site-packages/pandas/core/internals/construction.py", line 213, in init_ndarray
    return create_block_manager_from_blocks(block_values, [columns, index])
  File "/home/jon/minicondadai/lib/python3.6/site-packages/pandas/core/internals/managers.py", line 1688, in create_block_manager_from_blocks
    construction_error(tot_items, blocks[0].shape[1:], axes, e)
  File "/home/jon/minicondadai/lib/python3.6/site-packages/pandas/core/internals/managers.py", line 1719, in construction_error
    "Shape of passed values is {0}, indices imply {1}".format(passed, implied)
ValueError: Shape of passed values is (250, 2), indices imply (250, 1)
(base) jon@mr-dl10:/data/jon/h2oai.fullcondatest3$ 

```

**Comment by pseudotensor** [comment]
FYI @trivialfis

**Comment by pseudotensor** [comment]
FYI doesn't matter size of frame, if I give all 25 columns of data, then same result:

```
  File "/home/jon/minicondadai/lib/python3.6/site-packages/xgboost/dask.py", line 822, in mapped_predict
    predt = DataFrame(predt, columns=['prediction'])
  File "/home/jon/minicondadai/lib/python3.6/site-packages/pandas/core/frame.py", line 440, in __init__
    mgr = init_ndarray(data, index, columns, dtype=dtype, copy=copy)
  File "/home/jon/minicondadai/lib/python3.6/site-packages/pandas/core/internals/construction.py", line 213, in init_ndarray
    return create_block_manager_from_blocks(block_values, [columns, index])
  File "/home/jon/minicondadai/lib/python3.6/site-packages/pandas/core/internals/managers.py", line 1688, in create_block_manager_from_blocks
    construction_error(tot_items, blocks[0].shape[1:], axes, e)
  File "/home/jon/minicondadai/lib/python3.6/site-packages/pandas/core/internals/managers.py", line 1719, in construction_error
    "Shape of passed values is {0}, indices imply {1}".format(passed, implied)
ValueError: Shape of passed values is (250, 25), indices imply (250, 1)

```

**Comment by pseudotensor** [comment]
Work-around for pred_contribs not working with dask for any interface: https://github.com/dmlc/xgboost/issues/6547#issuecomment-753562193

**Comment by trivialfis** [comment]
Working on this.

**Comment by trivialfis** [comment]
Could you please show us the training procedure, and the commit of xgboost you are using?

**Comment by trivialfis** [comment]
When you generate a pickle, it will include the related Python bytecode.  We do not recommend sharing pickle file.

**Comment by pseudotensor** [comment]
> When you generate a pickle, it will include the related Python bytecode which is unstable across libraries or Python itself. We do not recommend sharing pickle file.

Do you run into a problem?  The pickle file should be fine across python, that's not a problem.  But particular packages can be incompatible of course.  I was using the commit just before you dropped binary support in favor of json.  You can just use latest master and revert that json being no longer experimental commit.

**Comment by trivialfis** [comment]
> Do you run into a problem? The pickle file should be fine across python, that's not a problem.

Pickle file  is not portable across Python version.

The more easily encountered issue is, the Python object you pickled, is the Python bytecode representation of that object, be it a function or a class.  That means, even if we are running the same Python version, if  my local installation of xgboost has any change to that class object, like removing an attribute, or adding an optional parameter to a function, we will have conflict.

**Comment by trivialfis** [comment]
So when I load your pickle, essentially I have 1 and half xgboost loaded.

**Comment by trivialfis** [comment]
Also, I added some simple tests for shap value computation in https://github.com/dmlc/xgboost/pull/6575 , could you please help taking a look?

**Comment by trivialfis** [comment]
Feel free to reopen if this is reproducible on latest master.

**Comment by pseudotensor** [comment]
Not sure why this is closed within 2 days of asking for more.  You should wait for me to follow-up.
