### ISSUE TITLE
UnboundLocalError: local variable 'column_indexes' referenced before assignment

### ISSUE THREAD

**Issue by pseudotensor** [dmlc/xgboost#6570]
```
import pandas as pd
import xgboost as xgb
def fun():
    from dask.distributed import Client, wait
    from dask_cuda import LocalCUDACluster

    with LocalCUDACluster() as cluster:
        with Client(cluster) as client:

            import xgboost as xgb
            import dask_cudf

            import pickle
            (model, X, y, kwargs) = pickle.load(open("xgbissue6469.pkl", "rb"))
            X = pd.read_csv("creditcard.csv")
            print(X.columns)
            target = 'default payment next month'
            y = X[target]
            X = X.drop(target, axis=1)
            import dask.dataframe as dd
            X = dd.from_pandas(X, chunksize=250).persist()
            y = dd.from_pandas(y, chunksize=250).persist()
            valid_X = kwargs['eval_set'][0][0]
            valid_y = kwargs['eval_set'][0][1]
            valid_X = dd.from_pandas(valid_X, chunksize=250).persist()
            valid_y = dd.from_pandas(valid_y, chunksize=250).persist()
            #kwargs['eval_set'] = [(valid_X, valid_y)]
            kwargs.pop('eval_set', None)
            kwargs.pop('eval_metric', None)
            model = xgb.dask.DaskXGBClassifier(**model.get_params())
            model.fit(X, y, **kwargs)
            model.get_booster().save_model('0001.model')
            bst = xgb.XGBClassifier(model.get_params())
            bst.load_model('0001.model')
            preds_contribs = bst.predict(X.compute(), pred_contribs=True)
            print(preds_contribs.shape)

            print("here")

if __name__ == '__main__':
    fun()
```

leads to

```
/home/jon/minicondadai/lib/python3.6/site-packages/xgboost/core.py:419: FutureWarning: Pass `objective` as keyword args.  Passing these as positional arguments will be considered as error in future releases.
  format(", ".join(args_msg)), FutureWarning)
/home/jon/minicondadai/lib/python3.6/site-packages/xgboost/sklearn.py:472: UserWarning: Loading a native XGBoost model with Scikit-Learn interface.
  'Loading a native XGBoost model with Scikit-Learn interface.')
Traceback (most recent call last):
  File "/data/jon/h2oai.fullcondatest3/dask_cudf_scitkit_predcontribs2.py", line 45, in <module>
    fun()
  File "/data/jon/h2oai.fullcondatest3/dask_cudf_scitkit_predcontribs2.py", line 39, in fun
    preds_contribs = bst.predict(X.compute(), pred_contribs=True)
  File "/home/jon/minicondadai/lib/python3.6/site-packages/xgboost/sklearn.py", line 1003, in predict
    return column_indexes
UnboundLocalError: local variable 'column_indexes' referenced before assignment

Process finished with exit code 1
```

**Comment by pseudotensor** [comment]
`/home/jon/minicondadai/lib/python3.6/site-packages/xgboost/sklearn.py:472: UserWarning: Loading a native XGBoost model with Scikit-Learn interface.`  Since this is just a warning and it should have worked.

**Comment by pseudotensor** [comment]
This attempt also fails same way, just showing part that is different:

```
            model.get_booster().save_model('0001.model')
            bst = xgb.Booster()
            bst.load_model('0001.model')
            model2 = xgb.XGBClassifier(**model.get_params())
            model2._Booster = bst
            preds_contribs2 = model2.predict(X.compute(), pred_contribs=True)
            print(preds_contribs2.shape)

```

**Comment by pseudotensor** [comment]
Ah, nm, this is my own local bug.
