### ISSUE TITLE
How to convert the new version model to the old version model 

### ISSUE THREAD

**Issue by LC9528** [dmlc/xgboost#6670]
Hello. I used the 1.1.1 version of xgboost to train the model and saved it in the methods of "joblib.dump" and "save_model". Now, I want to convert the model generated using xgboost version 1.1.1 to a model generated using xgboost version 0.80. Is there any way to do it? 
I tried to use 0.80 version of xgboost to open the model generated with 1.1.1 version of xgboost and predict. Use the "save_model" function to load the model without errors but no prediction results. Using the "joblib.load" function to load the model will report an error.

code:
```
import pandas as pd
import xgboost as xgb
from sklearn import preprocessing
from sklearn.model_selection import train_test_split
from sklearn.externals import joblib
from xgboost import XGBClassifier
from sklearn.metrics import accuracy_score
from xgboost import plot_importance
import sys

def load_features(csvname):
    test_X = pd.read_csv(csvname)
    test_X = test_X[[str(i) for i in range(1, test_X.shape[1])]]
    return test_X


def predict_with_bin_model(model_bin, test_X):
    test_X = xgb.DMatrix(test_X)
    bst = xgb.Booster({'nthread': 4})  # init model
    bst.load_model(model_bin)  # save_model()
    predictions = bst.predict(test_X)
    for i in range(predictions.shape[0]):
        predictions[i] = 1.0 - predictions[i]
    return predictions


def predict_with_model_model(model_model, test_X):
    bst = joblib.load(model_model) # joblib.dump()
    predictions = bst.predict_proba(test_X)
    return predictions

def main():
    csvname = '../process_data/feature/feature1.csv'
    model_bin = '../process_data/model/new_lexer3_xgb1_1.bin'
    model_model = '../process_data/model/new_lexer3_xgb1_1.model'
    test_X = load_features(csvname)

    res = predict_with_bin_model(model_bin, test_X)
    print("res: ", res)

    res = predict_with_model_model(model_model, test_X)
    print("res: ", res)

main()
```

result:
```
res: []
Traceback (most recent call last):
  File "predict_with_0.8_version.py", line 45, in <module>
    main()
  File "predict_with_0.8_version.py", line 42, in main
    res = predict_with_model_model(model_model, test_X)
  File "predict_with_0.8_version.py", line 29, in predict_with_model_model
    bst = joblib.load(model_model)
  File "/home/algo/.local/lib/python3.6/site-packages/joblib/numpy_pickle.py", line 605, in load
    obj = _unpickle(fobj, filename, mmap_mode)
  File "/home/algo/.local/lib/python3.6/site-packages/joblib/numpy_pickle.py", line 529, in _unpickle
    obj = unpickler.load()
  File "/usr/lib/python3.6/pickle.py", line 1050, in load
    dispatch[key[0]](self)
  File "/usr/lib/python3.6/pickle.py", line 1338, in load_global
    klass = self.find_class(module, name)
  File "/usr/lib/python3.6/pickle.py", line 1392, in find_class
    return getattr(sys.modules[module], name)
AttributeError: module 'xgboost.compat' has no attribute 'XGBoostLabelEncoder'
```

**Comment by trivialfis** [comment]
I don't think that's trivial.  We jump into the new JSON format because the binary one is so difficult to manipulate...

**Comment by LC9528** [comment]
> 
> 
> I don't think that's trivial. We jump into the new JSON format because the binary one is so difficult to manipulate...

I also exported the model in json format. However, xgboost mentioned that the main use case of the json format is for model interpretation or visualization and should not be loaded back into XGBoost. 
The document link is as follows.
```
https://xgboost.readthedocs.io/en/latest/tutorials/saving_model.html
```
Is it a better solution to retrain the old model with the old version of xgboost instead of converting the model?

**Comment by trivialfis** [comment]
No.  There's no official solution for forward compatibility, only backward is provided.  Could you please share why do you want to use the old xgboost version? (0.80 is long time ago for a project like xgboost, we ramped up the development for quite a bit after that).

**Comment by hansonw** [comment]
Of course this might not work for much longer, but here's a huge hack I used to unpickle a pickled Booster from an older xgboost version:

```
import xgboost as xgb
import ctypes
import numpy as np
import struct

mock_data = xgb.DMatrix(np.array([[0,1]]), label=np.array([0]))
mock_json_config = xgb.train({}, mock_data).save_config().encode('utf8')

# Modified __setstate__ which adapts older XGBoost binary formats to the current one
def backwards_compatible_setstate(self, state) -> None:
    # reconstruct handle from raw data
    handle = state['handle']
    if handle is not None:
        # Augment to match new serialization format
        # https://github.com/dmlc/xgb/blob/master/src/learner.cc#L954
        buf = (
            # serialisation_header
            bytearray(b'CONFIG-offset:') +
            # json_offset
            bytearray(struct.pack('Q', len(handle))) +
            # raw Booster data
            handle +
            # JSON config
            bytearray(mock_json_config)
        )
        dmats = xgb.core.c_array(ctypes.c_void_p, [])
        handle = ctypes.c_void_p()
        xgb.core._check_call(xgb.core._LIB.XGBoosterCreate(
            dmats, xgb.core.c_bst_ulong(0), ctypes.byref(handle)))
        length = xgb.core.c_bst_ulong(len(buf))
        ptr = (ctypes.c_char * len(buf)).from_buffer(buf)
        xgb.core._check_call(
            xgb.core._LIB.XGBoosterUnserializeFromBuffer(handle, ptr, length))
        state['handle'] = handle
    self.__dict__.update(state)

xgb.Booster.__setstate__ = backwards_compatible_setstate
```

After patching `Booster.__setstate__` unpickling the older format should work.

No guarantees here obviously - I suspect the use of a mock JSON config (`mock_json_config`) might cause issues with certain boosting configs.
