### ISSUE TITLE
TypeError: Expecting <class 'dask.dataframe.core.DataFrame'> or <class 'dask.array.core.Array'>.  Got <class 'cudf.core.dataframe.DataFrame'>

### ISSUE THREAD

**Issue by pseudotensor** [dmlc/xgboost#7021]
```
def fun():
    from dask.distributed import Client

    if True:
        with Client(scheduler_file="dask_scheduler.json") as client:
            import xgboost as xgb

            import pickle
            file1 = "dask_model_7057781c-8d70-4bed-b21b-126deb380a26.pickle"
            (X, y, kwargs) = pickle.load(open(file1, "rb"))
            params = dict(tree_method='gpu_hist', booster='gbtree', verbose=True, silent=False)
            model = xgb.dask.DaskXGBClassifier(**params)
            import dask.dataframe as dd
            X = dd.from_pandas(X, chunksize=50).persist()
            y = dd.from_pandas(y, chunksize=50).persist()
            model.fit(X, y, **kwargs)
            preds = model.predict(X)
            print(preds.compute()[0])
            print("here")

if __name__ == '__main__':
    fun()
```

[dask_model_7057781c-8d70-4bed-b21b-126deb380a26.pickle.zip](https://github.com/dmlc/xgboost/files/6589284/dask_model_7057781c-8d70-4bed-b21b-126deb380a26.pickle.zip)

```
Traceback (most recent call last):
  File "dask_cudf_scitkit_issue7019.py", line 22, in <module>
    fun()
  File "dask_cudf_scitkit_issue7019.py", line 16, in fun
    model.fit(X, y, **kwargs)
  File "/home/jon/minicondadai_py38/lib/python3.8/site-packages/xgboost/dask.py", line 1802, in fit
    return self._client_sync(self._fit_async, **args)
  File "/home/jon/minicondadai_py38/lib/python3.8/site-packages/xgboost/dask.py", line 1610, in _client_sync
    return self.client.sync(func, **kwargs, asynchronous=asynchronous)
  File "/home/jon/minicondadai_py38/lib/python3.8/site-packages/distributed/client.py", line 843, in sync
    return sync(
  File "/home/jon/minicondadai_py38/lib/python3.8/site-packages/distributed/utils.py", line 353, in sync
    raise exc.with_traceback(tb)
  File "/home/jon/minicondadai_py38/lib/python3.8/site-packages/distributed/utils.py", line 336, in f
    result[0] = yield future
  File "/home/jon/minicondadai_py38/lib/python3.8/site-packages/tornado/gen.py", line 762, in run
    value = future.result()
  File "/home/jon/minicondadai_py38/lib/python3.8/site-packages/xgboost/dask.py", line 1723, in _fit_async
    dtrain, evals = await _async_wrap_evaluation_matrices(
  File "/home/jon/minicondadai_py38/lib/python3.8/site-packages/xgboost/dask.py", line 1441, in _async_wrap_evaluation_matrices
    train_dmatrix, evals = _wrap_evaluation_matrices(create_dmatrix=_inner, **kwargs)
  File "/home/jon/minicondadai_py38/lib/python3.8/site-packages/xgboost/sklearn.py", line 312, in _wrap_evaluation_matrices
    m = create_dmatrix(
  File "/home/jon/minicondadai_py38/lib/python3.8/site-packages/xgboost/dask.py", line 1438, in _inner
    m = DaskDMatrix(client=client, **kwargs)
  File "/home/jon/minicondadai_py38/lib/python3.8/site-packages/xgboost/core.py", line 440, in inner_f
    return f(**kwargs)
  File "/home/jon/minicondadai_py38/lib/python3.8/site-packages/xgboost/dask.py", line 279, in __init__
    raise TypeError(_expect((dd.DataFrame, da.Array), type(data)))
TypeError: Expecting <class 'dask.dataframe.core.DataFrame'> or <class 'dask.array.core.Array'>.  Got <class 'cudf.core.dataframe.DataFrame'>
sys:1: RuntimeWarning: coroutine 'DaskDMatrix._map_local_data' was never awaited
```

I don't really understand this message.  This exact code worked before on older 1.3 releases of xgboost and was part of older issues.  Why doesn't it still work?

I encountered actually several of these kinds of problems when updating to latest xgboost, but now I'm asking why.

**Comment by pseudotensor** [comment]
This fails in similar way.  Above I can imagine has issues now because the .compute() from dask returned cudf always or something, but here I'm converting back to pandas and still get same failure
```
def fun():
    from dask.distributed import Client

    if True:
        with Client(scheduler_file="dask_scheduler.json") as client:
            import xgboost as xgb

            import pickle
            file1 = "dask_model_7057781c-8d70-4bed-b21b-126deb380a26.pickle"
            (X, y, kwargs) = pickle.load(open(file1, "rb"))
            params = dict(tree_method='gpu_hist', booster='gbtree', verbose=True, silent=False)
            model = xgb.dask.DaskXGBClassifier(**params)
            import dask.dataframe as dd
            print(type(X))
            X = X.to_pandas()
            y = y.to_pandas().values.ravel()
            print(type(X))

            X['target'] = y
            X = dd.from_pandas(X, chunksize=50).persist()
            import dask_cudf
            X = dask_cudf.from_dask_dataframe(X)
            y = X['target']
            X = X.drop('target', axis=1)

            model.fit(X, y, **kwargs)
            preds = model.predict_proba(X)
            print(preds.compute()[0])
            print("here")

if __name__ == '__main__':
    fun()
```


```
base) jon@mr-dl10:/data/jon/h2oai.fullcondatest3$ python dask_cudf_scitkit_issue7019.py
<class 'cudf.core.dataframe.DataFrame'>
<class 'pandas.core.frame.DataFrame'>
Traceback (most recent call last):
  File "dask_cudf_scitkit_issue7019.py", line 32, in <module>
    fun()
  File "dask_cudf_scitkit_issue7019.py", line 26, in fun
    model.fit(X, y, **kwargs)
  File "/home/jon/minicondadai_py38/lib/python3.8/site-packages/xgboost/dask.py", line 1802, in fit
    return self._client_sync(self._fit_async, **args)
  File "/home/jon/minicondadai_py38/lib/python3.8/site-packages/xgboost/dask.py", line 1610, in _client_sync
    return self.client.sync(func, **kwargs, asynchronous=asynchronous)
  File "/home/jon/minicondadai_py38/lib/python3.8/site-packages/distributed/client.py", line 843, in sync
    return sync(
  File "/home/jon/minicondadai_py38/lib/python3.8/site-packages/distributed/utils.py", line 353, in sync
    raise exc.with_traceback(tb)
  File "/home/jon/minicondadai_py38/lib/python3.8/site-packages/distributed/utils.py", line 336, in f
    result[0] = yield future
  File "/home/jon/minicondadai_py38/lib/python3.8/site-packages/tornado/gen.py", line 762, in run
    value = future.result()
  File "/home/jon/minicondadai_py38/lib/python3.8/site-packages/xgboost/dask.py", line 1723, in _fit_async
    dtrain, evals = await _async_wrap_evaluation_matrices(
  File "/home/jon/minicondadai_py38/lib/python3.8/site-packages/xgboost/dask.py", line 1441, in _async_wrap_evaluation_matrices
    train_dmatrix, evals = _wrap_evaluation_matrices(create_dmatrix=_inner, **kwargs)
  File "/home/jon/minicondadai_py38/lib/python3.8/site-packages/xgboost/sklearn.py", line 312, in _wrap_evaluation_matrices
    m = create_dmatrix(
  File "/home/jon/minicondadai_py38/lib/python3.8/site-packages/xgboost/dask.py", line 1438, in _inner
    m = DaskDMatrix(client=client, **kwargs)
  File "/home/jon/minicondadai_py38/lib/python3.8/site-packages/xgboost/core.py", line 440, in inner_f
    return f(**kwargs)
  File "/home/jon/minicondadai_py38/lib/python3.8/site-packages/xgboost/dask.py", line 279, in __init__
    raise TypeError(_expect((dd.DataFrame, da.Array), type(data)))
TypeError: Expecting <class 'dask.dataframe.core.DataFrame'> or <class 'dask.array.core.Array'>.  Got <class 'cudf.core.dataframe.DataFrame'>
sys:1: RuntimeWarning: coroutine 'DaskDMatrix._map_local_data' was never awaited
(base) jon@mr-dl10:/data/jon/h2oai.fullcondatest3$ 

```

**Comment by pseudotensor** [comment]
Ah, my kwargs had cudf still.  I guess I'll just live with the changes.

**Comment by trivialfis** [comment]
You need to make sure the data being dask collection.  Which backend (pandas, cudf) doesn't matter.
