### ISSUE TITLE
AttributeError: 'list' object has no attribute 'inplace_predict'

### ISSUE THREAD

**Issue by pseudotensor** [dmlc/xgboost#7045]
On master of xgboost but only after updating to rapids 21.06 and dask 2021.5 I get this now.  Known problem?  I can find repro, but I'm spending more time with multinode problem (which rapids 21.06 dask 2021.5 update didn't solve).  This error doesn't happen with same xgboost but rapids 19.2 dask 2021.4.

```
  File "/opt/h2oai/dai/cpu-only/lib/python3.8/site-packages/dask/base.py", line 285, in compute
    (result,) = compute(self, traverse=False, **kwargs)
  File "/opt/h2oai/dai/cpu-only/lib/python3.8/site-packages/dask/base.py", line 567, in compute
    results = schedule(dsk, keys, **kwargs)
  File "/opt/h2oai/dai/cpu-only/lib/python3.8/site-packages/distributed/client.py", line 2674, in get
    results = self.gather(packed, asynchronous=asynchronous, direct=direct)
  File "/opt/h2oai/dai/cpu-only/lib/python3.8/site-packages/distributed/client.py", line 1983, in gather
    return self.sync(
  File "/opt/h2oai/dai/cpu-only/lib/python3.8/site-packages/distributed/client.py", line 851, in sync
    return sync(
  File "/opt/h2oai/dai/cpu-only/lib/python3.8/site-packages/distributed/utils.py", line 354, in sync
    raise exc.with_traceback(tb)
  File "/opt/h2oai/dai/cpu-only/lib/python3.8/site-packages/distributed/utils.py", line 337, in f
    result[0] = yield future
  File "/opt/h2oai/dai/cpu-only/lib/python3.8/site-packages/tornado/gen.py", line 762, in run
    value = future.result()
  File "/opt/h2oai/dai/cpu-only/lib/python3.8/site-packages/distributed/client.py", line 1848, in _gather
    raise exception.with_traceback(traceback)
  File "/opt/h2oai/dai/cpu-only/lib/python3.8/site-packages/dask/optimization.py", line 966, in __call__
    return core.get(self.dsk, self.outkey, dict(zip(self.inkeys, args)))
  File "/opt/h2oai/dai/cpu-only/lib/python3.8/site-packages/dask/core.py", line 151, in get
    result = _execute_task(task, cache)
  File "/opt/h2oai/dai/cpu-only/lib/python3.8/site-packages/dask/core.py", line 121, in _execute_task
    return func(*(_execute_task(a, cache) for a in args))
  File "/opt/h2oai/dai/cpu-only/lib/python3.8/site-packages/dask/core.py", line 121, in <genexpr>
    return func(*(_execute_task(a, cache) for a in args))
  File "/opt/h2oai/dai/cpu-only/lib/python3.8/site-packages/dask/core.py", line 115, in _execute_task
    return [_execute_task(a, cache) for a in arg]
  File "/opt/h2oai/dai/cpu-only/lib/python3.8/site-packages/dask/core.py", line 115, in <listcomp>
    return [_execute_task(a, cache) for a in arg]
  File "/opt/h2oai/dai/cpu-only/lib/python3.8/site-packages/dask/core.py", line 121, in _execute_task
    return func(*(_execute_task(a, cache) for a in args))
  File "/opt/h2oai/dai/cpu-only/lib/python3.8/site-packages/dask/utils.py", line 34, in apply
    return func(*args, **kwargs)
  File "/opt/h2oai/dai/cpu-only/lib/python3.8/site-packages/dask/dataframe/core.py", line 5706, in apply_and_enforce
    df = func(*args, **kwargs)
  File "/opt/h2oai/dai/cpu-only/lib/python3.8/site-packages/xgboost/dask.py", line 1340, in mapped_predict
    prediction = booster.inplace_predict(
AttributeError: 'list' object has no attribute 'inplace_predict'
```

**Comment by trivialfis** [comment]
Not known.  A reproducible example is appreciated.  Initial guess is this one: https://github.com/dask/dask/issues/7681

**Comment by trivialfis** [comment]
The referenced issue is fixed in dask 2021.6.1 .  So maybe you can do a quick update and see if it works.

**Comment by pseudotensor** [comment]
There is no distributed 2021.6.1 in conda-forge, only 2021.6.0.

**Comment by trivialfis** [comment]
My bad, 2021.6.0 then.

**Comment by pseudotensor** [comment]
I tried that and hit other problems with rapids 21.06:

```
  File "/home/jon/minicondadai_py38/lib/python3.8/site-packages/dask_cuda/proxy_object.py", line 742, in <module>
    dispatch.register(ProxyObject, unproxify_input_wrapper(dispatch))
AttributeError: 'function' object has no attribute 'register'
```

I don't think can mix things up, the rapids version and dask/distributed version are too synced.

**Comment by pseudotensor** [comment]
![image](https://user-images.githubusercontent.com/2249614/122544193-6a1feb00-cfe1-11eb-87ff-78ded440aef2.png)


FYI, the thing inside booster is totally nuts/wrong.

**Comment by pseudotensor** [comment]
Trying, but it seems not trivial to reproduce.  Maybe it is a race, not sure.  Seems possible given what I described.

When I try to pickle up the "y" object just before failure, which would be most direct way of dealing with this, I get `Can't pickle local object '_inplace_predict_async.<locals>.mapped_predict'`.

That is, it seems xgboost does not return a dask dataframe for y that one would .compute() on.  Instead, you map it to some function.  I suspect that must be reason why there is problem in first place for this issue.

**Comment by pseudotensor** [comment]
There is problem even before the `model.predict_proba`.  If I try to take the valid_X dask frame and .compute() on it, I get: `Exception: TypeError('copy() takes no keyword arguments')`  


If I use latest master: https://s3-us-west-2.amazonaws.com/xgboost-nightly-builds/xgboost-1.5.0.dev0%2B29f8fd6fee96b5b28bc1ccd6fdfc5d472b949f0b-py3-none-manylinux2010_x86_64.whl

I still hit a problem, but it is a slightly different message:


```
distributed.worker - WARNING - Compute Failed
Function:  subgraph_callable
args:      (      ChangeTempDir  ...  ________SAMPLE_WEIGHT_________
0               1.0  ...                             1.0
1               1.0  ...                             1.0
2               1.0  ...                             1.0
3               1.0  ...                             1.0
4               1.0  ...                             1.0
...             ...  ...                             ...
1947            1.0  ...                             1.0
1948            1.0  ...                             1.0
1949            1.0  ...                             1.0
1950            1.0  ...                             1.0
1951            1.0  ...                             1.0

[1952 rows x 24 columns])
kwargs:    {}
Exception: TypeError('copy() takes no keyword arguments')

distributed.worker - WARNING - Compute Failed
Function:  subgraph_callable
args:      (      ChangeTempDir  ...  ________SAMPLE_WEIGHT_________
1952            1.0  ...                             1.0
1953            1.0  ...                             1.0
1954            1.0  ...                             1.0
1955            1.0  ...                             1.0
1956            1.0  ...                             1.0
...             ...  ...                             ...
3900            1.0  ...                             1.0
3901            1.0  ...                             1.0
3902            1.0  ...                             1.0
3903            1.0  ...                             1.0
3904            1.0  ...                             1.0

[1953 rows x 24 columns])
kwargs:    {}
Exception: TypeError('copy() takes no keyword arguments')

[W 2021-06-18 12:05:33,298] Trial 0 failed because of the following error: AssertionError('error')
Traceback (most recent call last):
  File "/home/jon/minicondadai_py38/lib/python3.8/site-packages/optuna/_optimize.py", line 198, in _run_trial
    value_or_values = func(trial)
  File "/home/jon/h2oai/h2oaicore/models.py", line 2508, in objective
    score = self.score_for_model(score_f=score_f, model=model, del_model=True, **kwargs_fit)
  File "/home/jon/h2oai/h2oaicore/models.py", line 3074, in score_for_model
    preds = model.predict_proba(valid_X)
  File "/home/jon/minicondadai_py38/lib/python3.8/site-packages/xgboost/dask.py", line 1838, in predict_proba
    return self._client_sync(
  File "/home/jon/minicondadai_py38/lib/python3.8/site-packages/xgboost/dask.py", line 1611, in _client_sync
    return self.client.sync(func, **kwargs, asynchronous=asynchronous)
  File "/home/jon/minicondadai_py38/lib/python3.8/site-packages/distributed/client.py", line 851, in sync
    return sync(
  File "/home/jon/minicondadai_py38/lib/python3.8/site-packages/distributed/utils.py", line 354, in sync
    raise exc.with_traceback(tb)
  File "/home/jon/minicondadai_py38/lib/python3.8/site-packages/distributed/utils.py", line 337, in f
    result[0] = yield future
  File "/home/jon/minicondadai_py38/lib/python3.8/site-packages/tornado/gen.py", line 762, in run
    value = future.result()
  File "/home/jon/minicondadai_py38/lib/python3.8/site-packages/xgboost/dask.py", line 1814, in _predict_proba_async
    predts = await super()._predict_async(
  File "/home/jon/minicondadai_py38/lib/python3.8/site-packages/xgboost/dask.py", line 1500, in _predict_async
    test_dmatrix = await DaskDMatrix(
  File "/home/jon/minicondadai_py38/lib/python3.8/site-packages/xgboost/dask.py", line 395, in _map_local_data
    assert part.status == 'finished', part.status
AssertionError: error

```

**Comment by pseudotensor** [comment]
These problems come when slicing the dask frame like `valid_X = valid_X[names_to_use]`.  As soon as it is sliced, the .compute() fails in various ways.

**Comment by trivialfis** [comment]
> These problems come when slicing the dask frame like valid_X = valid_X[names_to_use]. As soon as it is sliced, the .compute() fails in various ways 

Seems you have found a reliable way to reproduce it?

**Comment by pseudotensor** [comment]
> > These problems come when slicing the dask frame like valid_X = valid_X[names_to_use]. As soon as it is sliced, the .compute() fails in various ways
> 
> Seems you have found a reliable way to reproduce it?

I have reliable way to reproduce, but not in MRE.  I think it might be that things are done multiple times etc.  not sure.

**Comment by trivialfis** [comment]
Do you know where is this `________SAMPLE_WEIGHT_________` coming from?  I grep all the related libraries' source code and didn't get anything.

**Comment by pseudotensor** [comment]
> Do you know where is this `________SAMPLE_WEIGHT_________` coming from? I grep all the related libraries' source code and didn't get anything. Or it's a column of your data?

That and the __TARGET__ thing are just feature names.

**Comment by pseudotensor** [comment]
Seems as long as I don't slice the frame going into predict, all works fine when using latest xgboost version.

But that slice causes problems when doing .compute() on it or when passing into xgboost predict_proba.  So I doubt it is directly xgboost's fault.

xgboost just gives much more wild error, but original error is the 
```
Exception: TypeError('copy() takes no keyword arguments')
```
when doing .compute().

**Comment by pseudotensor** [comment]
The reason why it has that error about `TypeError('copy() takes no keyword arguments')` is because the dataframe is a list.

![image](https://user-images.githubusercontent.com/2249614/122613404-a4b57200-d039-11eb-87c7-ba1c653cc976.png)

The drop operation is totally messed up.

**Comment by trivialfis** [comment]
Shouldn't it be:

``` python
drop_by_shallow_copy(dataframe, list_of_columns)
```
?

**Comment by pseudotensor** [comment]
I don't think this is xgboost's fault, unless re-use of the frame is causing problems.

https://github.com/dask/dask/issues/7819

**Comment by pseudotensor** [comment]
ya for sure dask problem
