### ISSUE TITLE
xgb.train early_stopping_rounds failed!

### ISSUE THREAD

**Issue by bifeng** [dmlc/xgboost#7176]
early_stopping_rounds = 10
bst = xgb.train(param, dtrain, num_round, evallist, early_stopping_rounds)
Traceback (most recent call last):
  File "<input>", line 1, in <module>
  File "/home/homay/anaconda3/envs/pytorch/lib/python3.9/site-packages/xgboost/training.py", line 189, in train
    bst = _train_internal(params, dtrain,
  File "/home/homay/anaconda3/envs/pytorch/lib/python3.9/site-packages/xgboost/training.py", line 81, in _train_internal
    bst.update(dtrain, i, obj)
  File "/home/homay/anaconda3/envs/pytorch/lib/python3.9/site-packages/xgboost/core.py", line 1504, in update
    grad, hess = fobj(pred, dtrain)
TypeError: 'int' object is not callable

**Comment by trivialfis** [comment]
``` python
bst = xgb.train(param, dtrain, num_round, evallist, early_stopping_rounds=early_stopping_rounds)
```
