### ISSUE TITLE
Problem for (de)serialization of Spark implementation of custom objective and eval

### ISSUE THREAD

**Issue by nicovdijk** [dmlc/xgboost#7224]
I have been trying to get (de)serialization of the Spark version of XGBoost in combination with a customObj and customEval working. Serialization works, but loading the model results in the following error:

org.json4s.package$MappingException: No constructor for type ObjectiveTrait, JObject(List())

This error is related to the json4s package. Based on some tests I have run, it seems that we are missing a type hint for the customObj class. I have been trying to add this type hint, but the implementation of the `jsonEncode` method of the `CustomObjParam` class explicitly uses `NoTypeHints`. Comparing the `CustomObjParam` implementation:
```scala
override def jsonEncode(value: ObjectiveTrait): String = {
    import org.json4s.jackson.Serialization
    implicit val formats = Serialization.formats(NoTypeHints)
    compact(render(Extraction.decompose(value)))
}
```
with the general Spark implementation (here of the `IntArrayParam`):
```scala
override def jsonEncode(value: Array[Int]): String = {
    import org.json4s.JsonDSL._
    compact(render(value.toSeq))
}
```
I suspect that changing the line with `NoTypeHints` to something else would allow using type hints. Even better would be to make this work without the need for type hints.

The following test for the Spark version of XGBoost should demonstrate the issue:
```scala
import ml.dmlc.xgboost4j.scala.spark.XGBoostRegressor

import org.json4s._
import org.json4s.jackson.Serialization

import org.apache.spark.{SparkConf, SparkContext}

import some.package.MyCustomObj

class XGBoostTests {
    val sparkConfig = new SparkConf()
        .setAppName("app")
        .setMaster("local")
        .set("spark.ui.enabled", "false")
    val sparkContext = new SparkContext(sparkConfig)

    implicit val formats: Formats = Serialization.formats(ShortTypeHints(List(classOf[MyCustomObj])))

    def testSerialization(): Unit = {
        // XGBoost model
        val xgbRegressor = new XGBoostRegressor()
            .setFeaturesCol("features")
            .setLabelCol("label")
            .setCustomObj(new MyCustomObj)
        // Try saving and loading.
        System.out.println("**** Saving and loading ****");
        xgbRegressor.write.overwrite().save("./temp-xgb-model");
        println("**************** Succesfully saved *****************")
        val xgbRegressor2 = XGBoostRegressor.load("./temp-xgb-model");
        println("**************** Succesfully loaded *****************")
    }

}
```

**Comment by trivialfis** [comment]
Hi, thanks for opening the issue.  Do you have any solution in mind?

**Comment by nicovdijk** [comment]
It took me some time to get everything to work, but I think I managed to implement a nice solution, see this [pull request](https://github.com/dmlc/xgboost/pull/7274). All feedback welcome.

I did have two other issues (maybe related to my Windows 10 system):

1. One involving `create_jni.py` where somehow a space in a path seems to mess up the maven install process.
```
'C:\Program' is not recognized as an internal or external command,
operable program or batch file.
building Java wrapper
Traceback (most recent call last):
  File "C:\Users\Some\Folder\xgboost\jvm-packages\create_jni.py", line 125, in <module>
    run("{} mapfeat.py".format(sys.executable))
  File "C:\Users\Some\Folder\xgboost\jvm-packages\create_jni.py", line 54, in run
```

2. And one involving the `numWorkers` in `PerTest.scala` that results in an error when not equal to 1 (I read something on this being related to a `"local"` Spark session).
```
21/09/28 20:07:45 ERROR XGBoostSpark: XGBooster worker 1 has failed 0 times due to 
ml.dmlc.xgboost4j.java.XGBoostError: [20:07:45] C:\Users\Some\Folder\xgboost\rabit\include\rabit/internal/utils.h:114: Socket Poll Error:WSAError-code=10022
```

Please let me know if these should be added as issues.

**Comment by wbo4958** [comment]
Looks like other guy has reported this issue before https://github.com/dmlc/xgboost/issues/5936
