### ISSUE TITLE
XGBoost4J Spark Submit Spark Cluster: XGBoostTaskFailedListener:101 - Training Task Failed during XGBoost Training

### ISSUE THREAD

**Issue by conglt98** [dmlc/xgboost#7249]
Tracker started, with env={DMLC_NUM_SERVER=0, DMLC_TRACKER_URI=0.0.0.0, DMLC_TRACKER_PORT=9092, DMLC_NUM_WORKER=2}
2021-09-22 17:23:06 ERROR XGBoostTaskFailedListener:101 - Training Task Failed during XGBoost Training: ExceptionFailure(ml.dmlc.xgboost4j.java.XGBoostError,,[Ljava.lang.StackTraceElement;@1f417a98,ml.dmlc.xgboost4j.java.XGBoostError:
	at ml.dmlc.xgboost4j.java.Rabit.checkCall(Rabit.java:53)
	at ml.dmlc.xgboost4j.java.Rabit.shutdown(Rabit.java:83)
	at ml.dmlc.xgboost4j.scala.spark.XGBoost$.buildDistributedBooster(XGBoost.scala:381)
	at ml.dmlc.xgboost4j.scala.spark.XGBoost$.$anonfun$trainForNonRanking$1(XGBoost.scala:456)
	at org.apache.spark.rdd.RDD.$anonfun$mapPartitions$2(RDD.scala:863)
	at org.apache.spark.rdd.RDD.$anonfun$mapPartitions$2$adapted(RDD.scala:863)
	at org.apache.spark.rdd.MapPartitionsRDD.compute(MapPartitionsRDD.scala:52)
	at org.apache.spark.rdd.RDD.computeOrReadCheckpoint(RDD.scala:373)
	at org.apache.spark.rdd.RDD.$anonfun$getOrCompute$1(RDD.scala:386)
	at org.apache.spark.storage.BlockManager.$anonfun$doPutIterator$1(BlockManager.scala:1423)
	at org.apache.spark.storage.BlockManager.org$apache$spark$storage$BlockManager$$doPut(BlockManager.scala:1350)
	at org.apache.spark.storage.BlockManager.doPutIterator(BlockManager.scala:1414)
	at org.apache.spark.storage.BlockManager.getOrElseUpdate(BlockManager.scala:1237)
	at org.apache.spark.rdd.RDD.getOrCompute(RDD.scala:384)
	at org.apache.spark.rdd.RDD.iterator(RDD.scala:335)
	at org.apache.spark.scheduler.ResultTask.runTask(ResultTask.scala:90)
	at org.apache.spark.scheduler.Task.run(Task.scala:131)
	at org.apache.spark.executor.Executor$TaskRunner.$anonfun$run$3(Executor.scala:497)
	at org.apache.spark.util.Utils$.tryWithSafeFinally(Utils.scala:1439)
	at org.apache.spark.executor.Executor$TaskRunner.run(Executor.scala:500)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
,Some(org.apache.spark.ThrowableSerializationWrapper@5a43f714),Vector(AccumulableInfo(461,None,Some(41220),None,false,true,None), AccumulableInfo(463,None,Some(0),None,false,true,None), AccumulableInfo(470,None,Some(0),None,false,true,None), AccumulableInfo(471,None,Some(1),None,false,true,None), AccumulableInfo(472,None,Some(0),None,false,true,None), AccumulableInfo(473,None,Some(0),None,false,true,None), AccumulableInfo(474,None,Some(2006896),None,false,true,None), AccumulableInfo(475,None,Some(0),None,false,true,None), AccumulableInfo(476,None,Some(76540),None,false,true,None)),Vector(LongAccumulator(id: 461, name: Some(internal.metrics.executorRunTime), value: 41220), LongAccumulator(id: 463, name: Some(internal.metrics.resultSize), value: 0), LongAccumulator(id: 470, name: Some(internal.metrics.shuffle.read.remoteBlocksFetched), value: 0), LongAccumulator(id: 471, name: Some(internal.metrics.shuffle.read.localBlocksFetched), value: 1), LongAccumulator(id: 472, name: Some(internal.metrics.shuffle.read.remoteBytesRead), value: 0), LongAccumulator(id: 473, name: Some(internal.metrics.shuffle.read.remoteBytesReadToDisk), value: 0), LongAccumulator(id: 474, name: Some(internal.metrics.shuffle.read.localBytesRead), value: 2006896), LongAccumulator(id: 475, name: Some(internal.metrics.shuffle.read.fetchWaitTime), value: 0), LongAccumulator(id: 476, name: Some(internal.metrics.shuffle.read.recordsRead), value: 76540)),WrappedArray(874358296, 122789376, 0, 0, 1621140, 0, 1621140, 0, 784523, 0, 0, 0, 0, 0, 0, 0, 5, 397, 3, 354)), stopping SparkContext
2021-09-22 17:23:06 ERROR XGBoostTaskFailedListener:101 - Training Task Failed during XGBoost Training: ExceptionFailure(ml.dmlc.xgboost4j.java.XGBoostError,,[Ljava.lang.StackTraceElement;@79d85b40,ml.dmlc.xgboost4j.java.XGBoostError:
	at ml.dmlc.xgboost4j.java.Rabit.checkCall(Rabit.java:53)
	at ml.dmlc.xgboost4j.java.Rabit.shutdown(Rabit.java:83)
	at ml.dmlc.xgboost4j.scala.spark.XGBoost$.buildDistributedBooster(XGBoost.scala:381)
	at ml.dmlc.xgboost4j.scala.spark.XGBoost$.$anonfun$trainForNonRanking$1(XGBoost.scala:456)

How to fix this problems ?

**Comment by trivialfis** [comment]
Hi, do you have a reproducible example?

**Comment by conglt98** [comment]
> Hi, do you have a reproducible example?
I use this config. I have run training in InteliJ local and success. Then I build file Jar and push it to server. 

val xgbParam = Map("eta" -> 0.1f,
      "max_depth" -> 10,
      "missing" -> -1,
      "allow_non_zero_for_missing" -> "true",
      "objective" -> "binary:logistic",
      "num_round" -> 50,
      "num_workers" -> 2,
      "tracker_conf" -> TrackerConf(60 * 60 * 1000, typeTracker),
      "timeout_request_workers" -> timeoutWorker)
    val xgbClassifier = new XGBoostClassifier(xgbParam).
      setWeightCol("classWeightCol").
      setFeaturesCol("features").
      setLabelCol("status")
    val xgbClassificationModel = xgbClassifier.fit(training)

I submit this Jar with Spark and then it training failed.
$SPARK_HOME/bin/spark-submit \
--class MainClass.RunTrainingModel \
--master spark://server:8888 --driver-memory 3G --executor-memory 3G \
--total-executor-cores 3 \
--conf "spark.ui.port=8080"  module-training-1.0-SNAPSHOT.jar

**Comment by trivialfis** [comment]
Thanks, could you please share a self-contain, reproducible example that I can run on my machine and see the error?

**Comment by conglt98** [comment]
Sr because this project is so complex and privacy, after i rerun, the log become as below:

Tracker started, with env={DMLC_NUM_SERVER=0, DMLC_TRACKER_URI=0.0.0.0, DMLC_TRACKER_PORT=9092, DMLC_NUM_WORKER=2}
2021-09-22 21:46:52 WARN  TaskSetManager:69 - Lost task 0.0 in stage 10.0 (TID 10) (10.60.xx.xx executor 11): ml.dmlc.xgboost4j.java.XGBoostError: Failed to shutdown RABIT worker.
	at ml.dmlc.xgboost4j.java.Rabit.checkCall(Rabit.java:53)
	at ml.dmlc.xgboost4j.java.Rabit.shutdown(Rabit.java:83)
	at ml.dmlc.xgboost4j.scala.spark.XGBoost$.buildDistributedBooster(XGBoost.scala:424)
	at ml.dmlc.xgboost4j.scala.spark.XGBoost$.$anonfun$trainForNonRanking$1(XGBoost.scala:499)
	at org.apache.spark.rdd.RDD.$anonfun$mapPartitions$2(RDD.scala:863)
	at org.apache.spark.rdd.RDD.$anonfun$mapPartitions$2$adapted(RDD.scala:863)
	at org.apache.spark.rdd.MapPartitionsRDD.compute(MapPartitionsRDD.scala:52)
	at org.apache.spark.rdd.RDD.computeOrReadCheckpoint(RDD.scala:373)
	at org.apache.spark.rdd.RDD.$anonfun$getOrCompute$1(RDD.scala:386)
	at org.apache.spark.storage.BlockManager.$anonfun$doPutIterator$1(BlockManager.scala:1423)
	at org.apache.spark.storage.BlockManager.org$apache$spark$storage$BlockManager$$doPut(BlockManager.scala:1350)
	at org.apache.spark.storage.BlockManager.doPutIterator(BlockManager.scala:1414)
	at org.apache.spark.storage.BlockManager.getOrElseUpdate(BlockManager.scala:1237)
	at org.apache.spark.rdd.RDD.getOrCompute(RDD.scala:384)
	at org.apache.spark.rdd.RDD.iterator(RDD.scala:335)
	at org.apache.spark.scheduler.ResultTask.runTask(ResultTask.scala:90)
	at org.apache.spark.scheduler.Task.run(Task.scala:131)
	at org.apache.spark.executor.Executor$TaskRunner.$anonfun$run$3(Executor.scala:497)
	at org.apache.spark.util.Utils$.tryWithSafeFinally(Utils.scala:1439)
	at org.apache.spark.executor.Executor$TaskRunner.run(Executor.scala:500)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)

2021-09-22 21:46:52 ERROR XGBoostTaskFailedListener:125 - Training Task Failed during XGBoost Training: ExceptionFailure(ml.dmlc.xgboost4j.java.XGBoostError,Failed to shutdown RABIT worker.,[Ljava.lang.StackTraceElement;@456d0119,ml.dmlc.xgboost4j.java.XGBoostError: Failed to shutdown RABIT worker.
	at ml.dmlc.xgboost4j.java.Rabit.checkCall(Rabit.java:53)
	at ml.dmlc.xgboost4j.java.Rabit.shutdown(Rabit.java:83)
	at ml.dmlc.xgboost4j.scala.spark.XGBoost$.buildDistributedBooster(XGBoost.scala:424)
	at ml.dmlc.xgboost4j.scala.spark.XGBoost$.$anonfun$trainForNonRanking$1(XGBoost.scala:499)
	at org.apache.spark.rdd.RDD.$anonfun$mapPartitions$2(RDD.scala:863)
	at org.apache.spark.rdd.RDD.$anonfun$mapPartitions$2$adapted(RDD.scala:863)
	at org.apache.spark.rdd.MapPartitionsRDD.compute(MapPartitionsRDD.scala:52)
	at org.apache.spark.rdd.RDD.computeOrReadCheckpoint(RDD.scala:373)
	at org.apache.spark.rdd.RDD.$anonfun$getOrCompute$1(RDD.scala:386)
	at org.apache.spark.storage.BlockManager.$anonfun$doPutIterator$1(BlockManager.scala:1423)
	at org.apache.spark.storage.BlockManager.org$apache$spark$storage$BlockManager$$doPut(BlockManager.scala:1350)
	at org.apache.spark.storage.BlockManager.doPutIterator(BlockManager.scala:1414)
	at org.apache.spark.storage.BlockManager.getOrElseUpdate(BlockManager.scala:1237)
	at org.apache.spark.rdd.RDD.getOrCompute(RDD.scala:384)
	at org.apache.spark.rdd.RDD.iterator(RDD.scala:335)
	at org.apache.spark.scheduler.ResultTask.runTask(ResultTask.scala:90)
	at org.apache.spark.scheduler.Task.run(Task.scala:131)
	at org.apache.spark.executor.Executor$TaskRunner.$anonfun$run$3(Executor.scala:497)
	at org.apache.spark.util.Utils$.tryWithSafeFinally(Utils.scala:1439)
	at org.apache.spark.executor.Executor$TaskRunner.run(Executor.scala:500)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
,Some(org.apache.spark.ThrowableSerializationWrapper@6f97d0),Vector(AccumulableInfo(461,None,Some(42170),None,false,true,None), AccumulableInfo(463,None,Some(0),None,false,true,None), AccumulableInfo(470,None,Some(0),None,false,true,None), AccumulableInfo(471,None,Some(1),None,false,true,None), AccumulableInfo(472,None,Some(0),None,false,true,None), AccumulableInfo(473,None,Some(0),None,false,true,None), AccumulableInfo(474,None,Some(2023557),None,false,true,None), AccumulableInfo(475,None,Some(38),None,false,true,None), AccumulableInfo(476,None,Some(76541),None,false,true,None)),Vector(LongAccumulator(id: 461, name: Some(internal.metrics.executorRunTime), value: 42170), LongAccumulator(id: 463, name: Some(internal.metrics.resultSize), value: 0), LongAccumulator(id: 470, name: Some(internal.metrics.shuffle.read.remoteBlocksFetched), value: 0), LongAccumulator(id: 471, name: Some(internal.metrics.shuffle.read.localBlocksFetched), value: 1), LongAccumulator(id: 472, name: Some(internal.metrics.shuffle.read.remoteBytesRead), value: 0), LongAccumulator(id: 473, name: Some(internal.metrics.shuffle.read.remoteBytesReadToDisk), value: 0), LongAccumulator(id: 474, name: Some(internal.metrics.shuffle.read.localBytesRead), value: 2023557), LongAccumulator(id: 475, name: Some(internal.metrics.shuffle.read.fetchWaitTime), value: 38), LongAccumulator(id: 476, name: Some(internal.metrics.shuffle.read.recordsRead), value: 76541)),WrappedArray(391596400, 67940496, 0, 0, 29015, 0, 29015, 0, 12648, 0, 0, 0, 0, 0, 0, 0, 2, 49, 2, 123))
2021-09-22 21:46:52 ERROR XGBoostTaskFailedListener:127 - killing SparkContext
2021-09-22 21:46:52 ERROR XGBoostTaskFailedListener:125 - Training Task Failed during XGBoost Training: ExceptionFailure(ml.dmlc.xgboost4j.java.XGBoostError,Failed to shutdown RABIT worker.,[Ljava.lang.StackTraceElement;@6f1ee6d2,ml.dmlc.xgboost4j.java.XGBoostError: Failed to shutdown RABIT worker.
	at ml.dmlc.xgboost4j.java.Rabit.checkCall(Rabit.java:53)
	at ml.dmlc.xgboost4j.java.Rabit.shutdown(Rabit.java:83)
	at ml.dmlc.xgboost4j.scala.spark.XGBoost$.buildDistributedBooster(XGBoost.scala:424)
	at ml.dmlc.xgboost4j.scala.spark.XGBoost$.$anonfun$trainForNonRanking$1(XGBoost.scala:499)
	at org.apache.spark.rdd.RDD.$anonfun$mapPartitions$2(RDD.scala:863)
	at org.apache.spark.rdd.RDD.$anonfun$mapPartitions$2$adapted(RDD.scala:863)
	at org.apache.spark.rdd.MapPartitionsRDD.compute(MapPartitionsRDD.scala:52)
	at org.apache.spark.rdd.RDD.computeOrReadCheckpoint(RDD.scala:373)
	at org.apache.spark.rdd.RDD.$anonfun$getOrCompute$1(RDD.scala:386)
	at org.apache.spark.storage.BlockManager.$anonfun$doPutIterator$1(BlockManager.scala:1423)
	at org.apache.spark.storage.BlockManager.org$apache$spark$storage$BlockManager$$doPut(BlockManager.scala:1350)
	at org.apache.spark.storage.BlockManager.doPutIterator(BlockManager.scala:1414)
	at org.apache.spark.storage.BlockManager.getOrElseUpdate(BlockManager.scala:1237)
	at org.apache.spark.rdd.RDD.getOrCompute(RDD.scala:384)
	at org.apache.spark.rdd.RDD.iterator(RDD.scala:335)
	at org.apache.spark.scheduler.ResultTask.runTask(ResultTask.scala:90)
	at org.apache.spark.scheduler.Task.run(Task.scala:131)
	at org.apache.spark.executor.Executor$TaskRunner.$anonfun$run$3(Executor.scala:497)
	at org.apache.spark.util.Utils$.tryWithSafeFinally(Utils.scala:1439)
	at org.apache.spark.executor.Executor$TaskRunner.run(Executor.scala:500)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
,Some(org.apache.spark.ThrowableSerializationWrapper@761b689f),Vector(AccumulableInfo(461,None,Some(42215),None,false,true,None), AccumulableInfo(463,None,Some(0),None,false,true,None), AccumulableInfo(464,None,Some(297),None,false,true,None), AccumulableInfo(470,None,Some(0),None,false,true,None), AccumulableInfo(471,None,Some(1),None,false,true,None), AccumulableInfo(472,None,Some(0),None,false,true,None), AccumulableInfo(473,None,Some(0),None,false,true,None), AccumulableInfo(474,None,Some(2026494),None,false,true,None), AccumulableInfo(475,None,Some(0),None,false,true,None), AccumulableInfo(476,None,Some(76540),None,false,true,None)),Vector(LongAccumulator(id: 461, name: Some(internal.metrics.executorRunTime), value: 42215), LongAccumulator(id: 463, name: Some(internal.metrics.resultSize), value: 0), LongAccumulator(id: 464, name: Some(internal.metrics.jvmGCTime), value: 297), LongAccumulator(id: 470, name: Some(internal.metrics.shuffle.read.remoteBlocksFetched), value: 0), LongAccumulator(id: 471, name: Some(internal.metrics.shuffle.read.localBlocksFetched), value: 1), LongAccumulator(id: 472, name: Some(internal.metrics.shuffle.read.remoteBytesRead), value: 0), LongAccumulator(id: 473, name: Some(internal.metrics.shuffle.read.remoteBytesReadToDisk), value: 0), LongAccumulator(id: 474, name: Some(internal.metrics.shuffle.read.localBytesRead), value: 2026494), LongAccumulator(id: 475, name: Some(internal.metrics.shuffle.read.fetchWaitTime), value: 0), LongAccumulator(id: 476, name: Some(internal.metrics.shuffle.read.recordsRead), value: 76540)),WrappedArray(301170088, 119279992, 0, 0, 1301529, 0, 1301529, 0, 785342, 0, 0, 0, 0, 0, 0, 0, 6, 529, 3, 352))
2021-09-22 21:46:52 ERROR XGBoostTaskFailedListener:127 - killing SparkContext
2021-09-22 21:46:52 ERROR RabitTracker:91 - Uncaught exception thrown by worker:
org.apache.spark.SparkException: Job 6 cancelled because SparkContext was shut down
	at org.apache.spark.scheduler.DAGScheduler.$anonfun$cleanUpAfterSchedulerStop$1(DAGScheduler.scala:1085)
	at org.apache.spark.scheduler.DAGScheduler.$anonfun$cleanUpAfterSchedulerStop$1$adapted(DAGScheduler.scala:1083)
	at scala.collection.mutable.HashSet.foreach(HashSet.scala:79)
	at org.apache.spark.scheduler.DAGScheduler.cleanUpAfterSchedulerStop(DAGScheduler.scala:1083)
	at org.apache.spark.scheduler.DAGSchedulerEventProcessLoop.onStop(DAGScheduler.scala:2463)
	at org.apache.spark.util.EventLoop.stop(EventLoop.scala:84)
	at org.apache.spark.scheduler.DAGScheduler.stop(DAGScheduler.scala:2369)
	at org.apache.spark.SparkContext.$anonfun$stop$12(SparkContext.scala:2069)
	at org.apache.spark.util.Utils$.tryLogNonFatalError(Utils.scala:1419)
	at org.apache.spark.SparkContext.stop(SparkContext.scala:2069)
	at org.apache.spark.TaskFailedListener$$anon$2.$anonfun$run$2(SparkParallelismTracker.scala:164)
	at org.apache.spark.TaskFailedListener$$anon$2.$anonfun$run$2$adapted(SparkParallelismTracker.scala:164)
	at scala.Option.foreach(Option.scala:407)
	at org.apache.spark.TaskFailedListener$$anon$2.$anonfun$run$1(SparkParallelismTracker.scala:164)
	at scala.runtime.java8.JFunction0$mcV$sp.apply(JFunction0$mcV$sp.java:23)
	at scala.util.DynamicVariable.withValue(DynamicVariable.scala:62)
	at org.apache.spark.TaskFailedListener$$anon$2.run(SparkParallelismTracker.scala:163)
	at org.apache.spark.scheduler.DAGScheduler.runJob(DAGScheduler.scala:868)
	at org.apache.spark.SparkContext.runJob(SparkContext.scala:2196)
	at org.apache.spark.SparkContext.runJob(SparkContext.scala:2217)
	at org.apache.spark.SparkContext.runJob(SparkContext.scala:2236)
	at org.apache.spark.SparkContext.runJob(SparkContext.scala:2261)
	at org.apache.spark.rdd.RDD.$anonfun$foreachPartition$1(RDD.scala:1020)
	at org.apache.spark.rdd.RDDOperationScope$.withScope(RDDOperationScope.scala:151)
	at org.apache.spark.rdd.RDDOperationScope$.withScope(RDDOperationScope.scala:112)
	at org.apache.spark.rdd.RDD.withScope(RDD.scala:414)
	at org.apache.spark.rdd.RDD.foreachPartition(RDD.scala:1018)
	at ml.dmlc.xgboost4j.scala.spark.XGBoost$$anon$1.run(XGBoost.scala:612)
2021-09-22 21:46:57 ERROR XGBoostSpark:639 - the job was aborted due to
ml.dmlc.xgboost4j.java.XGBoostError: XGBoostModel training failed
	at ml.dmlc.xgboost4j.scala.spark.XGBoost$.postTrackerReturnProcessing(XGBoost.scala:746)
	at ml.dmlc.xgboost4j.scala.spark.XGBoost$.trainDistributed(XGBoost.scala:620)
	at ml.dmlc.xgboost4j.scala.spark.XGBoostClassifier.train(XGBoostClassifier.scala:199)
	at ml.dmlc.xgboost4j.scala.spark.XGBoostClassifier.train(XGBoostClassifier.scala:40)
	at org.apache.spark.ml.Predictor.fit(Predictor.scala:151)
	at com.zalopay.ml.algorithms.XGBoostSpark$.main(XGBoostSpark.scala:62)
	at com.zalopay.ml.algorithms.XGBoostSpark.main(XGBoostSpark.scala)
	at MainClass.RunTrainingModel.main(RunTrainingModel.java:6)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.apache.spark.deploy.JavaMainApplication.start(SparkApplication.scala:52)
	at org.apache.spark.deploy.SparkSubmit.org$apache$spark$deploy$SparkSubmit$$runMain(SparkSubmit.scala:951)
	at org.apache.spark.deploy.SparkSubmit.doRunMain$1(SparkSubmit.scala:180)
	at org.apache.spark.deploy.SparkSubmit.submit(SparkSubmit.scala:203)
	at org.apache.spark.deploy.SparkSubmit.doSubmit(SparkSubmit.scala:90)
	at org.apache.spark.deploy.SparkSubmit$$anon$2.doSubmit(SparkSubmit.scala:1039)
	at org.apache.spark.deploy.SparkSubmit$.main(SparkSubmit.scala:1048)
	at org.apache.spark.deploy.SparkSubmit.main(SparkSubmit.scala)

**Comment by conglt98** [comment]
Does it need a permission on executors ? Can rabit not connect the tracker so the:
TaskSetManager:69 - Lost task 0.0 in stage 10.0 (TID 10) (10.60.xx.xx executor 11) ???

**Comment by trivialfis** [comment]
Usually, it's something wrong that happened in the main tracker process, possibly killed by the launching processed due to failure in some workers, then the rest of the workers fail to connect the tracker for shutdown operation.  Without a reproducible example I can't guess the exact cause.

**Comment by conglt98** [comment]
Tks you. But, can I ask you a question. This xgboost4J-Spark was built into Jar. It was deployed on Spark Clusters which on multiple machines. Does it need to run a rabit tracker or config rabit tracker before submit this jars to spark-submit?
And how to config RabitTracker ?

**Comment by trivialfis** [comment]
It's automatically configured.
