### ISSUE TITLE
ml.dmlc.xgboost4j.java.XGBoostError: XGBoostModel training failed

### ISSUE THREAD

**Issue by withing1113** [dmlc/xgboost#7266]
Exception in thread "main" ml.dmlc.xgboost4j.java.XGBoostError: XGBoostModel training failed at ml.dmlc.xgboost4j.scala.spark.XGBoost$.ml$dmlc$xgboost4j$scala$spark$XGBoost$$postTrackerReturnProcessing(XGBoost.scala:582)
	at ml.dmlc.xgboost4j.scala.spark.XGBoost$$anonfun$trainDistributed$2.apply(XGBoost.scala:459)
	at ml.dmlc.xgboost4j.scala.spark.XGBoost$$anonfun$trainDistributed$2.apply(XGBoost.scala:435)
	at scala.collection.TraversableLike$$anonfun$map$1.apply(TraversableLike.scala:234)
	at scala.collection.TraversableLike$$anonfun$map$1.apply(TraversableLike.scala:234)
	at scala.collection.immutable.List.foreach(List.scala:392)
	at scala.collection.TraversableLike$class.map(TraversableLike.scala:234)
	at scala.collection.immutable.List.map(List.scala:296)
	at ml.dmlc.xgboost4j.scala.spark.XGBoost$.trainDistributed(XGBoost.scala:434)
	at ml.dmlc.xgboost4j.scala.spark.XGBoostClassifier.train(XGBoostClassifier.scala:194)
	at ml.dmlc.xgboost4j.scala.spark.XGBoostClassifier.train(XGBoostClassifier.scala:44)
	at org.apache.spark.ml.Predictor.fit(Predictor.scala:118)
	at XgbRunTest$.main(XgbRunTest.scala:55)
	at XgbRunTest.main(XgbRunTest.scala)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at org.apache.spark.deploy.JavaMainApplication.start(SparkApplication.scala:52)
	at org.apache.spark.deploy.SparkSubmit.org$apache$spark$deploy$SparkSubmit$$runMain(SparkSubmit.scala:852)
	at org.apache.spark.deploy.SparkSubmit.doRunMain$1(SparkSubmit.scala:161)
	at org.apache.spark.deploy.SparkSubmit.submit(SparkSubmit.scala:184)
	at org.apache.spark.deploy.SparkSubmit.doSubmit(SparkSubmit.scala:86)
	at org.apache.spark.deploy.SparkSubmit$$anon$2.doSubmit(SparkSubmit.scala:927)
	at org.apache.spark.deploy.SparkSubmit$.main(SparkSubmit.scala:936)
	at org.apache.spark.deploy.SparkSubmit.main(SparkSubmit.scala)
21/09/27 16:17:56 ERROR RabitTracker: Uncaught exception thrown by worker:
java.lang.InterruptedException
	at java.util.concurrent.locks.AbstractQueuedSynchronizer.doAcquireSharedInterruptibly(AbstractQueuedSynchronizer.java:998)
	at java.util.concurrent.locks.AbstractQueuedSynchronizer.acquireSharedInterruptibly(AbstractQueuedSynchronizer.java:1304)
	at scala.concurrent.impl.Promise$DefaultPromise.tryAwait(Promise.scala:206)
	at scala.concurrent.impl.Promise$DefaultPromise.ready(Promise.scala:222)
	at scala.concurrent.impl.Promise$DefaultPromise.ready(Promise.scala:157)
	at org.apache.spark.util.ThreadUtils$.awaitReady(ThreadUtils.scala:260)
	at org.apache.spark.scheduler.DAGScheduler.runJob(DAGScheduler.scala:729)
	at org.apache.spark.SparkContext.runJob(SparkContext.scala:2064)
	at org.apache.spark.SparkContext.runJob(SparkContext.scala:2085)
	at org.apache.spark.SparkContext.runJob(SparkContext.scala:2104)
	at org.apache.spark.SparkContext.runJob(SparkContext.scala:2129)
	at org.apache.spark.rdd.RDD$$anonfun$foreachPartition$1.apply(RDD.scala:990)
	at org.apache.spark.rdd.RDD$$anonfun$foreachPartition$1.apply(RDD.scala:988)
	at org.apache.spark.rdd.RDDOperationScope$.withScope(RDDOperationScope.scala:151)
	at org.apache.spark.rdd.RDDOperationScope$.withScope(RDDOperationScope.scala:112)
	at org.apache.spark.rdd.RDD.withScope(RDD.scala:385)
	at org.apache.spark.rdd.RDD.foreachPartition(RDD.scala:988)
	at ml.dmlc.xgboost4j.scala.spark.XGBoost$$anonfun$trainDistributed$2$$anon$1.run(XGBoost.scala:452)

the spark stage fail details:
repartition at XGBoost.scala:491+details
org.apache.spark.rdd.RDD.repartition(RDD.scala:442)
ml.dmlc.xgboost4j.scala.spark.XGBoost$.repartitionForTraining(XGBoost.scala:491)
ml.dmlc.xgboost4j.scala.spark.XGBoost$.composeInputData(XGBoost.scala:407)
ml.dmlc.xgboost4j.scala.spark.XGBoost$.trainDistributed(XGBoost.scala:429)
ml.dmlc.xgboost4j.scala.spark.XGBoostClassifier.train(XGBoostClassifier.scala:194)
ml.dmlc.xgboost4j.scala.spark.XGBoostClassifier.train(XGBoostClassifier.scala:44)
org.apache.spark.ml.Predictor.fit(Predictor.scala:118)
XgbRunTest$.main(XgbRunTest.scala:55)
XgbRunTest.main(XgbRunTest.scala)
sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
java.lang.reflect.Method.invoke(Method.java:497)
org.apache.spark.deploy.JavaMainApplication.start(SparkApplication.scala:52)
org.apache.spark.deploy.SparkSubmit.org$apache$spark$deploy$SparkSubmit$$runMain(SparkSubmit.scala:852)
org.apache.spark.deploy.SparkSubmit.doRunMain$1(SparkSubmit.scala:161)
org.apache.spark.deploy.SparkSubmit.submit(SparkSubmit.scala:184)
org.apache.spark.deploy.SparkSubmit.doSubmit(SparkSubmit.scala:86)
org.apache.spark.deploy.SparkSubmit$$anon$2.doSubmit(SparkSubmit.scala:927)
org.apache.spark.deploy.SparkSubmit$.main(SparkSubmit.scala:936)

**Comment by trivialfis** [comment]
Hi, could you please share a self-contain reproducible example that I can run?

**Comment by withing1113** [comment]
Of course sure. I will send to you later.






颂安，祝好~
On 09/27/2021 18:47, Jiaming Yuan wrote:

Hi, could you please share a self-contain reproducible example that I can run?

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by withing1113** [comment]
> Hi, could you please share a self-contain reproducible example that I can run?
> 
> > java.lang.InterruptedException
> 
> I can't guess what's happening from such exception.

```
import org.apache.spark.sql.SparkSession
import ml.dmlc.xgboost4j.scala.spark.XGBoost

import ml.dmlc.xgboost4j.scala.spark.{XGBoostClassificationModel, XGBoostClassifier, XGBoost}
import org.apache.spark.sql.types.{DoubleType, StringType, StructField, StructType}

object XgbRunTest {
  def main(args: Array[String]): Unit = {
    val spark = SparkSession
      .builder()
      .appName("test_xgb")
      //.config("spark.serializer", "org.apache.spark.serializer.KryoSerializer")
      //.config("spark.rdd.compress", "true")
      //.config("spark.io.compression.codec", "org.Apache.Spark.io.SnnapyCompressionCodec")
      //.config("spark.local.dir","/da2/jiangshuai")
      //.config("spark.shuffle.consolidateFiles","true")  //开启Map端小文件合并
      .enableHiveSupport()
      .getOrCreate()

    import org.apache.spark.sql.SparkSession
    import org.apache.spark.sql.types.{DoubleType, StringType, StructField, StructType}

    val input_path = "iris.data"
    val schema = new StructType(Array(
      StructField("sepal length", DoubleType, true),
      StructField("sepal width", DoubleType, true),
      StructField("petal length", DoubleType, true),
      StructField("petal width", DoubleType, true),
      StructField("class", StringType, true)))
    val rawInput = spark.read.schema(schema).csv(input_path)

    import org.apache.spark.ml.feature.StringIndexer
    val stringIndexer = new StringIndexer().
      setInputCol("class").
      setOutputCol("classIndex").
      fit(rawInput)
    val labelTransformed = stringIndexer.transform(rawInput).drop("class")

    import org.apache.spark.ml.feature.VectorAssembler
    val vectorAssembler = new VectorAssembler().
      setInputCols(Array("sepal length", "sepal width", "petal length", "petal width")).
      setOutputCol("features")
    val xgbInput = vectorAssembler.transform(labelTransformed).select("features", "classIndex")

    import ml.dmlc.xgboost4j.scala.spark.XGBoostClassifier
    val xgbParam = Map("eta" -> 0.1f,
      "missing" -> -999,
      "max_depth" -> 2,
      "objective" -> "multi:softprob",
      "num_class" -> 3,
      "num_round" -> 100,
      "num_workers" -> 2)
    val xgbClassifier = new XGBoostClassifier(xgbParam).
      setFeaturesCol("features").
      setLabelCol("classIndex")

    val xgbClassificationModel = xgbClassifier.fit(xgbInput)
    val valid_res = xgbClassificationModel.transform(xgbInput)
    print(valid_res.show(false))
    spark.stop()
  }
}

```
Actually, this is an example from https://xgboost.readthedocs.io/en/latest/jvm/xgboost4j_spark_tutorial.html.

**Comment by withing1113** [comment]
spark version:2.4，scala version: 2.11, xgboost version:0.90
This is the spark submit codes:
    /usr/bin/hadoop/software/spark2.4/bin/spark-submit \
    --jars scalaj-http_2.11-2.4.1.jar,xgboost4j-spark-0.90.jar,xgboost4j-0.90.jar \
    --priority VERY_HIGH \
    --queue $best_queue \
    --driver-memory 6G \
    --executor-memory 10G \
    --num-executors 12 \
    --conf spark.dynamicAllocation.enabled=false \
    --conf spark.executor.memoryOverhead=3G \
    --executor-cores 1 \
    --conf spark.sql.shuffle.partitions=1 \
    --conf spark.storage.memoryFraction=0.6 \
    --master yarn \
    --deploy-mode client \
    --class XgbRunTest \
    XgbTest.jar

**Comment by trivialfis** [comment]
I don't think we still support 0.90.  Feel free to reopen if this is reproducible using latest xgboost.
