### ISSUE TITLE
XGBoostClassifier fails to train on a large (>6TB) distributed dataset in a cluster

### ISSUE THREAD

**Issue by monicasenapati** [dmlc/xgboost#7288]
Hi, I have tried tweaking the number of executors, executor memory for spark-submit as well as the num_workers in XGBoost params set. However, I keep running into the following error:
```
21/10/06 02:25:47 INFO XGBoostClassifier: ml.dmlc.xgboost4j.scala.spark.XGBoostClassifier inferred 2 classes for labelCol=xgbc_1a1a7b72ecd0__labelCol since numClasses was not specified in the column metadata.
21/10/06 02:25:47 INFO XGBoostSpark: Running XGBoost 1.1.0 with parameters:

alpha -> 0.0
min_child_weight -> 1.0
sample_type -> uniform
base_score -> 0.5
rabit_timeout -> -1
colsample_bylevel -> 1.0
grow_policy -> depthwise
skip_drop -> 0.0
lambda_bias -> 0.0
silent -> 0
scale_pos_weight -> 104.0
seed -> 0
cache_training_set -> false
features_col -> features
num_early_stopping_rounds -> 5
label_col -> isPossiblySensitive
num_workers -> 27
subsample -> 1.0
lambda -> 1.0
max_depth -> 2
probability_col -> probability
raw_prediction_col -> rawPrediction
tree_limit -> 0
custom_eval -> null
dmlc_worker_connect_retry -> 5
rate_drop -> 0.0
max_bin -> 16
train_test_ratio -> 1.0
use_external_memory -> false
objective -> binary:logistic
eval_metric -> error
num_round -> 10
maximize_evaluation_metrics -> true
timeout_request_workers -> 1800000
missing -> 0.0
rabit_ring_reduce_threshold -> 32768
checkpoint_path -> 
tracker_conf -> TrackerConf(0,python)
tree_method -> hist
max_delta_step -> 0.0
eta -> 0.1
verbosity -> 1
colsample_bytree -> 1.0
normalize_type -> tree
allow_non_zero_for_missing -> false
custom_obj -> null
gamma -> 0.0
sketch_eps -> 0.03
nthread -> 1
prediction_col -> prediction
checkpoint_interval -> -1
21/10/06 02:25:47 WARN XGBoostSpark: train_test_ratio is deprecated since XGBoost 0.82, we recommend to explicitly pass a training and multiple evaluation datasets by passing 'eval_sets' and 'eval_set_names'
Tracker started, with env={DMLC_NUM_SERVER=0, DMLC_TRACKER_URI=130.127.133.143, DMLC_TRACKER_PORT=9091, DMLC_NUM_WORKER=27}
21/10/06 02:25:47 INFO RabitTracker$TrackerProcessLogger: 2021-10-06 04:25:47,864 INFO start listen on 130.127.133.143:9091
21/10/06 02:25:47 INFO XGBoostSpark: starting training with timeout set as 1800000 ms for waiting for resources
21/10/06 02:38:09 ERROR XGBoostTaskFailedListener: Training Task Failed during XGBoost Training: ExecutorLostFailure(13,true,Some(Remote RPC client disassociated. Likely due to containers exceeding thresholds, or network issues. Check driver logs for WARN messages.)), stopping SparkContext
21/10/06 02:38:09 ERROR RabitTracker: Uncaught exception thrown by worker:
org.apache.spark.SparkException: Job 12 cancelled because SparkContext was shut down
	at org.apache.spark.scheduler.DAGScheduler.$anonfun$cleanUpAfterSchedulerStop$1(DAGScheduler.scala:1085)
	at org.apache.spark.scheduler.DAGScheduler.$anonfun$cleanUpAfterSchedulerStop$1$adapted(DAGScheduler.scala:1083)
	at scala.collection.mutable.HashSet.foreach(HashSet.scala:79)
	at org.apache.spark.scheduler.DAGScheduler.cleanUpAfterSchedulerStop(DAGScheduler.scala:1083)
	at org.apache.spark.scheduler.DAGSchedulerEventProcessLoop.onStop(DAGScheduler.scala:2463)
	at org.apache.spark.util.EventLoop.stop(EventLoop.scala:84)
	at org.apache.spark.scheduler.DAGScheduler.stop(DAGScheduler.scala:2369)
	at org.apache.spark.SparkContext.$anonfun$stop$12(SparkContext.scala:2069)
	at org.apache.spark.util.Utils$.tryLogNonFatalError(Utils.scala:1419)
	at org.apache.spark.SparkContext.stop(SparkContext.scala:2069)
	at org.apache.spark.TaskFailedListener$$anon$2.$anonfun$run$1(SparkParallelismTracker.scala:119)
	at scala.runtime.java8.JFunction0$mcV$sp.apply(JFunction0$mcV$sp.java:23)
	at scala.util.DynamicVariable.withValue(DynamicVariable.scala:62)
	at org.apache.spark.TaskFailedListener$$anon$2.run(SparkParallelismTracker.scala:119)
	at org.apache.spark.scheduler.DAGScheduler.runJob(DAGScheduler.scala:868)
	at org.apache.spark.SparkContext.runJob(SparkContext.scala:2196)
	at org.apache.spark.SparkContext.runJob(SparkContext.scala:2217)
	at org.apache.spark.SparkContext.runJob(SparkContext.scala:2236)
	at org.apache.spark.SparkContext.runJob(SparkContext.scala:2261)
	at org.apache.spark.rdd.RDD.$anonfun$foreachPartition$1(RDD.scala:1020)
	at org.apache.spark.rdd.RDDOperationScope$.withScope(RDDOperationScope.scala:151)
	at org.apache.spark.rdd.RDDOperationScope$.withScope(RDDOperationScope.scala:112)
	at org.apache.spark.rdd.RDD.withScope(RDD.scala:414)
	at org.apache.spark.rdd.RDD.foreachPartition(RDD.scala:1018)
	at ml.dmlc.xgboost4j.scala.spark.XGBoost$$anon$1.run(XGBoost.scala:565)
java.util.concurrent.RejectedExecutionException: Task scala.concurrent.impl.CallbackRunnable@7b8a5cb4 rejected from java.util.concurrent.ThreadPoolExecutor@7bcd6cfe[Terminated, pool size = 0, active threads = 0, queued tasks = 0, completed tasks = 4925]
```

I would sincerely appreciate any help in figuring out what could potentially cause this or how I can address this issue. Thank you in advance!

**Comment by trivialfis** [comment]
Your system doesn't have enough memory for spark.

**Comment by monicasenapati** [comment]
Hi @trivialfis ! Thank you for the quick response. Could you please give me some additional information on what does it mean when "system doesn't have enough memory for spark"?

**Comment by trivialfis** [comment]
> terminate called after throwing an instance of 'std::bad_alloc'

This is an error that indicates memory allocation failure.
