### ISSUE TITLE
model slice problem

### ISSUE THREAD

**Issue by 7starsea** [dmlc/xgboost#7327]
I trained a xgb model with early-stopping and then slice the final model to get the best model. Some problem occurs when using the best model to predict.

I wrote a sample code to reproduce the error and here is the link https://github.com/7starsea/xgboost-testing/blob/master/test_model_slice.py with test_data https://github.com/7starsea/xgboost-testing/blob/master/test_xgb.npz
```
import numpy as np
import xgboost as xgb
from sklearn.model_selection import train_test_split
from sklearn.metrics import roc_auc_score, r2_score

sample, m = 1000, 10
# rx, ry = np.random.rand(sample, m), np.random.rand(sample)
# np.savez('test_xgb.npz', rx=rx, ry=ry)

d = np.load('test_xgb.npz')
rx, ry = d['rx'][:], d['ry'][:]

def get_slice_model(m):
    assert isinstance(m, xgb.Booster)
    if hasattr(m, 'best_ntree_limit') and m.best_ntree_limit > 0:
        n = m.best_ntree_limit + 1
        print("best_ntree_limit", n, m.best_iteration)
        return m[0:n]
    return m


def train_model(rx, ry):
    rx, rx_v, ry, ry_v = train_test_split(rx, ry, test_size=0.2, shuffle=False)

    dtrain = xgb.DMatrix(rx, label=ry)
    dval = xgb.DMatrix(rx_v, label=ry_v)

    m = xgb.train({'objective': 'reg:squarederror'}, dtrain, 200, evals=[(dval, "validation")],
                  early_stopping_rounds=20, verbose_eval=False)
    print(m.attributes())
    m.predict(dtrain)
    m = get_slice_model(m)
    # m.predict(dtrain)
    print('inner:', m.num_boosted_rounds(), m.num_features())
    return m


def run_test():
    m = train_model(rx, ry)
    print('outer:', m.num_boosted_rounds(), m.num_features())
    m.inplace_predict(rx)


if __name__ == '__main__':
    run_test()
```

On my machine, sometimes the output is normal
```
{'best_iteration': '0', 'best_ntree_limit': '1', 'best_score': '0.281999'}
best_ntree_limit 2 0
inner: 2 10
outer: 2 10
```
and sometime the output is
```
{'best_iteration': '0', 'best_ntree_limit': '1', 'best_score': '0.281999'}
best_ntree_limit 2 0
inner: 2 10
outer: 2 10
Traceback (most recent call last):
  File "./test_model_slice.py", line 47, in <module>
    run_test()
  File "./test_model_slice.py", line 43, in run_test
    m.inplace_predict(rx)
  File "~/anaconda3/envs/cuda/lib/python3.8/site-packages/xgboost/core.py", line 1846, in inplace_predict
    _check_call(
  File "~/anaconda3/envs/cuda/lib/python3.8/site-packages/xgboost/core.py", line 210, in _check_call
    raise XGBoostError(py_str(_LIB.XGBGetLastError()))
xgboost.core.XGBoostError: [16:53:10] ../src/predictor/cpu_predictor.cc:258: Check failed: m->NumColumns() == model.learner_model_param->num_feature (10 vs. 0) : Number of columns in data must equal to trained model.
Stack trace:
  [bt] (0) ~/anaconda3/envs/cuda/lib/python3.8/site-packages/xgboost/lib/libxgboost.so(+0x912df) [0x7fe1cc8ab2df]
  [bt] (1) ~/anaconda3/envs/cuda/lib/python3.8/site-packages/xgboost/lib/libxgboost.so(+0x243048) [0x7fe1cca5d048]
  [bt] (2) ~/anaconda3/envs/cuda/lib/python3.8/site-packages/xgboost/lib/libxgboost.so(+0x244d3d) [0x7fe1cca5ed3d]
  [bt] (3) ~/anaconda3/envs/cuda/lib/python3.8/site-packages/xgboost/lib/libxgboost.so(+0x198221) [0x7fe1cc9b2221]
  [bt] (4) ~/anaconda3/envs/cuda/lib/python3.8/site-packages/xgboost/lib/libxgboost.so(+0x1ce6a7) [0x7fe1cc9e86a7]
  [bt] (5) ~/anaconda3/envs/cuda/lib/python3.8/site-packages/xgboost/lib/libxgboost.so(+0x9cb2e) [0x7fe1cc8b6b2e]
  [bt] (6) ~/anaconda3/envs/cuda/lib/python3.8/site-packages/xgboost/lib/libxgboost.so(XGBoosterPredictFromDense+0x225) [0x7fe1cc89dfa5]
  [bt] (7) ~/anaconda3/envs/cuda/lib/python3.8/lib-dynload/../../libffi.so.7(+0x69dd) [0x7fe1ff37d9dd]
  [bt] (8) ~/anaconda3/envs/cuda/lib/python3.8/lib-dynload/../../libffi.so.7(+0x6067) [0x7fe1ff37d067]
```

The xgboost version used is 1.4.1.

**Comment by trivialfis** [comment]
Should be fixed in 1.5.  I'm about the make the release and push Python packages to pip.
