### ISSUE TITLE
[XGBoost4J-Spark] Version 1.5.0 fails (version 1.4.1 works)

### ISSUE THREAD

**Issue by candalfigomoro** [dmlc/xgboost#7350]
I tried to upgrade XGBoost4J-Spark from version 1.4.1 to version 1.5.0.

While version 1.4.1 works fine, version 1.5.0 fails (with the same config and code).

When I use version 1.5.0, I get the following errors on "_repartition at DataUtils.scala:96_":

```
Job aborted due to stage failure: Task serialization failed: java.lang.IllegalStateException: Cannot call methods on a stopped SparkContext.
This stopped SparkContext was created at:

org.apache.spark.SparkContext.getOrCreate(SparkContext.scala)
java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515)
com.google.common.util.concurrent.TrustedListenableFutureTask$TrustedFutureInterruptibleTask.runInterruptibly(TrustedListenableFutureTask.java:131)
com.google.common.util.concurrent.InterruptibleTask.run(InterruptibleTask.java:74)
com.google.common.util.concurrent.TrustedListenableFutureTask.run(TrustedListenableFutureTask.java:82)
java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515)
java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
java.base/java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:304)
java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
java.base/java.lang.Thread.run(Thread.java:829)

The currently active SparkContext was created at:

org.apache.spark.SparkContext.getOrCreate(SparkContext.scala)
java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515)
com.google.common.util.concurrent.TrustedListenableFutureTask$TrustedFutureInterruptibleTask.runInterruptibly(TrustedListenableFutureTask.java:131)
com.google.common.util.concurrent.InterruptibleTask.run(InterruptibleTask.java:74)
com.google.common.util.concurrent.TrustedListenableFutureTask.run(TrustedListenableFutureTask.java:82)
java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515)
java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
java.base/java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:304)
java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
java.base/java.lang.Thread.run(Thread.java:829)
         
java.lang.IllegalStateException: Cannot call methods on a stopped SparkContext.
This stopped SparkContext was created at:

org.apache.spark.SparkContext.getOrCreate(SparkContext.scala)
java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515)
com.google.common.util.concurrent.TrustedListenableFutureTask$TrustedFutureInterruptibleTask.runInterruptibly(TrustedListenableFutureTask.java:131)
com.google.common.util.concurrent.InterruptibleTask.run(InterruptibleTask.java:74)
com.google.common.util.concurrent.TrustedListenableFutureTask.run(TrustedListenableFutureTask.java:82)
java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515)
java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
java.base/java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:304)
java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
java.base/java.lang.Thread.run(Thread.java:829)

The currently active SparkContext was created at:

org.apache.spark.SparkContext.getOrCreate(SparkContext.scala)
java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515)
com.google.common.util.concurrent.TrustedListenableFutureTask$TrustedFutureInterruptibleTask.runInterruptibly(TrustedListenableFutureTask.java:131)
com.google.common.util.concurrent.InterruptibleTask.run(InterruptibleTask.java:74)
com.google.common.util.concurrent.TrustedListenableFutureTask.run(TrustedListenableFutureTask.java:82)
java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515)
java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
java.base/java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:304)
java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
java.base/java.lang.Thread.run(Thread.java:829)
         
	at org.apache.spark.SparkContext.assertNotStopped(SparkContext.scala:118)
	at org.apache.spark.SparkContext.broadcast(SparkContext.scala:1490)
	at org.apache.spark.scheduler.DAGScheduler.submitMissingTasks(DAGScheduler.scala:1223)
	at org.apache.spark.scheduler.DAGScheduler.submitStage(DAGScheduler.scala:1118)
	at org.apache.spark.scheduler.DAGScheduler.$anonfun$submitStage$5(DAGScheduler.scala:1121)
	at org.apache.spark.scheduler.DAGScheduler.$anonfun$submitStage$5$adapted(DAGScheduler.scala:1120)
	at scala.collection.immutable.List.foreach(List.scala:431)
	at org.apache.spark.scheduler.DAGScheduler.submitStage(DAGScheduler.scala:1120)
	at org.apache.spark.scheduler.DAGScheduler.handleJobSubmitted(DAGScheduler.scala:1061)
	at org.apache.spark.scheduler.DAGSchedulerEventProcessLoop.doOnReceive(DAGScheduler.scala:2196)
	at org.apache.spark.scheduler.DAGSchedulerEventProcessLoop.onReceive(DAGScheduler.scala:2188)
	at org.apache.spark.scheduler.DAGSchedulerEventProcessLoop.onReceive(DAGScheduler.scala:2177)
	at org.apache.spark.util.EventLoop$$anon$1.run(EventLoop.scala:49)
```

```
java.lang.IllegalStateException: Promise already completed.
	at scala.concurrent.Promise.complete(Promise.scala:53)
	at scala.concurrent.Promise.complete$(Promise.scala:52)
	at scala.concurrent.impl.Promise$DefaultPromise.complete(Promise.scala:187)
	at scala.concurrent.Promise.success(Promise.scala:86)
	at scala.concurrent.Promise.success$(Promise.scala:86)
	at scala.concurrent.impl.Promise$DefaultPromise.success(Promise.scala:187)
	at org.apache.spark.deploy.yarn.ApplicationMaster.org$apache$spark$deploy$yarn$ApplicationMaster$$sparkContextInitialized(ApplicationMaster.scala:404)
	at org.apache.spark.deploy.yarn.ApplicationMaster$.sparkContextInitialized(ApplicationMaster.scala:897)
	at org.apache.spark.scheduler.cluster.YarnClusterScheduler.postStartHook(YarnClusterScheduler.scala:32)
	at org.apache.spark.SparkContext.<init>(SparkContext.scala:625)
	at org.apache.spark.SparkContext.<init>(SparkContext.scala:127)
	at org.apache.spark.SparkContext$.getOrCreate(SparkContext.scala:2666)
	at org.apache.spark.SparkContext.getOrCreate(SparkContext.scala)
	at com.google.common.util.concurrent.TrustedListenableFutureTask$TrustedFutureInterruptibleTask.runInterruptibly(TrustedListenableFutureTask.java:131)
	at com.google.common.util.concurrent.InterruptibleTask.run(InterruptibleTask.java:74)
	at com.google.common.util.concurrent.TrustedListenableFutureTask.run(TrustedListenableFutureTask.java:82)
	at org.jboss.threads.ContextHandler$1.runWith(ContextHandler.java:18)
	at org.jboss.threads.EnhancedQueueExecutor$Task.run(EnhancedQueueExecutor.java:2449)
	at org.jboss.threads.EnhancedQueueExecutor$ThreadBody.run(EnhancedQueueExecutor.java:1452)
	at java.base/java.lang.Thread.run(Thread.java:829)
```

Spark version 3.0.2

**Comment by trivialfis** [comment]
@wbo4958 Do you have any insight?

**Comment by candalfigomoro** [comment]
> @candalfigomoro Could you please provide a runnable example that we can use to bisect the possible cause?

@trivialfis 

I used this dataset: https://archive.ics.uci.edu/ml/datasets/MiniBooNE+particle+identification

Train: 70%
Validation: 10%
Test: 20%

This is the Java code for the model (I use Java instead of Scala):
```
    import org.apache.spark.sql.Dataset;
    import org.apache.spark.sql.Row;
    import scala.collection.immutable.Map;
    import ml.dmlc.xgboost4j.scala.spark.XGBoostClassifier;
    import ml.dmlc.xgboost4j.scala.spark.XGBoostClassificationModel;

    ...

    XGBoostClassifier xgbClassifier = new XGBoostClassifier();
    xgbClassifier.setNumWorkers(8);  // less than or equal to: executor-cores * num-executors
    xgbClassifier.setNthread(1);  // less than or equal to: task-cpus
    xgbClassifier.setEta(0.1);
    xgbClassifier.setMaxDepth(6);
    xgbClassifier.setNumRound(1000);
    xgbClassifier.setNumEarlyStoppingRounds(5);
    xgbClassifier.setObjective("binary:logistic");
    xgbClassifier.setScalePosWeight(1.0);
    xgbClassifier.setSubsample(0.5);
    xgbClassifier.setColsampleBytree(0.5);
    xgbClassifier.setTreeMethod("hist");
    xgbClassifier.setFeaturesCol("features");
    xgbClassifier.setLabelCol("label");
    xgbClassifier.setEvalMetric("auc");
    xgbClassifier.setMaximizeEvaluationMetrics(true);  // true for "auc"
    xgbClassifier.setEvalSets(new Map.Map1<>("validation", validation));

    XGBoostClassificationModel xgbClassificationModel = xgbClassifier.fit(train);

    Dataset<Row> results = xgbClassificationModel.setContribPredictionCol("shap").transform(test);
```

It works fine with version 1.4.1.

**Comment by candalfigomoro** [comment]
@wbo4958 @trivialfis Sorry but we use a proprietary platform/framework, so I'm not able to provide the full code. The strange thing is that version 1.4.1 works fine, but I get those errors (with the same code and Spark 3.0.2 configuration) with version 1.5.0.

**Comment by trivialfis** [comment]
Feel free to run [bisect](https://www.google.com/url?sa=t&rct=j&q=&esrc=s&source=web&cd=&cad=rja&uact=8&ved=2ahUKEwj2wLTKiNvzAhVS3p4KHSRkD7wQFnoECAMQAQ&url=https%3A%2F%2Fgit-scm.com%2Fdocs%2Fgit-bisect&usg=AOvVaw21dGHLnuRx6f5bDrFFEjBO) , that might be easier than extracting the code.

**Comment by candalfigomoro** [comment]
> Hi, could you please try to extract the related portion of the code into something runnable? Or the issue has to be reproduced by using the proprietary platform? We can't guess the cause by simply looking at a backtrace that doesn't mention XGBoost at all.

@trivialfis Is the log above more useful?

**Comment by candalfigomoro** [comment]
@trivialfis
Maybe the documentation should also be updated: https://xgboost.readthedocs.io/en/latest/jvm/xgboost4j_spark_tutorial.html

_"By default, we use the tracker in dmlc-core to drive the training with XGBoost4J-Spark. It requires Python 2.7+."_

Should it be updated to "3.6+"?

**Comment by trivialfis** [comment]
Yup! Thanks for the reminder.
