### ISSUE TITLE
some Error on xgboost4j xgboost4j-spark version 1.5.0. spark version is 3.1.2 and python version is 3.7 

### ISSUE THREAD

**Issue by liuyonglang** [dmlc/xgboost#7427]
```
21/11/12 17:50:54 INFO codegen.CodeGenerator: Code generated in 14.541963 ms
21/11/12 17:50:54 INFO codegen.CodeGenerator: Code generated in 13.014808 ms
21/11/12 17:50:55 INFO XGBoostSpark: Running XGBoost 1.5.0 with parameters:
alpha -> 0.574910768982165
min_child_weight -> 3.9482691695848593
sample_type -> uniform
base_score -> 0.5
rabit_timeout -> -1
colsample_bylevel -> 0.9522819757815486
grow_policy -> lossguide
skip_drop -> 0.0
lambda_bias -> 0.13459007824713004
silent -> 0
scale_pos_weight -> 1.0
seed -> 12345
cache_training_set -> false
features_col -> importance_vec
num_early_stopping_rounds -> 0
label_col -> C2
num_workers -> 1
subsample -> 1.0
lambda -> 1.0
max_depth -> 7
probability_col -> probability
raw_prediction_col -> rawPrediction
kill_spark_context_on_worker_failure -> true
tree_limit -> 0
custom_eval -> null
dmlc_worker_connect_retry -> 5
rate_drop -> 0.0
max_bin -> 256
train_test_ratio -> 1.0
use_external_memory -> false
objective -> binary:logistic
eval_metric -> logloss
num_round -> 80
timeout_request_workers -> 1800000
missing -> -999.0
rabit_ring_reduce_threshold -> 32768
checkpoint_path -> 
tracker_conf -> TrackerConf(0,python)
tree_method -> hist
max_delta_step -> 0.0
eta -> 0.05928203529830945
verbosity -> 1
colsample_bytree -> 0.8553802018993538
normalize_type -> tree
allow_non_zero_for_missing -> true
custom_obj -> null
gamma -> 0.0
sketch_eps -> 0.03
nthread -> 1
prediction_col -> prediction
checkpoint_interval -> -1
21/11/12 17:50:55 WARN XGBoostSpark: train_test_ratio is deprecated since XGBoost 0.82, we recommend to explicitly pass a training and multiple evaluation datasets by passing 'eval_sets' and 'eval_set_names'
21/11/12 17:50:55 INFO XGBoostSpark: starting training with timeout set as 1800000 ms for waiting for resources
21/11/12 17:50:55 INFO java.RabitTracker: Tracker Process ends with exit code 1
21/11/12 17:50:55 INFO XGBoostSpark: Rabit returns with exit code 1
21/11/12 17:50:55 ERROR XGBoostSpark: the job was aborted due to 
ml.dmlc.xgboost4j.java.XGBoostError: XGBoostModel training failed
	at ml.dmlc.xgboost4j.scala.spark.XGBoost$.postTrackerReturnProcessing(XGBoost.scala:750)
	at ml.dmlc.xgboost4j.scala.spark.XGBoost$.trainDistributed(XGBoost.scala:624)
	at ml.dmlc.xgboost4j.scala.spark.XGBoostClassifier.train(XGBoostClassifier.scala:199)
	at ml.dmlc.xgboost4j.scala.spark.XGBoostClassifier.train(XGBoostClassifier.scala:40)
	at org.apache.spark.ml.Predictor.fit(Predictor.scala:151)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at py4j.reflection.MethodInvoker.invoke(MethodInvoker.java:244)
	at py4j.reflection.ReflectionEngine.invoke(ReflectionEngine.java:357)
	at py4j.Gateway.invoke(Gateway.java:282)
	at py4j.commands.AbstractCommand.invokeMethod(AbstractCommand.java:132)
	at py4j.commands.CallCommand.execute(CallCommand.java:79)
	at py4j.GatewayConnection.run(GatewayConnection.java:238)
	at java.lang.Thread.run(Thread.java:748)
21/11/12 17:50:55 ERROR java.RabitTracker$TrackerProcessLogger: java.io.IOException: Stream closed
21/11/12 17:50:55 ERROR java.RabitTracker: Uncaught exception thrown by worker:
java.lang.IllegalStateException: SparkContext has been shutdown
	at org.apache.spark.SparkContext.runJob(SparkContext.scala:2188)
	at org.apache.spark.SparkContext.runJob(SparkContext.scala:2217)
	at org.apache.spark.SparkContext.runJob(SparkContext.scala:2236)
	at org.apache.spark.SparkContext.runJob(SparkContext.scala:2261)
	at org.apache.spark.rdd.RDD.$anonfun$foreachPartition$1(RDD.scala:1020)
	at org.apache.spark.rdd.RDDOperationScope$.withScope(RDDOperationScope.scala:151)
	at org.apache.spark.rdd.RDDOperationScope$.withScope(RDDOperationScope.scala:112)
	at org.apache.spark.rdd.RDD.withScope(RDD.scala:414)
	at org.apache.spark.rdd.RDD.foreachPartition(RDD.scala:1018)
	at ml.dmlc.xgboost4j.scala.spark.XGBoost$$anon$1.run(XGBoost.scala:612)
21/11/12 17:50:55 ERROR java.RabitTracker: java.lang.InterruptedException: sleep interrupted
```

**Comment by trivialfis** [comment]
HI, please provide a reproducible example similar to the one described in https://stackoverflow.com/help/minimal-reproducible-example .

**Comment by tkone2018** [comment]
我也遇到这个错了，请问你解决了吗 ? @liuyonglang
