### ISSUE TITLE
Not correct error in Dmatrix with data.type=object

### ISSUE THREAD

**Issue by Rubtsowa** [dmlc/xgboost#7442]
I got the problem in xgboost. When I create a DMatrix like in the test (https://github.com/dmlc/xgboost/blob/master/tests/python/test_dmatrix.py#L82), I get an error other than the ValueError expected in this case:

>>> import xgboost as xgb
>>> import numpy as np
>>> data=np.array([['a', 'b'], ['c', 'd']])
>>> a=xgb.DMatrix(data)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/localdisk/mrubtsov/miniconda/envs/modin/lib/python3.8/site-packages/xgboost/core.py", line 506, in inner_f
    return f(**kwargs)
  File "/localdisk/mrubtsov/miniconda/envs/modin/lib/python3.8/site-packages/xgboost/core.py", line 616, in __init__
    handle, feature_names, feature_types = dispatch_data_backend(
  File "/localdisk/mrubtsov/miniconda/envs/modin/lib/python3.8/site-packages/xgboost/data.py", line 698, in dispatch_data_backend
    return _from_numpy_array(data, missing, threads, feature_names,
  File "/localdisk/mrubtsov/miniconda/envs/modin/lib/python3.8/site-packages/xgboost/data.py", line 178, in _from_numpy_array
    _check_call(
  File "/localdisk/mrubtsov/miniconda/envs/modin/lib/python3.8/site-packages/xgboost/core.py", line 218, in _check_call
    raise XGBoostError(py_str(_LIB.XGBGetLastError()))
xgboost.core.XGBoostError: [02:13:51] ../src/c_api/../data/array_interface.h:357: Unicode-1 is not supported.
Stack trace:
  [bt] (0) /localdisk/mrubtsov/miniconda/envs/modin/lib/python3.8/site-packages/xgboost/lib/libxgboost.so(+0x972bd) [0x7f7918f922bd]
  [bt] (1) /localdisk/mrubtsov/miniconda/envs/modin/lib/python3.8/site-packages/xgboost/lib/libxgboost.so(+0xb3506) [0x7f7918fae506]
  [bt] (2) /localdisk/mrubtsov/miniconda/envs/modin/lib/python3.8/site-packages/xgboost/lib/libxgboost.so(XGDMatrixCreateFromDense+0xe6) [0x7f7918f9c886]
  [bt] (3) /localdisk/mrubtsov/miniconda/envs/modin/lib/python3.8/lib-dynload/../../libffi.so.7(+0x69dd) [0x7f7a6f2189dd]
  [bt] (4) /localdisk/mrubtsov/miniconda/envs/modin/lib/python3.8/lib-dynload/../../libffi.so.7(+0x6067) [0x7f7a6f218067]
  [bt] (5) /localdisk/mrubtsov/miniconda/envs/modin/lib/python3.8/lib-dynload/_ctypes.cpython-38-x86_64-linux-gnu.so(_ctypes_callproc+0x319) [0x7f7a6f230d39]
  [bt] (6) /localdisk/mrubtsov/miniconda/envs/modin/lib/python3.8/lib-dynload/_ctypes.cpython-38-x86_64-linux-gnu.so(+0x137e5) [0x7f7a6f2317e5]
  [bt] (7) python(_PyObject_MakeTpCall+0x3bf) [0x5574716f625f]
  [bt] (8) python(_PyEval_EvalFrameDefault+0x5437) [0x55747179fe87]

A similar problem when a list is supplied as data:

>>> import xgboost as xgb
>>> xgb.DMatrix([['a', 'b'], ['c', 'd']])
Traceback (most recent call last):
File "<stdin>", line 1, in <module>
File "/localdisk/mrubtsov/miniconda/envs/modin/lib/python3.8/site-packages/xgboost/core.py", line 506, in inner_f
return f(**kwargs)
File "/localdisk/mrubtsov/miniconda/envs/modin/lib/python3.8/site-packages/xgboost/core.py", line 616, in __init__
handle, feature_names, feature_types = dispatch_data_backend(
File "/localdisk/mrubtsov/miniconda/envs/modin/lib/python3.8/site-packages/xgboost/data.py", line 703, in dispatch_data_backend
return _from_list(data, missing, threads, feature_names, feature_types)
File "/localdisk/mrubtsov/miniconda/envs/modin/lib/python3.8/site-packages/xgboost/data.py", line 635, in _from_list
return _from_numpy_array(array, missing, n_threads, feature_names, feature_types)
File "/localdisk/mrubtsov/miniconda/envs/modin/lib/python3.8/site-packages/xgboost/data.py", line 178, in _from_numpy_array
_check_call(
File "/localdisk/mrubtsov/miniconda/envs/modin/lib/python3.8/site-packages/xgboost/core.py", line 218, in _check_call
raise XGBoostError(py_str(_LIB.XGBGetLastError()))
xgboost.core.XGBoostError: [10:00:53] ../src/c_api/../data/array_interface.h:357: Unicode-1 is not supported.
Stack trace:
[bt] (0) /localdisk/mrubtsov/miniconda/envs/modin/lib/python3.8/site-packages/xgboost/lib/libxgboost.so(+0x972bd) [0x7fc1f9cdf2bd]
[bt] (1) /localdisk/mrubtsov/miniconda/envs/modin/lib/python3.8/site-packages/xgboost/lib/libxgboost.so(+0xb3506) [0x7fc1f9cfb506]
[bt] (2) /localdisk/mrubtsov/miniconda/envs/modin/lib/python3.8/site-packages/xgboost/lib/libxgboost.so(XGDMatrixCreateFromDense+0xe6) [0x7fc1f9ce9886]
[bt] (3) /localdisk/mrubtsov/miniconda/envs/modin/lib/python3.8/lib-dynload/../../libffi.so.7(+0x69dd) [0x7fc34ff689dd]
[bt] (4) /localdisk/mrubtsov/miniconda/envs/modin/lib/python3.8/lib-dynload/../../libffi.so.7(+0x6067) [0x7fc34ff68067]
[bt] (5) /localdisk/mrubtsov/miniconda/envs/modin/lib/python3.8/lib-dynload/_ctypes.cpython-38-x86_64-linux-gnu.so(_ctypes_callproc+0x319) [0x7fc34ff80d39]
[bt] (6) /localdisk/mrubtsov/miniconda/envs/modin/lib/python3.8/lib-dynload/_ctypes.cpython-38-x86_64-linux-gnu.so(+0x137e5) [0x7fc34ff817e5]
[bt] (7) python(_PyObject_MakeTpCall+0x3bf) [0x5563bb4e525f]
[bt] (8) python(_PyEval_EvalFrameDefault+0x5437) [0x5563bb58ee87]

**Comment by trivialfis** [comment]
Hi, It's an exception that inherits ValueError.
