### ISSUE TITLE
ERROR XGBoostSpark: the job was aborted due to java.lang.ClassCastException: ml.dmlc.xgboost4j.scala.Booster cannot be cast to ml.dmlc.xgboost4j.scala.Booster

### ISSUE THREAD

**Issue by ltken123** [dmlc/xgboost#7599]
Hi,
 
Trying to run XGBoost from Spark on Kubernetes but stuck with similar error as https://github.com/dmlc/xgboost/issues/5186 and https://github.com/dmlc/xgboost/issues/4218

spark.version = 3.1.2
spylon-kernel = 0.4.1
scala = 2.12.10
xgboost4j-spark = 1.5.2

`val xgbClassificationModel = xgbClassifier.fit(xgbInput)`
Output
`Tracker started, with env={DMLC_NUM_SERVER=0, DMLC_TRACKER_URI=10.220.2.238, DMLC_TRACKER_PORT=9091, DMLC_NUM_WORKER=2}
22/01/24 18:40:11 WARN XGBoostSpark: train_test_ratio is deprecated since XGBoost 0.82, we recommend to explicitly pass a training and multiple evaluation datasets by passing 'eval_sets' and 'eval_set_names'
`
`
22/01/24 18:40:13 ERROR XGBoostSpark: the job was aborted due to
java.lang.ClassCastException: ml.dmlc.xgboost4j.scala.Booster cannot be cast to ml.dmlc.xgboost4j.scala.Booster
        at ml.dmlc.xgboost4j.scala.spark.XGBoost$.postTrackerReturnProcessing(XGBoost.scala:738)
        at ml.dmlc.xgboost4j.scala.spark.XGBoost$.trainDistributed(XGBoost.scala:624)
        at ml.dmlc.xgboost4j.scala.spark.XGBoostClassifier.train(XGBoostClassifier.scala:199)
        at ml.dmlc.xgboost4j.scala.spark.XGBoostClassifier.train(XGBoostClassifier.scala:40)
        at org.apache.spark.ml.Predictor.fit(Predictor.scala:151)
        at $line24.$read$$iw$$iw$$iw$$iw$$iw$$iw$$iw$$iw$$iw$$iw$$iw$$iw$$iw$$iw$$iw$$iw.<init>(<console>:55)
        at $line24.$read$$iw$$iw$$iw$$iw$$iw$$iw$$iw$$iw$$iw$$iw$$iw$$iw$$iw$$iw$$iw.<init>(<console>:60)
        at $line24.$read$$iw$$iw$$iw$$iw$$iw$$iw$$iw$$iw$$iw$$iw$$iw$$iw$$iw$$iw.<init>(<console>:62)
        at $line24.$read$$iw$$iw$$iw$$iw$$iw$$iw$$iw$$iw$$iw$$iw$$iw$$iw$$iw.<init>(<console>:64)
        at $line24.$read$$iw$$iw$$iw$$iw$$iw$$iw$$iw$$iw$$iw$$iw$$iw$$iw.<init>(<console>:66)
        at $line24.$read$$iw$$iw$$iw$$iw$$iw$$iw$$iw$$iw$$iw$$iw$$iw.<init>(<console>:68)
        at $line24.$read$$iw$$iw$$iw$$iw$$iw$$iw$$iw$$iw$$iw$$iw.<init>(<console>:70)
        at $line24.$read$$iw$$iw$$iw$$iw$$iw$$iw$$iw$$iw$$iw.<init>(<console>:72)
        at $line24.$read$$iw$$iw$$iw$$iw$$iw$$iw$$iw$$iw.<init>(<console>:74)
        at $line24.$read$$iw$$iw$$iw$$iw$$iw$$iw$$iw.<init>(<console>:76)
        at $line24.$read$$iw$$iw$$iw$$iw$$iw$$iw.<init>(<console>:78)
        at $line24.$read$$iw$$iw$$iw$$iw$$iw.<init>(<console>:80)
        at $line24.$read$$iw$$iw$$iw$$iw.<init>(<console>:82)
        at $line24.$read$$iw$$iw$$iw.<init>(<console>:84)
        at $line24.$read$$iw$$iw.<init>(<console>:86)
        at $line24.$read$$iw.<init>(<console>:88)
        at $line24.$read.<init>(<console>:90)
        at $line24.$read$.<init>(<console>:94)
        at $line24.$read$.<clinit>(<console>)
        at $line24.$eval$.$print$lzycompute(<console>:7)
        at $line24.$eval$.$print(<console>:6)
        at $line24.$eval.$print(<console>)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:498)
        at scala.tools.nsc.interpreter.IMain$ReadEvalPrint.call(IMain.scala:745)
        at scala.tools.nsc.interpreter.IMain$Request.loadAndRun(IMain.scala:1021)
        at scala.tools.nsc.interpreter.IMain.$anonfun$interpret$1(IMain.scala:574)
        at scala.reflect.internal.util.ScalaClassLoader.asContext(ScalaClassLoader.scala:41)
        at scala.reflect.internal.util.ScalaClassLoader.asContext$(ScalaClassLoader.scala:37)
        at scala.reflect.internal.util.AbstractFileClassLoader.asContext(AbstractFileClassLoader.scala:41)
        at scala.tools.nsc.interpreter.IMain.loadAndRunReq$1(IMain.scala:573)
        at scala.tools.nsc.interpreter.IMain.interpret(IMain.scala:600)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:498)
        at py4j.reflection.MethodInvoker.invoke(MethodInvoker.java:244)
        at py4j.reflection.ReflectionEngine.invoke(ReflectionEngine.java:357)
        at py4j.Gateway.invoke(Gateway.java:282)
        at py4j.commands.AbstractCommand.invokeMethod(AbstractCommand.java:132)
        at py4j.commands.CallCommand.execute(CallCommand.java:79)
        at py4j.GatewayConnection.run(GatewayConnection.java:238)
        at java.lang.Thread.run(Thread.java:748)
`

Is this is a version error as well, or Spark on K8s is not currently supported with XGBoost?

**Comment by trivialfis** [comment]
@wbo4958 Could you please take a look when you are available?

**Comment by ltken123** [comment]
Test code for reference (based on Iris example) https://xgboost.readthedocs.io/en/stable/jvm/xgboost4j_spark_tutorial.html

`
%%init_spark
launcher.conf.set("spark.executor.instances", "1")
launcher.conf.set("spark.executor.memory", "10g")
launcher.conf.set("spark.driver.memory", "8g")
launcher.conf.set("spark.executor.cores", "4")
launcher.packages = ["ml.dmlc:xgboost4j-spark_2.12:1.5.2"]

import spark.implicits._ 
import org.apache.spark.sql.functions.{col, lit, when, row_number,udf}
import org.apache.spark.sql.expressions.Window
import org.apache.spark.sql.DataFrame

import ml.dmlc.xgboost4j.scala.spark.{XGBoostClassifier, XGBoostClassificationModel}
import org.apache.spark.sql.types.{DoubleType, StringType, StructField, StructType}

val schema = new StructType(Array(
  StructField("sepal length", DoubleType, true),
  StructField("sepal width", DoubleType, true),
  StructField("petal length", DoubleType, true),
  StructField("petal width", DoubleType, true),
  StructField("class", StringType, true)))
val rawInput = spark.read.schema(schema).csv(".../iris_data.csv")
import org.apache.spark.ml.feature.StringIndexer
val stringIndexer = new StringIndexer().
  setInputCol("class").
  setOutputCol("classIndex").
  fit(rawInput)
val labelTransformed = stringIndexer.transform(rawInput).drop("class")
import org.apache.spark.ml.feature.VectorAssembler
val vectorAssembler = new VectorAssembler().
  setInputCols(Array("sepal length", "sepal width", "petal length", "petal width")).
  setOutputCol("features")
val xgbInput = vectorAssembler.transform(labelTransformed).select("features", "classIndex")

val xgbParam = Map("eta" -> 0.1f,
      "max_depth" -> 2,
      "objective" -> "multi:softprob",
      "num_class" -> 3,
      "num_round" -> 100,
      "num_workers" -> 2)

val xgbClassifier = new XGBoostClassifier(xgbParam).
      setFeaturesCol("features").
      setLabelCol("classIndex").
      setMaxDepth(2)

val xgbClassificationModel = xgbClassifier.fit(xgbInput)
`

**Comment by wbo4958** [comment]
@ltken123 Does it repro in standalone mode?

**Comment by wbo4958** [comment]
@ltken123 I'm curious why there is `py4j` error log in the exception, XGBoost has not supported the pyspark yet. Could you also check the log from the executor side. Or can you find a way repro in the local or standalone env, since I don't have k8s env.

**Comment by ltken123** [comment]
Thanks for follow-up @wbo4958, I'm using spylon kernel which acts as a wrapper/interpreter for Scala code in a Python environment and under the hood it's using pyspark, could explain the issue.

Will try manually in spark-shell on the cluster from a pod, and look into standalone mode potentially

**Comment by ltken123** [comment]
@wbo4958 confirmed working in spark-shell directly in K8s, will close this. Thanks
