### ISSUE TITLE
running xgboost on apple silicon (aarm64) fails due to lack of native library

### ISSUE THREAD

**Issue by xelax** [dmlc/xgboost#7706]
running xgboost on spark (package ml.dmlc:xgboost4j_2.12:1.5.1:jar) on a Mac with Apple silicon fails with:

Caused by: java.lang.RuntimeException: java.io.FileNotFoundException: File /lib/macos/aarch64/libxgboost4j.dylib was not found inside JAR.
	at ml.dmlc.xgboost4j.java.XGBoostJNI.<clinit>(XGBoostJNI.java:37)
	... 23 more
Caused by: java.io.FileNotFoundException: File /lib/macos/aarch64/libxgboost4j.dylib was not found inside JAR.
	at ml.dmlc.xgboost4j.java.NativeLibLoader.createTempFileFromResource(NativeLibLoader.java:233)
	at ml.dmlc.xgboost4j.java.NativeLibLoader.loadLibraryFromJar(NativeLibLoader.java:176)
	at ml.dmlc.xgboost4j.java.NativeLibLoader.initXGBoost(NativeLibLoader.java:130)
	at ml.dmlc.xgboost4j.java.XGBoostJNI.<clinit>(XGBoostJNI.java:34)
	... 23 more

**Comment by trivialfis** [comment]
Closing as duplicated to https://github.com/dmlc/xgboost/issues/6408 .

**Comment by xelax** [comment]
but this is about the maven artifacts, I think https://github.com/dmlc/xgboost/issues/6408 is about the python packages?

**Comment by trivialfis** [comment]
It's not package-specific, we don't have the machine to build binary packages for apple silicon, nor does GitHub Action provide such instance.   @hcho3 found a way to build it for the Python package using cross-platform compilation.  But for JVM packages we haven't found a way yet.

You can compile XGBoost from the source.

**Comment by xelax** [comment]
ok. Would it help if build it on my computer and upload the libraries somewhere? If the instruction are not too complex I can try

**Comment by trivialfis** [comment]
Thank you for the offer.  But if we were to support it I think we need to find an automated solution instead of pinging you everytime we want to build it. ;-)

Right now all the builds are running on the CI, either on Github action or on Jenkins.

**Comment by xelax** [comment]
make sense. Hopefully arm64 instances will become more common soon.

**Comment by xelax** [comment]
Support of M1 mac might come soon for github actions: 
https://github.com/actions/runner/blob/main/docs/start/envosx.md

**Comment by kmate** [comment]
Can't we simply cross-compile using an x86 linux box?

**Comment by hcho3** [comment]
Hi everyone, XGBoost JVM package now ships with native binary for Apple Silicon.
