### ISSUE TITLE
Windows Branch Seems Missing

### ISSUE THREAD

**Issue by Aelvangunduz** [dmlc/xgboost#792]
I wanted to install XGBoost on a Windows machine but the https://github.com/dmlc/xgboost/blob/master/windows link in instructions is missing. I checked other files as well and can't seem to find required .dlls. Is its development discontinued?

**Comment by davutpolat** [comment]
try this one,

https://xgboost.readthedocs.org/en/latest/build.html#building-on-windows

**Comment by thushv89** [comment]
xgboost is switching to using make for building in windows. You can read about this in 
https://github.com/dmlc/xgboost/issues/736

If you want to build it in windows with MSVS, you can checkout the 0.4.0 (old) version. it has the windows folder directly inside the root_folder.

**Comment by tqchen** [comment]
As a reminder, we are also actively for helps to  get back VS build via CMake. via https://github.com/dmlc/xgboost/issues/746

**Comment by Aelvangunduz** [comment]
I built the libraries as instructed using mingw however when importing I get the following error message:

import xgboost as xgb
Traceback (most recent call last):

  File "<ipython-input-1-745aa3a2d734>", line 1, in <module>
    import xgboost as xgb

  File "C:\Users\Elvan\Anaconda\lib\site-packages\xgboost-0.4-py2.7.egg\xgboost\__init__.py", line 11, in <module>
    from .core import DMatrix, Booster

  File "C:\Users\Elvan\Anaconda\lib\site-packages\xgboost-0.4-py2.7.egg\xgboost\core.py", line 83, in <module>
    _LIB = _load_lib()

  File "C:\Users\Elvan\Anaconda\lib\site-packages\xgboost-0.4-py2.7.egg\xgboost\core.py", line 77, in _load_lib
    lib = ctypes.cdll.LoadLibrary(lib_path[0])

  File "C:\Users\Elvan\Anaconda\lib\ctypes\__init__.py", line 443, in LoadLibrary
    return self._dlltype(name)

  File "C:\Users\Elvan\Anaconda\lib\ctypes\__init__.py", line 365, in __init__
    self._handle = _dlopen(self._name, mode)

WindowsError: [Error 127] The specified procedure could not be found
