### ISSUE TITLE
[JVM-packages] XGBoostModel training failed with Rabit returns with exit code 1

### ISSUE THREAD

**Issue by Jasonzjj** [dmlc/xgboost#8003]
### I encountered the following problems when using xgboost4j-spark 1.6.1 , spark 3.2.1 and scala 2.12，
Can someone help me out？

spark parameters:
    --conf spark.sql.shuffle.partitions=200 \
    --conf spark.executor.instances=8 \
    --conf spark.driver.memory=4g \

xgboost parameters:
"num_workers"->8,
"nthread"->1

error:
2022-06-17 06:10:10 [task-result-getter-0]  INFO [YarnClusterScheduler:57]: Removed TaskSet 2.0, whose tasks have all completed, from pool 
2022-06-17 06:10:10 [dag-scheduler-event-loop]  INFO [DAGScheduler:57]: ResultStage 2 (collect at XGBoost.scala:431) finished in 2871.246 s
2022-06-17 06:10:10 [dag-scheduler-event-loop]  INFO [DAGScheduler:57]: Job 1 is finished. Cancelling potential speculative or zombie tasks for this job
2022-06-17 06:10:10 [dag-scheduler-event-loop]  INFO [YarnClusterScheduler:57]: Killing all running tasks in stage 2: Stage finished
2022-06-17 06:10:10 [Driver]  INFO [DAGScheduler:57]: Job 1 finished: collect at XGBoost.scala:431, took 3022.842636 s
2022-06-17 06:10:10 [Driver]  INFO [RabitTracker:213]: Tracker Process ends with exit code 1
2022-06-17 06:10:10 [Driver]  INFO [XGBoostSpark:433]: Rabit returns with exit code 1
2022-06-17 06:10:11 [Driver] ERROR [XGBoostSpark:455]: the job was aborted due to 
ml.dmlc.xgboost4j.java.XGBoostError: XGBoostModel training failed.
	at ml.dmlc.xgboost4j.scala.spark.XGBoost$.trainDistributed(XGBoost.scala:435)
	at ml.dmlc.xgboost4j.scala.spark.XGBoostRegressor.train(XGBoostRegressor.scala:190)
	at ml.dmlc.xgboost4j.scala.spark.XGBoostRegressor.train(XGBoostRegressor.scala:37)
	at org.apache.spark.ml.Predictor.fit(Predictor.scala:151)
	at SparkPi$.main(SparkPi.scala:52)
	at SparkPi.main(SparkPi.scala)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.apache.spark.deploy.yarn.ApplicationMaster$$anon$2.run(ApplicationMaster.scala:737)
2022-06-17 06:10:11 [Driver] ERROR [ApplicationMaster:94]: User class threw exception: ml.dmlc.xgboost4j.java.XGBoostError: XGBoostModel training failed.
ml.dmlc.xgboost4j.java.XGBoostError: XGBoostModel training failed.
	at ml.dmlc.xgboost4j.scala.spark.XGBoost$.trainDistributed(XGBoost.scala:435)
	at ml.dmlc.xgboost4j.scala.spark.XGBoostRegressor.train(XGBoostRegressor.scala:190)
	at ml.dmlc.xgboost4j.scala.spark.XGBoostRegressor.train(XGBoostRegressor.scala:37)
	at org.apache.spark.ml.Predictor.fit(Predictor.scala:151)
	at SparkPi$.main(SparkPi.scala:52)
	at SparkPi.main(SparkPi.scala)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.apache.spark.deploy.yarn.ApplicationMaster$$anon$2.run(ApplicationMaster.scala:737)
2022-06-17 06:10:11 [Driver]  INFO [ApplicationMaster:57]: Final app status: FAILED, exitCode: 15, (reason: User class threw exception: ml.dmlc.xgboost4j.java.XGBoostError: XGBoostModel training failed.
	at ml.dmlc.xgboost4j.scala.spark.XGBoost$.trainDistributed(XGBoost.scala:435)
	at ml.dmlc.xgboost4j.scala.spark.XGBoostRegressor.train(XGBoostRegressor.scala:190)
	at ml.dmlc.xgboost4j.scala.spark.XGBoostRegressor.train(XGBoostRegressor.scala:37)
	at org.apache.spark.ml.Predictor.fit(Predictor.scala:151)
	at SparkPi$.main(SparkPi.scala:52)
	at SparkPi.main(SparkPi.scala)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.apache.spark.deploy.yarn.ApplicationMaster$$anon$2.run(ApplicationMaster.scala:737)

**Comment by trivialfis** [comment]
Hi, could you please post the log from executors?

**Comment by Jasonzjj** [comment]
executors seems like running successfully。。

**Comment by Jasonzjj** [comment]
Executors seems like running successfully。

log：
2022-06-17 14:04:32 [dispatcher-Executor]  INFO [YarnCoarseGrainedExecutorBackend:57]: Got assigned task 92
2022-06-17 14:04:32 [Executor task launch worker for task 60.0 in stage 1.0 (TID 92)]  INFO [Executor:57]: Running task 60.0 in stage 1.0 (TID 92)
2022-06-17 14:04:33 [Executor task launch worker for task 60.0 in stage 1.0 (TID 92)]  INFO [FileScanRDD:57]: Reading File path: afs://xingtian.afs.baidu.com:9902/user/feed_plat/job_data/development/zhengjianjia/spark/spark_train_c, range: 3976977000-4043259950, partition values: [empty row]
2022-06-17 14:04:53 [Executor task launch worker for task 60.0 in stage 1.0 (TID 92)]  INFO [Executor:57]: Finished task 60.0 in stage 1.0 (TID 92). 1759 bytes result sent to driver
2022-06-17 14:04:54 [dispatcher-Executor]  INFO [YarnCoarseGrainedExecutorBackend:57]: Got assigned task 102
2022-06-17 14:04:54 [Executor task launch worker for task 6.0 in stage 2.0 (TID 102)]  INFO [Executor:57]: Running task 6.0 in stage 2.0 (TID 102)
2022-06-17 14:04:54 [Executor task launch worker for task 6.0 in stage 2.0 (TID 102)]  INFO [MapOutputTrackerWorker:57]: Updating epoch to 1 and clearing cache
2022-06-17 14:04:54 [Executor task launch worker for task 6.0 in stage 2.0 (TID 102)]  INFO [TorrentBroadcast:57]: Started reading broadcast variable 4 with 1 pieces (estimated total size 4.0 MiB)
2022-06-17 14:04:54 [Executor task launch worker for task 6.0 in stage 2.0 (TID 102)]  INFO [TransportClientFactory:310]: Successfully created connection to yq01-hpc-lvliang-i1316.yq01.baidu.com/10.108.181.24:49763 after 1 ms (0 ms spent in bootstraps)
2022-06-17 14:04:54 [Executor task launch worker for task 6.0 in stage 2.0 (TID 102)]  INFO [MemoryStore:57]: Block broadcast_4_piece0 stored as bytes in memory (estimated size 5.2 KiB, free 2.8 GiB)
2022-06-17 14:04:54 [Executor task launch worker for task 6.0 in stage 2.0 (TID 102)]  INFO [TorrentBroadcast:57]: Reading broadcast variable 4 took 21 ms
2022-06-17 14:04:54 [Executor task launch worker for task 6.0 in stage 2.0 (TID 102)]  INFO [MemoryStore:57]: Block broadcast_4 stored as values in memory (estimated size 9.4 KiB, free 2.8 GiB)
2022-06-17 14:04:55 [Executor task launch worker for task 6.0 in stage 2.0 (TID 102)]  INFO [MemoryStore:57]: Block rdd_20_6 stored as values in memory (estimated size 4.8 MiB, free 2.8 GiB)
2022-06-17 14:04:56 [Executor task launch worker for task 6.0 in stage 2.0 (TID 102)]  INFO [MapOutputTrackerWorker:57]: Don't have map outputs for shuffle 0, fetching them
2022-06-17 14:04:56 [Executor task launch worker for task 6.0 in stage 2.0 (TID 102)]  INFO [MapOutputTrackerWorker:57]: Doing the fetch; tracker endpoint = NettyRpcEndpointRef(spark://MapOutputTracker@yq01-hpc-lvliang-i1316.yq01.baidu.com:57813)
2022-06-17 14:04:56 [Executor task launch worker for task 6.0 in stage 2.0 (TID 102)]  INFO [MapOutputTrackerWorker:57]: Got the map output locations
2022-06-17 14:04:56 [Executor task launch worker for task 6.0 in stage 2.0 (TID 102)]  INFO [ShuffleBlockFetcherIterator:57]: Getting 64 (255.7 MiB) non-empty blocks including 8 (32.0 MiB) local and 0 (0.0 B) host-local and 0 (0.0 B) push-merged-local and 56 (223.7 MiB) remote blocks
2022-06-17 14:04:56 [Executor task launch worker for task 6.0 in stage 2.0 (TID 102)]  INFO [TransportClientFactory:310]: Successfully created connection to yq01-hpc-lvliang-i1108.yq01.baidu.com/10.108.175.12:56296 after 11 ms (0 ms spent in bootstraps)
2022-06-17 14:04:56 [Executor task launch worker for task 6.0 in stage 2.0 (TID 102)]  INFO [ShuffleBlockFetcherIterator:57]: Started 5 remote fetches in 117 ms
2022-06-17 14:05:14 [Executor task launch worker for task 6.0 in stage 2.0 (TID 102)]  INFO [TransportClientFactory:310]: Successfully created connection to yq01-hpc-lvliang-i1111.yq01.baidu.com/10.108.175.15:55054 after 3 ms (0 ms spent in bootstraps)
2022-06-17 14:05:26 [Executor task launch worker for task 6.0 in stage 2.0 (TID 102)]  INFO [TransportClientFactory:310]: Successfully created connection to yq01-hpc-lvliang-i1106.yq01.baidu.com/10.108.174.44:52970 after 2 ms (0 ms spent in bootstraps)
2022-06-17 14:56:12 [Executor task launch worker for task 6.0 in stage 2.0 (TID 102)]  INFO [Executor:57]: 1 block locks were not released by task 6.0 in stage 2.0 (TID 102)
[rdd_20_6]
2022-06-17 14:56:12 [Executor task launch worker for task 6.0 in stage 2.0 (TID 102)]  INFO [Executor:57]: Finished task 6.0 in stage 2.0 (TID 102). 1177 bytes result sent to driver
2022-06-17 15:08:23 [dispatcher-Executor]  INFO [YarnCoarseGrainedExecutorBackend:57]: Driver commanded a shutdown
2022-06-17 15:08:24 [dispatcher-Executor]  INFO [YarnCoarseGrainedExecutorBackend:57]: Driver from yq01-hpc-lvliang-i1316.yq01.baidu.com:57813 disconnected during shutdown
2022-06-17 15:08:24 [dispatcher-Executor]  INFO [YarnCoarseGrainedExecutorBackend:57]: Driver from yq01-hpc-lvliang-i1316.yq01.baidu.com:57813 disconnected during shutdown
2022-06-17 15:08:24 [CoarseGrainedExecutorBackend-stop-executor]  INFO [MemoryStore:57]: MemoryStore cleared
2022-06-17 15:08:24 [CoarseGrainedExecutorBackend-stop-executor]  INFO [BlockManager:57]: BlockManager stopped
2022-06-17 15:08:24 [CoarseGrainedExecutorBackend-stop-executor]  INFO [TSDBReporter:222]: stop sending
2022-06-17 15:08:24 [Thread-2]  INFO [ShutdownHookManager:57]: Shutdown hook called

output：
[06:05:51] [690]	train-rmse:34.52551950994114094

[06:05:55] [691]	train-rmse:34.52534229661804943

[06:06:00] [692]	train-rmse:34.52519560304814661

[06:06:03] [693]	train-rmse:34.52512034711867273

[06:06:06] [694]	train-rmse:34.52495916896965156

[06:06:09] [695]	train-rmse:34.52486004181641022

[06:06:13] [696]	train-rmse:34.52474283998827076

[06:06:17] [697]	train-rmse:34.52446090707221771

[06:06:20] [698]	train-rmse:34.52429376354228197

[06:06:23] [699]	train-rmse:34.52418313626171908

**Comment by Jasonzjj** [comment]
train failed with local mode as well.

output log:
[15:50:46] [690]	train-rmse:0.00520688644065732

[15:50:46] [691]	train-rmse:0.00520692697203341

[15:50:46] [692]	train-rmse:0.00520696681770753

[15:50:46] [693]	train-rmse:0.00520700622236835

[15:50:46] [694]	train-rmse:0.00520704498998811

[15:50:46] [695]	train-rmse:0.00520708323702370

[15:50:47] [696]	train-rmse:0.00520712108582036

[15:50:47] [697]	train-rmse:0.00520715829172192

[15:50:47] [698]	train-rmse:0.00520719506255524

[15:50:47] [699]	train-rmse:0.00520723134969795

22/06/17 15:50:47 ERROR XGBoostSpark: the job was aborted due to
ml.dmlc.xgboost4j.java.XGBoostError: XGBoostModel training failed.
	at ml.dmlc.xgboost4j.scala.spark.XGBoost$.trainDistributed(XGBoost.scala:435)
	at ml.dmlc.xgboost4j.scala.spark.XGBoostRegressor.train(XGBoostRegressor.scala:190)
	at ml.dmlc.xgboost4j.scala.spark.XGBoostRegressor.train(XGBoostRegressor.scala:37)
	at org.apache.spark.ml.Predictor.fit(Predictor.scala:151)
	at $line14.$read$$iw$$iw$$iw$$iw$$iw$$iw$$iw$$iw.<init>(example:44)
	at $line14.$read$$iw$$iw$$iw$$iw$$iw$$iw$$iw.<init>(example:61)
	at $line14.$read$$iw$$iw$$iw$$iw$$iw$$iw.<init>(example:63)
	at $line14.$read$$iw$$iw$$iw$$iw$$iw.<init>(example:65)
	at $line14.$read$$iw$$iw$$iw$$iw.<init>(example:67)
	at $line14.$read$$iw$$iw$$iw.<init>(example:69)
	at $line14.$read$$iw$$iw.<init>(example:71)
	at $line14.$read$$iw.<init>(example:73)
	at $line14.$read.<init>(example:75)
	at $line14.$read$.<init>(example:79)
	at $line14.$read$.<clinit>(example)
	at $line14.$eval$.$print$lzycompute(example:7)
	at $line14.$eval$.$print(example:6)
	at $line14.$eval.$print(example)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at scala.tools.nsc.interpreter.IMain$ReadEvalPrint.call(IMain.scala:747)
	at scala.tools.nsc.interpreter.IMain$Request.loadAndRun(IMain.scala:1020)
	at scala.tools.nsc.interpreter.IMain.$anonfun$interpret$1(IMain.scala:568)
	at scala.reflect.internal.util.ScalaClassLoader.asContext(ScalaClassLoader.scala:36)
	at scala.reflect.internal.util.ScalaClassLoader.asContext$(ScalaClassLoader.scala:116)
	at scala.reflect.internal.util.AbstractFileClassLoader.asContext(AbstractFileClassLoader.scala:41)
	at scala.tools.nsc.interpreter.IMain.loadAndRunReq$1(IMain.scala:567)
	at scala.tools.nsc.interpreter.IMain.interpret(IMain.scala:594)
	at scala.tools.nsc.interpreter.IMain.interpret(IMain.scala:564)
	at scala.tools.nsc.interpreter.ILoop.$anonfun$pasteCommand$11(ILoop.scala:795)
	at scala.tools.nsc.interpreter.IMain.withLabel(IMain.scala:111)
	at scala.tools.nsc.interpreter.ILoop.interpretCode$1(ILoop.scala:795)
	at scala.tools.nsc.interpreter.ILoop.pasteCommand(ILoop.scala:801)
	at org.apache.spark.repl.SparkILoop.$anonfun$process$8(SparkILoop.scala:177)
	at org.apache.spark.repl.SparkILoop.$anonfun$process$8$adapted(SparkILoop.scala:176)
	at scala.collection.immutable.List.foreach(List.scala:431)
	at org.apache.spark.repl.SparkILoop.loadInitFiles$1(SparkILoop.scala:176)
	at org.apache.spark.repl.SparkILoop.$anonfun$process$4(SparkILoop.scala:166)
	at scala.runtime.java8.JFunction0$mcV$sp.apply(JFunction0$mcV$sp.java:23)
	at scala.tools.nsc.interpreter.ILoop.$anonfun$mumly$1(ILoop.scala:166)
	at scala.tools.nsc.interpreter.IMain.beQuietDuring(IMain.scala:206)
	at scala.tools.nsc.interpreter.ILoop.mumly(ILoop.scala:163)
	at org.apache.spark.repl.SparkILoop.loopPostInit$1(SparkILoop.scala:153)
	at org.apache.spark.repl.SparkILoop.$anonfun$process$10(SparkILoop.scala:221)
	at org.apache.spark.repl.SparkILoop.withSuppressedSettings$1(SparkILoop.scala:189)
	at org.apache.spark.repl.SparkILoop.startup$1(SparkILoop.scala:201)
	at org.apache.spark.repl.SparkILoop.process(SparkILoop.scala:236)
	at org.apache.spark.repl.Main$.doMain(Main.scala:78)
	at org.apache.spark.repl.Main$.main(Main.scala:58)
	at org.apache.spark.repl.Main.main(Main.scala)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.apache.spark.deploy.JavaMainApplication.start(SparkApplication.scala:52)
	at org.apache.spark.deploy.SparkSubmit.org$apache$spark$deploy$SparkSubmit$$runMain(SparkSubmit.scala:958)
	at org.apache.spark.deploy.SparkSubmit.doRunMain$1(SparkSubmit.scala:180)
	at org.apache.spark.deploy.SparkSubmit.submit(SparkSubmit.scala:203)
	at org.apache.spark.deploy.SparkSubmit.doSubmit(SparkSubmit.scala:90)
	at org.apache.spark.deploy.SparkSubmit$$anon$2.doSubmit(SparkSubmit.scala:1046)
	at org.apache.spark.deploy.SparkSubmit$.main(SparkSubmit.scala:1055)
	at org.apache.spark.deploy.SparkSubmit.main(SparkSubmit.scala)
ml.dmlc.xgboost4j.java.XGBoostError: XGBoostModel training failed.
  at ml.dmlc.xgboost4j.scala.spark.XGBoost$.trainDistributed(XGBoost.scala:435)
  at ml.dmlc.xgboost4j.scala.spark.XGBoostRegressor.train(XGBoostRegressor.scala:190)
  at ml.dmlc.xgboost4j.scala.spark.XGBoostRegressor.train(XGBoostRegressor.scala:37)
  at org.apache.spark.ml.Predictor.fit(Predictor.scala:151)
  ... 60 elided

**Comment by Jasonzjj** [comment]
executors log:
2022-06-17 14:04:32 [dispatcher-Executor]  INFO [YarnCoarseGrainedExecutorBackend:57]: Got assigned task 92
2022-06-17 14:04:32 [Executor task launch worker for task 60.0 in stage 1.0 (TID 92)]  INFO [Executor:57]: Running task 60.0 in stage 1.0 (TID 92)
2022-06-17 14:04:33 [Executor task launch worker for task 60.0 in stage 1.0 (TID 92)]  INFO [FileScanRDD:57]: Reading File path: /train, range: 3976977000-4043259950, partition values: [empty row]
2022-06-17 14:04:53 [Executor task launch worker for task 60.0 in stage 1.0 (TID 92)]  INFO [Executor:57]: Finished task 60.0 in stage 1.0 (TID 92). 1759 bytes result sent to driver
2022-06-17 14:04:54 [dispatcher-Executor]  INFO [YarnCoarseGrainedExecutorBackend:57]: Got assigned task 102
2022-06-17 14:04:54 [Executor task launch worker for task 6.0 in stage 2.0 (TID 102)]  INFO [Executor:57]: Running task 6.0 in stage 2.0 (TID 102)
2022-06-17 14:04:54 [Executor task launch worker for task 6.0 in stage 2.0 (TID 102)]  INFO [MapOutputTrackerWorker:57]: Updating epoch to 1 and clearing cache
2022-06-17 14:04:54 [Executor task launch worker for task 6.0 in stage 2.0 (TID 102)]  INFO [TorrentBroadcast:57]: Started reading broadcast variable 4 with 1 pieces (estimated total size 4.0 MiB)
2022-06-17 14:04:54 [Executor task launch worker for task 6.0 in stage 2.0 (TID 102)]  INFO [TransportClientFactory:310]: Successfully created connection to after 1 ms (0 ms spent in bootstraps)
2022-06-17 14:04:54 [Executor task launch worker for task 6.0 in stage 2.0 (TID 102)]  INFO [MemoryStore:57]: Block broadcast_4_piece0 stored as bytes in memory (estimated size 5.2 KiB, free 2.8 GiB)
2022-06-17 14:04:54 [Executor task launch worker for task 6.0 in stage 2.0 (TID 102)]  INFO [TorrentBroadcast:57]: Reading broadcast variable 4 took 21 ms
2022-06-17 14:04:54 [Executor task launch worker for task 6.0 in stage 2.0 (TID 102)]  INFO [MemoryStore:57]: Block broadcast_4 stored as values in memory (estimated size 9.4 KiB, free 2.8 GiB)
2022-06-17 14:04:55 [Executor task launch worker for task 6.0 in stage 2.0 (TID 102)]  INFO [MemoryStore:57]: Block rdd_20_6 stored as values in memory (estimated size 4.8 MiB, free 2.8 GiB)
2022-06-17 14:04:56 [Executor task launch worker for task 6.0 in stage 2.0 (TID 102)]  INFO [MapOutputTrackerWorker:57]: Don't have map outputs for shuffle 0, fetching them
2022-06-17 14:04:56 [Executor task launch worker for task 6.0 in stage 2.0 (TID 102)]  INFO [MapOutputTrackerWorker:57]: Doing the fetch; tracker endpoint = NettyRpcEndpointRef(spark://MapOutputTracker@) 2022-06-17 14:04:56 [Executor task launch worker for task 6.0 in stage 2.0 (TID 102)]  INFO [MapOutputTrackerWorker:57]: Got the map output locations
2022-06-17 14:04:56 [Executor task launch worker for task 6.0 in stage 2.0 (TID 102)]  INFO [ShuffleBlockFetcherIterator:57]: Getting 64 (255.7 MiB) non-empty blocks including 8 (32.0 MiB) local and 0 (0.0 B) host-local and 0 (0.0 B) push-merged-local and 56 (223.7 MiB) remote blocks
2022-06-17 14:04:56 [Executor task launch worker for task 6.0 in stage 2.0 (TID 102)]  INFO [TransportClientFactory:310]: Successfully created connection to after 11 ms (0 ms spent in bootstraps)
2022-06-17 14:04:56 [Executor task launch worker for task 6.0 in stage 2.0 (TID 102)]  INFO [ShuffleBlockFetcherIterator:57]: Started 5 remote fetches in 117 ms
2022-06-17 14:05:14 [Executor task launch worker for task 6.0 in stage 2.0 (TID 102)]  INFO [TransportClientFactory:310]: Successfully created connection to after 3 ms (0 ms spent in bootstraps)
2022-06-17 14:05:26 [Executor task launch worker for task 6.0 in stage 2.0 (TID 102)]  INFO [TransportClientFactory:310]: Successfully created connection to after 2 ms (0 ms spent in bootstraps)
2022-06-17 14:56:12 [Executor task launch worker for task 6.0 in stage 2.0 (TID 102)]  INFO [Executor:57]: 1 block locks were not released by task 6.0 in stage 2.0 (TID 102)
[rdd_20_6]
2022-06-17 14:56:12 [Executor task launch worker for task 6.0 in stage 2.0 (TID 102)]  INFO [Executor:57]: Finished task 6.0 in stage 2.0 (TID 102). 1177 bytes result sent to driver
2022-06-17 15:08:23 [dispatcher-Executor]  INFO [YarnCoarseGrainedExecutorBackend:57]: Driver commanded a shutdown
2022-06-17 15:08:24 [dispatcher-Executor]  INFO [YarnCoarseGrainedExecutorBackend:57]: Driver from disconnected during shutdown
2022-06-17 15:08:24 [dispatcher-Executor]  INFO [YarnCoarseGrainedExecutorBackend:57]: Driver from isconnected during shutdown
2022-06-17 15:08:24 [CoarseGrainedExecutorBackend-stop-executor]  INFO [MemoryStore:57]: MemoryStore cleared
2022-06-17 15:08:24 [CoarseGrainedExecutorBackend-stop-executor]  INFO [BlockManager:57]: BlockManager stopped
2022-06-17 15:08:24 [CoarseGrainedExecutorBackend-stop-executor]  INFO [TSDBReporter:222]: stop sending
2022-06-17 15:08:24 [Thread-2]  INFO [ShutdownHookManager:57]: Shutdown hook called

**Comment by Jasonzjj** [comment]
Simplified code：
val xgbReg = new XGBoostRegressor(xgbParam).
            setFeaturesCol("features").
            setLabelCol("label")

            val xgbInput = spark.read.format("libsvm").load("adata")
            val xgbModel = xgbReg.fit(xgbInput)

            val results = xgbModel.transform(xgbInput)

            xgbModel.nativeBooster.saveModel(fs_out)

**Comment by Jasonzjj** [comment]
@trivialfis could you please help me out thist problem?

**Comment by trivialfis** [comment]
@wbo4958 Could you please take a look when you are available?

**Comment by wbo4958** [comment]
Sorry for late response, @Jasonzjj , Looks like driver sent the SHUTDOWN from the exeuctor log

``` console
 Driver commanded a shutdown
2022-06-17 15:08:24 [dispatcher-Executor] INFO [YarnCoarseGrainedExecutorBackend:57]: Driver from disconnected during shutdown
```

Could you please double-check?

if the executor log is correct one, please fill the executor log with exceptions.

**Comment by jbcsimple** [comment]
last, did you solve then problem?

**Comment by Wanke15** [comment]
Got same error run on EMR, but it's ok run in local Mac

**Comment by jxudata** [comment]
same error

**Comment by diggzhang** [comment]
same error

**Comment by trivialfis** [comment]
Closing as the tracker is rewritten https://github.com/dmlc/xgboost/pull/10112
