### ISSUE TITLE
[XGBoost4j-Spark] Loading model gives XGBoostError: basic_string::resize

### ISSUE THREAD

**Issue by olbapjose** [dmlc/xgboost#8074]
I have trained a Spark ML pipeline (Spark 3) on Databricks with XGBoost-Spark version 1.5.2, where the last stage is a Spark XGBoostClassifierModel with "multi:softmax" output. The model has been logged to MLflow but I cannot load it back due to a failure in loading the last stage. I have tried loading it in my notebook directly from DBFS as well (no MLflow involved) and I get exactly the same error (see below) both with XGBoost version 1.5.2 and 1.6.1. 

You can find the stage attached (only the last stage, which should be loadable directly as an XGBoostClassificationModel)

```
XGBoostError: basic_string::resize
	at ml.dmlc.xgboost4j.java.XGBoostJNI.checkCall(XGBoostJNI.java:48)
	at ml.dmlc.xgboost4j.java.Booster.loadModel(Booster.java:81)
	at ml.dmlc.xgboost4j.java.XGBoost.loadModel(XGBoost.java:64)
	at ml.dmlc.xgboost4j.scala.XGBoost$.loadModel(XGBoost.scala:157)
	at ml.dmlc.xgboost4j.scala.spark.XGBoostClassificationModel$XGBoostClassificationModelReader.load(XGBoostClassifier.scala:549)
	at ml.dmlc.xgboost4j.scala.spark.XGBoostClassificationModel$XGBoostClassificationModelReader.load(XGBoostClassifier.scala:533)
	at org.apache.spark.ml.Pipeline$SharedReadWrite$.$anonfun$load$5(Pipeline.scala:277)
	at org.apache.spark.ml.MLEvents.withLoadInstanceEvent(events.scala:161)
	at org.apache.spark.ml.MLEvents.withLoadInstanceEvent$(events.scala:156)
	at org.apache.spark.ml.util.Instrumentation.withLoadInstanceEvent(Instrumentation.scala:43)
	at org.apache.spark.ml.Pipeline$SharedReadWrite$.$anonfun$load$4(Pipeline.scala:277)
	at scala.collection.TraversableLike.$anonfun$map$1(TraversableLike.scala:238)
	at scala.collection.IndexedSeqOptimized.foreach(IndexedSeqOptimized.scala:36)
	at scala.collection.IndexedSeqOptimized.foreach$(IndexedSeqOptimized.scala:33)
	at scala.collection.mutable.ArrayOps$ofRef.foreach(ArrayOps.scala:198)
	at scala.collection.TraversableLike.map(TraversableLike.scala:238)
	at scala.collection.TraversableLike.map$(TraversableLike.scala:231)
	at scala.collection.mutable.ArrayOps$ofRef.map(ArrayOps.scala:198)
	at org.apache.spark.ml.Pipeline$SharedReadWrite$.$anonfun$load$3(Pipeline.scala:274)
	at org.apache.spark.ml.util.Instrumentation$.$anonfun$instrumented$1(Instrumentation.scala:284)
	at scala.util.Try$.apply(Try.scala:213)
```
[XGBoostClassificationModel.zip](https://github.com/dmlc/xgboost/files/9113242/XGBoostClassificationModel.zip)

**Comment by olbapjose** [comment]
Excuse me, any updates on this? Thanks

**Comment by olbapjose** [comment]
@wbo4958 excuse me for mentioning you... looks like nobody is looking at this... thanks

**Comment by wbo4958** [comment]
@olbapjose Sorry for the late, I will check it.

**Comment by olbapjose** [comment]
@wbo4958  Did you have time to check it? It is really impacting our team

**Comment by wbo4958** [comment]
Sorry for the delay, I will check it today and give some feedback.

**Comment by wbo4958** [comment]
@olbapjose I tried with 

``` scala
      val model = XGBoostClassificationModel.load("/home/bobwang/tmp/XGBoostClassificationModel")
      model.nativeBooster.saveModel("/tmp/xxxx.json")
```
and it worked as expected.

**Comment by wbo4958** [comment]
no issue happens locally

**Comment by wbo4958** [comment]
@olbapjose Can you share the code loading the model by Pipeline?

**Comment by trivialfis** [comment]
Closing due to stalled.
