### ISSUE TITLE
RabitTracker:179 - FAULT: failed to start tracker process

### ISSUE THREAD

**Issue by Ayyan-droid** [dmlc/xgboost#8191]
hi i am getting this error can any guide me 
spark version 3.1
xgboost4j_2.12-1.6.1.jar
xgboost4j-spark_2.12-1.6.1.jar

ERROR RabitTracker:179 - FAULT: failed to start tracker process
ERROR XGBoostSpark:643 - the job was aborted due to 
java.lang.IllegalArgumentException: requirement failed: FAULT: Failed to start tracker
	at scala.Predef$.require(Predef.scala:281)
	at ml.dmlc.xgboost4j.scala.spark.XGBoost$.startTracker(XGBoost.scala:436)
	at ml.dmlc.xgboost4j.scala.spark.XGBoost$.trainDistributed(XGBoost.scala:593)
	at ml.dmlc.xgboost4j.scala.spark.XGBoostClassifier.train(XGBoostClassifier.scala:199)
	at ml.dmlc.xgboost4j.scala.spark.XGBoostClassifier.train(XGBoostClassifier.scala:40)
	at org.apache.spark.ml.Predictor.fit(Predictor.scala:151)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at py4j.reflection.MethodInvoker.invoke(MethodInvoker.java:244)
	at py4j.reflection.ReflectionEngine.invoke(ReflectionEngine.java:357)
	at py4j.Gateway.invoke(Gateway.java:282)
	at py4j.commands.AbstractCommand.invokeMethod(AbstractCommand.java:132)
	at py4j.commands.CallCommand.execute(CallCommand.java:79)
	at py4j.GatewayConnection.run(GatewayConnection.java:238)
	at java.lang.Thread.run(Thread.java:750)

**Comment by trivialfis** [comment]
Could you please share the specification of the environment where we can try to reproduce it?

**Comment by Ayyan-droid** [comment]
hi i am running it on docker with following versions
spark version 3.1
xgboost4j_2.12-1.6.1.jar
xgboost4j-spark_2.12-1.6.1.jar

**Comment by Ayyan-droid** [comment]
code works fine on local environment

**Comment by Ayyan-droid** [comment]
hii kindly help me on this issue
i am completely stuck
i am using a docker image
with python version 3.7.11
spark 3.1

**Comment by trivialfis** [comment]
Hi, we need more information on how to reproduce it. We run XGBoost jobs almost daily and haven't seen it.

**Comment by Ayyan-droid** [comment]
hi Dmlc/Xgboost
i am using redhat/ubi8:8.4 linux for docker image

and i am using code from this repo https://github.com/sllynn/spark-xgboost

spark 3.1.1 python 3.7.11

and xgboost4j and xgboost4j spark 2.12-1.6.1

kindly help

regards

**Comment by Ayyan-droid** [comment]
How can i specify tracker propertise

**Comment by trivialfis** [comment]
@Ayyan-droid Consider using the pyspark in xgboost with the nightly build.

Nightly build:
https://xgboost.readthedocs.io/en/latest/install.html#id1

Pyspark tutorial:
https://xgboost.readthedocs.io/en/latest/tutorials/spark_estimator.html

**Comment by wbo4958** [comment]
@Ayyan-droid if you're using the XGBoost jvm packages, you can specify the Tracker configuration by

`Map("tracker_conf" -> TrackerConf(0l, "python", YOUR_IP, PYTHON_EXEC))`

See 

``` scala
case class TrackerConf(workerConnectionTimeout: Long, trackerImpl: String,
  hostIp: String = "", pythonExec: String = "")
```
