### ISSUE TITLE
ml.dmlc.xgboost4j.java.XGBoostError: XGBoostModel training failed.

### ISSUE THREAD

**Issue by ITHM** [dmlc/xgboost#8194]
Scala = 2.12.10
spark = 3.1.3
xgboost  = 1.6.1

I have tried many versions from xgboost=0.82, to the latest version 1.6.1, and reported the same error "ml.dmlc.xgboost4j.java.XGBoostError: XGBoostModel training failed.", there is no more detailed information, I have tried both under Windows and Linux, but it doesn't work. Windows can be trained several times, and then an error is reported. I can't test it, and my head is big! ! ! I've tried all the methods I've tried, but it's still an error.Here is the error log:

22/08/22 22:38:21 ERROR XGBoostSpark: the job was aborted due to 
ml.dmlc.xgboost4j.java.XGBoostError: XGBoostModel training failed.
	at ml.dmlc.xgboost4j.scala.spark.XGBoost$.trainDistributed(XGBoost.scala:435)
	at ml.dmlc.xgboost4j.scala.spark.XGBoostClassifier.train(XGBoostClassifier.scala:196)
	at ml.dmlc.xgboost4j.scala.spark.XGBoostClassifier.train(XGBoostClassifier.scala:35)
	at org.apache.spark.ml.Predictor.fit(Predictor.scala:151)
	at org.apache.spark.ml.Predictor.fit(Predictor.scala:115)
	at org.apache.spark.ml.Pipeline.$anonfun$fit$5(Pipeline.scala:151)
	at org.apache.spark.ml.MLEvents.withFitEvent(events.scala:130)
	at org.apache.spark.ml.MLEvents.withFitEvent$(events.scala:123)
	at org.apache.spark.ml.util.Instrumentation.withFitEvent(Instrumentation.scala:42)
	at org.apache.spark.ml.Pipeline.$anonfun$fit$4(Pipeline.scala:151)
	at scala.collection.Iterator.foreach(Iterator.scala:941)
	at scala.collection.Iterator.foreach$(Iterator.scala:941)
	at scala.collection.AbstractIterator.foreach(Iterator.scala:1429)
	at org.apache.spark.ml.Pipeline.$anonfun$fit$2(Pipeline.scala:147)
	at org.apache.spark.ml.MLEvents.withFitEvent(events.scala:130)
	at org.apache.spark.ml.MLEvents.withFitEvent$(events.scala:123)
	at org.apache.spark.ml.util.Instrumentation.withFitEvent(Instrumentation.scala:42)
	at org.apache.spark.ml.Pipeline.$anonfun$fit$1(Pipeline.scala:133)
	at org.apache.spark.ml.util.Instrumentation$.$anonfun$instrumented$1(Instrumentation.scala:191)
	at scala.util.Try$.apply(Try.scala:213)
	at org.apache.spark.ml.util.Instrumentation$.instrumented(Instrumentation.scala:191)
	at org.apache.spark.ml.Pipeline.fit(Pipeline.scala:133)

Please save the children, thank you

**Comment by wbo4958** [comment]
@ITHM Could you please provide the source code and script to repro this issue?

**Comment by ITHM** [comment]
@wbo4958 The code is official，https://xgboost.readthedocs.io/en/latest/jvm/xgboost4j_spark_tutorial.html
@trivialfis

**Comment by ITHM** [comment]
@wbo4958 @trivialfis Thanks to the big guys, the problem is solved, the problem is because the xgboost model I ran under the win single machine (the error that I put in the discussion area has not been solved so far), it has been successfully run on the Hadoop cluster

**Comment by trivialfis** [comment]
Great news!
