### ISSUE TITLE
Can't import xgboost in python 3.7

### ISSUE THREAD

**Issue by razdoburdin** [dmlc/xgboost#8258]
Hi,

I faced with a bug in trying to import xgboost in python 3.7 on Ubuntu.

Here is a step by step building of xgboost from sources:
```
conda create -n xgb_test python=3.7 -y
conda activate xgb_test
conda install -c conda-forge gxx cmake make numpy scipy
git clone --recursive https://github.com/dmlc/xgboost
cd xgboost
mkdir build
cd build/
cmake ..
make
cd ../python-package/
python setup.py install
```

then in a python environment:
`import xgboost as xgb`

And here is the error message:
```
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/localdisk2/mkl/drazdobu/xgboost_test/python-package/xgboost/__init__.py", line 8, in <module>
    from . import dask
  File "/localdisk2/mkl/drazdobu/xgboost_test/python-package/xgboost/dask.py", line 43, in <module>
    from typing import (
ImportError: cannot import name 'TypedDict' from 'typing' (/export/users/drazdobu/miniconda/envs/xgb_test/lib/python3.7/typing.py)
```
I found, that for commit
**7d43e74e71c1a0f6526fda78d46395c883d14cb0**
the bug doesn't take place, while for 
**b791446623977516a47d4795b2860dd590242335** 
it does

**Comment by hcho3** [comment]
XGBoost now requires Python 3.8+:
