### ISSUE TITLE
xgboost running with kubernetes issue

### ISSUE THREAD

**Issue by Ayyan-droid** [dmlc/xgboost#8412]
i am using the following jars 

xgboost4j-spark_2.12-1.6.1.jar
xgboost4j_2.12-1.6.1.jar

**Here is the stack trace:**

Traceback (most recent call last):
  File "/u/bin/ai_fraudengine/AIModelTrain/aimodeltrain/bl/StandardModelTrainHandlerImpl.py", line 32, in train_model
    trained_pipeline = train_pipeline.fit(df)
  File "/opt/spark/python/pyspark/ml/base.py", line 161, in fit
    return self._fit(dataset)
  File "/opt/spark/python/pyspark/ml/pipeline.py", line 114, in _fit
    model = stage.fit(dataset)
  File "/opt/spark/python/pyspark/ml/base.py", line 161, in fit
    return self._fit(dataset)
  File "/opt/spark/python/pyspark/ml/wrapper.py", line 335, in _fit
    java_model = self._fit_java(dataset)
  File "/opt/spark/python/pyspark/ml/wrapper.py", line 331, in _fit_java
    self._transfer_params_to_java()
  File "/opt/spark/python/pyspark/ml/wrapper.py", line 143, in _transfer_params_to_java
    pair = self._make_java_param_pair(param, self._paramMap[param])
  File "/opt/spark/python/pyspark/ml/wrapper.py", line 134, in _make_java_param_pair
    return java_param.w(java_value)
  File "/opt/spark/python/lib/py4j-0.10.9-src.zip/py4j/java_gateway.py", line 1305, in __call__
    answer, self.gateway_client, self.target_id, self.name)
  File "/opt/spark/python/pyspark/sql/utils.py", line 111, in deco
    return f(*a, **kw)
  File "/opt/spark/python/lib/py4j-0.10.9-src.zip/py4j/protocol.py", line 328, in get_return_value
    format(target_id, ".", name), value)
py4j.protocol.Py4JJavaError: An error occurred while calling o18402.w.
: java.lang.ClassCastException: java.lang.String cannot be cast to java.lang.Integer
        at scala.runtime.BoxesRunTime.unboxToInt(BoxesRunTime.java:103)
        at org.apache.spark.ml.param.IntParam.w(params.scala:382)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:498)
        at py4j.reflection.MethodInvoker.invoke(MethodInvoker.java:244)
        at py4j.reflection.ReflectionEngine.invoke(ReflectionEngine.java:357)
        at py4j.Gateway.invoke(Gateway.java:282)
        at py4j.commands.AbstractCommand.invokeMethod(AbstractCommand.java:132)
        at py4j.commands.CallCommand.execute(CallCommand.java:79)
        at py4j.GatewayConnection.run(GatewayConnection.java:238)
        at java.lang.Thread.run(Thread.java:750)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/u/bin/ai_fraudengine/AIModelTrain/aimodeltrain/bl/ModelTrainHandlerImpl.py", line 101, in train_model
    execution_context_info=execution_context_info, model_class_handler=model_class, model=model, validation_df = validation_df)
  File "/u/bin/ai_fraudengine/AIModelTrain/aimodeltrain/bl/StandardModelTrainHandlerImpl.py", line 50, in train_model
    raise CommonBaseException(exp)
commonexceps.CommonBaseException.CommonBaseException: An error occurred while calling o18402.w.
: java.lang.ClassCastException: java.lang.String cannot be cast to java.lang.Integer
        at scala.runtime.BoxesRunTime.unboxToInt(BoxesRunTime.java:103)
        at org.apache.spark.ml.param.IntParam.w(params.scala:382)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:498)
        at py4j.reflection.MethodInvoker.invoke(MethodInvoker.java:244)
        at py4j.reflection.ReflectionEngine.invoke(ReflectionEngine.java:357)
        at py4j.Gateway.invoke(Gateway.java:282)
        at py4j.commands.AbstractCommand.invokeMethod(AbstractCommand.java:132)
        at py4j.commands.CallCommand.execute(CallCommand.java:79)
        at py4j.GatewayConnection.run(GatewayConnection.java:238)
        at java.lang.Thread.run(Thread.java:750)

**Comment by trivialfis** [comment]
Hi, if you are using PySpark can you consider using the PySpark interface of XGBoost instead of the jvm package? I read through your backtrace and couldn't find any mention of XGBoost, which makes it difficult to guess what's happening.

**Comment by Ayyan-droid** [comment]
resolved
