### ISSUE TITLE
XGBoost not working if executed with python -OO

### ISSUE THREAD

**Issue by interseba5** [dmlc/xgboost#8537]
## Enviroment
Python: 3.9.5 
Executable: C:\Python39\python.exe
OS: Windows
Arch: x86_64
WindowsRelease: 10

## Reproducible code
```Python
from xgboost import XGBClassifier
print("Hello World")
```

## The bug
If i try to execute the code with python -OO flag i obtain the following error:
```
Traceback (most recent call last):
  File "F:\main.py", line 1, in <module>
    from xgboost import XGBClassifier
  File "C:\Python39\lib\site-packages\xgboost\__init__.py", line 18, in <module>
    from . import dask
  File "C:\Python39\lib\site-packages\xgboost\dask.py", line 63, in <module>
    from .sklearn import XGBModel, XGBClassifier, XGBRegressorBase, XGBClassifierBase
  File "C:\Python39\lib\site-packages\xgboost\sklearn.py", line 1300, in <module>
    class XGBClassifier(XGBModel, XGBClassifierBase):
  File "C:\Python39\lib\site-packages\xgboost\sklearn.py", line 1421, in XGBClassifier
    fit.__doc__ = XGBModel.fit.__doc__.replace(
AttributeError: 'NoneType' object has no attribute 'replace'
```

**Comment by trivialfis** [comment]
Thank you for raising the issue. However, I don't think we will fix that, like many other packages, we have document generation procedures, adding checks to all those places, and having to run all the tests with this additional option is infeasible.
