### ISSUE TITLE
pyspark+xgboost1.7.1 requires cuda to be installed on driver nodes

### ISSUE THREAD

**Issue by nvliyuan** [dmlc/xgboost#8566]
I tried training with pyspark and xgboost 1.7.1 in this [example](https://github.com/NVIDIA/spark-rapids-examples/pull/252/files#diff-1fb047e1256c1d51fdee48ab5779f3bad41270e54098277c0c4d6918230eb0e7)
I found that it request cuda in spark driver nodes, is it a feature or a bug?
Env:

spark standalone cluster:
1 master without GPU
8 workers with 1 A100 GPU

python libs:
pyspark3.2.1
xgboost1.7.1
cudf-cu11
scikit-learn

train params:
```
params = { 
    "tree_method": "gpu_hist",
    "grow_policy": "depthwise",
    "num_workers": 8,
    "use_gpu": "true",
}
```
only if I submit the spark job(run notebook) on worker nodes, it works. If I submit the job on master node, it will failed with below error:
```
ImportError: /opt/spark/spark-3.2.1-bin-hadoop3.2/work/app-20221206072901-0031/3/environment/lib/python3.8/site-packages/cupy_backends/cuda/api/runtime.cpython-38-x86_64-linux-gnu.so: symbol cudaMemPoolCreate version libcudart.so.11.0 not defined in file libcudart.so.11.0 with link time reference
The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/opt/spark/spark-3.2.1-bin-hadoop3.2/python/lib/pyspark.zip/pyspark/worker.py", line 619, in main
```

**Comment by trivialfis** [comment]
could you please paste the complete backtrace on the driver?

**Comment by trivialfis** [comment]
also, could you please try nightly build as well?

**Comment by nvliyuan** [comment]
```
[I 02:03:12.026 NotebookApp] Saving file at /MortgageETL+XGBoost-gpu.ipynb
Thread-5 22/12/08 02:03:53:762 WARN package: Truncated the string representation of a plan since it was too large. This behavior can be adjusted by setting 'spark.sql.debug.maxToStringFields'.
task-result-getter-0 22/12/08 02:04:09:768 WARN TaskSetManager: Lost task 0.0 in stage 6.0 (TID 36) (10.150.166.223 executor 0): org.apache.spark.api.python.PythonException: Traceback (most recent call last):
  File "/opt/spark/spark-3.2.1-bin-hadoop3.2/work/app-20221208020223-0020/0/environment/lib/python3.8/site-packages/cupy/__init__.py", line 18, in <module>
    from cupy import _core  # NOQA
  File "/opt/spark/spark-3.2.1-bin-hadoop3.2/work/app-20221208020223-0020/0/environment/lib/python3.8/site-packages/cupy/_core/__init__.py", line 1, in <module>
    from cupy._core import core  # NOQA
  File "cupy/_core/core.pyx", line 1, in init cupy._core.core
  File "/opt/spark/spark-3.2.1-bin-hadoop3.2/work/app-20221208020223-0020/0/environment/lib/python3.8/site-packages/cupy/cuda/__init__.py", line 8, in <module>
    from cupy.cuda import compiler  # NOQA
  File "/opt/spark/spark-3.2.1-bin-hadoop3.2/work/app-20221208020223-0020/0/environment/lib/python3.8/site-packages/cupy/cuda/compiler.py", line 13, in <module>
    from cupy.cuda import device
  File "cupy/cuda/device.pyx", line 1, in init cupy.cuda.device
ImportError: /opt/spark/spark-3.2.1-bin-hadoop3.2/work/app-20221208020223-0020/0/environment/lib/python3.8/site-packages/cupy_backends/cuda/api/runtime.cpython-38-x86_64-linux-gnu.so: symbol cudaMemPoolCreate version libcudart.so.11.0 not defined in file libcudart.so.11.0 with link time reference

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/opt/spark/spark-3.2.1-bin-hadoop3.2/python/lib/pyspark.zip/pyspark/worker.py", line 619, in main
    process()
  File "/opt/spark/spark-3.2.1-bin-hadoop3.2/python/lib/pyspark.zip/pyspark/worker.py", line 611, in process
    serializer.dump_stream(out_iter, outfile)
  File "/opt/spark/spark-3.2.1-bin-hadoop3.2/python/lib/pyspark.zip/pyspark/sql/pandas/serializers.py", line 273, in dump_stream
    return ArrowStreamSerializer.dump_stream(self, init_stream_yield_batches(), stream)
  File "/opt/spark/spark-3.2.1-bin-hadoop3.2/python/lib/pyspark.zip/pyspark/sql/pandas/serializers.py", line 81, in dump_stream
    for batch in iterator:
  File "/opt/spark/spark-3.2.1-bin-hadoop3.2/python/lib/pyspark.zip/pyspark/sql/pandas/serializers.py", line 266, in init_stream_yield_batches
    for series in iterator:
  File "/opt/spark/spark-3.2.1-bin-hadoop3.2/python/lib/pyspark.zip/pyspark/worker.py", line 358, in func
    for result_batch, result_type in result_iter:
  File "/home/rladmin/yuali/python-env/xgb170_pyspark_venv/lib/python3.8/site-packages/xgboost/spark/core.py", line 796, in _train_booster
    dtrain, dvalid = create_dmatrix_from_partitions(
  File "/opt/spark/spark-3.2.1-bin-hadoop3.2/work/app-20221208020223-0020/0/environment/lib/python3.8/site-packages/xgboost/spark/data.py", line 303, in create_dmatrix_from_partitions
    dtrain: DMatrix = make_qdm(train_data, gpu_id, meta, None, params)
  File "/opt/spark/spark-3.2.1-bin-hadoop3.2/work/app-20221208020223-0020/0/environment/lib/python3.8/site-packages/xgboost/spark/data.py", line 167, in make_qdm
    m = QuantileDMatrix(it, **params, ref=ref)
  File "/opt/spark/spark-3.2.1-bin-hadoop3.2/work/app-20221208020223-0020/0/environment/lib/python3.8/site-packages/xgboost/core.py", line 620, in inner_f
    return func(**kwargs)
  File "/opt/spark/spark-3.2.1-bin-hadoop3.2/work/app-20221208020223-0020/0/environment/lib/python3.8/site-packages/xgboost/core.py", line 1386, in __init__
    self._init(
  File "/opt/spark/spark-3.2.1-bin-hadoop3.2/work/app-20221208020223-0020/0/environment/lib/python3.8/site-packages/xgboost/core.py", line 1445, in _init
    it.reraise()
  File "/opt/spark/spark-3.2.1-bin-hadoop3.2/work/app-20221208020223-0020/0/environment/lib/python3.8/site-packages/xgboost/core.py", line 488, in reraise
    raise exc  # pylint: disable=raising-bad-type
  File "/opt/spark/spark-3.2.1-bin-hadoop3.2/work/app-20221208020223-0020/0/environment/lib/python3.8/site-packages/xgboost/core.py", line 469, in _handle_exception
    return fn()
  File "/opt/spark/spark-3.2.1-bin-hadoop3.2/work/app-20221208020223-0020/0/environment/lib/python3.8/site-packages/xgboost/core.py", line 534, in <lambda>
    return self._handle_exception(lambda: self.next(input_data), 0)
  File "/opt/spark/spark-3.2.1-bin-hadoop3.2/work/app-20221208020223-0020/0/environment/lib/python3.8/site-packages/xgboost/spark/data.py", line 99, in next
    data=self._fetch(self._data[alias.data]),
  File "/opt/spark/spark-3.2.1-bin-hadoop3.2/work/app-20221208020223-0020/0/environment/lib/python3.8/site-packages/xgboost/spark/data.py", line 85, in _fetch
    import cudf  # pylint: disable=import-error
  File "/opt/spark/spark-3.2.1-bin-hadoop3.2/work/app-20221208020223-0020/0/environment/lib/python3.8/site-packages/cudf/__init__.py", line 7, in <module>
    import cupy
  File "/opt/spark/spark-3.2.1-bin-hadoop3.2/work/app-20221208020223-0020/0/environment/lib/python3.8/site-packages/cupy/__init__.py", line 20, in <module>
    raise ImportError(f'''
ImportError:
================================================================
Failed to import CuPy.

If you installed CuPy via wheels (cupy-cudaXXX or cupy-rocm-X-X), make sure that the package matches with the version of CUDA or ROCm installed.

On Linux, you may need to set LD_LIBRARY_PATH environment variable depending on how you installed CUDA/ROCm.
On Windows, try setting CUDA_PATH environment variable.

Check the Installation Guide for details:
  https://docs.cupy.dev/en/latest/install.html

Original error:
  ImportError: /opt/spark/spark-3.2.1-bin-hadoop3.2/work/app-20221208020223-0020/0/environment/lib/python3.8/site-packages/cupy_backends/cuda/api/runtime.cpython-38-x86_64-linux-gnu.so: symbol cudaMemPoolCreate version libcudart.so.11.0 not defined in file libcudart.so.11.0 with link time reference
================================================================


  at org.apache.spark.api.python.BasePythonRunner$ReaderIterator.handlePythonException(PythonRunner.scala:555)
  at org.apache.spark.sql.rapids.execution.python.GpuPythonArrowOutput$$anon$1.read(GpuArrowPythonRunner.scala:180)
  at org.apache.spark.sql.rapids.execution.python.GpuPythonArrowOutput$$anon$1.read(GpuArrowPythonRunner.scala:125)
  at org.apache.spark.api.python.BasePythonRunner$ReaderIterator.hasNext(PythonRunner.scala:508)
  at org.apache.spark.InterruptibleIterator.hasNext(InterruptibleIterator.scala:37)
  at scala.collection.Iterator$$anon$10.hasNext(Iterator.scala:460)
  at com.nvidia.spark.rapids.ColumnarToRowIterator.$anonfun$fetchNextBatch$2(GpuColumnarToRowExec.scala:239)
  at com.nvidia.spark.rapids.Arm.withResource(Arm.scala:28)
  at com.nvidia.spark.rapids.Arm.withResource$(Arm.scala:26)
  at com.nvidia.spark.rapids.ColumnarToRowIterator.withResource(GpuColumnarToRowExec.scala:187)
  at com.nvidia.spark.rapids.ColumnarToRowIterator.fetchNextBatch(GpuColumnarToRowExec.scala:238)
  at com.nvidia.spark.rapids.ColumnarToRowIterator.loadNextBatch(GpuColumnarToRowExec.scala:215)
  at com.nvidia.spark.rapids.ColumnarToRowIterator.hasNext(GpuColumnarToRowExec.scala:255)
  at scala.collection.Iterator$$anon$10.hasNext(Iterator.scala:460)
  at scala.collection.Iterator$$anon$10.hasNext(Iterator.scala:460)
  at org.apache.spark.api.python.SerDeUtil$AutoBatchedPickler.hasNext(SerDeUtil.scala:86)
  at scala.collection.Iterator.foreach(Iterator.scala:943)
  at scala.collection.Iterator.foreach$(Iterator.scala:943)
  at org.apache.spark.api.python.SerDeUtil$AutoBatchedPickler.foreach(SerDeUtil.scala:80)
  at org.apache.spark.api.python.PythonRDD$.writeIteratorToStream(PythonRDD.scala:307)
  at org.apache.spark.api.python.PythonRunner$$anon$2.writeIteratorToStream(PythonRunner.scala:680)
  at org.apache.spark.api.python.BasePythonRunner$WriterThread.$anonfun$run$1(PythonRunner.scala:434)
  at org.apache.spark.util.Utils$.logUncaughtExceptions(Utils.scala:2019)
  at org.apache.spark.api.python.BasePythonRunner$WriterThread.run(PythonRunner.scala:269)

[I 02:05:09.837 NotebookApp] Saving file at /MortgageETL+XGBoost-gpu.ipynb
```

**Comment by nvliyuan** [comment]
@wbo4958 @trivialfis just verified there is a folder named `/usr/local/cuda-11.0` which was cuda11.0, if we remove the folder, and then submit the job on master nodes, it works, so it does not requires Cuda to be installed on driver nodes

**Comment by trivialfis** [comment]
Excellent!
