### ISSUE TITLE
QuantileDMatrix no longer take libsvm file as an input?

### ISSUE THREAD

**Issue by weitian** [dmlc/xgboost#8618]
XGBoost 1.7.2

dtrain=xgb.QuantileDMatrix('/Users/weitian/tmp/data.test')
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Users/weitian/opt/miniconda3/envs/turi/lib/python3.9/site-packages/xgboost/core.py", line 620, in inner_f
    return func(**kwargs)
  File "/Users/weitian/opt/miniconda3/envs/turi/lib/python3.9/site-packages/xgboost/core.py", line 1386, in __init__
    self._init(
  File "/Users/weitian/opt/miniconda3/envs/turi/lib/python3.9/site-packages/xgboost/core.py", line 1445, in _init
    it.reraise()
  File "/Users/weitian/opt/miniconda3/envs/turi/lib/python3.9/site-packages/xgboost/core.py", line 488, in reraise
    raise exc  # pylint: disable=raising-bad-type
  File "/Users/weitian/opt/miniconda3/envs/turi/lib/python3.9/site-packages/xgboost/core.py", line 469, in _handle_exception
    return fn()
  File "/Users/weitian/opt/miniconda3/envs/turi/lib/python3.9/site-packages/xgboost/core.py", line 534, in <lambda>
    return self._handle_exception(lambda: self.next(input_data), 0)
  File "/Users/weitian/opt/miniconda3/envs/turi/lib/python3.9/site-packages/xgboost/data.py", line 1172, in next
    input_data(**self.kwargs)
  File "/Users/weitian/opt/miniconda3/envs/turi/lib/python3.9/site-packages/xgboost/core.py", line 620, in inner_f
    return func(**kwargs)
  File "/Users/weitian/opt/miniconda3/envs/turi/lib/python3.9/site-packages/xgboost/core.py", line 519, in input_data
    new, cat_codes, feature_names, feature_types = _proxy_transform(
  File "/Users/weitian/opt/miniconda3/envs/turi/lib/python3.9/site-packages/xgboost/data.py", line 1206, in _proxy_transform
    raise TypeError("Value type is not supported for data iterator:" + str(type(data)))
TypeError: Value type is not supported for data iterator:<class 'str'>

**Comment by trivialfis** [comment]
It never does. Users are encouraged to use 3-party libraries for loading data.

**Comment by weitian** [comment]
then the Doc should be updated:
https://xgboost.readthedocs.io/en/stable/python/python_api.html#xgboost.QuantileDMatrix

data (os.PathLike/string/numpy.array/scipy.sparse/pd.DataFrame/) –

dt.Frame/cudf.DataFrame/cupy.array/dlpack/arrow.Table

Data source of DMatrix.

When data is string or os.PathLike type, it represents the path libsvm format txt file, csv file (by specifying uri parameter ‘path_to_csv?format=csv’), or binary file that xgboost can read from.

**Comment by trivialfis** [comment]
Thank you for pointing it out. We are working on that https://github.com/dmlc/xgboost/issues/8541
