### ISSUE TITLE
AssertionError when trying to load data in in multi-node Dask cluster

### ISSUE THREAD

**Issue by dewan-c** [dmlc/xgboost#8671]
Hello, I'm trying to run XGBoost training on multiple EC2 instances with GPUs(example config - 2 g4dn.xlarge instances). However, when I split the input data between instances using [distribution=“ShardedByS3Key”](https://docs.aws.amazon.com/sagemaker/latest/APIReference/API_S3DataSource.html), and try to use read_csv(for multi-part csv) or read_parquet, I run into the following error:

```
Traceback (most recent call last):
  File "/miniconda3/lib/python3.8/runpy.py", line 194, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/miniconda3/lib/python3.8/runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "/opt/ml/code/dask_entry_script.py", line 218, in <module>
    dtrain = xgb.dask.DaskDeviceQuantileDMatrix(client, X_train, y_train)
  File "/miniconda3/lib/python3.8/site-packages/xgboost/core.py", line 506, in inner_f
    return f(**kwargs)
  File "/miniconda3/lib/python3.8/site-packages/xgboost/dask.py", line 645, in __init__
    super().__init__(
  File "/miniconda3/lib/python3.8/site-packages/xgboost/core.py", line 506, in inner_f
    return f(**kwargs)
  File "/miniconda3/lib/python3.8/site-packages/xgboost/dask.py", line 298, in __init__
    self._init = client.sync(
  File "/miniconda3/lib/python3.8/site-packages/distributed/utils.py", line 339, in sync
    return sync(
  File "/miniconda3/lib/python3.8/site-packages/distributed/utils.py", line 406, in sync
    raise exc.with_traceback(tb)
  File "/miniconda3/lib/python3.8/site-packages/distributed/utils.py", line 379, in f
    result = yield future
  File "/miniconda3/lib/python3.8/site-packages/tornado/gen.py", line 762, in run
    value = future.result()
  File "/miniconda3/lib/python3.8/site-packages/xgboost/dask.py", line 405, in _map_local_data
    assert part.status == 'finished', part.status
AssertionError: error
2023-01-11 23:48:23,820 - distributed.worker - WARNING - Compute Failed
Key:       ('getitem-2bf7ea2dffeb67f46f1be3403a0e834e', 14)
Function:  subgraph_callable-bb500a8d-2a0a-4808-873e-ef7e67ed
args:      ({'piece': ('/opt/ml/input/data/train/xgboost_benchmark_95.parquet', [0], [])})
kwargs:    {}
Exception: "FileNotFoundError('/opt/ml/input/data/train/xgboost_benchmark_95.parquet')"
2023-01-11 23:48:23,822 - distributed.worker - WARNING - Compute Failed
Key:       ('getitem-2bf7ea2dffeb67f46f1be3403a0e834e', 20)
Function:  subgraph_callable-bb500a8d-2a0a-4808-873e-ef7e67ed
args:      ({'piece': ('/opt/ml/input/data/train/xgboost_benchmark_142.parquet', [0], [])})
kwargs:    {}
```

If I replicate the entire dataset in each instance, the training completes. I know this probably is a Dask question, but since the error is coming from XGBoost package, I'm asking here - _is it by design that all the data has to be replicated to each instance_? I'm surprised to see this and I'm worried that I might not be using Dask for XGBoost training correctly. I had posted in [Dask forum](https://dask.discourse.group/t/filenotfounderror-when-reading-input-in-distributed-cluster/1425), but didn't get a response.
My code looks like the following:

```
# Start a scheduler in one node, and dask-cuda-worker in all nodes
def start_daemons(master_ip, current_host_ip, num_gpus):
    cmd_start_scheduler = os.path.join(DASK_PATH, "dask-scheduler")
    cmd_start_worker = os.path.join(DASK_PATH, "dask-cuda-worker")
    schedule_conn_string = "tcp://{ip}:".format(ip=master_ip) + str(SCHEDULER_PORT)
    worker_cli_command = [cmd_start_worker, schedule_conn_string, "--no-dashboard", "--nthreads", "4"]
    if master_ip == current_host_ip:
        Popen([cmd_start_scheduler, "--no-dashboard"])
       
    new_env = os.environ.copy()
    for gpu in range(0,num_gpus):
        new_env["CUDA_VISIBLE_DEVICES"] = str(gpu)
        Popen(worker_cli_command, env=new_env)
# Helper to load data
def load_csv(train_path, valid_path):
    colnames = ['label'] + ['feature-%02d' % i for i in range(1, 29)]
    train_dask_df = dask_cudf.read_csv(train_path + "/*.csv", header=None, names=colnames)
    valid_dask_df = dask_cudf.read_csv(valid_path + "/*.csv", header=None, names=colnames)
    ...
    return X_train, X_valid, y_train, y_valid
...
# After daemons are started, submit the job from one node.
if current_host_ip == master_host_ip:
            with Client(scheduler_addr) as client:

                X_train, X_valid, y_train, y_valid = load_csv(args.train, args.validation)

                # DaskDMatrix acts like normal DMatrix, works as a proxy for local
                # DMatrix scattered around the workers.
                dtrain = xgb.dask.DaskDeviceQuantileDMatrix(client, X_train, y_train)
                dvalid = xgb.dask.DaskDMatrix(client, X_valid, y_valid)
                ....
```
Is there a way to run to run the training with data split between the instances? Thanks!

**Comment by trivialfis** [comment]
> is it by design that all the data has to be replicated to each instance

No. But it can take some effort to launch task on each worker to load the data and join them together.

Most of the cluster types are configured with a common storage pool shared by all workers and all data are stored there uniformly.

**Comment by trivialfis** [comment]
I think there are two options you may try:
1. Submit tasks for each worker to load the data and concatenate them using dask.
2. Configure your cluster to access a common storage pool like s3.

I will close this issue now, feel free to reopen if there's something xgboost can do.

**Comment by dewan-c** [comment]
Thanks for the quick response! I was trying the first approach recommended, since the second one wouldn't work for us. I'm using `client.submit` to submit read tasks to the cluster and then concatenate the resulting dataframes, but still see the assertionerror when creating DaskDeviceQuantileDMatrix. I'll look into this farther before reaching out for help again.

**Comment by trivialfis** [comment]
Feel free to open news issues if you can more specific questions
