### ISSUE TITLE
XGBoostModel training failed on AWS EMR cluster

### ISSUE THREAD

**Issue by nvliyuan** [dmlc/xgboost#8746]
I try to run the mortgage xgboost training demo (training both CPU and GPU) on the [AWS EMR cluster as steps](https://github.com/nvliyuan/spark-rapids-examples/blob/v2302-legacy-doc-updates/docs/get-started/xgboost-examples/csp/aws/emr.md), but I hit issue:
```
23/02/01 03:46:20 INFO SparkContext: Successfully stopped SparkContext
23/02/01 03:46:20 ERROR ApplicationMaster: User class threw exception: ml.dmlc.xgboost4j.java.XGBoostError: XGBoostModel training failed.
ml.dmlc.xgboost4j.java.XGBoostError: XGBoostModel training failed.
	at ml.dmlc.xgboost4j.scala.spark.XGBoost$.trainDistributed(XGBoost.scala:418) ~[__app__.jar:?]
	at ml.dmlc.xgboost4j.scala.spark.XGBoostClassifier.train(XGBoostClassifier.scala:202) ~[__app__.jar:?]
	at ml.dmlc.xgboost4j.scala.spark.XGBoostClassifier.train(XGBoostClassifier.scala:34) ~[__app__.jar:?]
	at org.apache.spark.ml.Predictor.fit(Predictor.scala:151) ~[spark-mllib_2.12-3.3.0-amzn-1.jar:3.3.0-amzn-1]
	at com.nvidia.spark.examples.mortgage.Main$.$anonfun$main$4(Main.scala:67) ~[__app__.jar:?]
	at com.nvidia.spark.examples.utility.Benchmark.time(Benchmark.scala:29) ~[__app__.jar:?]
	at com.nvidia.spark.examples.mortgage.Main$.main(Main.scala:67) ~[__app__.jar:?]
	at com.nvidia.spark.examples.mortgage.Main.main(Main.scala) ~[__app__.jar:?]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_352]
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_352]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_352]
	at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_352]
	at org.apache.spark.deploy.yarn.ApplicationMaster$$anon$2.run(ApplicationMaster.scala:742) ~[spark-yarn_2.12-3.3.0-amzn-1.jar:3.3.0-amzn-1]
23/02/01 03:46:20 INFO ApplicationMaster: Final app status: FAILED, exitCode: 15, (reason: User class threw exception: ml.dmlc.xgboost4j.java.XGBoostError: XGBoostModel training failed.
	at ml.dmlc.xgboost4j.scala.spark.XGBoost$.trainDistributed(XGBoost.scala:418)
	at ml.dmlc.xgboost4j.scala.spark.XGBoostClassifier.train(XGBoostClassifier.scala:202)
	at ml.dmlc.xgboost4j.scala.spark.XGBoostClassifier.train(XGBoostClassifier.scala:34)
	at org.apache.spark.ml.Predictor.fit(Predictor.scala:151)
	at com.nvidia.spark.examples.mortgage.Main$.$anonfun$main$4(Main.scala:67)
	at com.nvidia.spark.examples.utility.Benchmark.time(Benchmark.scala:29)
	at com.nvidia.spark.examples.mortgage.Main$.main(Main.scala:67)
```
I also tried running on my local env(spark320 standalone cluster), but did not hit any issues. So I suspect is there any compatibility issues on the AWS EMR spark version.

**Comment by nvliyuan** [comment]
[application_1675216611460_0008.tar.zip](https://github.com/dmlc/xgboost/files/10554019/application_1675216611460_0008.tar.zip)
please see the logs for more details

**Comment by nvliyuan** [comment]
@wbo4958 FYI

**Comment by nvliyuan** [comment]
could someone help with this error?

**Comment by trivialfis** [comment]
I think @wbo4958 looked into it and found an issue with rabit network connection? I can help debug if there's an existing setup that I can use. I'm not familiar with aws deployment.

**Comment by eordentlich** [comment]
fwiw, I found that nccl was not using the correct network interfaces on AWS EMR when I was trying out the pyspark api.  In case it is related to this error, see https://github.com/dmlc/xgboost/issues/7982#issuecomment-1379390906 .

**Comment by nvliyuan** [comment]
I didn't run with pyspark xgboost api, I run with scala, could that be the same NCCL reason? I did not find any NCCL related output log.

**Comment by eordentlich** [comment]
NCCL is in the core c++ layer and I believe it will be used by all higher level apis running distributed gpu_hist mode (e.g. both spark apis).   You can turn on NCCL logging following [this comment](https://github.com/dmlc/xgboost/issues/7982#issuecomment-1150931569) on that same thread.

**Comment by trivialfis** [comment]
I think this is caused by incorrectly configured Python error:

```
23/02/01 03:46:11 INFO SparkContext: Created broadcast 8 from broadcast at GpuParquetScan.scala:113
23/02/01 03:46:11 INFO RabitTracker$TrackerProcessLogger:   File "/mnt/yarn/usercache/hadoop/appcache/application_1675216611460_0008/container_1675216611460_0008_01_000001/tmp/tracker6036301105427904005.py", line 24
23/02/01 03:46:11 INFO RabitTracker$TrackerProcessLogger:     def __init__(self, sock: socket.socket) -> None:
23/02/01 03:46:11 INFO RabitTracker$TrackerProcessLogger:                            ^
23/02/01 03:46:11 INFO RabitTracker$TrackerProcessLogger: SyntaxError: invalid syntax
23/02/01 03:46:11 ERROR RabitTracker$TrackerProcessLogger: Tracker Process ends with exit code 1
23/02/01 03:46:11 INFO SparkContext: Starting job: collect at XGBoost.scala:414
```

Please check the available Python version on your worker, XGBoost requires Python >= 3.8.
