### ISSUE TITLE
xgboost4j-spark_2.12 2.0.0-SNAPSHOT Issue on Azure Synapse

### ISSUE THREAD

**Issue by myj1k** [dmlc/xgboost#8763]
We have a Synapse notebook(in Scala) using Spark + xgboost4j and the notebook fails with following error:

java.lang.NoSuchMethodError: akka.serialization.BaseSerializer$.identifierFromConfig(Ljava/lang/String;Lakka/actor/ExtendedActorSystem;)I
      at akka.serialization.IntSerializer.<init>(PrimitiveSerializers.scala:63)
      at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
      at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
      at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
      at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
      at akka.actor.ReflectiveDynamicAccess.$anonfun$createInstanceFor$1(ReflectiveDynamicAccess.scala:33)
      at scala.util.Try$.apply(Try.scala:213)
      at akka.actor.ReflectiveDynamicAccess.createInstanceFor(ReflectiveDynamicAccess.scala:28)
      at akka.actor.ReflectiveDynamicAccess.$anonfun$createInstanceFor$5(ReflectiveDynamicAccess.scala:41)
      at scala.util.Success.flatMap(Try.scala:251)
      at akka.actor.ReflectiveDynamicAccess.createInstanceFor(ReflectiveDynamicAccess.scala:40)
      at akka.serialization.Serialization.serializerOf(Serialization.scala:397)
      at akka.serialization.Serialization.$anonfun$serializers$2(Serialization.scala:426)
      at scala.collection.TraversableLike$WithFilter.$anonfun$map$2(TraversableLike.scala:935)
      at scala.collection.immutable.HashMap$HashMap1.foreach(HashMap.scala:400)
      at scala.collection.immutable.HashMap$HashTrieMap.foreach(HashMap.scala:728)
      at scala.collection.TraversableLike$WithFilter.map(TraversableLike.scala:934)
      at akka.serialization.Serialization.<init>(Serialization.scala:426)
      at akka.serialization.SerializationExtension$.createExtension(SerializationExtension.scala:16)
      at akka.serialization.SerializationExtension$.createExtension(SerializationExtension.scala:13)
      at akka.actor.ActorSystemImpl.registerExtension(ActorSystem.scala:1006)
      at akka.actor.ActorSystemImpl.$anonfun$loadExtensions$1(ActorSystem.scala:1044)
      at scala.collection.Iterator.foreach(Iterator.scala:943)
      at scala.collection.Iterator.foreach$(Iterator.scala:943)
      at scala.collection.AbstractIterator.foreach(Iterator.scala:1431)
      at scala.collection.IterableLike.foreach(IterableLike.scala:74)
      at scala.collection.IterableLike.foreach$(IterableLike.scala:73)
      at scala.collection.AbstractIterable.foreach(Iterable.scala:56)
      at akka.actor.ActorSystemImpl.loadExtensions$1(ActorSystem.scala:1040)
      at akka.actor.ActorSystemImpl.loadExtensions(ActorSystem.scala:1056)
      at akka.actor.ActorSystemImpl.liftedTree2$1(ActorSystem.scala:920)
      at akka.actor.ActorSystemImpl._start$lzycompute(ActorSystem.scala:908)
      at akka.actor.ActorSystemImpl._start(ActorSystem.scala:908)
      at akka.actor.ActorSystemImpl.start(ActorSystem.scala:930)
      at akka.actor.ActorSystem$.apply(ActorSystem.scala:258)
      at akka.actor.ActorSystem$.apply(ActorSystem.scala:302)
      at akka.actor.ActorSystem$.apply(ActorSystem.scala:246)
      at akka.actor.ActorSystem$.create(ActorSystem.scala:176)
      at ml.dmlc.xgboost4j.scala.rabit.RabitTracker.<init>(RabitTracker.scala:71)
      at ml.dmlc.xgboost4j.scala.spark.XGBoost$.getTracker(XGBoost.scala:353)
      at ml.dmlc.xgboost4j.scala.spark.XGBoost$.startTracker(XGBoost.scala:361)
      at ml.dmlc.xgboost4j.scala.spark.XGBoost$.trainDistributed(XGBoost.scala:395)
      at ml.dmlc.xgboost4j.scala.spark.XGBoostClassifier.train(XGBoostClassifier.scala:202)
      at ml.dmlc.xgboost4j.scala.spark.XGBoostClassifier.train(XGBoostClassifier.scala:34)
      at org.apache.spark.ml.Predictor.fit(Predictor.scala:151)
      at org.apache.spark.ml.Predictor.fit(Predictor.scala:115)
      at org.apache.spark.ml.Pipeline.$anonfun$fit$5(Pipeline.scala:151)
      at org.apache.spark.ml.MLEvents.withFitEvent(events.scala:130)
      at org.apache.spark.ml.MLEvents.withFitEvent$(events.scala:123)
      at org.apache.spark.ml.util.Instrumentation.withFitEvent(Instrumentation.scala:42)
      at org.apache.spark.ml.Pipeline.$anonfun$fit$4(Pipeline.scala:151)
      at scala.collection.Iterator.foreach(Iterator.scala:943)
      at scala.collection.Iterator.foreach$(Iterator.scala:943)
      at scala.collection.AbstractIterator.foreach(Iterator.scala:1431)
      at org.apache.spark.ml.Pipeline.$anonfun$fit$2(Pipeline.scala:147)
      at org.apache.spark.ml.MLEvents.withFitEvent(events.scala:130)
      at org.apache.spark.ml.MLEvents.withFitEvent$(events.scala:123)
      at org.apache.spark.ml.util.Instrumentation.withFitEvent(Instrumentation.scala:42)
      at org.apache.spark.ml.Pipeline.$anonfun$fit$1(Pipeline.scala:133)
      at org.apache.spark.ml.util.Instrumentation$.$anonfun$instrumented$1(Instrumentation.scala:191)
      at scala.util.Try$.apply(Try.scala:213)
      at org.apache.spark.ml.util.Instrumentation$.instrumented(Instrumentation.scala:191)
      at org.apache.spark.ml.Pipeline.fit(Pipeline.scala:133)

**xgboost package & repo:**
        "spark.jars.packages": "ml.dmlc:xgboost4j_2.12:2.0.0-SNAPSHOT,ml.dmlc:xgboost4j-spark_2.12:2.0.0-SNAPSHOT",
        "spark.jars.repositories": "https://s3-us-west-2.amazonaws.com/xgboost-maven-repo/snapshot",
**akka-actor version:**
        akka-actor_2.12 2.7.0
**Spark version:**
         Both 3.2 and 3.3 fail

Appreciate any help. Thank!

**Comment by trivialfis** [comment]
akka dependency is removed.
