### ISSUE TITLE
The application will be kill when finishing train model

### ISSUE THREAD

**Issue by yilaguan** [dmlc/xgboost#879]
Hi, When I try to use /demo/distribed-training/run_yarn.sh , some Errors have caused:
root@Master:/usr/local/xgboost/demo/distributed-training# ./run_yarn.sh 2 2 /user/root/test 
mkdir: `/user/root/test/data': File exists
put: `/user/root/test/data/agaricus.txt.train': File exists
put: `/user/root/test/data/agaricus.txt.test': File exists
2016-02-26 17:09:41,552 INFO start listen on 192.168.43.159:9091
16/02/26 17:09:42 WARN util.NativeCodeLoader: Unable to load native-hadoop library for your platform... using builtin-java classes where applicable
16/02/26 17:09:42 INFO client.RMProxy: Connecting to ResourceManager at Master/192.168.43.159:8032
16/02/26 17:09:43 INFO dmlc.Client: jobname=DMLC[nworker=2]:xgboost,username=root
16/02/26 17:09:43 INFO dmlc.Client: Submitting application application_1456464832031_0016
16/02/26 17:09:43 INFO impl.YarnClientImpl: Submitted application application_1456464832031_0016
2016-02-26 17:09:47,526 INFO @tracker All of 2 nodes getting started
2016-02-26 17:09:49,068 INFO [17:09:49] [0]     test-error:0.016139     train-error:0.014433
[17:09:49] [0]  test-error:0.016139     train-error:0.014433
2016-02-26 17:09:49,236 INFO [17:09:49] [1]     test-error:0.000000     train-error:0.001228
[17:09:49] [1]  test-error:0.000000     train-error:0.001228
2016-02-26 17:09:58,537 INFO [17:09:58] [0]     test-error:0.016139     train-error:0.014433
[17:09:58] [0]  test-error:0.016139     train-error:0.014433
2016-02-26 17:09:58,704 INFO [17:09:58] [1]     test-error:0.000000     train-error:0.001228
[17:09:58] [1]  test-error:0.000000     train-error:0.001228
2016-02-26 17:10:06,516 INFO [17:10:06] [0]     test-error:0.016139     train-error:0.014433
[17:10:06] [0]  test-error:0.016139     train-error:0.014433
2016-02-26 17:10:06,677 INFO [17:10:06] [1]     test-error:0.000000     train-error:0.001228
[17:10:06] [1]  test-error:0.000000     train-error:0.001228
Application application_1456464832031_0016 finished with state FINISHED at 1456477808280

Available queues:
default
16/02/26 17:10:08 INFO impl.YarnClientImpl: Killed application application_1456464832031_0016

I don't know why application_1456464832031_0016 was killed.The log can be find below:

[15:11:07] src/tree/updater_prune.cc:74: tree pruning end, 1 roots, 12 extra nodes, 0 pruned nodes, max_depth=3
connect to ip: [192.168.43.159]
[15:11:07] src/tree/updater_prune.cc:74: tree pruning end, 1 roots, 10 extra nodes, 0 pruned nodes, max_depth=3
connect to ip: [192.168.43.159]
16/02/26 15:11:07 WARN hdfs.DFSClient: DataStreamer Exception
org.apache.hadoop.ipc.RemoteException(org.apache.hadoop.hdfs.server.namenode.LeaseExpiredException): No lease on /user/root/test/mushroom.final.model (inode 16466): File does not exist. Holder DFSClient_NONMAPREDUCE_359367512_1 does not have any open files.
        at org.apache.hadoop.hdfs.server.namenode.FSNamesystem.checkLease(FSNamesystem.java:3602)
        at org.apache.hadoop.hdfs.server.namenode.FSNamesystem.analyzeFileState(FSNamesystem.java:3399)
        at org.apache.hadoop.hdfs.server.namenode.FSNamesystem.getAdditionalBlock(FSNamesystem.java:3255)
        at org.apache.hadoop.hdfs.server.namenode.NameNodeRpcServer.addBlock(NameNodeRpcServer.java:676)
        at org.apache.hadoop.hdfs.server.namenode.AuthorizationProviderProxyClientProtocol.addBlock(AuthorizationProviderProxyClientProtocol.java:212)
        at org.apache.hadoop.hdfs.protocolPB.ClientNamenodeProtocolServerSideTranslatorPB.addBlock(ClientNamenodeProtocolServerSideTranslatorPB.java:483)
        at org.apache.hadoop.hdfs.protocol.proto.ClientNamenodeProtocolProtos$ClientNamenodeProtocol$2.callBlockingMethod(ClientNamenodeProtocolProtos.java)
        at org.apache.hadoop.ipc.ProtobufRpcEngine$Server$ProtoBufRpcInvoker.call(ProtobufRpcEngine.java:617)
        at org.apache.hadoop.ipc.RPC$Server.call(RPC.java:1060)
        at org.apache.hadoop.ipc.Server$Handler$1.run(Server.java:2086)
        at org.apache.hadoop.ipc.Server$Handler$1.run(Server.java:2082)
        at java.security.AccessController.doPrivileged(Native Method)
        at javax.security.auth.Subject.doAs(Subject.java:422)
        at org.apache.hadoop.security.UserGroupInformation.doAs(UserGroupInformation.java:1671)
        at org.apache.hadoop.ipc.Server$Handler.run(Server.java:2080)

        at org.apache.hadoop.ipc.Client.call(Client.java:1466)
        at org.apache.hadoop.ipc.Client.call(Client.java:1403)
        at org.apache.hadoop.ipc.ProtobufRpcEngine$Invoker.invoke(ProtobufRpcEngine.java:230)
        at com.sun.proxy.$Proxy9.addBlock(Unknown Source)
        at org.apache.hadoop.hdfs.protocolPB.ClientNamenodeProtocolTranslatorPB.addBlock(ClientNamenodeProtocolTranslatorPB.java:399)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:497)
        at org.apache.hadoop.io.retry.RetryInvocationHandler.invokeMethod(RetryInvocationHandler.java:256)
        at org.apache.hadoop.io.retry.RetryInvocationHandler.invoke(RetryInvocationHandler.java:104)
        at com.sun.proxy.$Proxy10.addBlock(Unknown Source)
        at org.apache.hadoop.hdfs.DFSOutputStream$DataStreamer.locateFollowingBlock(DFSOutputStream.java:1674)
        at org.apache.hadoop.hdfs.DFSOutputStream$DataStreamer.nextBlockOutputStream(DFSOutputStream.java:1471)
        at org.apache.hadoop.hdfs.DFSOutputStream$DataStreamer.run(DFSOutputStream.java:668)
FSDataOutputStream#close error:
org.apache.hadoop.ipc.RemoteException(org.apache.hadoop.hdfs.server.namenode.LeaseExpiredException): No lease on /user/root/test/mushroom.final.model (inode 16466): File does not exist. Holder DFSClient_NONMAPREDUCE_359367512_1 does not have any open files.

**Comment by tqchen** [comment]
Was caused by recent changes in the AppMaster. I think it should not affect the saved procedure. Moved to https://github.com/dmlc/dmlc-core/issues/114
