### ISSUE TITLE
[CI] Gtest segfaults when compiled with sanitizers and GCC 9+

### ISSUE THREAD

**Issue by hcho3** [dmlc/xgboost#8863]
* OS: Ubuntu 20.04.5 LTS
* Compiler: GCC 9.4.0

When I build XGBoost with sanitizers enabled, I get a segfault.

Reproduction:
```bash
cmake .. -GNinja -DUSE_SANITIZER=ON   -DENABLED_SANITIZERS="address;leak;undefined" \
   -DCMAKE_BUILD_TYPE=Debug -DGOOGLE_TEST=ON -DUSE_DMLC_GTEST=ON
ninja
./testxgboost  # segfaults
```

Backtrace:
```
#0  0x0000000000000000 in ?? ()
#1  0x00007ffff76aa045 in __sanitizer::MaybeInstallSigaction (signum=11,
    handler=0x7ffff7693690 <__asan::AsanOnDeadlySignal(int, void*, void*)>)
    at ../../../../src/libsanitizer/sanitizer_common/sanitizer_posix_libcdep.cc:213
#2  0x00007ffff76aa4c2 in __sanitizer::InstallDeadlySignalHandlers (
    handler=0x7ffff7693690 <__asan::AsanOnDeadlySignal(int, void*, void*)>)
    at ../../../../src/libsanitizer/sanitizer_common/sanitizer_posix_libcdep.cc:222
#3  0x00007ffff76994f3 in __asan::AsanInitInternal () at ../../../../src/libsanitizer/asan/asan_rtl.cc:442
#4  __asan::AsanInitInternal () at ../../../../src/libsanitizer/asan/asan_rtl.cc:384
#5  0x00007ffff7fe0cf6 in _dl_init (main_map=0x7ffff7ffe190, argc=1, argv=0x7fffffffe2b8, env=0x7fffffffe2c8)
    at dl-init.c:104
#6  0x00007ffff7fd013a in _dl_start_user () from /lib64/ld-linux-x86-64.so.2
```

**Comment by hcho3** [comment]
Just tried it with GCC 9 and 10, and it still segfaults.

Interestingly, the current CI uses GCC 7, and the gtest doesn't segfault there. So the bug is associated with GCC 9+ versions.

**Comment by hcho3** [comment]
@trivialfis Any idea as to why this is happening? I am hoping to run sanitizers without having to use GCC 7.

**Comment by trivialfis** [comment]
Hmm, I'm using ubuntu 22.04 and its default gcc is 11.3.

- Using only libasan.so.6 works. Segfault if ubsan is also used:
> Warning: REAL(sigaction_symname) == nullptr. This may happen if you link with ubsan statically. Sigaction will not work.

I'm linking ubsan dynamically:
```
ldd ./testxgboost 
        linux-vdso.so.1 (0x00007ffd9114c000)
        libasan.so.6 => /lib/x86_64-linux-gnu/libasan.so.6 (0x00007fb4e7e00000)
        liblsan.so.0 => /lib/x86_64-linux-gnu/liblsan.so.0 (0x00007fb4e7800000)
        libubsan.so.1 => /lib/x86_64-linux-gnu/libubsan.so.1 (0x00007fb4e7000000)
```
- libasan.so.8 doesn't work
```
==100348==Shadow memory range interleaves with an existing memory mapping. ASan cannot proceed correctly. ABORTING.
==100348==ASan shadow was supposed to be located in the [0x00007fff7000-0x10007fff7fff] range.
==100348==This might be related to ELF_ET_DYN_BASE change in Linux 4.12.
==100348==See https://github.com/google/sanitizers/issues/856 for possible workarounds.
```
- Using only ubsan works.
- Using only thread sanitizer works.
