### ISSUE TITLE
xgboost model.attr("best_iteration") error

### ISSUE THREAD

**Issue by yananchen1989** [dmlc/xgboost#9117]
xgboost version 1.7.5

```
def spearmanr(predt: np.ndarray, dtrain: xgb.DMatrix):
    return 'spearmanr', float(scipy.stats.spearmanr(predt, dtrain.get_label()).correlation)
es = xgb.callback.EarlyStopping(
        rounds=100,
        min_delta =0.0001,
        save_best=True,
        maximize=False,
        data_name="val",
        metric_name= 'rmse'
    )


param = {"tree_method": "exact",
    'max_depth':7, 'eta': 0.1, 
      'subsample': 0.7, 'min_child_weight':0.2, 'colsample_bytree':0.7,
      'alpha':0,'lambda':0, 'max_bin':256,'disable_default_eval_metric':False, 
      'max_cat_to_onehot': 10, 'max_cat_threshold': 1000,
      'eval_metric': 'rmse', 'objective':'reg:tweedie' }

for i in range(5):
    bst = xgb.train(param, dtrain, num_boost_round=4000, callbacks=[es],
                        custom_metric= spearmanr, 
                        evals=[(dtrain, 'train'),  (dval, 'val')],  verbose_eval=10) 
```

error:

> Traceback (most recent call last):
>   File "/home/lwk/odc/src/main/python/training.py", line 530, in <module>
>     bst = xgb.train(param, dtrain, num_boost_round=4000, callbacks=[es],
>   File "/home/lwk/anaconda3/lib/python3.9/site-packages/xgboost/core.py", line 620, in inner_f
>     return func(**kwargs)
>   File "/home/lwk/anaconda3/lib/python3.9/site-packages/xgboost/training.py", line 189, in train
>     bst = cb_container.after_training(bst)
>   File "/home/lwk/anaconda3/lib/python3.9/site-packages/xgboost/callback.py", line 159, in after_training
>     model = c.after_training(model=model)
>   File "/home/lwk/anaconda3/lib/python3.9/site-packages/xgboost/callback.py", line 439, in after_training
>     model = model[: int(model.attr("best_iteration")) + 1]
> TypeError: int() argument must be a string, a bytes-like object or a number, not 'NoneType'

each time when `i `goes to 2,  this error comes out. 
dtrain and dval are always the same.
Please advise. Thanks.

**Comment by yananchen1989** [comment]
solution: move the es into the loop, which is created at each iteration.
