### ISSUE TITLE
Failed on NGC due to TrackerConf() interface updated.

### ISSUE THREAD

**Issue by NvTimLiu** [dmlc/xgboost#9145]
Run XGBoost train with parameter `-rabit_tracker_host=127.0.0.1` (this parameter is a must, otherwise train will failed on similare issue : [OSError: [Errno 99] Cannot assign requested address](https://github.com/dmlc/xgboost/issues/9118)) against latest DMLC 2.0.0-SNAPSHOTjars built from mlc/xgboost master branch, got below failure log:

DMLC XGBoost version : *https://github.com/dmlc/xgboost/blob/master/jvm-packages/pom.xml#L9*

As the latest XGBoost 2.0.0-SNAPSHOT updated its TrackerConf interface, which has compatible problem,compared to v1.7.0+

https://github.com/dmlc/xgboost/blob/release_1.7.0/jvm-packages/xgboost4j-spark/src/main/scala/ml/dmlc/xgboost4j/scala/spark/XGBoost.scala#L61

https://github.com/dmlc/xgboost/blob/master/jvm-packages/xgboost4j-spark/src/main/scala/ml/dmlc/xgboost4j/scala/spark/XGBoost.scala#L55

```
INFO BlockManagerMaster: BlockManagerMaster stopped
INFO OutputCommitCoordinator$OutputCommitCoordinatorEndpoint: OutputCommitCoordinator stopped!
INFO SparkContext: Successfully stopped SparkContext
08:12:49  Exception in thread "main" java.lang.NoSuchMethodError: ml.dmlc.xgboost4j.scala.spark.TrackerConf$.apply$default$4()Ljava/lang/String;
08:12:49  	at com.nvidia.spark.examples.utility.XGBoostArgs.xgboostParams(XGBoostArgs.scala:205)
08:12:49  	at com.nvidia.spark.examples.agaricus.Main$.main(Main.scala:67)
08:12:49  	at com.nvidia.spark.examples.agaricus.Main.main(Main.scala)
08:12:49  	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
08:12:49  	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
08:12:49  	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
08:12:49  	at java.lang.reflect.Method.invoke(Method.java:498)
08:12:49  	at org.apache.spark.deploy.JavaMainApplication.start(SparkApplication.scala:52)
08:12:49  	at org.apache.spark.deploy.SparkSubmit.org$apache$spark$deploy$SparkSubmit$$runMain(SparkSubmit.scala:951)
08:12:49  	at org.apache.spark.deploy.SparkSubmit.doRunMain$1(SparkSubmit.scala:180)
08:12:49  	at org.apache.spark.deploy.SparkSubmit.submit(SparkSubmit.scala:203)
08:12:49  	at org.apache.spark.deploy.SparkSubmit.doSubmit(SparkSubmit.scala:90)
08:12:49  	at org.apache.spark.deploy.SparkSubmit$$anon$2.doSubmit(SparkSubmit.scala:1039)
08:12:49  	at org.apache.spark.deploy.SparkSubmit$.main(SparkSubmit.scala:1048)
08:12:49  	at org.apache.spark.deploy.SparkSubmit.main(SparkSubmit.scala)
INFO ShutdownHookManager: Shutdown hook called
INFO ShutdownHookManager: Deleting directory /raid/tmp/spark-337a5ed1-cc71-4a14-a98f-e6e894a450f6
INFO ShutdownHookManager: Deleting directory /tmp/spark-412265d5-0813-4dd6-8918-f0a0ba367a9a
INFO MetricsSystemImpl: Stopping s3a-file-system metrics system...
INFO MetricsSystemImpl: s3a-file-system metrics system stopped.
INFO MetricsSystemImpl: s3a-file-system metrics system shutdown complete.
```

**Comment by NvTimLiu** [comment]
@wbo4958

**Comment by wbo4958** [comment]
@NvTimLiu, Yes, recently xgboost has a breaking change that has removed the scala tracker, so we don't need to specify the "python" when using tracker_conf. I have fixed it in the spark-rapids-examples https://github.com/NVIDIA/spark-rapids-ml/pull/263

**Comment by wbo4958** [comment]
@NvTimLiu could you help to close this issue?
