### ISSUE TITLE
[jvm-packages] xgboost training failed with a rabit error

### ISSUE THREAD

**Issue by nvliyuan** [dmlc/xgboost#9374]
We are following the guide [doc](https://github.com/NVIDIA/spark-rapids/blob/branch-23.08/docs/get-started/getting-started-gcp.md#create-a-dataproc-cluster-using-t4s) to run a mortgage training demo. The application works well if we setup less than 5 executors, but if we setup 6~8 executors, it will fail with below error:
```
Tracker started, with env={DMLC_NUM_SERVER=0, DMLC_TRACKER_URI=10.128.0.168, DMLC_TRACKER_PORT=42795, DMLC_NUM_WORKER=8}
23/07/10 09:07:06 INFO ml.dmlc.xgboost4j.java.RabitTracker$TrackerProcessLogger: 2023-07-10 09:07:06,892 INFO start listen on 10.128.0.168:42795
23/07/10 09:07:11 INFO ml.dmlc.xgboost4j.java.RabitTracker$TrackerProcessLogger: 2023-07-10 09:07:11,808 DEBUG Received start signal from 10.128.0.134; assign rank 0
23/07/10 09:07:11 INFO ml.dmlc.xgboost4j.java.RabitTracker$TrackerProcessLogger: 2023-07-10 09:07:11,809 DEBUG Received start signal from 10.128.0.134; assign rank 1
23/07/10 09:07:11 INFO ml.dmlc.xgboost4j.java.RabitTracker$TrackerProcessLogger: 2023-07-10 09:07:11,810 DEBUG Received start signal from 10.128.0.135; assign rank 2
23/07/10 09:07:11 INFO ml.dmlc.xgboost4j.java.RabitTracker$TrackerProcessLogger: 2023-07-10 09:07:11,811 DEBUG Received start signal from 10.128.0.137; assign rank 3
23/07/10 09:07:11 INFO ml.dmlc.xgboost4j.java.RabitTracker$TrackerProcessLogger: 2023-07-10 09:07:11,812 DEBUG Received start signal from 10.128.0.137; assign rank 4
23/07/10 09:07:11 INFO ml.dmlc.xgboost4j.java.RabitTracker$TrackerProcessLogger: 2023-07-10 09:07:11,813 DEBUG Received start signal from 10.128.0.167; assign rank 5
23/07/10 09:07:11 INFO ml.dmlc.xgboost4j.java.RabitTracker$TrackerProcessLogger: 2023-07-10 09:07:11,813 DEBUG Received start signal from 10.128.0.176; assign rank 6
23/07/10 09:07:11 INFO ml.dmlc.xgboost4j.java.RabitTracker$TrackerProcessLogger: 2023-07-10 09:07:11,815 DEBUG Received start signal from 10.128.0.176; assign rank 7
23/07/10 09:07:11 INFO ml.dmlc.xgboost4j.java.RabitTracker$TrackerProcessLogger: 2023-07-10 09:07:11,815 INFO @tracker All of 8 nodes getting started
23/07/10 09:07:16 INFO ml.dmlc.xgboost4j.java.RabitTracker$TrackerProcessLogger: 2023-07-10 09:07:16,508 DEBUG Received shutdown signal from 5
23/07/10 09:07:16 INFO ml.dmlc.xgboost4j.java.RabitTracker$TrackerProcessLogger: 2023-07-10 09:07:16,508 DEBUG Received shutdown signal from 2
23/07/10 09:07:16 WARN org.apache.spark.scheduler.TaskSetManager: Lost task 0.0 in stage 7.0 (TID 91) (liyuan-ryan-img2-0-ubuntu-v2306-xgboost-issues-w-4.c.rapids-spark.internal executor 4): ml.dmlc.xgboost4j.java.XGBoostError: [09:07:16] /workspace/rabit/include/rabit/internal/utils.h:86: Allreduce failed
	at ml.dmlc.xgboost4j.java.XGBoostJNI.checkCall(XGBoostJNI.java:48)
	at ml.dmlc.xgboost4j.java.DeviceQuantileDMatrix.<init>(DeviceQuantileDMatrix.java:24)
	at ml.dmlc.xgboost4j.scala.DeviceQuantileDMatrix.<init>(DeviceQuantileDMatrix.scala:36)
	at ml.dmlc.xgboost4j.scala.rapids.spark.GpuPreXGBoost$.buildDMatrix(GpuPreXGBoost.scala:549)
	at ml.dmlc.xgboost4j.scala.rapids.spark.GpuPreXGBoost$.$anonfun$buildWatches$1(GpuPreXGBoost.scala:504)
	at ml.dmlc.xgboost4j.scala.rapids.spark.GpuUtils$.time(GpuUtils.scala:149)
	at ml.dmlc.xgboost4j.scala.rapids.spark.GpuPreXGBoost$.buildWatches(GpuPreXGBoost.scala:504)
	at ml.dmlc.xgboost4j.scala.rapids.spark.GpuPreXGBoost$.$anonfun$buildRDDWatches$4(GpuPreXGBoost.scala:481)
	at ml.dmlc.xgboost4j.scala.spark.XGBoost$.buildWatchesAndCheck(XGBoost.scala:277)
	at ml.dmlc.xgboost4j.scala.spark.XGBoost$.buildDistributedBooster(XGBoost.scala:308)
	at ml.dmlc.xgboost4j.scala.spark.XGBoost$.$anonfun$trainDistributed$3(XGBoost.scala:409)
	at scala.Option.map(Option.scala:230)
	at ml.dmlc.xgboost4j.scala.spark.XGBoost$.$anonfun$trainDistributed$2(XGBoost.scala:408)
	at org.apache.spark.rdd.RDDBarrier.$anonfun$mapPartitions$2(RDDBarrier.scala:51)
	at org.apache.spark.rdd.RDDBarrier.$anonfun$mapPartitions$2$adapted(RDDBarrier.scala:51)
	at org.apache.spark.rdd.MapPartitionsRDD.compute(MapPartitionsRDD.scala:52)
	at org.apache.spark.rdd.RDD.computeOrReadCheckpoint(RDD.scala:373)
	at org.apache.spark.rdd.RDD.iterator(RDD.scala:337)
	at org.apache.spark.scheduler.ResultTask.runTask(ResultTask.scala:90)
	at org.apache.spark.scheduler.Task.run(Task.scala:131)
	at org.apache.spark.executor.Executor$TaskRunner.$anonfun$run$3(Executor.scala:505)
	at org.apache.spark.util.Utils$.tryWithSafeFinally(Utils.scala:1439)
	at org.apache.spark.executor.Executor$TaskRunner.run(Executor.scala:508)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:750)

23/07/10 09:07:16 ERROR XGBoostSpark: the job was aborted due to
org.apache.spark.SparkException: Job aborted due to stage failure: Could not recover from a failed barrier ResultStage. Most recent failure reason: Stage failed because barrier task ResultTask(7, 0) finished unsuccessfully.
ml.dmlc.xgboost4j.java.XGBoostError: [09:07:16] /workspace/rabit/include/rabit/internal/utils.h:86: Allreduce failed
	at ml.dmlc.xgboost4j.java.XGBoostJNI.checkCall(XGBoostJNI.java:48)
	at ml.dmlc.xgboost4j.java.DeviceQuantileDMatrix.<init>(DeviceQuantileDMatrix.java:24)
	at ml.dmlc.xgboost4j.scala.DeviceQuantileDMatrix.<init>(DeviceQuantileDMatrix.scala:36)
	at ml.dmlc.xgboost4j.scala.rapids.spark.GpuPreXGBoost$.buildDMatrix(GpuPreXGBoost.scala:549)
	at ml.dmlc.xgboost4j.scala.rapids.spark.GpuPreXGBoost$.$anonfun$buildWatches$1(GpuPreXGBoost.scala:504)
	at ml.dmlc.xgboost4j.scala.rapids.spark.GpuUtils$.time(GpuUtils.scala:149)
	at ml.dmlc.xgboost4j.scala.rapids.spark.GpuPreXGBoost$.buildWatches(GpuPreXGBoost.scala:504)
	at ml.dmlc.xgboost4j.scala.rapids.spark.GpuPreXGBoost$.$anonfun$buildRDDWatches$4(GpuPreXGBoost.scala:481)
	at ml.dmlc.xgboost4j.scala.spark.XGBoost$.buildWatchesAndCheck(XGBoost.scala:277)
	at ml.dmlc.xgboost4j.scala.spark.XGBoost$.buildDistributedBooster(XGBoost.scala:308)
	at ml.dmlc.xgboost4j.scala.spark.XGBoost$.$anonfun$trainDistributed$3(XGBoost.scala:409)
	at scala.Option.map(Option.scala:230)
	at ml.dmlc.xgboost4j.scala.spark.XGBoost$.$anonfun$trainDistributed$2(XGBoost.scala:408)
	at org.apache.spark.rdd.RDDBarrier.$anonfun$mapPartitions$2(RDDBarrier.scala:51)
	at org.apache.spark.rdd.RDDBarrier.$anonfun$mapPartitions$2$adapted(RDDBarrier.scala:51)
	at org.apache.spark.rdd.MapPartitionsRDD.compute(MapPartitionsRDD.scala:52)
	at org.apache.spark.rdd.RDD.computeOrReadCheckpoint(RDD.scala:373)
	at org.apache.spark.rdd.RDD.iterator(RDD.scala:337)
	at org.apache.spark.scheduler.ResultTask.runTask(ResultTask.scala:90)
	at org.apache.spark.scheduler.Task.run(Task.scala:131)
	at org.apache.spark.executor.Executor$TaskRunner.$anonfun$run$3(Executor.scala:505)
	at org.apache.spark.util.Utils$.tryWithSafeFinally(Utils.scala:1439)
	at org.apache.spark.executor.Executor$TaskRunner.run(Executor.scala:508)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:750)

	at org.apache.spark.scheduler.DAGScheduler.failJobAndIndependentStages(DAGScheduler.scala:2304)
	at org.apache.spark.scheduler.DAGScheduler.$anonfun$abortStage$2(DAGScheduler.scala:2253)
	at org.apache.spark.scheduler.DAGScheduler.$anonfun$abortStage$2$adapted(DAGScheduler.scala:2252)
	at scala.collection.mutable.ResizableArray.foreach(ResizableArray.scala:62)
	at scala.collection.mutable.ResizableArray.foreach$(ResizableArray.scala:55)
	at scala.collection.mutable.ArrayBuffer.foreach(ArrayBuffer.scala:49)
	at org.apache.spark.scheduler.DAGScheduler.abortStage(DAGScheduler.scala:2252)
	at org.apache.spark.scheduler.DAGScheduler.handleTaskCompletion(DAGScheduler.scala:2013)
	at org.apache.spark.scheduler.DAGSchedulerEventProcessLoop.doOnReceive(DAGScheduler.scala:2488)
	at org.apache.spark.scheduler.DAGSchedulerEventProcessLoop.onReceive(DAGScheduler.scala:2433)
	at org.apache.spark.scheduler.DAGSchedulerEventProcessLoop.onReceive(DAGScheduler.scala:2422)
	at org.apache.spark.util.EventLoop$$anon$1.run(EventLoop.scala:49)
	at org.apache.spark.scheduler.DAGScheduler.runJob(DAGScheduler.scala:902)
	at org.apache.spark.SparkContext.runJob(SparkContext.scala:2204)
	at org.apache.spark.SparkContext.runJob(SparkContext.scala:2225)
	at org.apache.spark.SparkContext.runJob(SparkContext.scala:2244)
	at org.apache.spark.SparkContext.runJob(SparkContext.scala:2269)
	at org.apache.spark.rdd.RDD.$anonfun$collect$1(RDD.scala:1030)
	at org.apache.spark.rdd.RDDOperationScope$.withScope(RDDOperationScope.scala:151)
	at org.apache.spark.rdd.RDDOperationScope$.withScope(RDDOperationScope.scala:112)
	at org.apache.spark.rdd.RDD.withScope(RDD.scala:414)
	at org.apache.spark.rdd.RDD.collect(RDD.scala:1029)
	at ml.dmlc.xgboost4j.scala.spark.XGBoost$.trainDistributed(XGBoost.scala:414)
	at ml.dmlc.xgboost4j.scala.spark.XGBoostClassifier.train(XGBoostClassifier.scala:202)
	at ml.dmlc.xgboost4j.scala.spark.XGBoostClassifier.train(XGBoostClassifier.scala:34)
	at org.apache.spark.ml.Predictor.fit(Predictor.scala:151)
	at com.nvidia.spark.examples.mortgage.Main$.$anonfun$main$4(Main.scala:67)
	at com.nvidia.spark.examples.utility.Benchmark.time(Benchmark.scala:29)
	at com.nvidia.spark.examples.mortgage.Main$.main(Main.scala:67)
	at com.nvidia.spark.examples.mortgage.Main.main(Main.scala)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.apache.spark.deploy.JavaMainApplication.start(SparkApplication.scala:52)
	at org.apache.spark.deploy.SparkSubmit.org$apache$spark$deploy$SparkSubmit$$runMain(SparkSubmit.scala:966)
	at org.apache.spark.deploy.SparkSubmit.doRunMain$1(SparkSubmit.scala:180)
	at org.apache.spark.deploy.SparkSubmit.submit(SparkSubmit.scala:203)
	at org.apache.spark.deploy.SparkSubmit.doSubmit(SparkSubmit.scala:90)
	at org.apache.spark.deploy.SparkSubmit$$anon$2.doSubmit(SparkSubmit.scala:1054)
	at org.apache.spark.deploy.SparkSubmit$.main(SparkSubmit.scala:1063)
	at org.apache.spark.deploy.SparkSubmit.main(SparkSubmit.scala)
23/07/10 09:07:16 ERROR ml.dmlc.xgboost4j.java.RabitTracker$TrackerProcessLogger: Tracker Process ends with exit code 143
23/07/10 09:07:16 INFO org.sparkproject.jetty.server.AbstractConnector: Stopped Spark@cfbc8e8{HTTP/1.1, (http/1.1)}{0.0.0.0:0}
Exception in thread "main" org.apache.spark.SparkException: Job aborted due to stage failure: Could not recover from a failed barrier ResultStage. Most recent failure reason: Stage failed because barrier task ResultTask(7, 0) finished unsuccessfully.
ml.dmlc.xgboost4j.java.XGBoostError: [09:07:16] /workspace/rabit/include/rabit/internal/utils.h:86: Allreduce failed
	at ml.dmlc.xgboost4j.java.XGBoostJNI.checkCall(XGBoostJNI.java:48)
	at ml.dmlc.xgboost4j.java.DeviceQuantileDMatrix.<init>(DeviceQuantileDMatrix.java:24)
	at ml.dmlc.xgboost4j.scala.DeviceQuantileDMatrix.<init>(DeviceQuantileDMatrix.scala:36)
	at ml.dmlc.xgboost4j.scala.rapids.spark.GpuPreXGBoost$.buildDMatrix(GpuPreXGBoost.scala:549)
	at ml.dmlc.xgboost4j.scala.rapids.spark.GpuPreXGBoost$.$anonfun$buildWatches$1(GpuPreXGBoost.scala:504)
	at ml.dmlc.xgboost4j.scala.rapids.spark.GpuUtils$.time(GpuUtils.scala:149)
	at ml.dmlc.xgboost4j.scala.rapids.spark.GpuPreXGBoost$.buildWatches(GpuPreXGBoost.scala:504)
	at ml.dmlc.xgboost4j.scala.rapids.spark.GpuPreXGBoost$.$anonfun$buildRDDWatches$4(GpuPreXGBoost.scala:481)
	at ml.dmlc.xgboost4j.scala.spark.XGBoost$.buildWatchesAndCheck(XGBoost.scala:277)
	at ml.dmlc.xgboost4j.scala.spark.XGBoost$.buildDistributedBooster(XGBoost.scala:308)
	at ml.dmlc.xgboost4j.scala.spark.XGBoost$.$anonfun$trainDistributed$3(XGBoost.scala:409)
	at scala.Option.map(Option.scala:230)
	at ml.dmlc.xgboost4j.scala.spark.XGBoost$.$anonfun$trainDistributed$2(XGBoost.scala:408)
	at org.apache.spark.rdd.RDDBarrier.$anonfun$mapPartitions$2(RDDBarrier.scala:51)
	at org.apache.spark.rdd.RDDBarrier.$anonfun$mapPartitions$2$adapted(RDDBarrier.scala:51)
	at org.apache.spark.rdd.MapPartitionsRDD.compute(MapPartitionsRDD.scala:52)
	at org.apache.spark.rdd.RDD.computeOrReadCheckpoint(RDD.scala:373)
	at org.apache.spark.rdd.RDD.iterator(RDD.scala:337)
	at org.apache.spark.scheduler.ResultTask.runTask(ResultTask.scala:90)
	at org.apache.spark.scheduler.Task.run(Task.scala:131)
	at org.apache.spark.executor.Executor$TaskRunner.$anonfun$run$3(Executor.scala:505)
	at org.apache.spark.util.Utils$.tryWithSafeFinally(Utils.scala:1439)
	at org.apache.spark.executor.Executor$TaskRunner.run(Executor.scala:508)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:750)

	at org.apache.spark.scheduler.DAGScheduler.failJobAndIndependentStages(DAGScheduler.scala:2304)
	at org.apache.spark.scheduler.DAGScheduler.$anonfun$abortStage$2(DAGScheduler.scala:2253)
	at org.apache.spark.scheduler.DAGScheduler.$anonfun$abortStage$2$adapted(DAGScheduler.scala:2252)
	at scala.collection.mutable.ResizableArray.foreach(ResizableArray.scala:62)
	at scala.collection.mutable.ResizableArray.foreach$(ResizableArray.scala:55)
	at scala.collection.mutable.ArrayBuffer.foreach(ArrayBuffer.scala:49)
	at org.apache.spark.scheduler.DAGScheduler.abortStage(DAGScheduler.scala:2252)
	at org.apache.spark.scheduler.DAGScheduler.handleTaskCompletion(DAGScheduler.scala:2013)
	at org.apache.spark.scheduler.DAGSchedulerEventProcessLoop.doOnReceive(DAGScheduler.scala:2488)
	at org.apache.spark.scheduler.DAGSchedulerEventProcessLoop.onReceive(DAGScheduler.scala:2433)
	at org.apache.spark.scheduler.DAGSchedulerEventProcessLoop.onReceive(DAGScheduler.scala:2422)
	at org.apache.spark.util.EventLoop$$anon$1.run(EventLoop.scala:49)
	at org.apache.spark.scheduler.DAGScheduler.runJob(DAGScheduler.scala:902)
	at org.apache.spark.SparkContext.runJob(SparkContext.scala:2204)
	at org.apache.spark.SparkContext.runJob(SparkContext.scala:2225)
	at org.apache.spark.SparkContext.runJob(SparkContext.scala:2244)
	at org.apache.spark.SparkContext.runJob(SparkContext.scala:2269)
	at org.apache.spark.rdd.RDD.$anonfun$collect$1(RDD.scala:1030)
	at org.apache.spark.rdd.RDDOperationScope$.withScope(RDDOperationScope.scala:151)
	at org.apache.spark.rdd.RDDOperationScope$.withScope(RDDOperationScope.scala:112)
	at org.apache.spark.rdd.RDD.withScope(RDD.scala:414)
	at org.apache.spark.rdd.RDD.collect(RDD.scala:1029)
	at ml.dmlc.xgboost4j.scala.spark.XGBoost$.trainDistributed(XGBoost.scala:414)
	at ml.dmlc.xgboost4j.scala.spark.XGBoostClassifier.train(XGBoostClassifier.scala:202)
	at ml.dmlc.xgboost4j.scala.spark.XGBoostClassifier.train(XGBoostClassifier.scala:34)
	at org.apache.spark.ml.Predictor.fit(Predictor.scala:151)
	at com.nvidia.spark.examples.mortgage.Main$.$anonfun$main$4(Main.scala:67)
	at com.nvidia.spark.examples.utility.Benchmark.time(Benchmark.scala:29)
	at com.nvidia.spark.examples.mortgage.Main$.main(Main.scala:67)
	at com.nvidia.spark.examples.mortgage.Main.main(Main.scala)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.apache.spark.deploy.JavaMainApplication.start(SparkApplication.scala:52)
	at org.apache.spark.deploy.SparkSubmit.org$apache$spark$deploy$SparkSubmit$$runMain(SparkSubmit.scala:966)
	at org.apache.spark.deploy.SparkSubmit.doRunMain$1(SparkSubmit.scala:180)
	at org.apache.spark.deploy.SparkSubmit.submit(SparkSubmit.scala:203)
```
Steps to reproduce:
1: create a cluster on dataproc
```
gcloud dataproc clusters create $CLUSTER_NAME  \
    --region $GCS_REGION \
    --image-version=2.0-ubuntu18 \
    --master-machine-type n1-standard-4 \
    --num-workers 4 \
    --subnet default \
    --worker-machine-type n1-standard-8 \
    --initialization-actions gs://xxxx/gcp-init/v2306/spark-rapids.sh \
    --metadata rapids-runtime=SPARK \
    --worker-accelerator type=nvidia-tesla-t4,count=2 \
    --optional-components=JUPYTER,ZEPPELIN \
    --worker-local-ssd-interface=NVME \
    --num-worker-local-ssds 2 \
    --bucket $GCS_BUCKET \
    --enable-component-gateway \
    --max-idle 8h
```
2. submit the job to the cluster:
```
gcloud dataproc jobs submit spark --cluster=liyuan-ryan-img2-0-ubuntu-v2306-xgboost-issues --region=us-central1 --class=com.nvidia.spark.examples.mortgage.Main --jars=gs://xxx/sample_xgboost_apps-0.2.3-jar-with-dependencies.jar --properties=spark.executor.instances=8,spark.executor.cores=4,spark.executor.memory=8G,spark.executor.resource.gpu.amount=1,spark.task.resource.gpu.amount=1,spark.rapids.sql.batchSizeBytes=512M,spark.rapids.sql.reader.batchSizeBytes=768M,spark.rapids.sql.variableFloatAgg.enabled=true,spark.locality.wait=0,spark.rapids.memory.gpu.pooling.enabled=false,spark.rapids.memory.gpu.pooling.enabled=false,spark.dynamicAllocation.enabled=false -- -dataPath=train::gs://xxx/mortgage_data/etl-v01/train -dataPath=trans::gs://xxx/mortgage_data/etl-v01/eval -format=parquet -numWorkers=8 -treeMethod=gpu_hist -numRound=100 -maxDepth=8
```
upload the yarn logs to the attachment
[yarnlogs-xgb-issues.tar.gz](https://github.com/dmlc/xgboost/files/12000239/yarnlogs-xgb-issues.tar.gz)

**Comment by nvliyuan** [comment]
This issue is specific to xgboost171, I test 176 five times and did not hit this issue, close this issue
