### ISSUE TITLE
Quantile Regression with multiple alphas fails on transform using SparkXGBRegressor

### ISSUE THREAD

**Issue by maeschbacher** [dmlc/xgboost#9537]
xgboost==2.0.0rc1

Quantile Regression with multiple alphas fails on transform using SparkXGBRegressor. It appears to be a Pandas issue, the code expects to unpack a 1-dimensional array into a Pandas column but with multiple alphas specified in the Regressor a 2-dimensional array is returned.

Stack trace below:
```
PythonException: 
  An exception was thrown from the Python worker. Please see the stack trace below.
'ValueError: Data must be 1-dimensional'. Full traceback below:
Traceback (most recent call last):
  File "/local_disk0/.ephemeral_nfs/envs/pythonEnv-1d129fe0-ac77-4fc6-aa6c-cf76c955a619/lib/python3.10/site-packages/xgboost/spark/core.py", line 1178, in predict_udf
    data[pred.prediction] = pd.Series(preds)
  File "/databricks/python/lib/python3.10/site-packages/pandas/core/series.py", line 451, in __init__
    data = sanitize_array(data, index, dtype, copy)
  File "/databricks/python/lib/python3.10/site-packages/pandas/core/construction.py", line 601, in sanitize_array
    subarr = _sanitize_ndim(subarr, data, dtype, index, allow_2d=allow_2d)
  File "/databricks/python/lib/python3.10/site-packages/pandas/core/construction.py", line 652, in _sanitize_ndim
    raise ValueError("Data must be 1-dimensional")
ValueError: Data must be 1-dimensional
```

Code to reproduce the issue:
```
from xgboost.spark import SparkXGBRegressor
from pyspark.sql.types import *


train_data = [([1.0, 2.0, 3.0], 6.0), ([2.0, 2.0, 3.0], 7.0), ([1.0, 2.0, 5.0], 8.0)]
train_schema = StructType([
    StructField("features", ArrayType(FloatType()), False),
    StructField("label", FloatType(), False)
])

pred_data = [([1.0, 3.0, 3.0], 7.0), ([0.0, 2.0, 3.0], 5.0)]
pred_schema = StructType([
    StructField("features", ArrayType(FloatType()), False),
    StructField("label", FloatType(), False)
])

train_df = spark.createDataFrame(data=train_data, schema=train_schema)
pred_df = spark.createDataFrame(data=pred_data, schema=pred_schema)

alpha = np.array([0.05, 0.5, 0.95])

xgb_regressor = SparkXGBRegressor(
    objective="reg:quantileerror",
    quantile_alpha=alpha,
    features_col="features",
    label_col="label",
)

xgb_regressor_model = xgb_regressor.fit(train_df)

preds = xgb_regressor_model.transform(pred_df)

preds.collect()
```

**Comment by trivialfis** [comment]
The spark interface doesn't support multi-target yet (multi-quantile is just multi-target).

**Comment by SaiBeathanabhotla** [comment]
Hi, I am using just one value in alpha (for example, alpha = np.array([0.5])) to train a model, however, I am not able to save the model as it says "Object of type ndarray is not JSON serializable" and I think it is mainly because of the alpha variable which is a numpy array. Anyway you could suggest to save the model and load it back? Please let me know. Thanks in advance!

**Comment by trivialfis** [comment]
@SaiBeathanabhotla Have you tried using the floating instead of a np array?
