### ISSUE TITLE
cannot find and load libxgboost4j3832117424674659500.dylib

### ISSUE THREAD

**Issue by dycasxe101** [dmlc/xgboost#9566]
Hai 
I am newbie with xgboost.
I want to load xgboost model on my code 
Use JDK 8, on my m1 apple sillicon, here the error

	java.lang.UnsatisfiedLinkError: Can't load library: /var/folders/wl/gxt831dd0bn2fr1jjsprswwc0000gn/T/libxgboost4j3832117424674659500.dylib
    at java.lang.ClassLoader.loadLibrary(ClassLoader.java:1823)
    at java.lang.Runtime.load0(Runtime.java:782)
	at java.lang.System.load(System.java:1098)
	at ml.dmlc.xgboost4j.java.NativeLibLoader.loadLibraryFromJar(NativeLibLoader.java:67)
	at ml.dmlc.xgboost4j.java.NativeLibLoader.smartLoad(NativeLibLoader.java:153)
	at ml.dmlc.xgboost4j.java.NativeLibLoader.initXGBoost(NativeLibLoader.java:41)
	at ml.dmlc.xgboost4j.java.Booster.<clinit>(Booster.java:41)
	at ml.dmlc.xgboost4j.java.XGBoost.loadModel(XGBoost.java:57)

**Comment by trivialfis** [comment]
Closing in favor of https://github.com/dmlc/xgboost/issues/9570 .
