### ISSUE TITLE
[jvm-packages] xgboost 2.0 fails to run with spark

### ISSUE THREAD

**Issue by dtera** [dmlc/xgboost#9603]
```scala
    import java.io.File
    import scala.collection.mutable
    import ml.dmlc.xgboost4j.scala.{DMatrix, XGBoost}

    val params = new mutable.HashMap[String, Any]()
    params += "booster" -> "gbtree"
    params += "eta" -> 1.0
    params += "gamma" -> 1.0
    params += "max_depth" -> 8
    params += "seed" -> 0
    params += "min_child_weight" -> 0
    params += "missing" -> 0f
    params += "verbosity" -> 2
    params += "objective" -> "binary:logistic"
    params += "tree_method" -> "hist"
    params += "eval_metric" -> "auc"
    params += "dump_format" -> "json"

    val trainMax = new DMatrix("../demo/data/a9a.train?format=libsvm")
    val testMax = new DMatrix("../demo/data/a9a.test?format=libsvm")
    val watches = new mutable.HashMap[String, DMatrix]
    watches += "train" -> trainMax
    watches += "test" -> testMax

    val round = 3
    // train a model
    val booster = XGBoost.train(trainMax, params.toMap, round, watches.toMap)
    // predict
    val predicts = booster.predict(testMax)
    // save model to model path
    val file = new File("./model/a9a")
    if (!file.exists()) {
      file.mkdirs()
    }
    booster.saveModel(file.getAbsolutePath + "/xgb.model.json")
    // save dmatrix into binary buffer
    testMax.saveBinary(file.getAbsolutePath + "/dtest.buffer")
```
On MacOS M1, Win11 or Centos 7(8), the code above run successfully, however, it doesn't work with Spark.
```scala
    import ml.dmlc.xgboost4j.scala.spark.XGBoostClassifier
    import org.apache.spark.SparkConf
    import org.apache.spark.ml.evaluation.BinaryClassificationEvaluator

    val trainInput = spark.read.format("libsvm").load("../demo/data/a9a.train")
    val testInput = spark.read.format("libsvm").load("../demo/data/a9a.test")

    params += "num_workers" -> 2
    params += "timeout_request_workers" -> 60000L
    params += "eval_sets" -> Map("test" -> testInput)

    val xgbClassifier = new XGBoostClassifier(params.toMap).setMissing(0.0f)
    val xgbModel = xgbClassifier.fit(trainInput)
    val testAUC = evaluator.evaluate(xgbModel.transform(testInput))
    println(s"Test AUC: $testAUC")
```
The error log when running the code above is as follows:
```
ml.dmlc.xgboost4j.java.XGBoostError: [15:05:31] /Users/zhaohuiqiang/CLionProjects/xgboost/rabit/src/allreduce_base.cc:127: 
- Failed to connect to the tracker.
- Failed to recieve the verification number.
Stack trace:
  [bt] (0) 1   libxgboost4j2120825777935734343.dyl 0x00000002861fd650 dmlc::LogMessageFatal::~LogMessageFatal() + 124
  [bt] (1) 2   libxgboost4j2120825777935734343.dyl 0x00000002864a93a0 rabit::engine::AllreduceBase::Init(int, char**) + 1092
  [bt] (2) 3   libxgboost4j2120825777935734343.dyl 0x000000028626dffc xgboost::collective::RabitCommunicator::Create(xgboost::Json const&) + 1484
  [bt] (3) 4   libxgboost4j2120825777935734343.dyl 0x000000028626d584 xgboost::collective::Communicator::Init(xgboost::Json const&) + 184
  [bt] (4) 5   libxgboost4j2120825777935734343.dyl 0x0000000286224fcc XGCommunicatorInit + 60
  [bt] (5) 6   libxgboost4j2120825777935734343.dyl 0x00000002861fbdfc Java_ml_dmlc_xgboost4j_java_XGBoostJNI_CommunicatorInit + 892
  [bt] (6) 7   ???                                 0x0000000105d99168 0x0 + 4393111912
  [bt] (7) 8   ???                                 0x0000000105d8bc60 0x0 + 4393057376
  [bt] (8) 9   ???                                 0x0000000105d8c1d8 0x0 + 4393058776


	at ml.dmlc.xgboost4j.java.Communicator.checkCall(Communicator.java:55)
	at ml.dmlc.xgboost4j.java.Communicator.init(Communicator.java:82)
	at ml.dmlc.xgboost4j.scala.spark.XGBoost$.buildDistributedBooster(XGBoost.scala:309)
	at ml.dmlc.xgboost4j.scala.spark.XGBoost$.$anonfun$trainDistributed$3(XGBoost.scala:411)
	at scala.Option.map(Option.scala:230)
	at ml.dmlc.xgboost4j.scala.spark.XGBoost$.$anonfun$trainDistributed$2(XGBoost.scala:410)
	at org.apache.spark.rdd.RDDBarrier.$anonfun$mapPartitions$2(RDDBarrier.scala:51)
	at org.apache.spark.rdd.RDDBarrier.$anonfun$mapPartitions$2$adapted(RDDBarrier.scala:51)
	at org.apache.spark.rdd.MapPartitionsRDD.compute(MapPartitionsRDD.scala:52)
	at org.apache.spark.rdd.RDD.computeOrReadCheckpoint(RDD.scala:364)
	at org.apache.spark.rdd.RDD.iterator(RDD.scala:328)
	at org.apache.spark.rdd.MapPartitionsRDD.compute(MapPartitionsRDD.scala:52)
	at org.apache.spark.rdd.RDD.computeOrReadCheckpoint(RDD.scala:364)
	at org.apache.spark.rdd.RDD.iterator(RDD.scala:328)
	at org.apache.spark.shuffle.ShuffleWriteProcessor.write(ShuffleWriteProcessor.scala:59)
	at org.apache.spark.scheduler.ShuffleMapTask.runTask(ShuffleMapTask.scala:101)
	at org.apache.spark.scheduler.ShuffleMapTask.runTask(ShuffleMapTask.scala:53)
	at org.apache.spark.TaskContext.runTaskWithListeners(TaskContext.scala:161)
	at org.apache.spark.scheduler.Task.run(Task.scala:139)
	at org.apache.spark.executor.Executor$TaskRunner.$anonfun$run$3(Executor.scala:554)
	at org.apache.spark.util.Utils$.tryWithSafeFinally(Utils.scala:1529)
	at org.apache.spark.executor.Executor$TaskRunner.run(Executor.scala:557)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:750)
23/09/22 15:05:31 ERROR XGBoostSpark: XGBooster worker 0 has failed 0 times due to 

Job aborted due to stage failure: ShuffleMapStage 7 (repartition at XGBoost.scala:419) has failed the maximum allowable number of times: 4. Most recent failure reason: Stage failed because barrier task ShuffleMapTask(7, 0) finished unsuccessfully.
ml.dmlc.xgboost4j.java.XGBoostError: [15:05:32] /Users/zhaohuiqiang/CLionProjects/xgboost/src/collective/communicator.h:202: Rank -1 is less than 0.
Stack trace:
  [bt] (0) 1   libxgboost4j2120825777935734343.dyl 0x00000002861fd650 dmlc::LogMessageFatal::~LogMessageFatal() + 124
  [bt] (1) 2   libxgboost4j2120825777935734343.dyl 0x000000028626e850 xgboost::collective::Communicator::Communicator(int, int) + 260
  [bt] (2) 3   libxgboost4j2120825777935734343.dyl 0x000000028626e078 xgboost::collective::RabitCommunicator::Create(xgboost::Json const&) + 1608
  [bt] (3) 4   libxgboost4j2120825777935734343.dyl 0x000000028626d584 xgboost::collective::Communicator::Init(xgboost::Json const&) + 184
  [bt] (4) 5   libxgboost4j2120825777935734343.dyl 0x0000000286224fcc XGCommunicatorInit + 60
  [bt] (5) 6   libxgboost4j2120825777935734343.dyl 0x00000002861fbdfc Java_ml_dmlc_xgboost4j_java_XGBoostJNI_CommunicatorInit + 892
  [bt] (6) 7   ???                                 0x0000000105d99168 0x0 + 4393111912
  [bt] (7) 8   ???                                 0x0000000105d8bc60 0x0 + 4393057376
  [bt] (8) 9   ???                                 0x0000000105d8c1d8 0x0 + 4393058776


	at ml.dmlc.xgboost4j.java.Communicator.checkCall(Communicator.java:55)
	at ml.dmlc.xgboost4j.java.Communicator.init(Communicator.java:82)
	at ml.dmlc.xgboost4j.scala.spark.XGBoost$.buildDistributedBooster(XGBoost.scala:309)
	at ml.dmlc.xgboost4j.scala.spark.XGBoost$.$anonfun$trainDistributed$3(XGBoost.scala:411)
	at scala.Option.map(Option.scala:230)
	at ml.dmlc.xgboost4j.scala.spark.XGBoost$.$anonfun$trainDistributed$2(XGBoost.scala:410)
	at org.apache.spark.rdd.RDDBarrier.$anonfun$mapPartitions$2(RDDBarrier.scala:51)
	at org.apache.spark.rdd.RDDBarrier.$anonfun$mapPartitions$2$adapted(RDDBarrier.scala:51)
	at org.apache.spark.rdd.MapPartitionsRDD.compute(MapPartitionsRDD.scala:52)
	at org.apache.spark.rdd.RDD.computeOrReadCheckpoint(RDD.scala:364)
	at org.apache.spark.rdd.RDD.iterator(RDD.scala:328)
	at org.apache.spark.rdd.MapPartitionsRDD.compute(MapPartitionsRDD.scala:52)
	at org.apache.spark.rdd.RDD.computeOrReadCheckpoint(RDD.scala:364)
	at org.apache.spark.rdd.RDD.iterator(RDD.scala:328)
	at org.apache.spark.shuffle.ShuffleWriteProcessor.write(ShuffleWriteProcessor.scala:59)
	at org.apache.spark.scheduler.ShuffleMapTask.runTask(ShuffleMapTask.scala:101)
	at org.apache.spark.scheduler.ShuffleMapTask.runTask(ShuffleMapTask.scala:53)
	at org.apache.spark.TaskContext.runTaskWithListeners(TaskContext.scala:161)
	at org.apache.spark.scheduler.Task.run(Task.scala:139)
	at org.apache.spark.executor.Executor$TaskRunner.$anonfun$run$3(Executor.scala:554)
	at org.apache.spark.util.Utils$.tryWithSafeFinally(Utils.scala:1529)
	at org.apache.spark.executor.Executor$TaskRunner.run(Executor.scala:557)
```

**Comment by trivialfis** [comment]
The worker is unable to connect with the tracker in xgboost, is there any restriction on networking like limited ports or firewall?

**Comment by dtera** [comment]
> The worker is unable to connect with the tracker in xgboost, is there any restriction on networking like limited ports or firewall?

no restriction on networking, and it works in early version.

**Comment by trivialfis** [comment]
The networking module has been reworked. Feel free to reopen if the issue persists.
