### ISSUE TITLE
XGBoostError save_raw() on mac M1

### ISSUE THREAD

**Issue by masc-it** [dmlc/xgboost#9683]
Hi,

I've installed xgboost from source using `pip install -U --no-cache xgboost --no-binary xgboost -v` and I am having weird crashes, actually, what I noticed is that each time a command issues some warning (it can be as simple as a deprecation message), the function being called crashes.

An example:
```
dump = model.get_booster().save_raw()

[17:32:17] WARNING: [/Users/runner/work/xgboost/xgboost/src/c_api/c_api.cc:1240](https://file+.vscode-resource.vscode-cdn.net/Users/runner/work/xgboost/xgboost/src/c_api/c_api.cc:1240): Saving into deprecated binary model format, please consider using `json` or `ubj`. Model format will default to JSON in XGBoost 2.2 if not specified.

XGBoostError                              Traceback (most recent call last)
Cell In[12], line 1
-> 20     dump = model.get_booster().save_raw()

...
  [bt] (6) 7   libffi.8.dylib                      0x000000010567174c ffi_call_int + 1208
  [bt] (7) 8   _ctypes.cpython-310-darwin.so       0x0000000105650c88 _ctypes_callproc + 1260
  [bt] (8) 9   _ctypes.cpython-310-darwin.so       0x000000010564af58 PyCFuncPtr_call + 1132
```
This example comes from a practical usage that currently makes the [shap](https://github.com/shap/shap) library unusable on mac m1.

Another one (this is a dummy one, where I tell to save the model in a dir, rather than a file):

```
model.save("./path_that_should_be_a_file/")

XGBoostError                              Traceback (most recent call last)
Cell In[13], line 1
----> 1 model.save_model

File ... in XGBModel.save_model(self, fname)
    834 meta_str = json.dumps(meta)
    835 self.get_booster().set_attr(scikit_learn=meta_str)
--> 836 self.get_booster().save_model(fname)
    837 self.get_booster().set_attr(scikit_learn=None)

File .. in Booster.save_model(self, fname)
   2530 if isinstance(fname, (str, os.PathLike)):  # assume file name
   2531     fname = os.fspath(os.path.expanduser(fname))
-> 2532     _check_call(_LIB.XGBoosterSaveModel(self.handle, c_str(fname)))
   2533 else:
   2534     raise TypeError("fname must be a string or os PathLike")

File [~/Library/Caches/pypoetry/virtualenvs/churn-prediction-Pm6D_DmO-py3.10/lib/python3.10/site-packages/xgboost/core.py:281](https://file+.vscode-resource.vscode-cdn.net/Users/../projects/../notebooks/train_xgboost/~/Library/Caches/pypoetry/virtualenvs/churn-prediction-Pm6D_DmO-py3.10/lib/python3.10/site-packages/xgboost/core.py:281), in _check_call(ret)
    270 """Check the return value of C API call
    271 
    272 This function will raise exception when error occurs.
   (...)
    278     return value from API calls
    279 """
...
  [bt] (6) 7   _ctypes.cpython-310-darwin.so       0x0000000105650c88 _ctypes_callproc + 1260
  [bt] (7) 8   _ctypes.cpython-310-darwin.so       0x000000010564af58 PyCFuncPtr_call + 1132
  [bt] (8) 9   python3.10                          0x0000000104d9faec _PyObject_MakeTpCall + 612
```
If I input a correct file path, the command works just fine.

Any ideas?

**Comment by trivialfis** [comment]
What happens if you install xgboost using pip from PyPI? 

cc @hcho3

**Comment by masc-it** [comment]
Already tested it, but same result:

```
dump = model.get_booster().save_raw()

UserWarning: [18:12:53] WARNING: [/Users/runner/work/xgboost/xgboost/src/c_api/c_api.cc:1240](https://file+.vscode-resource.vscode-cdn.net/Users/runner/work/xgboost/xgboost/src/c_api/c_api.cc:1240): Saving into deprecated binary model format, please consider using `json` or `ubj`. Model format will default to JSON in XGBoost 2.2 if not specified.
  warnings.warn(smsg, UserWarning)

XGBoostError                              Traceback (most recent call last)
Cell In[10], line 1
----> 1 d = model.get_booster().save_raw()#raw_format="json")

File [~/Library/Caches/pypoetry/virtualenvs/churn-prediction-Pm6D_DmO-py3.10/lib/python3.10/site-packages/xgboost/core.py:2553](https://file+.vscode-resource.vscode-cdn.net/Users/../projects/churn-prediction/notebooks/train_xgboost/~/Library/Caches/pypoetry/virtualenvs/../lib/python3.10/site-packages/xgboost/core.py:2553), in Booster.save_raw(self, raw_format)
   2551 cptr = ctypes.POINTER(ctypes.c_char)()
   2552 config = make_jcargs(format=raw_format)
-> 2553 _check_call(
   2554     _LIB.XGBoosterSaveModelToBuffer(
   2555         self.handle, config, ctypes.byref(length), ctypes.byref(cptr)
   2556     )
   2557 )
   2558 return ctypes2buffer(cptr, length.value)

File [~/Library/Caches/pypoetry/virtualenvs/../lib/python3.10/site-packages/xgboost/core.py:281](https://file+.vscode-resource.vscode-cdn.net/Users/../projects/churn-prediction/notebooks/train_xgboost/~/Library/Caches/pypoetry/virtualenvs/../lib/python3.10/site-packages/xgboost/core.py:281), in _check_call(ret)
    270 """Check the return value of C API call
    271 
    272 This function will raise exception when error occurs.
   (...)
    278     return value from API calls
    279 """
    280 if ret != 0:
--> 281     raise XGBoostError(py_str(_LIB.XGBGetLastError()))
...
  [bt] (6) 7   libffi.8.dylib                      0x00000001035a974c ffi_call_int + 1208
  [bt] (7) 8   _ctypes.cpython-310-darwin.so       0x0000000103588c88 _ctypes_callproc + 1260
  [bt] (8) 9   _ctypes.cpython-310-darwin.so       0x0000000103582f58 PyCFuncPtr_call + 1132
```

Then I tried to comment out that exception check in core.py: what happens in this particular case is that the _dump_ variable contains an empty bytearray. So something breaks during the process, but it's hidden from the final stack trace.

**Comment by trivialfis** [comment]
My initial guess is the warning call in Python is throwing exception somehow. Will try to get a Mac device from AWS tomorrow.

**Comment by hcho3** [comment]
Can you provide more details about your Mac M1 machine?

I just tried the same command on AWS's Mac instance and could not reproduce the error.

**Comment by masc-it** [comment]
Macbook Pro, M1 Pro, Ventura 13.0.1.
Python 3.10.12 via poetry. Tried the same also with a conda venv, but same result.

**Comment by hcho3** [comment]
Here's my M1 machine.

```
$ sw_vers -productVersion
13.5.2

$  system_profiler SPSoftwareDataType
Software:

    System Software Overview:

      System Version: macOS 13.5.2 (22G91)
      Kernel Version: Darwin 22.6.0
      Boot Volume: Macintosh HD
      Boot Mode: Normal
      User Name: ec2-user (ec2-user)
      Secure Virtual Memory: Enabled
      System Integrity Protection: Enabled
      Time since boot: 12 hours, 1 minute
```

**Comment by masc-it** [comment]
```
❯ sw_vers -productVersion
13.0.1
❯ system_profiler SPSoftwareDataType
Software:

    System Software Overview:

      System Version: macOS 13.0.1 (22A400)
      Kernel Version: Darwin 22.1.0
      Boot Volume: Macintosh HD
      Boot Mode: Normal
      Computer Name: ...
      User Name: ...
      Secure Virtual Memory: Enabled
      System Integrity Protection: Enabled
      Time since boot: 8 days, 23 hours, 9 minutes

❯ python --version
Python 3.10.12
```

**Comment by hcho3** [comment]
So both of us are using MacOS Ventura, with different patch versions. I don't think this should make much difference.

Unless we can reproduce the bug on our end, it will be difficult for us to fix the bug unfortunately.

**Comment by masc-it** [comment]
I am trying to purge pip cache and retry. Can you tell me which version of clang, gcc and cmake do you have? 

Mine:

```
❯ clang --version
Homebrew clang version 15.0.4
Target: arm64-apple-darwin22.1.0
Thread model: posix
InstalledDir: /opt/homebrew/opt/llvm/bin
❯ cmake --version
cmake version 3.24.3

CMake suite maintained and supported by Kitware (kitware.com/cmake).
❯ gcc --version
Apple clang version 14.0.0 (clang-1400.0.29.202)
Target: arm64-apple-darwin22.1.0
Thread model: posix
InstalledDir: /Library/Developer/CommandLineTools/usr/bin
```

**Comment by hcho3** [comment]
```
$ clang --version
Apple clang version 14.0.3 (clang-1403.0.22.14.1)
Target: arm64-apple-darwin22.6.0
Thread model: posix
InstalledDir: /Library/Developer/CommandLineTools/usr/bin

$ cmake --version
cmake version 3.27.7

CMake suite maintained and supported by Kitware (kitware.com/cmake).

$ gcc --version
Apple clang version 14.0.3 (clang-1403.0.22.14.1)
Target: arm64-apple-darwin22.6.0
Thread model: posix
InstalledDir: /Library/Developer/CommandLineTools/usr/bin
```

**Comment by masc-it** [comment]
I've tried to uninstall llvm so that clang and gcc are by apple, create an env from scratch, pip cache purge, install requirements.. same story. This is a weird one, for sure something wrong on my system. I'll try to replicate it with someone at work. 
Thank you for your time!

**Comment by trivialfis** [comment]
Since you have already gone to length to debug this and have familiarity with compiling from the source, let's try to debug the code directly. During warning log:

https://github.com/dmlc/xgboost/blob/ea9f09716bd426f235ce785d6286e0ad26350ce1/src/logging.cc#L20

calls:

https://github.com/dmlc/xgboost/blob/ea9f09716bd426f235ce785d6286e0ad26350ce1/python-package/xgboost/core.py#L156

through Python ctypes callback. See if there's anything wrong with the callback.

This is the implementation of save raw: https://github.com/dmlc/xgboost/blob/ea9f09716bd426f235ce785d6286e0ad26350ce1/src/c_api/c_api.cc#L1321 , it returns inside the `API_END` macro if there's a c++ exception, which is caught here https://github.com/dmlc/xgboost/blob/ea9f09716bd426f235ce785d6286e0ad26350ce1/src/c_api/c_api_error.h#L31 .

**Comment by masc-it** [comment]
You can easily try to reproduce that with this notebook:
[_reproduce_bug_xgboost.ipynb.zip](https://github.com/dmlc/xgboost/files/13044835/_reproduce_bug_xgboost.ipynb.zip)

**Comment by trivialfis** [comment]
I can reproduce the error, but it has full error trace with the correct message:
```
/home/jiamingy/workspace/xgboost_dev/xgboost/python-package/xgboost/core.py:160: UserWarning: [00:23:29] WARNING: /home/jiamingy/workspace/xgboost_dev/xgboost/src/c_api/c_api.cc:1273: Saving into deprecated binary model format, please consider using `json` or `ubj`. Model format will default to JSON in XGBoost 2.2 if not specified.
  warnings.warn(smsg, UserWarning)
Traceback (most recent call last):
  File "/home/jiamingy/workspace/xgboost_dev/XGBoostUtils/issues/9683/reproduce.py", line 68, in <module>
    dump = model.get_booster().save_raw()
  File "/home/jiamingy/workspace/xgboost_dev/xgboost/python-package/xgboost/core.py", line 2593, in save_raw
    _check_call(
  File "/home/jiamingy/workspace/xgboost_dev/xgboost/python-package/xgboost/core.py", line 281, in _check_call
    raise XGBoostError(py_str(_LIB.XGBGetLastError()))
xgboost.core.XGBoostError: [00:23:29] /home/jiamingy/workspace/xgboost_dev/xgboost/src/tree/tree_model.cc:899: Check failed: !HasCategoricalSplit(): Please use JSON/UBJSON for saving models with categorical splits.
Stack trace:
  [bt] (0) /home/jiamingy/workspace/xgboost_dev/xgboost/python-package/xgboost/../../lib/libxgboost.so(dmlc::LogMessageFatal::~LogMessageFatal()+0x80) [0x7f5ef7d80480]
  [bt] (1) /home/jiamingy/workspace/xgboost_dev/xgboost/python-package/xgboost/../../lib/libxgboost.so(xgboost::RegTree::Save(dmlc::Stream*) const+0x4d2) [0x7f5ef81e3f02]
...
```

emphasis on:
```
model.cc:899: Check failed: !HasCategoricalSplit(): Please use JSON/UBJSON for saving models with categorical splits.
```
You should use `json/ubjson` during `save_raw`:
``` python
dump = model.get_booster().save_raw(raw_format="json")
dump = model.get_booster().save_raw(raw_format="ubj")
```

I don't know why the message is missing in your error trace, something is wrong with logging.
