### ISSUE TITLE
XGBoost training failed with xgboost.core.XGBoostError error

### ISSUE THREAD

**Issue by nvliyuan** [dmlc/xgboost#9700]
[Mortgage demo ](https://github.com/NVIDIA/spark-rapids-examples/blob/main/examples/XGBoost-Examples/mortgage/notebooks/python/MortgageETL%2BXGBoost.ipynb) failed with below error while training with Enable GDS:
```
File "/usr/local/lib/python3.8/dist-packages/xgboost/core.py", line 281, in _check_call
    raise XGBoostError(py_str(_LIB.XGBGetLastError()))
xgboost.core.XGBoostError: [23:13:08] /workspace/rabit/include/rabit/internal/socket.h:170: Poll timeout
Stack trace:
  [bt] (0) /usr/local/lib/python3.8/dist-packages/xgboost/lib/libxgboost.so(+0x1ba0be) [0x7f1de26270be]
  [bt] (1) /usr/local/lib/python3.8/dist-packages/xgboost/lib/libxgboost.so(+0x77acec) [0x7f1de2be7cec]
  [bt] (2) /usr/local/lib/python3.8/dist-packages/xgboost/lib/libxgboost.so(+0x774572) [0x7f1de2be1572]
  [bt] (3) /usr/local/lib/python3.8/dist-packages/xgboost/lib/libxgboost.so(+0x77c33c) [0x7f1de2be933c]
  [bt] (4) /usr/local/lib/python3.8/dist-packages/xgboost/lib/libxgboost.so(+0x1b464e) [0x7f1de262164e]
  [bt] (5) /usr/local/lib/python3.8/dist-packages/xgboost/lib/libxgboost.so(+0x86ecb0) [0x7f1de2cdbcb0]
  [bt] (6) /usr/local/lib/python3.8/dist-packages/xgboost/lib/libxgboost.so(+0x3f883a) [0x7f1de286583a]
  [bt] (7) /usr/local/lib/python3.8/dist-packages/xgboost/lib/libxgboost.so(+0x3a2367) [0x7f1de280f367]
  [bt] (8) /usr/local/lib/python3.8/dist-packages/xgboost/lib/libxgboost.so(XGQuantileDMatrixCreateFromCallback+0x2b0) [0x7f1de25d2ab0]
```
Configs:
```
RAPIDS_JAR = os.getenv("RAPIDS_JAR", "/XXX/rapids-4-spark_2.12-23.08.2.jar")

driverMem = os.getenv("DRIVER_MEM", "12g")
executorMem = os.getenv("EXECUTOR_MEM", "12g")
pinnedPoolSize = os.getenv("PINNED_POOL_SIZE", "2g")
concurrentGpuTasks = os.getenv("CONCURRENT_GPU_TASKS", "2")
executorCores = int(os.getenv("EXECUTOR_CORES", "40"))
os.environ['PYSPARK_SUBMIT_ARGS']="--master spark://${MASTER_HOST}:7077 pyspark-shell"
os.environ['JAVA_HOME']='/usr/local/karthik_rapids_accelerator_apache_spark/jre1.8.0_361'

# Common spark settings
conf = SparkConf()
conf.setMaster(SPARK_MASTER_URL)
conf.setAppName("Microbenchmark on GPU")
conf.set("spark.driver.memory", driverMem)
## The tasks will run on GPU memory, so there is no need to set a high host memory
conf.set("spark.executor.memory", executorMem)
## The tasks will run on GPU cores, so there is no need to use many cpu cores
conf.set("spark.executor.cores", executorCores)
conf.set("spark.eventLog.enabled","true")

# Plugin settings
conf.set("spark.executor.resource.gpu.amount", "1")
conf.set("spark.rapids.sql.concurrentGpuTasks", concurrentGpuTasks)
conf.set("spark.rapids.memory.pinnedPool.size", pinnedPoolSize)
##############note: only support value=1 see https://github.com/dmlc/xgboost/blame/master/python-package/xgboost/spark/core.py#L370-L374
conf.set("spark.task.resource.gpu.amount", 1) 
# since pyspark and xgboost share the same GPU, we need to allocate some memory to xgboost to avoid GPU OOM while training 
conf.set("spark.rapids.memory.gpu.allocFraction","0.6")
conf.set("spark.rapids.sql.enabled", "true") 
conf.set("spark.executorEnv.NCCL_DEBUG","INFO")
conf.set("spark.plugins", "com.nvidia.spark.SQLPlugin")
conf.set("spark.sql.cache.serializer","com.nvidia.spark.ParquetCachedBatchSerializer")
conf.set("spark.sql.execution.arrow.maxRecordsPerBatch", 200000) 
conf.set("spark.driver.extraClassPath", RAPIDS_JAR)
conf.set("spark.executor.extraClassPath", RAPIDS_JAR)
conf.set("spark.jars", RAPIDS_JAR)
conf.set("spark.shuffle.manager","com.nvidia.spark.rapids.spark331.RapidsShuffleManager")
conf.set("spark.local.dir","/spark/sparkshuffle")
conf.set("spark.python.worker.reuse", "true") 
conf.set("spark.executor.extraJavaOptions", "-XX:ErrorFile=/tmp/debug.log") 
conf.set("spark.rapids.memory.gpu.pool","NONE") 
conf.set("spark.rapids.sql.batchSizeBytes","2147483647") 
conf.set("spark.rapids.sql.reader.batchSizeBytes", "2147483647")
conf.set("spark.rapids.memory.gpu.direct.storage.spill.enabled","true")

```

We are testing to disable GDS to see whether it related to GDS.

**Comment by wbo4958** [comment]
I found the Allreduce failed when creating the QuantileDMatrix

``` console

23/10/17 23:13:08 ERROR PythonRunner: Python worker exited unexpectedly (crashed)
org.apache.spark.api.python.PythonException: Traceback (most recent call last):
  File "/user/spark//spark-3.3.1-bin-hadoop3/python/lib/pyspark.zip/pyspark/worker.py", line 666, in main
    eval_type = read_int(infile)
  File "/user/spark//spark-3.3.1-bin-hadoop3/python/lib/pyspark.zip/pyspark/serializers.py", line 595, in read_int
    raise EOFError
EOFError

	at org.apache.spark.api.python.BasePythonRunner$ReaderIterator.handlePythonException(PythonRunner.scala:559)
	at org.apache.spark.api.python.PythonRunner$$anon$3.read(PythonRunner.scala:765)
	at org.apache.spark.api.python.PythonRunner$$anon$3.read(PythonRunner.scala:747)
	at org.apache.spark.api.python.BasePythonRunner$ReaderIterator.hasNext(PythonRunner.scala:512)
	at org.apache.spark.InterruptibleIterator.hasNext(InterruptibleIterator.scala:37)
	at scala.collection.Iterator.foreach(Iterator.scala:943)
	at scala.collection.Iterator.foreach$(Iterator.scala:943)
	at org.apache.spark.InterruptibleIterator.foreach(InterruptibleIterator.scala:28)
	at scala.collection.generic.Growable.$plus$plus$eq(Growable.scala:62)
	at scala.collection.generic.Growable.$plus$plus$eq$(Growable.scala:53)
	at scala.collection.mutable.ArrayBuffer.$plus$plus$eq(ArrayBuffer.scala:105)
	at scala.collection.mutable.ArrayBuffer.$plus$plus$eq(ArrayBuffer.scala:49)
	at scala.collection.TraversableOnce.to(TraversableOnce.scala:366)
	at scala.collection.TraversableOnce.to$(TraversableOnce.scala:364)
	at org.apache.spark.InterruptibleIterator.to(InterruptibleIterator.scala:28)
	at scala.collection.TraversableOnce.toBuffer(TraversableOnce.scala:358)
	at scala.collection.TraversableOnce.toBuffer$(TraversableOnce.scala:358)
	at org.apache.spark.InterruptibleIterator.toBuffer(InterruptibleIterator.scala:28)
	at scala.collection.TraversableOnce.toArray(TraversableOnce.scala:345)
	at scala.collection.TraversableOnce.toArray$(TraversableOnce.scala:339)
	at org.apache.spark.InterruptibleIterator.toArray(InterruptibleIterator.scala:28)
	at org.apache.spark.rdd.RDD.$anonfun$collect$2(RDD.scala:1021)
	at org.apache.spark.SparkContext.$anonfun$runJob$5(SparkContext.scala:2268)
	at org.apache.spark.scheduler.ResultTask.runTask(ResultTask.scala:90)
	at org.apache.spark.scheduler.Task.run(Task.scala:136)
	at org.apache.spark.executor.Executor$TaskRunner.$anonfun$run$3(Executor.scala:548)
	at org.apache.spark.util.Utils$.tryWithSafeFinally(Utils.scala:1504)
	at org.apache.spark.executor.Executor$TaskRunner.run(Executor.scala:551)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.lang.Thread.run(Thread.java:829)
Caused by: org.apache.spark.api.python.PythonException: Traceback (most recent call last):
  File "/user/spark//spark-3.3.1-bin-hadoop3/python/lib/pyspark.zip/pyspark/worker.py", line 686, in main
    process()
  File "/user/spark//spark-3.3.1-bin-hadoop3/python/lib/pyspark.zip/pyspark/worker.py", line 678, in process
    serializer.dump_stream(out_iter, outfile)
  File "/user/spark//spark-3.3.1-bin-hadoop3/python/lib/pyspark.zip/pyspark/sql/pandas/serializers.py", line 343, in dump_stream
    return ArrowStreamSerializer.dump_stream(self, init_stream_yield_batches(), stream)
  File "/user/spark//spark-3.3.1-bin-hadoop3/python/lib/pyspark.zip/pyspark/sql/pandas/serializers.py", line 84, in dump_stream
    for batch in iterator:
  File "/user/spark//spark-3.3.1-bin-hadoop3/python/lib/pyspark.zip/pyspark/sql/pandas/serializers.py", line 336, in init_stream_yield_batches
    for series in iterator:
  File "/user/spark//spark-3.3.1-bin-hadoop3/python/lib/pyspark.zip/pyspark/worker.py", line 413, in func
    for result_batch, result_type in result_iter:
  File "/usr/local/lib/python3.8/dist-packages/xgboost/spark/core.py", line 966, in _train_booster
    dtrain, dvalid = create_dmatrix_from_partitions(
  File "/usr/local/lib/python3.8/dist-packages/xgboost/spark/data.py", line 307, in create_dmatrix_from_partitions
    dtrain: DMatrix = make_qdm(train_data, dev_ordinal, meta, None, params)
  File "/usr/local/lib/python3.8/dist-packages/xgboost/spark/data.py", line 169, in make_qdm
    m = QuantileDMatrix(it, **params, ref=ref)
  File "/usr/local/lib/python3.8/dist-packages/xgboost/core.py", line 729, in inner_f
    return func(**kwargs)
  File "/usr/local/lib/python3.8/dist-packages/xgboost/core.py", line 1528, in __init__
    self._init(
  File "/usr/local/lib/python3.8/dist-packages/xgboost/core.py", line 1589, in _init
    _check_call(ret)
  File "/usr/local/lib/python3.8/dist-packages/xgboost/core.py", line 281, in _check_call
    raise XGBoostError(py_str(_LIB.XGBGetLastError()))
xgboost.core.XGBoostError: [23:13:08] /workspace/rabit/include/rabit/internal/utils.h:86: Allreduce failed
```

@trivialfis any idea about this failure?

**Comment by trivialfis** [comment]
No idea. I'm revamping the RABIT module at the moment. Currently, it's impossible to debug network error without diving into C++ code.

**Comment by sajadn** [comment]
any update on this? I'm seeing the same error.

**Comment by trivialfis** [comment]
That's likely caused by other errors and one of the workers died during the process, while other workers trying to communicate. It's difficult to explain it without knowing the original error.

**Comment by nvliyuan** [comment]
close this error since out of date
