### ISSUE TITLE
read data error

### ISSUE THREAD

**Issue by KobeDeShow** [dmlc/xgboost#99]
Hi ,tianqi
below are error  message..
Traceback (most recent call last):
  File "process.py", line 81, in <module>
    dtrain = xgb.DMatrix(trainXg, label=trainY)
  File "/data7/arvinjin/machine_learning_tools/xgboost-master/wrapper/xgboost.py", line 79, in **init**
    raise Exception("can not intialize DMatrix from"+str(type(data)))
Exception: can not intialize DMatrix from<type 'list'>
Exception AttributeError: "DMatrix instance has no attribute 'handle'" in <bound method DMatrix.__del__ of <xgboost.DMatrix instance at 0x7f494bc8db48>> ignored

trainXg is list type, like [[1,0.1,-999],[2,3,4],]

ths!

**Comment by StevenLOL** [comment]
Same error for scipy.sparse.csr.csr_matrix'
```
Traceback (most recent call last):
  File "....py", line 217, in <module>
    eval_set=[(evalx, evalyall)])
  File "/usr/local/lib/python2.7/dist-packages/xgboost-0.4-py2.7.egg/xgboost/sklearn.py", line 297, in fit
    missing=self.missing)
  File "/usr/local/lib/python2.7/dist-packages/xgboost-0.4-py2.7.egg/xgboost/core.py", line 167, in __init__
    raise TypeError('can not intialize DMatrix from {}'.format(type(data).__name__))
TypeError: can not intialize DMatrix from list
Exception AttributeError: "'DMatrix' object has no attribute 'handle'" in <bound method DMatrix.__del__ of <xgboost.core.DMatrix object at 0x7feb4304c850>> ignored

```
